src/webgl-overlay.js
src/webgl-renderer.js

Changes from @heshan0131
Fixes #1

fix rendering with devicePixelRatio

---

package.json

babel presets and react in devDependencies

---

.gitignore
src/layers/base-layer.js
src/layers/scatterplot-layer/index.js
src/webgl-overlay.js

use deep equal to compare whether data has changed. Check if radius has changed to recalculate radius

update layer when data changed also radius changed

---

src/flat-world.js
src/webgl-renderer.js

@gnavvy @ibgreen 
This magically fixed the picking issue with retina rendering. I also tested on regular display and it works. Anybody else want to test it?

fix picking on retina/regular display

---

src/flat-world.js

For issue #19.
@heshan0131 Can you experiment with this blendFunc and see if it works for your case and generally? If not we can try some other combinations or explore more advanced blending options.
@ibgreen @philogb

switch to blendFunc src_alpha, one_minus_src_alpha

---

example/main.js
src/layer.js
src/layers/grid-layer/grid-layer-vertex.glsl
src/layers/grid-layer/grid-layer.js

set grid opacity to 0 when no points in grid

Fix grid layer rendering, add selectedPickingColor to layer uniform

---

package.json

Bumping the react version for the dev branch

[Dev] Updating react deps to 15.0.2

---

example/main.js
src/layer.js
src/layers/arc-layer/arc-layer.js
src/layers/hexagon-layer/hexagon-layer.js

WebGL buffers were not updating when data changed.

Fix buffer updates and layer default props to avoid unnecessesary rerenders

---

src/webgl-renderer.js

right now you can't set your own

pass through style properties

---

package.json
src/index.js
src/layers/base-layer.js
src/layers/grid-layer/grid-layer.js
src/layers/hexagon-layer/hexagon-layer.js
src/layers/scatterplot-layer/scatterplot-layer.js
src/test-layers/test-layer.js
src/viewport/viewport.js
test/test-utils.js
test/viewport-spec.js

This is a breaking change, so will be merged into dev and published as beta3.0.0 release

Add test cases / fixes for Viewport project. Standardize on array format for lngLat and coordinates.

---

src/layer-manager.js
src/layers/arc-layer/arc-layer.js
src/layers/base-layer.js
src/layers/choropleth-layer/choropleth-layer.js
src/layers/grid-layer/grid-layer.js
src/layers/hexagon-layer/hexagon-layer.js
src/layers/line-layer/line-layer.js
src/layers/scatterplot-layer/scatterplot-layer.js

Cleans up layer definitions, makes it a little easier to create your own deck.gl layers
@gnavvy This will be merged to dev and published as a beta release for now.

Remove attribute definitions

---

src/layers/base-layer.js

Remove double default for opacity

---

src/layer-manager.js
test/index.js
test/layers-spec.js

More robust layerName debug helper.

Add layer construction test cases, including empty and null data. 

---

README.md
src/layers/base-layer.js

Instantiating any of these throws errors per https://github.com/uber/deck.gl/blob/master/src/layers/base-layer.js#L103

Document common required props

---

example/main.js

Remove no longer valid props in example arc layer. Fixes #43.

---

CHANGELOG.md
docs/performance.md
example/layer-examples.js
example/layer-selector.js
example/main.js
src/layers/core/scatterplot-layer/scatterplot-layer.js
src/viewport/viewport.js

@gnavvy @shaojingli Adds 1 million and 10 million point ScatterPlotLayers to the example.
@Pessimistress Adds initial performance doc

Add performance example and docs

---

example/layer-examples.js
package.json
src/layers/fp64/index.js
src/layers/fp64/scatterplot-layer/index.js
src/layers/fp64/scatterplot-layer/scatterplot-layer-fragment.glsl
src/layers/fp64/scatterplot-layer/scatterplot-layer-vertex.glsl
src/layers/fp64/scatterplot-layer/scatterplot-layer.js
src/layers/shaderlib/fp64/div-fp64.glsl
src/layers/shaderlib/fp64/exp-fp64.glsl
src/layers/shaderlib/fp64/log-fp64.glsl
src/layers/shaderlib/fp64/mat4-vec4-mul-fp64.glsl
src/layers/shaderlib/fp64/mul-fp64.glsl
src/layers/shaderlib/fp64/project-fp64.glsl
src/layers/shaderlib/fp64/radians-fp64.glsl
src/layers/shaderlib/fp64/sqrt-fp64.glsl
src/layers/shaderlib/fp64/sub-fp64.glsl
src/layers/shaderlib/fp64/sum-fp64.glsl
src/layers/shaderlib/fp64/utility.glsl
src/layers/shaderlib/fp64/vec4-dot-fp64.glsl
src/layers/shaderlib/fp64/vec4-fp64.glsl
src/layers/shaderlib/fp64/vec4-scalar-mul-fp64.glsl
src/layers/shaderlib/fp64/vec4-sum-fp64.glsl
src/react/deckgl-overlay.js

Please review. @gnavvy @ibgreen
This change requires luma.gl change to function properly.

Implemented the df64 floating point arithmetic for high precision layers

---

src/layers/shaderlib/fp64/cos-taylor-fp64.glsl
src/layers/shaderlib/fp64/nint-fp64.glsl
src/layers/shaderlib/fp64/sin-fp64.glsl
src/layers/shaderlib/fp64/sin-taylor-fp64.glsl
src/layers/shaderlib/fp64/sincos-taylor-fp64.glsl
src/layers/shaderlib/fp64/tan-fp64.glsl
src/test/shader.js
src/test/test_shader/vs_float_cos.glsl
src/test/test_shader/vs_float_sin.glsl
src/test/test_shader/vs_float_tan.glsl

Implemented three most common trigonometric functions for fp64 library. Please review @ibgreen, @gnavvy

Added sin_fp64(), cos_fp64() and tan_fp64() functions

---

package.json
shaderlib/project.glsl
src/layers/core/arc-layer/arc-layer.js
src/layers/core/choropleth-layer/choropleth-layer.js
src/layers/core/grid-layer/grid-layer.js
src/layers/core/hexagon-layer/hexagon-layer.js
src/layers/core/line-layer/line-layer.js
src/layers/core/scatterplot-layer/scatterplot-layer.js
src/layers/fp64/scatterplot-layer/scatterplot-layer.js

Use the fp64 version of log() function for Intel GPUs. I added a #ifdef to the custom shaders of all existing layers. Please review, test and verify that it fixes the offset issue.
@ibgreen @Pessimistress @abmai @twojtasz

Workaround for the inaccurate math functions of Intel GPUs

---

src/layers/core/choropleth-layer/choropleth-layer.js

- renders MultiPolygon and Polygon with holes
- add strokeWidth prop for drawContour: true mode
- add getColor accessor (default to use color property of the feature)
- use Uint32Array for indices when available to support larger feature sets
- throws error when vertex count exceeds UNSIGNED_SHORT limit
@ibgreen @gnavvy

Better geojson support in ChoroplethLayer

---

src/layers/core/choropleth-layer/choropleth-layer.js
src/layers/core/grid-layer/grid-layer-vertex.glsl
src/layers/core/grid-layer/grid-layer.js

Presumably broken by luma.gl API change.

Fix grid layer

---

docs/choropleth.md
example/layer-examples.js
react.js
src/lib/base-layer.js
src/viewport/viewport.js

@pessimistress @contra - pushing some loose branches that contain doc fragments. A ChoroplethLayer example in this case.

Add docs. Reorganize example, prioritize Core and 64-bit layers

---

shaderlib/fp64/cos-fp64.glsl
shaderlib/fp64/exp-fp64.glsl
shaderlib/fp64/log-fp64.glsl
shaderlib/fp64/sin-fp64.glsl
shaderlib/fp64/sincos-taylor-fp64.glsl
shaderlib/fp64/split.glsl
shaderlib/fp64/sqrt-fp64.glsl
shaderlib/fp64/tan-fp64.glsl
shaderlib/fp64/twoProd.glsl
shaderlib/fp64/twoSqr.glsl
shaderlib/fp64/twoSub.glsl
shaderlib/fp64/twoSum.glsl
src/layers/fp64/arc-layer/arc-layer-vertex.glsl
src/layers/fp64/scatterplot-layer/scatterplot-layer-vertex.glsl
src/layers/fp64/scatterplot-layer/scatterplot-layer.js
src/lib/base-layer.js
src/test/shader.js

Fixed flickering issue of 64-bit arc layer
Fixed the 64-bit tan() function returning incorrect value on Intel GPU on Windows
Other improvements of 64-bit shader library

Fixed the 64bit Arc Layer on Windows with Nvidia, Intel GPUs

---

example/layer-examples.js
shaderlib/project.glsl
shaderlib/projection/lib.glsl
src/layers/fp64/arc-layer/arc-layer-vertex.glsl
src/layers/fp64/choropleth-layer/choropleth-layer-fragment.glsl
src/layers/fp64/choropleth-layer/choropleth-layer-vertex.glsl
src/layers/fp64/choropleth-layer/choropleth-layer.js
src/layers/fp64/choropleth-layer/index.js
src/layers/fp64/index.js
src/shader-utils/assemble-shader.js
src/viewport/viewport.js

Added 64-bit choropleth layer.
Workaround for existing 32-bit layers to use tan_fp64() in new shaderAssembler scheme

Choropleth64

---

shaderlib/projection/lib.glsl

Implemented an accurate tan_fp32() function to replace the tan_fp64() used to substitute inaccurate tan() function from Intel GPU

Implemented an accurate tan_fp32() function for Intel GPU

---

CHANGELOG.md
shaderlib/pick/index.js
shaderlib/pick/picking.fragment.glsl
shaderlib/pick/picking.vertex.glsl
src/index.js
src/layers/core/arc-layer/arc-layer-vertex.glsl
src/layers/core/choropleth-layer/choropleth-layer-fragment.glsl
src/layers/core/choropleth-layer/choropleth-layer-vertex.glsl
src/layers/core/line-layer/line-layer-vertex.glsl
src/layers/core/screen-grid-layer/screen-grid-layer-vertex.glsl
src/layers/fp64/arc-layer/arc-layer-vertex.glsl
src/layers/fp64/line-layer/line-layer-vertex.glsl
src/lib/layer.js
src/lib/pick-models.js
src/test/lib/attribute-manager.spec.js

Fixes picking in most layers by ensuring that vertex shaders set opacity to 1 on picking colors.
Not quite sure how all layers ended up broken. @Pessimistress @Shaojingli @contra

Fixes to picking

---

CHANGELOG.md
docs/layers/scatterplot-layer.md
example/layer-examples.js
src/layers/core/scatterplot-layer/scatterplot-layer.js

Add outline to scatterplot in response to #55

Add outline to scatterplot

---

CHANGELOG.md
src/layers/core/screen-grid-layer/screen-grid-layer-vertex.glsl
src/layers/core/screen-grid-layer/screen-grid-layer.js

- Fix broken ScreenGridLayer on the deck.gl 3
- Add custom color ramp
- Add position and weight accessors

unbreak screen grid layer

---

docs/attribute-management.md
docs/custom-layers.md
docs/layer.md
package.json
src/layers/core/choropleth-layer/choropleth-layer.js
src/layers/fp64/choropleth-layer/choropleth-layer.js
src/layers/fp64/extruded-choropleth-layer/extruded-choropleth-layer.js
src/layers/samples/enhanced-choropleth-layer/enhanced-choropleth-layer.js
src/lib/layer-manager.js
src/lib/layer.js
src/lib/pick-layers.js
src/react/deckgl.js
src/shader-utils/assemble-shaders.js

@pessimistress should fix the beta26 issues you experienced.

Fixes to minor issues

---

package.json
src/lib/layer.js
src/lib/utils/compare-objects.js
src/lib/utils/compare-objects.spec.js
src/test/index.js

@shaojingli @Pessimistress @twojtasz

Add test cases for compare props and fixes identical case

---

docs/introduction.md
docs/using-layers.md

revision for the introduction and using-layers pages.
more pages to come later in this PR.

Doc revision

---

src/layers/core/choropleth-layer/choropleth-layer.js
src/layers/core/line-layer/line-layer.js
src/layers/core/scatterplot-layer/scatterplot-layer.js
src/layers/fp64/arc-layer/arc-layer.js
src/layers/fp64/choropleth-layer/choropleth-layer.js
src/layers/fp64/line-layer/line-layer.js
src/layers/fp64/scatterplot-layer/scatterplot-layer.js
src/layers/samples/enhanced-choropleth-layer/enhanced-choropleth-layer.js
src/lib/layer-manager.js
src/lib/layer.js
src/react/deckgl.js

Also enables prop diff tracing.

Fixes to lineWidth warning, context.viewport = null. opacity prop.

---

src/layers/core/arc-layer/arc-layer-vertex.glsl

By rendering more fine-grain near the ends:

Render nicer arcs with the same number of segments

---

src/layers/fp64/arc-layer/arc-layer-vertex.glsl

Ported #153 to 64-bit Arc layer.

Fine arc for 64-bit arc layer

---

demo/src/javascripts/components/home.js
demo/src/stylesheets/_home.scss
package.json

While we figure out if we want a live demo or video, this might come handy if we take the first solution.

Add fps counter to demo page

---

src/viewport/webgl-viewport.js

Make the 64-bit layers work again... by providing correct projection matrix. Solved issue #156

Fix the fp64 projection matrix

---

demo/src/javascripts/components/home.js
demo/src/javascripts/constants/pages.js
demo/src/stylesheets/_home.scss
docs/README.md
docs/getting-started.md
package.json
src/layers/fp64/extruded-choropleth-layer/extruded-choropleth-layer.js
src/layers/samples/geojson-layer/geojson-layer.js
src/lib/layer.js

- added link from the get started button to the get started page;
- simplified the text in the introduction page
- updated the getting-started page
* updated eslint to the latest version (2.* is not compatible with my editor, will revert if this causes any issue)

doc update

---

shaderlib/project/project.glsl

Removed the retired projectionMatrixUncentered uniform and make the projection shader working again in meters mode

Fix meters projection mode

---

src/layers/fp64/choropleth-layer/choropleth-layer.js

Make the attribute.value array matching the data type specified with attributeManager

Fix choropleth64 layer

---

CHANGELOG.md
demo/src/javascripts/components/header.js
demo/src/javascripts/components/home.js
demo/src/javascripts/constants/pages.js
demo/src/stylesheets/_home.scss
package.json
src/lib/layer.js

@pessimistress @gnavvy @apercu
Fine tuned the features text.
Reduced the margin for the title below the banner.
Moved the github link down to a button under the features, needs some more styling.

Homepage polish

---

src/layers/core/scatterplot-layer/scatterplot-layer-vertex.glsl
src/viewport/viewport.js

Addressing the comments in #178

Using gl-matrix function to do mat-vec multiplication.

---

shaderlib/project/project.glsl

Fixed z coordinate bug in the shader

Fix the z coord in shader

---

demo/src/static/index.html

- Add GA tracking for the demo/documentation
- Fix an issue where `<body>` was under the `<head>` tag for the demo's `index.html`

Add Google Analytics Tracking

---

demo/src/javascripts/components/demos/trips-layer/trips-layer-vertex.glsl
demo/src/stylesheets/_home.scss
demo/src/stylesheets/_mixins.scss
demo/src/stylesheets/main.scss

- Fix trips layer not rendering problem in some systems
- Disable text selection in header

Demo site bug fixes

---

demo/src/javascripts/components/demos/hero.js
demo/src/javascripts/components/demos/index.js
demo/src/javascripts/components/home.js
demo/src/javascripts/components/map.js
demo/src/javascripts/components/page.js
demo/src/javascripts/components/table-of-contents.js

- Consolidate data and viewport loading
- Reduce page serenader
- Fix bug where table of contents doesn't update on navigation
- Add an option in trips demo

Demo optimization

---

src/lib/layer.js

Fix a bug so that attribute data calculation is fired only when data has changed. #221

 Fix data update bug

---

shaderlib/fp64/math-fp64.glsl

Fix the precision problem it suffers in previous version

Changed the implementation of vec2_mix_fp64()

---

docs/using-with-react.md
src/react/deckgl.js

#224
let me know if we should rename some variables here to make it clearer

pass up original MouseEvent when calling onLayerClick and onLayerHover

---

src/test/index.js
src/test/lib/attribute-manager.spec.js
src/test/lib/index.js
src/test/lib/utils/compare-objects.spec.js
src/test/lib/utils/index.js

* Fix import bug in attribute-manager.spec.js
* Add attrubute manager to test
* Edit path of compare-object.spec.js

Add test code (attribute-manager)

---

docs/layers/arc-layer-64.md
docs/layers/arc-layer.md
docs/layers/line-layer-64.md
docs/layers/line-layer.md

LineLayer documentation was talking about arcs - this is the main thing that's fixed. Also slight improvements to the wording in ArcLayer and LineLayer descriptions.

Minor improvements to line and arc layer documentation.

---

examples/main/webpack.config.js
package.json
webpack.config.js
webpack.config.test-browser.js
yarn.lock

Breaking this out from #293 as it seems we need more time to discuss that PR

Webpack polish

---

docs/custom-layers.md
src/layers/core/arc-layer/arc-layer.js
src/layers/core/hexagon-layer/hexagon-layer.js
src/layers/core/icon-layer/icon-layer.js
src/layers/core/line-layer/line-layer.js
src/layers/core/screen-grid-layer/screen-grid-layer.js
src/layers/deprecated/choropleth-layer/choropleth-layer.js
src/layers/deprecated/extruded-choropleth-layer-64/extruded-choropleth-layer-64.js

Add default props to all layers

Update all layers to use new defaultProps mechanism. Add docs.

---

src/layers/deprecated/choropleth-layer/geojson.js
src/lib/layer.js
src/lib/utils/index.js
src/lib/utils/log.js
test/layers/geojson-layer.spec.js
test/lib/layer.spec.js
test/lib/utils/container.spec.js

Need to use hasOwnProperty when walking the constructor chain.

Fix to defaultProps handling

---

shaderlib/fp64/math-fp64.glsl
shaderlib/project64/project64.glsl
src/test/shader-tests/vs_float_radians.glsl
src/test/shader.js
src/test/vs_float_radians.glsl

Fix a bug in the project_fp64 that only shows up in linux + Nvidia;
Added unit test for radians_fp64;
@Pessimistress

Fix project_fp64 issue under linux + nvidia

---

src/shaderlib/fp64/math-fp64.glsl
src/shaderlib/project64/project64.glsl
src/test/shader-tests/vs_float_radians.glsl
src/test/vs_float_radians.glsl
test/fp64-test/fp64-shader.spec.js

Added unit test for radians_fp64
Cherrypick PR #315

Fix a bug in the project_fp64 that only shows up in linux + Nvidia; 

---

src/index.js
src/lib/utils/color.js
src/lib/utils/index.js
test/bench/index.js
test/lib/utils/color.spec.js
test/lib/utils/index.js

@gnavvy - this is an experimental color converter implementation based on our discussion. Benchmarking the color conversions in isolation looks good, although we need to integrate them into attribute updaters and measure the impact.

Simple parse colors implementation with benchmarking

---

examples/main/data-samples.js
examples/main/layer-examples.js
src/lib/utils/color.js
test/lib/utils/color.spec.js

use new geoJson file for testing

---

examples/main/layer-examples.js
package.json
src/index.js
src/layers/core/geojson-layer/geojson-layer.js
src/lib/utils/color.js

Fix point and multiPoint in geojson

---

.eslintrc
examples/main/app.js
examples/main/layer-examples.js
src/layers/core/arc-layer/arc-layer.js
src/layers/core/geojson-layer/geojson-layer.js
src/layers/core/grid-layer/grid-layer.js
src/layers/core/hexagon-layer/hexagon-layer.js
src/layers/core/icon-layer/icon-layer.js
src/layers/core/line-layer/line-layer.js
src/layers/core/path-layer/path-layer.js
src/layers/core/polygon-layer/polygon-layer.js
src/layers/core/scatterplot-layer/scatterplot-layer.js
src/layers/core/screen-grid-layer/screen-grid-layer.js
src/lib/attribute-manager.js
src/lib/layer.js
test/lib/attribute-manager.spec.js
test/lib/layer.spec.js

- allow accessor names as update trigger keys
- fix bug where undefined update trigger throws an error
- add accessor names to all core layer attributes
- add test cases

Allow accessor names as update trigger keys

---

demo/package.json
demo/src/components/demos/arc.js
demo/src/components/map.js
demo/webpack/prod.js

- Add build script
- Fix viewport flying
- Fix arc layer demo
@apercu

Fix demo build

---

demo/src/constants/pages.js
demo/webpack/dev.js

- rotate Mapbox token
- update doc links

Update docs in demo

---

CHANGELOG.md
demo/src/constants/pages.js
docs/v4.0/layers/point-cloud-layer.md
docs/v4.0/whats-new.md
examples/main/src/data-samples.js
examples/main/src/layer-examples.js
src/index.js
src/layers/core/point-cloud-layer/index.js
src/layers/core/point-cloud-layer/point-cloud-layer-fragment.glsl
src/layers/core/point-cloud-layer/point-cloud-layer-vertex.glsl
src/layers/core/point-cloud-layer/point-cloud-layer.js
test/layers/core-layers.spec.js

- add PointCloudLayer, renders LiDAR data with `position` `normal` and `color` properties
- add doc
- replace scatterplot (meter) example with point cloud (meter) example

Add PointCloudLayer

---

demo/src/constants/pages.js
docs/viewports.md

Viewport docs

---

API-GUIDELINES.md

Publishing initial version of API guidelines, to increase transparency of the deck.gl API Audit process. @shaojingli

Api guidelines

---

docs/custom-layers.md

@shaojingli Slightly improved introduction.

Clean up doc

---

src/index.js
src/layers/core/geojson-layer/geojson-layer.js
src/lib/composite-layer.js
src/lib/index.js
test/layers/hexagon-layer.spec.js

Composite layer

---

CHANGELOG.md
demo/src/components/demos/plot.js
docs/layer-lifecycle.md
docs/upgrade-guide.md
docs/whats-new.md
examples/sample-layers/plot-layer/plot-layer.js
examples/sample-layers/plot-layer/surface-layer.js
package.json
src/layers/core/geojson-layer/geojson-layer.js
src/lib/composite-layer.js
src/lib/draw-and-pick.js
src/lib/layer-manager.js
src/lib/layer.js
src/react/deckgl.js

- `onHover` is only called upon enter/leave
- `onClick` is only called on the picked layer

Only invoke mouse event on affected layers

---

src/layers/core/polygon-layer/polygon-tesselator-extruded.js

A one liner to fix a typo that breaks the 64-bit extruded polygon layer

Fix a bug that breaks the 64-bit extruded polygon layer

---

src/layers/core/arc-layer/arc-layer.js
src/layers/core/grid-layer/grid-layer-64-vertex.glsl
src/layers/core/grid-layer/grid-layer.js
src/layers/core/grid-layer/picking.glsl
src/layers/core/hexagon-layer/hexagon-layer-64-vertex.glsl
src/layers/core/hexagon-layer/hexagon-layer.js
src/layers/core/hexagon-layer/picking.glsl
src/layers/core/icon-layer/icon-layer-64-vertex.glsl
src/layers/core/icon-layer/icon-layer.js
src/layers/core/line-layer/line-layer.js
src/layers/core/point-density-grid-layer/point-density-grid-layer.js
src/layers/core/point-density-hexagon-layer/point-density-hexagon-layer.js
src/layers/core/polygon-layer/polygon-layer.js
src/layers/core/scatterplot-layer/scatterplot-layer-64-vertex.glsl
src/layers/core/scatterplot-layer/scatterplot-layer.js

More 64-bit layers coming!
64-bit IconLayer, HexagonLayer, GridLayer, PointDensityHexagonLayer, PointDensityGridLayer added

More 64-bit layers

---

src/layers/core/arc-layer/arc-layer.js
src/layers/core/geojson-layer/geojson-layer.js
src/layers/core/grid-layer/grid-layer.js
src/layers/core/hexagon-layer/hexagon-layer.js
src/layers/core/icon-layer/icon-layer.js
src/layers/core/line-layer/line-layer.js
src/layers/core/path-layer/path-layer.js
src/layers/core/point-cloud-layer/point-cloud-layer-64-vertex.glsl
src/layers/core/point-cloud-layer/point-cloud-layer.js
src/layers/core/point-density-grid-layer/point-density-grid-layer.js
src/layers/core/point-density-hexagon-layer/point-density-hexagon-layer.js
src/layers/core/polygon-layer/polygon-layer.js
src/layers/core/scatterplot-layer/scatterplot-layer.js
src/lib/layer.js
src/shaderlib/fp64/math-fp64.glsl

Add 64-bit point cloud layer.
Make the fp64 a prop available for all layers
Add a check so that the fp64 prop is only effective when projectionMode is set to 1.

64bit point cloud layer

---

docs/layers/point-density-hexagon-layer.md
examples/main/src/layer-examples.js
src/layers/core/hexagon-layer/hexagon-layer-vertex.glsl
src/layers/core/hexagon-layer/hexagon-layer.js
src/layers/core/point-density-grid-layer/point-density-grid-layer.js
src/layers/core/point-density-hexagon-layer/point-density-hexagon-layer.js
src/utils/scale-utils.js
src/utils/sorted-bins.js

* added upperPercentile and lowerPercentile to hexagon layer
* Add to layer doc
* add clamp to scale

Add percentile filter to point density hexagon layer

---

demo/src/constants/pages.js
demo/webpack/config.js
docs/whats-new.md

Doc highlight

---

demo/src/constants/pages.js
demo/webpack/config.js
docs/whats-new.md

Rebase #407 on master and integrate

Reintegrate #407 Doc highlight

---

docs/64-bits.md
docs/attribute-management.md
docs/custom-layers.md
docs/layer-lifecycle.md
docs/performance.md
docs/tips-and-tricks.md
docs/upgrade-guide.md
docs/whats-new.md
src/layers/core/path-layer/path-layer.js

A round of update for the docs.

Docs update

---

src/layers/core/path-layer/path-layer-64-vertex.glsl

Update the 64-bit PathLayer according to API audit

Update the 64-bit PathLayer with new uniform names

---

src/layers/core/solid-polygon-layer/solid-polygon-layer.js

A leftover from previous changes...

Change the default name of SolidPolygonLayer

---

src/layers/core/scatterplot-layer/scatterplot-layer.js

Add super.updateState() to the scatterplot layer

---

demo/package.json
demo/webpack/config.js
examples/layer-browser/webpack.config.js
examples/webpack.config.local.js

resume brfs and transform-loader for examples / demo depending on mapbox-gl

fix brfs regressions

---

examples/layer-browser/src/examples/core-layers.js
src/layers/core/solid-polygon-layer/polygon-tesselator-extruded.js

@ibgreen @Pessimistress @gnavvy

Fix the position generation for extruded polygons with holes

---

CHANGELOG.md
examples/layer-browser/src/data-samples.js
examples/layer-browser/src/examples/core-layers.js
src/layers/core/point-cloud-layer/point-cloud-layer-vertex.glsl.js
src/layers/core/point-cloud-layer/point-cloud-layer.js

- Use `radiusPixels` instead of `radius` in rendering
- Better data sample in layer browser

Fix PointCloudLayer bug where radiusPixels is not working

---

docs/layers/grid-layer.md
docs/layers/hexagon-layer.md
src/layers/core/arc-layer/arc-layer.js
src/layers/core/grid-cell-layer/grid-cell-layer.js
src/layers/core/hexagon-cell-layer/hexagon-cell-layer.js
src/layers/core/icon-layer/icon-layer.js
src/layers/core/line-layer/line-layer.js
src/layers/core/path-layer/path-layer.js
src/layers/core/point-cloud-layer/point-cloud-layer-vertex-64.glsl.js
src/layers/core/point-cloud-layer/point-cloud-layer.js
src/layers/core/scatterplot-layer/scatterplot-layer.js
src/layers/core/solid-polygon-layer/solid-polygon-layer.js
src/lib/layer.js
src/lib/utils/fp64.js

bug fixes for typos (COORDINATE_SYSTEM.**LNG_LAT**, instead of COORDINATE_SYSTEM.**LNGLAT**) and raidusPixels for vertex-64 shader of the point-cloud-layer.

fix projectionMode checks and radiusPixels for point-cloud-layer-64

---

src/layers/core/geojson-layer/geojson-layer.js
src/layers/core/grid-layer/grid-layer.js
src/layers/core/hexagon-layer/hexagon-layer.js
src/layers/core/polygon-layer/polygon-layer.js

Transfer positionOffset and modelMatrix props properly to their underlying layers
@Pessimistress @ibgreen

Composite layer to transfer positionOffset and modelMatrix

---

src/lib/draw-and-pick.js

@Pessimistress 
please take a look and see if I understand your request correctly
@ibgreen

Fix the bug that layers got updated in the middle of the picking cycle

---

src/layers/core/hexagon-layer/hexagon-layer.js

Fix the coverage prop for Hexagon layer

---

CHANGELOG.md
docs/layer-lifecycle.md
package.json
src/lib/draw-and-pick.js

Addressing [Issue #466](https://github.com/uber/deck.gl/issues/466)

Expose sourceLayer to getPickingInfo()

---

examples/layer-browser/src/examples/sample-layers.js

Remove TripsLayer in LayerBrowser

---

demo/src/components/demos/geojson.js

Let's see of this actually solves the low frame rate problem for 2014 Macbook Pro. 
@Pessimistress @philogb

Turning off the outline for GeoJson layer demo

---

demo/package.json
demo/src/components/input.js
demo/src/components/markdown-page.js
demo/webpack/config.js

- Upgrade react-map-gl to 3.0.0 to avoid importing mapbox files
- Fix mapbox runtime error
@apercu

Fix demo build problems with mapbox

---

CHANGELOG.md
src/layers/core/geojson-layer/geojson-layer.js
src/layers/core/grid-layer/grid-layer.js
src/layers/core/hexagon-layer/hexagon-layer.js

Need to add this default value otherwise the default light settings of composite layers won't work properly
@ibgreen

Default light settings in the defaultProps

---

_posts/2017-03-31-introducing-deckgl-v4.md

add interoperability section

---

demo/src/components/markdown-page.js
demo/src/components/page.js
demo/src/constants/pages.js

- Generic url rewrite
- Support in-page jump links

Fix internal links in demo>documentation

---

demo/src/components/demos/geojson-demo.js
demo/src/components/demos/heatmap-demo.js
demo/src/components/demos/icon-demo.js
demo/src/components/demos/line-demo.js
demo/src/components/demos/plot-demo.js
demo/src/components/demos/scatterplot-demo.js
demo/src/components/demos/screen-grid-demo.js
demo/src/components/demos/trips-demo.js

Update the label text for our demo examples

Clean up the texts of examples on demo site

---

src/lib/viewports/viewport.js
src/lib/viewports/web-mercator-viewport.js
test/lib/test-utils/index.js
test/lib/viewports/index.js
test/lib/viewports/mercator-project-unproject.spec.js
test/lib/viewports/viewport.spec.js
test/lib/viewports/web-mercator-project-unproject.spec.js
test/lib/viewports/web-mercator-viewport.spec.js

Fix viewport

---

docs/get-started/getting-started.md
docs/get-started/using-with-mapbox-gl.md
docs/get-started/using-with-react.md

Doc shaojing3

---

docs/get-started/getting-started.md
docs/get-started/using-with-react.md

- Remove inline comments inside jsx
- Remove unnecessary code

Fix getting started sample code

---

demo/src/constants/pages.js
docs/advanced/layer-lifecycle.md
docs/advanced/picking.md
docs/advanced/primitive-layers.md
docs/advanced/using-standalone.md
docs/advanced/writing-shaders.md
docs/api-reference/attribute-manager.md
docs/api-reference/base-layer.md
docs/api-reference/composite-layer.md
docs/api-reference/deckgl.md
docs/api-reference/layer-manager.md
docs/api-reference/orthographic-viewport.md
docs/api-reference/perspective-viewport.md
docs/api-reference/viewport.md
docs/api-reference/web-mercator-viewport.md
docs/get-started/using-layers.md

- Make API docs the single source of truth
- Update outdated content
- Formatting consistency

API Doc Improvements

---

demo/src/components/blog.js

Handle iframe redirection and browser back button correctly

More robust navigation in blog

---

_data/authors.yml
_posts/2017-03-31-introducing-deckgl-v4.md

Now that I've touched the blog, I can add my name to authors :)

Copy / grammar corrections.

---

demo/src/components/map.js
demo/src/routes.js

- redirect unknown route to section index page instead of home 
- only show map rotation tip if applicable

Misc bug fixes for demo site

---

demo/src/components/map.js
demo/yarn.lock
examples/layer-browser/yarn.lock

Reverts demo to react-map-gl v2 for now

---

src/lib/constants.js
src/lib/layer-manager.js
src/lib/layer.js

Check `layer.lifecycle` instead of `layer.state`

Fix finalization bug

---

src/layers/core/solid-polygon-layer/polygon-tesselator-extruded.js

Replace spread operator on array for performance reasons

---

CHANGELOG.md
src/layers/core/hexagon-layer/hexagon-layer.js

- Add `getHexagons` and `getSortedCounts` methods

Add Hexagon layer methods

---

examples/hello-world-webpack2/README.md

This would fix #568.
Doc corrected according to @Apercu

Updating doc according to browserify's

---

src/controllers/orbit-controller.js

Remove JSX from lib/controllers

---

examples/brushing/app.js

For [issue/600](https://github.com/uber/deck.gl/issues/600)

Fix brushing layer demo

---

.travis.yml
package.json
src/layers/core/grid-layer/grid-aggregator.js
src/layers/core/hexagon-cell-layer/hexagon-cell-layer.js
test/browser.js
test/experimental/lib/effect-manager.spec.js
test/index.js
test/layers/core-layers.spec.js
test/layers/geojson-layer.spec.js
test/layers/grid-cell-layer.spec.js
test/layers/grid-layer.spec.js
test/layers/hexagon-cell-layer.spec.js
test/layers/hexagon-layer.spec.js
test/layers/polygon-layer.spec.js
test/node.js
test/setup-gl.js
test/setup-jsdom-env.js
test/setup.js
test/test-utils.js

-  Add layer test utils for base layer test, using jsDom and sinon
- Disable some grid / hexagon layer test for now
- Coverage increase to 68%

Layer tests

---

src/layers/core/solid-polygon-layer/polygon-tesselator-extruded.js
src/lib/layer.js
test/bench/index.js

by replacing the naive math with bit-wise operations

Optimize encodePickingColor 

---

src/utils/events/wheel-input.js

Named import, not default.

---

src/react/deckgl.js
src/utils/events/event-manager.js

- Merge changes from react-map-gl
- Fix gl error when dragging outside of the canvas
- Fix drag events registration

Event handling bug fixes

---

examples/layer-browser/package.json
examples/webpack.config.local.js
package.json

@1chandu This will help with debugging #683

Bump luma.gl version and add source map support in example

---

package.json

Fix deck.gl after #684 @ibgreen

Add source-map-loader to as a dev dependency

---

src/utils/events/event-manager.js
src/utils/events/move-input.js
src/utils/events/wheel-input.js
yarn.lock

Add missing devDep.
Note that tests are failing, apparently due to a transpilation error, so this PR probably won't pass CI.

Simplify activation of WheelInput and MoveInput.

---

docs/layers/icon-layer.md

It was importing ArcLayer instead of IconLayer
Updated against master

Updated icon-layer.md

---

demo/package.json

https://github.com/uber/deck.gl/issues/691

Transpile demo workers to es5

---

src/layers/core/path-layer/path-layer-vertex-64.glsl.js

This is a fix to the 64-bit PathLayer. The original `lineJoin` function in the 64-bit vertex shader actually uses 32-bit positions. This make the center vertices of 64-bit PathLayer accurate but not the vertices extending in the lateral direction.
The fix solves this by using 64-bit floating point numbers for currPosition, prevPosition and nextPosition to do `lineJoin`

Fix 64-bit PathLayer

---

src/react/deckgl.js
src/utils/events/constants.js
src/utils/events/event-manager.js
src/utils/events/move-input.js
src/utils/events/wheel-input.js
test/utils/event-manager.spec.js
test/utils/move-input.spec.js
test/utils/wheel-input.spec.js

- Consistent `event` object: https://github.com/uber/deck.gl/issues/703
- Do not call `preventDefault` on wheel input
- Simplify emit chain

EventManager consistency and bug fixes

---

examples/trips/trips-layer/trips-layer.js

Fix the trip layer example
https://github.com/uber/luma.gl/issues/221

fix the trips layer example

---

examples/arc/deckgl-overlay.js
examples/brushing/deckgl-overlay.js
examples/geojson/deckgl-overlay.js
examples/layer-browser/src/app.js
examples/line/deckgl-overlay.js
examples/plot/deckgl-overlay.js
examples/point-cloud-laz/app.js
examples/point-cloud-ply/app.js
examples/sample-layers/mesh-layer/mesh-layer.js
examples/trips/deckgl-overlay.js
examples/trips/trips-layer/trips-layer.js
src/layers/core/screen-grid-layer/screen-grid-layer.js
src/lib/draw-and-pick.js
src/lib/layer.js
src/react/deckgl.js
src/react/webgl-renderer.js
test/fp64-test/fp64-shader.spec.js
website/src/components/demos/layer-demo-base.js

- Changing gl.*** calls into setParameters
- Use withParameters for temporarily setting state for specific draws (draw-and-pick.js)
- Tested with:  'run test, run test-browser (3 errors, not new), examples/layer-browser and all website examples'.

Adopt to new luma state managment api

---

src/layers/core/path-layer/path-layer-vertex-64.glsl.js

The end cap of path layer is unstable in 64-bit mode
@ibgreen @Pessimistress

Fix the fluctuation of the end cap for path layer 64bit

---

src/lib/draw-and-pick.js

@Pessimistress Could you try this branch to see if the performance regression is still there?
#769

Remove a redundant withParameters call in draw-and-pick

---

src/layers/core/screen-grid-layer/screen-grid-layer.js
src/lib/draw-and-pick.js
src/lib/layer.js

Consistent with luma.gl beta.4

Rename settings to parameters

---

examples/plot/plot-layer/axes-layer.js
examples/plot/plot-layer/surface-layer.js
examples/sample-layers/bitmap-layer/bitmap-layer.js
examples/sample-layers/enhanced-choropleth-layer/enhanced-choropleth-layer.js
examples/sample-layers/mesh-layer/mesh-layer.js
examples/trips/trips-layer/trips-layer.js
package.json
src/layers/deprecated/choropleth-layer/choropleth-layer.js
src/shaderlib/index.js

Note: Requires luma.gl's #266.

Add `project` as a default shader module.

---

CHANGELOG.md
src/layers/core/grid-cell-layer/grid-cell-layer.js

- Add update cellSize back to draw()

fix grid cell layer cellSize uniform

---

docs/layers/geojson-layer.md
docs/layers/scatterplot-layer.md
src/layers/core/geojson-layer/geojson-layer.js
src/layers/core/scatterplot-layer/scatterplot-layer.js

@Pessimistress as we discussed yesterday.

Add the missing radius mix/max and scale control for GeoJSON layer

---

examples/wind/package.json

Update the dependencies of the wind demo

---

examples/wind/src/layers/delaunay-interpolation/delaunay-interpolation.js
examples/wind/src/layers/particle-layer/particle-layer.js
examples/wind/src/layers/wind-layer/wind-layer.js

- Remove lot of redundant/unused props in texture creation path.

Wind: cleanup of texture creation code

---

website/src/components/demos/brushing-demo.js
website/src/components/demos/plot-demo.js
website/src/components/header.js
website/src/components/info-panel.js
website/src/components/map.js
website/src/components/page.js
website/src/stylesheets/_gallery.scss
website/src/stylesheets/main.scss

For 4.1-release
- Consistent header styling with other frameworks
- Fix bug where scrolling is disabled over home demo
- Fix mobile interaction

Website Styling

---

docs/README.md
docs/advanced/primitive-layers.md
docs/api-reference/attribute-manager.md
docs/api-reference/base-layer.md
docs/api-reference/composite-layer.md
docs/api-reference/deckgl.md
docs/api-reference/layer-manager.md
docs/api-reference/orthographic-viewport.md
docs/api-reference/perspective-viewport.md
docs/api-reference/viewport.md
docs/api-reference/web-mercator-viewport.md
docs/whats-new.md
website/contents/pages.js

For 4.1-release
Release date change and make hyperlink of examples pointing to 4.1-release branch

Website update

---

src/controllers/map-controller/map-controls.js
website/src/components/map.js

For 4.1-release
Identical to https://github.com/uber/react-map-gl/pull/332
- Remove hack from website code

Interaction bug fixes for MapController

---

examples/wind/package.json
examples/wind/src/layers/delaunay-cover-layer/delaunay-cover-layer.js
examples/wind/src/layers/particle-layer/particle-layer-fragment.glsl.js
examples/wind/src/layers/particle-layer/particle-layer-vertex.glsl.js
examples/wind/src/layers/particle-layer/particle-layer.js
examples/wind/src/layers/wind-layer/wind-layer-fragment.js
examples/wind/src/layers/wind-layer/wind-layer-vertex.js
examples/wind/src/layers/wind-layer/wind-layer.js
examples/wind/src/utils/load-data.js
examples/wind/src/wind-demo.js

- Use `delaunay-cover-layer` for elevation.
- Fix bounding box and triangulation.
(Note: this is functionally not equal to http://philogb.github.io/page/wind/ yet)

Fix elevation and bounding box.

---

src/controls/events/event-manager.js

Related to https://github.com/uber/react-map-gl/pull/348/files

Add missing set() mock

---

docs/api-reference/composite-layer.md
docs/api-reference/first-person-viewport.md
docs/api-reference/orthographic-viewport.md
docs/api-reference/perspective-viewport.md
docs/api-reference/third-person-viewport.md
docs/api-reference/viewport.md
docs/api-reference/web-mercator-viewport.md
src/index.js
src/math/utils.js
src/viewport-mercator-project/web-mercator-utils.js
src/viewports/first-person-viewport.js
src/viewports/perspective-viewport.js
src/viewports/third-person-viewport.js
src/viewports/viewport.js
src/viewports/web-mercator-viewport.js

Implementation, as outlined in the RFC.
NOTE: I'm making some changes that are likely to (temporarily) break backwards compatibility, so I am merging this into 4.2-dev instead of master for now.

Viewport class hierarchy refactor. Doc updates.

---

docs/api-reference/event-manager.md
src/controls/events/event-manager.js
src/controls/events/key-input.js
src/controls/generic-controls.js
src/controls/map-controls/map-state.js

This is a somewhat hacky implementation of keyboard event handling - I did not have time to figure out how to do it in the hammer way.
Also started documenting the event manager. The doc still needs a table describing what events and gestures it support.
I will land this into my 4.2-dev working branch now, but I will address any comments in the working branch before merging to master.

Keyboard event handling

---

examples/wind/src/layers/wind-layer/wind-layer.js
examples/wind/src/wind-demo.js

- Fix a typo in setting depth test, fixes depth issues in wind layer.
- Use non-debug gl context, fixes performance issues.

Minor wind demo fixes

---

src/controls/events/constants.js
src/controls/events/event-manager.js
src/controls/events/key-input.js
src/controls/events/move-input.js
src/controls/events/wheel-input.js
src/controls/generic-controls.js
test/utils/index.js
test/utils/key-input.spec.js
test/utils/move-input.spec.js
test/utils/wheel-input.spec.js

- Add `pointerleave` event (https://github.com/uber/deck.gl/issues/847)
- General code consistency
- Tests

EventManager Improvements

---

examples/layer-browser/src/examples/sample-layers.js
examples/sample-layers/s2-layer/s2-layer.js

Fix S2Layer base class and props.

---

examples/layer-browser/src/examples/sample-layers.js

Followup fix for #869, fixes fill color.
Output is confirmed by @urosi2453

Fix S2Layer fill color

---

docs/api-reference/event-manager.md
src/controls/events/constants-hammer.js
src/controls/events/constants.js
src/controls/events/event-manager.js
src/controls/events/key-input.js
src/controls/events/move-input.js
src/controls/events/wheel-input.js

- Update EventManager docs
- Centralize constants into constants.js
- Move constants that need to be conditionally required into their own file, to avoid conditional requires where possible

EventManager docs + cleanup

---

examples/text-layer/text-layer/multi-icon-layer/multi-icon-layer-vertex-64.glsl.js
src/layers/core/icon-layer/icon-layer-vertex-64.glsl.js

As suggested by @shaojingli here #872:
use `sin()` instead of `sqrt(...)` to fix the issue of always generating positive values.

Fix sin calculation using sin()

---

CHANGELOG.md
docs/advanced/subclassed-layers.md
docs/advanced/tips-and-tricks.md
docs/api-reference/base-layer.md
docs/layers/hexagon-cell-layer.md
docs/whats-new.md
examples/brushing/arc-brushing-layer/arc-brushing-layer.js
examples/brushing/deckgl-overlay.js
examples/brushing/scatterplot-brushing-layer/scatterplot-brushing-layer.js
examples/layer-browser/src/examples/core-layers.js
examples/layer-browser/src/examples/sample-layers.js
examples/sample-layers/s2-layer/s2-layer.js
package.json
src/layers/core/geojson-layer/geojson-layer.js
src/layers/core/grid-layer/grid-aggregator.js
src/layers/core/screen-grid-layer/screen-grid-layer.js
src/lib/draw-and-pick.js

4.1 release patch

---

src/controllers/events/move-input.js
src/lib/draw-and-pick.js
src/lib/layer-manager.js

https://github.com/uber/deck.gl/issues/847

Clear hovered object when pointer leaves the canvas

---

docs/layers/path-layer.md
docs/whats-new.md
src/layers/core/path-layer/path-layer-fragment.glsl.js
src/layers/core/path-layer/path-layer-vertex-64.glsl.js
src/layers/core/path-layer/path-layer-vertex.glsl.js
src/layers/core/path-layer/path-layer.js

Support dashed line in PathLayer

---

dev-docs/RFCs/v5.0/break-out-math-module-rfc.md
dev-docs/RFCs/v5.0/controller-architecture-rfc.md
docs/api-reference/composite-layer.md
package.json
src/experimental/react/deckgl-multiview.js
src/experimental/react/viewport-layout.js

Adds retina support to multi viewport and includes some other minor updates from the first-person-viewport branch, mainly to reduce the size of that PR and focus that review on the changes that matter.

Multiview updates and doc polish

---

docs/advanced/writing-shaders.md
docs/shader-modules/lighting.md
docs/shader-modules/project.md
docs/shader-modules/project64.md
docs/whats-new.md
src/shaderlib/lighting/lighting.glsl.js
src/shaderlib/project/project-deprecated.glsl.js
src/shaderlib/project/project.glsl.js
src/shaderlib/project/project.js
src/shaderlib/project/viewport-uniforms.js
src/shaderlib/project64/project64.glsl.js
src/shaderlib/project64/project64.js
website/contents/pages.js

Major overhaul of shader module docs and code.

Update project shader module to follow shadertools conventions

---

docs/api-reference/first-person-viewport.md
docs/api-reference/orthographic-viewport.md
docs/api-reference/perspective-viewport.md
docs/api-reference/third-person-viewport.md
docs/api-reference/viewport.md

Separating docs and code update to keep PRs reasonable in size

Geospatially enabled Viewport docs

---

examples/point-cloud-laz/app.js
examples/point-cloud-ply/app.js

- move data from my personal repo to the deck.gl-data repo (solves CORS)
- minor refactoring and auto-format by prettier

fix point cloud examples cors issue

---

docs/api-reference/layer-manager.md
src/lib/layer-manager.js
test/layers/core-layers.spec.js
test/lib/index.js
test/lib/layer-manager.spec.js
test/test-utils/setup-gl.js

* Updates `LayerManager` docs
* Adds `LayerManager` test cases.
* Fixes #920

Handle recursive layer ids. Update LayerManager docs and tests. 

---

examples/wind/src/wind-demo.js

use default: useDevicePixelRatio = false

fix wind-demo offset

---

docs/layers/grid-cell-layer.md
docs/layers/scatterplot-layer.md
docs/layers/solid-polygon-layer.md

Fixes #906 and some other missing props.

Update docs with missing layer props.

---

dev-docs/RFCs/vNext/composite-layer-customization-rfc.md
dev-docs/RFCs/vNext/layer-shader-customization.md
examples/layer-browser/src/app.js
examples/layer-browser/src/examples/index.js
examples/layer-browser/src/examples/sample-layers.js
examples/sample-layers/s2-layer/s2-layer.js
examples/sample-layers/segment-layer/path-layer-fragment.glsl.js
examples/sample-layers/segment-layer/path-layer-vertex-64.glsl.js
examples/sample-layers/segment-layer/path-layer-vertex.glsl.js
examples/sample-layers/segment-layer/segment-layer.js
examples/sample-layers/shaderlib/outline/outline.js
examples/sample-layers/shaderlib/outline/outline.md

SegmentLayer - a Path layer that uses a shadow buffer to create outlines between paths at different heights

---

examples/layer-browser/src/app.js

Also fixes separation slider for non METER_OFFSET layers

Retina option in layer browser

---

examples/layer-browser/src/app.js
src/core/shaderlib/project/project.glsl.js

Fix separation controls

---

examples/plot/app.js
src/core/index.js
src/core/lib/draw-layers.js
src/core/lib/layer-manager.js
src/core/lib/layer.js
src/core/lib/pick-layers.js
src/core/lib/seer-integration.js
src/index.js

https://github.com/uber/deck.gl/issues/991

Multi model fixes, OrbitController fix in plot layer

---

examples/layer-browser/package.json
examples/layer-browser/src/data-samples.js
examples/layer-browser/src/examples/core-layers.js
package.json
src/core/lib/draw-layers.js
yarn.lock

Make sure blending modes are correctly overridden, use correct parameters when rendering.

Fixes to drawlayers

---

src/core-layers/point-cloud-layer/point-cloud-layer-vertex-64.glsl.js

Reproduced issue in #903 and fix it here.

Fix point missing issue for 64 bits point cloud layer vertex shader

---

README.md

Asking users to use the release branch and developers to use the master branch

Change the README.md

---

examples/point-cloud-laz/app.js
examples/point-cloud-ply/app.js

forgot to pick these changes for v4.1-release after fixing in master last time.

fix point cloud data paths

---

examples/plot/plot-layer/axes-layer.js
examples/plot/plot-layer/surface-layer.js
examples/plot/plot-layer/utils.js
src/core-layers/arc-layer/arc-layer.js
src/core-layers/icon-layer/icon-layer.js
src/core-layers/line-layer/line-layer.js
src/core-layers/point-cloud-layer/point-cloud-layer.js
src/core-layers/scatterplot-layer/scatterplot-layer.js
src/core-layers/screen-grid-layer/screen-grid-layer.js
src/core-layers/solid-polygon-layer/solid-polygon-layer.js

Remove console warnings about inline attributes

Upgrade layers to new luma.gl API

---

examples/wip/first-person-map/app.js
src/core/viewports/first-person-viewport.js
src/core/viewports/third-person-viewport.js

First attempt on adding the 3rd person viewport support.
Now testing in the examples/wip/first-person-map (I know, will add a separate example later)

Add 3rd person viewport support

---

examples/plot/plot-layer/plot-layer.js
examples/plot/plot-layer/surface-layer.js

Fix problem where the axes are rendered until mouse interaction.

Fix plot layer state bug

---

examples/wip/viewport-animation-3d-heatmap/app.js
examples/wip/viewport-animation-geojson/app.js
examples/wip/viewport-animation/src/app.js
src/react/experimental/transition-manager.js
src/react/experimental/viewport-transition-utils.js

Addressing remaining review comments from #1038 
Verified with all three viewport-transition examples.

ViewportTransition minor fixes

---

src/core/lib/layer-manager.js

More details : #1069 
Fixes #1069
Related to #1043
Verified with `first-person-map` and `layer-browser` examples.

Fix layer context update

---

src/core/controllers/map-state.js

Verified with layer-browser example

Fix MapState constraints check

---

docs/api-reference/layer-manager.md
src/core/lib/draw-layers.js
src/core/lib/layer-manager.js
src/core/pure-js/deck-js.js
src/core/viewports/viewport.js
src/react/deckgl.js
test/src/core/experimental/lib/effect-manager.spec.js
test/src/core/lib/layer-manager.spec.js
test/test-utils/layer-utils.js

Needs to address comments in #1078

4.2-dev: Solidify viewport descriptor (aka `View`) support 

---

docs/api-reference/layer-manager.md
src/core/lib/attribute-manager.js
src/core/lib/composite-layer.js
src/core/lib/draw-layers.js
src/core/lib/layer-manager.js
src/core/lib/layer.js
src/core/lib/props.js
src/core/pure-js/deck-js.js
src/core/utils/log.js
src/core/viewports/viewport.js
src/react/deckgl.js
test/bench/core-layers.bench.js
test/bench/layer.bench.js
test/bench/viewport.bench.js
test/src/core/experimental/lib/effect-manager.spec.js
test/src/core/lib/attribute-manager.spec.js
test/src/core/lib/layer-manager.spec.js
test/src/core/lib/layer.spec.js
test/test-utils/index.js
test/test-utils/layer-utils.js
test/test-utils/spy.js

I've done a lot of work on polishing the 4.2-dev and I believe this is a good time to merge.

Merge 4.2 dev to master

---

examples/js/carto/utils/carto-torque-utils.js
examples/layer-browser/src/app.js
examples/point-cloud-laz/worker/laslaz.js
examples/point-cloud-laz/worker/laz-loader-worker.js
src/core/lib/stats.js
src/core/math/utils.js
src/core/utils/bin-sorter.js

This fixes a few minor JavaScript issues found by [lgtm](https://lgtm.com); for more details see https://lgtm.com/projects/g/uber/deck.gl.
Each commit fixes one particular kind of issue; I'd be happy to squash them into one if preferred.
(Full disclosure: I work on lgtm's JavaScript analysis.)

Fix issues found by lgtm

---

src/core/viewports/orbit-viewport.js

Make point-cloud-ply, point-cloud-plz and plot examples to have the right size in viewport.
Tested with these examples.

Fix the bug of distance calculation in orbit controller

---

src/core/pure-js/deck-js.js

Revert "Fix default alpha blend mode"

---

src/core-layers/path-layer/path-layer-vertex.glsl.js

Fix spike issue in path layer

---

examples/layer-browser/src/data-samples.js
examples/layer-browser/src/examples/core-layers.js
src/core-layers/path-layer/path-layer-fragment.glsl.js

Separating out new test case from path layer vertex shader changes.
These should be easy to land now while the remaining changes are reviewed.

PathLayer Meters Test

---

examples/point-cloud-laz/package.json
examples/wind/package.json

can reduce example bundle.js size after run "npm run build"

Minify example bundle

---

CHANGELOG.md
docs/README.md
docs/api-reference/attribute-manager.md
docs/api-reference/first-person-state.md
docs/api-reference/first-person-viewport.md
docs/api-reference/layer-manager.md
docs/api-reference/map-state.md
docs/api-reference/orbit-state.md
docs/api-reference/react/deckgl.md
docs/api-reference/third-person-viewport.md
docs/api-reference/web-mercator-viewport.md
docs/roadmap.md
docs/upgrade-guide.md
docs/whats-new.md
website/contents/pages.js

Clarify whats experimental in 4.2

---

examples/wind/package.json
examples/wind/yarn.lock

add "babel-loader" dependency for wind example

---

README.md

Like all other examples, I've added # or yarn to keep consistency

Add '#or yarn' to README.md

---

src/core/pure-js/deck-js.js

@ibgreen I'm 100% sure I've opened a PR on this and you approved it. Can't find it anywhere. Am I crazy?

Fix blending parameter

---

dev-docs/RFCs/v4.1/picking-improvements-rfc.md
dev-docs/RFCs/v5.0/viewport-transition-rfc.md
docs/advanced/writing-shaders.md
docs/roadmap.md
docs/upgrade-guide.md
docs/whats-new.md
src/core-layers/scatterplot-layer/scatterplot-layer.js
src/core-layers/screen-grid-layer/screen-grid-layer.js
src/core/lib/attribute-manager.js
src/core/lib/layer-manager.js
src/core/lib/layer.js
src/index.js

- Remove deprecated API
Verified with `test-browser` and `examples`.

Remove deprecated API

---

src/experimental-layers/CHANGELOG.md
src/experimental-layers/package.json
src/experimental-layers/src/solid-polygon-layer/solid-polygon-layer-vertex-64.glsl.js
src/experimental-layers/src/solid-polygon-layer/solid-polygon-layer-vertex.glsl.js
src/experimental-layers/src/solid-polygon-layer/solid-polygon-layer.js

Merge normal projection fix into experimental polygon layer

---

examples/brushing/arc-brushing-layer/arc-brushing-layer-vertex.glsl.js
examples/plot/plot-layer/grid-vertex.glsl.js
examples/plot/plot-layer/label-vertex.glsl.js
examples/tagmap/tagmap-layer/text-layer/multi-icon-layer/multi-icon-layer-vertex-64.glsl.js
examples/tagmap/tagmap-layer/text-layer/multi-icon-layer/multi-icon-layer-vertex.glsl.js
examples/text-layer/text-layer/multi-icon-layer/multi-icon-layer-vertex-64.glsl.js
examples/text-layer/text-layer/multi-icon-layer/multi-icon-layer-vertex.glsl.js
examples/trips/trips-layer/trips-layer-vertex.glsl.js
examples/webpack.config.local.js
src/core-layers/arc-layer/arc-layer-vertex-64.glsl.js
src/core-layers/arc-layer/arc-layer-vertex.glsl.js
src/core-layers/line-layer/line-layer-vertex-64.glsl.js
src/core-layers/line-layer/line-layer-vertex.glsl.js
src/core-layers/point-cloud-layer/point-cloud-layer-vertex.glsl.js
src/core/deprecated/shaderlib/project/project-deprecated.glsl.js
src/core/lib/layer.js
src/core/shaderlib/check-legacy-uniforms.js
src/core/shaderlib/lighting/lighting.glsl.js
src/core/shaderlib/project/viewport-uniforms.js
src/core/shaderlib/project64/project64.glsl.js
test/src/core/shaderlib/project/viewport-uniforms.spec.js

Tested: node, browser, layer-browser, website examples

Remove deprecated uniforms

---

src/core/controllers/map-state.js
src/core/lib/attribute-manager.js
src/core/lib/draw-layers.js
src/core/lib/props.js
src/core/shaderlib/check-legacy-uniforms.js
src/core/shaderlib/project/viewport-uniforms.js
src/core/transitions/linear-interpolator.js
src/core/transitions/viewport-fly-to-interpolator.js

Not functional changes, these are due to PRs that were not part of original #1249

Linter (prettier) changes

---

src/layers/core/arc-layer/arc-layer.js
src/layers/core/grid-cell-layer/grid-cell-layer.js
src/layers/core/hexagon-cell-layer/hexagon-cell-layer.js
src/layers/core/icon-layer/icon-layer.js
src/layers/core/line-layer/line-layer.js
src/layers/core/path-layer/path-layer.js
src/layers/core/point-cloud-layer/point-cloud-layer.js
src/layers/core/scatterplot-layer/scatterplot-layer.js
src/layers/core/solid-polygon-layer/solid-polygon-layer.js

Same as https://github.com/uber/deck.gl/pull/1268

[4.1-release] Fix double model generation

---

docs/upgrade-guide.md
docs/whats-new.md

Minor updates to documentation.

Address TODO in docs.

---

examples/point-cloud-laz/app.js
website/contents/pages.js

Fix blending in `point-cloud-laz` example.
Update example links.

Add links to new examples.

---

docs/README.md
docs/roadmap.md

I thought I already opened this, but can't find it now...

Some 5.0 doc cleanup

---

src/core/pure-js/deck-js.js
test/rendering-test/data-generator.js
test/rendering-test/test-config.js
test/rendering-test/test-rendering.js

#999 initial work to make the rendering test utility code work.

Fix rendering test module

---

docs/README.md

In the final sentence of the README

Adding space between luma.gl and "can"

---

.prettierignore

Ignore some files that should not be pretty

---

docs/api-reference/attribute-manager.md
docs/api-reference/composite-layer.md
docs/api-reference/first-person-viewport.md
docs/api-reference/layer-manager.md
docs/api-reference/layer.md
docs/api-reference/orthographic-viewport.md
docs/api-reference/perspective-viewport.md
docs/api-reference/react/viewport-controller.md
docs/api-reference/third-person-viewport.md
docs/api-reference/viewport.md
docs/api-reference/web-mercator-viewport.md
docs/layers/arc-layer.md
docs/layers/geojson-layer.md
docs/layers/grid-cell-layer.md
docs/layers/grid-layer.md
docs/layers/hexagon-cell-layer.md
docs/layers/hexagon-layer.md
docs/layers/icon-layer.md
docs/layers/line-layer.md
docs/layers/path-layer.md
docs/layers/point-cloud-layer.md
docs/layers/polygon-layer.md
docs/layers/scatterplot-layer.md
docs/layers/screen-grid-layer.md
docs/layers/solid-polygon-layer.md
docs/upgrade-guide.md
src/core/shaderlib/project/project.glsl.js
website/contents/pages.js

#1273 
I will port this to 5.0-release branch.
Verified running website.

Fix hyperlinks in documentation

---

website/src/components/demos/plot-demo.js
website/src/static/markdown/examples.md

Fix plot-demo crash.
Update the wind demo link.
Verified running website.

More doc fixes

---

test/bench/browser.js
test/bench/node.js
test/browser.js
test/node-dist.js
webpack.config.js

Fix the following tests:
- test-browser
- bench
- bench-browser
- test-dist

Fix test-utils reference

---

docs/api-reference/attribute-manager.md
src/core/lib/attribute-manager.js
src/experimental-layers/src/solid-polygon-layer/solid-polygon-layer.js

Already supported in luma.gl, just passing the field down.

Add `isGeneric` support to attribute manager

---

src/experimental-layers/src/solid-polygon-layer/solid-polygon-layer.js

Fix experimental PolygonLayer

---

src/core/lib/layer.js
test/bench/core-layers.bench.js

Recently separated prettification from linting, forgot to prettify first.

Fix pretty

---

src/core/lib/attribute-transition-manager.js
src/core/lib/attribute-transition-model.js

Depends on https://github.com/uber/luma.gl/pull/383

Use latest luma.gl transform feedback features

---

src/core-layers/geojson-layer/geojson-layer.js
src/core-layers/polygon-layer/polygon-layer.js
src/core-layers/solid-polygon-layer/solid-polygon-layer.js
src/core/lib/composite-layer.js
src/core/lifecycle/create-props.js

Hex and Grid layer are using more complicated logic, will defer changing these.

Update composite layers to use multiple prop objects

---

src/experimental-layers/src/bezier-curve-layer/README.md
src/experimental-layers/src/bezier-curve-layer/bezier-curve-layer-fragment.glsl.js
src/experimental-layers/src/bezier-curve-layer/bezier-curve-layer-vertex.glsl.js
src/experimental-layers/src/bezier-curve-layer/bezier-curve-layer.js
src/experimental-layers/src/index.js

Copy bezier curve layer from examples to experimental-layers folder

---

src/react/deckgl.js

Reported by @jianhuang01. Fixes broken rendering tests.

Fix: JSX layer extraction from nextProps

---

package.json
src/core/index.js
src/core/lib/layer-manager.js
src/core/pure-js/deck-js.js
src/core/views/view.js
src/index.js
test/src/core/views/index.js
test/src/core/views/view.spec.js

This is an initial PR relating to the [View Class RFC](https://github.com/uber/deck.gl/blob/ib/view-classes/dev-docs/RFCs/v6.0/view-class-rfc.md).
By getting this basic plumbing landed now, the more interesting upcoming changes should be a lot easier to review.
Tested with our multi-viewports example to ensure backwards compatibility.

Initial View class plumbing

---

.travis.yml
src/core-layers/geojson-layer/geojson-layer.js
src/core-layers/hexagon-layer/hexagon-layer.js
src/core/lib/composite-layer.js
src/core/lib/layer-manager.js
src/core/lib/layer-state.js
src/core/lib/layer.js
src/core/lib/seer-integration.js
test/src/core-layers/core-layers.spec.js
test/src/core-layers/grid-cell-layer.spec.js
test/src/core-layers/hexagon-cell-layer.spec.js
test/src/core/lib/layer.spec.js

This is a slightly simplified version of the layer state class PR that was previously approved for 6.0, now proposing for for 5.2.

Async Props RFC: LayerState class introduction (Stage 1)

---

dev-docs/RFCs/v6.0/prop-types-rfc.md
docs/advanced/prop-types.md
docs/whats-new.md
examples/layer-browser/src/components/layer-controls.js
examples/layer-browser/src/components/layer-selector.js
examples/layer-browser/src/examples/core-layers.js
src/core-layers/grid-cell-layer/grid-cell-layer.js
src/core-layers/grid-layer/grid-layer.js
src/core-layers/hexagon-cell-layer/hexagon-cell-layer.js
src/core-layers/hexagon-layer/hexagon-layer.js
src/core/lib/layer.js
src/core/lifecycle/create-props.js
src/core/lifecycle/prop-types.js
test/src/core/lifecycle/index.js
test/src/core/lifecycle/prop-types.spec.js

This PR provides an initial implementation of the [Prop Types RFC](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v6.0/view-class-rfc.md)

Prop types implementation per RFC

---

examples/experimental/multi-viewport-transitions/app.js
examples/experimental/multi-viewport/app.js
examples/layer-browser/src/app.js

Implements #1370
This is the third in a series of staged diffs (shows differences compared to #1380)

Official multi viewport API: Update examples (Stage 3 of 3)

---

examples/experimental/multi-viewport-transitions/app.js
examples/experimental/multi-viewport/app.js
examples/layer-browser/src/app.js
src/core/lib/layer-manager.js
src/core/lib/transition-manager.js
src/core/pure-js/deck-js.js
src/core/transitions/linear-interpolator.js
src/core/transitions/transition-utils.js
src/react/deckgl.js

Implements #1370
This is a staged diff (shows differences compared to #1379)

Official multi viewport API - Implement per RFC (Stage 2 of 3)

---

src/core/lib/deck.js

An attempt to break out pieces of the pending state->controller refactor as separate reviewable packets.

Deck component: Code reorg + fix createCanvas (Stage 2)

---

examples/experimental/js/carto/app.js
examples/experimental/js/with-mapbox-map/app.js
examples/experimental/js/without-map/app.js
src/core/index.js
src/core/lib/deck.js
src/index.js
src/react/deckgl.js
test/rendering-test/test-rendering.js

Rename `DeckJS` to just `Deck` and move to lib folder.

Deck component: Move to lib folder (Stage 1 PR)

---

dev-docs/RFCs/v6.0/per-view-controllers.md
docs/api-reference/deck.md
docs/api-reference/first-person-view.md
docs/api-reference/javascript/deck.md
docs/api-reference/map-view.md
docs/api-reference/orthographic-view.md
docs/api-reference/perspective-view.md
docs/api-reference/third-person-view.md
website/contents/pages.js

JSAPI docs

---

docs/get-started/using-with-react.md

update using-with-react.md with workable example code

---

examples/wind/package.json
examples/wind/src/layers/delaunay-cover-layer/delaunay-cover-layer.js
examples/wind/src/layers/elevation-layer/elevation-layer.js
examples/wind/src/shaderlib/fs-lighting/fs-lighting.js
examples/wind/src/wind-demo.js

https://github.com/uber/deck.gl/issues/1452

Fix wind demo

---

docs/layers/hexagon-layer.md

For #1369 
- Change default 'extruded' to be 'false'

Change default 'extruded'  to be 'false' in hexagon-layer.md

---

docs/api-reference/attribute-manager.md
docs/api-reference/layer.md
docs/whats-new.md

For #1459 
- Add transitions prop in layer.md
- Fix a doc error in attribute-manager.md
- Add right link in whats-new.md

Update docs for layer transitions.

---

examples/layer-browser/src/app.js
examples/layer-browser/src/index.js
examples/layer-browser/webpack.config.js

Retains app state after reload

Fix layer-browser hot reload

---

website/contents/pages.js

Problem introduced in https://github.com/uber/deck.gl/pull/1364

Fix link rewrite in website

---

website/src/components/demos/plot-demo.js

https://github.com/uber/deck.gl/issues/1471

Fix plot demo on website

---

src/core/lib/layer-manager.js

https://github.com/uber/deck.gl/issues/1474
- Replace outdated mjolnir.js API usage
Tested in layer browser.

Do not pick when dragging

---

website/contents/pages.js

For https://github.com/uber/deck.gl/issues/1470
- Table of contents update for 5.1 release website

[Website] Update documentation hierarchy

---

website/src/components/header.js

[website] redirect to new blog

---

docs/api-reference/test-utils/README.md
examples/test-utils/webpack.config.js
test/bench/browser.js
test/bench/core-layers.bench.js
test/bench/layer.bench.js
test/bench/node.js
test/node-aliases.js
test/render-from-node.js
test/render/old/test-rendering.react.js
test/render/test-rendering.js
test/src/core-layers/core-layers.spec.js
test/src/core-layers/geojson-layer.spec.js
test/src/core-layers/grid-cell-layer.spec.js
test/src/core-layers/grid-layer.spec.js
test/src/core-layers/hexagon-cell-layer.spec.js
test/src/core-layers/hexagon-layer.spec.js
test/src/core-layers/polygon-layer.spec.js
test/src/core/lib/layer-manager.spec.js
test/src/core/lib/layer.spec.js
test/src/core/lib/transition/viewport-fly-to-interpolator.spec.js
test/src/core/viewports/web-mercator-project-unproject.spec.js
webpack.config.js

For #1423 
- Rename module across code base

deck.gl-test-utils: Rename library (#1 of 2)

---

package.json
test/render/old/test-rendering.react.js

For #
Non react version of rendering test is broken on master, change it to the old one without blocking the team
- change "npm run test" command
- call renderTestComplete to notify puppeteer

change rendering test to react version

---

docs/api-reference/test-utils/README.md
docs/api-reference/test-utils/render-test-driver.md
docs/api-reference/test-utils/scene-renderer.md
docs/api-reference/test-utils/test-layer.md
docs/api-reference/test-utils/test-renderer.md

For #1423
- Another pass at improving the test utils documentation

Test documentation improvements

---

docs/api-reference/test-utils/README.md
docs/api-reference/test-utils/scene-renderer.md
docs/api-reference/test-utils/test-layer.md
src/test-utils/CHANGELOG.md
src/test-utils/package.json

For #1423 
- Updating package version as decided in review
- Additional doc polish, remove experimental labels
- doc cleanup
- package.json version
- CHANGELOG

deck.gl-test-utils v5.2.0-alpha.1

---

src/core/lifecycle/constants.js

Fix minor typo in constants.js

---

src/core/utils/bin-sorter.js

For #1360
- iterate items to get max count

Fix max count issue in bin sorter

---

examples/experimental/js/with-mapbox-map/app.js
src/core/lib/layer-manager.js

For #1502
- Add a protection for viewState
- Update example to use new viewState API

with-mapbox-map example fix

---

src/core/utils/bin-sorter.js

For #1360 
- Compare the counts

Fix bug in getMaxCount

---

src/core/lib/attribute-manager.js

For https://github.com/uber/deck.gl/issues/1519
- Allow external buffer for an attribute to be a luma.gl Buffer object

Allow external buffer to be Buffer instead of typed array

---

src/core-layers/screen-grid-layer/screen-grid-layer.js

For #
Remove invalid deprecation warning
- ScreenGridLayer: Remove invalid deprecation warning

ScreenGridLayer: Remove invalid deprecation warning

---

.travis.yml
aliases.js
package.json
test/scripts/collect-metrics.sh
test/size/import-nothing.js
test/webpack.config.js
yarn.lock

Ensure we can measure dist size on previous release to measure progress
- Add size test script and webpack code copied from master branch.

Add metrics to 5.1-release

---

dev-docs/RFCs/v5.0/purejs-standalone-rfc.md

Proposed submodule `@deck.gl/js`

Standalone JS RFC

---

website/package.json
website/webpack.config.js

Website demos are broken on master
- Use the root copy of luma.gl when building the website

Fix website build

---

docs/advanced/view-state.md
docs/advanced/viewports.md
docs/advanced/views.md
docs/api-reference/first-person-view.md
docs/api-reference/view.md
docs/api-reference/viewport.md

For #1370, a pass on the new view docs. More work will follow.
- Partial round of doc updates for new View classes

View doc updates

---

src/core/views/orbit-view.js
src/core/views/orthographic-view.js
src/core/views/view.js

For #1370 
- Cleanup and orthographic support

View improvements

---

src/core/viewports/orbit-viewport.js
src/core/viewports/orthographic-viewport.js
src/core/viewports/viewport.js
src/core/viewports/web-mercator-viewport.js

For #1370 
- Orthographic support in Viewports

Viewport improvements

---

examples/tagmap/app.js
examples/tagmap/deckgl-overlay.js
examples/tagmap/package.json
examples/tagmap/tagmap-layer/tagmap-layer.js
examples/tagmap/tagmap-layer/tagmap-wrapper.js
examples/tagmap/webpack.config.js
examples/text-layer/app.js
examples/text-layer/package.json
examples/text-layer/webpack.config.js

For https://github.com/uber/deck.gl/issues/1619
- Remove unnecessary dependencies
- Perf: add caching for layout results (5fps -> 40fps)
- Misc. code clean up

tagmap layer example improvements

---

dev-docs/RFCs/v6.0/gpu-screengrid-aggregation.md
src/experimental-layers/src/utils/gpu-grid-aggregator.js

For #1414
- Found issues when switching between GPU and GPU, adding fixes.
- Add markdown version of the RFC
- Fix: switching between CPU and GPU.
- Add markdown version of the RFC

GpuScreenGridLayer : RFC and Fixes

---

src/core/lib/attribute-transition-manager.js
src/core/lib/attribute.js

For https://github.com/uber/deck.gl/issues/1609
- Use new attribute fields

Fix attribute transition manager

---

examples/bezier/deckgl-overlay.js
examples/experimental/orthographic-zooming/app.js
examples/graph/deckgl-overlay.js
examples/graph/package.json
examples/graph/webpack.config.js
examples/plot/app.js
examples/plot/deckgl-overlay.js
examples/plot/package.json
examples/plot/webpack.config.js
examples/point-cloud-laz/app.js
examples/point-cloud-ply/app.js
examples/svg-interoperability/app.js
src/core/lib/deck.js
src/index.js

For #1370 and #1429
- Fixes to and cleanup of infovis examples
- Needs to be rebased after current crop of PRs have landed.
- examples

Update examples using new View classes and Deck/Controller integration

---

docs/whats-new.md

For #1583 
Add icon and fix url.
- Add ScreenGrid Icon, fix doc link

WhatsNew: Add ScreenGrid Icon, fix doc link

---

docs/layers/text-layer.md
src/core-layers/text-layer/text-layer.js
src/core/lib/deck.js

For #
- add fontFamily prop
- use .position as getPosition default
- update document
- minor linter issue

Text layer audit

---

aliases.js
examples/graph/deckgl-overlay.js
examples/plot/app.js
examples/plot/deckgl-overlay.js
package.json
scripts/collect-metrics.sh
src/bundle.js
src/experimental-layers/package.json
src/experimental-layers/test/node-dist.js
src/experimental-layers/test/node.js
src/react/package.json
src/test-utils/package.json
src/test-utils/test/test-browser.js
yarn.lock

- Cleanup of scripts
- lint fixes
- remove babel polyfill
- new collect-metrics script

Remove polyfill. Update test scripts

---

examples/webpack.config.local.js
src/core/views/orthographic-view.js

- Small fix to orthographic view
- Ensure valid top, right values

Fix orthographic viewport

---

examples/without-map/app.js

- Use the JS controller instead of the React controller
- Use the JS controller

Quick Fix for `without-map` example

---

src/core-layers/text-layer/text-layer.js

For #1608
Chrome doesn't support all the font face well on windows
- Remove the font face chrome doesn't support well on windows

fix text layer issue on windows

---

package.json
test/start.js
test/webpack.config.js

bench browser test is broken on master
- fix the tests

fix bench browser test

---

examples/layer-browser/src/app.js
examples/scatterplot/app.js
examples/scatterplot/deckgl-overlay.js
package.json
src/core/lib/deck.js
src/core/lib/layer-manager.js
src/react/src/deckgl.js
src/test-utils/src/scene-renderer.js
test/render/test-cases.js

Partial diff from new controller branch

Deck Component: auto resize handling

---

aliases.js
examples/layer-browser/src/examples/experimental-layers.js
examples/webpack.config.local.js
modules/experimental-layers/src/index.js
modules/experimental-layers/src/path-outline-layer/path-outline-layer.js
test/bench/browser.js
test/bench/core-layers.bench.js
test/bench/gpu-grid-aggregator.bench.js
test/bench/layer.bench.js
test/render/old/test-rendering.react.js
test/render/test-cases.js
test/render/test-rendering.js
test/src/core-layers/core-layers.spec.js
test/src/core-layers/geojson-layer.spec.js
test/src/core-layers/grid-cell-layer.spec.js
test/src/core-layers/grid-layer.spec.js
test/src/core-layers/hexagon-cell-layer.spec.js
test/src/core-layers/hexagon-layer.spec.js
test/src/core-layers/polygon-layer.spec.js
test/src/core/lib/layer-manager.spec.js
test/src/core/lib/layer.spec.js
test/src/core/lib/transitions/viewport-fly-to-interpolator.spec.js
test/src/core/viewports/web-mercator-project-unproject.spec.js
test/src/experimental-layers/gpu-grid-aggregator.spec.js
test/src/experimental-layers/index.js
test/src/index.js
test/start.js
test/webpack.config.js
website/webpack.config.js

Module split for #1629
- Update aliases system
- Update webpack module resolve
- Correct imports in examples and tests

Module split PR4

---

docs/advanced/view-state.md
docs/advanced/viewports.md
docs/advanced/views.md
docs/api-reference/map-controller.md
docs/developer-guide/building-apps.md
docs/roadmap.md
docs/upgrade-guide.md
docs/whats-new.md
website/contents/pages.js

- Updates for What's New and docs.
- docs

Update What's New and View docs

---

scripts/bootstrap.sh

bootstrap has issues with fresh cloned repo
- remove the .bin folder before the symbol link

fix bootstrap

---

package.json

add lint to ci test to keep code style consistent
- add linter

add linter to ci test

---

docs/advanced/view-state.md
docs/advanced/viewports.md
docs/advanced/views.md
docs/api-reference/map-controller.md
docs/developer-guide/building-apps.md
docs/roadmap.md
docs/upgrade-guide.md
docs/whats-new.md
website/contents/pages.js

What's new, restoring after revert

What's new update

---

modules/core/src/core/lib/deck.js
modules/lite/src/deckgl.js
modules/lite/test/index.js
modules/lite/webpack.config.js

- Fix controller breakage when using auto resize
- Integrate autoresize to standalone version

Fix auto resize and controller

---

docs/layers/text-layer.md
examples/layer-browser/src/components/layer-controls.js
examples/layer-browser/src/data-samples.js
examples/layer-browser/src/examples/core-layers.js
modules/core/src/core-layers/text-layer/text-layer.js

Follow up PR for #976 
- regenerate font atlas when fontFamily changed

regenerate font atlas when fontFamily changed

---

modules/core/src/core-layers/grid-cell-layer/grid-cell-layer-vertex.glsl.js
modules/core/src/core-layers/grid-cell-layer/grid-cell-layer.js
modules/core/src/core-layers/hexagon-cell-layer/hexagon-cell-layer-vertex.glsl.js
modules/core/src/core-layers/hexagon-cell-layer/hexagon-cell-layer.js
modules/core/src/core-layers/point-cloud-layer/point-cloud-layer-vertex.glsl.js
test/src/core-layers/hexagon-cell-layer.spec.js

For https://github.com/uber/deck.gl/issues/1672
- Use `project_scale` in vertex shaders to support all coordinate systems
- Add uniforms in `draw` method
- Replace deprecated `getLightWeight` shader function

Clean up cell layers code

---

docs/whats-new.md
examples/text-layer/app.js
examples/text-layer/deckgl-overlay.js

- Change link in what's new pointing to the text-layer gif.
- Minor style change for the text-layer example making fonts more salient.

add text-layer screenshot to what's new

---

examples/3d-heatmap/package.json
examples/arc/app.js
examples/arc/package.json
examples/bezier/package.json
examples/brushing/app.js
examples/brushing/package.json
examples/geojson/app.js
examples/geojson/package.json
examples/graph/package.json
examples/icon/app.js
examples/icon/package.json
examples/layer-browser/package.json
examples/line/app.js
examples/line/package.json
examples/scatterplot/app.js
examples/scatterplot/package.json
examples/screen-grid/app.js
examples/screen-grid/package.json
examples/svg-interoperability/package.json
examples/tagmap/app.js
examples/tagmap/package.json
examples/text-layer/app.js
examples/text-layer/package.json
examples/trips/app.js
examples/trips/package.json

For #
use fetch instead of d3-request/json in examples where applicable
- replace d3-request/json with fetch
- remove d3-request from package.json

use fetch instead of d3-request/json in examples

---

examples/bezier/deckgl-overlay.js
examples/layer-browser/package.json
examples/layer-browser/src/examples/experimental-layers.js
examples/test-utils/webpack.config.js

deck.gl-layers are replaced by @deck.gl/experimental-layers
- Replace deck.gl-layers with new name
- Fix a dependency issue

replace deck.gl-layers with @deck.gl/experimental-layers

---

docs/whats-new.md

pre release what's new update
- update what's new

update whats new

---

CHANGELOG.md
lerna.json
modules/core/package.json
yarn.lock

5.2.0 beta 1 release
- Update change log
- Bump package version
- Bump luma.gl version

v5.2.0-beta.1

---

examples/plot/deckgl-overlay.js
website/src/components/demos/plot-demo.js

For https://github.com/uber/deck.gl/issues/1684
- Remove reference to removed component `OrbitController`
- Support both standalone and website use case

Fix plot example in website

---

examples/layer-browser/src/app.js
modules/core/src/core/lib/deck.js

For https://github.com/uber/deck.gl/issues/1687
- Add default values for `width` and `height` props

Default width and height props

---

docs/layers/text-layer.md
examples/layer-browser/src/examples/core-layers.js
modules/core/src/core-layers/text-layer/font-atlas.js
modules/core/src/core-layers/text-layer/text-layer.js

For https://github.com/uber/deck.gl/issues/1691
- Fix exception if character is missing. Warn in console instead.
- Add prop `characterSet` for TextLayer
- Update docs

Support characterSet prop in TextLayer

---

scripts/publish.sh

Missing `#` before comment, throws error at runtime
- Fix publish script error

Fix publish script typo

---

modules/core/src/core-layers/text-layer/font-atlas.js

For https://github.com/uber/deck.gl/issues/1696
- do not import `global`

Remove missing import global

---

modules/core/package.json
modules/lite/package.json
modules/main/package.json
modules/react/package.json

For https://github.com/uber/deck.gl/issues/1702
- Add [prepublishOnly](https://docs.npmjs.com/misc/scripts#deprecation-note) script to core and main packages
- Remove unused test scripts

Fix inline versions

---

docs/advanced/view-state.md
examples/layer-browser/src/app.js
modules/core/src/core/viewports/viewport.js

For #1706
- Fix fov radians calculation.
- Small doc change: Clarify where projection related view parameters go.

Fix inverted FirstPersonView

---

modules/core/package.json
yarn.lock

- Make sure deck.gl uses latest math.gl

Bump math.gl

---

modules/core/src/core/lib/deck.js
modules/core/src/core/lib/layer-manager.js
yarn.lock

For #1709
- Pass useDevicePixels from deck to layerManager

fix useDevicePixels bug

---

modules/core/src/core/lib/deck.js
modules/core/src/core/lib/layer-manager.js

For #1709
- Update useDevicePixels in setParameters

handle review feedback for useDevicePixels

---

examples/get-started/pure-js-without-map/app.js
examples/get-started/pure-js-without-map/index.html
examples/get-started/pure-js-without-map/package.json
examples/get-started/pure-js/app.js
examples/get-started/pure-js/index.html
examples/get-started/pure-js/mapbox.js
examples/get-started/pure-js/package.json
examples/get-started/pure-js/webpack.config.js

Upgrade pure-js examples to the latest API, improve general readability
- Remove React-style class structure
- Remove react-map-gl code, add minimal mapbox wrapper

Clean up js examples

---

docs/api-reference/test-utils/render-test.md
docs/api-reference/test-utils/test-layer.md
docs/developer-guide/testing/README.md
docs/developer-guide/testing/testing.md
docs/developer-guide/testing/using-with-unit-test-frameworks.md
website/contents/pages.js

Test-utils website pages are outdated
- Update test-utils docs

Update test-utils website pages

---

docs/advanced/using-standalone.md
docs/api-reference/standalone/deckgl.md
docs/get-started/using-standalone.md
modules/lite/README.md
website/contents/pages.js

For https://github.com/uber/deck.gl/issues/1625
- Update "Using Standalone" article
- Add docs for the standalone `DeckGL` component

Update scripting API docs

---

docs/api-reference/test-utils/render-test.md
docs/developer-guide/testing/README.md

Fix bad links and format
- Update test-utils docs

more doc fix for test-utils

---

test/apps/multi-viewport/app.js
test/apps/multi-viewport/index.html

- Multiviewport example fixes
- include path
- imports
- mapbox styles

Fix multi-viewport test app

---

examples/website/brushing/package.json
test/node-examples.js

"npm run test examples" is down
- Fix the example and test

fix example test

---

docs/advanced/views.md
docs/api-reference/first-person-view.md
docs/api-reference/map-view.md
docs/api-reference/orthographic-view.md
docs/api-reference/perspective-view.md
docs/api-reference/test-utils/test-layer.md
docs/api-reference/third-person-view.md
docs/api-reference/view.md
docs/whats-new.md
modules/core/src/core/views/perspective-view.js
modules/core/src/core/views/view.js

- A pass on the `View` docs as discussed in pre-release meeting.
- View docs
- test-utils (assert function) docs

View documentation updates. 

---

docs/advanced/view-state.md
docs/advanced/viewports.md
docs/advanced/views.md
docs/api-reference/layer.md
docs/api-reference/web-mercator-viewport.md
docs/get-started/interactivity.md
docs/get-started/using-layers.md
docs/get-started/using-with-react.md
docs/whats-new.md
website/contents/pages.js
website/src/components/markdown-page.js

Lots of links are broken
- Warning message for broken links
- Fix the bad links

Fix bad links on website

---

docs/api-reference/attribute-manager.md
docs/api-reference/deck.md
docs/api-reference/first-person-view.md
docs/api-reference/first-person-viewport.md
docs/api-reference/internal/layer-manager.md
docs/api-reference/react/deckgl.md
docs/api-reference/react/viewport-controller.md
docs/api-reference/standalone/deckgl.md
docs/api-reference/test-utils/render-test.md
docs/api-reference/test-utils/scene-renderer.md
docs/api-reference/test-utils/test-layer.md
docs/api-reference/third-person-view.md
docs/api-reference/third-person-viewport.md
docs/api-reference/view.md
docs/layers/README.md

- Fix outdated source links in documentation

Fix outdated source links

---

website/contents/pages.js
website/src/static/markdown/showcase.md

- Fix broken links to showcase apps and source

Update showcases links

---

docs/layers/text-layer.md
website/src/components/demos/layer-demos.js
website/src/utils/format-utils.js
website/src/utils/layer-params.js

- Add embedded demo for TextLayer API page
- Fix: ScreenGridLayer demo not rendering
- Fix: inherited layer props are not visible in the embedded demos

Embedded layer demo fixes

---

dev-docs/RFCs/v5.3/picking-overlapping-objects-rfc.md

For #1733 
- Incorporating feedback from the PR #1730 review into the RFC
- RFC updates

Update picking RFC

---

dev-docs/RFCs/v5.3/picking-overlapping-objects-rfc.md
docs/api-reference/deck.md
docs/whats-new.md
examples/layer-browser/src/app.js
examples/layer-browser/src/components/layer-info.js
modules/core/src/core/lib/deck.js
modules/core/src/core/lib/layer-manager.js
modules/core/src/core/lib/layer.js
modules/core/src/core/lib/pick-layers.js
modules/react/src/deckgl.js

Picking overlapping objects RFC implementation

---

docs/api-reference/deck.md

- Published Deck Doc looks iffy: http://uber.github.io/deck.gl/#/documentation/deckgl-api-reference/deck
- Fix code section termination

Fix Deck class doc

---

dev-docs/RFCs/README.md
dev-docs/RFCs/v5.3/constant-accessor-rfc.md
dev-docs/RFCs/v5.3/generic-accessor-props-rfc.md

Generic accessor micro-RFC

---

modules/experimental-layers/package.json
modules/react/package.json
modules/test-utils/package.json

For #1767 
- add missing BABEL_ENV environment variable to package scripts.

Update deck.gl package.json files with missing BABEL_ENV

---

docs/layers/text-layer.md

Hello, please let me know if I should create an issue first. Otherwise, this fix is within the comments of a sample for text data.

Change property name from coordinates to position

---

modules/core/src/core/controllers/controller.js
modules/core/src/core/lib/deck.js

For #1422 
- Clean up some internal naming in the controller classes.
- Clean up some internal naming in the controller classes.

Controller cleanup

---

package.json
scripts/test.sh
yarn.lock

Hook browser based tests with "git push" instead of "git commit"
- Define pre-commit hook
- Add pre-push dependency

Hook git push with browser based tests

---

docs/roadmap.md
docs/whats-new.md
website/src/components/header.js

For #1780
- Fix the wrong links

fix the wrong blog link

---

examples/get-started/pure-js-without-map/app.js
examples/get-started/pure-js/app.js
modules/core/src/views/view-manager.js

- Fix issue with previous refactor
- Redraw flag, example imports.

Fix viewport resize issue

---

modules/core-layers/src/grid-layer/grid-layer.js
modules/core/src/lib/composite-layer.js
modules/core/src/lib/layer-state.js
modules/core/src/lib/layer.js
modules/core/src/lib/pick-layers.js
modules/core/src/lib/seer-integration.js
modules/core/src/lifecycle/component-state.js
modules/core/src/lifecycle/component.js
modules/core/src/lifecycle/create-props.js
modules/test-utils/src/lifecycle-test.js
test/bench/core-layers.bench.js
test/modules/core/lifecycle/component-state.spec.js
test/modules/core/lifecycle/component.spec.js

For #
- Renaming Layer->Component to generalize some prop creation code.
- As above
- Also attempt to make function names more descriptive

Async Props #0: Renaming prep

---

modules/core/src/lib/layer.js
modules/core/src/lifecycle/create-props.js

For #1372 
- Update props object in `create-props.js`

Async Props #1: Add ability to differentiate between actual and resolved values for async props.

---

modules/core/src/lib/deck.js

I spotted this, presumably a typo?

Fix a typo in deck.js

---

docs/upgrade-guide.md
docs/whats-new.md

- per discussion in release meeting
- docs

Add deprecation guide and what's new polish

---

modules/core/src/lib/attribute-transition-manager.js
test/modules/core/lib/attribute-transition-manager.spec.js
test/modules/core/lib/index.js

Add tests for AttributeTransitionManager
- tests
- fix a bug where new transform is not generated after the old one being invalidated

AttributeTransitionManager test

---

modules/core/src/lib/attribute-transition-utils.js
test/modules/core/lib/attribute-transition-manager.spec.js

- Fix browser test cases
- Add tests for buffer padding
- Fix buffer padding bugs

Fix attribute transition manager tests

---

modules/lite/webpack.config.js

- Fix `modules/lite` webpack config to cover both core and layers modules.

Fix scripting in 5.3-release

---

examples/website/arc/app.js
examples/website/icon/app.js
modules/react/src/deckgl.js
website/src/components/demos/icon-demo.js

Some example fixes

---

docs/whats-new.md

For #
Layer demos in whats-new should point to deck.gl-data repo's master branch.
- Fix whats-new layer demo urls.

Fix whats-new layer demo urls.

---

examples/website/brushing/app.js
examples/website/brushing/arc-brushing-layer/index.js
examples/website/brushing/scatterplot-brushing-layer/index.js
examples/website/geojson/app.js
examples/website/line/app.js
examples/website/scatterplot/app.js

For #1873 
- Make sure examples at least start locally
- Small fixes in examples

 Make sure website examples start locally

---

modules/lite/package.json
yarn.lock

For https://github.com/uber/deck.gl/issues/1874
Bring in fixes in https://github.com/uber/react-map-gl/pull/521
- Bump mapbox wrapper version

Fix mapbox wrapper error when use viewState

---

dev-docs/RFCs/README.md
dev-docs/RFCs/v6.0/data-filter-rfc.md

See RFC.
- Add data filter RFC
- Update RFC catalog

Data filter RFC

---

modules/layers/src/arc-layer/arc-layer.js
modules/layers/src/grid-cell-layer/grid-cell-layer.js
modules/layers/src/hexagon-cell-layer/hexagon-cell-layer.js
modules/layers/src/icon-layer/icon-layer.js
modules/layers/src/line-layer/line-layer.js
modules/layers/src/point-cloud-layer/point-cloud-layer.js
modules/layers/src/scatterplot-layer/scatterplot-layer.js
modules/test-utils/src/scene-renderer.js

- Forgot to do this when moving to default accessors in #1676 
- Remove comments

 Remove commented functions from layers

---

modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer.js
test/bench/array-copy.bench.js
test/bench/browser.js
test/bench/gpu-grid-aggregator.bench.js
test/bench/index.js
test/bench/utils.bench.js
test/start.js

Bench fixes

---

examples/gallery/src/viewport-transition.html
examples/layer-browser/src/app.js
examples/website/plot/app.js
examples/website/point-cloud-laz/app.js
examples/website/point-cloud-ply/app.js
modules/core/package.json
modules/core/src/controllers/view-state.js
modules/core/src/deprecated/first-person-viewport.js
modules/core/src/deprecated/third-person-viewport.js
modules/core/src/index.js
modules/core/src/views/first-person-view.js
modules/core/src/views/third-person-view.js
modules/lite/src/deckgl.js
modules/main/src/index.js
test/apps/multi-viewport/app.js
test/apps/multi-viewport/package.json
test/apps/viewport-transitions-flyTo/src/app.js
yarn.lock

For #1607 
- Initial changes based on using underscore for experimental exports

WIP: Experimental exports

---

examples/layer-browser/src/app.js
modules/core/src/lib/deck.js
modules/core/src/lib/layer-manager.js
modules/core/src/views/view-manager.js
modules/react/src/deckgl.js
modules/test-utils/src/lifecycle-test.js
test/modules/core/lib/layer-manager.spec.js
yarn.lock

- Cleanup
- Move view manager from layer manager to deck.

Move ViewManager out of LayerManager

---

dev-docs/RFCs/README.md
dev-docs/RFCs/v6.1/project32-with-64bit-data-rfc.md
dev-docs/RFCs/vNext/projection-mode-improvements-rfc.md

Projection RFC split: Separate RFC for 32/64-bit projection

---

dev-docs/RFCs/v6.0/binary-data-rfc.md

- Initial attempt to capture binary related topics in one place

RFC Draft: "Using Binary Data" 

---

examples/layer-browser/src/examples/experimental-layers.js
modules/experimental-layers/src/path-marker-layer/path-marker-layer.js
modules/experimental-layers/src/path-outline-layer/path-outline-layer.js

and remove moduleParameters to fix offset coordinates

Fix path-marker-layer property passing

---

scripts/extract-types.js

- Script that walks all layers, and iterates over prop types and writes type definitions on stdout
- New script.

Initial layer prop type generator

---

modules/layers/src/index.js
modules/layers/src/path-layer/path-layer.js
modules/layers/src/solid-polygon-layer/solid-polygon-layer.js

For #
- Make it easier to override things when developing with deck.gl
- Expose all layers in `@deck.gl/layers` (with underscore)
- Add a `_getPathLength()` method to `PathLayer`
- Add `_PolygonTesselator` to `_SolidPolygonLayer`

Expose more internals (as experimental exports)

---

dev-docs/RFCs/README.md
dev-docs/RFCs/v6.1/improved-lnglat-projection-rfc.md
dev-docs/RFCs/v6.1/project32-with-64bit-data-rfc.md

- Updates based on discussions

Updates to RFC: Improved LNGLAT projection mode

---

test/render/test-cases.js

For #
These render tests are failing randomly on Intel GPU.
- Disable render tests failing on Intel GPU

Disable render tests failing on Intel GPU

---

modules/core/src/lib/attribute-manager.js
modules/core/src/lib/attribute-transition-manager.js
modules/core/src/lib/attribute-transition-utils.js
modules/layers/src/solid-polygon-layer/solid-polygon-layer.js

For https://github.com/uber/deck.gl/issues/1905
This is prep for implementing path/polygon transition in a follow up PR.
- Pass the current context (layer instance) to the transition manager
- Remove hacks from `SolidPolygonLayer`, align with other layer code

Advanced attribute transition PR1

---

docs/whats-new.md
modules/core/src/lib/layer.js
modules/experimental-layers/src/mesh-layer/mesh-layer.js
modules/layers/src/arc-layer/arc-layer.js
modules/layers/src/grid-cell-layer/grid-cell-layer.js
modules/layers/src/hexagon-cell-layer/hexagon-cell-layer.js
modules/layers/src/icon-layer/icon-layer.js
modules/layers/src/line-layer/line-layer.js
modules/layers/src/path-layer/path-layer.js
modules/layers/src/point-cloud-layer/point-cloud-layer.js
modules/layers/src/scatterplot-layer/scatterplot-layer.js
modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
test/modules/core/lib/layer.spec.js
test/render/test-cases.js

For #1937 
See RFC.
- Add new method for deciding if we need 64-bit array

Add needs64bitPositions() to Layer and use it in existing layers

---

docs/README.md
examples/website/3d-heatmap/app.js
examples/website/3d-heatmap/package.json
examples/website/arc/app.js
examples/website/arc/package.json
examples/website/brushing/app.js
examples/website/brushing/package.json
examples/website/geojson/app.js
examples/website/geojson/package.json
examples/website/icon/app.js
examples/website/icon/package.json
examples/website/line/app.js
examples/website/point-cloud-laz/app.js
examples/website/point-cloud-ply/app.js
examples/website/scatterplot/app.js
examples/website/screen-grid/app.js
examples/website/tagmap/app.js
examples/website/tagmap/package.json
examples/website/text-layer/app.js
examples/website/trips/app.js
examples/website/trips/package.json
modules/lite/package.json
test/modules/core-layers/grid-layer.spec.js
website/package.json
website/src/components/demo-launcher.js

- Keep cleaning up/fixing website demos

Website Example Updates

---

docs/upgrade-guide.md
docs/whats-new.md
examples/layer-browser/src/examples/core-layers.js
modules/core/src/lib/constants.js
modules/core/src/lib/layer.js
modules/core/src/shaderlib/project/project.glsl.js
modules/core/src/shaderlib/project/viewport-uniforms.js
modules/core/src/shaderlib/project32/project32.js

COORDINATE_SYSTEM_EXPERIMENTAL_LNG_LAT
For #1937 
See RFC.
- Add new projection mode

Implement RFC: Improved 32-bit LNGLAT projection mode

---

dev-docs/RFCs/README.md
dev-docs/RFCs/v6.0/react-api.md

For https://github.com/uber/deck.gl/issues/1969
See RFC

React-API RFC

---

examples/website/3d-heatmap/app.js
modules/core/src/lib/deck.js
modules/core/src/viewports/viewport.js
modules/core/src/views/view-manager.js
modules/core/src/views/view.js
modules/react/src/deckgl.js
modules/react/src/utils/evaluate-children.js
modules/react/src/utils/extract-jsx-layers.js
test/apps/multi-viewport/app.js
test/modules/index.js
test/modules/react/index.js
test/modules/react/utils/extract-jsx-layers.spec.js

For https://github.com/uber/deck.gl/issues/1969
RFC: https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v6.0/react-api.md
- Support render callback in DeckGL React component
- Support JSX views
- Clean up 3d-heatmap example
- Clean up multi-viewport example
- Tests
- Update all examples
- Docs

Implement React API RFC

---

modules/core/src/lib/attribute-manager.js
modules/core/src/lib/attribute-transition-manager.js
modules/core/src/lib/attribute-transition-utils.js
modules/core/src/lib/attribute.js
modules/layers/src/path-layer/path-layer.js
modules/layers/src/solid-polygon-layer/polygon-tesselator.js
modules/layers/src/solid-polygon-layer/solid-polygon-layer.js

For #1905
- Enable attribute transition in PathLayer and SolidPolygonLayer
- Tests
- Update docs

Advanced attribute transition PR2

---

modules/layers/src/geojson-layer/geojson.js
test/apps/webpack.config.local.js

buble-loader somehow does not like nested assignment.
- Avoid buble-loader error
- Fix source path in webpack config

Fix start-local for test apps

---

docs/api-reference/layer.md
docs/layers/geojson-layer.md
docs/layers/path-layer.md
docs/layers/polygon-layer.md
docs/layers/solid-polygon-layer.md
modules/core/src/lib/attribute-transition-manager.js
modules/core/src/lib/attribute.js
modules/layers/src/geojson-layer/geojson-layer.js
modules/layers/src/path-layer/path-layer.js
modules/layers/src/polygon-layer/polygon-layer.js
modules/layers/src/solid-polygon-layer/solid-polygon-layer.js

For #1905
- Enable attribute transition in PolygonLayer and GeoJsonLayer
- Update docs

Advanced attribute transition PR3

---

docs/api-reference/react/deckgl.md
docs/get-started/using-with-react.md
docs/whats-new.md

For https://github.com/uber/deck.gl/issues/1969
Follow up of https://github.com/uber/deck.gl/pull/1971
- What's new
- Using with React article
- DeckGL React component API docs

Update React docs

---

docs/whats-new.md

For whats-new updates for #1976 #1931 
- ScreenGridLayer: update whats-new

Update whats-new doc

---

modules/core/package.json
modules/core/src/lib/attribute-transition-manager.js
modules/core/src/lib/attribute-transition-utils.js
test/modules/core/lib/attribute-transition-manager.spec.js
yarn.lock

For https://github.com/uber/deck.gl/issues/1974
- Remove reference to `buffer.data`

Buffer data removal

---

docs/whats-new.md
modules/layers/src/geojson-layer/geojson-layer.js

For https://github.com/uber/deck.gl/issues/1905
- Fix geojson layer transitions prop passing
- Update what's new

Attribute Transition bug fix & what's new

---

README.md
examples/layer-browser/src/examples/experimental-layers.js
modules/experimental-layers/src/contour-layer/contour-layer.js
modules/experimental-layers/src/contour-layer/contour-layer.md
modules/experimental-layers/src/gpu-grid-layer/gpu-grid-layer.js
modules/experimental-layers/src/gpu-grid-layer/gpu-grid-layer.md

For #1979 #1556 #1415 
- Add docs for GPUGridLayer and ContourLayer

Add docs for GPUGridLayer and ContourLayer

---

docs/api-reference/react/deckgl.md
docs/whats-new.md
modules/core/src/lib/deck.js

For https://github.com/uber/deck.gl/issues/1422
- Fix controller proptype
- update controller docs and what's new

Controller proptype fix

---

examples/website/point-cloud-laz/app.js
examples/website/point-cloud-ply/app.js

For #1873
- Fix the two point cloud examples

fix point cloud examples

---

docs/layers/icon-layer.md
examples/website/icon/app.js
examples/website/icon/icon-cluster-layer.js
examples/website/point-cloud-laz/app.js
examples/website/point-cloud-ply/app.js
modules/layers/src/icon-layer/icon-layer.js
website/src/components/demos/icon-demo.js

- Make IconLayer prop `iconMapping` accept async input
- Wrap clustering logic into `IconClusterLayer`

IconLayer demo clean up

---

examples/website/trips/app.js

For #1873 
Trigger animation on component mount.
- Fix: Trigger trips-layer animation

Fix: Trigger trips-layer animation

---

examples/website/point-cloud-laz/app.js
examples/website/point-cloud-ply/app.js

For #1873 
- Change scale and point size

fix the scale and point size for point cloud examples

---

modules/core/src/utils/deep-equal.js
modules/core/src/views/view-manager.js
test/modules/core/utils/deep-equal.spec.js
test/modules/core/utils/index.js

- Fix bug where multi-view does not rerender
- Add tests

Fix view state comparison

---

modules/core/src/viewports/viewport.js
modules/core/src/viewports/web-mercator-viewport.js
test/apps/multi-viewport/app.js

- Fix missing `projectFlat` and `unprojectFlat` for first-person and third-person viewports
- Remove unused Viewport class methods
- Upgrade multi-viewport test app to new controller API

Fix first-person and third-person viewports

---

examples/layer-browser/package.json
examples/layer-browser/src/app.js

For https://github.com/uber/deck.gl/issues/1967
- Upgrade layer browser to v6 API

Upgrade layer browser to v6 API

---

modules/test-utils/src/scene-renderer.js
test/render/test-cases.js

For #2032 
- Disable icon layer test
- Remove logic to loading layers twice

fix rendering test

---

docs/api-reference/orbit-view.md
website/contents/pages.js

For #1985
- Add doc for OrbitView

add doc for OrbitView

---

examples/website/point-cloud-laz/app.js
examples/website/point-cloud-ply/app.js
modules/core/src/controllers/map-controller.js
modules/core/src/controllers/orbit-controller.js
test/apps/viewport-transitions-flyTo/src/app.js

For #2046
OrbitController: Add support for viewport transitions
Update `point-cloud-ply` to use linear transitions for rotation
- OrbitController: Add support for viewport transitions

OrbitController: Add support for viewport transitions

---

docs/get-started/learning-resources.md
docs/get-started/using-standalone.md
docs/get-started/using-with-react.md
docs/get-started/vis-academy.md
website/contents/pages.js
website/src/components/gallery.js

- Fix bug in documentation url handling
- Add missing pages
- Fix broken internal links
- Rename "Vis Academy" page to "Learning Resources"

Documentation minor fixes

---

examples/website/screen-grid/app.js
website/src/components/demos/screen-grid-demo.js

For #
- Use custom colorRange for ScreenGridDemo
- Change default cellSize to 5
- Use default cell margin  (2 pixels)
- Use custom colorRange for ScreenGridDemo

Use custom colorRange for ScreenGridDemo

---

website/package.json
website/src/main.js

For https://github.com/uber/deck.gl/issues/2070
Polyfill breaks async props (`fetch(...) instanceof Promise` returns `false`)
- Remove polyfill

Fix website in Firefox

---

docs/layers/arc-layer.md
docs/layers/geojson-layer.md
docs/layers/grid-cell-layer.md
docs/layers/hexagon-cell-layer.md
docs/layers/icon-layer.md
docs/layers/line-layer.md
docs/layers/path-layer.md
docs/layers/point-cloud-layer.md
docs/layers/polygon-layer.md
docs/layers/scatterplot-layer.md
docs/layers/solid-polygon-layer.md
docs/layers/text-layer.md
docs/upgrade-guide.md
modules/layers/src/arc-layer/arc-layer.js
modules/layers/src/geojson-layer/geojson-layer.js
modules/layers/src/grid-cell-layer/grid-cell-layer.js
modules/layers/src/hexagon-cell-layer/hexagon-cell-layer.js
modules/layers/src/icon-layer/icon-layer.js
modules/layers/src/line-layer/line-layer.js
modules/layers/src/path-layer/path-layer.js
modules/layers/src/point-cloud-layer/point-cloud-layer.js
modules/layers/src/polygon-layer/polygon-layer.js
modules/layers/src/scatterplot-layer/scatterplot-layer.js
modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer.js
modules/layers/src/text-layer/text-layer.js

- Use constants for default props
- Layer docs

Use constants for default props

---

examples/get-started/pure-js-without-map/package.json
examples/get-started/pure-js/package.json
examples/get-started/react-browserify/package.json
examples/get-started/react-webpack-2/package.json
examples/get-started/react-without-map/package.json
examples/layer-browser/package.json
examples/website/3d-heatmap/package.json
examples/website/arc/package.json
examples/website/brushing/package.json
examples/website/geojson/package.json
examples/website/highway/package.json
examples/website/icon/package.json
examples/website/line/package.json
examples/website/plot/package.json
examples/website/scatterplot/package.json
examples/website/screen-grid/package.json
examples/website/tagmap/package.json
examples/website/text-layer/package.json
examples/website/trips/package.json
modules/core/package.json
showcases/ascii/package.json
yarn.lock

- Bump luma.gl dependency to official release
- Bump example dependencies to official release

Bump dependency versions

---

modules/core/src/lib/attribute.js

For https://github.com/uber/deck.gl/issues/2069
- avoid mutating source data

Avoid mutating source data

---

modules/core/src/lib/layer-manager.js

For https://github.com/uber/deck.gl/issues/2103
- Pass `layerFilter` to `pickObject` and `pickObjects`

Fix layerFilter in picking

---

docs/upgrade-guide.md
test/apps/mapbox-tile/map-layer/map-layer.js
test/apps/mapbox-tile/map-layer/utils/tile-cache.js

For #2119 
- Should be cherry picked into 6.0
- upgrade guide now mentions luma.gl
- some prettier auto changes

Upgrade guide improvements

---

modules/layers/src/solid-polygon-layer/solid-polygon-layer.js

Fix solid-polygon-layer to work with new coordinate mode

---

modules/core/package.json

For #
Bump luma.gl and deck.gl to latest alpha.
- Bump luma.gl and math.gl versions to latest alpha.

Bump luma.gl and math.gl versions to latest alpha

---

test/apps/data-filter/package.json
test/apps/data-filter/src/app.js
test/apps/data-filter/src/data-filter.js
test/apps/data-filter/src/data-sample.js
test/apps/data-filter/src/scatterplot-layer.js
test/apps/data-filter/webpack.config.js

Implements RFC: https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v6.0/data-filter-rfc.md

[POC] Data filter shader module

---

modules/core/src/lib/layer.js

For https://github.com/uber/luma.gl/issues/621
**NOTE:** Depends on https://github.com/uber/luma.gl/pull/622
Remove setting shader module specific uniforms in `Layer` class.
- Remove module specific uniforms setting from Layer

Remove module specific uniforms setting from Layer

---

scripts/lint.sh
scripts/test.sh

- Automatically prettify changed files before commit
- Add linting to pre-commit check

Improve linting script

---

modules/core/package.json
modules/experimental-layers/README.md
modules/lite/package.json
modules/test-utils/package.json

- Fix build issues after fresh bootstrap
- Ensure correct dependencies
- Include Probe fix for changed webpack behavior

Build fixes

---

modules/layers/src/arc-layer/arc-layer-vertex.glsl.js
modules/layers/src/arc-layer/arc-layer.js
modules/layers/src/path-layer/path-layer-vertex.glsl.js
modules/layers/src/path-layer/path-layer.js

For https://github.com/uber/deck.gl/issues/1937
- ArcLayer
- PathLayer

Make ArcLayer and PathLayer work with LNGLAT_EXPERIMENTAL mode

---

dev-docs/RFCs/v6.1/json-layers-rfc.md
docs/api-reference/json/json-deck.md
docs/api-reference/json/json-layer.md
docs/whats-new.md
modules/json/README.md
modules/json/package.json
modules/json/src/index.js
modules/json/src/json-deck/json-deck.js
modules/json/src/json-layer/json-layer.js
modules/json/src/utils/deep-equal.js
modules/json/src/utils/get.js
modules/json/src/utils/shallow-equal-objects.js
test/modules/index.js
test/modules/json/index.js
test/modules/json/json-deck.spec.js
test/modules/json/json-layer.spec.js
test/modules/json/utils/deep-equal.spec.js
test/modules/json/utils/get.spec.js
test/modules/json/utils/shallow-equal-objects.spec.js
website/contents/pages.js
yarn.lock

- See RFC
- JSONLayer
- JSONDeck
- MapboxMap
- docs

JSON Layers RFC implementation #1 (of 2)

---

modules/test-utils/src/scene-renderer.js
test/render/test-cases.js

For #2097
- fix the icon layer rendering test
- avoid test report duplication

fix icon layer rendering test and avoid test report duplication

---

modules/core/package.json
modules/core/src/lib/attribute-transition-manager.js
showcases/wind/src/layers/particle-layer/particle-layer.js

For https://github.com/uber/luma.gl/issues/623
- Fix import name for `Transform`.
- Bump to required luma.gl version
- Fix Transform export, bump luma.gl version

Fix Transform export, bump luma.gl version

---

examples/experimental/json-layers/webpack.config.js
modules/core/package.json
modules/test-utils/package.json
test/apps/attribute-transition/package.json
test/apps/multi-viewport/package.json
test/apps/orthographic-zooming/package.json
test/apps/tree-shaking/package.json
yarn.lock

- Bump probe.gl to match luma.gl 
- dependency bumps

Bump dependency

---

dev-docs/RFCs/README.md
dev-docs/RFCs/v6.x/property-animation-rfc.md
dev-docs/roadmaps/animation-roadmap.md
dev-docs/roadmaps/layers-roadmap.md
dev-docs/roadmaps/performance-roadmap.md

Roadmap updates

---

dev-docs/roadmaps/lighting-roadmap.md

In order to implement a good lighting module, here I want to specify the initial development roadmap
- Lighting module development roadmap doc

lighting module initial roadmap

---

examples/get-started/pure-js-without-map/package.json

For https://github.com/uber/deck.gl/issues/2190
- Add missing dependency

Fix pure-js-without-map example

---

modules/core/src/lib/deck.js

For #2200 
- Pass through `opts`

Pass through opts in _createAnimationLoop's onCreateContext

---

docs/api-reference/web-mercator-viewport.md
docs/developer-guide/64-bits.md
docs/developer-guide/coordinate-systems.md
docs/developer-guide/performance.md
docs/developer-guide/writing-shaders.md
docs/layers/arc-layer.md
docs/layers/contour-layer.md
docs/layers/geojson-layer.md
docs/layers/grid-cell-layer.md
docs/layers/grid-layer.md
docs/layers/hexagon-cell-layer.md
docs/layers/hexagon-layer.md
docs/layers/icon-layer.md
docs/layers/line-layer.md
docs/layers/path-layer.md
docs/layers/point-cloud-layer.md
docs/layers/polygon-layer.md
docs/layers/scatterplot-layer.md
docs/layers/solid-polygon-layer.md
docs/layers/text-layer.md
docs/shader-modules/project.md
docs/whats-new.md

- Doc updates, across api-reference, developer-guide and whats-new
- As above

Update docs for new projection mode

---

modules/core/src/lib/draw-layers.js
modules/core/src/lib/view-manager.js

- Minor fixes after rebasing and landing several PRs

Small fixes

---

modules/experimental-layers/src/advanced-text-layer/advanced-text-layer.js
test/modules/core/experimental/lib/effect-manager.spec.js
test/render/old/test-rendering.react.js

Fixes #1989 
- Remove stray references to global module

Remove stray references to global module

---

docs/api-reference/deck.md
docs/api-reference/layer.md

Improve docs around setting parameters

---

docs/developer-guide/animations-and-transitions.md
docs/developer-guide/updates.md
docs/faq.md
website/contents/pages.js

Fixes #2123 Fixes #2204
For #2152 
-

Doc Updates: FAQ and Animation

---

modules/layers/src/index.js
modules/layers/src/path-layer/path-layer.js
modules/layers/src/solid-polygon-layer/solid-polygon-layer.js

For #
Cherry picking #1921 into 5.3-release branch.
-

Expose more internals (as experimental exports) (#1921)

---

docs/layers/contour-layer.md
docs/whats-new.md
modules/layers/src/contour-layer/contour-layer.js

Docs whats-new for #2126 #2086
- Docs and whats-new update

Docs and whats-new update

---

docs/whats-new.md
website/src/components/demos/layer-demos.js

For #2221
- Fix ContourLayer demo crash, use more appropriate strokeWidths.
- Fix whats-new gif table setup.
- 6.1 Docs : Misc changes

6.1 Docs : Misc changes

---

examples/layer-browser/src/examples/experimental-layers.js
modules/core/src/lib/layer-manager.js
modules/layers/src/hexagon-layer/hexagon-layer.js

For #2226 
Reverting the fix for #2111 as unit tests need some work, will merge after fixing unit tests.
- Revert "HexagonLayer: Aggregate data using valid viewport. (#2196)" 
- Comment out unused import

Hexagon layer change revert

---

modules/core/src/shaderlib/lighting/lighting.js

For https://github.com/uber/deck.gl/issues/2223
- Rewrite target coordinate system with lnglat offset parameters if in `LNGLAT_AUTO_OFFSET` mode

Fix lighting module under auto offset

---

modules/core/package.json
yarn.lock

For #
Bump luma to 6.1.0-beta.1
- Bump luma to 6.1.0-beta.1

Bump luma to 6.1.0-beta.1

---

modules/core/src/lib/draw-layers.js
test/apps/minimap/README.md
test/apps/minimap/app.js
test/apps/minimap/package.json
test/apps/minimap/webpack.config.js

For #
- Test app for the new "minimap" View class support.
- New test app

Example: minimap in cloned trips layer

---

dev-docs/PUBLISH-CHECKLIST.md

- Port internal publish guidelines to dev-docs

Add publish-guideline

---

dev-docs/PUBLISH-CHECKLIST.md

Add instructions for publishing JSON browser on website

---

.eslintignore
.prettierignore
examples/layer-browser/package.json
examples/webpack.config.local.js
modules/core/package.json
modules/experimental-layers/package.json
modules/json/package.json
modules/layers/package.json
modules/react/package.json
modules/test-utils/package.json
package.json
yarn.lock

For #2070 #2235
- Bump probe.gl

Safari fixes

---

modules/core/package.json
website/webpack.config.js
yarn.lock

For #2235
- Bump luma.gl to beta.4
- Refresh yarn.lock files
- Build website as production on release branch

Website fixes for Safari

---

modules/core/src/lib/layer-manager.js
modules/layers/src/hexagon-layer/hexagon-layer.js
modules/test-utils/src/lifecycle-test-deprecated.js
test/modules/layers/hexagon-layer.spec.js

For #2111
- Re-enable the changes from #2196 (It was reverted due to unit test failures)
- Fix unit tests.
- Re-enable the changes from #2196 (It was reverted due to unit test failures)
- Fix unit tests.

Hexagon aggregation with valid viewport

---

modules/experimental-layers/src/trips-layer/trips-layer.js

For #2255 
- Trips-layer: fix import

Trips-layer: fix import

---

modules/core/package.json
test/apps/multi-viewport/package.json
yarn.lock

For #2263 
#2263 
- Bump math.gl version

Bump math.gl version

---

modules/core/src/lib/constants.js
modules/core/src/lib/layer.js
modules/core/src/shaderlib/project/viewport-uniforms.js
test/modules/core/lib/layer.spec.js

Revert "Change Back Projection mode to the 6.0 default (#2225)"

Make LNGLAT_EXPERIMENTAL the new default projection mode

---

docs/contributing.md

I don't think you need the first "you" in this sentence in contributing.md
> Note that you once your PR is about to be merged, you will be asked to register
- Remove an extra "you" from contributing.md

Fix minor typo in contributing.md

---

docs/layers/icon-layer.md
docs/whats-new.md
modules/layers/src/icon-layer/icon-layer-fragment.glsl.js

For #2260 
- Change the logic in icon-layer-fragment shader

Use the alpha component from getColor when mask is turned off in IconLayer

---

modules/mapbox-layers/src/deck-layer.js
test/apps/mapbox-layers/.gitignore
test/apps/mapbox-layers/app-3d.js
test/apps/mapbox-layers/webpack.config.js

For https://github.com/uber/deck.gl/issues/2132

Fix 3d projection in Mapbox integration

---

test/modules/core/shaderlib/project/project-glsl.spec.js

For #2272 
Add `Transform` based unit tests for `project` module. Verified on AMD and INTEL GPUs.
- Add Transform based GPU tests for project module.

Add Transform based GPU tests for project module.

---

modules/core/src/lib/deck.js
modules/mapbox-layers/src/deck-layer.js
modules/mapbox-layers/src/deck-utils.js
test/apps/mapbox-layers/app.js

For https://github.com/uber/deck.gl/issues/2132
- Add custom animation loop for transition/async/animation updates
- Subscribe to Mapbox's pointer events

Support picking and transition in mapbox integration

---

.eslintignore
test/modules/json/json-converter.spec.js

Fix Browser Test

---

showcases/wind/src/layers/delaunay-interpolation/delaunay-interpolation.js
showcases/wind/src/layers/particle-layer/particle-layer.js

For #
Updated wind demo code to latest luma.gl Buffer API, fix a typo.
- WindDemo: Updated to latest luma.gl API

WindDemo: Updated to latest luma.gl Buffer API, fix a typo.

---

modules/mapbox/src/deck-utils.js
test/apps/mapbox-layers/README.md
test/apps/mapbox-layers/app.js
test/apps/mapbox-layers/layers.js
test/apps/mapbox-layers/package.json
test/apps/mapbox-layers/react-app.js
test/apps/mapbox-layers/webpack.config.js

For #2132 	
Depends on https://github.com/uber/react-map-gl/pull/603

Add React example for Mapbox custom layer API

---

dev-docs/RFCs/v6.x/lighting-rfc.md
dev-docs/RFCs/v6.x/phong-lighting-rfc.md

For #2096
First RFC to improve our lighting model which has a lot of limits
- new RFC doc

Lighting RFC

---

dev-docs/RFCs/v6.x/gpu-aggregation-enhancements.md
docs/api-reference/mapbox/mapbox-layer.md
docs/api-reference/mapbox/overview.md

For #2291 
- GPUGridAggregator: Enhancements RFC

GPUGridAggregator: Enhancements RFC

---

dev-docs/RFCs/README.md
dev-docs/RFCs/v6.x/event-handling-rfc.md

For https://github.com/uber/deck.gl/issues/2099
- See RFC
- RFC catalog
- Advanced event handling RFC

Add advanced event handling RFC

---

examples/get-started/pure-js-without-map/package.json
examples/get-started/pure-js/package.json
examples/get-started/react-browserify/package.json
examples/get-started/react-webpack-2/package.json
examples/get-started/react-without-map/package.json
examples/json-browser/pure-js-app/package.json
examples/json-browser/react-app/package.json
examples/layer-browser/package.json
examples/website/3d-heatmap/package.json
examples/website/arc/package.json
examples/website/brushing/package.json
examples/website/geojson/package.json
examples/website/highway/package.json
examples/website/icon/package.json
examples/website/line/package.json
examples/website/plot/package.json
examples/website/point-cloud-laz/package.json
examples/website/point-cloud-ply/package.json
examples/website/scatterplot/package.json
examples/website/screen-grid/package.json
examples/website/tagmap/package.json

For #2325
- update deck.gl version in dependencies

fixed versions in dependencies of examples

---

docs/upgrade-guide.md
docs/whats-new.md

- v6.2 what's new
- v6.2 upgrade guide

6.2 what's new and upgrade guide

---

modules/core/src/controllers/orthographic-controller.js

For #2274 
- Implemented a new zoom logic

improve orthographic zoom

---

examples/gallery/src/mapbox-layer.html
test/apps/mapbox-layers/app.js
test/apps/mapbox-layers/package.json
test/apps/mapbox-layers/webpack.config.js

- Remove manually built mapbox versions

Upgrade Mapbox integration examples to latest release

---

modules/mapbox/src/mapbox-layer.js

- Fix crash when setProps is called before onAdd

MapboxLayer.setProps bug fix

---

docs/upgrade-guide.md

For #2240 
- Fix upgrade guide

Fix upgrade guide

---

docs/README.md
website/contents/links.js

...so newcomers to the docs may notice it.
For #
Feature editing capabilities are one of the things some people might look for or ask when they come across deck.gl.
- Added nebula.gl to the links rendered in the doc website header
- Added nebula.gl mention in the doc intro

Added nebula.gl to docs intro and website header

---

modules/core/src/controllers/controller.js
modules/core/src/experimental/utils/gpu-grid-aggregation/gpu-grid-aggregator.js
modules/core/src/lib/attribute-manager.js
modules/core/src/lib/layer-manager.js
modules/core/src/lib/layer.js
modules/core/src/lifecycle/component-state.js
modules/core/src/lifecycle/create-props.js
modules/core/src/shaderlib/project/viewport-uniforms.js
modules/core/src/utils/scale-utils.js
modules/layers/src/arc-layer/arc-layer.js
modules/layers/src/line-layer/line-layer.js

`log.*` returns a function and must be called
- Fix log usage
- Fix AttributeManager console error

Fix log usage

---

examples/website/trips/package.json

For #2366 
- fixed the dependency issue in tripslayer example

fixed the dependency issue in tripslayer example

---

docs/developer-guide/prop-types.md
modules/core/src/lib/layer.js
modules/core/src/lifecycle/prop-types.js
modules/core/src/lifecycle/props.js
modules/react/src/utils/extract-jsx-layers.js
test/modules/core/lib/layer.spec.js
test/modules/core/lifecycle/prop-types.spec.js
test/modules/core/lifecycle/props.spec.js
website/contents/pages.js

For https://github.com/uber/deck.gl/issues/1371
- Implement prop types
- Update prop diffing to use prop type equal functions
- Use prop types in base Layer default props

Implement prop types RFC

---

modules/experimental-layers/src/trips-layer/trips-layer.js

For https://github.com/uber/deck.gl/issues/2368

Fix trips layer getColor update trigger

---

test/bench/browser.js

For #
- Fix bench-browser script

Fix bench-browser script

---

dev-docs/RFCs/v6.x/gpu-aggregation-enhancements.md

For #2291 
- Change `weights` from array to object, where `key` can be used as unique id, `results` object uses same keys to return aggregated data.
- Split `needMinMax` into `needMin` and `needMax`, applications may only want `max` values, so can just set `needMax` to true and avoid extra rendering loop for calculating min values.
- Add more details on how data is formatted into R, G, B and Alpha channels.
- RFC Update: GPU Aggregation enhancements

RFC Update: GPU Aggregation enhancements

---

modules/lite/package.json
yarn.lock

For #
`lite` module is not being published yet, and `lerna` is configured to ignore it. Remove old dependencies to avoid version conflicts.
- Remove dependencies from lite module

Remove dependecies from lite module

---

modules/core/package.json

Upgrade luma.gl to v5.3.1 for including the fix https://github.com/uber/luma.gl/pull/760

Upgrade luma.gl to v5.3.1

---

modules/core/src/experimental/utils/gpu-grid-aggregation/aggregate-all-fs.glsl.js
modules/core/src/experimental/utils/gpu-grid-aggregation/aggregate-to-grid-fs.glsl.js
modules/core/src/experimental/utils/gpu-grid-aggregation/aggregate-to-grid-vs-64.glsl.js
modules/core/src/experimental/utils/gpu-grid-aggregation/aggregate-to-grid-vs.glsl.js
modules/core/src/experimental/utils/gpu-grid-aggregation/gpu-grid-aggregator-constants.js
modules/core/src/experimental/utils/gpu-grid-aggregation/gpu-grid-aggregator-utils.js
modules/core/src/experimental/utils/gpu-grid-aggregation/gpu-grid-aggregator.js
modules/core/src/experimental/utils/gpu-grid-aggregation/grid-aggregation-utils.js
modules/core/src/index.js
modules/experimental-layers/src/gpu-grid-layer/gpu-grid-cell-layer-vertex.glsl.js
modules/experimental-layers/src/gpu-grid-layer/gpu-grid-layer.js
modules/layers/src/contour-layer/contour-layer.js
modules/layers/src/screen-grid-layer/screen-grid-layer-vertex.glsl.js
modules/layers/src/screen-grid-layer/screen-grid-layer.js
test/bench/gpu-grid-aggregator.bench.js
test/data/grid-aggregation-data.js
test/modules/core/experimental/utils/gpu-grid-aggregator.spec.js
test/modules/core/experimental/utils/grid-aggregation-utils.spec.js
test/render/test-cases.js

For #2291
[RFC](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v6.x/gpu-aggregation-enhancements.md)
- GPU Aggregation Enhancements: core changes
- GPU Aggregation Enhancements: update ScreenGridLayer
- GPU Aggregation Enhancements: update GPUGridLayer
- GPU Aggregation Enhancements: update ContourLayer
- GPU Aggregation Enhancements: Tests

GPU aggregator enhancements

---

modules/mapbox/src/deck-utils.js
modules/mapbox/src/mapbox-layer.js

- Enable depth test before drawing non-mapbox layers
- Set view state before drawing non-mapbox layers

[@deck.gl/mapbox] Reset context state before drawing non-mapbox layers

---

modules/core/package.json

Bump math.gl version to 2.2.0
- Bump math.gl version to 2.2.0

Bump math.gl version to 2.2.0

---

docs/api-reference/composite-layer.md
docs/api-reference/layer.md
docs/get-started/interactivity.md
modules/core/src/lib/layer-manager.js
modules/core/src/lib/pick-layers.js
yarn.lock

For #
Currently, we are using the prop name _lngLat_ to surface the world coordinate from the picked info object, which can be confusing to non-geospatial use cases.
- renamed _lngLat_ to _coordinate_
- kept the lngLat prop for compatibility
- updated docs

rename lngLat to coordinate in pickInfo for non-geo use cases

---

test/modules/core/shaderlib/project/project-32-64-glsl.spec.js

For #
Disable randomly failing 64bit project tests on Intel GPUs
- Disable randomly failing 64bit project tests on Intel GPUs

Disable randomly failing 64bit project tests on Intel GPUs

---

modules/core/src/experimental/utils/gpu-grid-aggregation/gpu-grid-aggregator.js
modules/core/src/experimental/utils/gpu-grid-aggregation/gpu-grid-aggregator.md
modules/layers/src/screen-grid-layer/screen-grid-layer-vertex-webgl1.glsl.js
modules/layers/src/screen-grid-layer/screen-grid-layer.js

For #2291
- ScreenGridLayer: fix webgl1 shader
- Rename aggregation fields to match with newer API (no functional change)
- Add aggregator documentation page

ScreenGridLayer fixes

---

modules/experimental-layers/src/index.js
test/apps/mapbox-tile/app.js

- Export TileLayer from experimental layers

Export TileLayer from experimental layers

---

docs/layers/arc-layer.md
docs/upgrade-guide.md
package.json
scripts/update-release-branch.sh

```
npm run update-release branch 6.3
```
Will update:
- Dependencies in `examples/(website|exprimental|get-started)/*/package.json`
- Source code links in `docs/**/*.md`
- Doc and code links in website

Add release branch update script

---

docs/api-reference/map-view.md
docs/api-reference/orthographic-view.md
modules/core/src/controllers/orthographic-controller.js

minZoom and maxZoom should not be hard-coded.
- OrthographicController
- docs

Allow user to change min/max zoom of the orthographic controller

---

docs/layers/polygon-layer.md

For https://github.com/uber/deck.gl/issues/2435
@SymbolixAU @mdsumner

Update PolygonLayer documentation

---

modules/core/src/shaderlib/project/project.glsl.js

For #2454 
- Do not apply 2nd-order adjuster if offsetY is larger than 1 degree or 110km (~1 degree)

Fix offset mode bug

---

modules/core/package.json
modules/core/src/deprecated/orbit-viewport.js
modules/core/src/shaderlib/project/project-functions.js
modules/core/src/shaderlib/project/viewport-uniforms.js
modules/core/src/utils/math-utils.js
modules/core/src/viewports/viewport.js
modules/core/src/viewports/web-mercator-viewport.js
modules/core/src/views/orbit-view.js
modules/core/src/views/perspective-view.js
test/modules/core/viewports/viewport.spec.js
yarn.lock

Ref https://github.com/uber-web/math.gl/pull/34

Replace gl packages with original gl-matrix

---

modules/mapbox/src/deck-utils.js

For https://github.com/uber/deck.gl/issues/2461

[@deck.gl/mapbox] Do not override canvas size if using external gl context

---

docs/get-started/interactivity.md
docs/layers/arc-layer.md
docs/layers/geojson-layer.md
docs/layers/grid-layer.md
docs/layers/hexagon-layer.md
docs/layers/icon-layer.md
docs/layers/line-layer.md
docs/layers/path-layer.md
docs/layers/point-cloud-layer.md
docs/layers/polygon-layer.md
docs/layers/scatterplot-layer.md
docs/layers/screen-grid-layer.md
docs/layers/text-layer.md

For https://github.com/uber/deck.gl/issues/1861
- Add tooltip examples to "adding interactivity" page
- Update each layer example with link

Update layer docs regarding tooltip display

---

modules/experimental-layers/src/tile-layer/tile-layer.js
modules/experimental-layers/src/tile-layer/tile-layer.md
modules/experimental-layers/src/tile-layer/utils/tile-cache.js
modules/experimental-layers/src/tile-layer/utils/tile.js
test/modules/experimental-layers/tile-layer/tile-cache.spec.js

Add callback function -- `onDataLoaded` in TileLayer, which is called when all tiles in the viewport are loaded.

Add callback function onDataLoaded in TileLayer

---

package.json
test/modules/core/shaderlib/project/project-32-64-glsl.spec.js
test/modules/core/shaderlib/shaderlib-test-utils.js
yarn.lock

- Bump glsl-transpiler version, remove hacks for fixed issues
- Enable transpiled shader test for all test cases

Fix fp64 shader tests

---

.babelrc
package.json
yarn.lock

Saves ~6K in standalone bundle

Strip glsl comments

---

modules/core/src/index.js
modules/core/src/utils/tesselator.js
modules/experimental-layers/src/path-outline-layer/path-outline-layer.js
modules/layers/src/path-layer/path-layer.js
modules/layers/src/path-layer/path-tesselator.js
modules/layers/src/path-layer/tesselator.js
test/modules/layers/index.js
test/modules/layers/path-tesselator.spec.js

Preparation For #2492 
- Refactor PathLayer attribute generation into `PathTesselator` class
- Add tests

PathTesselator class

---

docs/api-reference/deck.md
docs/layers/grid-cell-layer.md
docs/layers/hexagon-cell-layer.md
website/contents/pages.js

For
https://github.com/uber/deck.gl/issues/2482
https://github.com/uber/deck.gl/issues/2527
- Document `controller` prop for the `Deck` class
- Add the documentations of `HexagonCellLayer` and `GridCellLayer` to website

Documentation updates

---

docs/layers/contour-layer.md
examples/layer-browser/src/examples/core-layers.js
modules/layers/src/contour-layer/contour-layer.js
modules/layers/src/contour-layer/marching-squares.js
website/src/components/demos/layer-demos.js

For # as per API Audit
Replace `zOffsetScale` with `zOffset`
- ContourLayer: zOffsetScale -> zOffset

ContourLayer: zOffsetScale -> zOffset

---

website/src/components/markdown-page.js

- Add anchors for h4 and h5 headers
- Fix: url query parameter is sometimes not updated during scroll
- Fix: does not scroll back to top when switching pages

Fix website anchor handling

---

modules/experimental-layers/src/bezier-curve-layer/README.md

For #2477 
In bezier curve layer, the default props are updated. We need to update the documentation
- update readme file

update readme for bezier curve layer

---

examples/website/point-cloud-laz/package.json
examples/website/point-cloud-ply/package.json
examples/website/tagmap/package.json
examples/website/text-layer/package.json
showcases/wind/package.json
test/apps/carto-wip/package.json
test/apps/viewport-transitions-flyTo/package.json
test/apps/viewport-transitions/package.json

For #2558 
Old webpack-dev-server version causes security vulnerabilities in the dependencies of some examples. We need to upgrade it's version
- upgrade webpack-dev-server version to `^3.1.11`

update webpack-dev-server versions

---

docs/api-reference/layer.md

For #2571 
Wrong symbol used in the documentation(layer.md). This causes eslint to fail when commit.
- change asterisk to dash

update the format of doc

---

examples/experimental/bitmap/README.md

Update README.md: "Later" -> "Layer"

---

docs/layers/geojson-layer.md
docs/layers/scatterplot-layer.md
modules/layers/src/geojson-layer/geojson-layer.js
modules/layers/src/scatterplot-layer/scatterplot-layer-fragment.glsl.js
modules/layers/src/scatterplot-layer/scatterplot-layer-vertex.glsl.js
modules/layers/src/scatterplot-layer/scatterplot-layer.js

For #2544 
update APIs for 7.0 release
- add new APIs
- remove deprecated APIs
- update documentation
note: tested in layer browser, render test and picking test

allow ScatterplotLayer to draw both stroke and fill

---

modules/core/package.json
yarn.lock

The IconLayer change triggered a bug in luma.gl's `loadTextures`.
- Bump luma version

Fix render test

---

modules/layers/src/hexagon-cell-layer/hexagon-cell-layer.js
modules/layers/src/hexagon-layer/hexagon-layer.js

For #2584 
- Use the prop type system for validation and fallback

Fix HexagonLayer constructors

---

modules/core/src/utils/globals.js

For #2530 
See [thread](https://github.com/uber-web/mjolnir.js/pull/20).
- Remove `module.exports`

Fix Rollup bundling

---

examples/gallery/build-tools/page.html
examples/gallery/build-tools/utils.js
examples/gallery/src/boiler-plate.html
examples/gallery/src/geojson-layer.html

For #2597 
- Generate dynamic URL for iframe src
- Fix boiler plate example size
- Fix geojson example lighting

Fix gallery in Firefox

---

modules/mapbox/src/deck-utils.js

For https://github.com/uber/deck.gl/issues/2602
- Reset GL context before drawing picking buffer

Fix occasional picking failure in mapbox layer

---

modules/layers/src/text-layer/font-atlas.js

For #2577 
- Safe guard default character set generation against optimization

Fix Angular build

---

docs/layers/scatterplot-layer.md
modules/layers/src/scatterplot-layer/scatterplot-layer.js

For #2573 
- update the default value of lineWidthMinPixels and radiusMinPixels to 1

update default values in scatterplot layer

---

dev-docs/RFCs/vNext/text-layer-font-setting-api.md

For #1550 
- add text layer api change RFC

add text layer api change RFC

---

examples/website/geojson/app.js
modules/core/src/effects/lighting-effect.js
modules/core/src/index.js
modules/core/src/lib/draw-layers.js
modules/core/src/lighting/point-light.js
modules/core/src/shaderlib/project/project-functions.js
modules/main/src/index.js

For #2096 
- Provide the right coordinate system for point lights projection
- Improve comment for projectPosition function

fix projection for point lights

---

examples/website/brushing/app.js
website/src/main.js

For #2623 
- Fix target rings in brushing example
- Add polyfill to website for IE

Website issue fixes

---

docs/api-reference/deck.md

updated docs with a note about getCursor

---

modules/core/package.json
modules/experimental-layers/package.json
modules/experimental-layers/src/bitmap-layer/bitmap-layer.js
modules/experimental-layers/src/mesh-layer/mesh-layer.js
modules/layers/package.json
modules/layers/src/icon-layer/icon-manager.js
yarn.lock

- Replace the removed `loadTextures` and `loadImages` utilities with loaders.gl

Upgrade to the latest  luma.gl API

---

modules/core/src/controllers/controller.js
modules/core/src/controllers/map-controller.js
modules/core/src/controllers/orthographic-controller.js

Don't use invertPan flag in _onPanRotate method

---

docs/developer-guide/viewports.md

additin -> addition

---

examples/layer-browser/package.json
examples/layer-browser/src/app.js
examples/layer-browser/src/examples/experimental-layers.js
modules/experimental-layers/src/index.js
modules/experimental-layers/src/scenegraph-layer/scenegraph-layer.js

For supporting glTF and other formats.
- Add ScenegraphLayer

Add ScenegraphLayer with Demo

---

modules/core/src/lib/deck-picker.js
modules/core/src/lib/deck-renderer.js
modules/core/src/lib/deck.js
modules/core/src/lib/layer-manager.js
modules/core/src/lib/layer.js
modules/core/src/utils/pick-info.js
modules/core/src/utils/pixel-ratio.js
modules/core/src/utils/query-object.js

For #2662 
- Integrate new DeckPicker to deck

Refactor picking workflow (2/2)

---

test/bench/pick-layers.bench.js
test/bench/tesselation.bench.js

For #2662
- use the new picking API
- fix the wrong tesselator import

fix broken picking API bench test

---

dev-docs/code-guidelines.md

Update coding guidelines to allow ES2018

---

modules/core/package.json
modules/core/src/effects/lighting-effect.js
modules/core/src/lib/deck-renderer.js
modules/core/src/lib/deck.js
modules/core/src/lib/effect-manager.js
modules/core/src/lib/effect.js
modules/core/src/passes/draw-layers-pass.js
modules/core/src/passes/layers-pass.js
yarn.lock

For #2096 
- integrate effects
- project point light source

integrate lighting effect

---

website/src/components/demos/icon-demo.js
website/src/static/markdown/showcase.md

For #2739 
- Lack of space between words was fixed;
- Links to repositories were updated;
- Link to kepler.gl example that matches the picture was created;

Small UI fixes and updates on the website

---

docs/developer-guide/views.md

For #2748
- In the docs: getViewport -> makeViewport
I confirmed that this fixes the example in codepen.

getViewport -> makeViewport

---

docs/layers/arc-layer.md
modules/layers/src/arc-layer/arc-layer.js

For #2545
update ArcLayer APIs for 7.0-release
- modify the doc and deprecated props

modify doc and deprecated props in ArcLayer

---

aliases.js

Fix module alias error when switching branches

---

examples/experimental/json-common/examples/3d-heatmap.json
examples/experimental/json-common/examples/geojson.json
examples/gallery/src/geojson-layer.html
examples/gallery/src/hexagon-layer.html
examples/gallery/src/point-cloud-layer.html
examples/layer-browser/src/examples/additional-layers.js
examples/layer-browser/src/examples/core-layers.js
examples/layer-browser/src/examples/infovis-layers.js
examples/layer-browser/src/examples/perf-layers.js
examples/website/3d-heatmap/app.js
examples/website/trips/app.js
modules/core/package.json
website/src/components/demos/layer-demos.js

For #2096 
- remove lightSettings prop
- update probe.gl version to avoid crash
- fix wrong contour layer import

Remove lightSettings prop in examples and website

---

docs/get-started/getting-started.md
docs/get-started/using-with-mapbox-gl.md
modules/json/package.json
modules/layers/package.json
modules/react/package.json
modules/test-utils/package.json

For #2736 
- Dependency audit for submodules
- Update documentation

Move cross-submodule deps to peer dependencies

---

babel.config.js
examples/webpack.config.local.js
package.json
test/apps/webpack.config.local.js
yarn.lock

Follow up of #2764 
- Fix `yarn start-local` in examples and test apps

Fix start-local commands

---

scripts/bundle.config.js
scripts/extract-types.js
website/webpack.config.js

Fix additional alias imports

---

modules/aggregation-layers/src/grid-layer/grid-aggregator.js
modules/aggregation-layers/src/hexagon-layer/hexagon-aggregator.js
modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer.js
modules/layers/src/arc-layer/arc-layer.js
modules/layers/src/grid-cell-layer/grid-cell-layer.js
modules/layers/src/hexagon-cell-layer/hexagon-cell-layer.js
modules/layers/src/icon-layer/icon-layer.js
modules/layers/src/icon-layer/icon-manager.js
modules/layers/src/line-layer/line-layer.js
modules/layers/src/point-cloud-layer/point-cloud-layer.js
modules/layers/src/polygon-layer/polygon-layer.js
modules/layers/src/text-layer/text-layer.js

For #2665 
- Support non-iterable data in all core layers

Implement binary data RFC (PR 2/3)

---

modules/aggregation-layers/package.json

Fix missed push in previous PR

---

modules/layers/src/icon-layer/icon-manager.js

Fix IconLayer autopacking: generate mipmap when constructing Texture

---

test/bench/attribute-update.bench.js
test/bench/index.js

For #2665 
**ITERATION (1M)**
├─ Baseline#iterate plain array: 1.34K iterations/s ±25.61%
├─ Context#Plain array#Iterator: 45.8 iterations/s ±2.83%
├─ Context#Plain array#Inline: 968 iterations/s ±0.83%
├─ Context#Plain array#forEach: 79.4 iterations/s ±6.94%
├─ Context#Non-iterable#Iterator: 94.8 iterations/s ±2.43%
├─ Context#Non-iterable#Inline: 805 iterations/s ±8.27%
├─ Context#Non-iterable#forEach: 85.2 iterations/s ±1.50%
**ATTRIBUTE UPDATE (100K)**
├─ Baseline#plain accessor: 14.6 iterations/s ±2.46%
├─ Baseline#create small objects: 15.1 iterations/s ±1.63%
├─ Context#user target array: 14.4 iterations/s ±2.83%

Add benchmarks for attribute update

---

website/src/static/markdown/showcase.md

For #2773
- A typo in showcases "Autonomous Visuaization System" was fixed;
- In showcases, links from menu open in a new tab, but links in image or text open in the current tab. All  of them now open in a new tab;

Fixes in showcases and documentation UI

---

docs/api-reference/layer.md
modules/core/src/lib/deck.js
modules/core/src/lib/layer-manager.js

Add deck.gl instance to layer context

---

modules/layers/src/path-layer/path-tesselator.js
modules/layers/src/solid-polygon-layer/polygon-tesselator.js
modules/test-utils/src/generate-layer-tests.js
test/modules/layers/core-layers.spec.js
test/modules/layers/polygon-layer.spec.js

- All accessors should be called with two arguments
- Tests

Fix non-iterable support in tesselators

---

babel.config.js
package.json
scripts/bundle.config.js
yarn.lock

h3-js is about 150KB and s2-geometry is about 15KB. @nrabinowitz is it possible to include h3 separately with a `<script>` tag?
- Inline WebGL constants
- Exclude H3 and S2 from bundle

Improve bundle size

---

babel.config.js
docs/layers/arc-layer.md
docs/layers/great-circle-layer.md
examples/layer-browser/src/examples/additional-layers.js
modules/geo-layers/src/great-circle-layer/great-circle-layer.js
modules/geo-layers/src/great-circle-layer/great-circle-vertex.glsl.js
test/modules/geo-layers/great-circle-layer.spec.js

- Update vertex shader to match the new ArcLayer API
- Add documentation
- Tests

GreatCircleLayer Fixes

---

.prettierignore
docs/upgrade-guide.md
docs/whats-new.md

Feel free to push to this branch.

[WIP] 7.0 what's new and upgrade guide

---

examples/website/3d-heatmap/app.js
examples/website/trips/app.js
modules/core/src/index.js

For #2833 
- update lighting of trips layer example
- update lighting of 3d heatmap example

Update lighting of examples

---

modules/core/src/lib/pick-layers.js

Set picking color only when hovering

---

modules/layers/src/icon-layer/icon-layer-vertex.glsl.js
modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer-vertex.glsl.js

Minor fix projection in IconLayer and TextLayer

---

examples/layer-browser/src/app.js
modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-cell-layer.js
modules/core/package.json
modules/core/src/shaderlib/index.js
modules/layers/src/column-layer/column-layer.js
modules/layers/src/point-cloud-layer/point-cloud-layer.js
modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer-fragment.glsl.js
modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer-vertex.glsl.js
modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js
yarn.lock

For #2833 
- Add module dependency
- Change shaders with lighting APIs

Integrate lighting in mesh layer

---

examples/experimental/bezier/src/app.js
examples/website/plot/app.js
modules/core/src/controllers/controller.js
modules/core/src/controllers/map-controller.js
modules/core/src/controllers/orbit-controller.js
modules/core/src/controllers/orthographic-controller.js

Additional clean ups of the controllers
- Move map-specific rotation logic into `MapController`
- Support keyboard navigation and transition in both `OrbitController` and `OrthographicController`

Clean up controller classes

---

examples/webpack.config.local.js

- Use babel-loader (layer-browser does not have buble)
- Add missing alias (@luma.gl/shadertools)

Fix layer-browser configs

---

docs/api-reference/lights/ambient-light.md
docs/api-reference/lights/directional-light.md
docs/api-reference/lights/point-light.md
docs/developer-guide/using-lighting.md
docs/effects/lighting-effect.md
docs/layers/column-layer.md
docs/layers/geojson-layer.md
docs/layers/gpu-grid-layer.md
docs/layers/grid-cell-layer.md
docs/layers/grid-layer.md
docs/layers/h3-hexagon-layer.md
docs/layers/hexagon-layer.md
docs/layers/point-cloud-layer.md
docs/layers/polygon-layer.md
docs/layers/simple-mesh-layer.md
docs/layers/solid-polygon-layer.md
docs/upgrade-guide.md
website/contents/pages.js

For #2833 
- New docs
- Add entries in website

New Lighting docs

---

docs/layers/scenegraph-layer.md
modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js

ScenegraphLayer delete() Scenegraph

---

docs/api-reference/internal/layer-manager.md

Update internal layer manager doc after code refactor
- update doc

update layer manager doc

---

docs/layers/column-layer.md
docs/layers/grid-cell-layer.md
docs/layers/s2-layer.md
examples/layer-browser/src/examples/core-layers.js
modules/layers/src/column-layer/grid-cell-layer.js
website/src/components/demos/layer-demos.js

For v7.0 release, fix and add missing embed demos.
- Add ColumnLayerDemo, GridCellDemo, S2LayerDemo
ColumnLayerDemo
GridCellDemo
S2LayerDemo

Add missing website demos

---

examples/website/point-cloud-laz/app.js

Fix point cloud example for the OribitView change

---

modules/core/src/effects/lighting-effect.js

use light type instead of constructor name

---

dev-docs/RFCs/v7.0/google-maps-integration.md

Draft: google maps module RFC

---

docs/layers/great-circle-layer.md
docs/layers/simple-mesh-layer.md
modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-cell-layer.js
modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-layer.js
website/contents/pages.js
website/src/components/demos/aggregation-layer-demos.js
website/src/components/demos/geo-layer-demos.js
website/src/components/demos/index.js
website/src/components/demos/layer-demos.js

7.0 audit
- split layer-demos to layer catalog demos
- reorg layer docs
- add GreatCircleLayer demo

Add layer docs Catalog and GreatCircleLayer Demo

---

docs/layers/simple-mesh-layer.md
modules/core/package.json
modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js
yarn.lock

Wireframe option for SimpleMeshLayer.

SimpleMeshLayer wireframe

---

docs/layers/simple-mesh-layer.md
examples/layer-browser/package.json
examples/layer-browser/src/examples/additional-layers.js
modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js

- Support loading mesh via loaders.gl
- Remove requirement of uvs.

Loader.gl mesh loading

---

modules/core/package.json
modules/core/src/lib/deck-picker.js
modules/core/src/passes/pick-layers-pass.js
test/modules/core/index.js
test/modules/core/passes/index.js
test/modules/core/passes/pick-layers-pass.spec.js
yarn.lock

For #2833 
- add empty light source for picking
- add test

disable lighting in picking pass

---

modules/core/src/shaderlib/project/project.glsl.js

For #2833 
Fix a bug in projectNormal API
- add auto_offset mode

fix project normal

---

examples/website/mesh/README.md
examples/website/mesh/app.js
examples/website/mesh/index.html
examples/website/mesh/package.json
examples/website/mesh/webpack.config.js

- Add an example for SimpleMeshLayer.

Add SimpleMeshLayer example

---

website/src/components/demos/heatmap-demo.js

The data format feeding from `HexagonLayer` into `ColumnLayer` has changed.

Fix heatmap demo in website

---

docs/README.md
docs/upgrade-guide.md

For #2892 
- Remove references older minor releases documentation, just keep major releases for v4 and v5.
- Fix subheadings in upgrade guide page.
- Minor Doc changes

Minor Doc changes

---

examples/website/mesh/app.js
examples/website/mesh/package.json

- Bump dependency to a working version of loaders.gl
- Use a slightly smaller sample to save bandwidth

Update mesh example

---

docs/get-started/using-standalone.md

**Fixed docs to be more hello-world friendly for standalone**
Makes the red dot visible (at zoom 3 or 1 it was not visible) #2935 
For #2935

Fixed standalone example

---

docs/layers/geojson-layer.md

Fixed a quick typo, error is clear in diff

Fix typo in geojson-layer docs

---

.gitignore
modules/aggregation-layers/package.json
modules/core/package.json
modules/geo-layers/package.json
modules/google-maps/package.json
modules/json/package.json
modules/layers/package.json
modules/main/package.json
modules/mapbox/package.json
modules/mesh-layers/package.json
scripts/bundle.config.js

Move dev scripts out of module roots

---

modules/core/package.json
modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer-fragment.glsl1.js
yarn.lock

Required a fix the the SimpleMeshLayer shaders.

Update luma version to beta 8

---

docs/api-reference/lights/sunlight.md
modules/core/src/effects/lighting/suncalc.js
modules/core/src/effects/lighting/sunlight.js
modules/core/src/index.js
test/modules/core/effects/index.js
test/modules/core/effects/lighting/sunlight.spec.js
test/modules/core/index.js

v7.0 audit
- Add sunlight class
- Add unit test
- Add doc

Add sunlight effect

---

docs/developer-guide/custom-layers/composite-layers.md
docs/developer-guide/custom-layers/picking.md
docs/developer-guide/custom-layers/primitive-layers.md
docs/developer-guide/custom-layers/subclassed-layers.md
docs/developer-guide/custom-layers/writing-shaders.md

- Update the description of event system & prop forwarding to match the latest API
- Replace outdated examples

Update custom layer docs

---

modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js

clean up unused and duplicated code
- clean up

clean up in mesh layer

---

docs/api-reference/lights/camera-light.md
docs/api-reference/lights/directional-light.md
docs/api-reference/lights/point-light.md
docs/api-reference/lights/sun-light.md
docs/effects/lighting-effect.md
modules/core/src/effects/lighting/sun-light.js
modules/core/src/index.js
website/contents/pages.js

For #2833 
- update links
- change Sunlight to SunLight

Update lighting doc links in website

---

modules/core/package.json
modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js
yarn.lock

- Update luma version: fixes deletion of input mesh properties.
- Fix hasNormals check for meshes without "attributes" property.

SimpleMeshLayer bug fixes

---

modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer-vertex-webgl1.glsl.js

Fix screen grid layer crash in safari

---

examples/website/line/app.js
website/src/components/demos/layer-demos.js
website/src/components/demos/line-demo.js

For #2892 
- replace getStrokeWidth

replace getStrokeWidth with getWidth

---

website/contents/pages.js

For #2892 
- improve the regular expression

fix gpu grid layer link

---

docs/layers/screen-grid-layer.md
modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer.js
modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.js
website/contents/pages.js
website/src/components/demos/aggregation-layer-demos.js

For #2892 
- remove deprecated APIs
- update doc

Remove deprecated APIs and update doc

---

docs/developer-guide/custom-layers/subclassed-layers.md
examples/website/plot/plot-layer/axes-layer.js
examples/website/plot/plot-layer/surface-layer.js
examples/website/trips/app.js
website/src/components/demos/layer-demos.js

For #2892 
- update doc link
- remove deprecated APIs

fix website warnings

---

modules/core/src/lib/base-attribute.js

Fix buffer warnings

---

modules/core/src/experimental/utils/gpu-grid-aggregation/gpu-grid-aggregator.js
modules/core/src/experimental/utils/gpu-grid-aggregation/grid-aggregation-utils.js
modules/core/src/index.js
modules/core/src/utils/iterable-utils.js
modules/layers/src/screen-grid-layer/screen-grid-layer.js
test/modules/core/experimental/utils/grid-aggregation-utils.spec.js

For #2084
Kepler.gl is in process of upgrading to deck.gl 6.4, to support GPU GridLayer, port some of the aggregation releated change to 6.4-release branch.
- Port #2794 and other required changes.
- Disable a failing unit test (also disabled on master).
- GridAggregation: port grid aggregation changes to 6.4

GridAggregation: port grid aggregation changes to 6.4

---

website/package.json
website/webpack.config.js

For #2892 
- add @babel-preset-env

improve babel config for Edge/IE

---

docs/api-reference/attribute-manager.md
docs/api-reference/composite-layer.md
docs/api-reference/controller.md
docs/api-reference/deck.md
docs/api-reference/first-person-view.md
docs/api-reference/internal/layer-manager.md
docs/api-reference/json/json-converter.md
docs/api-reference/layer.md
docs/api-reference/map-controller.md
docs/api-reference/orbit-view.md
docs/api-reference/orthographic-view.md
docs/api-reference/perspective-view.md
docs/api-reference/react/deckgl.md
docs/api-reference/standalone/deckgl.md
docs/api-reference/test-utils/test-layer.md
docs/api-reference/third-person-view.md
docs/api-reference/view.md
docs/api-reference/viewport.md
docs/api-reference/web-mercator-viewport.md
docs/developer-guide/custom-layers/picking.md
docs/developer-guide/custom-layers/primitive-layers.md
docs/developer-guide/custom-layers/writing-shaders.md
docs/roadmap.md
docs/whats-new.md
modules/json/src/parsers/convert-json.js

For #
Update more links to 7.0-release branch
-  Update more links to 7.0-release branch

Update more links to 7.0-release branch

---

dev-docs/RFCs/README.md

For #3020 
I was just reading some RFCs and did spot an incorrect URL

fixed version for project/unproject RFC

---

modules/core/package.json
modules/core/src/lifecycle/component.js
package.json
yarn.lock

- Bump mjolnir.js version - v2.1 fixes a console warning about passive listeners
- Fix a console warning about missing component name

Various console warning fixes

---

modules/core/src/lib/attribute-manager.js
modules/core/src/lib/attribute-transition-manager.js
modules/core/src/lib/attribute.js
modules/core/src/lib/base-attribute.js
modules/core/src/lib/layer.js
modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js
modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js
modules/mesh-layers/src/utils/matrix.js
test/modules/core/lib/attribute.spec.js
test/modules/core/lib/base-attribute.spec.js

Decided to consolidate these:
- Fix shader attribute constant updates
- Fix shader attribute transitions
- Move shader attribute logic into `Attribute` class.

Fix shader attribute constants and transitions

---

docs/whats-new.md

- add gif images
- add using lighting doc link

update what's new for lighting

---

docs/api-reference/lights/ambient-light.md
docs/api-reference/lights/camera-light.md
docs/api-reference/lights/directional-light.md
docs/api-reference/lights/point-light.md

add gif images to light source docs

---

modules/core/src/effects/lighting/camera-light.js
modules/core/src/effects/lighting/point-light.js
test/modules/core/effects/lighting-effect.spec.js

Better to update projected light props after user changes original point lights
- update projected light props internally

update internal props of point lights

---

modules/aggregation-layers/src/contour-layer/contour-layer.js
modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-layer.js
modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer.js
modules/layers/src/bitmap-layer/bitmap-layer.js
modules/layers/src/icon-layer/icon-layer.js
modules/layers/src/icon-layer/icon-manager.js
modules/layers/src/text-layer/font-atlas-manager.js
modules/layers/src/text-layer/text-layer.js
modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js
modules/test-utils/src/lifecycle-test.js
test/modules/aggregation-layers/contour-layer/contour-layer.spec.js
test/modules/layers/core-layers.spec.js

For #3039 
- Delete Texture2Ds on layer finalization
- GPUGridAggregator is not freeing all resources, need investigation @1chandu

Delete textures on layer finalization

---

examples/experimental/json-browser/package.json
examples/layer-browser/package.json
examples/website/scenegraph-layer/package.json
modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator-utils.js
modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.js
modules/core/package.json
test/modules/aggregation-layers/contour-layer/contour-layer.spec.js
test/modules/layers/core-layers.spec.js
yarn.lock

For #3039 
GPUAggregator: Couple of resources are not properly deleted, collect and delete these resources.
- GPUAggregator: Fix Buffer/Texture leaks

GPUAggregator: Fix Texture/Buffer resource leaks.

---

dev-docs/RFCs/v7.x/64bit-attribute-rfc.md

- Had a bunch of thoughts after our recent brainstorming session, did a rough writeup, will clean up next week, hopefully the gist of the ideas still comes through.
- New RFC

RFC: Thoughts on binary attribute generation

---

docs/developer-guide/views.md

For [#3060](https://github.com/uber/deck.gl/issues/3060)
- fixed spelling of "different"

fix typo: diffenrent => different

---

dev-docs/RFCs/v7.x/gpu-grid-layer.md

For #2084 
- Adding RFC for supporting GPU Acceleration in `GridLayer`.
- RFC: GPU Acceleration in GridLayer

RFC: GPU Acceleration in GridLayer

---

modules/google-maps/src/utils.js

Broken by https://github.com/uber/deck.gl/pull/3041

Fix onClick callback in GoogleMapsOverlay

---

modules/layers/package.json
modules/mesh-layers/package.json
yarn.lock

Main bundle 1.3M -> 780K
- Bump loaders.gl version

Fix bundle size

---

scripts/bundle.config.js

Follow up of https://github.com/uber/deck.gl/pull/3085
Bundle size 939k > 805k

Optimize bundle size

---

modules/layers/src/solid-polygon-layer/solid-polygon-layer-vertex-main.glsl.js

- `elevationScale` should only apply to `elevations`.

Fix elevationScale in PolygonLayer

---

modules/layers/src/column-layer/column-geometry.js
modules/layers/src/column-layer/column-layer.js
modules/layers/src/column-layer/grid-cell-layer.js

For #3015 
- Use a single model for stroke and fill in ColumnLayer

Use a single model for stroke and fill in ColumnLayer

---

dev-docs/RFCs/v7.x/post-process-effect-rfc.md

post-process effect RFC

---

modules/core/src/lib/deck-renderer.js

Fix logging

---

modules/core/src/viewports/web-mercator-viewport.js
test/apps/multi-viewport/app.js
test/apps/multi-viewport/index.html
test/apps/multi-viewport/package.json
test/apps/multi-viewport/webpack.config.js

For https://github.com/uber/streetscape.gl/issues/283

Remove force override of position parameter in WebMercatorViewport

---

modules/core/src/effects/post-process-effect.js
modules/core/src/index.js
modules/core/src/lib/deck-renderer.js
modules/core/src/lib/deck.js
modules/core/src/lib/effect-manager.js
modules/core/src/lib/effect.js
modules/core/src/passes/layers-pass.js
modules/core/src/passes/pass.js
modules/core/src/passes/screen-pass.js
test/modules/core/effects/index.js
test/modules/core/effects/post-process-effect.spec.js
test/modules/core/lib/effect-manager.spec.js

For #2962 
- new PostProcessEffect and ScreenPass classes
- new PostProcessEffect rendering logic in DeckRenderer

post-processing effect rendering pipeline

---

modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer.js
modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.js
modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.md
test/modules/aggregation-layers/utils/gpu-grid-aggregator.spec.js

For #2561
- Move the logic for Buffer vs Array testing and aching Buffer reads into `GPUGridAggregator` class.
- Update docs and add unit test.
-  GPUGridAggregaotor: add getData method

GPUGridAggregator: Add `getData` method

---

docs/api-reference/attribute-manager.md
modules/core/src/lib/attribute-manager.js
modules/core/src/lib/attribute.js
modules/core/src/utils/range.js
test/modules/core/lib/attribute.spec.js
test/modules/core/utils/index.js
test/modules/core/utils/range.spec.js

For #1576 
- Support invalidating a partial range of an attribute
- Unit tests

support multiple ranges in attribute partial update

---

modules/core/src/lib/attribute.js
modules/layers/src/arc-layer/arc-layer.js
modules/layers/src/column-layer/column-layer.js
modules/layers/src/icon-layer/icon-layer.js
modules/layers/src/line-layer/line-layer.js
modules/layers/src/point-cloud-layer/point-cloud-layer.js
modules/layers/src/scatterplot-layer/scatterplot-layer.js
modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer.js
modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js
modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js
modules/mesh-layers/src/utils/matrix.js

For #1576 
- Update all primitive layers' updaters to support partial update

Support partial update in layer attribute updaters

---

modules/core/src/utils/tesselator.js
test/modules/layers/path-tesselator.spec.js
test/modules/layers/polygon-tesselation.spec.js

For #1576 
- Make `Tesselator` class support partial update
- Unit tests

Handle partial update in Tesselator

---

docs/layers/h3-cluster-layer.md
docs/layers/h3-hexagon-layer.md
docs/layers/s2-layer.md
modules/geo-layers/src/h3-layers/h3-cluster-layer.js
website/src/components/demos/geo-layer-demos.js

- Add embedded demos to H3HexagonLayer and H3ClusterLayer docs
- Fix a picking bug in `H3ClusterLayer`

Add h3 layer embedded demos

---

modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.js
test/modules/aggregation-layers/utils/grid-aggregation-utils.spec.js
test/modules/index.js

For #3156 
- Enable the test case, disable parts of the test that are failing only in headless browser.
- Fix deprecated API usage for Buffer.
-

GPU Aggregator : enable partial test

---

dev-docs/RFCs/v7.x/post-process-effect-rfc.md
docs/effects/lighting-effect.md
docs/effects/post-process-effect.md
docs/whats-new.md
modules/main/src/index.js
website/contents/pages.js

Post-processing effect doc

---

docs/layers/cpu-grid-layer.md
docs/layers/gpu-grid-layer.md
docs/layers/grid-layer.md
docs/layers/hexagon-layer.md
website/src/components/demos/aggregation-layer-demos.js

For #
Minor formatting / url  fixes for grid and hexagon layers.
-

Fix GridLayer docs

---

examples/website/map-tile/app.js
modules/layers/src/bitmap-layer/bitmap-layer.js

Reduce flashing in map-tile demo

---

examples/website/icon/app.js
examples/website/icon/icon-cluster-layer.js
examples/website/icon/package.json
website/package.json

- Replace custom clustering implementation with [supercluster](https://www.npmjs.com/package/supercluster)

Use supercluster for clustering in IconLayer demo

---

docs/layers/grid-cell-layer.md
website/src/components/demos/geo-layer-demos.js
website/src/components/demos/layer-demos.js
website/src/utils/layer-params.js

For #3173 
- Remove deprecated API usage thats causing crashes.
- Fix mapbox token variable.
- Fix crashes in GridCellLayer and TileLayer Demos

Website: fix crashes in GridCellLayer and TileLayer Demos

---

package.json
website/contents/pages.js
website/package.json
website/src/components/demos/layer-demo-base.js
website/src/components/demos/layer-demos.js
website/src/main.js
website/src/static/markdown/showcase.md
website/webpack.config.js
yarn.lock

- Transpile workers to es5
- Disable depth mask in PathLayer embedded demo
- Optimize `@babel/polyfill` usage (through preset-env `useBuiltIns` option)
- Fix IconLayer & TileLayer breakage in Firefox and Edge
- Fix kepler.gl links

Fix website bugs

---

website/src/components/info-panel.js

- react component did not update correctly in safari
- change the key of info panel item
- sort panel param keys

Fix website control panel

---

bindings/python/pydeck/README.md
bindings/python/pydeck/examples/Conway's Game of Life.ipynb
bindings/python/pydeck/examples/Introduction.ipynb
bindings/python/pydeck/pydeck/_version.py
bindings/python/pydeck/pydeck/bindings/deck.py
bindings/python/pydeck/pydeck/bindings/json_tools.py
bindings/python/pydeck/pydeck/bindings/layer.py
bindings/python/pydeck/pydeck/bindings/view_state.py
bindings/python/pydeck/pydeck/widget/_frontend.py
bindings/python/pydeck/pydeck/widget/widget.py
bindings/python/pydeck/setup.py
bindings/python/pydeck/tests/test_deckgl_widget.py
bindings/python/pydeck/tests/test_json_interface.py

- Change versioning scheme for release of `0.1dev1`
- Add warning if Mapbox token is not set
- Add an additional notebook
- Re-introduce support for updating pre-existing visuals

Address different publishing requirements

---

test/modules/core/effects/lighting-effect.spec.js
test/modules/core/lib/effect-manager.spec.js

improve test coverage
- more unit tests

more unit tests for lighting effect and effect manager

---

modules/core/src/lib/attribute.js
modules/layers/src/path-layer/path-layer.js
test/apps/attribute-transition/app.js
test/apps/attribute-transition/index.html
test/apps/attribute-transition/package.json
test/apps/attribute-transition/webpack.config.js

- Fix a bug in SolidPolygonLayer indices buffer update (broken tesselation when layer data is updated)
- Fix PathLayer attribute transition crash
- Fix attribute transition test app

Attribute buffer handling bug fixes

---

modules/jupyter-widget/package.json
modules/jupyter-widget/src/version.js
modules/jupyter-widget/src/widget.js
package.json
test/modules/index.js
test/modules/jupyter-widget/index.spec.js
test/modules/jupyter-widget/utils.spec.js
yarn.lock

Increase the test coverage from 0%
Part of #2929
- Add tests for view and model objects
- Verify critical functionality like creating a widget from an initial state

Give jupyter-widget JS module test coverage

---

test/modules/core/effects/post-process-effect.spec.js

Improve unit test coverage for PostProcessEffect
- more unit test

improve PostProcessEffect unit tests

---

examples/layer-browser/src/app.js
examples/layer-browser/src/map.js

- Separate state handling and layer generation into two components (no longer re-renders examples on view state change and/or hover)
- Fix `OrbitView` usage
- Fix `MapView` bug with `position`

Layer browser perf and bug fixes

---

modules/layers/src/text-layer/text-layer.js
package.json
test/modules/index.js
test/modules/json/json-converter.spec.js
test/modules/json/json-render.spec.js
test/modules/jupyter-widget/index.spec.js
test/modules/layers/index.js
test/modules/layers/text-layer/text-layer.spec.js
yarn.lock

- Allow canvas-based code to run under Node
- Add basic tests for `TextLayer`
- Fix `TextLayer` handling of non-iterable data

Enable unit tests for canvas-based layers

---

modules/geo-layers/src/s2-layer/s2-layer.js
test/modules/geo-layers/index.js
test/modules/geo-layers/s2-layer.spec.js
test/modules/geo-layers/trips-layer.spec.js

- Fix `S2Layer` handling of non-iterable data
- Add tests for `TripsLayer`

Update geo-layers unit tests

---

docs/api-reference/deck.md
modules/core/package.json
modules/core/src/lib/deck.js
yarn.lock

For #3189 
- Add `touchAction` prop to `Deck` to support scrolling on mobile

Add touchAction prop to Deck

---

modules/core/src/lib/base-attribute.js
test/modules/core/lib/base-attribute.spec.js

For comments in #3211 
- Add `elementOffset` to `BaseAttribute`
- Tests

Add elementOffset to BaseAttribute

---

docs/api-reference/deck.md
modules/core/src/controllers/controller.js
modules/core/src/controllers/map-controller.js
modules/core/src/controllers/transition-manager.js
test/modules/core/controllers/test-controller.js

For #2726 
- Add more flags to `interactionState`
- Tests

Align controller behavior with react-map-gl

---

modules/core/src/lib/view-manager.js
modules/core/src/utils/math-utils.js
modules/core/src/viewports/viewport.js
test/modules/core/utils/index.js
test/modules/core/utils/math-utils.spec.js
test/modules/core/viewports/viewport.spec.js
test/utils/utils.js

New `ViewManager` method to extract frustum planes from a particular view.

Frustum planes

---

modules/react/src/deckgl.js
package.json
test/modules/core/lib/deck.spec.js
test/modules/core/lib/index.js
test/modules/index.js

- Add node tests for the Deck class

Add Deck tests using headless-gl

---

modules/core/src/viewports/viewport.js
test/modules/core/viewports/viewport.spec.js

Cache frustum planes

---

dev-docs/RFCs/v7.x/layer-shader-hook-rfc.md

Related to #2524 	
See RFC content.

Add layer shader hooks rfc

---

modules/google-maps/src/utils.js

Fix fullscreen bug in GoogleMapsOverlay

---

test/modules/layers/bitmap-layer.spec.js
test/node.js

Enable bitmap layer test

---

scripts/bundle.config.js

- Add babel plugins to align with module transpilation settings and reduce bundle size

Update bundle configs

---

modules/layers/src/geojson-layer/geojson-layer.js
modules/layers/src/geojson-layer/geojson.js
modules/layers/src/polygon-layer/polygon-layer.js
modules/layers/src/text-layer/text-layer.js
modules/layers/src/utils.js
modules/test-utils/src/generate-layer-tests.js
test/modules/layers/geojson-layer.spec.js
test/modules/layers/index.js
test/modules/layers/polygon-layer.spec.js
test/modules/layers/text-layer/text-layer.spec.js
test/modules/layers/utils.spec.js

For #1576 
- Support partial update in all core composite layers
- Update `generateLayerTests` in test-utils to cover partial update case
- Unit tests

Data Partial Update (2/2)

---

docs/api-reference/layer.md
modules/core/src/lib/attribute.js
modules/core/src/lib/layer.js
modules/core/src/lifecycle/props.js
modules/core/src/utils/tesselator.js
modules/layers/src/geojson-layer/geojson-layer.js
modules/layers/src/geojson-layer/geojson.js
modules/layers/src/path-layer/path-layer.js
modules/layers/src/polygon-layer/polygon-layer.js
modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
modules/layers/src/text-layer/text-layer.js
modules/layers/src/utils.js
modules/test-utils/src/generate-layer-tests.js
test/apps/partial-update/README.md
test/apps/partial-update/app.js
test/apps/partial-update/data-generator.js
test/apps/partial-update/package.json
test/apps/partial-update/webpack.config.js
test/modules/layers/geojson-layer.spec.js
test/modules/layers/index.js
test/modules/layers/polygon-layer.spec.js
test/modules/layers/text-layer/text-layer.spec.js
test/modules/layers/utils.spec.js

For #1576 
- Expose the partial update feature with a `_dataDiff` prop
- Support partial update in all primitive layers
- Add a test application

Data Partial Update

---

docs/layers/scenegraph-layer.md
modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js
test/modules/layers/scenegraph-layer.spec.js

This reverts commit e443afeda90e1ac57f09eecb4d19681aeff0112f.

Revert "Add _scenegraphLoader property to ScenegraphLayer (#3258)"

---

package.json
yarn.lock

Upgrade to puppeteer 1.18.0

---

dev-docs/RFCs/v7.x/data-loading-rfc.md

Data Loading RFC

---

docs/layers/bitmap-layer.md
examples/experimental/json-browser/package.json
examples/layer-browser/package.json
examples/website/scenegraph-layer/package.json
modules/core/package.json
modules/layers/src/bitmap-layer/bitmap-layer.js
package.json
test/apps/glsl-debugger/package.json
test/apps/video/README.md
test/apps/video/app.js
test/apps/video/package.json
test/apps/video/webpack.config.js
yarn.lock

for #3199 
- support video
- update doc 
- add video test app

Add video support in BitmapLayer

---

dev-docs/RFCs/README.md
dev-docs/RFCs/vNext/layer-extension-rfc.md

Some ideas to support new functionalities of core layers in the long term.

Layer extension RFC

---

docs/api-reference/layer.md
docs/layers/column-layer.md
docs/layers/cpu-grid-layer.md
docs/layers/grid-cell-layer.md
docs/layers/grid-layer.md
docs/layers/solid-polygon-layer.md
docs/layers/trips-layer.md

For #3285
Fixed minor spell mistakes

Correct minor spell mistakes in layer docs

---

docs/developer-guide/performance.md

For  NA
Typo in `performance.md`
- changed `// Bad` comment to `// Good`

developer-guide/performance.md typo

---

examples/layer-browser/package.json
modules/core/package.json
modules/core/src/lib/init.js
modules/core/src/lib/layer.js
modules/core/src/utils/json-loader.js
modules/layers/package.json
modules/layers/src/bitmap-layer/bitmap-layer.js
modules/layers/src/icon-layer/icon-layer.js
modules/layers/src/icon-layer/icon-manager.js
modules/mesh-layers/package.json
modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js
modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js
yarn.lock

For #3072 
For discussion with #3077 
- Use loaders.gl `load` as the default `fetch` function
- Add `loadOptions` prop
- Default loaders: `JSONLoader` and `HTMLImageLoader`

loaders.gl integration

---

modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js

With this fix, I was finally able to display embedded GLBs using the ScenegraphLayer... 
For #
-

ScengraphLayer: scene detection fixup

---

modules/core/src/lib/composite-layer.js
modules/core/src/lib/layer-extension.js
modules/core/src/lib/layer.js
modules/geo-layers/src/h3-layers/h3-cluster-layer.js
modules/layers/src/geojson-layer/geojson-layer.js
modules/layers/src/polygon-layer/polygon-layer.js
modules/layers/src/text-layer/text-layer.js
test/modules/core/lib/layer-extension.spec.js

Follow up of https://github.com/uber/deck.gl/pull/3305
- Allow extensions to pass props from a composite layer to sub layers
- Tests

composite layer: pass extension props through

---

dev-docs/RFCs/README.md
dev-docs/RFCs/v6.3/gpu-aggregation-enhancements.md
dev-docs/RFCs/v7.1/gpu-grid-layer.md
dev-docs/RFCs/v7.x/heatmap-layer-rfc.md

For #2   (issue # 2, wow !!! finally)
- RFC: HeatmapLayer

RFC: HeatmapLayer

---

bindings/python/pydeck/tests/browser/test_examples.py

Skips currently flaky screen diff tests on master

Skip Jupyter notebook tests

---

modules/core/src/lib/deck.js

Fix missing pickingRadius for onClick handlers (#3321)

---

modules/layers/src/geojson-layer/geojson.js
test/modules/layers/geojson.spec.js

For https://github.com/uber/deck.gl/issues/3301
- If some feature geometries are malformed, log warning instead of crash

Relax geometry validation in GeoJsonLayer

---

modules/core/src/lib/attribute.js
modules/core/src/utils/tesselator.js
modules/core/src/utils/typed-array-manager.js
modules/layers/src/solid-polygon-layer/polygon-tesselator.js
test/modules/core/lib/attribute.spec.js
test/modules/core/lib/layer-extension.spec.js
test/modules/core/utils/index.js
test/modules/core/utils/typed-array-manager.spec.js
test/modules/layers/core-layers.spec.js
test/modules/layers/path-tesselator.spec.js
test/modules/layers/polygon-tesselation.spec.js

For data streaming
- Split `TypedArrayManager` off of `Tesselator`
- Use central typed array pool in the `Attribute` class
- Tests

Typed array manager

---

docs/developer-guide/coordinate-systems.md

Notes on camera transforms

---

README.md

For doc
Hit 404, while reading the docs
- Fixes 404 link for webpack in the README.md

chore(readme): fixes bad link in the README.md

---

docs/developer-guide/performance.md

- Add examples for the new streaming and external attribute features

Update performance documentation

---

docs/api-reference/controller.md
modules/core/src/controllers/controller.js
modules/core/src/lib/view-manager.js
test/apps/minimap/app.js
test/apps/minimap/package.json
test/apps/minimap/webpack.config.js
test/modules/core/controllers/test-controller.js

For #3294 
- Make views on top capture controller events
- Fix test/apps/minimap

Fix controller event propagation

---

.travis.yml
bindings/python/pydeck/setup.py

For #2929
Simplify the setup.py to make installation with `pip` a bit easier
- Add `develop` to setup.py to support `pip install -e .` instead of `python setup.py install` as the preferred development installation route

Simplify setup.py

---

docs/api-reference/deck.md

- Fix typos
- Add missing documentation for props `onResize` `onBeforeRender` and `onAfterRender`

Update deck documentation

---

dev-docs/RFCs/v6.1/contour-layer-rfc.md

For #
Update status of implemented RFC
-

Doc: Update status of implemented RFC

---

modules/layers/src/bitmap-layer/bitmap-layer-fragment.js
modules/layers/src/bitmap-layer/bitmap-layer.js
modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer-fragment.glsl.js
modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer-fragment.glsl1.js

Normalize bitmap layer color uniforms

---

examples/website/scenegraph-layer/README.md
examples/website/scenegraph-layer/app.js

Update model in website/scenegraph-layer example

---

modules/core/package.json
yarn.lock

For #
Bump luma.gl to 7.2-alpha.6
- Bump luma.gl to 7.2-alpha.6

Bump luma.gl to 7.2-alpha.6

---

modules/aggregation-layers/src/heatmap-layer/heatmap-layer.js

- Make zoom more responsive by debouncing texture updates
- Fix bug in bounds clipping

[HeatmapLayer] add debounce to zoom updates

---

modules/core/src/effects/lighting/lighting-effect.js
modules/core/src/shaderlib/shadow/shadow.js
test/modules/core/effects/lighting-effect.spec.js
test/modules/core/shaderlib/shadow/shadow.spec.js

For #3341
- calc right scale by unproject 4 screen corners
- remove default shadow module in cleanup function

Calc right scale for shadow map

---

examples/experimental/bezier/package.json
examples/experimental/json-browser/package.json
examples/experimental/sun/package.json
examples/get-started/pure-js/basic/package.json
examples/get-started/pure-js/google-maps/package.json
examples/get-started/pure-js/mapbox/package.json
examples/get-started/react/basic/package.json
examples/get-started/react/mapbox-browserify/package.json
examples/get-started/react/mapbox/package.json
examples/get-started/scripting/basic/index.html
examples/get-started/scripting/google-maps/index.html
examples/get-started/scripting/mapbox/index.html
examples/website/3d-heatmap/package.json
examples/website/arc/package.json
examples/website/brushing/package.json
examples/website/data-filter/package.json
examples/website/geojson/package.json
examples/website/highway/package.json
examples/website/icon/package.json
examples/website/line/package.json
examples/website/map-tile/package.json
examples/website/mesh/package.json
examples/website/plot/package.json
examples/website/point-cloud/package.json
examples/website/scatterplot/package.json
examples/website/scenegraph-layer/package.json
examples/website/screen-grid/package.json
examples/website/tagmap/package.json
examples/website/text-layer/package.json
examples/website/trips/package.json

Bump example dependencies

---

examples/website/trips/app.js
modules/core/src/effects/lighting/lighting-effect.js
website/src/actions/app-actions.js
website/src/components/app.js
website/src/components/demos/home-demo.js
website/src/components/header.js
website/src/components/home.js
website/src/reducers/app.js
website/src/static/workers/trips-data-decoder.js
website/src/stylesheets/_gallery.scss
website/src/stylesheets/_home.scss
website/src/stylesheets/main.scss

For #3396 
- Add shadow to front page demo
- Fix bug in LightingEffect handling `shadowEnabled`
- Update trips example to use the latest data format
- Update website styling to match new demo

Add shadow to website home demo

---

docs/README.md
docs/whats-new.md

For #3396 
Whats-new: fix heatmap layer formatting
Overview: add 7.2 and 7.1 and 7.0 badges, remove 6.x badges
-

Fix formatting in whats-new

---

examples/website/geojson/app.js
modules/core/src/effects/lighting/sun-light.js
modules/core/src/effects/lighting/suncalc.js

- Fix SunLight direction
- Fix SunLight shadow
- Add shadows to geojson example

Fix sunlight with shadows

---

website/src/static/workers/earthquakes-decoder.js
website/src/stylesheets/_gallery.scss

- Remove worker syntax that requires polyfill
- Fix map container styles

Fix website data filter example

---

docs/upgrade-guide.md

For #3396
- Update 7.2 upgrade guide

Update 7.2 upgrade guide

---

modules/core/src/lib/attribute.js
test/modules/core/lib/attribute.spec.js

External color buffers got cleared when zoom in/out map.
- setExternalBuffer

Fix set external buffer

---

examples/website/point-cloud/package.json
website/package.json

For #3396 
Fix a crash in website
- Website: Lock loaders.gl/las to 1.0.3

Website: Lock loaders.gl/las to 1.0.3

---

examples/experimental/json-browser/package.json
examples/layer-browser/package.json
examples/website/scenegraph-layer/package.json
modules/core/package.json
modules/jupyter-widget/package.json
modules/mesh-layers/package.json
package.json
test/apps/glsl-debugger/package.json
yarn.lock

For #3396
- Bump luma.gl to 7.2.0

Bump luma.gl to 7.2.0

---

examples/website/point-cloud/package.json
examples/website/scenegraph-layer/package.json
website/package.json

For https://github.com/uber/deck.gl/issues/3396#issuecomment-520066849
Issue fixed in loaders.gl@1.2.1

Bump loaders dependencies in examples

---

modules/json/package.json
modules/json/src/parsers/convert-json-expression.js
modules/json/src/parsers/convert-json.js
modules/json/src/parsers/enhanced-fetch.js
modules/json/src/parsers/parse-string-expression.js
test/modules/json/convert-json-expression.spec.js
test/modules/json/index.js
test/modules/json/json-converter.spec.js
test/modules/json/json-layer.spec.js
test/modules/json/parse-string-expression.spec.js

For #3079
Cleaner version of #3186 
-

Support expression parsing for JSON API and pydeck

---

test/modules/core/effects/lighting/sunlight.spec.js

More unit test for SunLight class

---

docs/api-reference/orbit-view.md
modules/core/src/controllers/orbit-controller.js

- Allow the orbit view to rotate 360 degrees around the X axis
- Introduce `minRotationX` and `maxRotationX` view states to retain current behavior

Support 360 rotation in OrbitController
