visgl/deck.gl

package.json, src/layers/layer-manager.js, src/layers/layer.js, src/util.js
fix a bug with layer getNumInstance not returning the updated number of instance after layer state changed in the _getRenderFunction
=> Performance fix

src/layer.js, test/layer-spec.js
Fixes #31 
I added unit tests confirming this behavior, but there's still a test failure on
```
⨯ Viewport projection matrix
not ok 7 TypeError: viewport.getZoomedViewProjectionMatrix is not a function
---
operator: error
expected: 
actual:   {}
at: Test.exports.Test.run (/Users/Hyde/src/deck.gl/node_modules/tape-catch/index.js:29:10)
stack:
TypeError: viewport.getZoomedViewProjectionMatrix is not a function
at Test._cb (viewport-spec.js:55:39)
```
I'm not sure the best solution to this, so I just left it as-is.
=> Fix Layer#checkProp to only error on undefined/null

src/layers/choropleth-layer/choropleth-layer.js
Responds to https://github.com/uber/deck.gl/pull/46, allows users to specify a rgb vector a property of each geojson layer being passed in. Example
=> Enable fill coloring for choropleths

.eslintrc, example/main.js, src/layers/arc-layer/arc-layer.js, src/layers/choropleth-layer/choropleth-layer.js, src/layers/hexagon-layer/hexagon-layer.js, src/layers/line-layer/line-layer.js, src/layers/scatterplot-layer/scatterplot-layer.js, test/layers-spec.js
@gnavvy -  All positions now use array format and all layers use accessors that application can override. 
- Apps no longer have to transform data to a specific format to use deck.gl.
- Also apps can now pass any iterable objects (e.g. Immutable Lists) as deck.gl data props.
This is a breaking change that will be merged to dev branch and initially published in a 3.0.0 beta release.
=> Added accessors

shaderlib/project.glsl, src/layers/base-layer.js
A trial fix for https://github.com/uber/deck.gl/issues/63, certain implementation of webgl has a regression in GLSL such that boolean uniforms cannot be used.
=> change bool uniform to float uniform

package.json, src/layers/base-layer.js
Fixes #73
@gnavvy @abmai @contra
Using the new luma logging it was easy to spot that the picking colors attribute was all zeroes. Fixed by a one line change to second parameter in `Layer.calculateInstancePickingColors`.
=> Fix picking

README.md, example/main.js, src/layers/choropleth-layer/choropleth-layer.js
currently, the choropleth layer uses a global line width for this contour.
that is, if other layers set the line width, the choropleth layer will pick that value, which is not desired.
this fix allows the user to specify the line width via the lineWidth prop.
@ibgreen
=> add line width support for the choropleth layer

src/viewport/viewport.js
Extend the far plane for creating the perspective projection matrix so that models with negative height are also shown
@Pessimistress @ibgreen
=> Extend the far plane to show models with negative z coord

CHANGELOG.md, README.md, docs/getting-started.md, src/lib/layer-manager.js, src/lib/layer.js, src/lib/pick-models.js, src/react/deckgl.js, src/test/layers/core-layers.spec.js, src/test/lib/layer.spec.js
@Pessimistress This PR routes picking through `layer.pick` lifecycle method, enabling layers to override default picking behavior.
Also substantially cleans up the picking code.
=> Expose a `pick` lifecycle method that layers can override

example/layer-examples.js, src/lib/layer.js, src/viewport/index.js, src/viewport/viewport.js, src/viewport/webgl-viewport.js
@shaojingli @gnavvy - Step 1 towards moving core viewport to viewport-mercator-project.
=> Split the viewport into GL and non-GL related classes.

src/layers/core/arc-layer/arc-layer-vertex.glsl, src/layers/fp64/arc-layer/arc-layer-vertex.glsl
Attempt to fix the arc layer flickering.
The flickering of the segment 0 of arc layer seems due to negative results returned by the paraboloid() and paraboloid_fp64() function.
=> Fix arc layer flickering

docs/layer.md, docs/layers/arc-layer.md, docs/layers/choropleth-layer.md, docs/layers/line-layer.md, docs/layers/sample-layers.md, docs/layers/scatterplot-layer.md, docs/layers/screen-grid-layer.md, src/layers/core/choropleth-layer/choropleth-layer.js
Standardized parameters types case among layer docs, and moved the default values (if any) down the heading, to provide more control over the markup with its value and possible description.
Had a little doubt about keeping the additional notes in the *Choropleth* one, since it's in the `data` object so I kept it for now.
=> Update layer docs

CHANGELOG.md, example/layer-examples.js, package.json, src/layers/core/choropleth-layer/choropleth-layer.js, src/layers/core/scatterplot-layer/scatterplot-layer.js, src/lib/attribute-manager.js, src/lib/layer.js
@shaojingli @Pessimistress @gnavvy 
This long overdue fix saves 21 bytes per instance for most layers (4 x colors + 3 x pickingColors = 7 colors).
- Float32Array - 7 x 4 = 28 bytes per instance
- Uint8Array - 7 x 1 = 7 bytes per instance
This should more than make up for memory expansion from 64 bits, which is usually 4-8 bytes
per instance.
@apercu - If you are updating color attributes for all layers, you could also update type to `GL.UNSIGNED_BYTE`.
=> Use Uint8Array for Scatterplot colors and instancePickingColors

shaderlib/project/project.glsl, src/layers/core/scatterplot-layer/scatterplot-layer-vertex.glsl, src/viewport/viewport.js
Fixe the wobbling of meters projection mode by separating the transformation of origin and offset. 
**mercatorProj(originPosition) * projectionMatrix** + offsetPosition * projectionMatrix
The **bold** part is done on CPU and the rest on GPU
Please verify before we merge @ibgreen
=> Fixed the wobbling in meters projection mode

package.json
- `demo-gh-pages`: pushes the demo dist folder to be the root of github pages
- `demo-publish`: compiles deck.gl and the demos, then pushes the changes to `gh-pages` using `demo-gh-pages`
=> Adding npm commands for pushing demos and documentation to gh-pages

example/layer-examples.js, package.json, src/layers/samples/index.js, src/layers/samples/voronoi-layer/voronoi-layer-fragment.glsl, src/layers/samples/voronoi-layer/voronoi-layer-vertex.glsl, src/layers/samples/voronoi-layer/voronoi-layer.js, src/viewport/old-viewport.js
@gnavvy @shaojingli 
Partial fix to Voronoi Layer, uses gl_FragDepth extension to populate the depth buffer while rendering a flat image.
=> Voronoi Layer fragment depth fix

docs/writing-shaders.md, src/lib/layer-manager.js, src/lib/layer.js
@shaojingli @gnavvy 
By adding a `drawCount` uniform we can add small offsets in the vertex shader while rendering to avoid z-fighting.
`drawCount` is simply an integer starting at 0 and incremented for each rendered layer.
=> Support drawCount uniform to control polygon offsets (defeat z-fighting)

example/layer-examples.js
@ibgreen
We probably should remove Scatterplot64(Meters) for our v3 release
=> Remove Scatterplot64(Meters) Layer for now

src/lib/layer-manager.js, src/viewport/viewport.js
Need to be able to debug getUniforms, removing unnecessary calls and autobind which block override.
=> Make getUniforms more debuggable

example/layer-examples.js
Assign correct id for all example layers
=> Fix incorrect rendering in the example when multiple choropleth64 layers are turned on

docs/64-bits.md
Corrected the display of the mandelbrot image by updating path, as  [recommended](https://github.com/uber/deck.gl/pull/207#issuecomment-260016592).
=> Correct the path of the mandelbrot image

src/react/deckgl.js
Enables alpha blending by default, so we can see things behind other things.
=> enabled blending by default

src/lib/layer-manager.js, src/lib/pick-layers.js
As mentioned in the title. After the change, the profile data looks like:
comparing with what we saw in issue #216 
@gnavvy
=> Allocate frame buffer object only when the viewport size changed.

src/layers/core/arc-layer/arc-layer.js, src/layers/core/choropleth-layer/choropleth-layer.js, src/layers/core/line-layer/line-layer.js, src/layers/core/scatterplot-layer/scatterplot-layer.js, src/layers/core/screen-grid-layer/screen-grid-layer.js, src/layers/fp64/arc-layer/arc-layer.js, src/layers/fp64/choropleth-layer/choropleth-layer.js, src/layers/fp64/line-layer/line-layer.js
gl.getParameter() calls bring significant performance hit to the library. We should remove it and find a better way to preserve line width settings later.
=> Remove getParameter() calls

.travis.yml
Travis now test the project using the Node 6 LTS version and the latest 7, so we can have better vision of our current support and future possible issues coming in a next update.
=> Build on Node 6 & 7

src/layers/core/scatterplot-layer/scatterplot-layer.js, src/layers/fp64/extruded-choropleth-layer/extruded-choropleth-layer-64.js
@Pessimistress @shaojingli
Uniforms update when props change.
Also predefines default props as precaution to avoid triggering change detection.
=> Fixes ExtrudedChoroplethLayer attribute updates and defaults

src/layers/core/scatterplot-layer/scatterplot-layer.js
Fallback to instanceRadius=1 since radius is calculated as radius * instanceRadius
=> Fix ScatterplotLayer radius when accessor is not defined

src/react/deckgl.js
Notify when no pickable layer has been found but one of the two mouse events has been specified.
I personally got caught and figured people could/have too, this is a simple way to address it.
=> Warning no pickable with mouse events

docs/using-with-react.md, src/react/deckgl.js
`onLayerHover(info, pickedInfos, event)`
`onLayerHover(info, pickedInfos, event)`
The first argument is more useful if it is the first non-empty layer under the pointer instead of the topmost layer.
=> onLayerHover and onLayerClick return first match

src/layers/fp64/scatterplot-layer/scatterplot-layer-64.js
NOTE: this is a PR against the master branch.
One line fix to get around nan when z data is 0.
This is a fix that has already been landed in dev branch. Porting it to master to unbreak users
=> Fix an issue in scatterplot64 that height is nan when the data source has no z data

src/shaderlib/fp64/math-fp64.glsl
Fixed a bug that fp64 math occasionally fail to reach expected precision on MacBook with NVIDIA GPUs
Trade some accuracies in exp_fp64 for speed
=> FP64 math function improvement

src/lib/viewports/viewport.js, test/lib/index.js, test/lib/viewports/index.js, test/lib/viewports/web-mercator-viewport.spec.js
- Match default value of option `topLeft` with JSDoc
- Fix bug where y is flipped in `ScreenGridLayer`
- Fix bug where picking info produce wrong `latLng` values
- Add tests
@ibgreen @heshan0131
=> Set Viewport project/unproject default to screen coordinates

docs/layers/geojson-layer.md, docs/layers/path-layer.md, examples/main/layer-examples.js, examples/main/layer-info.js, src/layers/core/geojson-layer/geojson-layer.js, src/layers/core/geojson-layer/geojson.js, src/layers/core/path-layer/path-layer.js, src/layers/core/polygon-layer/polygon-layer.js
- Fix PathLayer rendering
* PathLayer cannot accept both line and polygon features
- Fix picking on GeoJSONLayer
* aggregates results from every `onHover`, `onClick` fired by sublayers
- Correct prop names in examples
- Remove dead code
@ibgreen @gnavvy
=> GeoJSONLayer bug fixes

src/layers/core/icon-layer/icon-layer.js, src/layers/core/path-layer/path-layer.js, src/layers/core/scatterplot-layer/scatterplot-layer.js
- Fix bug where size === 0 gets overwritten
- Consistent fallback strategy in IconLayer, ScatterplotLayer and PathLayer:
* fallback check in update functions instead of default accessors
* always check before using value returned by accessor
* do not use `||` on numeric values unless fallback is 0
=> Fix fallback size on IconLayer

src/layers/core/scatterplot-layer/scatterplot-layer.js, src/lib/attribute-manager.js, src/lib/layer.js, test/bench/index.js, test/lib/layer.spec.js
@gnavvy @Pessimistress @shaojingli
* Allows us to remove the `calculateInstance` functions for most instanced layers.
* Also some webpack config cleanup.
Based on an idea from @apercu
=> New autocalculating "accessor" option in AttributeManager

docs/layers/path-layer.md, examples/main/layer-examples.js, src/layers/core/path-layer/path-layer-vertex.glsl, src/layers/core/path-layer/path-layer.js, test/bench/index.js
- do not construct intermediate arrays
- replace `prevPositions` and `nextPositions` with delta (prep for 64bit version)
- add benchmark
=> PathLayer perf improvements

examples/main/layer-info.js, src/layers/core/geojson-layer/geojson-layer.js
Hack picking differently (for now) to avoid rewriting props.
Eventually we need to re-architect picking to fix composite layers.
Known issues:
- hover events are one frame behind
- picking info's `index` and `object` are not correct
@ibgreen
=> Remove GeoJSON prop override

examples/main/app.css, examples/main/app.js, examples/main/layer-controls.js, examples/main/layer-examples.js, examples/main/layer-selector.js, examples/main/utils/color-picker.js
Prop types are inferred from names and values in `layer.defaultProps` and `example.props`.
Only accessors supported are color accessors. Update triggers are keyed to the prop name.
Updating the `effects` prop on `DeckGL` does not seem to work.
@ibgreen
=> Add per-layer settings to example app

src/lib/layer-manager.js, src/react/deckgl.js
Fixed an issue in the layer manager that even when no layer is selected, deck.gl still issues draw calls. #300
=> Fixed the unnecessary layer draw calls when there is no layer #300

docs/layers/hexagon-layer.md, examples/main/layer-controls.js, examples/main/layer-examples.js, src/layers/core/hexagon-layer/hexagon-layer-vertex.glsl, src/layers/core/hexagon-layer/hexagon-layer.js
- use radiusScale instead of dotRadius
- use extruded instead of enable3d
- calculate default hexagonVertices if not provided
=> Hexagon layer api

docs/layers/path-layer.md, examples/main/data-samples.js, examples/main/layer-controls.js, examples/main/layer-examples.js, src/layers/core/path-layer/path-layer-fragment.glsl, src/layers/core/path-layer/path-layer-vertex.glsl, src/layers/core/path-layer/path-layer.js
Re: [Mitering bug: PathLayer produces uneven strokes if the path has acute angles #337](https://github.com/uber/deck.gl/issues/337)
Current PathLayer:
Fixed miter (still some z-fighting issues):
Basically one extra point is added to each corner to control the joint.
This also allows us to do other line joints:
In this POC I'm switching to an instancing model. Comparing instanced against indexed draws:
- removed the requirement of the `OES_element_index_uint` extension
- reduce attribute length to 1/3
- the number of vertex shader calls per path increased from `numPoints * 3` to `(numPoints - 1) * 6`
Setting the perf concerns aside, it does open some pretty nice opportunities for us such as dashed lines. 
@ibgreen @contra @dcposch
=> PathLayer Miter Fix -- POC

docs/layers/icon-layer.md, examples/main/layer-examples.js, src/layers/core/icon-layer/icon-layer-vertex.glsl, src/layers/core/icon-layer/icon-layer.js
- renamed `getScale` to `getSize`
- renamed `size` to `sizeScale`
- moved color fallback to the default accessor
@shaojingli @gnavvy @ibgreen @heshan0131 @apercu @abmai
=> IconLayer API Audit

src/layers/core/scatterplot-layer/scatterplot-layer.js
Currently on the dev branch, when you change the `data` prop on a `ScatterplotLayer`, it doesn't invalidate attributes.
@ibgreen @Pessimistress
=> ScatterplotLayer bugfix: update when data changes

src/layers/core/scatterplot-layer/scatterplot-layer-fragment.glsl, src/layers/core/scatterplot-layer/scatterplot-layer-vertex.glsl, src/layers/core/scatterplot-layer/scatterplot-layer.js
- Switch from drawing 16-sided polygon to square + fragment shader, about 3x faster
- Fix lineWidth
@ibgreen @shaojingli The `strokeWidth` here is also in pixels, which is consistent with v3 but not the new PathLayer. We probably need another pass of API audit.
=> ScatterplotLayer perf improvement + lineWidth fix

examples/sample-layers/app.css, examples/sample-layers/index.html, examples/sample-layers/layers/enhanced-choropleth-layer/README.md, examples/sample-layers/layers/enhanced-choropleth-layer/enhanced-choropleth-layer-fragment.glsl.js, examples/sample-layers/layers/enhanced-choropleth-layer/enhanced-choropleth-layer-vertex.glsl.js, examples/sample-layers/layers/enhanced-choropleth-layer/enhanced-choropleth-layer.js, examples/sample-layers/layers/enhanced-choropleth-layer/geojson.js, examples/sample-layers/layers/index.js, examples/sample-layers/layers/multi-color-path-layer/multi-color-path-layer.js, examples/sample-layers/package.json, examples/sample-layers/src/app.js, examples/sample-layers/src/data-samples.js, examples/sample-layers/src/layer-controls.js, examples/sample-layers/src/layer-examples.js, examples/sample-layers/src/layer-info.js, examples/sample-layers/src/layer-selector.js, examples/sample-layers/src/utils/color-picker.js, examples/sample-layers/src/utils/color.js, examples/sample-layers/src/utils/grid-aggregator.js, examples/sample-layers/src/utils/index.js, examples/sample-layers/webpack.config.js, examples/sample-layers/yarn.lock
@Pessimistress @gnavvy @shaojingli 
Idea is to have a separate example that contains a bunch of sample layers (with the same layer property browsing UI as the `main` example has for the core layers). 
At the moment it copies a number of files from the `main` example, in order for this `layer-samples` example to remain as stand alone as possible.
=> Fixes sample-layers example

examples/main/src/layer-examples.js, src/index.js, src/layers/core/polygon-layer/polygon-layer-64-vertex.glsl, src/layers/core/polygon-layer/polygon-layer.js, src/layers/core/polygon-layer/polygon-tesselator-extruded.js, src/layers/core/polygon-layer/polygon-tesselator.js, src/layers/fp64/arc-layer/arc-layer-64.js, src/layers/fp64/geojson-layer/geojson-layer-64.js, src/layers/fp64/line-layer/line-layer-64.js, test/layers/polygon-tesselation.spec.js
Implemented 64-bit polygon layer and also 64-bit geojson layer (partially, as 64-bit path layer will come later)
The 64-bit version of polygon layer is implemented differently as other 64-bit layers as the polygon tessellator uses a fp64 flag to switch between 32-bit and 64-bit geometries. 
I'm investigating if this approach is the way to go for unifying 64 and 32 bit line, arc and scatterplot layers.
@ibgreen @gnavvy @Pessimistress
=> 64-bit polygon layer

examples/main/src/layer-examples.js, src/index.js, src/layers/core/geojson-layer/geojson-layer.js, src/layers/core/polygon-layer/polygon-layer.js, src/layers/core/scatterplot-layer/scatterplot-layer-64-vertex.glsl, src/layers/core/scatterplot-layer/scatterplot-layer.js
The user can switch between two versions using props.fp64.
This PR is on top of #379. It should be merged after #379 got merged.
=> Merge 64-bit and 32-bit scatterplot layer

CHANGELOG.md, examples/main/src/app.js, examples/main/src/layer-examples.js, examples/main/src/layer-info.js, src/layers/core/geojson-layer/geojson-layer.js, src/layers/core/point-density-grid-layer/point-density-grid-layer.js, src/layers/core/point-density-hexagon-layer/point-density-hexagon-layer.js, src/layers/deprecated/choropleth-layer/choropleth-layer.js, src/layers/deprecated/extruded-choropleth-layer-64/extruded-choropleth-layer-64.js, src/lib/draw-and-pick.js, src/lib/layer-manager.js, src/lib/layer.js, src/lib/utils/blend.js, src/lib/utils/index.js
- Improve perf by calling `gl.readPixels()` only once
- Breaking: occluded objects can no longer be picked even if on a separate layer.
- Breaking: `onHover` and `onClick` callbacks are invoked by `layer.pick()`. This allows layers to block an event if necessary. Layers that override the default `pick()` method must now call `super.pick()` *after* augmenting the info object, or call the callback functions themselves.
=> Render all picking buffers in one pass

src/layers/core/arc-layer/arc-layer.js, src/layers/core/grid-layer/grid-layer.js, src/layers/core/hexagon-layer/hexagon-layer.js, src/layers/core/icon-layer/icon-layer-64-vertex.glsl, src/layers/core/icon-layer/icon-layer.js, src/layers/core/line-layer/line-layer.js, src/layers/core/path-layer/path-layer.js, src/layers/core/point-cloud-layer/point-cloud-layer.js, src/layers/core/polygon-layer/polygon-layer.js, src/layers/core/scatterplot-layer/scatterplot-layer.js, src/lib/utils/fp64.js
Add a warning message when user tries to draw 64-bit layers in projection mode other than LON_LAT;
Reorganized the shader loading code to save some redundant load;
Fix the 64-bit IconLayer issue brought by #388
=> Warning message for using 64-bit mode with projection mode other than LON_LAT

src/layers/core/icon-layer/icon-layer-64-vertex.glsl
After default uniforms changed in #390, 64-bit IconLayer not longer receives screenSize uniform. Update it to use viewportSize as in its 32-bit counterpart
=> Update the vertex shader for IconLayer64

examples/layer-browser/src/examples/core-layers.js, src/layers/core/geojson-layer/geojson-layer.js, src/layers/core/polygon-layer/polygon-layer.js, src/lib/composite-layer.js
, which has no AttributeManager so no attribute to invalidate;
Clean up the accessor and prop names for Polygon layer and GeoJson layer
=> Fix the bug that Layer's invalidateAttribute get called for CompositeLayer

src/layers/core/geojson-layer/geojson-layer.js, src/layers/core/polygon-layer/polygon-layer.js
Now the composite layer needs to handle which updateTriggers it's sending to the child layers. 
It can no longer dump all updateTriggers it receives from the user to all of its child layers, which leads to assertions being fired from AttributeManager.invalidate(triggerName)
=> Fix the updateTrigger transfer from composite layer to its child layers

examples/layer-browser/data/sample.geo.json, examples/layer-browser/src/examples/core-layers.js, src/layers/core/arc-layer/arc-layer.js, src/layers/core/geojson-layer/geojson-layer.js, src/layers/core/grid-cell-layer/grid-cell-layer.js, src/layers/core/hexagon-cell-layer/hexagon-cell-layer.js, src/layers/core/icon-layer/icon-layer.js, src/layers/core/line-layer/line-layer.js, src/layers/core/path-layer/path-layer.js, src/layers/core/point-cloud-layer/point-cloud-layer.js, src/layers/core/polygon-layer/polygon-layer.js, src/layers/core/scatterplot-layer/scatterplot-layer.js, src/layers/core/screen-grid-layer/screen-grid-layer.js, src/layers/core/solid-polygon-layer/solid-polygon-layer.js, src/lib/layer.js
Fix the GeoJSON layer demo after the change of default value of the scatterplot layer
Update the GeoJSON layer accessor names according to the API audit
Fix the layer props of the GeoJSON layer and the Polygon layer
Also, removed the updateModel in the base Layer and put the code to each subclassed layer because the criteria for updating models are different for each layer.
=> Polygon layer fix

examples/svg-interoperability/webpack.config.js, examples/webpack.config.local.js
add start-local (run against source code) for the svg-compatibility example.
minor change on the addLocalDevSettings logic in webpack.config.local.js.
(^ resolve is not a must have field in webpack configs)
=> update webpack config for start-local scripts

examples/layer-browser/src/examples/core-layers.js, src/layers/core/geojson-layer/geojson-layer.js, src/layers/core/grid-layer/grid-layer.js, src/layers/core/hexagon-layer/hexagon-layer.js, src/layers/core/path-layer/path-layer.js, src/layers/core/polygon-layer/polygon-layer.js
Change the interface of GeoJson layer and Polygon layer to clear the confusion
Change the way composite layers pass their props to their underlying layers. Now it requires explicitly passing. Layers affected are the GeoJsonLayer, PolygonLayer, GridLayer, and HexagonLayer.
Docs change will be in an updated #436 
@Pessimistress @ibgreen @gnavvy
=> Composite layer interface and props transfer

src/layers/deprecated/extruded-choropleth-layer-64/extruded-choropleth-layer-64.js, src/layers/deprecated/extruded-choropleth-layer-64/extruded-choropleth-layer-vertex.glsl.js
Even though it's a deprecated layer, we still need this fixed as it's included in our layer browser example
#365
=> Fix the deprecated extruded choropleth 64-bit layer

src/react/deckgl.js
fixes #248 and #444 
tested (ad-hoc) in the svg-interoperability example with a scolled offset.
will add a dedicated example consist of multiple non-full screen widgets later.
=> use offsetX & offsetY instead of x & y to get relative positions

CHANGELOG.md, src/layers/core/geojson-layer/geojson-layer.js, src/layers/core/grid-layer/grid-layer.js, src/layers/core/hexagon-layer/hexagon-layer.js, src/layers/core/polygon-layer/polygon-layer.js
- Because composite layers do not render anything themselves, they must manually trigger `onHover` and `onClick` callbacks by listening to sublayer events. This was a bug on `GridLayer` and `HexagonLayer`.
- Hover and click events on composite layers should have `info.layer` point to the composite layer and `info.object` point to user data, instead of sublayer and intermediate data. This was a bug on `GeoJsonLayer` and `PolygonLayer`.
=> Consistently handle picking in composite layers

docs/layer-lifecycle.md, src/layers/core/geojson-layer/geojson-layer.js, src/layers/core/grid-layer/grid-layer.js, src/layers/core/hexagon-layer/hexagon-layer.js, src/layers/core/polygon-layer/polygon-layer.js, src/lib/composite-layer.js, src/lib/draw-and-pick.js, src/lib/layer-manager.js, src/lib/layer.js
- add `parentLayer` reference to sublayers
- `pickLayers()` only trigger callbacks on top level layers
- remove the requirement for `onHover` and `onClick` overrides
- use consistent interface (`getPickingInfo`) with the `Layer` class
=> Simplify picking inplementation in CompositeLayer

src/layers/core/solid-polygon-layer/polygon-tesselator.js
@Pessimistress 
So, the root cause here is that extruded and non-extruded polygon tessellator use different typed arrays to store color. 
Now, both of them are using Uint8ClampedArray now. The color in the polygon layer demo is out of [0, 255] so now both extruded and non-extruded render a single yellow color now - we need to fix that instead.
=> Use Uint8ClampedArray for both extruded and non-extruded polygon colors

src/lib/utils/fp64.js
CI (Jenkins) tools complains about module '.'
module.js:340
throw err;
^
Error: Cannot find module '.'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
**at Object.<anonymous> (.../deck.gl/dist/lib/utils/fp64.js:9:9)**
=> explicit import instead of import from '.'

src/layers/core/icon-layer/icon-layer.js
This is a thin PR.  I don't see any existing tests for the icon layer.  So I will add one and test the call to accessors when the state changes.
=> When the iconMapping changes we must invalid any dependent attributes

package.json
Ensure users can simply `git clone; npm i; npm start` and see a build without errors.
=> Add postinstall hook to install dependencies for `npm start`

examples/layer-browser/src/app.js, examples/layer-browser/src/examples/sample-layers.js
Also remove RotationX, RotationZ and effect controls from the layer browser. The only layer in the layer browser that responds to RotationX and RotationZ is the point cloud layer due to projection mode settings. It makes those controls seem like broken while they are not. So I decide to remove them to clear the confusions.
I commented out most of the lines instead of removing them.
=> Remove BitmapLayer and MeshLayer from layer browser. 

src/layers/core/geojson-layer/geojson-layer.js, src/layers/core/grid-layer/grid-layer.js, src/layers/core/hexagon-layer/hexagon-layer.js
to its underlying layer
It slipped through because it's not one of the props defined in base layer's default props...
=> Make composite layers transfer the lightSettings prop

examples/layer-browser/src/app.js
Comment out modelMatrix.rotateZ and modelMatrix.rotateX for the point cloud layer in the layer browser as we removed those controls in a previous commit
=> Point cloud layer example fix for the layer browser

docs/api-reference/attribute-manager.md, docs/upgrade-guide.md, docs/whats-new.md, examples/trips/trips-layer/trips-layer.js, src/layers/deprecated/choropleth-layer-64/choropleth-layer-64.js, src/layers/deprecated/choropleth-layer/choropleth-layer.js, src/lib/attribute-manager.js, src/lib/draw-and-pick.js, src/lib/layer-manager.js, src/lib/layer.js, src/lib/utils/log.js, test/lib/attribute-manager.spec.js
Attribute logging was broken for a couple of reasons. Most importantly layers no longer pass through props so it was not possible to set logging functions using props on composite layers.
Changed to a set of global loggers for all attribute managers (layers).
Gave these loggers nice defaults that collect timings for attribute updates when `deck.log.priority = 1` or higher (see screenshot).
Carefully went through docs and upgrade guide. Added new test coverage for the logging functionality.
Overhauled chaotic logging priorities to reduce noise in console and defined priority constants for various log items.
Found a couple of things that were deprecated in v3, removed them and updated the "Upgrade guide:
=> Attribute loggers

examples/layer-browser/app.css, examples/layer-browser/src/app.js
Also turn on ScatterplotLayer by default; without anything visible on the map, the example feels unfinished IMO. (Especially when there's no basemap visible.) But open to disagreement on that.
Supercedes #509, which had an errant commit from another branch.
=> Add on-screen warning when no Mapbox token exists.

src/lib/viewport-uniforms.js, src/lib/viewports/web-mercator-viewport.js
Meter offset mode was broken in #519.
This fix should let us finally close #291 
Point Cloud Layer (in Layer Browser) before and after the fix
=> Fix meter offset mode

CHANGELOG.md, examples/3d-heatmap/package.json, examples/arc/package.json, examples/brushing/package.json, examples/geojson/package.json, examples/hello-world-browserify/package.json, examples/hello-world-webpack2/package.json, examples/icon/package.json, examples/jsx-layers/package.json, examples/layer-browser/package.json, examples/line/package.json, examples/plot/package.json, examples/scatterplot/package.json, examples/screen-grid/package.json, examples/svg-interoperability/package.json, examples/tree-shaking/package.json, examples/trips/package.json
The only big change in this PR reorganizes CHANGELOG to put beta releases at the bottom.
=> Update all version numbers to official version

demo/webpack/prod.js
in the webpack build script in the demo folder. Webpack 2.3.0 and above no longer handles relative path for build
@Pessimistress @ibgreen
=> Change the relative path to absolute path

src/layers/core/solid-polygon-layer/solid-polygon-layer.js
Fix the model regeneration bug introduced by #424, that Model is recreated when data of the solid polygon layer got changed. 
@Pessimistress @ibgreen
=> Fix the model regeneration bug introduced by #424

docs/advanced/subclassed-layers.md, src/layers/core/grid-cell-layer/grid-cell-layer-vertex-64.glsl.js, src/layers/core/grid-cell-layer/grid-cell-layer-vertex.glsl.js, src/layers/core/hexagon-cell-layer/hexagon-cell-layer-vertex-64.glsl.js, src/layers/core/hexagon-cell-layer/hexagon-cell-layer-vertex.glsl.js, src/layers/core/point-cloud-layer/point-cloud-layer-vertex-64.glsl.js, src/layers/core/point-cloud-layer/point-cloud-layer-vertex.glsl.js, src/layers/core/solid-polygon-layer/solid-polygon-layer-vertex-64.glsl.js, src/layers/core/solid-polygon-layer/solid-polygon-layer-vertex.glsl.js, src/shaderlib/lighting/lighting.glsl.js
For issue #559 
Change getLightWeight() interface: now it takes a vec3 for the worldspace position (this is a workaround required for Intel GPU)
Update the 64-bit vertex shader according to 32-bit vertex shader (remove LatOffst, LonOffset)
This is a high risk / high reward change I plan to also land into 4.0-release. I tested through layer browser and demo site but I need independent verifications and tests. @Pessimistress @ericsoco @ibgreen
=> Shader workaround for Intel Iris Pro GPU

CHANGELOG.md, docs/layers/hexagon-layer.md, src/layers/core/hexagon-layer/hexagon-aggregator.js, src/layers/core/hexagon-layer/hexagon-layer.js, src/utils/bin-sorter.js
- add internal `getUpdateTrigger` method
- add `colorValueAccessor` as hexagon layer prop to get the value for bin colors. When undefined, layer will use points.length to calculate color
- change default `hexagonAggregator` output to be `{hexagons: [], hexagonVertices: []}`
- add valueAccessor to bin-sorter to support color / elevation by value
=> separate out more methods in hexagon-layer, use valueAccessor in BinSorter to enable color / elevation by value

CHANGELOG.md, docs/advanced/layer-lifecycle.md, docs/api-reference/composite-layer.md, src/lib/composite-layer.js, src/lib/draw-and-pick.js, src/lib/layer-manager.js, src/lib/layer.js
Changes:
- Only composite layers have `renderLayer()` methods
- Only non-composite layers' `draw()` methods are called during render
Goal:
- A cleaner interface
- Improve perf by skipping the uniform calculations and parameter updates for composite layers
=> Separate composite and non-composite layer APIs

src/lib/viewport-uniforms.js, test/bench/index.js, test/data/index.js, test/data/viewport.js
Changes:
- Switch from using custom math class to `gl-matrix`
- Add benchmark
Before:
```
getUniformsFromViewport#LNGLAT x 54,286 ops/sec ±2.77% (84 runs sampled)
getUniformsFromViewport#METER_OFFSETS x 37,155 ops/sec ±2.44% (84 runs sampled)
```
After:
```
getUniformsFromViewport#LNGLAT x 155,845 ops/sec ±1.70% (88 runs sampled)
getUniformsFromViewport#METER_OFFSETS x 123,868 ops/sec ±0.86% (90 runs sampled)
```
=> getViewportUniforms Optimization

src/layers/core/hexagon-layer/hexagon-layer.js
The condition was flipped. If there is no customer aggregator (``!props.hexagonAggregator``) **AND** no radius (``!props.radius``), only then enforce the default radius of ``1000``.
=> 🐛  Fixed default hexagonAggregator radius being set to default value even when it is passed in.

examples/layer-browser/package.json, examples/layer-browser/yarn.lock, package.json, yarn.lock
Looks like older versions of webpack2 crashes for empty files, so upgrade to latest. https://github.com/webpack/webpack/issues/4072
Also bump react-map-gl in layer-browser to get around any flow-type compilation issues.
=> Fix build with luma.gl 4.0.0 alpha

.gitignore, .travis.yml, package.json
- `npm run cover` run test and report code coverage at coverage/index.html
- coverall.io integrate with travis CI to report code coverage
=> Implement code coverage with nyc and coverall report

src/lib/draw-and-pick.js, src/lib/layer.js, src/react/deckgl.js
Note that many mouse events are already supported by luma.gl; this PR extends the support for a subset of these upwards into deck.gl.
I know that we have grander plans for encapsulating interaction models for different scenarios. I don't believe this runs afoul of those, but it is possible the direction taken in this PR is setting us up for a bigger refactor when we tackle new interaction models.
/cc @gnavvy @Pessimistress as potential consumers of these additions.
=> Add support for drag events.

demo/package.json, demo/src/components/mapbox/interactive-map.js, demo/src/components/mapbox/map-controls.js, demo/src/components/markdown-page.js, demo/src/components/page.js, demo/src/components/table-of-contents.js, demo/yarn.lock, examples/plot/orbit-controller.js, examples/plot/package.json, examples/plot/yarn.lock, package.json, src/react/deckgl.js, src/react/webgl-renderer.js, yarn.lock
`deck.gl` is the last remaining dependency of `react-vis` that isn't using the `prop-types` module. This PR fixes that, and gets rid of console warnings when using React >= 15.5
Related 
* uber/react-vis#368
* uber/react-vis#391
=> Migrate from React.PropTypes to `prop-types` module

.travis.yml, package.json
Include `npm build` in `npm test` to make sure commits don't break the build (which is otherwise only run on publish).
=> Remove /examples from coverage. Add report to npm run cover. 

package.json, src/debug/seer-integration.js, src/lib/layer-manager.js, src/lib/layer.js, test/node.js, yarn.lock
Add integration with the soon-to-be born seer.
No performance drawback for production on normal users given the checks over its presence. 
Pass the layer props and allow their edition with an override object that will persist across renders.
Also invalidate the data to be sure we got the latest version of it.
=> feat(dev): seer integration

CHANGELOG.md, docs/layers/grid-layer.md, docs/layers/hexagon-layer.md, examples/layer-browser/src/examples/core-layers.js, src/layers/core/grid-cell-layer/grid-cell-layer-vertex.glsl.js, src/layers/core/grid-cell-layer/grid-cell-layer.js, src/layers/core/grid-layer/grid-aggregator.js, src/layers/core/grid-layer/grid-layer.js, src/layers/core/hexagon-layer/hexagon-aggregator.js, src/layers/core/hexagon-layer/hexagon-layer.js, src/utils/bin-sorter.js, test/layers/grid-layer.spec.js, test/layers/hexagon-layer.spec.js, test/test-utils.js, yarn.lock
- To make grid layer consistent with hexagon layer, add `coverage`, `lowerPercentile`, `upperPercentile` and `getColorValue` to layer prop
- Fix bug in hex `_onGetSublayerColor`, use bin.value instead of bin.points.length to calculate color
=> - Add coverage percentiles getColorValue prop to grid layer 

package.json
Since we don't need to lookup the other lockfiles now, better this way and won't fail if you still using yarn with the private registry on examples
=> chore(lint): simplify command

src/debug/seer-integration.js
Only invalidate the `data` if it has been set as an override.
Also log a limit of 20 data items instead of the full list.
=> fix(seer): improve invalidate and log

CHANGELOG.md, docs/api-reference/deckgl.md, examples/layer-browser/src/app.js, examples/layer-browser/src/components/layer-controls.js, src/lib/draw-and-pick.js, src/lib/layer-manager.js, src/react/deckgl.js
- Add `pickingRadius` prop to `DeckGL` component. The old picking behavior is equivalent to `pickingRadius: 0`. The closest object to the pointer within `pickingRadius` pixels is picked.
=> Add `pickingRadius` prop

CHANGELOG.md, docs/api-reference/base-layer.md, src/lib/layer.js, src/react/deckgl.js
When multiple layers are rendered on the same plane, [z-fighting](https://en.wikipedia.org/wiki/Z-fighting) may create undesirable artifects (e.g. [Issue#411](https://github.com/uber/deck.gl/issues/411)). This PR offsets each layer by a small amount to improve the visual quality of composition. Advanced users can modify the default behavior by specifying their own `getPolygonOffset` accesor.
Remaining issues:
- Does not solve in-layer z-fighting when objects overlap each other
- At a higher zoom level, this solution is undone by precision error. Can only be fixed by turning on `fp64` flag.
=> Reduce z-fighting between layers

src/utils/events/constants.js, src/utils/events/event-manager.js
This update to the single/double-tap workaround from `events-refactor` allows hammer.js to handle `requireFailure()` on its own, and instead drops the single tap / click recognizer interval to 0 by default and bumps it up when doubletap functionality is required.
=> Fix single/double tap workaround.

CHANGELOG.md, src/layers/core/geojson-layer/geojson-layer.js, src/layers/core/grid-layer/grid-layer.js, src/layers/core/hexagon-layer/hexagon-layer.js, src/layers/core/polygon-layer/polygon-layer.js
- Composite layers now pass `getPolygonOffset` prop to children
- `PolygonLayer` and `GeoJsonLayer` orders sublayers dynamically. 3D layers should be drawn last for correct blending with 2D layers.
=> Improve z handling and blending in composite layers

src/utils/events/event-manager.js, src/utils/events/wheel-input.js
Conditionally require hammer.js to avoid failure on server, on `window` and `document` references.
I'm not happy with this solution, but https://github.com/hammerjs/hammer.js/issues/930 suggests there isn't much of a better option for now :/
=> Conditionally require hammer.js

test/node-dist.js, test/test-utils.js
Fix the issue that headless GL context is not created properly on node
=> Fix the layer tests on node

src/layers/core/icon-layer/icon-layer.js
Icon layer did not automatically re-render when texture was loaded.
Remove the old async loading hack and use `setState`.
=> Fix IconLayer async loading

src/utils/events/event-manager.js, src/utils/events/move-input.js, src/utils/events/wheel-input.js
This bug is causing major performance regression when interacting with the map.
Also fixed a bug in event aliasing (always use registered event types instead of source event type).
@ericsoco We are currently firing all three of `pointermove`, `mousemove` and `touchmove` events on any pointer move, which is technically incorrect. `touchmove` should not be fired on `mousemove`, for example. In the case of `pointermove`, we will need to do some poking to determine the source input device. Yet we do not need to make that differentiation in any of our built-in interactions. I propose we remove the `mouse*` and `touch*` aliases and only surface `pointer*` events to avoid confusion.
=> Fix bug where `mousemove` event is fired twice during drag

package.json, test/rendering-test/color-delta.js, test/rendering-test/data-generator.js, test/rendering-test/test-config.js, test/rendering-test/test-rendering.js, test/rendering-test/webpack.config.test-rendering.js
- Only run each test case once
- Proper image diffing
- Add a test case for `METER_OFFSET` mode
Threshold set at 99% of pixels have <5% perceived color difference. Current test result:
```
scatterplot-1: 99.268% PASS
scatterplot-2: 99.925% PASS
scatterplot-1-meters: 12.306% FAIL
```
(expected to be fixed by [607](https://github.com/uber/deck.gl/pull/607))
=> Fix rendering test

docs/api-reference/deckgl.md, docs/whats-new.md, examples/layer-browser/src/app.js, examples/layer-browser/src/components/layer-info.js, src/lib/draw-and-pick.js, src/lib/layer-manager.js, src/react/deckgl.js
Given a bounding box and a list of layer ids (optional), returns an array of unique picking info objects.
As discussed before, the limitation of this API is that it doesn't return occluded objects.
=> Add queryObjects api to DeckGL component

src/shaderlib/project/project.glsl.js
`project_to_clipspace` bug introduced by https://github.com/uber/deck.gl/pull/607
=> Fix modelMatrix in METER_OFFSET mode

examples/point-cloud-laz/app.js, examples/point-cloud-laz/package.json, examples/point-cloud-ply/app.js, examples/point-cloud-ply/package.json
changed how the empty data is checked.
the filtering logics was moved to post-renderLayers() in https://github.com/uber/deck.gl/pull/676,
causing 0, generated by previous check logics, being used as a 'layer' that leads to the error.
=> fix point cloud examples bug

examples/trips/app.js
There was a mismatch as ._animation must be replaced with ._animationFrame to successfully stop listing to animation frames.
=> _animation typo fix

src/lib/layer.js
Fix bug when `data` prop is `null`, `changeFlags.dataChanged` flag is set on each frame.
=> Use constant for empty data fallback

.travis.yml
Use only latest LTS `6.9.1` for travis, as other versions are having too many issues lately and creating false negative build results
WIP
=> test(travis): use pinned latest lts

src/debug/seer-integration.js, src/lib/attribute-manager.js, src/lib/layer-manager.js, src/lib/layer.js, src/lib/stats.js, test/debug/seer-integration.spec.js, test/index.js
=> Seer performance badges for attribute updates and render

examples/graph/app.js, examples/graph/deckgl-overlay.js, examples/graph/graph-layer/graph-layout-layer.js, src/lib/draw-and-pick.js, src/lib/layer.js
Update graph example to maange drag state on its own, using mouse handlers and queryObject().
I branched off of #741, so once that's landed I'll just rebase this to remove the duplicate commit from #741.
(Also, looks like this is the first use of `queryLayers()` in our examples. Works like a charm, thx @Pessimistress 🙏 🙆
=> Graph layer drag refactor

src/lib/props.js, test/lib/index.js, test/lib/props.spec.js
Comparator `equals` from luma.gl's math classes fail when comparing to `null`.
=> Avoid deep comparison error in compareProps when oldProp is empty

examples/tagmap/tagmap-layer/tagmap-layer.js
This worked well in the previous deck.gl version. But in the recently released beta version, the `tagMap` example doesn't call the `updateState` function when the viewport changes. Adding the `shouldUpdateState` function fixed the issue though.
=> TagMap: add shouldUpdateState function

src/react/deckgl.js, src/react/webgl-renderer.js
- Fixes #747 
- Update canvas size to match with device framebuffer for each frame, considering logical size and `devicePixelRation`
- Use canvas size to set viewport.
@ibgreen @Pessimistress  : not ready to merge, have some open questions
=> Update canvas size to match with device framebuffer size.

src/lib/layer.js
`polygonOffset` parameter was not applied.
=> Fix `getPolygonOffset` prop

src/layers/core/icon-layer/icon-layer-vertex.glsl.js
sqrt(1 - cos^2) lead to all positive values, only 180-360 degree ranges cannot be obtained, use sin instead.
@shaojingli
=> [icon-layer] use sin to get 180-360 degree ranges

CHANGELOG.md, src/layers/core/grid-cell-layer/grid-cell-layer.js, src/layers/core/grid-layer/grid-layer.js, src/layers/core/hexagon-layer/hexagon-layer.js
For easier subclassing:
- Add static methods to layer class
- Add method `getSubLayer ` to get SubLayer class
- Add method `getSubLayerProps` to get SubLayer props
=> Hex grid layer methods

CHANGELOG.md, src/layers/core/hexagon-cell-layer/hexagon-cell-layer.js, test/layers/hexagon-cell-layer.spec.js
updateState no longer called when viewport updates, move update angle and radius to draw because it is based on viewport
=> hexagonCellLayer call update angle and radius in draw()

docs/upgrade-guide.md, examples/plot/package.json, examples/trips/package.json, src/layers/core/arc-layer/arc-layer.js, src/layers/core/grid-cell-layer/grid-cell-layer.js, src/layers/core/hexagon-cell-layer/hexagon-cell-layer.js, src/layers/core/icon-layer/icon-layer.js, src/layers/core/line-layer/line-layer.js, src/layers/core/path-layer/path-layer.js, src/layers/core/point-cloud-layer/point-cloud-layer.js, src/layers/core/scatterplot-layer/scatterplot-layer.js, src/layers/core/screen-grid-layer/screen-grid-layer.js, src/layers/core/solid-polygon-layer/solid-polygon-layer.js, src/shaderlib/lighting/lighting.js
* Now that 'project' module is added by default, remove code supplying to `model` object.
* Add dependency `lighting` -> `project`, so modules are inserted in right order.
* Tested with : test-browser, layer-browser, examples.
NOTE: not ready to merge, requires luma.gl change (https://github.com/uber/luma.gl/pull/270)
=> ShaderModule: Remove supplying 'project' module, fix 'lighting' module dependency.

docs/api-reference/base-layer.md, examples/graph/graph-layer/graph-layer.js, examples/icon/deckgl-overlay.js, examples/scatterplot/deckgl-overlay.js
Per feedback of
https://github.com/uber/deck.gl/issues/577#issuecomment-314934239
- Better explanation of `updateTriggers` in layer documentation
- Remove arbitrary trigger keys from examples to avoid confusion
=> Update doc for updateTriggers

examples/plot/plot-layer/axes-layer.js
Fix the axes layer for new shader module system. This is a quick fix for examples. We'll add support for layers with multiple models in the core library in the future.
@1chandu @Pessimistress
=> Fix AxesLayer for the plot example

docs/upgrade-guide.md, docs/whats-new.md
@Pessimistress @gnavvy @1chandu
=> Update whats new and upgrade guide

CHANGELOG.md, docs/advanced/layer-lifecycle.md, docs/layers/hexagon-layer.md, docs/layers/icon-layer.md, src/layers/core/icon-layer/icon-layer.js
did a sweep on the docs and update logs for the post-v4.0.0 PRs (#548-#787).
most changes are documented (if we were not to document internal methods changes like in #783).
also, we don't have any docs on how shaderCache works, consider it as implicit from the users for now?
=> V4.1 doc update

CHANGELOG.md, package.json, src/lib/constants.js, src/shaderlib/project/project.glsl.js, src/shaderlib/project/viewport-uniforms.js, src/viewport-mercator-project/web-mercator-utils.js, src/viewports/web-mercator-viewport.js, test/viewports/web-mercator-viewport.spec.js
Reverts most of https://github.com/uber/deck.gl/pull/806
As discussed, the plan is to provide a more generic solution for alternative projections, as opposed to including arbitrary modes and dependencies in deck.gl.
=> Remove UTM_OFFSETS mode

examples/wind/src/layers/delaunay-cover-layer/delaunay-cover-layer.js, examples/wind/src/layers/particle-layer/particle-layer.js, examples/wind/src/layers/wind-layer/wind-layer.js
- Port depth behavior from demo version. This matches rendering of particles/elevations with the demo.
- Increase field layer sample count, to show high wind speeds at `mount washington`.
=> wind demo: fix particle/elevation rendering

CHANGELOG.md, docs/api-reference/base-layer.md, docs/whats-new.md, src/layers/core/path-layer/path-layer-fragment.glsl.js, src/layers/core/path-layer/path-layer-vertex.glsl.js, src/layers/core/path-layer/path-layer.js, src/layers/core/scatterplot-layer/scatterplot-layer-fragment.glsl.js, src/layers/core/scatterplot-layer/scatterplot-layer-vertex.glsl.js, src/layers/core/scatterplot-layer/scatterplot-layer.js, src/lib/draw-and-pick.js, src/lib/layer.js, src/shaderlib/index.js, src/shaderlib/picking/picking.js, src/shaderlib/picking/shadertools-picking.md
- Copy picking module from luma.gl, this is temporary and avoids dependencies as I make changes to this module, once all layers are modified to use picking module, I will update luma version and remove it from deck.gl.
- Add new props required for highlighting as described in RFC : https://github.com/uber/deck.gl/pull/839
- Update Scatterplot and Path layer shaders to use picking module.
- Verified rendering/performance using layer-browser example.
- Found one issue related to mouse leave event : #847
=> Automatic/custom highlighting using picking shader module.

CHANGELOG.md, docs/README.md, docs/advanced/performance.md, docs/get-started/getting-started.md, docs/get-started/using-layers.md, docs/get-started/using-with-mapbox-gl.md, docs/layers/README.md, docs/layers/arc-layer.md, docs/layers/geojson-layer.md, docs/layers/grid-cell-layer.md, docs/layers/grid-layer.md, docs/layers/hexagon-cell-layer.md, docs/layers/hexagon-layer.md, docs/layers/icon-layer.md, docs/layers/line-layer.md, docs/layers/path-layer.md, docs/layers/point-cloud-layer.md, docs/layers/polygon-layer.md, docs/layers/scatterplot-layer.md, docs/layers/screen-grid-layer.md, docs/layers/solid-polygon-layer.md, docs/upgrade-guide.md, docs/whats-new.md, website/contents/pages.js
There are not many textual changes here, mostly structural updates and some edits due to proof reading. I'll land this without review but will be happy to address any comments post-facto.
There are a few new sections in the performance doc, if anything you may want to look at those.
=> Doc paragraph reformatting. Bump code links to 4.1-release

docs/advanced/performance.md, docs/advanced/picking.md, docs/api-reference/deckgl.md, docs/get-started/interactivity.md
Some cleanup of the overall picking/interactivity/event-handling documentation complex.
- I tried to keep new features out of this pass so that it could be merged to current 4.1-release and website.
- We should discuss how to add documentation for in-progress features such as auto highlighting, use of new picking module, and a presumably public EventManager class.
=> A pass on refreshing picking and event handling docs

dev-docs/RFCs/README.md, dev-docs/RFCs/drafts/reduce-distribution-size.md, dev-docs/RFCs/drafts/reducing-distribution-size.md
Since we are in RFC creation mode for deck.gl, did a write-up on current thoughts around reducing distribution size.
#621
@georgios-uber  @romaxa
=> Reducing distribution size RFC

docs/advanced/performance.md, docs/api-reference/deckgl.md, docs/api-reference/layer-manager.md, docs/whats-new.md, examples/wind/src/wind-demo.js, src/lib/draw-and-pick.js, src/lib/layer-manager.js, src/react/deckgl.js
- `useDevicePixelRatio` prop will be single point of truth to use retina resolution of the device or not, will affect picking and normal rendering.
- Verified using layer-browser example, by setting `useDevicePixelRatio` to true and false.
=> Add useDevicePixelRatio prop to DeckGL component.

examples/layer-browser/src/examples/core-layers.js, src/layers/core/screen-grid-layer/screen-grid-layer.js
Fixes #602 - removes the artifacts in layer-browser. We can discuss if this should be the default parameter setting in `ScreenGridLayer`.
=> Add depthTest:false to ScreenGridLayer

src/lib/draw-and-pick.js
=> Make sure picking blend modes override layer `parameters` during picking

docs/advanced/subclassed-layers.md, examples/brushing/arc-brushing-layer/arc-brushing-layer.js, examples/brushing/scatterplot-brushing-layer/scatterplot-brushing-layer.js, examples/text-layer/text-layer/multi-icon-layer/multi-icon-layer.js
=> Update docs for `getShaders()`

docs/layers/hexagon-cell-layer.md, examples/brushing/deckgl-overlay.js, examples/layer-browser/src/examples/core-layers.js
Brushing : data source only contains vec2, use '0' for z component. Fixes #882 
Layer-browser:GeoJson : enable fp64 by default to avoid z-fighting between layers. Fixes #411 
Minor documentation changes. Fixes #840
=> Example fixes.

dev-docs/RFCs/README.md, dev-docs/RFCs/v5.0/multi-viewport-rfc.md, src/experimental/react/deckgl-multiview.js, src/experimental/react/deckgl-multiview.md, src/experimental/react/viewport-layout.js, src/experimental/react/viewport-layout.md, src/index.js
This adds two new React components in the `experimental` folder: `DeckGLMultiView` and `ViewportLayouts`. The RFC text is included, as are documentation fragments for the new components.
=> Multi viewport support

src/layers/core/icon-layer/icon-layer-vertex-64.glsl.js, src/layers/core/icon-layer/icon-layer-vertex.glsl.js, src/layers/core/icon-layer/icon-layer.js
A different (and better) fix for #834 as opposed to the way originally proposed. Manipulate the vertex scaling and rotation in "pixel" values before converting back to "fraction" in the screen space.  No need to calculate the aspect ratio and factor it in the rotation function. To do this, it is better to pass the anchor position into the shader as pixel values instead of normalizing it (see the change in `icon-layer.js`). The `devicePixelRatio` is used to avoid hardcoding in the previous implementation.
=> Fix the icon rotation issue

CHANGELOG.md, src/controllers/controls.js, src/controllers/first-person-state.js, src/controllers/map-state.js, src/index.js, src/react/controllers/viewport-controller.js, src/viewports/viewport.js
This PR continues the generalization of controllers.
The vision is that there should be only one react component: 
```
<ViewportController >
```
that can take a state class and do the right thing
This PR is a partial step, it leaves things in a "half finished" state:
- temporarily breaking `npm run start-local` in some non-geospatial examples.
- more work is needed on `FirstPersonState` to handle mouse events.
- `OrbitState` should be updated to work better with `ThirdPersonViewport`.
- All `Viewports` should be able to extract at least some information from each `State` class
=> New controllers

src/lib/draw-and-pick.js
- Clear color should be set before drawing any layers for picking. When none of the layers are eligible for picking, we still get correct picking results (alpha channel will be 0).
- Return early from picking flow, when layer count is 0.
- Fixes an issue with `point-cloud-laz` example.
- Tested with `test-browser` and `layer-browser`.
=> Fix picking buffer clear color.

examples/wip/data/cities.json, examples/wip/viewport-animation-3d-heatmap/README.md, examples/wip/viewport-animation-3d-heatmap/app.js, examples/wip/viewport-animation-geojson/README.md, examples/wip/viewport-animation-geojson/app.js, examples/wip/viewport-animation/README.md, examples/wip/viewport-animation/app.css, examples/wip/viewport-animation/index.html, examples/wip/viewport-animation/package.json, examples/wip/viewport-animation/src/app.js, examples/wip/viewport-animation/src/control-panel.js, examples/wip/viewport-animation/src/root.js, examples/wip/viewport-animation/webpack.config.js, src/experimental/react/controllers/viewport-animation-utils.js, src/index.js, src/react/experimental/animation-map-controller.js, src/react/experimental/viewport-animation-utils.js
- Adding a utility method to achieve flyTo style animation.
- Copy react-map-gl's `viewport-animation` example and update to test flyTo style animation.
- Add new props to support map interaction and loop style animations.
Next steps:
- documentation.
- update `viewport-animation` to test all combinations of animation props.
=> Viewport Animation: Adding flyTo style animation support.

src/core-layers/grid-cell-layer/grid-cell-layer-vertex-64.glsl.js, src/core-layers/grid-cell-layer/grid-cell-layer-vertex.glsl.js, src/core-layers/grid-layer/grid-layer.js, src/core-layers/hexagon-cell-layer/hexagon-cell-layer-vertex-64.glsl.js, src/core-layers/hexagon-cell-layer/hexagon-cell-layer-vertex.glsl.js, src/core-layers/hexagon-layer/hexagon-layer.js
- Add checks in grid fp64 to hide cell when filtered by elevation (same operation as the none fp64, this is a patch to #954 
- Fix grid cell layer position shifts on fp64 #962
=>  [Hexagon/Grid] add no render when elevation < 0.0 to vertex-64

docs/api-reference/layer-manager.md, docs/layers/grid-cell-layer.md, docs/layers/grid-layer.md, docs/layers/hexagon-layer.md, docs/layers/scatterplot-layer.md, docs/layers/solid-polygon-layer.md, docs/whats-new.md, examples/layer-browser/src/examples/core-layers.js, package.json, src/layers/core/grid-cell-layer/grid-cell-layer-vertex-64.glsl.js, src/layers/core/grid-cell-layer/grid-cell-layer-vertex.glsl.js, src/layers/core/grid-layer/grid-layer.js, src/layers/core/hexagon-cell-layer/hexagon-cell-layer-vertex-64.glsl.js, src/layers/core/hexagon-cell-layer/hexagon-cell-layer-vertex.glsl.js, src/layers/core/hexagon-layer/hexagon-layer.js, src/lib/composite-layer.js, src/lib/draw-and-pick.js, src/lib/layer-manager.js, src/utils/bin-sorter.js, src/utils/scale-utils.js, test/layers/grid-layer.spec.js, test/layers/hexagon-layer.spec.js, test/lib/index.js, test/lib/layer-manager.spec.js, test/test-utils/setup-gl.js
Cherry picked following from master :
- Fix picking buffer clear color. (#931)
- Handle recursive layer ids, update LayerManager docs and tests. (#933)
- Hexagon Layer: Add getElevationValue to calculate hexagon elevation by aggregation (#938)
- Update docs with missing layer props. (#959)
- Grid Layer: Add getElevationValue to enable grid elevation by aggregation (#954)
- Hexagon/Grid Layer: Fix FP64 mode rendering when elevation < 0.0 (#968)
Had to selectively pick changes from #933 as some of the changes are on top of 4.2 changes.
Tested with `test-browser` and all layers in `layer-browser`.
=> 4.1.3 patch

src/core/lib/layer.js, test/src/core/lib/layer.spec.js
https://github.com/uber/deck.gl/issues/950
Include `diffUpdateTriggers` result in `changeFlags.propsOrDataChanged`.
=> Fix bug where layer does not update on updateTriggers change

src/core/lib/draw-layers.js, src/core/lib/layer-manager.js, src/core/lib/pick-layers.js, src/core/lib/seer-integration.js, src/core/pure-js/deck.js, src/react/deckgl.js
* Split `draw-and-pick` into `draw-layers` and `pick-layers`
* Keep push drawing and picking code into these files from `deck` and `layer-manager`.
PR looks bigger than it is due to file split, not much I can do about that.
=> Big draw and pick refactor

examples/layer-browser/package.json, examples/layer-browser/src/app.js, examples/layer-browser/webpack.config.js, examples/webpack.config.local.js
* New option to show picking buffer contents, helpful for debugging picking in complex framebuffer based layers
* Allows luma version to be controlled in start-local etc, allows testing latest luma patches in layer browser
=> layer-browser: show picking buffer, support luma.gl override during local dev

src/core/deprecated/shaderlib/project/project-deprecated.glsl.js, src/core/shaderlib/project/viewport-uniforms.js
When I was porting packed point cloud shaders from ATG to a customized deck.gl layer, found that there is no way to access viewMatrix, here add it back.
=> add viewMatrix back so users can access it in their own vertex shader

dev-docs/RFCs/v5.0/auto-highlighting-rfc.md, docs/api-reference/react/deckgl.md, src/core/lib/draw-layers.js, src/core/lib/layer-manager.js
Fix for #979
Verified picking and highlighting with `layer-browser` and running website (examples).
=> Fix picking and highlighting regressions.

src/core/lib/layer.js, src/core/lib/pick-layers.js
Verified with `layer-browser`.
Found a regression on master for picking/highlighting feature (#979), will re-test this after it is resolved.
=> Skip picking flow when no layer is pickable

src/core/viewports/web-mercator-viewport.js, test/src/core/viewports/web-mercator-viewport.spec.js
Was calling `this.metersToLngLatDelta` with incorrect parameters.
=> Fix WebMercatorViewport.addMetersToLngLat

examples/wind/src/app.js, examples/wind/src/control-panel.js, examples/wind/src/wind-demo.js, src/core/lib/layer.js, src/core/pure-js/deck-js.js
Fix for #843 
- Turn 'useDevicePixelRatio' to true, to match previous behavior.
- Add an option to toggle 'useDevicePixelRatio' to wind example. (This is useful in testing as layer-browser rendering doesn't change much when toggling this option.)
Verified with: `test-browser`, `layer-browser` (picking/highlighing/toggling useDevicePixelRatio) and `examples`.
=> Fix useDevicePixelRatio prop usage

test/bench/browser.js, test/bench/index.js, test/bench/node.js, test/test-utils/layer-utils.js
Fixed:
- Missing gl context error in `Layer.initializeState`
- Wrong `getPosition` accessor for `ScatterplotLayer`
- Wrong `data` format and `getPolygon` accessor for `PolygonLayer`
- Overflow error in `Layer.encodePickingColor`
Added:
- Bench tests for `SolidPoligonLayer` (actually calling the tesselators)
=> Fix benchmark tests

src/index.js
Make it possible to access all the helper functions used by layers from outside deck.gl, so that layers can be copied to an app and modified with a minimum of code changes.
=> Add experimental exports

README.md, examples/README.md, examples/wind/src/app.js, examples/wind/src/control-panel.js, examples/wind/src/wind-demo.js, src/core/lib/layer.js, src/core/lib/pick-layers.js, src/core/pure-js/deck-js.js, src/index.js, test/bench/browser.js, test/bench/index.js, test/bench/node.js, test/test-utils/layer-utils.js
As said in #1000, the query visible object button doesn't work in layer-browser, fix the bug in pick-layers.js where a for loop is not valid because of wrong condition check.
Tested with "npm run test-browser" and "layer-browser" example.
=> Fix issue that visible object query in layer-brower returns empty

src/core/lib/draw-layers.js, src/core/lib/pick-layers.js
Verified with : `test-browser`, `examples`, `layer-browser` (toggle useDevicePixelRatio and verify picking/highlighting).
=> Pass useDevicePixelRatio to picking flow.

src/core/lib/pick-layers.js
- When picking multiple layers, starting with non-pickable layers, if we only render pickable layers, resulting layerIndex is used on original layers, causing wrong layer being picked. Used pickableLayers to only detect early return, but always render all layers.
=> Fix picking when rendereing pickable and non-pickable layers

src/core/lib/pick-layers.js
Verified with: `test-browser`, `examples`, `layer-browser` (Query Visible Object with/without retina).
=> Pass useDevicePixelRatio to picking flow

docs/layers/geojson-layer.md
Per request in #1027, add meter as the unit.
=> Specify meter unit for getLineWidth in geojson layer

src/core/viewports/orbit-viewport.js
I have a PureJS use case where only deck.gl core is imported to avoid React dependency. This line breaks it.
=> Fix Viewport import in OrbitViewport

examples/layer-browser/src/examples/core-layers.js
Micro fix for blending in our scatterplot layer example.  Before and after:
=> Fix blending in ScatterplotLayer example

src/core/lib/layer.js, src/core/lib/props.js, test/src/core/lib/layer.spec.js
Consolidates prop diffing and moves prop related code from `layer.js` to `props.js`. 
* Will make layer code easier to work with, and to prepare for features like more sophisticated prop diffing, prop types and prop animations/transitions.
* simple interface, the new `diffProps` function just returns an object with changeFlags.
* and a callback is supplied by the layer to handle any detected updateTriggers.
Tested in layer-browser.
=> Move prop diffing from layer.js to props.js

examples/point-cloud-ply/app.js, src/core/deprecated/viewports/orthographic-viewport.js, src/core/deprecated/viewports/perspective-viewport.js
This is a temporary fix to bring OrthographicViewport-dependent apps to a good state.
Later the OrthographicViewport will extend the ThirdPersonViewport instead of the base Viewport once all functions are fully tested in new ThirdPersonViewport.
To test:
Use either the `svg-interoperability` or the `graph` example in the /examples folder.
Before: nothing/partially visible in the viewport.
After: visual elements are properly rendered.
(There's a bug in the graph example that the hovered info is y-flipped, will fix in a later PR)
=> temporary fix for orthographic-viewport dependent apps

src/react/experimental/transition-manager.js, src/react/viewport-controller.js
Default props of transition params were not always applied, make them part of `ViewportController` `defaultProps`.
Verified with : 
test-browser
layer-browser ( interact with map to trigger viewport change, default values get applied here)
all 3 viewport transition examples.
=> Apply default values for transition props

src/core/experimental/lib/effect.js, src/core/lib/attribute-manager.js, src/core/lib/draw-layers.js, src/core/lib/layer-manager.js, src/core/lib/layer.js, src/core/pure-js/deck-js.js
This PR enables every redraw call to be logged with a reason to help quickly trace down the root cause of unnecessary redraws
Depends on #1036 for full functionality (tracing picking reasons) but can be landed independently.
=> Improved tracking and logging of redraw reason

src/core/lib/pick-layers.js
In pick-layers, instead of picking functions starting with rendering and reading the picking buffer, and then extracting data from it, the rendering was deeply nested.
Every time we change rendering parameters there were bugs introduced by forgetting to forward them to rendering at some stage.
This change is also needed for an "improved redraw logging" PR which is staged after this.
=> Remove excessive nesting in picking code

dev-docs/RFCs/v5.0/multi-viewport-rfc.md, docs/advanced/viewports.md, examples/layer-browser/src/app.js, examples/wip/first-person-map/app.js
Before this feature is added layer-browser rendered with full device pixel ratio, match the behavior by setting `useDevicePixelRatio` default value to true in the example.
=> Examples: set useDevicePixelRatio by default

src/react/experimental/transition-manager.js, src/react/experimental/viewport-transition-utils.js, src/react/viewport-controller.js
Consolidating changes and feedback from https://github.com/uber/react-map-gl/pull/383
- Fix incorrect timer, replace `setInterval` with `requestAnimationFrame`
- Always use the transition settings from when the transition is triggered (removes the burden from app: set and forget)
- Use `onViewportChange` for transition update callback
- Do not trigger transition on viewport size change
- Do not compare viewports if there's no transition
- Remove nested function definitions in utils
=> Transition manager improvements

examples/wip/first-person-map/app.js, examples/wip/first-person-map/package.json, src/core/controllers/first-person-state.js, src/core/controllers/map-state.js, src/core/controllers/view-state.js, src/core/viewports/first-person-viewport.js, src/react/viewport-controller.js
Per discussion in https://github.com/uber/deck.gl/issues/986
Additional fixes:
- Firstperson Viewport: Always calculate `direction` from `bearing` and `pitch`.
- Cleanup the `first-person-map` example.
- Fix `ViewportController` prop type for `position`.
Verified with `layer-browser` and `first-person-map` example.
=> Separate common ViewState from FirstPersonState and MapState

examples/plot/app.js, examples/point-cloud-laz/app.js, examples/point-cloud-ply/app.js, src/core/viewports/orbit-viewport.js
Current fitBounds API recalculates user's 'lookat' position and distance based on a bounds to make sure canvas size can fit bound size. But changing of 'lookat' position will trigger new behaviors user doesn't expect, like model rotates on a new axis.
The PR here is to keep 'lookat' position untouched unless user changes it, and the bounds is always centered at 'lookat' position.
=> Quick fix of fitBounds API in orbit-viewport and examples

examples/layer-browser/src/examples/experimental-layers.js, src/experimental-layers/src/index.js, src/experimental-layers/src/text-layer/font-atlas.js, src/experimental-layers/src/text-layer/multi-icon-layer/multi-icon-layer-vertex-64.glsl.js, src/experimental-layers/src/text-layer/multi-icon-layer/multi-icon-layer-vertex.glsl.js, src/experimental-layers/src/text-layer/multi-icon-layer/multi-icon-layer.js, src/experimental-layers/src/text-layer/text-layer.js, src/experimental-layers/src/text-layer/text-layer.md
A few changes to the original text layer in the example folder:
- New features added: including `getTextAnchor`, `getAlignmentBaseline`, `getPixelOffset`. (Details in the doc)
- Dynamically generate font atlas once the layer is initialized. No need to read static json and bitmap files. This change avoids the headache of adding additional webpack loaders or plugins to deal with those static assets.
- Use `project_pixel_to_clipspace` in the shader to deal with conversion between pixels and clipspace coordinates. (Will create another PR to make this change to the icon layer)
- An example added in the layer-browser. Run `yarn start-local` to see the result.
Once this is officially added to the core layers, we can remove the duplicated code in the text-layer and tagmap examples.
=> Move text layer to experimental layers

src/core/lib/composite-layer.js, src/core/lib/layer-manager.js, src/core/lib/layer.js, src/core/lib/props.js, src/core/utils/log.js, test/src/core/lib/layer.spec.js, test/test-utils/layer-utils.js, test/test-utils/spy.js
This PR is an initial effort towards making our layer life cycle more rigorous, this one focuses on change flag handling
* changeFlags handling now goes through `layer.setChangeFlags` and `layer.clearChangeFlags`
* The idea here is that this will enable us to decouple setting of changeFlags and actual updates, allowing changeFlags to accumulate but postponing the update until we need to do it. Think layers with `visible: false`
* `LayerManager` is now no longer responsible for sending changeFlags to layer.updateLayer. It sets the changeFlags and then calls updateLayer. This simplifies logic in `LayerManager` which is where simplification really counts.
* Drops `Layer.invalidateAttribute` which added nothing and just created one more method for layer writers to be confused by.
=> More rigorous changeFlags handling.

examples/wip/viewport-animation-geojson/app.js, examples/wip/viewport-animation/src/app.js, src/core/lib/transition-manager.js, src/react/viewport-controller.js
This includes following two changes :
1. `ViewportController` intercepts and updates all children props to avoid a jump when viewport is updated with transition enabled, this can be achieved by using `shouldComponentUpdate()`, which returns false when a new transition is triggered and hence skipping the render for itself and all its children. All following viewport updates are handled by 'onViewportChange()' called by `TransitionManger`. This should make code a lot less complicated and also makes it easy to integrate Viewport Transitions with Multi-viewports feature.
2. In `TransitionManger`, this.props should be set before calling '_triggerTransition()' which calls `_updateViewport` that uses this.props.
Verified with all 3 viewport-animation examples and layer-manager. #2 fixes an issue …
=> ViewportTransitions: remove recursive children update, fix props update

src/core/lib/composite-layer.js, src/core/lib/layer-manager.js, src/core/lib/layer.js, src/core/lib/props.js, src/core/utils/log.js, test/src/core/lib/layer.spec.js, test/test-utils/layer-utils.js, test/test-utils/spy.js
Reverts uber/deck.gl#1051 - since this is part of a series of life cycle change PRs that all have a risk of introducing issues, will move this work to a `4.2-dev` branch to keep `master` stable.
=> Revert "More rigorous changeFlags handling."

docs/api-reference/react/deckgl.md, docs/whats-new.md, src/core/lib/draw-layers.js, src/core/lib/layer-manager.js, src/core/lib/pick-layers.js, src/core/pure-js/deck-js.js
A new optional prop that takes (layer, viewport) and allows filtering out layers in specific viewports or from rendering or picking.
Also a bit more functional breakdown in pick-layers.js. No logic changes.
=> Add `layerFilter` prop

examples/wip/viewport-animation-first-person-map/app.js, examples/wip/viewport-animation-first-person-map/index.html, examples/wip/viewport-animation-first-person-map/package.json, examples/wip/viewport-animation-first-person-map/webpack.config.js, src/core/viewports/web-mercator-viewport.js
- Create multi-viewport transition example using existing first-person-map example.
- Add bias to 'isMapSynched' to avoid flashes during transition.
Verified with layer-browser.
=> MultiViewport Transitions: Add example, and fix `isMapSynced`.

src/core/lib/layer.js
Quick fix on `master` to ensure the `invalidateAttribute` function is still called.
=> Fix attribute updates for composite layers

docs/layers/geojson-layer.md, docs/layers/polygon-layer.md, docs/layers/solid-polygon-layer.md, examples/layer-browser/src/app.js, examples/layer-browser/src/examples/core-layers.js, src/core-layers/geojson-layer/geojson-layer.js, src/core-layers/polygon-layer/polygon-layer.js, src/core-layers/solid-polygon-layer/solid-polygon-layer-vertex-64.glsl.js, src/core-layers/solid-polygon-layer/solid-polygon-layer-vertex.glsl.js, src/core-layers/solid-polygon-layer/solid-polygon-layer.js
- bug fix: Recalculate geometry when updateTriggers.getElevation has changed
- add elevationScale
=> PolygonLayer- add elevationScale, fix updateTriggers.getElevation doesn't trigger updateGeometry

examples/wip/viewport-animation-3d-heatmap/app.js, examples/wip/viewport-animation-first-person-map/app.js, examples/wip/viewport-animation/package.json, examples/wip/viewport-animation/src/app.js, src/core/controllers/map-state.js, src/core/index.js, src/core/lib/transition-manager.js, src/core/lib/viewport-transition-utils.js, src/core/math/utils.js, src/react/viewport-controller.js, website/src/components/home.js
Viewport Transition updates : 
* Normalize angle props (bearing and pitch) before saving them in TransitionManger.
* For angle props, take shortest interpolation path always
* When interpolating bearing -120 -> 120 (240 degree change), change them to 240 -> 120 (120 degree change)
* Add new prop 'transitionProps', which is an array of viewport props that will be interpolated, this will allow applications to change props (that are not part of `transitionProps`) while animating props specified using `transitionProps`. For example, an application can change `latitude` and `longitude`  while `bearing` and `pitch` are in transition.
* Add asserts to help debugging.
Verified with all 4 viewport-animation examples and layer-browser.
=> Transitions: Add transitionProps, fix bearing and longitude interpolation.

src/core/lib/transition-manager.js
* Add `inTransition: true` argument to `onViewportChange`, so application know the source of the callback.
Verified with layer-browser and viewport transition examples.
=> Add flag for viewport transition updates

examples/plot/app.js, examples/point-cloud-laz/app.js, examples/point-cloud-ply/app.js, src/core/controllers/orbit-state.js, src/core/viewports/orbit-viewport.js
1. Can specify both 'Y' and 'Z' axis as orbit axis instead of 'Y' only
2. Change translate to world space instead of screen space
3. Change scale to world space in stead of screen space, which makes frustum clipping fails
Tested with point-cloud-laz, point-cloud-ply and plot examples
=> Fix issues in Orbit Viewport and update examples

src/react/experimental/orbit-controller.js
Pan event doesn't work well in orbit controller, can't pan along the Y direction. here add the right canvas size to root element to fix the issue.
Tested with point-cloud-ply example.
=> Fix the pan event handling of orbit controller

src/core/viewports/viewport.js
Tested with layer-browser, point-cloud-ply and graph examples
=> Remove y-flip and camera re-center logic for non-geospatial viewport

src/core/lib/layer-manager.js
- Enable program caching in 'ShaderCache' class.
- Corresponding luma.gl PR (https://github.com/uber/luma.gl/pull/352)
=> Enable Program caching

examples/plot/app.js, examples/point-cloud-laz/app.js, examples/point-cloud-ply/app.js, src/core/controllers/orbit-state.js, src/core/viewports/orbit-viewport.js
This is the second round to improve Orbit Controller, includes these items.
1. Continue to move panning from clip space to world space, which can avoid rendering distortion and inaccurate depth clipping
2. Change the old Orbit State modeling from (lookAt, translateX, translateY, pitchAngle, rotationAngle) to (lookAt, pitchAngle, rotationAngle), cause translate and rotation is dependent with each other which makes the logic much more complicated.
3. Clean up code for pan, rotation and zoom to adapt new modeling
Tested with plot, point-cloud-laz and point-cloud
=> Orbit Controller refactor to improve pan, rotation and zoom

src/core/lib/attribute-manager.js
@georgios-uber  this should resolve the uncertainty around whether `invalidateAll` actually invalidates all attributes.
=> AttributeManager.invalidateAll() now invalidates all attributes.

src/core/lib/layer.js, src/core/lib/props.js
This PR is to prepare the fixes for `PolygonLayer`, where `updateTriggers` change does not trigger polygon tessellation. This PR adds the changed triggers to `changeFlags.updateTriggersChanged`, so that each layer has knowledge of which triggers have changed.
- If any trigger has changed. `changeFlags.updateTriggersChanged` will be an object `{getElevation: true}` or `{all: true}`
- If none has changed `changeFlags.updateTriggersChanged`  will be `false`
=> add triggers changed to changeFlags.updateTriggersChanged

dev-docs/RFCs/v4.1/picking-improvements-rfc.md, docs/advanced/performance.md, docs/api-reference/layer-manager.md, docs/api-reference/react/deckgl.md, docs/get-started/interactivity.md, docs/layers/path-layer.md, docs/shader-modules/project.md, docs/whats-new.md, examples/graph/app.js, examples/layer-browser/src/app.js, examples/wind/package.json, examples/wind/src/app.js, examples/wind/src/control-panel.js, examples/wind/src/wind-demo.js, src/core-layers/path-layer/path-layer.js, src/core-layers/polygon-layer/polygon-layer.js, src/core/lib/draw-layers.js, src/core/lib/layer-manager.js, src/core/lib/layer.js, src/core/lib/pick-layers.js, src/core/pure-js/deck-js.js, src/core/shaderlib/project/viewport-uniforms.js, src/experimental-layers/src/path-outline-layer/path-outline-layer.js, src/react/deckgl.js
- Query API 
- Rename : queryVisibleObjects -> pickObjects, queryObject -> pickObject
- Support old methods with a deprecated message.
- Add an  item to whats-news section in docs.
- Rename: useDevicePixelRatio -> useDevicePixels (AnimationLoop class in luma.gl still has useDevicePixelRatio, will change that in a separate PR)
- Update docs.
- PathLayer:
- Rename 'justified' to 'dashJustified', update docs.
Tested with layer-browser (toggle `useDevicePixels`, picking, pickObjects) and website/examples.
=> Part-1 : 4.2 API changes as per Audit.

examples/js/carto/package.json, examples/js/with-mapbox-map/package.json, examples/js/without-map/package.json, examples/plot/package.json, examples/point-cloud-laz/package.json, examples/point-cloud-ply/package.json, examples/tagmap/package.json, examples/text-layer/package.json
Don't need specify luma.gl version in example's package.json, which could introduce dependency conflicts and make example invalid.
Tested with examples under example folder
=> Remove luma.gl dependency in package.json to avoid conflict with deck.gl

package.json
Use `^` to lock on major version to avoid any breaking changes in next major version.
Tested with `wip/viewport-transition` that uses project methods from `viewport-mercator-project`.
=> Fix viewport-mercator-project version dependency

src/core/index.js, src/react/deckgl.js
Found some warnings while using latest alpha release, after investigation the log import is not correct.
WARNING in ./~/deck.gl/dist-es6/react/deckgl.js
70:6-9 "export 'log' was not found in '../core'
WARNING in ./~/deck.gl/dist-es6/react/deckgl.js
88:6-9 "export 'log' was not found in '../core'
=> Fix log import errors

src/core/pure-js/deck-js.js
ScatterplotLayer with `getColor: d => [0, 0, 0, 50]`
Before:
After:
=> Fix default alpha blend mode

docs/upgrade-guide.md, src/core/lib/draw-layers.js, src/core/lib/pick-layers.js, src/core/pure-js/deck-js.js
Requiers luma.gl changes : https://github.com/uber/luma.gl/pull/355
* Device Pixel Ratio: Update AnimationLoop API from `useDevicePixelRatio` to `useDevicePixels`
* Auto-highlighting: Remove setting `pickingSelectedColorValid` and only set `pickingSelectedColor`, internally picking module disables the highlighting if `pickingSelectedColor` is invalid or equal `PICKING_NULL_COLOR`.
Tested with : node, browser, examples and layer-browser (toggle useDevicePixels and auto-higlighting on several layers).
=> Part-2 : 4.2 API changes as per Audit

src/core/controllers/map-state.js, src/core/viewports/viewport.js
- Fix `project`/`unproject`  `options.topLeft` to behave as per documentation.
- Our viewports are setup with top-left as origin, so perform `y-flip` only when `topLeft=false`.
Fixes #1167 
Tested with: `test-browser`, `layer-browser`, `plot`, `point-cloud-ply` and `point-cloud-laz`.
=> Fix viewport projection topLeft option

docs/layers/geojson-layer.md, docs/layers/polygon-layer.md, docs/layers/solid-polygon-layer.md, examples/layer-browser/src/app.js, examples/layer-browser/src/examples/core-layers.js, src/layers/core/geojson-layer/geojson-layer.js, src/layers/core/polygon-layer/polygon-layer.js, src/layers/core/solid-polygon-layer/solid-polygon-layer-vertex-64.glsl.js, src/layers/core/solid-polygon-layer/solid-polygon-layer-vertex.glsl.js, src/layers/core/solid-polygon-layer/solid-polygon-layer.js
#1046
tested with
- npm run tests
- All layers in layer-browser able to render
- toggle polygon layer, geojson layer 'extruded'
- slide polygon layer, geojson layer elevationScale
=> apply #1046 to 4.1

docs/advanced/picking.md, docs/advanced/writing-shaders.md, docs/upgrade-guide.md, src/core/lib/layer.js
Fixes #1179 
* Add back `selectedPickingColor` uniform to support old custom picking.
* Docs :
* Mark `renderPickingBuffer` and `selectedPickingColor` as deprecated.
* Add picking documentation for custom shaders.
=> Add support for old picking uniforms

src/core/pure-js/deck-js.js
Per recommendation in https://github.com/uber/deck.gl/issues/1176: enable new blend mode without breaking existing apps.
=> Add new blend mode to initWebGLParameters

examples/layer-browser/src/app.js, src/core/index.js, src/index.js, src/react/index.js, src/react/viewport-controller.js
This PR rather "aggressively" moves unfinished APIs (i.e. classes that I consider unaudited) to `experimental`
All classes that were not experimental in 4.1 should still be available here, but most new controller/viewport classes are in the `experimental` namespace.
This PR will be presented/discussed in today's audit meeting before landing.
=> Move unaudited APIs to experimental

src/core-layers/path-layer/path-layer-vertex-64.glsl.js
Port fix #1200 to 64bits shader, may resolve #896 .
Tested with layer-browser and enabled 64bits flag.
=> update sharp end/joint fix for 64bits pathlayer shader

examples/layer-browser/package.json, package.json, src/core/lib/layer.js, src/core/lib/pick-layers.js, website/package.json
* Remove `PICKING_NULL_COLOR` and use `null` as default value. When no layers are picked , it will remain 'null' and luma.gl picking module sets a flag to indicate the picking color is invalid.
Verified picking/highlighting with latest luma.gl code on several layers using `layer-browser`.
NOTE: This change requires 'https://github.com/uber/luma.gl/pull/365' , once this PR is approved, I will also bump luma.gl version to an alpha release containing above change.
=> Picking: Use 'null' instead of 'PICKING_NULL_COLOR`.

.buildkite/coverTests, .buildkite/pipeline.yml, .buildkite/xvfb, Dockerfile, README.md, docker-compose.yml
This is a WIP proposal to run Buildkite as a CI service alongside Travis. Buildkite allows for easy-to-configure parallelization as well as running within Docker containers. There's still some github configuration that we need to do before landing, but just opening this to get the conversation going.
=> Use buildkite and docker for CI

README.md
Removing the buildkite badge for the time being until coveralls is working fully.
=> Remove buildkite badge

examples/layer-browser/package.json, examples/plot/package.json, examples/point-cloud-laz/package.json, examples/point-cloud-laz/worker/laslaz.js, examples/point-cloud-ply/package.json, examples/sample-layers/bitmap-layer/bitmap-layer.js, examples/wind/src/layers/elevation-layer/elevation-layer.js, src/core-layers/grid-cell-layer/grid-cell-layer.js, src/core-layers/hexagon-cell-layer/hexagon-cell-layer.js, src/deprecated-layers/extruded-choropleth-layer-64/extruded-choropleth-layer-64.js, src/index.js
* Remove deprecated API usage from core layers (layer.setUnifroms -> model.setUnifroms)
* Fix Oribt and MapController exports.
Verified with examples.
=> Cleanup: Remove deprecated API usage from core layers

src/core/shaderlib/project/viewport-uniforms.js, test/bench/viewport.bench.js, test/src/core/shaderlib/project/viewport-uniforms.spec.js
During profiling of an internal app, `setUniforms` and `fp64ifyMatrix4` stand out among the top most expensive operations. In reality, we do not have to generate the fp64 uniforms when using 32bit projection. 
Changes in this diff:
- Only generate fp64 viewport uniforms if `fp64` flag is on
- Remove duplicate call to `fp64ifyMatrix4(viewProjectionMatrix)`
- Remove unnecessary creation of new typed arrays
- Reduce small arrays generated during `fp64ify`
In terms of implementation, I do not think checking `fp64` is the right approach, as layers could use the `project64` module without the `fp64` flag. I suggest that in luma.gl, when a module specifies `dependencies`, its `getUniforms` callback should be able to access the uniforms generated by its dependencies. `project64` will then be able …
=> Conditionally generate fp64 viewport uniforms

src/core/lib/pick-layers.js, test/bench/index.js, test/bench/pick-layers.bench.js
- Avoid decoding picking color and generating info objects during the traversal
- Skip entire rows
Before:
| Test | Result |
| ---- | ------ |
| Solid | 56.8k iterations/s (0.18s) |
| Circle | 95.2k iterations/s (0.10s) |
| Triangle | 147k iterations/s (0.68s) |
| Solid - Big | 5.00k iterations/s (0.20s) |
After:
| Test | Result |
| ---- | ------ |
| Solid | 826k iterations/s (0.12s) |
| Circle | 1.04M iterations/s (0.96s) |
| Triangle | 820k iterations/s (0.12s) |
| Solid - Big | 64.5k iterations/s (0.15s) |
Tested: node, browser, layer-browser
=> Improve perf of picking with large `pickingRadius`

src/core/lib/layer-manager.js, src/core/lib/pick-layers.js, src/core/utils/log.js, src/core/viewports/viewport.js
Some calls to `log.warn` are not supplying the `priority` argument, which makes the message always invisible.
=> Fix `log.warn` usage

src/core-layers/path-layer/path-layer-vertex.glsl.js
Simple initial set of code changes to `PathLayer`:
* Many instances of `mix` replaced with `if` and `?:`.
* More descriptive variable names in a few places.
* Includes METER_OFFSET PathLayer example
=> Path Layer Code Cleanup Step 1

docs/whats-new.md, src/core-layers/scatterplot-layer/scatterplot-layer.js, src/core-layers/solid-polygon-layer/polygon-tesselator-extruded.js, src/core-layers/solid-polygon-layer/polygon-tesselator.js, src/core-layers/solid-polygon-layer/polygon.js, src/experimental-layers/src/mesh-layer/mesh-layer.js, test/bench/utils.bench.js, test/src/core-layers/geojson-layer.spec.js, test/src/core-layers/polygon-tesselation.spec.js
[The `get` function](https://github.com/uber/deck.gl/blob/master/src/core/utils/get.js#L31) used for immutable/ES6 container support has a large perf hit, both due to the complexity of the operation, and the creation of a small new array of keys every time it is called. In ScatterplotLayer, `get` is called 7-9x per object.
deck.gl never fully supported immutable data - only ScatterplotLayer and PolygonLayer did. I think it's debatable what value this inconsistent feature brings to the table given its cost.
This PR demonstrates how much we gain by removing `get` usage from the ScatterplotLayer:
|      | Test | Result |
| --- | --- | --- |
| Before | ScatterplotLayer#initialize | 97.1 iterations/s (10.3ms) |
| After | ScatterplotLayer#initialize | 141 iterations/s (7.1ms) |
=> Remove container support from core layers

src/core/lib/draw-layers.js
- Object highlighting uniforms should be set during drawing mode.
- Rename `getPickingModuleParameters` -> `getObjectHighlightParameters`
Fixes #1229 
Verified with layer-browser (`picking`, `selectedObjectIndex` and `autoHighlight`)
=> Fix Picking Module object highlighting

src/core/index.js, src/core/pure-js/orbit-controller-js.js, src/react/experimental/orbit-controller.js
Pretty much mirrors `MapControllerJS` and `MapController`. There's room for code reuse in follow up refactors.
Tested: node, browser, examples/plot, examples/point-cloud-laz
=> OrbitController pure-js support

src/core/lib/attribute-manager.js, test/src/core/lib/attribute-manager.spec.js
I ran into this error that somehow the application is invalidating a triggerName that was not in the updateTriggers, which led to invalidatedAttributes = undefined, and we are calling undefined.forEach afterward.
However, from the test spec it seems we were expecting an exception thrown in this case. Is this by design? 
I would expect the application to continue working if a mismatched triggerName is provided.
=> [DISCUSSION] invalid triggerName in attribute-manager.invalidate()

src/core-layers/grid-cell-layer/grid-cell-layer-vertex-64.glsl.js, src/core-layers/hexagon-cell-layer/hexagon-cell-layer-vertex-64.glsl.js, src/core-layers/hexagon-cell-layer/hexagon-cell-layer-vertex.glsl.js, src/core/shaderlib/lighting/lighting.glsl.js
The normals of our layers (hexagon cell and extruded polygon) has y axis as the vertical axis, so our lighting modules apply a transform to correct it. 
`vec3 normals_worldspace_vec3 = normals_worldspace.xzy;`
Now, the extruded polygons has z-axis as vertical (https://github.com/uber/deck.gl/pull/1011), so we need to fix the hexagon cell layer and lighting module to make the lighting correct.
@1chandu @Pessimistress @heshan0131
=> Fix the normal direction of the hexagon layer and lighting module

examples/layer-browser/src/examples/experimental-layers.js, src/experimental-layers/src/index.js, src/experimental-layers/src/solid-polygon-layer/polygon-tesselator-extruded.js, src/experimental-layers/src/solid-polygon-layer/polygon-tesselator.js, src/experimental-layers/src/solid-polygon-layer/polygon.js, src/experimental-layers/src/solid-polygon-layer/solid-polygon-layer-fragment.glsl.js, src/experimental-layers/src/solid-polygon-layer/solid-polygon-layer-vertex-64.glsl.js, src/experimental-layers/src/solid-polygon-layer/solid-polygon-layer-vertex.glsl.js, src/experimental-layers/src/solid-polygon-layer/solid-polygon-layer.js, src/experimental-layers/test/polygon-tesselation.spec.js, test/bench/core-layers.bench.js, test/bench/index.js, test/bench/tesselation.bench.js, test/index.js, test/node.js, webpack.config.js
Per request of https://github.com/uber/deck.gl/pull/1224
- Copy `solid-polygon-layer` to `experimental-layers`
- Add example in layer-browser
- Add benchmark tests
- Include `experimental-layers` test in standard tests
=> Add SolidPolygonLayer to experimental layers

docs/upgrade-guide.md, src/core/shaderlib/project/viewport-uniforms.js, src/core/utils/log.js
- Remove `projectionMode` and `projectionOrigin`, instead setting them to corresponding new props.
- As described in upgrade-guide there is a semantic change (y-direciton flipped) with new props, so remove and generate errors  (instead of warnings) when used.
Tested with `test-browser` and `layer-browser`.
=> Remove old Coordinate system props.

docs/shader-modules/project.md, src/core-layers/solid-polygon-layer/solid-polygon-layer-vertex-64.glsl.js, src/core-layers/solid-polygon-layer/solid-polygon-layer-vertex.glsl.js, src/core-layers/solid-polygon-layer/solid-polygon-layer.js, src/core/shaderlib/project/project.glsl.js, src/core/shaderlib/project/viewport-uniforms.js
Polygon layer needs to project normals (either lng_lat delta or meters delta depending on the coordinate system) into the world space. The existing code assumes that the layer is always in LNG_LAT mode.
=> Fix polygon normals in meter offset mode

CHANGELOG.md, package.json, test/bench/browser.js, yarn.lock
`npm run bench` now calculates rudimentary regression numbers:
=> Upgrade probe.gl

test/node-dist.js
`publish` scripts are failing as they can't find `deck.gl-layers` module. Do not include these tests in `test-dist`.
Verified running `test-dist`.
=> Fix test-dist

dev-docs/RFCs/v5.0/auto-highlighting-rfc.md, src/core/lib/draw-layers.js, src/core/lib/layer.js, src/experimental-layers/src/mesh-layer/mesh-layer.js
- Fix highlighting when `highlightedObjectIndex` is used, set its default value to `null` which disables the feature. When set to a non null value, corresponding instance will be highlighted. Any invalid index value doesn't highlight any object.
- Fix a regression in `mesh-layer`.
Verified with `layer-browser`.
=> Fix pickingSelectedColor, fix mesh-layer regression

dev-docs/RFCs/v5.0/viewport-transition-rfc.md, docs/advanced/picking.md, docs/advanced/primitive-layers.md, docs/advanced/writing-shaders.md, docs/roadmap.md, docs/upgrade-guide.md, docs/whats-new.md, src/core-layers/solid-polygon-layer/solid-polygon-layer-fragment.glsl.js, src/core/lib/draw-layers.js, src/core/shaderlib/check-legacy-uniforms.js, src/experimental-layers/src/solid-polygon-layer/solid-polygon-layer-fragment.glsl.js
- Remove remaining old picking uniforms.
- Update docs to point to luma.gl picking module.
- Add RFC links to experimental features in road-map doc.
=> Remove old uniforms

examples/3d-heatmap/package.json, examples/arc/package.json, examples/experimental/js/with-mapbox-map/package.json, examples/experimental/viewport-transitions/package.json, examples/geojson/package.json, examples/graph/package.json, examples/graph/webpack.config.js, examples/icon/package.json, examples/line/package.json, examples/plot/plot-layer/axes-layer.js, examples/point-cloud-ply/package.json, examples/point-cloud-ply/webpack.config.js, examples/react/hello-world-webpack2/package.json, examples/react/jsx-layers/package.json, examples/scatterplot/package.json, examples/screen-grid/package.json, examples/svg-interoperability/package.json, examples/svg-interoperability/webpack.config.js, examples/tagmap/package.json, examples/test/tree-shaking/package.json, examples/text-layer/package.json, examples/trips/package.json
- Fix `plot` example to work when using `npm run start`, `state.models` is iterated using `for .. of` iterator so it should be an array , not a object. 
- Fix build script in few examples.
Verified running `plot` and `point-cloud-laz` example
=> Examples start script

package.json, src/core/shaderlib/check-legacy-uniforms.js, src/core/shaderlib/project/project.glsl.js, src/core/shaderlib/project/viewport-uniforms.js, src/core/viewports/viewport.js
Use new scaling factors from https://github.com/uber-common/viewport-mercator-project/blob/master/docs/get-started/offset-accuracy.md
Test data - 60km x 60km grid centered at SF
- grey - fp64 LNGLAT mode
- red - METER_OFFSETS mode
- blue - LNGLAT_OFFSETS mode
zoom=13, before: 
After:
=> More precise offset projection

src/core-layers/arc-layer/arc-layer.js, src/core-layers/grid-cell-layer/grid-cell-layer.js, src/core-layers/hexagon-cell-layer/hexagon-cell-layer.js, src/core-layers/icon-layer/icon-layer.js, src/core-layers/line-layer/line-layer.js, src/core-layers/path-layer/path-layer.js, src/core-layers/point-cloud-layer/point-cloud-layer.js, src/core-layers/scatterplot-layer/scatterplot-layer.js, src/core-layers/solid-polygon-layer/solid-polygon-layer.js, src/core/lib/layer.js, src/experimental-layers/src/mesh-layer/mesh-layer.js, src/experimental-layers/src/solid-polygon-layer/solid-polygon-layer.js
In core layers, we call `_getModel` in `initializeState`, then immediately again in `updateState` because `props.fp64 !== oldProps.fp64` (oldProps is empty at initialization).
=> Fix double model generation

src/experimental-layers/src/text-layer/text-layer.js
* Observe `getText` updateTrigger
* Use `getSubLayerProps` to ensure correct forwarding of props, plus correct sublayer naming to enable filtering.
=> TextLayer fixes

.eslintrc, docs/roadmap.md, src/react/viewport-controller.js
* Disable react linter warnings for `PropTypes.array` - type checking each element in arrays is too expensive.
* Remove React warning:
=> Remove lint and React warnings

src/test-utils/luma.gl/io-basic/README.md, src/test-utils/luma.gl/io-basic/browser-compress-image.js, src/test-utils/luma.gl/io-basic/browser-read-file.js, src/test-utils/luma.gl/io-basic/browser-request-file.js, src/test-utils/luma.gl/io-basic/browser-request-image.js, src/test-utils/luma.gl/io-basic/index.js, src/test-utils/luma.gl/io-basic/json-loader.js, src/test-utils/luma.gl/io-basic/load-files.js, src/test-utils/luma.gl/io-basic/load-texture.js, src/test-utils/luma.gl/io-basic/node-compress-image.js, src/test-utils/luma.gl/io-basic/node-load-image.js, src/test-utils/luma.gl/io-basic/path-prefix.js, src/test-utils/luma.gl/io-extended/README.md, src/test-utils/luma.gl/io-extended/browser-compress-image.js, src/test-utils/luma.gl/io-extended/browser-write-file.js, src/test-utils/luma.gl/io-extended/index.js, src/test-utils/luma.gl/io-extended/test/index.js, src/test-utils/luma.gl/io-extended/test/write-read-image.spec.js, src/test-utils/luma.gl/test/index.js, src/test-utils/luma.gl/test/read-image.spec.js, src/test-utils/luma.gl/utils/globals.js
The luma.gl I/O package was originally designed to support read / write of files and images using a single API across both browser and Node.js. 
Unfortunately this approach was abandoned, mainly due to issues with bundle size due to the big node dependencies. But with dynamic requires we can get the best of both worlds. 
This PR is the start of an effort to review the luma.gl IO package:
* It copies the luma.gl IO module
* Splits IO into a clearer file structure and modernizes the code
Next steps:
* IO code will be iterated on here as part of making the rendering tests / golden image support work under both browser and node
* And finally moved back to luma.gl.
=> file read/write methods for Browser and Node

src/experimental-layers/CHANGELOG.md, src/experimental-layers/package.json
This is similar to how React components always have React as peer dependency.
=> deck.gl-layers:  deck.gl is now peer dependency

src/core-layers/arc-layer/arc-layer.js, src/core-layers/grid-cell-layer/grid-cell-layer.js, src/core-layers/hexagon-cell-layer/hexagon-cell-layer.js, src/core-layers/icon-layer/icon-layer.js, src/core-layers/line-layer/line-layer.js, src/core-layers/path-layer/path-layer.js, src/core-layers/point-cloud-layer/point-cloud-layer.js, src/core-layers/scatterplot-layer/scatterplot-layer.js, src/core-layers/solid-polygon-layer/polygon-tesselator-extruded.js, src/core-layers/solid-polygon-layer/polygon-tesselator.js, src/core/index.js, src/core/utils/fp64.js, src/experimental-layers/src/mesh-layer/mesh-layer.js, src/experimental-layers/src/solid-polygon-layer/polygon-tesselator.js, src/index.js, test/bench/utils.bench.js
Avoid creating intermediate arrays.
Node:
├─ fp64#fp64ify(x)[1]: 21.3M iterations/s (0.03s elapsed)
├─ fp64#fp64LowPart(x): 39.5M iterations/s (0.03s elapsed)
Browser:
├─ fp64#fp64ify(x)[1]: 30.6M iterations/s (0.04s elapsed)
├─ fp64#fp64LowPart(x): 43.9M iterations/s (0.03s elapsed)
Verified: layer-browser
=> Improve fp64ify perf

.buildkite/pipeline.yml
We are currently migrating all buildkite jobs to new queues which should be more performant. There should be no change in functionality.
=> Update buildkite queue information

docs/get-started/using-layers.md
Changed 'data' to 'id', otherwise the object would have the 'data' attribute twice and no id at all.
=> [Doc] Fix of layer attribute typo

src/core/lib/layer.js
This PR just reorders methods.
* The `dataUrl` diff makes some clever changes to the `Layer` class and I'd like to get this cleanup in place first to keep next PR clean.
* This split will also helps when reviewing future additions to the Layer API.
=> Reorder layer methods into public/private API. 

examples/layer-browser/src/components/layer-controls.js, src/core/lib/layer.js, src/core/lib/props.js, src/core/lifecycle/create-props.js, test/bench/core-layers.bench.js, test/rendering-test/test-rendering.js, test/src/core/lib/props.spec.js
I made this change on the 6.0-dev branch. I'm a little worried that this could cause some side effects, but hard to ignore the perf boost, so I am proposing it for 5.1:
LAYER CONSTRUCTION BENCH | MASTER | THIS PR |
| --- | --- | --- |
| ScatterplotLayer#construct: | 78k iterations/s | 532k iterations/s |
| GeoJsonLayer#construct | 55k iterations/s | 521k iterations/s | 
| PolygonLayer#construct | 51k iterations/s | 460k iterations/s |
| SolidPolygonLayer#construct | 55k iterations/s | 471k iterations/s |
=> Use Object.prototype to speed up default prop setting

docs/whats-new.md, src/react/deckgl.js
not sure if it was done by design (due to picking issues?) but I need to use relative position and have deck.gl canvas resize with his parent node.
=> allow override position, left, top of deck.gl canvas

docs/api-reference/layer.md, docs/whats-new.md, src/core/lib/layer.js, src/core/lifecycle/create-props.js, test/bench/core-layers.bench.js, test/src/core/lib/layer.spec.js, test/src/core/lib/props.spec.js
This PR might be pushing micro performance optimization a little far so opening this for comment:
The problem: Complex apps often build large prop objects by "merging" smaller objects. Currently we have to merge these objects in the app, and then the layer merges again with the default props. With lots of layers and props in play, such copying can have a noticeable perf impact (see measurements in #1336 ). 
The idea in this PR: By allowing Layers to take multiple prop objects, we can let the layer do a single merge and save one round of copying and temp object creation, i.e:
```
new Layer({...commonProps, ...settingProps, ...layerProps});
```
```
new Layer(commonProps, this.getSublayerProps(...), {data: ...});
```
Obviously documentation needs to be updated, this PR is not final.
=> Property Copy Reduction

examples/wind/src/layers/particle-layer/particle-layer-vertex.glsl.js, examples/wind/src/layers/particle-layer/particle-layer.js
- REQUIRES luma.gl 5.1.0.
- Update wind demo to use newer luma.gl TransformFeedback API.
- Use instanced rendering for particle layer.
Verified running wind demo using latest luma.gl build.
=> Wind demo: update using newest luma.gl TF API

src/core/lib/pick-layers.js
Closes #1344
`pickVisibleObjects` should bounding box (x, y, width and height in pixels) in result , as described in docs.
Verified with layer-browser.
=> Fix crash during pickVisibleObjects

src/core/views/view.js
`layerManager.viewsChanged` is always `true`.
=> Fix View.equals

src/core-layers/hexagon-layer/hexagon-layer.js
To reproduce the bug: run layer browser, and set `luma.log.priority=2` in the console.
=> Fix bug where HexagonLayer always rerenders

docs/whats-new.md
To see how this will look, click the **view** button on `whats-new.md` below, and check the images for the last three releases
I am using tables because I can't seem to be able to control styling on github HTML, if someone is better at this. I welcome a follow up diff to improve formatting.
=> Add more screenshots in Whats New

examples/bezier/deckgl-overlay.js, src/experimental-layers/src/bezier-curve-layer/bezier-curve-layer-vertex.glsl.js, src/experimental-layers/src/bezier-curve-layer/bezier-curve-layer.js
There were two different problems :
1. Triangle ordering was incorrect for the first instance.
2. Depending on number of segments, some of the vertices have wrong z, values.
I have included the fix for both, but lets discuss and finalize the changes.
**Before:**
**After.**
=> Fix Bezier-Curve layer rendering issues

test/rendering-test/node-rendering.js
If there is an exception happens, the rendering test won't kill webpack server process which is hanging on background.
=> Catch exception in rendering test

examples/experimental/multi-viewport/app.js, src/core/lib/deck.js, src/core/viewports/first-person-viewport.js, src/core/viewports/orbit-viewport.js, src/core/viewports/orthographic-viewport.js, src/core/viewports/perspective-viewport.js, src/core/viewports/third-person-viewport.js, src/core/views/first-person-view.js, src/core/views/map-view.js, src/core/views/orbit-view.js, src/core/views/orthographic-view.js, src/core/views/perspective-view.js, src/core/views/third-person-view.js, src/core/views/view.js
Another PR towards completing #1370.
Once this is in place we can potentially deprecate/remove most of the `Viewport` classes.
=> View constructors no longer rely on custom Viewport classes (PR 1)

src/core/lib/draw-layers.js, src/core/shaderlib/project/viewport-uniforms.js
Set devicePixel related viewport uniform based on `useDevicePixels` flag.
Verified toggling `useDevicePixels` in layerBrowser and windDemo.
=> Fix devicePixelRatio uniform

docs/advanced/64-bits.md, docs/layers/grid-cell-layer.md, docs/layers/grid-layer.md, docs/layers/hexagon-cell-layer.md, docs/layers/hexagon-layer.md, website/src/components/markdown-page.js
Md docs in website has wrong image links, need make the image showing correctly for both website and github repo
- Change image link in 64-bits.md to the right one
- Change "demo" in image path to "website" which is our current folder name
=> Fix wrong image links in website

README.md, package.json, yarn.lock
- When using Fusion to build deck.gl example, it installs 5.1.0 as a dependency which is missing a patch that fixes an import issue. The import issue will break Fusion build.
- Update README.md to reflect latest release
- Update package.json to reflect latest luma.gl release
=> Update README.md and package.json to reflect latest luma.gl

src/core/lib/layer-manager.js
`viewportChanged` flag was always set to true due to an old issue on `Viewport.equals`. This is no longer the case.
=> Fix viewportChanged flag

examples/point-cloud-laz/app.js
During the data loading time, point cloud layer should not be rendered
- Skip rendering until data is fully loaded
=> Improve point-cloud-laz example by skipping rendering until data loaded

website/contents/pages.js, website/src/components/table-of-contents.js, website/src/stylesheets/_gallery.scss
For https://github.com/uber/deck.gl/issues/1470
- Support sub headers in table of contents
- Support badges
- Render wider side bar in large window
=> [Website] Render nested categories in side bar

examples/layer-browser/src/app.js
In the layer browser app, changing any layer prop will cause some other prop controls to disappear.
This bug started after https://github.com/uber/deck.gl/pull/1336 when we switched to using chained object prototypes for merging props. Upon updating layer settings, the layer browser uses spread operator to update the props object, and loses its `__proto__` in the process.
- Manually flatten layer props to a plain object
=> Fix layer browser disappearing controls

test/src/core-layers/core-layers.spec.js
Test-browser failed after we fix the uniform bug(https://github.com/uber/luma.gl/pull/425)
- Change the minColor uniform to match the size in glsl shader.
=> Add alpha for minColor to fix test

package.json, src/test-utils/package.json, src/test-utils/src/drivers/render-test-driver.js, src/test-utils/src/index.js, src/test-utils/src/lifecycle-test-deprecated.js, src/test-utils/src/lifecycle-test.js, test/node-dist.js, test/src/core-layers/core-layers.spec.js, test/src/core-layers/geojson-layer.spec.js, test/src/core-layers/grid-cell-layer.spec.js, test/src/core-layers/grid-layer.spec.js, test/src/core-layers/hexagon-cell-layer.spec.js, test/src/core-layers/hexagon-layer.spec.js, test/src/core-layers/index.js, test/src/core-layers/polygon-layer.spec.js, test/src/core/lib/layer.spec.js, yarn.lock
For #1423
- replace various lifecycle test utils with `testLayer`.
- update tests
- remove unused test utils
=> Modernize tests, remove deprecated test utils

package.json, test/render/test-cases.js
Chrome 65 can't rendering out path-marker layer correctly, disable it for now.
- Disable path-marker rendering test
- use test-render-react cause the test-render has bug which allowed failed rendering test pass the full test set.
=> disable path-marker rendering test

docs/shader-modules/lighting.md, docs/shader-modules/project.md, docs/shader-modules/project64.md, src/core/shaderlib/lighting/lighting.js
- Update shader module docs
- Add deprecation warning for the old `getLightWeight` function
=> Update shader module docs

package.json, src/test-utils/package.json, src/test-utils/src/drivers/render-test-driver.js, src/test-utils/src/render-test.js, test/render/test-cases.js, test/start.js, yarn.lock
For #1423
- Removes "circular" install of deck.gl, instead using alias to run from source, per discussion.
- Fixes passing of correct return status from Browser to Node.
- Also returns name of failing test.
=> Fix test harness exit code on failure

docs/shader-modules/project32.md, docs/shader-modules/project64.md, docs/whats-new.md, src/core/shaderlib/project32/project32.js, src/core/shaderlib/project64/project64.glsl.js, website/contents/pages.js
For https://github.com/uber/deck.gl/issues/1492
- Add shader module `project32`
- Implement `project_position_to_clipspace` interface in `project32` and `project64`
=> Implement unified 32 and 64 bit project interface (PR 1/2)

src/core/index.js, src/core/lib/deck.js, src/core/pure-js/map-controller-js.js, src/core/pure-js/orbit-controller-js.js, src/react/src/deckgl.js, src/react/src/experimental/orbit-controller.js, src/react/src/map-controller.js
But keep the prop definitions with the code that implements them.
Towards #1429
=> JSAPI: Avoid importing PropTypes in the JavaScript API

src/core/utils/scale-utils.js, test/src/core/utils/index.js, test/src/core/utils/scale-utils.spec.js
For #1536
This bug is easier to reproduce with screen-grid layers, as when you zoom-in, you might endup with just one grid, where domain will have same min and max values. Also reproducible with Grid and Hex layers, if user provides domain with same min max value.
- Fix quantizeScale
- Add unit test
=> Fix quantize scale

src/core/lib/layer.js
For https://github.com/uber/deck.gl/issues/1548
- reset `layer.oldProps` once update is complete
Tests: node, browser, layer-browser
=> Fix memory leak via oldProps

src/experimental-layers/src/text-layer/text-layer.js
Possible fix For #1551
TextLayer doesn't setup attributes, so attributeManager's `invalidateAll` has no effect, add manual checks. Also check for `getText` and `getPosition` which are also used in `transformStringToLetters` method.
- TextLayer: fix updateTriggers
=> TextLayer: fix updateTriggers

src/experimental-layers/src/text-layer/font-atlas.js
For #1550 
Padding not applied for horizontal axis, fixed.
- TextLayer: Fix horizontal padding
before:
after:
=> TextLayer: Fix horizontal padding

src/core/lib/composite-layer.js, src/core/lib/layer-manager.js, src/core/lib/layer.js
For https://github.com/uber/deck.gl/issues/1548
Addressing additional comments in https://github.com/uber/deck.gl/pull/1549
- Remove `layer.oldProps`
- Remove `layerManager.prevLayers`
Tests: node, browser, layer-browser
=> Remove `oldProps` and `prevLayers` references

docs/api-reference/viewport.md, src/core/viewports/viewport.js
The `Viewport` constructor accepts an `focalDistance` option but does not handle it properly.
This PR only affects viewports without `zoom`, i.e. `FirstPersonViewport` and `ThirdPersonViewport`. Both are experimental exports.
- Adjust default geospatial zoom with `focalDistance`
- Add documentation
=> Focal distance

src/experimental-layers/src/text-layer/text-layer.js, test/bench/core-layers.bench.js
TextLayer (100k) example in layer-browser:
| method | time (old) | time (new) |
| -- | -- | -- |
| `transformStringToLetters` | 32585ms | 78ms |
- Remove spread operator construction of arrays
- Avoid merging objects
=> Improve text layer perf

test/scripts/collect-metrics.sh
- `npm run test` does not clean up formatting after itself
- Unbold console output
=> Unbold console output after test

src/experimental-layers/src/text-layer/text-layer.js
Current issues with TextLayer:
- TextLayer is not passing update triggers to MultiIconLayer
- If `sizeScale` is not specified, luma.gl throws warning of missing uniform
- Add default value for `sizeScale`
- Correct updateTriggers
=> Fix TextLayer props handling

examples/layer-browser/src/app.js, examples/layer-browser/src/data-samples.js, examples/layer-browser/src/examples/experimental-layers.js, src/experimental-layers/src/gpu-screen-grid-layer/gpu-screen-grid-layer-fragment.glsl.js, src/experimental-layers/src/gpu-screen-grid-layer/gpu-screen-grid-layer-vertex.glsl.js, src/experimental-layers/src/gpu-screen-grid-layer/gpu-screen-grid-layer.js, src/experimental-layers/src/utils/gpu-grid-aggregator.js, test/bench/gpu-grid-aggregator.bench.js, test/bench/index.js, test/data/grid-aggregation-data.js, test/data/index.js, test/src/experimental-layers/gpu-grid-aggregator.spec.js, test/src/experimental-layers/index.js
For #1414
- Add support for GPU Aggregation
- Add Bench tests.
- Add Unit tests.
- Add GPUScreenGrid Perf layers in layer-browser
Bench Results: (GPU path performs CPU and GPU sync after every iteration)
GRID AGGREGATION
├─ CPU 1K: 991 iterations/s
├─ GPU 1K: 389 iterations/s
├─ CPU 100K: 8.26 iterations/s
├─ GPU 100K: 32.3 iterations/s
├─ CPU 1M: 1.03 iterations/s
├─ GPU 1M: 4.76 iterations/s
GPUScreenGridLayer with 1M points, zoom in/out performance on CPU vs GPU
CPU:
GPU:
- ScreenGrid GPU Aggregation (Part-3, Add GPU Aggregation)
- Add Unit and Bench tests
=>  ScreenGrid GPU Aggregation (Part-3, Add GPU Aggregation)

src/core/lib/attribute.js, test/src/core-layers/core-layers.spec.js
- Fixing breakages on master.
- Plot layer accesses `value` in attribute directly, which wasn't supported by the attribute refactor.
- TextLayer needs a canvas which doesn't work under Node.js tests.
=> Hotfix to plot layer and node tests

examples/layer-browser/src/examples/experimental-layers.js, src/experimental-layers/src/mesh-layer/mesh-layer-vertex.glsl.js, src/experimental-layers/src/mesh-layer/mesh-layer.js, src/experimental-layers/src/mesh-layer/mesh-layer.md
For https://github.com/uber/deck.gl/issues/1564
- Remove prop `getAngleDegreesCW`
- Add props `getYaw` `getPitch` `getRoll`
`PathMarkerLayer` uses `MeshLayer` but does not specify an accessor. Looks like it relies on `object.angle`. Checks in layer-browser and the render test passes.
=> Support 3d rotation in MeshLayer

examples/layer-browser/src/app.js, src/core/controllers/map-controller.js, src/core/controllers/orbit-controller.js, src/core/controllers/viewport-controls.js, src/core/lib/deck.js, src/core/views/orthographic-view.js, src/core/views/view.js
For #1429
- Similar logic to the scripting PR, but now shared inside `Deck` component
- Add handling of existing controllers to `Deck` component
Depends on one or two of the PRs opened today, but isolated to simplify review.
=> Integrate the existing JS controllers into Deck component

src/core/viewports/web-mercator-viewport.js
- The new parameter calculation has a slight scale error
- WebMercatorViewport reverted to make tests work
=> Fix render tests by temporarily reverting the new orthographic map projection support

src/core/lib/deck.js, src/core/lib/layer-manager.js, src/core/lib/layer.js
For #1421 
- Our messy internal context handling interfered with the auto size feature.
- Copy only props that are actually wanted to the context object.
- Remove `oldContext`
- Remove unused props from
=> Clean up LayerManager context handling

examples/3d-heatmap/package.json, examples/arc/package.json, examples/bezier/package.json, examples/brushing/package.json, examples/experimental/js/with-mapbox-map/package.json, examples/experimental/multi-viewport/package.json, examples/experimental/orthographic-zooming/package.json, examples/experimental/viewport-transitions-flyTo/package.json, examples/experimental/viewport-transitions/package.json, examples/geojson/package.json, examples/graph/package.json, examples/icon/package.json, examples/line/package.json, examples/plot/package.json, examples/point-cloud-laz/package.json, examples/point-cloud-ply/package.json, examples/scatterplot/package.json, examples/screen-grid/package.json, examples/svg-interoperability/package.json, examples/test-utils/package.json, examples/test/tree-shaking/package.json, examples/text-layer/package.json, examples/trips/package.json, examples/wip/attribute-transition/package.json, examples/without-map/package.json
- Previous commit went a little bit too far, breaking ability to install in examples, which breaks `test-examples` script, and interferes which example cleanup work.
- example package.json updates to 5.2 alpha versions
=> Bump examples to 5.2 alpha versions

docs/layers/arc-layer.md, docs/layers/line-layer.md
=> fix(docs): wdith to width typo

website/package.json, website/webpack.config.js
Fix website build broken by the text layer example
- Add tagmap.js as dependency
- Remove unused build script that copies blog post from branch
- Clean up webpack aliases
=> Fix website dependencies

lerna.json, modules/lite/package.json
For https://github.com/uber/deck.gl/issues/1625
Disable publishing of the standalone submodule
- Add to lerna's `publish.ignore`
- Add `private` field to submodule package.json
=> ignore standalone module for now

.babelrc, modules/core/package.json, modules/core/src/core/lib/draw-layers.js
- Fix two issues found during app integration
- disable `babel-minify`, since it disrupts source-maps
- check if `stats` object is provided before calling it
=> Fixes: disable babel-minify, check if stats object is provided

examples/website/point-cloud-laz/package.json, examples/website/point-cloud-laz/webpack.config.js
Webpack 4's UglifyJS can handle ES6, plus better tree-shaking / minification.
- webpack config/package.json
=> Upgrade point cloud LAZ to webpack 4

docs/api-reference/deck.md, docs/api-reference/react/deckgl.md
- Remove duplicated documentation of `Deck` properties
- docs
=> Make DeckGL doc refer to Deck docs

modules/core/src/core/controllers/map-controls.js, modules/core/src/core/controllers/viewport-controls.js
For related bug found in https://github.com/uber/deck.gl/issues/1743
- `MapControls` does not handle right button pan
- `ViewportControls` pan/rotate accidentally got reversed in https://github.com/uber/deck.gl/pull/1330
- Add right button handling to MapControls
- Reverse pan/rotate in ViewportControls. This affects the behavior of OrbitController.
=> Handle right button pan in MapControls

.babelrc, modules/core/package.json, modules/lite/package.json, modules/lite/webpack.config.js
For https://github.com/uber/deck.gl/issues/1742
`babel-plugin-version-inline` uses the package version from the working directory.
- Apply appropriate version string at build time
=> Fix standalone bundle inline version

examples/README.md
While taking a look at the examples, I found some bad links to the respective example folders.  This PR fixes those links.
=> Update example links in README.md

modules/core/src/core/controllers/map-controller.js, modules/core/src/core/controllers/orbit-controller.js
- The check to make sure that OrbitControllers are not React components can fail.
- Remove the check, it was only intended to be temporary while we fixed examples.
=> Remove React checks in controller classes

docs/api-reference/deck.md, examples/get-started/react-without-map/app.js, modules/core/src/core/lib/deck.js, modules/react/src/deckgl.js
My last feature PR for 5.2
For #1661
- Most small examples don't need event handling, we can get rid of a callback that clutters the code.
- Fixes to controller classes
- Support for default viewState and initialViewState.
=> Auto Controls: Automatic Event Handling if no callback is specified

docs/advanced/views.md, docs/api-reference/viewport.md, modules/core/src/core/viewports/viewport.js, modules/core/src/core/viewports/web-mercator-viewport.js
Not yet passing render tests
For #1507 
- Add `orthographic` projection flag and `orthographicFocalDistance` option to `Viewport`
- Add `orthographic` projection flag and `orthographicFocalDistance` option to `WebMercatorViewport`
- Update docs
- Landed in 5.2 but reverted due to render test issue.
=> Orthographic support in WebMercatorViewport

modules/core/src/core-layers/solid-polygon-layer/solid-polygon-layer.js
For https://github.com/uber/deck.gl/issues/1784
- SolidPolygonLayer checks if context is WebGL2 when choosing index type
=> fix index type in webgl 2 context

docs/advanced/views.md
Removed a line break which was preventing the table from rendering the last 3 rows on http://uber.github.io/deck.gl/#/documentation/developer-guide/using-views?section=choosing-a-view
=> Docs: Fix table on "Choosing a View" page

modules/core/src/lib/attribute.js
Importing from missing dependency
- import `assert` from utils
=> Fix assert import from missing dependency

modules/core-layers/src/arc-layer/arc-layer.js, modules/core-layers/src/grid-cell-layer/grid-cell-layer.js, modules/core-layers/src/hexagon-cell-layer/hexagon-cell-layer.js, modules/core-layers/src/icon-layer/icon-layer.js, modules/core-layers/src/line-layer/line-layer.js, modules/core-layers/src/point-cloud-layer/point-cloud-layer.js, modules/core-layers/src/scatterplot-layer/scatterplot-layer.js
For #1676 
- Many attribute update function do the same simple copying of accessor values into arrays.
- The AttributeManager already has a default implementation that covers these cases.
- By using the default updaters we can make layer code smaller and reduce overall dist size. 
- This PR removes the simple updaters to measure the bundle size
- Drop the unnecessary updater functions
* A 3.5KB saving on minified bundle.
* However, duplicated code compresses well, so the compressed bundle size savings are only 0.5KB
Before
After
=> Dist Size Reduction: Remove default attribute updaters

modules/core/src/controllers/controller.js
Double negatives.
MapControls have `invertPan: true` which means default `alternate mode` should be pan.
- Invert `invertPan`
=> Fix `invertPan` handling

modules/lite/src/deckgl.js, modules/lite/test/index.js
- remove `onViewportChange` hack, use the new automatic control API instead
- minor fix to test app
=> Use auto control in standalone version

modules/core/src/lib/layer.js, modules/core/src/lifecycle/component-state.js, modules/core/src/lifecycle/create-props.js, test/modules/core/lifecycle/component-state.spec.js
For #1372 
- handle loading of async props in the `ComponentState` base class
- test cases for async out of order resolutions
- async update of layer on load, comes in PR3
=> Async Props #2: Loading and shadowing in new ComponentState base class

test/render/test-cases.js
- temporarily unblock render tests to allow pending PRs to be opened.
- comment out GPUScreenGridLayer render test
=> Unblock render tests

examples/layer-browser/app.css, examples/layer-browser/src/app.js, examples/layer-browser/src/components/layer-controls.js
Add ability to test transition and constant accessors with layer-browser 
- Display controls for accessor props
- Add `T` (transition) and `C` (constant) toggles to accessor controls
- Fix network errors in the console due to trying to execute `props.fetch`
- Clean up LayerControls component
- Minor styling tweaks
=> Update layer browser

modules/core/src/lib/attribute.js, modules/experimental-layers/src/gpu-screen-grid-layer/gpu-screen-grid-layer.js, test/render/test-cases.js
For #1828 
Existing `External Buffer` support for Attributes is only through `Layer` props. This state is non persistent, and when buffer is not supported for an attribute through props, it will switch back to normal attribute where `AttributeManger` creates the Buffer object.
For GPGPU layers, we need to support another way of providing `Buffer` object, which will persist until the layer resets it. Added a new flag `isCustomBuffer` to `Attribute` class.
- Attribute: Add custom buffer support.
- Enable GPUScreenGridLayer rendering tests.
=> Attribute: Add custom Buffer support.

docs/developer-guide/composite-layers.md, docs/layers/geojson-layer.md, examples/layer-browser/src/app.js, examples/layer-browser/src/examples/core-layers.js, examples/website/point-cloud-laz/app.js, examples/website/point-cloud-ply/app.js, modules/layers/src/geojson-layer/geojson-layer.js, test/apps/svg-interoperability/app.js
Implement the missing `getLineDashArray` for `GeoJsonLayer` in order to match the functionality of `PolygonLayer`.
=> Add getLineDashArray to GeoJsonLayer

modules/core/src/controllers/controller.js, modules/core/src/controllers/transition-manager.js, test/apps/viewport-transitions-flyTo/index.html, test/apps/viewport-transitions-flyTo/src/app.js, test/apps/viewport-transitions/index.html
For https://github.com/uber/deck.gl/issues/1874
- Update viewport-transition-flyto test app to use the latest API
- Support `onViewStateChange` prop in TransitionManager
- Support `viewState` prop in TransitionManager
- Fix `onViewportChange` callback arguments in Controller (`this.controllerState.getViewport` no longer exists)
=> Fix viewport transition and auto controls

.eslintrc, examples/experimental/bezier/app.js, examples/website/3d-heatmap/app.js, examples/website/arc/app.js, examples/website/brushing/app.js, examples/website/geojson/app.js, examples/website/icon/app.js, examples/website/line/app.js, examples/website/plot/app.js, examples/website/scatterplot/app.js, examples/website/screen-grid/app.js, examples/website/tagmap/app.js, examples/website/text-layer/app.js, examples/website/trips/app.js, modules/core/src/lib/deck.js, modules/core/src/views/view-manager.js, modules/react/src/deckgl.js, modules/react/src/utils/extract-jsx-layers.js
- Light `ViewManager`, `Deck`, `DeckGL` cleanup
- Move some child position related calculation from `DeckGL` to `ViewManager`
- Clean up some props handling in `Deck`
- Make `DeckGL` class smaller/simpler by reducing child positioning logic and moving JSX layers to util.
=> View Manager cleanup

docs/api-reference/deck.md, docs/whats-new.md, examples/website/line/app.js, examples/website/line/deckgl-overlay.js, examples/website/point-cloud-laz/app.js, examples/website/text-layer/deckgl-overlay.js, modules/core/src/lib/deck.js
- For #1840 
- Add new prop.
- Update examples: replace `onWebGLInitialized` callback with new `parameters` prop
=> Add Deck.parameters prop to enable declarative setting of initial GL params

docs/api-reference/deck.md, docs/whats-new.md, modules/core/src/lib/deck.js
For #1840 
- This closes the open question in #1840 whether to apply params each frame or only on initialization.
- Apply params each frame. It makes the prop more useful and matches better with how other props work
- luma already caches params so perf impact should be smalle.
=> Update params per frame

modules/test-utils/src/scene-renderer.js, test/render/test-cases.js
For #1896
Following render tests are failing when run on Intel GPU, blocking engineers in opening PRs.
Add a mechanism so render test can specify GPU name , on which it should be skipped
Disable following render tests on Intel GPU (some of these are failing randomly)
- path-lnglat
- path-lnglat-64
- arc-lnglat
- arc-lnglat-64
- line-lnglat
- geojson-lnglat
- geojson-extruded-lnglat
- gridcell-lnglat
- grid-lnglat
- hexagoncell-lnglat
- pointcloud-lnglat
- pointcloud-lnglat-64
-  Disable failing render tests for Intel GPU
=> Disable failing rendertests for Intel GPU

docs/layers/arc-layer.md, docs/layers/grid-cell-layer.md, docs/layers/grid-layer.md, docs/layers/hexagon-cell-layer.md, docs/layers/hexagon-layer.md, docs/layers/icon-layer.md, docs/layers/line-layer.md, docs/layers/point-cloud-layer.md, docs/layers/scatterplot-layer.md, docs/layers/text-layer.md, modules/layers/src/grid-cell-layer/grid-cell-layer-vertex.glsl.js, modules/layers/src/grid-cell-layer/grid-cell-layer.js, modules/layers/src/grid-layer/grid-layer.js, modules/layers/src/hexagon-cell-layer/hexagon-cell-layer-vertex.glsl.js, modules/layers/src/hexagon-cell-layer/hexagon-cell-layer.js, modules/layers/src/hexagon-layer/hexagon-layer.js, modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer.js, modules/layers/src/text-layer/text-layer.js
For https://github.com/uber/deck.gl/issues/1889
For #1810
- Update layer docs: mark all transition enabled data accessors
- Enable transitions in TextLayer: getPosition, getColor, getSize, getAngle, getPixelOffset
- Enable transitions in GridLayer: getElevationValue, getColorValue
- Enable transitions in HexagonLayer: getElevationValue, getColorValue
=> Add transition prop forwarding for composite layers; docs

examples/layer-browser/src/app.js, examples/layer-browser/src/data-samples.js, examples/layer-browser/src/examples/core-layers.js, modules/layers/src/geojson-layer/geojson-layer.js, modules/layers/src/geojson-layer/geojson.js, test/modules/core-layers/geojson.spec.js
When using Multi* geometries (e.g. `MultiPoint`, `MultiLineString`, `MultiPolygon`), the `index` of the picking info had the incorrect index (i.e. it would increment for each sub-geometry). This fixes that issue.
- `GeoJsonLayer`
=> Fix picking index for GeoJsonLayer

modules/layers/package.json, modules/lite/package.json, modules/main/package.json, modules/react/package.json
For #
When 6.0.0-alpha.1 published, I bumped luma version to 6.0.0-alpha.1 in core module, but other modules still referring to older luma version, manually change versions.
- Update luma.gl dependencies in modules
=> Update luma.gl dependencies in modules

modules/layers/src/geojson-layer/geojson-layer.js, modules/layers/src/geojson-layer/geojson.js, test/modules/core-layers/geojson.spec.js
The feature passed into accessors isn't the same feature the user passed into the props, and may be missing some properties. Yes, it will include the `properties` property. But, it doesn't include the `id` property (which is valid in GeoJSON), or any other custom properties the user may have (much less likely).
This fixes that issue by using the "wrapped" feature produced by `separateGeojsonFeatures` and "unwrapping" it before calling accessor callbacks.
- `GeoJsonLayer`
=> Real feature for accessors

dev-docs/RFCs/v6.0/gpu-screengrid-aggregation-rfc.md, modules/experimental-layers/src/gpu-screen-grid-layer/gpu-screen-grid-layer-vertex.glsl.js, modules/experimental-layers/src/gpu-screen-grid-layer/gpu-screen-grid-layer.js, modules/experimental-layers/src/utils/gpu-grid-aggregator.js, test/bench/gpu-grid-aggregator.bench.js, test/data/grid-aggregation-data.js, test/modules/experimental-layers/gpu-grid-aggregator.spec.js, test/render/test-cases.js
For #1556 
- Add support for 64 bit float operations (optional). This is needed for accuracy when doing world-space aggregation, as cellSize and positions are in lng/lat space and require high float precision.
- Add support for world-space aggregation, in addition to existing screen-space aggregation.
- Add unit tests and bench tests.
- API change: added three parameters to run() method.
1. projectPoints : Input points are projected to screen space, only when `projectPoints` is true, for world space aggregation, set this value to false.
2. gridTransformMatrix : This transformation is applied before aggregation when doing world space aggregation. (not applicable when doing screen-space aggregation, i.e. when projectPoints is true)
3. fp64, when true uses shaders with 64bit float support. …
=> [PART-1] GPUGridAggregation : Add world-space aggregation support to GPUAggregator

examples/layer-browser/src/app.js, modules/core/src/controllers/controller.js, modules/core/src/controllers/first-person-controller.js, modules/core/src/controllers/transition-manager.js, modules/core/src/lib/deck.js, modules/core/src/views/view-manager.js, modules/core/src/views/view.js, modules/lite/src/deckgl.js, test/apps/multi-viewport/app.js, test/apps/multi-viewport/index.html, test/modules/lite/deckgl.spec.js
For
https://github.com/uber/deck.gl/issues/1422
https://github.com/uber/deck.gl/issues/1668
- Move controllers from Deck into ViewManager class
- Add `controller` option to View class
- Support per-view viewState: the `viewState` prop may be a view id to view state map. Fallback to the old viewState format if a view id is not found.
- Support per-view controller. The `controller` prop applies to the first view if specified.
- Clean up the multi-viewport test app, add controllers to each view
- Update controllers to handle events outside of viewport bounds
Tested applications:
Layer-browser, viewport-transitions-flyto, multi-viewport, pure-js, standalone
=> Per-view controller

modules/core/src/shaderlib/project/viewport-uniforms.js, modules/core/src/viewports/viewport.js, modules/core/src/viewports/web-mercator-viewport.js
Make it easier to create viewport of a different projection.
- Reduce hard-coded `lngLatToWorld` and `worldToLngLat` usage
=> Reduce projection-specific code

test/modules/experimental-layers/gpu-grid-aggregator.spec.js
For #1940 
64-bit GPU Aggregation fails on Intel GPUs, will track actual issue here #1945 
- Disable 64 bit gpu aggregation test
=> Disable 64 bit gpu aggregation test

modules/experimental-layers/src/gpu-screen-grid-layer/gpu-screen-grid-layer-fragment.glsl.js, modules/experimental-layers/src/gpu-screen-grid-layer/gpu-screen-grid-layer-vertex.glsl.js, modules/experimental-layers/src/gpu-screen-grid-layer/gpu-screen-grid-layer.js
For #1931
- Add shader instructions to do quantize-scale for color.
- Feature wise, this makes `GPUScreenGridLayer` on par with `ScreenGridLayer`, and ready to be replaced.
- GPUScreenGridLayer: Add colorRange and colorDomain support.
=>  GPUScreenGridLayer: Add colorRange and colorDomain support.

examples/layer-browser/src/examples/experimental-layers.js, modules/experimental-layers/src/gpu-grid-layer/gpu-grid-cell-layer-fragment.glsl.js, modules/experimental-layers/src/gpu-grid-layer/gpu-grid-cell-layer-vertex.glsl.js, modules/experimental-layers/src/gpu-grid-layer/gpu-grid-cell-layer.js, modules/experimental-layers/src/gpu-grid-layer/gpu-grid-layer.js, modules/experimental-layers/src/gpu-grid-layer/gpu-grid-utils.js, modules/experimental-layers/src/index.js, test/modules/experimental-layers/gpu-grid-utils.spec.js
For #1556 
- Copy existing GridLayer and GridCellLayers to experimental.
- Update layers to use GPUGridAggregator for world space aggregation.
- Add additional utility methods required to enable GridCellLayer to consume aggregated data.
- Add  unit tests.
- Add examples to layer-browser.
- 2 to 3X boost in FPS when using GPU Aggregation.
- Picking and Color/Elevation customizations done on CPU and are not supported in this new experimental layer, those feature need to added by moving more calculation to GPU or by using TF.
- Add new experimental GPUGridLyaer, uses GPU Aggregation
=> [PART-2] GPUGridAggregation : Add experimental GPUGridLayer.

docs/api-reference/attribute-manager.md, modules/core/package.json, modules/core/src/lib/attribute-manager.js, modules/core/src/lib/attribute-transition-manager.js, modules/core/src/lib/attribute-transition-utils.js, modules/core/src/lib/attribute.js, modules/core/src/lib/layer.js, modules/experimental-layers/src/mesh-layer/mesh-layer.js, modules/layers/src/grid-cell-layer/grid-cell-layer.js, modules/layers/src/hexagon-cell-layer/hexagon-cell-layer.js, modules/layers/src/icon-layer/icon-layer.js, modules/layers/src/line-layer/line-layer.js, modules/layers/src/point-cloud-layer/point-cloud-layer.js, modules/layers/src/scatterplot-layer/scatterplot-layer.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer.js, test/modules/core-layers/grid-layer.spec.js, test/modules/core/lib/attribute-transition-manager.spec.js, yarn.lock
Attribute transition is broken after upgrading to luma v6.
- `attributeTransitionManager.getAttributes()` now returns Attribute objects instead of Buffer
- Update `Transform` usage to v6 API
=> Fix attribute transition

modules/experimental-layers/src/gpu-screen-grid-layer/gpu-screen-grid-layer.js, modules/layers/src/screen-grid-layer/screen-grid-layer.js
For #1976 
- Add new prop, `cellMarginPixels`, so users can provide 0 or higher value. Default value `2`, matches with old behavior. (non breaking change)
- Use `0` for margin when the cellSize is less than are equal to margin.
- ScreenGridLayer: Fix cell margin
cellMarginSizePixels = 2 :
cellMarginSizePixels = 0 :
=>  ScreenGridLayer: Fix cell margin

examples/website/3d-heatmap/app.js, modules/react/src/deckgl.js, modules/react/src/utils/evaluate-children.js, modules/react/src/utils/extract-jsx-layers.js
For https://github.com/uber/deck.gl/issues/1969
- All React children will be positioned inside a specific view
- Any child not wrapped inside a <View> will be positioned inside the default (first) view
- Render callback behavior is not changed
- Regular React children are injected with the following props: `{x, y, width, height, viewState, viewport}`
=> Restore prop override for regular React children

docs/api-reference/map-controller.md, docs/api-reference/map-view.md, docs/api-reference/react/deckgl.md, docs/api-reference/view.md, modules/core/src/lib/deck.js, modules/core/src/views/first-person-view.js, modules/core/src/views/map-view.js, modules/core/src/views/orbit-view.js, modules/core/src/views/view-manager.js, modules/core/src/views/view.js, modules/lite/src/deckgl.js
For https://github.com/uber/deck.gl/issues/1422
- Allow View classes to specify default controller
- Accept the following values to be supplied to the `controller` prop:
+ `true` (enable)
+ `{dragRotate: false}` (enable with options)
+ `{type: MyMapController, dragRotate: false}` (custom controller with options)
- Update docs
=> More Flexible Controller API

docs/api-reference/layer.md, modules/core/src/lib/attribute-transition-manager.js, modules/core/src/lib/attribute.js, modules/layers/src/path-layer/path-layer.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
For https://github.com/uber/deck.gl/issues/1905
Most layer attributes have the default enter as "appearance" (no transition)
PathLayer and SolidPolygonLayer need them to use the last value of the chunk.
- Add `enter` callback to transition settings
- Allow each attribute to define its own default transition settings
- Update PathLayer and SolidPolygonLayer
=> Add enter parameter for transitions

modules/core/src/experimental/utils/gpu-grid-aggregator.js, modules/layers/src/screen-grid-layer/screen-grid-layer-fragment-webgl1.glsl.js, modules/layers/src/screen-grid-layer/screen-grid-layer-vertex-webgl1.glsl.js, modules/layers/src/screen-grid-layer/screen-grid-layer.js, test/data/grid-aggregation-data.js, test/modules/core-layers/core-layers.spec.js, test/render/test-cases.js
For #1987 
- Enable 64-bit operations when aggregating to a single cell, for `maxCount` and `maxWeight` by default. Should not impact performance as these are performed per cell and not per data item.
- UBO not supported in WebGL1, add fallback path and set uniform directly when using WebGL1.
- Enable tests cases that were previously disabled.
- ScreenGridLayer: 64-bit support for maxCount and WebGL1 fallback for UBO
=> ScreenGridLayer: 64-bit support for maxCount and WebGL1 fallback for UBO

modules/core/src/lib/composite-layer.js, modules/core/src/lib/layer.js
For https://github.com/uber/deck.gl/issues/1993
- add `stateChanged` to change flags
- composite layer marks as needs update when `setState` is called
- default layer behavior is not affected
=> rerender sublayers when state change

examples/website/brushing/arc-brushing-layer/arc-brushing-layer-vertex.glsl.js, examples/website/brushing/arc-brushing-layer/arc-brushing-layer.js, examples/website/brushing/scatterplot-brushing-layer/scatterplot-brushing-layer-vertex.glsl.js, examples/website/brushing/scatterplot-brushing-layer/scatterplot-brushing-layer.js
For #1873
FIX: Sublayers `draw` method.
FIX: Arc-brush-layer's `instanceWidths` attribute.
FIX: Usage and setting of `enableBrushing` uniform.
-  Brushing: Fix draw method, arc instanceWidth attribute and enableBrushing uniform.
=> Fix: Brushing example

modules/core/src/lib/attribute-transition-manager.js
Rendering TransformFeedback into an empty buffer causes WebGL to crash.
- Make sure target buffer size is never zero
=> Fix attribute transition manager crash when numInstances === 0

modules/core/src/controllers/controller.js, modules/core/src/controllers/transition-manager.js, modules/core/src/views/view-manager.js
- Fix: first `controller.processViewportChange` throws error for missing width/height
- Delete controller when view is removed
- Move default view state to each view
- Properly finalize controller and transition manager
=> Delete controller when view is removed

modules/react/src/deckgl.js, modules/react/src/utils/extract-jsx-layers.js, test/modules/react/utils/extract-jsx-layers.spec.js
DeckGL React syntax allows for auto showing/hiding UI of a view by wrapping children in a `<View id="...">` tag. The JSX multi-view syntax allows for adding a view by wrapping children in a e.g. `<MapView ...>` tag. The bug is that we currently extract all React children that is/inherits the `View` type to the views list, while the base View class should not be instantiated.
- Fix deprecation warning
- Do not extract view from JSX if type is base View class
=> React: JSX view bug fixes

modules/core/src/lib/deck.js, modules/core/src/utils/css-vendor-prefix.js, test/modules/core/utils/css-vendor-prefix.spec.js, test/modules/core/utils/index.js
In React, `props.getCursor` is not called when app state updates
- Update cursor in `renderFrame`
- fix cursor CSS for non-Chrome browsers
=> Fix getCursor bugs

modules/core/src/controllers/controller.js, modules/core/src/controllers/map-controller.js
For #2001 
**NOTE**: I will port the changes to 6.0 and master.
Make doubleTap and keyboard transitions exlusive to MapController
- Make doubleTap and keyboard transitions exlusive to MapController
=> Make doubleTap and keyboard transitions exlusive to MapController

modules/core/src/lib/attribute-manager.js
Composite layers do not have any self attributes and therefore always trigger this warning if `updateTriggers` are supplied.
- Disable non-existent updateTrigger warning for now
=> Disable non-existent updateTrigger warning

modules/core/src/lib/deck.js
`pointerLeave` event is not invoking `onHover`/`onLayerHover` callbacks
https://github.com/uber/deck.gl/issues/2027 may be related
- Fix pointer leave event handling
=> fix pointer leave callback

modules/core/src/lib/attribute-manager.js, modules/core/src/lib/composite-layer.js, modules/core/src/lib/layer.js, modules/layers/src/grid-cell-layer/grid-cell-layer.js, modules/layers/src/hexagon-cell-layer/hexagon-cell-layer.js, modules/layers/src/icon-layer/icon-layer.js, modules/layers/src/line-layer/line-layer.js, modules/layers/src/point-cloud-layer/point-cloud-layer.js, modules/layers/src/scatterplot-layer/scatterplot-layer.js
Fix https://github.com/uber/deck.gl/pull/2036 properly:
Do not create attribute manager for composite layers. This avoids generating warnings that only apply to primitive layers, and improves performance by skipping attribute update checks and picking color generation.
- Do not create attribute manager for composite layers
=> No attribute manager for composite layers

modules/core/src/lib/draw-layers.js
Although composite layers do not render anything, `setUniforms` and `setParameters` are still called when they are "drawn".
This is technically a bug since it's stated otherwise in the [docs](https://github.com/uber/deck.gl/blob/master/docs/api-reference/composite-layer.md#draw):
> A composite layer does not render directly into the WebGL context. The draw method inherited from the base class is therefore never called.
- Do not call `drawLayer` on composite layers
=> Perf: skip draw call for composite layers

docs/api-reference/deck.md, modules/core/src/lib/deck.js, test/apps/viewport-transitions/app.js
For #2041 
**NOTE** : I will cherry-pick this to 6.0
Add `onLoad` call back.
Replace the `onResize` hack in `viewport-tranisionts` example with `onLoad` callback.
-  Deck: Add onLoad callback
=> Deck: Add onLoad callback

modules/core/src/lib/deck.js, modules/core/src/lib/pick-layers.js, modules/core/src/viewports/viewport.js, modules/core/src/views/view-manager.js, test/modules/core/viewports/viewport.spec.js, test/modules/core/views/view-manager.spec.js
`pickLayers` should only render the views that contain the picked position
- Add `viewport.containsPixel` method
- `viewManager.getViewports` accepts an optional pixel/rect as filter
- Tests
=> Multi-view picking perf: filter viewports by pointer position

modules/core/src/lib/deck.js
- Check if `props.onLayerHover` is empty
=> Fix callback error on pointer leave

website/src/components/demos/point-cloud-demo.js, website/src/components/info-panel.js, website/src/components/spinner.js, website/src/static/workers/building-data-decoder.js, website/src/static/workers/screen-grid-data-decoder.js, website/src/static/workers/trips-data-decoder.js, website/src/stylesheets/_gallery.scss
- Add progress bar for point cloud and trips data
- Remove progressive loading for screen grid layer (perf)
Full size:
Mobile:
=> Add progress bar to website demos

modules/core/src/utils/css-vendor-prefix.js
`document.body` may be `null` if deck.gl is loaded in the header
- Remove dependency on `document.body`
=> Fix crash in get vendor prefix

docs/layers/screen-grid-layer.md, docs/upgrade-guide.md, examples/website/screen-grid/app.js, modules/layers/src/screen-grid-layer/screen-grid-layer.js
For #1946
- ScreenGridLayer: deprecate minColor and maxColor props
=> ScreenGridLayer: deprecate minColor and maxColor props

website/src/components/demos/plot-demo.js
For #2070 
A string value used to define resolution causing a crash in WebGL for vertex count. Use correct paramter type.
-
=> 3DSurfaceExplorer Demo: fix crash

modules/layers/src/text-layer/font-atlas.js
For https://github.com/uber/deck.gl/issues/2070
Text alignment differences cross browsers:
- Switch to use `baseline` alignment
- Add generous padding vertically
=> Fix font rendering in FF and Safari

modules/layers/src/point-cloud-layer/point-cloud-layer-vertex.glsl.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
For #2070	
This is a hack to unblock v6 release.
See https://github.com/uber/luma.gl/issues/609 for root cause
- Fix PointCloudLayer
- Fix SolidPolygonLayer
=> Fix layer constant attributes in safari

modules/core/src/experimental/utils/gpu-grid-aggregator.js
For #2121
On Intel GPUs `fp64` shader module uses `LUMA_FP64_CODE_ELIMINATION_WORKAROUND`, which uses a const uniform `ONE` always. For all layers this is provided as part of base `Layer` class. Set this uniform explicitly for GPU Aggregation path. 
- GPUAggregator: Set ONE uniform for fp64 module
=> GPUAggregator: Set ONE uniform for fp64 module

modules/core/src/lib/deck.js
- Make it possible to start deck.gl without a gl context and an animation loop.
- Expose initialization and render functions so that they can be called from external code.
- deck.gl component initialization.
=>  Enable drawing into external gl context, controlled by external software

modules/lite/src/deckgl.js, modules/lite/test/index.js
For https://github.com/uber/deck.gl/issues/2102
This was lost when we deprecated `onViewportChange` callbacks
- make sure user-supplied `onViewStateChange` is called
=> Fix onViewStateChange callback in standalone bundle

modules/core/src/views/view-manager.js, test/apps/viewport-transitions-flyTo/package.json, test/apps/viewport-transitions/package.json
For https://github.com/uber/deck.gl/issues/2102
This bug was introduced by the implementation of per-view controller.
Inside `viewManager.setProps`, all viewports are updated. If a viewport transition is triggered during this update, the controller immediately calls `onViewStateChange` callback which calls `viewManager.setProps` again. The nested updates result in an incomplete `controllers` map.
- Avoid invoking `_rebuildViewportsFromViews` inside itself
=> Fix: transition breaks map interaction

examples/gallery/src/boiler-plate.html, examples/gallery/src/hexagon-layer.html, examples/gallery/src/point-cloud-layer.html, modules/lite/src/deckgl.js, modules/lite/test/index.js, test/apps/mapbox-custom-layers/deck-layer.js
- Add missing accessors (due to v6 accessor default value change)
- Fix an issue in standalone bundle where calling `setProps` without `viewState` resets the viewport
=> Scripting example fixes

test/modules/core/experimental/utils/gpu-grid-aggregator.spec.js, test/modules/core/experimental/utils/grid-aggregation-utils.spec.js, test/render/test-cases.js
For #1945 
- Test only changes.
- Enable previously disabled gpu aggregation unit tests. (Several fixes went into aggregation and fp64 module uniforms).
- Disable couple of new render tests for Intel gpus.
Verified on Intel and AMD gpus.
-  Updte unit and render tests
=> Update unit and render tests

modules/layers/src/solid-polygon-layer/polygon-tesselator.js, modules/layers/src/solid-polygon-layer/polygon.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer-fragment.glsl.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer-vertex.glsl.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer.js, test/modules/layers/polygon-tesselation.spec.js
For https://github.com/uber/deck.gl/issues/1775
This is made possible by the new Attribute buffer feature.
SolidPolygonLayer used to generate two buffers for `positions` and `nextPositions` to draw the side quad instances. This PR offsets the `positions` buffer by 1 vertex for `nextPositions`:
positions      A0 A1 A2 A3 A4 B0 B1 B2 C0 ...
nextPositions  A1 A2 A3 A4 B0 B1 B2 C0 C1 ...
vertexEnabled   1  1  1  1  0  1  1  0  1  ...
Old fp64 mode: `positions` and `nextPositions` use `2 * vertexCount * 3 * 4` bytes. `positions64xyLow` and `nextPositions64xyLow` use `2 * vertexCount * 2 * 4` bytes. Total `40 * vertexCount` bytes.
New fp64 mode: `positions` uses `vertexCount * 3 * 4` bytes. `positions64xyLow` uses `vertexCount * 2 * 4` bytes. The new `discardFlags` buffer uses `vertexCount * 1 …
=> Buffer reuse in SolidPolygonLayer

docs/api-reference/layer.md, examples/layer-browser/src/components/color-picker.js, modules/core/src/lib/draw-layers.js, modules/core/src/lib/layer-state.js, modules/core/src/lib/layer.js, modules/core/src/lib/pick-layers.js
General code quality issues encountered as I'm working on custom shader modules.
- Add `layer.setModuleParameters` method
- Remove direct `model.updateModuleSettings` calls from `drawLayer` and `pickLayer`
=> Consolidate module parameter handling

modules/core/package.json, modules/test-utils/package.json
For #
- Webpack made a big change (starting to bundle dynamic requires) in a minor version.
- The updated probe.gl prevents node modules from being pulled into browser builds.
- Bump probe.gl
=> PATCH (v6.0.x): Bump probe.gl version to avoid issues with changed webpack behavior

modules/layers/src/grid-layer/grid-aggregator.js, modules/layers/src/hexagon-layer/hexagon-aggregator.js, test/modules/layers/grid-aggregator.spec.js, test/modules/layers/hexagon-aggregator.spec.js
Usage of iterable data types with deck.gl works most of the time, but the grid and hexagonal aggregators use `.map`, `.reduce` and `for in` which cause errors.
- change hexagon-aggregator to use `for of` instead of `.map`
- change grid-aggregator to use `for of` instead of `.reduce` or `for in`
=> Support iterables in grid and hexagonal aggregators

dev-docs/RFCs/README.md, dev-docs/RFCs/v6.1/json-layers-rfc.md, dev-docs/RFCs/v6.1/view-class-extension-rfc.md, dev-docs/RFCs/v6.x/view-class-extensions-2-rfc.md, docs/README.md, docs/api-reference/view.md, docs/developer-guide/json/README.md, docs/developer-guide/json/using-json-api.md, docs/developer-guide/views.md, docs/whats-new.md, modules/core/src/lib/deck.js, modules/core/src/lib/draw-layers.js, modules/core/src/lib/layer-manager.js, modules/core/src/lib/view-manager.js, modules/core/src/views/view.js, modules/json/README.md, package.json, test/modules/core/views/view-manager.spec.js, website/package.json, website/webpack.config.js, yarn.lock
- Implements [View Class Extensions RFC](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v6.1/view-class-extension-rfc.md)
- Adds a version of trips example with minimap support
- Add some `View` capabilities, `viewStateId`, `filterViewState`, `clear`.
- Clone trips example and add minimap.
- Move `ViewManager` to `lib`, it handles more than Views and feels more natural there.
=> RFC: View Class Extensions

docs/api-reference/layer.md, docs/whats-new.md, examples/website/icon/app.js, modules/core/src/lib/composite-layer.js, modules/core/src/lib/layer.js, modules/core/src/shaderlib/project/project.glsl.js, modules/core/src/shaderlib/project/viewport-uniforms.js
For https://github.com/uber/deck.gl/issues/2051
Before:
After:
- By default, wrap longitude around the viewport center.
- Add a `wrapCoordinates` prop to layers. If set to `false`, fallback to the old projection behavior.
=> Wrap longitudes over the 180th meridian

examples/website/trips/README.md
Added link to TripsLayer example on deck.gl website.
=> fixed broken link to documentation of TripsLayer

modules/core/src/lib/layer-manager.js, modules/layers/src/hexagon-layer/hexagon-layer.js
For #2111 
Re-aggregate and update hexbins when viewport is changed.
- HexagonLayer: Re-aggregate data when viewport is changed.
=> HexagonLayer: Aggregate data using valid viewport.

modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
The hack was put in before 6.0 release due to the WebGL1 constant attribute bug.
This fix depends on the latest VertexArray fix on luma.gl.
- Revert hack.
=> Revert hack in SolidPolygonLayer

docs/get-started/using-with-react.md
The code for the examples for getting started with deck.gl and react have a wrong closing tag on the DeckGl component.
- Docs: get-started/using-with-react
=> Fix wrong closing tag in get-started examples

docs/layers/contour-layer.md, modules/core/package.json, modules/layers/src/contour-layer/contour-layer.js, website/src/components/demos/line-demo.js, yarn.lock
For #2235
In #2243 while fixing WebGL1 flow, I accidentally removed `Buffer.getData()` code needed for WbGL2, adding it back. Tested on Safari (WebGL1) and Chrome (WebGL2).
Also opened #2246 , since this regression should have been caught by `render-tests` script.
Fix website lineDemo issue : slider doesn't change the stroke width.
Bump luma version to 6.1.0-beta.3
-  Fix ContourLayer for WebGL2
-  Bump luma version to 6.1.0-beta.3
=> More contour fixes

modules/core/src/shaderlib/project/project-functions.js, modules/core/src/shaderlib/project/project.glsl.js, modules/core/src/shaderlib/project/viewport-uniforms.js, modules/core/src/viewports/viewport.js, modules/core/src/viewports/web-mercator-viewport.js, modules/experimental-layers/src/mesh-layer/mesh-layer-vertex.glsl.js, test/modules/core/shaderlib/project/project-functions.spec.js
Instance Y is flipped when using offset modes. The switch from LNGLAT to LNGLAT_AUTO_OFFSETS can illustrate this issue:
Related PR:
https://github.com/uber/deck.gl/pull/2167
- Y is reversed in Web Mercator projection (`worldPosition.y` goes down as `lnglat.y` goes up) during projection.
- CPU projection function (`webMercatorViewport.projectFlat`) produces flipped Y. This is used in calculating the projection center.
- Shader function `project_mercator_` produces flipped Y. This is used in the old LNGLAT projection mode.
- Shader function `project_offset_` produces non-flipped Y. This is used in offset modes (`LNGLAT_OFFSETS`, `METER_OFFSETS`, `LNGLAT_AUTO_OFFSET`).
- Shader function `project_scale` produces non-flipped Y. This is used in all modes.
A `Viewport` instance has two …
=> Fix offset projection under offset modes

package.json, test/modules/core/shaderlib/index.js, test/modules/core/shaderlib/project/project-glsl.spec.js, test/modules/core/shaderlib/shaderlib-test-utils.js, yarn.lock
- Add tests for `project` module's vertex shader functions
- More tests for modelMatrix will be added in follow up PRs as I address the CPU/GPU disparity issue
- Use `Transform` instead of transpilation in browser test @1chandu
=> Add tests for project vertex shader functions

docs/api-reference/viewport.md, modules/core/src/viewports/viewport.js, test/modules/core/shaderlib/project/project-functions.spec.js, test/modules/core/shaderlib/project/project-glsl.spec.js, test/modules/core/viewports/web-mercator-viewport.spec.js
The GPU project functions convert LngLatZ to world space (pixels) before projecting to clipspace.
The CPU project function convert LngLat to world space (pixels) but leaves Z in meters before projecting to clipspace.
- New: `viewport.projectPosition` and `viewport.unprojectPosition`
- Fix: `viewport.project` and `viewport.unproject`
- Test: add 3d projection test cases to compare project modules's vertex shader output agains that of `viewport.project`
- Test: set math.gl's equality tolerance by test case
=> Match `viewport.project` behavior with shader projection

.gitignore, examples/layer-browser/data/sample.geo.json, modules/layers/src/geojson-layer/geojson.js, test/modules/layers/geojson.spec.js
Handle geometry with `type='GeometryCollection'`.
`GeometryCollection` is described in [section 3.1.8 of the GeoJSON spec](https://tools.ietf.org/html/rfc7946#section-3.1.8).
TODO
[X] Tests
=> Handle GeoJSON GeometryCollection

modules/core/package.json, modules/core/src/shaderlib/project/viewport-uniforms.js, modules/core/src/viewports/web-mercator-viewport.js, modules/experimental-layers/src/mesh-layer/mesh-layer-vertex.glsl.js, test/modules/core/shaderlib/project/project-functions.spec.js, yarn.lock
- Remove y-flip hack in projection uniforms
- The only layer affected by the new `project_scale` is the MeshLayer. This PR keeps  the experimental layer's output the same as v6.1. When we move it to the core layers, its behavior will change (y-flip). I will add proper render tests and documentation to ensure its correctness.
=> Upgrade viewport-mercator-project

modules/core/src/lib/deck.js, modules/core/src/lib/layer.js, modules/core/src/views/view.js, test/modules/core/views/view.spec.js
This is needed by the Mapbox integration.
- `deck.needsRedraw({clearRedrawFlags})` stops executing as soon as a truthy value is found. Instead, it should recursively clear the redraw flags on all its descendants. This is causing excessive redraw in the following frames.
- `deck._redrawLayers` contains two parts of code. The first half executes on every animation frame (update canvas, async props, animation props etc.) and the second half only runs if `needsRedraw`. The `Deck` instance used in Mapbox integration calls `_redrawLayers` once per layer during redraw. To (A) ensure that updates are performed without redraw and (B) bypass the internal flag check when `_redrawLayers` is repeatedly called, the general update procedure and the actual redraw must be separated.
- `view.equals` is not …
=> Fix various deck issues that cause excessive redraw

modules/mapbox-layers/README.md
For https://github.com/uber/deck.gl/issues/2132
=> Update Mapbox integration documentation

examples/experimental/bezier/README.md, examples/website/3d-heatmap/README.md, examples/website/arc/README.md, examples/website/brushing/README.md, examples/website/geojson/README.md, examples/website/highway/README.md, examples/website/icon/README.md, examples/website/line/README.md, examples/website/scatterplot/README.md, examples/website/screen-grid/README.md
The links to the documentation on some of the examples is broken, it links to a 404 page.
Change link to documentation
=> Fix broken link to documentation on some examples

modules/core/src/lib/layer-manager.js
This is needed by the Mapbox custom layer API.
When there are multiple `Deck` instances, their layer managers share the same `lastPickedInfo` object which results in unintended side effects.
- Each `LayerManager` instance now has its own `lastPickedInfo` object
=> Fix lastPickingInfo bug

dev-docs/RFCs/README.md, dev-docs/RFCs/v6.2/mapbox-custom-layer-rfc.md
For #2132 
- While the mapbox API integration turned out to be relatively straightforward, an RFC is needed to settle the more complicated deck.gl API integration
- New RFC
=> Mapbox custom layers RFC

modules/mapbox/src/deck-utils.js, modules/mapbox/src/mapbox-layer.js, test/apps/mapbox-layers/index.html
For https://github.com/uber/deck.gl/issues/2132
API proposal to provide a path for deck.gl pure-js and React users to use Mapbox custom layers. This change allows user to leverage deck.gl top-level API such as `pickingRadius`, `onLayerHover` etc.
Example:
```js
import Deck, {ScatterplotLayer} from '@deck.gl/core';
import {MapboxLayer} from '@deck.gl/mapbox';
const map = new mapboxgl.Map({...});
const deck = new Deck({
width: '100%',
height: '100%',
longitude: -122.4,
latitude: 37.8
layers: [
new ScatterplotLayer({
id: 'my-scatterplot',
...
})
]
});
map.on('load', () => {
map.addLayer(new MapboxLayer({id: 'my-scatterplot', deck}), getFirstTextLayerId(map.getStyle()));
});
```
- Support composite layers in Mapbox integration
- Support Deck top-level props in Mapbox integration
=> Implement Mapbox custom layer API RFC

docs/api-reference/layer.md, modules/core/src/lib/layer.js, modules/core/src/shaderlib/project/project-functions.js, test/modules/core/lib/layer.spec.js
`Layer.project` does not respect the coordinate system of the position
- Use the current coordinate system for projection
- **Proposed** deprecate `Layer.projectFlat` and replace with `Layer.projectPosition`
- **Proposed** deprecate `Layer.unprojectFlat`. There is no easy way to unproject back to the original coordinate system.
=> update layer.project to use actual coordinate system

docs/api-reference/layer.md, modules/core/src/lib/layer.js, modules/core/src/shaderlib/lighting/lighting.js, modules/core/src/shaderlib/project/project-functions.js, modules/core/src/shaderlib/project/viewport-uniforms.js, modules/core/src/viewports/web-mercator-viewport.js, test/modules/core/lib/layer.spec.js, test/modules/core/shaderlib/project/project-functions.spec.js, test/modules/core/viewports/web-mercator-viewport.spec.js
`projectPosition` is the CPU utility function that projects a point from any coordinate system to the world position in another coordinate system. It is currently used by the lighting module.
In a follow up PR, I will update the `project` method on the base Layer class to use this util, so that layers can work with different coordinate systems on the CPU.
- Remove LNGLAT_AUTO_OFFSET hack from `lighting.getUniforms`
- Handle LNGLAT_AUTO_OFFSET mode in `projectPosition`
- Add tests that compare the returned values from `projectPosition` and compiled vertex shader function `project_position`.
=> Match projectPosition on CPU and GPU

scripts/publish.sh
We will be able to publish from personal accounts from now on
- Remove account check in publish script
=> Remove account check in publish script

modules/core/src/lib/layer.js, modules/core/src/shaderlib/lighting/lighting.js, modules/core/src/shaderlib/project/viewport-uniforms.js, test/modules/core/lib/layer.spec.js, test/render/test-cases.js
For https://github.com/uber/deck.gl/issues/2334
and https://github.com/uber/deck.gl/issues/2345
- Fix `Layer.use64bitProjection`
- Fix lighting module opts
- Remove inconsistent fp64 handling from `getShaderCoordinateSystem`
- Update fp64 render tests to use correct coordinate system
=> Fix lighting in LNGLAT_AUTO_OFFSET mode

modules/core/src/experimental/utils/gpu-grid-aggregation/aggregate-to-grid-vs.glsl.js, modules/core/src/experimental/utils/gpu-grid-aggregation/gpu-grid-aggregator.js, modules/core/src/viewports/viewport.js, modules/layers/src/screen-grid-layer/screen-grid-layer.js
For #2350 
ScreenGridLayer uses GPUAggregator to to perform aggregation in screen (viewport) space. It first uses `project_position` to perform mercator projection then trnasforms the result into viewport (screen) sapce to perform aggregation.
With the introduction of new LNGLAT_OFFSET (now LNGLAT) projection mode, when zoom level is more than a certain level (12), `project_position` only returns projected offsets instead of actual points. And required offset is added back during `project_to_clipspace`.
The fix is, replaced `project_position` with `project_position_to_clipspace` and instead of using `pixelProjectionMatrix` use `viewportMatrix` to convert projected points from NDC to viewport (screen) space.
- GPUGridAggregator: Project to clip space to handle offset project modes
=> GPUGridAggregator: Project to clip space to handle offset project modes.

docs/api-reference/mapbox/overview.md, test/modules/core/shaderlib/index.js, test/modules/core/shaderlib/project/project-32-64-glsl.spec.js, test/modules/core/shaderlib/project/project-glsl-test-utils.js, test/modules/core/shaderlib/project/project-glsl.spec.js, test/modules/core/shaderlib/shaderlib-test-utils.js
For #2272 & https://github.com/uber/luma.gl/issues/630 
- Add unit tests for project32 and project64 module glsl functions.
- NOTE: disabled failing unit tests on Intel (due to precision issues, expected as some of fp64 tests fail on Intel too)
- NOTE: disable some unit tests due to bugs in `glsl-transpiler` for CPU path.
- Add unit tests for project32 and project64
=> Projec3264 tests

modules/core/src/lib/layer.js
CompositeLayers do not have models but are marked needs redraw in `_updateBaseUniforms()`
- only update attributes and uniforms for non-composite layers
- use model's needsRedraw flag
=> Remove excessive redraws in layer update

docs/upgrade-guide.md, docs/whats-new.md, modules/layers/src/arc-layer/arc-layer.js, modules/layers/src/contour-layer/contour-layer.js, modules/layers/src/geojson-layer/geojson-layer.js, modules/layers/src/grid-cell-layer/grid-cell-layer.js, modules/layers/src/grid-layer/grid-layer.js, modules/layers/src/hexagon-cell-layer/hexagon-cell-layer.js, modules/layers/src/hexagon-layer/hexagon-layer.js, modules/layers/src/icon-layer/icon-layer.js, modules/layers/src/line-layer/line-layer.js, modules/layers/src/path-layer/path-layer.js, modules/layers/src/point-cloud-layer/point-cloud-layer.js, modules/layers/src/polygon-layer/polygon-layer.js, modules/layers/src/scatterplot-layer/scatterplot-layer.js, modules/layers/src/screen-grid-layer/screen-grid-layer.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer.js, modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer.js, modules/layers/src/text-layer/text-layer.js, test/modules/layers/grid-layer.spec.js, test/modules/layers/hexagon-layer.spec.js
For #1371 
GeoJsonLayer shows 2x FPS during constant React rerender (hover and viewport manipulation)
- Use prop types in all core layers
- BREAKING: HexagonLayer and GridLayer no longer updates when `getColorValue` and `getElevationValue` change shallowly - use updateTriggers instead
=> apply proptypes in layers

modules/experimental-layers/src/tile-layer/tile-layer.js, modules/experimental-layers/src/tile-layer/tile-layer.md, modules/experimental-layers/src/tile-layer/utils/tile-cache.js, modules/experimental-layers/src/tile-layer/utils/tile.js, modules/experimental-layers/src/tile-layer/utils/viewport-util.js, test/apps/mapbox-tile/app.js, test/modules/experimental-layers/index.js, test/modules/experimental-layers/tile-layer/tile-cache.spec.js
**Tile Cache**
- Set default caching size based on the size of the viewport
- When cache is full, only remove tiles that are not visible
- Use cached parents tiles when we are waiting for a new tile to be loaded
**Tile Layer**
- Only Render tiles that are between minZoom and maxZoom level
=> Handle TileLayer Caching Better

docs/developer-guide/prop-types.md, modules/core/src/lib/deck.js, modules/core/src/lib/layer-manager.js, modules/layers/src/hexagon-layer/hexagon-layer.js, modules/test-utils/src/lifecycle-test-deprecated.js, test/modules/layers/hexagon-layer.spec.js
For #2111 and #2215 
Before version 6, it was guaranteed that layers are always initialized with a viewport built with user provided parameters, during multi-viewport support this code was re-structured and now layers are initialized with a default viewport (not built with user provided `viewState` or `initialViewState`) causing issues. For example, layers that use `context.viewport` to perform projection on `data`.  Actual viewport is only set during draw time.
To fix this, build `viewport` from user provided `view`/`viewState` or default when not available, and use it to initialize the `LayerManager`, this will match the old behavior.
This change also reverts previously added WA for HexagonLayer : #2239
- Revert "Hexagon aggregation with valid viewport (#2239)"
- LayerManager: …
=> LayerManager: fix initial viewport

modules/mapbox/.babelrc
Other modules export common-js compatible modules. Looks like the babelrc didn't get copied here which caused the mapbox layer's dist output to include es6 features like modules and makes non-es6 importers like fusion unable to parse the file.
- Makes dist for Mapbox layer output es5 code instead of es6
=> Add mapbox layer babelrc

docs/layers/arc-layer.md, modules/core/package.json, modules/layers/src/arc-layer/arc-layer-vertex-64.glsl.js, modules/layers/src/arc-layer/arc-layer-vertex.glsl.js, modules/layers/src/arc-layer/arc-layer.js
As you zoom out, the ArcLayer's line widths appear to grow instead of staying consistent with the projection of the viewport. 
-This adds a `widthScale` uniform float prop meant to be used to determine the scaling factor based on the zoom level:
```
new ArcLayer({
// ...
widthScale: Math.pow(2, viewport.zoom) / scaleFactor,
})
```
Alternatively, the layer could unproject the viewport's zoom by default, and call worldToPixels on the scaleFactor. Open to suggestions.
=> Add a width scale to arc layer so it maintains projected size

modules/core/src/viewports/viewport.js
After https://github.com/uber/deck.gl/pull/2284, `pixelPerMeters` already adjusts for Mercator plane Y-flip.
- Correct offset projection in FirstPersonView
=> Fix FirstPersonView offset

docs/api-reference/deck.md, docs/api-reference/layer.md, modules/core/package.json, modules/core/src/lib/constants.js, modules/core/src/lib/deck.js, modules/core/src/lib/layer-manager.js, modules/core/src/lib/layer.js, modules/core/src/lib/pick-layers.js, yarn.lock
[RFC](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v6.x/event-handling-rfc.md)
- Support `onDragStart`, `onDrag`, `onDragEnd` callbacks in both layer and deck props.
=> Implement Event handling RFC

modules/mapbox/src/deck-utils.js, modules/mapbox/src/mapbox-layer.js
- Fix a bug for React integration: `props.layerFilter` is reset every render due to default props
- Accept a new `renderingMode` prop to `MapboxLayer`. Value can be `'2d'` or `'3d'` (default)
- When using React, also draw layers that are not added to Mapbox
=> Improve mapbox module

modules/core/src/lib/deck.js
For #2296 
- Fallback to canvas.width/height when clientWidth/clientHeight are not available.
=> Fallback to canvas.width/height when clientWidth/clientHeight are not available

modules/core/src/lib/composite-layer.js
Base `Layer` class constructor supports multiple arguments, e.g.:
`new ScatterplotLayer(props1, props2)`.
- Allow multiple arguments in CompositeLayer constructor
=> Support multiple arguments in CompositeLayer constructor

modules/core/src/experimental/utils/gpu-grid-aggregation/gpu-grid-aggregator.js, modules/core/src/experimental/utils/gpu-grid-aggregation/transform-mean-vs.glsl.js, test/modules/core/experimental/utils/gpu-grid-aggregator.spec.js
For #2291
Adding Mean operation support.
CPU: After initial aggregation, calculate mean weights (RGB) based on count (Alpha).
GPU: Use `Transform`'s texture API to calculate Mean.
- CPU: Add Mean operation support, and unit tests.
- GPU: Add Mean operation support
=> GPUGridAggregator: Add support for MEAN operations

modules/core/src/lib/layer.js, modules/core/src/lifecycle/create-props.js, test/modules/core/lib/layer-manager.spec.js
These new test cases capture a bug: if an async prop (e.g. `data`) is not specified by the user, instead of resolving to default (`[]`), it is assumed to be "loading". As a result, when later a value is supplied to this prop via layer update, `changeFlags.dataChanged` is set to `false`.
This issue does not block any applications (can be worked around by setting `data: null`), but it causes unexpected behavior in some of our core layer tests.
- Resolve undefined async props correctly
- Remove a duplicate setAsyncProps call
=> Fix async prop comparison bug

modules/core/src/experimental/utils/gpu-grid-aggregation/gpu-grid-aggregator.js, modules/core/src/experimental/utils/gpu-grid-aggregation/grid-aggregation-utils.js, modules/experimental-layers/src/mesh-layer/mesh-layer.js, modules/layers/src/contour-layer/contour-utils.js, modules/layers/src/contour-layer/marching-squares.js, modules/layers/src/screen-grid-layer/screen-grid-layer.js
For #
As commented in #2429
- Use internal `assert` in core module.
- Remove assert usage in marching-squares/contour private utility methods, most of these were added for internal validation.
- Add `assert` definition for mesh layer, not sure if we need this, but added to be safe.
- Remove assert dependency from modules
=> Remove assert dependency from modules

modules/layers/src/contour-layer/contour-layer.js, modules/layers/src/grid-layer/grid-layer.js
For #2399 
All layers should make use of changeFlags.updateTriggersChanged instead of comparing function type accessors.
- modified the incorrect comparison in contour layer and grid layer
=> fixed invalid accessor comparisons in contour layer and grid layer

modules/experimental-layers/src/tile-layer/tile-layer.js
- Pass tile layer's `sourceLayer` in `getPickingInfo`, so sublayers can access
- Pass tile to `renderSubLayers`, so sublayers can access its data.
=> Give TileLayer event callbacks access to source layer and tile

test/modules/layers/core-layers.spec.js, yarn.lock
This test case was broken due to https://github.com/uber/luma.gl/pull/782
=> Fix test with luma.gl@6.3.0-beta.2

docs/api-reference/layer.md, modules/core/src/lib/deck.js, modules/core/src/lib/layer-manager.js, modules/core/src/lib/layer.js
`onClick` and `onHover` should receive the event object as the second argument like the `onDrag*` callbacks do
=> Align parameters passed to all layer callbacks

examples/layer-browser/src/app.js, test/apps/attribute-transition/app.js
For #2480 
The layer-browser app was referencing the Uber light Mapbox style at mapbox://styles/uberdata/cive48w2e001a2imn5mcu2vrs.  This Uber light Mapbox style used to be public, but appears to have been made private.  This Uber light Mapbox style is shared by many teams at Uber, so to prevent this issue in the future, I've switched the layer-browser example to use Mapbox's default light style mapbox://styles/mapbox/light-v9, which many of the other examples do as well.  I also replaced one other use of the Uber specific Mapbox style in a unit test.
=> Fix missing mapbox style in layer-browser

examples/layer-browser/src/data-samples.js, modules/layers/src/path-layer/path-layer-vertex-64.glsl.js, modules/layers/src/path-layer/path-layer-vertex.glsl.js
For
https://github.com/uber/deck.gl/issues/2384
https://github.com/uber/deck.gl/issues/2301
- Point filter should use relative distance instead of absolute (tiny line segment use case)
- Precision fix: apply delta to position64xyLow in auto-offset mode
Before: 
After:
=> PathLayer: fix various precision issues

dev-docs/RFCs/README.md
Looks like there's a small typo in the RFC README that causes one of the markdown tables to not render correctly. This PR fixes that.
Let me know if you want me to open a GitHub Issue and go through that workflow. 😄
=> fix RFC Readme table formatting

modules/core/package.json, test/modules/layers/index.js, test/modules/layers/path-layer/path-layer-vertex.spec.js, yarn.lock
For #
**NOTE** requires : https://github.com/uber/luma.gl/pull/812
As discussed in https://github.com/uber/deck.gl/pull/2495
Reference implementation to add unit tests for a layer shader. Shader should be divded into multiple glsl functions and these functions can be tested individually.
More robust unit tests can be added using this as reference, for which we need the correct values for intermediate shader variables.
- UnitTests: for path layer shaders
=> UnitTests: for path layer shaders

modules/experimental-layers/src/bitmap-layer/bitmap-layer.js
For #2477 
In bitmap layer, the defaultProps don't have types specified. We need to specify type for those props.
- Add type to the defaultProps in the bitmap layers
=> specify types for defaultProps in bitmap layer

modules/experimental-layers/src/gpu-grid-layer/gpu-grid-cell-layer.js, modules/experimental-layers/src/gpu-grid-layer/gpu-grid-layer.js
For #2477 
In gpu grid layer, the defaultProps don't have types specified. We need to specify type for those props.
- Add type to the defaultProps in the gpu grid layers
=> specify types for defaultProps in gpu grid layer

test/modules/core/lib/pick-layers.spec.js, test/modules/index.js
For #1756 
We need to enhance deck.gl test utils to test different approaches of picking objects, such as single-pixel picking, rectangular picking and multi-depth picking.
- add test cases for picking test
- test scatterplotLayer, polygonLayer, pathLayer and multiple layers overlapping
- test single-pixel picking, rectangular picking and multi-depth picking
=> add picking test

modules/layers/src/path-layer/path-layer.js, test/modules/core/lib/pick-layers.spec.js
For #2478 
In pathLayer, pickMultipleObjects is expected to return an array of different objects at the picking point. But it returns an array of same objects.
- add clearPickingColor in pathLayer which overrides its parent class(layer.js)
- add test cases in picking test
Note: tested with layer browser and picking test
=> fix pickMultipleObjects in pathLayer

modules/layers/src/path-layer/path-layer.js
For #2478 
In pathLayer, pickMultipleObjects is expected to return an array of different objects at the picking point. But it returns an array of same objects.
- add clearPickingColor in pathLayer which overrides its parent class(layer.js)
Note: tested with layer browser and render-test
=> fix pickMultipleObjects in pathLayer(6.3-release)

modules/experimental-layers/src/mesh-layer/mesh-layer.js, modules/experimental-layers/src/mesh-layer/mesh-layer.md
For #2477 
In mesh layer, the defaultProps don't have types specified. We need to specify type for those props.
- Add type to the defaultProps in the mesh layer
note: tested with render test and layer browser
=> specify types for defaultProps in mesh layer

modules/core/src/lib/layer.js
For https://github.com/uber/deck.gl/issues/2533
We are using the return value of `layer.onClick` and `layer.onHover` here:
https://github.com/uber/deck.gl/blob/master/modules/core/src/lib/pick-layers.js#L398
But the default implementations do not return anything.
This was broken by
https://github.com/uber/deck.gl/commit/940f1b023c1b53be6dadcf4edcb0083331ddf136#diff-53a662c6a53ead1797297b72797107d9
- Use the return values of user supplied `onClick` and `onHover`
=> Fix handling for event callback function return values

modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
For #2537 
The current clearPickingColor method in solid-polygon-layer is inefficient in performance. We can improve the time complexity from linear to constant
- override clearPickingColor method by finding the starting and ending offset of the data points which have the same picking color as the selected picking color and then updating values
note: tested with picking test and layer browser
=> modify clearPickingColor in solid-polygon-layer

docs/api-reference/layer.md
As mentioned in #2565 comments https://github.com/uber/deck.gl/issues/2565#issuecomment-453124435,
Change List:
* Property name "propsChanged" in `updateState` and `shouldUpdateState` is misspelled (`propChanged`);
* Implement properties structure like `stateChanged` inside `changeFlags` in `updateState` and `shouldUpdateState`;
=> Documentation Updates

modules/mapbox/src/deck-utils.js
After Mapbox renders, the GL context is not restored to its previous state. Let's reset the blend parameters after Mapbox renders in order to ensure a restored state.
=> reset blend params after mapbox render

docs/layers/text-layer.md, examples/layer-browser/src/examples/core-layers.js, modules/layers/package.json, modules/layers/src/text-layer/font-atlas.js, modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer-fragment.glsl.js, modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer-vertex.glsl.js, modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer.js, modules/layers/src/text-layer/text-layer.js
[issue](https://github.com/uber/deck.gl/issues/2546)
This PR focuses on the first and second items
- Use SDF in font atlas generation
- fontSmoothing: Number
- Applied `TinySDF` library to encode the distance (distance between a data point and nearest character edge) into texture alpha channel
Rendering comparison:
1. looking:
```
sizeScale: 48
getSize: 100
```
Left is the original code, right is with `sdf` applied. 
2. performance:
```
fontSize: 64 // used in generating `fontAtlas`
```
Time used for generating fontAtlas:
```
original: <5 milliseconds 
sdf:      ~50 - 100 milliseconds 
```
=> Apply TinySDF to TextLayer

dev-docs/RFCs/v7.x/binary-data-rfc.md, docs/layers/path-layer.md, examples/layer-browser/src/examples/core-layers.js, modules/core/src/utils/tesselator.js, modules/layers/src/path-layer/path-layer.js, modules/layers/src/path-layer/path-tesselator.js
For https://github.com/uber/deck.gl/issues/2492
There are several components to supporting generic binary input:
- Users need to be able to specify per-object size when the `data` prop is a flat array (see discussion on https://github.com/uber/deck.gl/pull/2436)
- PathLayer and PolygonLayer need to support flattened coordinates
- Users need to be able to supply additional information along with the flattened coordinates (e.g. dimensions of the points; hole indices, if drawing complex polygon)
- Binary data RFC
- Add flat path data example to layer browser
- Support flat coordinates in PathLayer (proof of concept)
- PathLayer documentation
=> Flat path data proposal

modules/core/src/lifecycle/component.js, test/modules/core/lib/layer.spec.js
`layer.clone()` always results in `data` prop being an empty array.
- Fix async prop cloning
- Add test case
=> Fix layer.clone bug

modules/layers/src/path-layer/path-layer-fragment.glsl.js, modules/layers/src/path-layer/path-layer-vertex-64.glsl.js, modules/layers/src/path-layer/path-layer-vertex.glsl.js
The old varying `float vPathPosition` is set to the position of a fragment along the length of the path, normalized by width. This PR makes the varying a `vec2`, adding the position along the width of the path as the `x` component.
As an attempt to make the PathLayer more customizable, this change addresses an internal use case where we need to subclass the PathLayer to add custom fill logic in the fragment shader, including double line, path offset, and custom marking patterns.
Example to draw double line:
```js
class MyPathLayer extends PathLayer {
getShaders() {
return {
...super.getShaders(),
inject: {
'fs:#main-start': `if (abs(vPathPosition.x) < 0.1) discard;`
}
}
}
}
```
- Change `vPathPosition` varying from `float` to `vec2`
=> PathLayer shader: 2-dimensional vPathPosition

docs/developer-guide/prop-types.md, modules/core/src/lifecycle/create-props.js, modules/core/src/lifecycle/prop-types.js, modules/layers/src/arc-layer/arc-layer.js, modules/layers/src/line-layer/line-layer.js, test/modules/core/lifecycle/props.spec.js
For https://github.com/uber/deck.gl/issues/2584
- Support `getValue` callback in prop type definition
- Fix `LineLayer` constructor support for multiple arguments
- Tests
=> Add deprecated flag to prop types

docs/layers/path-layer.md, docs/layers/polygon-layer.md, docs/layers/solid-polygon-layer.md, examples/layer-browser/src/app.js, examples/layer-browser/src/examples/core-layers.js, modules/core/src/lib/composite-layer.js, modules/core/src/lifecycle/props.js, modules/layers/src/polygon-layer/polygon-layer.js, modules/layers/src/solid-polygon-layer/polygon-tesselator.js, modules/layers/src/solid-polygon-layer/polygon.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer.js, test/modules/layers/path-tesselator.spec.js, test/modules/layers/polygon-tesselation.spec.js
For #2492 
- Support two new polygon input format: flat array and `{positions, loopStartIndices}`
- Forward `positionFormat` prop from composite layer to sublayer
- When `positionFormat` prop changes, set `dataChanged` flag
- `Polygon.normalize` now returns the complex flat format (`{positions, loopStartIndices}`)
- Layer browser example
- Tests
=> Support flat data input to polygon layer

modules/experimental-layers/src/tile-layer/tile-layer.md
Typo in documentation (or maybe you'd want to change the code to match the docs? Either way.)
- "renderSubLayer" -> "renderSubLayers"
=> In docs, "renderSubLayer" -> "renderSubLayers"

docs/api-reference/orthographic-view.md, modules/core/src/controllers/orthographic-controller.js
The startZoomPosition should be passed down to the interactiveState in Orthographic Controller.
-
=> Pass the missing startZoomPosition into Orthographic Controller interactiveState

docs/developer-guide/prop-types.md, examples/layer-browser/src/examples/core-layers.js, modules/core/src/lifecycle/create-props.js, modules/core/src/lifecycle/prop-types.js, modules/layers/src/geojson-layer/geojson-layer.js, modules/layers/src/scatterplot-layer/scatterplot-layer.js
For #2584 
- Allow `deprecatedFor` to be an array
- Remove ad-hoc ScatterPlotLayer constructor
- Revert GeoJsonLayer to using multiple arguments in creating ScatterPlotLayer
=> Fix multiple argument support in ScatterplotLayer

modules/core/package.json, modules/core/src/lib/attribute-transition-manager.js, modules/core/src/lib/attribute.js, modules/core/src/lib/layer-manager.js, modules/core/src/lib/layer.js, modules/core/src/utils/tesselator.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer.js, test/modules/core/lib/attribute-manager.spec.js, test/modules/core/lib/attribute-transition-manager.spec.js, test/modules/core/lib/layer-manager.spec.js, yarn.lock
For #2489 
This PR contains necessary changes to the core classes.
- Use the latest mjolnir.js (can be safely imported in a worker)
- Use the latest luma.gl (`Attribute` ignores missing WebGLContext, and properly infers index type)
- Make the following constructors ignore missing WebGLContext: `AttributeManager`, `AttributeTransitionManager`, `LayerManager`.
- `numInstances` and `vertexCount` defined in layer `props` override those in `state`.
- When using external buffers for attribute values, relax type check from throwing an error to a warning.
=> Generate layer attributes on a worker (PR 1/3)

modules/layers/src/text-layer/text-layer.js
- This debug log is to help evaluate the time difference between with and without SDF applied to `TextLayer`
- delete logging generating fontAtlas time
=> remove logging fontAlas time

modules/core/src/lib/attribute-transition-manager.js, test/modules/core/lib/attribute-transition-manager.spec.js
If `data` is an url, before it is loaded, `data.length` is 0. The `Transform` class throws an error if `elementCount` is 0: https://github.com/uber/luma.gl/blob/6.3-release/modules/core/src/core/transform.js#L289
- Force data length to be non-zero
- Add test case
=> Fix AttributeTransitionManager crash when data is empty

modules/experimental-layers/src/tile-layer/tile-layer.md
Copying and pasting the original did not work for me, but this does.
Also, the default viewport just gave me a blue square... Not sure if that's the right behavior? This looks better for me, but I'm not sure how that should be integrated into this document.
```
<App viewport={new WebMercatorViewport({
width:600, height:600, zoom: 10, longitude: -71.1, latitude:42.4
})}/>
```
- `@deck.gl/experimental-layers/tile-layer/tile-layer` -> `@deck.gl/experimental-layers`
- `TileLayer` -> `{TileLayer}`
=> Update import path for TileLayer in example

modules/core/src/lifecycle/create-props.js
Unbreak `updateTriggers` and `transitions` if a deprecated accessor is used.
- Check deprecated props in updateTriggers and transitions
=> Check deprecated props in updateTriggers and transitions

modules/core/src/lib/init.js, modules/react/index.js
For https://github.com/uber/deck.gl/issues/2530
- Remove `require('../shaderlib')` from init (already imported at root)
- Remove an unused file from the react submodule
=> Remove require()

docs/api-reference/composite-layer.md, docs/layers/text-layer.md, modules/core/src/lib/composite-layer.js, modules/layers/src/geojson-layer/geojson-layer.js, modules/layers/src/grid-layer/grid-layer.js, modules/layers/src/hexagon-layer/hexagon-layer.js, modules/layers/src/polygon-layer/polygon-layer.js, modules/layers/src/text-layer/text-layer.js
RFC: https://github.com/uber/deck.gl/pull/2600
- Add `compositeLayer.getSubLayerClass` method
- Update all core composite layers' `renderLayers` method. Some sublayer props are no longer passed to `compositeLayer.getSubLayerProps` for perf reasons (reduce `Object.assign` cost) but there's no functional changes.
=> Update composite layer API

docs/api-reference/orthographic-view.md, examples/experimental/bezier/app.js, modules/core/src/controllers/orthographic-controller.js, modules/core/src/lib/view-manager.js, modules/core/src/shaderlib/project/viewport-uniforms.js, modules/core/src/views/orthographic-view.js, test/render/test-cases.js
For #2622 
Bug fixes:
- Fix crash when `offset` is not present in `viewState`
- Fix bug where zoom center does not stay under the pointer
- Fix project module error when `zoom < 0`
Breaking changes:
- Default `zoom`: `0`
- Default `minZoom`: `-10`
- Default `maxZoom`: `10`
- `eye`, `lookAt` and `up` are moved to view props from view state
Doc updates:
- Document new default values
- Remove `left` `top` `right` `bottom` from view props - the controller does not work with these props, and incorrectly set bounds will break the view. We should remove them in v7.0.
=> OrthographicView updates

examples/experimental/bezier/bezier-graph-layer.js, examples/get-started/react-browserify/app.js, examples/get-started/react-webpack-2/app.js, examples/layer-browser/src/examples/perf-layers.js, examples/website/brushing/app.js, examples/website/line/app.js
For #2623 
depreciation warning are found in website examples that use scatterplot layer. 
- replace deprecated props with new ones
=> replace deprecated props of scatterplot layer in examples

docs/layers/text-layer.md, examples/layer-browser/src/examples/core-layers.js, modules/layers/src/text-layer/font-atlas.js, modules/layers/src/text-layer/text-layer.js
For #1550 
- change TextLayer API
- expose fontSettings for generating `fontAtlas` as layer props
- extend layer browser example to include `fontSettings` options
[RFC](https://github.com/uber/deck.gl/pull/2627)
Should cover this [PR](https://github.com/uber/deck.gl/pull/2609)
=> expose font settings as TextLayer props

examples/website/brushing/app.js, examples/website/brushing/scatterplot-brushing-layer/scatterplot-brushing-layer-fragment.glsl.js, examples/website/brushing/scatterplot-brushing-layer/scatterplot-brushing-layer-vertex.glsl.js, examples/website/brushing/scatterplot-brushing-layer/scatterplot-brushing-layer.js
For #2623 
Scatterplot brushing layer extends scatterplot layer. Due to the API update in scatterplot layer, the APIs in scatterplot brushing layer also need to be updated.
- update APIs in scatterplot brushing layer
- update the brushing example of deck.gl website
note: the rendering result is compared with that in 6.3-release
=> fix deprecated props in brushing example

modules/experimental-layers/src/path-outline-layer/path-outline-layer.js
For #2477 
In path outline layer, the defaultProps don't have types specified. We need to specify type for those props.
- Add type to the defaultProps in path outline layer
note: tested with render test and layer-browser. compared the rendering result with that in 6.3-release
=> add type for defaultProps in path outline layer

docs/layers/scatterplot-layer.md
…rs in docs
For #2544 
the unit of getLineWidth of ScatterplotLayer should be meters, not pixels
- change pixels to meters in the documentation
=> update the unit of getLineWidth(ScatterplotLayer) in doc

modules/experimental-layers/src/path-marker-layer/create-path-markers.js, modules/experimental-layers/src/path-marker-layer/path-marker-layer.js
For #2477 
In PathMarkerLayer, the defaultProps don't have types specified. We need to specify types for those props.
- Add type to the defaultProps in the PathMarkerLayer
note: tested in layer browser
=> specify types for defaultProps in PathMarkerLayer

docs/api-reference/orthographic-view.md
I could be confused, but OrthographicView is a subclass of View, rather than of Viewport, and the link points to View, too.
- s/Viewport/View/
=> fix "Inherits all Viewport/View methods"

docs/developer-guide/tips-and-tricks.md
Two small typos in tips-and-tricks
- Remove repeated word
- Add "s" to verb
=> repeated word in tips-and-tricks

docs/developer-guide/prop-types.md
On http://deck.gl/#/documentation/developer-guide/writing-custom-layers/layer-prop-types there is an extra paren on this line:
> Reflection) (e.g. dynamically creating UI controls for layer props)
My guess is a discrepancy between markdown parsers?
And 'allows ... to happen' is probably better than 'offers ... to happen'
- Encode the URL so the trailing paren won't cause problems.
- Switch verb
=> Encode URL so that extra ")" does not come through

docs/api-reference/deck.md
For #2658 (second section)
Code example uses wrong method name: Now it matches section title, and the signature is correct.
- At one location, pickObject -> pickMultipleObjects
=> In docs: pickObjects -> pickMultipleObjects

docs/developer-guide/primitive-layers.md
The docs on primitive-layers are missing a few words and parentheses, and so it's a bit hard to read. (Nothing here should change the meaning of the text.)
- add missing words
- balance parens
=> grammar typos in primitive-layers

docs/get-started/interactivity.md
For #2658 (first section)
Page linked from documentation doesn't actually have any information on the picking methods mentioned.
- Just at this line, change "DeckGL" to "Deck",
- and point at the "Deck" documentation page.
Perhaps an anchored link would be better?
Apologies again if I'm confused.
=> docs: pick methods belong to Deck, not DeckGL

modules/layers/src/path-layer/path-tesselator.js, test/modules/layers/path-tesselator.spec.js
When index is out of bounds, `this.getPointOnPath` returns `undefined` for nested vertices, and `[undefined, undefined, undefined]` for flat vertices. This leads to `NaN`s in the `rightDeltas` array.
- Explicitly check if index is within bounds
- Add test cases
=> PathLayer: fix rightDeltas attribute generation when using flat vertices

modules/core/src/lib/layer.js, modules/layers/src/path-layer/path-layer.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer.js, modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer.js, test/bench/layer.bench.js
Calculate picking color for 1M instances, before: 45 iterations/s; after: 412 iterations/s
Since `layer.calculateInstancePickingColors` always produces the same sequence, we can save the largest generated array and copy its value into others.
We can potentially make all `instancePickingColors` attributes share the same WebGLBuffer, but that would introduce more complexity around:
- Retrieving the shared buffer by GL context
- Creating a temporary buffer when performing multi-depth picking
- Optimize `layer.calculateInstancePickingColors`
- Benchmark case
=> Improve picking color generation

modules/layers/src/path-layer/path-layer.js, test/modules/core/lib/pick-layers.spec.js
For #2700 
This was fixed separately for master and 6.3-release branches in #2532 and #2534. We did not consolidate the changes correctly when creating the 6.4-release branch.
- Fix PathLayer's reference to `pathTesselator`
- Restore multi-depth picking tests
=> Multi-depth picking fix

README.md, dev-docs/RFCs/v7.x/binary-data-rfc.md, docs/api-reference/layer.md, docs/api-reference/mapbox/mapbox-layer.md, docs/api-reference/mapbox/overview.md, docs/developer-guide/composite-layers.md, docs/get-started/interactivity.md, examples/experimental/json-common/examples/dot-text.json, examples/experimental/json-common/examples/line.json, examples/experimental/json-common/examples/scatterplot.json, showcases/graph/graph-layer/graph-layer.js, showcases/wind/src/wind-demo.js
For #2544 
- replace deprecated API usage in ScatterplotLayer due to the API update for 6.4 release
- replace deprecated APIs with new one in ScatterplotLayer in the documentation
=> replace deprecated APIs of ScatterplotLayer in documentation

docs/api-reference/deck.md, modules/core/src/lib/deck.js
This is to support performance instrumentation in streetscape.gl.
- Add experimental `onMetrics` prop to `Deck`
- Update documentation
=> Add experimental onMetrics callback

modules/core/src/lib/deck.js
For https://github.com/uber/deck.gl/issues/1913 - currently multiple test cases in the browser test create `Deck` instances and they do not get cleaned up after the tests are done. This is interfering with the new snapshot tests.
- If the canvas is not externally provided, it should be removed when `Deck` instance is finalized.
=> Remove internally created canvas when deck is finalized

modules/core/src/lib/attribute-manager.js, modules/core/src/lib/attribute.js, modules/core/src/lib/layer.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer-vertex-main.glsl.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer-vertex-side.glsl.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer-vertex-top.glsl.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer-vertex.glsl.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
Removes the `updateAttributes` override in SolidPolygonLayer.
- `AttributeManger.update` now iterates over all models in `getModels()` array to update attributes of all models associated with a layer.
- `shaderAttributes` support constant values.
- `SolidPolygonLayer` `vertexCount` and `instanceCount` are now updated whenever the `polygonTesselator` runs, so that no longer needs to happen in `updateAttributes`.
- All instanced vs non-instanced attributes are separated and given different names so they don't need to be hijacked.
- If `Model.userData.excludeAttributes` exists, it will be used to filter out attributes for that model. This is used to exclude `indices` from `sideModel` for its non-indexed rendering.
=> SolidPolygonLayer cleanup

docs/developer-guide/primitive-layers.md
These have been moved to `modules/experimental-layers` and are no longer under `examples`.
... Though there is a note at the top of the referenced file:
> Note: This file will either be moved back to deck.gl or reformatted to web-monorepo standards
If they will only be in their current location temporarily, then this PR might not make sense?
Another option might be to add an actual link to the source code of the examples. Your call.
- Replace `examples/sample-layers` with `modules/experimental-layers/src` in two places.
=> fix paths to examples in docs

dev-docs/RFCs/v7.x/binary-data-rfc.md, dev-docs/RFCs/v7.x/effects-manager-rfc.md, dev-docs/rfc-guidelines.md
As I was reading the documentation I found some typos and I would like to fix them.
- dev-docs/RFCs/v7.x/binary-data-rfc.md
- dev-docs/RFCs/v7.x/effects-manager-rfc.md
- dev-docs/rfc-guidelines.md
=> Fixes typos in RFCs

docs/layers/icon-layer.md, examples/layer-browser/src/examples/core-layers.js, modules/layers/src/icon-layer/icon-manager.js, test/modules/layers/icon-manager.spec.js
#2725 
- update document
- In `auto packing` case: `getMapping` could return an object with an additional field `id`, used to track which icons are already fetched
=> Support caching icons

modules/layers/src/path-layer/path-tesselator.js, modules/layers/src/solid-polygon-layer/polygon-tesselator.js
**Background**
#2732
**Changes**
Instead of mutating the color variables when missing the alpha value, return a new color array instead.
=> Prevent mutation of color variables passed to color setters

modules/core/src/effects/lighting-effect.js
For #2096 
Planned to have a PointLight class in deck.gl with coordinate information, found which is not necessary, change the import name back.
- fix point light class import name
=> Change point light class import name

modules/lite/package.json, modules/lite/src/deckgl.js, modules/lite/test/index.html, modules/mapbox/src/deck-utils.js, yarn.lock
For #2736 
- Upgrade mapbox dependency of the standalone bundle to v4
- Redraw map in `onBeforeRender` which is more reliable
- Update mapbox submodule to use new render pipeline
=> Upgrade mapbox dependency for standalone bundle

modules/core/package.json, modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js, yarn.lock
=> Add mat4 instanceModelMatrix to ScenegraphLayer

modules/core/src/lib/attribute-manager.js, modules/core/src/lib/deck-renderer.js, modules/core/src/lib/deck.js, modules/core/src/lib/effect-manager.js, modules/core/src/lib/layer-manager.js, modules/core/src/lib/layer.js, modules/core/src/lib/view-manager.js, test/modules/core/views/view-manager.spec.js
- avoid recursively creating small objects in `deck.needsRedraw`
- all `clearRedrawFlags` are now default to `false`
=> Avoid creating small objects when checking redraw flags

modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer.js, modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.js, modules/aggregation-layers/src/utils/gpu-grid-aggregation/grid-aggregation-utils.js, modules/core/src/index.js
- Avoid using `Array.push`, pre-allocate typed arrays
- Remove excessive `assert`s
=> Improve grid aggregation perf

modules/core/src/controllers/controller.js
Fixing a bug. When there are multiple views each with its own controller, panning outside of the current viewport would cause the controller inside the current viewport to fire "panmove", which would throw an error. Adding checks here so panmove doesn't get fired.
fixes #2779 
- ` modules/core/src/controllers/controller.js`
=> Don't fire panmove if drag started somewhere else

modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-cell-layer.js, modules/core/package.json, modules/core/src/shaderlib/index.js, modules/layers/src/grid-cell-layer/grid-cell-layer.js, modules/layers/src/hexagon-cell-layer/hexagon-cell-layer.js, modules/layers/src/point-cloud-layer/point-cloud-layer.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer.js, yarn.lock
For #2096 
- integrate with module with new name
=> integrate phong light module with new name

modules/test-utils/src/generate-layer-tests.js, test/modules/layers/geojson-layer.spec.js, test/modules/layers/polygon-layer.spec.js
1. onAfterUpdate should be called in every test
2. onAfterUpdate should work when data is empty
=> Fix onAfterUpdate callback in tests

docs/layers/tile-layer.md, modules/geo-layers/src/tile-layer/tile-layer.js, website/package.json, website/src/components/demos/layer-demo-base.js, website/src/components/demos/layer-demos.js
v7.0 API audit
- tile-layer.md
- website demo
=> TileLayer: add embed demo example

babel.config.js, docs/layers/tile-layer.md, examples/website/openstreet-map/README.md, examples/website/openstreet-map/app.js, examples/website/openstreet-map/index.html, examples/website/openstreet-map/package.json, examples/website/openstreet-map/webpack.config.js, modules/core/src/lib/picking/pick-info.js, modules/geo-layers/src/tile-layer/tile-layer.js, modules/geo-layers/src/tile-layer/utils/tile.js, modules/layers/src/bitmap-layer/bitmap-layer-fragment.js, modules/layers/src/bitmap-layer/bitmap-layer-vertex.js, modules/layers/src/bitmap-layer/bitmap-layer.js, test/apps/mapbox-tile/app.js, test/modules/geo-layers/tile-layer/index.js, test/modules/geo-layers/tile-layer/tile.spec.js
=> Add OpenStreetMap example using TileLayer and BitmapLayer

modules/core/src/lib/layer.js
- No longer checks model redraw flag (deprecated in v7)
=> Remove dependency on model redraw flags

docs/api-reference/deck.md, docs/api-reference/layer.md, docs/api-reference/mapbox/mapbox-layer.md, docs/developer-guide/interactivity.md, docs/upgrade-guide.md, examples/layer-browser/src/app.js, modules/core/src/lib/constants.js, modules/core/src/lib/deck.js
@xintongxia has observed that the `pointermove` event sometimes fires multiple times between two animation frames. I do not see this locally in Chrome, but it's steadily reproducible in Safari.
Edit: upgraded to Chrome 73 from 72 and the issue is showing up.
I'm fairly certain the above behavior is causing this bug: https://github.com/uber/deck.gl/issues/2550
Note that the proposed new system no longer support the legacy event handling behavior (pick on both hover and click). When we introduced additional event handlers (onDrag*) in 6.3, we kept the existing click/hover behavior to avoid breaking change. The old `onLayerHover(info, infos, srcEvent)` and `onLayerClick(info, infos, srcEvent)` callbacks no longer pass a meaningful second argument (leftover from the v5 layer-by-layer picking …
=> Only pick once per animation frame

modules/layers/src/bitmap-layer/bitmap-layer.js
BitmapLayer has artifacts when rendering multiple layers side by side.
- forces only sampling pixels from the actual texture
=> Fix bitmap artifacts

modules/layers/src/column-layer/column-layer.js
Smaller step toward cleaning up the attributes. Prevent column layer from manipulating geometry attributes directly.
=> Clean up column layer geometry usage

docs/api-reference/internal/attribute.md, docs/api-reference/internal/layer-manager.md, modules/core/src/lib/attribute.js, modules/core/src/lib/base-attribute.js, test/modules/core/lib/base-attribute.spec.js, test/modules/core/lib/index.js
For #
- luma `Model` now longer imports the `Attribute` class, it just [checks for `attribute.getValue()`](https://github.com/uber/luma.gl/blob/master/modules/core/src/core/model.js#L102) and calls it if present.
- No code in luma uses the `Attribute` class directly. 
- By copying it here, we can remove it in luma.
- Copy `Attribute` class to `lib` as `BaseAttribute`
- Extend `Attribute` from `BaseAttribute`
- if approved, I will move `attribute.spec` as well and update.
=> PROPOSAL: Move Attribute from luma to deck

examples/webpack.config.local.js
The removal of the rule breaks custom layer examples - `class A extends Layer` breaks if the app is transpiled while `Layer` is es6.
=> Restore source transpilation in local example config

website/contents/pages.js, website/src/components/demos/layer-demo-base.js, website/src/components/page.js
Embed demos do not pick up the parameters from user because of a recent change.
https://github.com/uber/deck.gl/pull/2814/
- remove unapplied H3 links
- fix parameters not updated in embed demos
=> Fix layer demos not update parameters

docs/api-reference/deck.md, modules/core/src/lib/deck.js
=> Add redraw method

docs/layers/h3-cluster-layer.md, docs/layers/h3-hexagon-layer.md, examples/webpack.config.local.js, modules/core/package.json, modules/geo-layers/package.json, modules/mesh-layers/package.json, package.json, scripts/bundle.config.js, yarn.lock
- Use the latest version of luma
- Use the prod version of probe.gl
- Use the latest version of h3-js (fixes "Can't resolve 'fs'" issue when bundled using Webpack)
=> Bump dependencies

modules/core/package.json, modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js, modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js, modules/mesh-layers/src/utils/matrix.js, yarn.lock
For #2890 
Matrix attributes no longer hold on to layer at initialization. Required an update to Luma.gl.
=> Fix stale layer bug when using matrix attributes

examples/webpack.config.local.js
@luma.gl/addons is not imported into the root directory.
=> Remove aliasing of @luma.gl/addons in examples

docs/layers/arc-layer.md, docs/layers/icon-layer.md, docs/layers/line-layer.md, docs/layers/path-layer.md, docs/layers/scatterplot-layer.md, docs/layers/text-layer.md, modules/layers/src/arc-layer/arc-layer.js, modules/layers/src/line-layer/line-layer.js, modules/layers/src/scatterplot-layer/scatterplot-layer.js
Prior to introducing `widthUnits`, we agreed to change the default value of `widthMinPixels` from `0` to `1`. This decision was never fully implemented, and we have a bunch of inconsistencies between layers and their docs.
I find the resulting behavior very confusing when combined with `widthUnits: 'pixels'` (default in ArcLayer and LineLayer). In this case, `getWidth` is supposed to return width in pixels, but it is ineffective when returning a number smaller than 1. I would argue that this is unexpected behavior as the user did not specify `widthMinPixels` themselves.
I see two solutions to this:
- Default `*MinPixels` to `1` only if using meter units, otherwise `0`;
- Keep the defaults `0` and do not make any breaking change for v7.
=> Revert min-pixels prop default

docs/upgrade-guide.md, examples/layer-browser/src/components/layer-info.js, modules/core/src/lib/deck-picker.js, modules/core/src/lib/deck.js, modules/core/src/lib/picking/pick-info.js, test/modules/core/lib/pick-layers.spec.js
The new `onHover` callback (replaces `onLayerHover`) should always return a non-empty first argument per documentation.
- `pickObject` returns a valid picking info object (with `index: -1` and current pixel information) even if nothing is picked
- Fix layer browser crash
=> Fix onHover behavior

modules/core/src/controllers/controller.js, modules/core/src/controllers/transition-manager.js, modules/core/src/lib/attribute-manager.js, modules/core/src/lib/deck.js, modules/core/src/lib/layer-manager.js, modules/core/src/lib/layer.js, modules/core/src/lib/view-manager.js, test/modules/core/lib/transition-manager.spec.js
This PR is preparation for:
- Supporting externally provided world clock (replaces `Date.now()`) for more robust testing & video capture
- Fixing render synchronization issues in React
- Use `animationProps` from `AnimationLoop` to drive attribute transitions
- Use `animationProps` from `AnimationLoop` to drive viewport transitions
=> Use the same animation loop for render, attribute transitions and viewport transitions

modules/core/src/lib/deck.js
External gl context must be supplied to `AnimationLoop` as a prop for polyfill to work. This breaks the mapbox custom layer use case.
=> Fix external gl context usage

modules/core/src/lib/deck-renderer.js, modules/core/src/lib/deck.js, modules/core/src/passes/layers-pass.js, modules/core/src/passes/pick-layers-pass.js, modules/mapbox/src/deck-utils.js
The `_customRender` prop does 3 things:
1. it is called instead of `drawLayers` on each redraw
2. it prevents the render pass from clearing the canvas
3. it prevents Deck from registering pointer events
2 & 3 are not implied in the prop name, and makes it very difficult for the user of this prop to control side effects.
The `_customRender` prop is currently only used in mapbox integration.
- `Deck` always create `EventManager` regardless of `_customRender`
- Remove `customRender` logic from `DeckRenderer` and `LayersPass`
- Simplify mapbox integration event handling logic - always use deck events
- Remove `layerFilter` hack from mapbox integration (was not working)
=> Clean up customRender prop handling

modules/core/src/index.js, modules/react/src/deckgl.js, modules/react/src/utils/position-children-under-views.js
- Export `memoize` from core
- Avoid re-extracting JSX components if props are not changed
=> Improve react perf with memoized extractors

docs/api-reference/standalone/deckgl.md, docs/get-started/using-standalone.md
For #2892 
- Mention the props getFillColor and getRadius in the Standalone doc example for ScatterPlotLayer.
- Fix broken links for observablehq
=> Minor doc fixes

examples/gallery/build-tools/constants.js, examples/gallery/src/point-cloud-layer.html, scripts/bundle.config.js
- Rename dev bundle to dist.dev.js
- Update reference in gallery start-local script
- Fix point cloud standalone example
=> Fix gallery examples

docs/layers/h3-cluster-layer.md, docs/layers/h3-hexagon-layer.md
For #2892 (see Firefox testing issues list).
Remove references to PolygonLayer demos in new H3 layer doc pages.  Better to have no embedded demo than the incorrect one.
Filed issue #2979 to add missing H3 layer embedded examples in a future release.
=> Remove references to PolygonLayer demos in new H3 layer doc pages.

modules/core/src/lib/effect-manager.js
The effects comparing is always fail in effects manager class because we added the default lighting.
- use the right way to apply default lighting
=> fix effects comparing issue

docs/upgrade-guide.md, docs/whats-new.md
For #2892 
* Add more gifs and images for new layers
* Add glTF section
* Fix formatting
=> More Content and Polish for Whats New

modules/core/src/lifecycle/props.js, test/bench/compare-props.bench.js, test/bench/index.js
For https://github.com/uber/streetscape.gl/issues/298
If shallow comparison fails, `compareProps` stringifies the changed prop values. This imposes a large cost when the value is a large array.
Benchmark with a `instancePositions` prop for 33.3k points:
Before: 7.30 iterations/s ±0.43%
After: 389K iterations/s ±4.19%
- Remove values from `compreProps`'s props changed reason string.
=> Fix compareProps perf

docs/layers/icon-layer.md
**IconLayer AutoPacking Example**
- Change Octokit request format from `octokit.repos.listContributors` to `octokit.repos.getContributors`
- Change the tooltip parameters according to example dataset.
- For the autopacking example, I don't think Icons need to be treated as a transparency mask. Keep the default value for mask which is false and the user-defined `getColor` accessor is not required.
=> Minor changes to the IconLayer AutoPacking Docs Example

examples/gallery/src/line-layer.html
For #2968 
- Fix the `deck.gl` URL and add `onHover` to the demo to make it interactive for the user.
=> Add Changes to the LineLayer Demo

modules/react/src/deckgl.js
In streetscape.gl, viewState and React children (DOM labels) are changed at the same time. In the current implementation, child components are updated before the Deck viewports, resulting in flashing of label positions.
- When both children and views are changed, defer React rerender to the next animation frame.
=> More React synchronization fix

modules/google-maps/src/google-maps-overlay.js, modules/google-maps/src/utils.js
For #2981 
- Implement `overlay.onRemove`
- Remove listeners correctly
- Remove canvas when finalized
=> Fix GoogleMapsOverlay remove and finalize

modules/geo-layers/src/h3-layers/h3-hexagon-layer.js, test/modules/geo-layers/h3-layers.spec.js
For #3015 
- Enable `stroke` feature for H3Hexagon Layer by changing the subLayer `SolidPolygonLayer` to `PolygonLayer`.
- Required changes for the support of the new SubLayer.
=> Add stroke functionality for the H3Hexagon Layer

modules/core/src/lib/layer-manager.js
For #3039 
- Finalize all layers (will call `buffer.delete` and `model.delete`) upon Deck finalization
=> Finalize all layers

modules/core/src/lib/deck-picker.js, modules/core/src/lib/deck.js
For #https://github.com/uber/deck.gl/issues/2986
This bug is caused by overloading the `lastPickedInfo` object in DeckPicker. We used this object for two purposes:
1. Store the last hovered object for use during the next `hover` event. The `onHover` callback is only fired when the hovered object is changed.
2. Store the picked object on `pointerdown`. This object is reused for subsequent `onClick` and `onDrag*` callbacks.
This design was based on the assumption that when the pointer remains down, `pointermove` does not trigger a `hover` event, therefore the object from (2) cannot be overwritten by (1).
This becomes an issue when the user clicks and quickly moves the pointer away. The `click` event fires with a small delay to rule out double clicking. During this delay, if the pointer is …
=> Fix bug in click event handling

modules/core/src/views/orbit-view.js, modules/core/src/views/orthographic-view.js, test/modules/core/views/view.spec.js
For #3042
When we merged viewport props the `width` and `height` in `viewState` ended up overriding the values provided by the `ViewManager`.
- Use base `View` class' `_getViewport` implementation instead
=> Fix OrbitView and OrthographicView resize bug

modules/jupyter-widget/README.md, modules/jupyter-widget/package.json, modules/jupyter-widget/src/embed.js, modules/jupyter-widget/src/index.js, modules/jupyter-widget/src/plugin.js, modules/jupyter-widget/src/utils.js, modules/jupyter-widget/src/version.js, modules/jupyter-widget/src/widget.js, test/modules/jupyter-widget/index.js, test/modules/jupyter-widget/index.spec.js, test/modules/jupyter-widget/utils.spec.js
Adding a Jupyter widget for rendering deck.gl in a Python environment, building on #3013. 
See #2929.
- Adds JS module to support a Jupyter notebook extension
- Modifies `pydeck` Python library to support a Jupyter notebook extension
=> Add Jupyter widget - JS Module

modules/aggregation-layers/src/utils/gpu-grid-aggregation/aggregate-all-vs-64.glsl.js, modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.js
For #2084 
Fix issues found when enabling world space aggregation (GridLayer)
- Fix rounding issue in shader instructions when calculating domain (min/max) values.
- Fix Model creation/update when  64-bit aggregation is toggled.
- GPU Grid Aggregation PART-1: Aggregator: fix world space aggregation
=>  GPUGridLayer PART-1: Fix world space aggregation

modules/layers/src/column-layer/column-layer.js
If models are regenerated but vertices are not updated, model geometry are not correctly positioned.
=> Fix update vertices when regenerate models

docs/api-reference/react/deckgl.md, examples/layer-browser/src/app.js, examples/layer-browser/src/index.js, modules/react/src/deckgl.js, modules/react/src/utils/position-children-under-views.js
All react-map-gl control components require a React context provider rendered by the MapGL component. Currently, if we render these components outside of `StaticMap`, they crash; if we render them as children of `StaticMap`, they are not interactive, because they are stuck behind the deck.gl canvas.
This PR proposes a new prop `ContextProvider` for the `DeckGL` React component. If provided, deck will supply the React context to all child components.
- Add `ContextProvider` prop
- Add `NavigationControl` to layer-browser
=> [React] Add the ability to use react-map-gl controls

README.md, yarn.lock
Required:
- Updating the build badge
Also includes an update to the yarn.lock file, assuming this was accidentally not committed with previous checkin.
=> Migrate from travis-ci.org to travis-ci.com

scripts/bundle.config.js
For #3076
I tried to verify this but wasn't able to. Running `npm run build` doesn't seem to create the dist bundle.
=> Ensure UMD bundles are ES5

docs/layers/column-layer.md, docs/layers/h3-hexagon-layer.md, modules/geo-layers/src/h3-layers/h3-hexagon-layer.js
For #3015 
- Add `getFillColor`, `getLineColor` & `wireframe` props to ColumnLayer of H3Hexagon Layer.
- Add updated props to the docs.
- Fix ColumnLayer docs for `wireframe`.
=> Update H3Hexagon Layer docs & props for ColumnLayer

modules/core/src/lib/attribute.js, modules/core/src/lib/base-attribute.js
For #1576
- Avoid calculating buffer props unless needed
- Only upload changed subarray on attribute update
=> Prep Attribute class for partial update

modules/layers/src/column-layer/column-geometry.js, modules/layers/src/column-layer/column-layer.js, modules/layers/src/column-layer/grid-cell-layer.js
For #3015 
- Remove unused options, reduce attribute size (1/3 vertex count)
- Move custom vertices handling into `ColumnGeometry` constructor
=> Use a single model for stroke and fill in ColumnLayer

modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-layer.js, modules/aggregation-layers/src/grid-layer/grid-aggregator.js, modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.js, modules/aggregation-layers/src/utils/gpu-grid-aggregation/grid-aggregation-utils.js, test/modules/aggregation-layers/contour-layer/contour-layer.spec.js, test/modules/aggregation-layers/gpu-grid-layer/gpu-grid-layer.spec.js, test/modules/aggregation-layers/grid-layer/grid-layer.spec.js, test/modules/aggregation-layers/hexagon-layer.spec.js, test/modules/aggregation-layers/screen-grid-layer.spec.js
For #3100
- Automatic layer tests test for `empty ` and `non-iterable` data prop, `resource leaks` and other prop updates. Add these tests for all aggregation layers, `GridLayer`, `GPUGridLayer`, `HexagonLayer`, `ScreenGridLayer` and `ContourLayer`.
- Fix `non-iterable` and `empty` data prop usage for `GPUGridLayer`.
- Fix memory leak in `GPUGridLaeyr`
- Fix `non-iterable` data prop usage for `GridLayer`
- Aggregation-layers: Add unit tests, fix bugs.
=> Aggregation-layers: Add unit tests, fix bugs.

modules/mapbox/src/deck-utils.js
`MapboxLayer` was overwriting `<DeckGL>`'s `_customRender`, which handles viewport update for the child `<Map>` component.
=> Fix react integration of mapbox layers

modules/geo-layers/src/h3-layers/h3-hexagon-layer.js
The current implementation of `H3HexagonLayer` updates the instanced geometry (regenerating attributes and creating new WebGL buffers) whenever the hexagon at the center of the viewport changes. This is excessive especially at fine resolutions.
This PR introduces a distance threshold within which we consider all hexagons having the same shape. This significantly reduces the number of attribute updates needed when interacting with the viewport.
- Use the distance between the current center hex and the last center hex to determine whether geometry update is needed
=> Improve H3HexagonLayer perf

docs/layers/tile-layer.md, modules/geo-layers/src/tile-layer/utils/tile.js, modules/geo-layers/src/tile-layer/utils/viewport-util.js, test/modules/geo-layers/tile-layer/index.js, test/modules/geo-layers/tile-layer/viewport-util.spec.js
TileLayer generates invalid tile indices (e.g. `x: -1, y: -1, z: 0`) at low zoom levels.
- Fix tile index generation from viewport, add tests
- Add `bbox` to arguments when calling `getTileData` (needed by H3 hexagon lookup)
=> Fix TileLayer bug at low zoom levels

modules/core/src/lib/deck.js, modules/mapbox/src/deck-utils.js, modules/mapbox/src/mapbox-layer.js, test/apps/mapbox-layers/layers.js, test/apps/mapbox-layers/package.json
The old approach overwrote deck's `viewState` prop during render, which conflict with the props set by React, and polluted the redraw flag.
- Remove `deck.setProps` calls in the React use case
- Tested w/ React and pure JS
=> Fix view state handling in mapbox integration

docs/api-reference/attribute-manager.md, modules/core/src/lib/attribute-manager.js, modules/core/src/lib/attribute.js, modules/core/src/utils/iterable-utils.js, test/modules/core/lib/attribute.spec.js, test/modules/core/utils/index.js, test/modules/core/utils/iterable-utils.spec.js
For #1576 [RFC](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/vNext/partial-updates-rfc.md)
This is a non-breaking change -- any custom attribute updater now receive `startIndex` `endIndex` parameters. If it doesn't handle them, it would perform a full update on the attribute array just like before.
- Add optional `startIndex` `endIndex` parameters to `AttributeManager.update`
- Docs
- Unit test
- Add a test app for this feature
- Handle partial updates in core layers (e.g. `PathTesselator` and `PolygonTesselator`)
- Validate the provided range -- in path and polygon use cases, if the old and new vertex counts in the partial range do not match, partial update would corrupt the attribute array. This is less of a concern if we limit the usage to internal scenarios.
=> Add partial update support to AttributeManager

modules/aggregation-layers/package.json, modules/geo-layers/package.json, modules/google-maps/package.json, modules/json/package.json, modules/layers/package.json, modules/mapbox/package.json, modules/mesh-layers/package.json, modules/react/package.json, modules/test-utils/package.json
For https://github.com/uber/deck.gl/issues/3118
Lerna does not manage peer dependency versions.
=> Update peer dependency versions

docs/upgrade-guide.md, modules/core/src/shaderlib/project/project.glsl.js, modules/core/src/shaderlib/project/viewport-uniforms.js, test/modules/core/shaderlib/project/viewport-uniforms.spec.js
This is a breaking change if a vec3 is provided to `coordinateOrigin` while `coordinateSystem` is `COORDINATE_SYSTEM.METER_OFFSETS` or `COORDINATE_SYSTEM.LNGLAT_OFFSETS`.
`LNGLAT`, `LNGLAT_AUTO_OFFSET` and `IDENTITY` modes are not affected.
=> Fix coordinate origin z bug

modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-cell-layer-fragment.glsl.js, modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-cell-layer-vertex.glsl.js, modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-cell-layer.js, modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-layer.js, modules/aggregation-layers/src/grid-layer/grid-aggregator.js, modules/aggregation-layers/src/grid-layer/grid-layer.js, modules/aggregation-layers/src/new-grid-layer/new-grid-layer.js, modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.js, modules/aggregation-layers/src/utils/gpu-grid-aggregation/grid-aggregation-utils.js, modules/main/src/index.js, test/modules/aggregation-layers/grid-aggregator.spec.js, test/modules/core/lib/pick-layers.spec.js
For #2084 
- `GPUGridLayer` : Adding support for picking.
- `onHover` will read data from aggregated textures, will only display, `colorValue`, `elevationValue` and `count` and `position` of selected grid cell.
- For all other modes, data is aggregated on CPU (and saved in `state`). Based current selected cell `index`, corresponding `hash-key` is generated to access full aggregation results (including array of all aggregated `points`) from cpu Aggregation data.  CPU Aggregation is triggered only during picking and it is previously not calculated.
- `Picking Tests`
- Add picking tests for `NewGridLayer`, for both cpu and gpu aggregaiton paths, and results are matched.
- In addition to `pickInfo` count, update the tests to compare, number of aggregated points for each cell, results match in …
=> GPU GridLayer PART-4: Add support for picking

docs/layers/path-layer.md, examples/layer-browser/src/data-samples.js, modules/layers/src/path-layer/path-layer-vertex-64.glsl.js, modules/layers/src/path-layer/path-layer-vertex.glsl.js, modules/layers/src/path-layer/path-layer.js, test/modules/layers/path-layer/path-layer-vertex.spec.js
For #3138 
billboard: false (default)
billboard: true
This new prop is not supported in the deprecated fp64 mode.
There are precision issues at high zoom levels, will address in a follow up PR.
- Add `billboard` prop to path layer (screenspace extrusion)
- Docs
=> Add billboard mode to PathLayer

docs/layers/grid-layer.md, modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-layer.js, modules/aggregation-layers/src/grid-layer/grid-layer.js, modules/aggregation-layers/src/hexagon-layer/hexagon-layer.js, modules/aggregation-layers/src/index.js, modules/aggregation-layers/src/new-grid-layer/new-grid-layer.js, modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer.js, modules/aggregation-layers/src/utils/aggregation-operation-utils.js, modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator-constants.js, modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.js, test/modules/aggregation-layers/grid-layer/grid-layer.spec.js, test/modules/aggregation-layers/hexagon-layer.spec.js, test/modules/aggregation-layers/new-grid-layer.spec.js, test/modules/aggregation-layers/utils/gpu-grid-aggregator.spec.js, test/render/test-cases.js
For #2084
Following props are needed to perform GPU Aggregation. For parity add these props to `GridLayer` and `HexagonLayer`
- `getColorWeight`, `colorAggregation`, `getElevationWeight` and `elevationAggregation`
- Add new color/elevation props to Grid and Hexagon layers
=> GPU GridLayer PART 5: Add new color/elevation props to Grid and Hexagon layers

docs/layers/gpu-grid-layer.md, docs/layers/hexagon-layer.md, docs/layers/new-grid-layer.md, modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-cell-layer-vertex.glsl.js, modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-cell-layer.js, modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-layer.js, modules/aggregation-layers/src/new-grid-layer/new-grid-layer.js, modules/main/src/index.js, test/modules/aggregation-layers/new-grid-layer.spec.js, website/contents/pages.js, website/src/components/demos/aggregation-layer-demos.js
For #2084
- Docs:
- Update doc page for `GPUGridLayer`
- Add doc page for `NewGridLayer`
- Add sections in above docs describing differences with `GridLayer` and list all fallback cases.
- Add demos for `GPUGridLayer` and `NewGridLayer`
- GPUGridLayer
- Fix color calculation when not extruded.
- Fix color and elevation domain processing.
- NewGridLayer
- disable GPU Aggregation by default.
- Use `getSubLayerClass` method to allow customization.
- GPU GridLyer Part 6: GPUGridLayer fixes and docs.
=> GPU GridLyer Part 6: GPUGridLayer fixes and docs.

modules/core/src/passes/screen-pass.js
For #2962
Edgework effect doesn't work well because the target framebuffer is not bound correctly. Replace framebuffer.clear() with clear() function to resolve the issue
- Replace framebuffer.clear() with clear()
=> fix post-processing effect framebuffer binding bug

package.json, yarn.lock
For #3151 
We are blocked from upgrading ocular-dev-tools (which also bumps puppeteer version) due to this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=968830&q=component%3AInternals%3EHeadless
- Force bump lerna version to v3
=> Bump lerna version

docs/api-reference/deck.md, modules/core/src/lib/deck.js
Simple Deck member prop that tracks performance statistics over a 60-frame window.
=> Metrics-tracking Deck property

docs/api-reference/react/deckgl.md, examples/layer-browser/package.json, examples/layer-browser/src/app.js, modules/react/src/utils/position-children-under-views.js
- By passing `onViewStateChange` with the context, we make the viewport change callback on react-map-gl controls optional.
=> Support react-map-gl's new MapContext format

docs/api-reference/test-utils/test-layer.md, modules/layers/src/arc-layer/arc-layer.js, test/modules/layers/core-layers.spec.js
If `getSourcePosition` and `getTargetPosition` write into the same target array, the layer fails to render. (see test case)
- Fix attribute updater bug
=> Fix ArcLayer bug when using non-iterable data with pre-allocated target array

docs/layers/cpu-grid-layer.md, docs/layers/gpu-grid-layer.md, modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-layer.js, modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.js, website/contents/pages.js
For #3173 
GPUGridLayer is only supported when using `WebGL2`, add a warning to use `GridLayer` when not supported.
- GPUGridLayer: make it exclusive for WebGL2
=> GPUGridLayer: make it exclusive for WebGL2

modules/core/package.json, modules/core/src/lib/init.js, modules/core/src/shaderlib/index.js, modules/main/package.json
=> Add sideEffects field to core package.json

modules/core/package.json
For #3213 
In our bundle script, each module is resolved to source, and `src/lib/init.js` is not listed in `sideEffects`.
- Change `sideEffects` to use wildcard
=> Fix tree shaking in pre-bundled version

examples/experimental/sun/src/shadow-effect/shadow-module.js
Depth value encoding is wrong which made the shadow is not rendered correctly.
- improve depth encoding
=> improve shadow/sun example depth value encoding

docs/layers/h3-hexagon-layer.md, modules/geo-layers/src/h3-layers/h3-hexagon-layer.js, test/modules/geo-layers/h3-layers.spec.js
For #3209 
- Forward `coverage` prop to `ColumnLayer`
- Scale polygon vertices when using `PolygonLayer`.
- H3Hexagon: add support for coverage.
=> H3Hexagon: add support for coverage.

docs/api-reference/composite-layer.md, modules/core/src/lib/composite-layer.js, test/modules/core/lib/composite-layer.spec.js
For #3233 
Allow to override `updateTriggers` using `_subLayerProps`.
Add unit tests and update docs.
- CompositeLayer: add ability to override sublayer updateTriggers
=> CompositeLayer: add ability to override sublayer updateTriggers

modules/core/src/lib/deck-picker.js, modules/core/src/lib/picking/query-object.js, test/modules/core/lib/deck-picker.spec.js, test/modules/core/lib/deck.spec.js, test/modules/core/lib/index.js, test/modules/core/lib/pick-layers.spec.js
The bug: {y: 0, radius: 0} yields an invalid picking rect. This is because we are actually picking the pixel above (x, y) when `pickingRadius` is `0`.
- Fix how `getPickingRect` and `getClosestObject` handle `pickingRadius: 0`
- Tests
=> Fix picking rect calculation

test/modules/core/lib/attribute-transition-utils.spec.js, test/modules/core/lib/deck.spec.js, test/modules/core/lib/index.js, test/modules/index.js, test/modules/mapbox/index.js, test/modules/mapbox/mapbox-layer.spec.js, test/modules/react/deckgl.spec.js, test/modules/react/index.js
Now that we can construct Deck instance under Node, add tests for `DeckGL` React component and `MapboxLayer`
=> Improve unit test coverage

.prettierignore, docs/api-reference/viewport.md
There is a typo in the `viewport` api doc page which is causing a link to render as text. 
- Fix the link bracket to render the link correctly.
- add `*.md` to the `.prettierignore` to prevent prettier from ruining the docs formatting.
=> Fix missing brace on link in viewport doc

.nycrc, modules/core/package.json, ocular-dev-tools.config.js, package.json, test/bench/node.js, test/browser.js, test/modules/index.js, test/node.js, yarn.lock
- Bring dev tools up to date
- puppeteer is locked to `1.12.0` due to #3156, will unpin when Chromium 77 is released.
TODO:
- Fix bench (broken on master)
=> Upgrade ocular-dev-tools

modules/core/src/views/view.js, test/modules/core/views/view.spec.js
For #3259
If the user does not specify an id for the view, the viewport created by `makeViewport` end up with a different default id from its view.
- Force viewports to have the same id as the parent view
=> fix missing viewport id

examples/gallery/src/mapbox-layer.html, test/apps/mapbox-layers/package.json
For some reason the older versions of mapbox-gl stopped working.
- Upgrade mapbox in examples
=> Fix broken mapbox layer example

modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-cell-layer.js, modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer.js, modules/core/src/index.js, modules/core/src/lib/layer-extension.js, modules/core/src/lib/layer.js, modules/core/src/lifecycle/props.js, modules/core/src/utils/shader.js, modules/layers/src/arc-layer/arc-layer.js, modules/layers/src/bitmap-layer/bitmap-layer.js, modules/layers/src/column-layer/column-layer.js, modules/layers/src/icon-layer/icon-layer.js, modules/layers/src/line-layer/line-layer.js, modules/layers/src/path-layer/path-layer.js, modules/layers/src/point-cloud-layer/point-cloud-layer.js, modules/layers/src/scatterplot-layer/scatterplot-layer.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer.js, modules/main/src/index.js, modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js, test/modules/core/lib/index.js, test/modules/core/lib/layer-extension.spec.js, test/modules/core/utils/shader.spec.js, test/modules/extensions/data-filter.spec.js, test/modules/extensions/index.js
[RFC](https://github.com/uber/deck.gl/blob/fe927512b171618746e566744a7b173039ee883f/dev-docs/RFCs/vNext/layer-extension-rfc.md)
- Add `LayerExtensions` interface
- Handle `extensions` prop in base Layer class: lifecycle callbacks, `extensionsChanged` flag
- Update all layers to use new `getShaders` API
- Tests
=> Implement layer extensions RFC

docs/api-reference/composite-layer.md, docs/developer-guide/custom-layers/composite-layers.md, modules/core/src/lib/composite-layer.js, modules/core/src/lib/layer-extension.js, modules/geo-layers/src/h3-layers/h3-cluster-layer.js, modules/layers/src/geojson-layer/geojson-layer.js, modules/layers/src/geojson-layer/geojson.js, modules/layers/src/polygon-layer/polygon-layer.js, modules/layers/src/text-layer/text-layer.js, test/modules/core/utils/typed-array-manager.spec.js, test/modules/layers/geojson.spec.js
Follow up of comments in https://github.com/uber/deck.gl/pull/3307
- Add `getSubLayerDatum` and `getSubLayerAccessor` methods to `CompositeLayer`
- Update `GeoJsonLayer`, `PolygonLayer`, `TextLayer` and `H3ClusterLayer` to use the new API
=> Formal API for CompositeLayer data/accessor wrapping

modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
Pull `SolidPolygonLayer` change from https://github.com/uber/deck.gl/pull/3306 into 7.1-release.
For kepler.gl's data filter implementation.
- Add `NON_INSTANCED_MODEL` define to `SolidPolygonLayer` shader
=> add NON_INSTANCED_MODEL define

examples/website/point-cloud/app.js, modules/core/src/lib/attribute-manager.js, modules/core/src/lib/attribute.js, modules/layers/src/point-cloud-layer/point-cloud-layer.js, test/modules/core/lib/attribute.spec.js, test/modules/layers/index.js, test/modules/layers/point-cloud-layer.spec.js
For [RFC](https://github.com/uber/deck.gl/blob/c21a75a428d5126dab7d4f89af21b5f67916203e/dev-docs/RFCs/v7.x/data-loading-rfc.md)
- Add `onDataLoad` callback (needs audit)
- In addition to `Buffer` and typed array, `Attribute` class supports externally provided attribute descriptors (`{value, size, stride, ...}`)
- `AttributeManager` supports external buffers provided via `data.attributes`.
=> Support loaders.gl data attributes

modules/core/src/lifecycle/component-state.js, modules/core/src/lifecycle/props.js, test/bench/compare-props.bench.js, test/modules/core/lifecycle/props.spec.js
Our `props` object is created by inheriting the `defaultProps` object (one per `Layer` class), and then assign user-specified values on top. Currently, we compare two props objects by iterating through all key-value pairs, including the default prop values even if they are not supplied by the user. This PR switches to only examining the props explicitly set by the user.
Before:
├─ compareProps#empty: 65.1K iterations/s ±7.02%
├─ compareProps#real world sample: 55.6K iterations/s ±7.31%
After:
├─ compareProps#empty: 15.2M iterations/s ±0.92%
├─ compareProps#real world sample: 1.08M iterations/s ±1.23%
- `compareProps` util
- Creation of `oldProps` object when an async prop is loaded
- Benchmark and unit tests
=> Improve prop comparison perf

docs/api-reference/layer.md, modules/core/src/lib/layer.js, modules/core/src/shaderlib/index.js, modules/layers/src/arc-layer/arc-layer.js, modules/layers/src/column-layer/column-layer.js, modules/layers/src/icon-layer/icon-layer.js, modules/layers/src/line-layer/line-layer.js, modules/layers/src/path-layer/path-layer.js, modules/layers/src/point-cloud-layer/point-cloud-layer.js, modules/layers/src/polygon-layer/polygon-layer.js, modules/layers/src/scatterplot-layer/scatterplot-layer.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer.js, modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js, modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js
For #3197 
There is a small save on resources, but this is most useful when using external buffers.
- Add `colorFormat` prop
- Fix `positionFormat` support in `PolygonLayer`
=> Add support for RGB color format

modules/core/src/lib/attribute.js, modules/layers/src/bitmap-layer/bitmap-layer.js, test/modules/core/lib/attribute.spec.js
- Fix a bug where `Attribute.allocate` may skip allocation if previously set external buffer or constant value is large enough
- Make BitmapLayer attributes use pre-allocated typed arrays
- Unit tests
=> Attribute allocation bug fixes

dev-docs/RFCs/v7.x/shadow-for-directional-lights.md
=> shadow effect RFC

docs/layers/tile-layer.md, examples/website/map-tile/package.json, modules/geo-layers/src/tile-layer/utils/tile.js
For #2987 
`Tile.data` wraps resolved data in a new promise which prevents it from being rendered immediately.
- Fix tile flashing
- Support synchronous `getTileData`
=> Fix TileLayer flashing

examples/website/plot/plot-layer/axes-layer.js, modules/aggregation-layers/src/heatmap-layer/heatmap-layer.js, modules/core/src/lib/layer.js, modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js
- Breaking change in `layer.updateAttributes` (this is currently considered private API) - separate `AttributeManager` update, which all layers need, from `model.setAttributes` calls, which some layers may want to override.
- Update ScenegraphLayer
- Update plot example
=> Simplify `layer.updateAttributes` override

docs/layers/heatmap-layer.md, modules/aggregation-layers/src/heatmap-layer/heatmap-layer-utils.js, modules/aggregation-layers/src/heatmap-layer/heatmap-layer.js, modules/aggregation-layers/src/heatmap-layer/triangle-layer.js, test/modules/aggregation-layers/heatmap-layer/heatmap-layer-utils.spec.js, test/modules/aggregation-layers/heatmap-layer/heatmap-layer.spec.js
- Only render the quad of visible pixels
- Flatten bounds object
- More efficient attribute updates (reuse typed array and `subData` instead of `setData`)
=> HeatmapLayer minor optimizations

modules/core/package.json, modules/core/src/lib/deck.js, modules/core/src/lib/index.js, modules/core/src/lib/init.js, modules/core/src/shaderlib/index.js
Per discussion in #3213, `sideEffects` is not sufficient to prevent tree shaking in some use cases.
- Wrap global registration in a function
Tested with build-bundle script.
=> Remove side effects from core module

examples/layer-browser/src/app.js, examples/layer-browser/src/index.js, examples/layer-browser/src/map.js, examples/layer-browser/src/render-metrics.js, examples/layer-browser/src/render-stats.js
- Display stats from `Deck.metrics` on screen in the layer browser. Currently displaying FPS, GPU frame time, CPU frame time and GPU memory. Can easily add more layer.
- Add an option to cause the camera to randomly shake to ensure rendering occurs every frame.
- Remove old FPS stats display from layer browser.
=> Display rendering stats in layer browser

modules/layers/src/path-layer/path-layer-vertex.glsl.js, test/modules/core/lib/pick-layers.spec.js, website/src/static/workers/trips-data-decoder.js
For #3396 
In https://github.com/uber/deck.gl/pull/3211/files#diff-f1f8e62816742b25869f5b5a7c79e7cfR150 we removed the check for very small neighbor segments, and replaced it with explicit end cap flags. Although this reduced ambiguity for end caps, when a path contains two adjacent identical points, the shader produces a big joint triangle which kills rasterization.
This was not caught in testing because we have clean data in layer-browser/render tests. The trips demo has a bug that produces duplicate vertices at navigation points.
- Restore check for neighbor size
- Fix trips demo data decoder
=> Fix PathLayer/trips demo perf regression

docs/layers/README.md, examples/website/heatmap-layer/app.js, modules/aggregation-layers/src/heatmap-layer/heatmap-layer.js, website/src/components/demos/aggregation-layer-demos.js
For #3396 
- HeatmapLayer: disable resource setup when using `WebGL1` context to avoid crash (Safari)
- Docs: Add HeatmapLayer entry to layer overview doc.
- Example: display error text when not supported to avoid confusion. (Safari)
- HeatmapLayer: website testing fixes
=> HeatmapLayer: website testing fixes

modules/core/src/lib/attribute-transition-manager.js, modules/layers/src/path-layer/path-tesselator.js, test/modules/layers/path-tesselator.spec.js
For #3396 
- Fix crashing bug in `PathTesselator` when a path consists of two identical points; add test case
- Fix `AttributeTransitionManager` handling of normalized attributes
=> Fix highway safety demo bugs

modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer.js, modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.js
For #3396 
When running website demo, data is not loaded immidetely and aggregation is performed with 0 vertex count, causing following warnings:
`[.WebGL-0x7fef75911400]RENDER WARNING: Render count or primcount is 0.`
Skip aggregation when there is no data.
- ScreenGridLayer: skip aggregation when data is empty
=> ScreenGridLayer: skip aggregation when data is empty

examples/website/map-tile/app.js, modules/core/package.json, modules/core/src/lib/init.js, modules/layers/package.json, modules/layers/src/bitmap-layer/bitmap-layer.js, modules/layers/src/icon-layer/icon-manager.js, test/modules/layers/core-layers.spec.js, yarn.lock
- Use `ImageLoader` instead of `HTMLImageLoader` (web worker compatible)
- Support `ImageBitmap` in `IconManager` and `BitmapLayer`
=> Upgrade to loaders.gl@1.2.0

website/webpack.config.js
The default path loads ES6 code into the bundle.
=> Website reference ES5 transpiled version of supercluster dependency

modules/core/src/lib/init.js
For https://github.com/uber/deck.gl/issues/3436
Revert back to HTMLImageLoader for now to unblock. In the long term:
- loaders.gl should detect browser support before using `options` in `createImageBitmap`
- To remove the need for `flipY` option in `createImageBitmap`, we need to flip all textures by setting `unpackFlipY: false` for `Texture2D` (only works for DOM elements as data source) and update the shaders. This will be a breaking change. We may also want to introduce a layer prop to revert the behavior.
- Fix texture loading in FF
=> Use HTMLImageLoader for browser compatibility

modules/json/src/parsers/convert-json.js, test/modules/json/json-converter.spec.js
For #2929 
This helps support additional alerting for pydeck and warns a user if a layer name passed is invalid
- Add warning to json converter
=> Add warnings for invalid layer types in JSONConverter

modules/aggregation-layers/src/hexagon-layer/hexagon-aggregator.js, test/modules/aggregation-layers/hexagon-aggregator.spec.js
For #2929 and #3079
Hexbin aggregation has been failing in pydeck in 7.2.
This is also causing an issue in the JSON browser demo.
This PR gives a useful error without blocking rendering.
=> Fail gracefully in the event of a hexbin projection error

docs/upgrade-guide.md, modules/core/src/lib/composite-layer.js, modules/core/src/lib/layer-manager.js, modules/core/src/lib/layer.js, test/modules/core/lib/composite-layer.spec.js
Current behavior:
If `setState` is called inside of a composite layer, a full update is triggered on `layerManager` but sublayer props are not updated. This is because `shouldUpdateState` by default returns `false` on just state change.
Expected behavior:
If `setState` is called inside of a composite layer, `compositeLayer.renderLayers()` should be called to "redraw" sublayers.
- update composite layers on state change
- rename `setLayerNeedsUpdate` to `setNeedsUpdate` to align with other classes
- add tests
=> Composite layer should rerender when state updates

examples/website/mesh/app.js, modules/core/src/effects/lighting/lighting-effect.js, modules/core/src/shaderlib/shadow/shadow.js, test/modules/core/effects/lighting-effect.spec.js, test/modules/core/shaderlib/shadow/shadow.spec.js
Mesh layer has a sampler which blocks the binding of shadow map sampler array. Because of that the shadow map texture sampling always returns [0, 0, 0, 0]. Made the full mesh layer rendered with shadow.
- fix the shadow map sampler issue
- new bounding box for identity mode
- add shadow to mesh example
- unit test
=> Improve shadow for mesh layer

docs/api-reference/attribute-manager.md, modules/core/src/index.js, modules/core/src/lib/attribute-manager.js, modules/core/src/lib/attribute.js, modules/core/src/utils/math-utils.js, modules/layers/src/arc-layer/arc-layer.js, modules/layers/src/column-layer/column-layer.js, modules/layers/src/icon-layer/icon-layer.js, modules/layers/src/icon-layer/icon-manager.js, modules/layers/src/line-layer/line-layer.js, modules/layers/src/point-cloud-layer/point-cloud-layer.js, modules/layers/src/scatterplot-layer/scatterplot-layer.js, modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer.js, modules/main/src/index.js, modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js, modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js, test/modules/core/lib/attribute-manager.spec.js, test/modules/core/lib/attribute.spec.js, yarn.lock
Since we introduced the partial update feature, it has become increasingly complex for layers to implement their own attribute updaters.
This PR removes the need for a custom updater of the `instancePositions64xyLow` attribute, and will also make it easier when we move to use 3d 64-bit positions in the next major release.
- Add `enable` and `transform` options to `Attribute` class
- Add new core utility `positionFp64LowPart`
- Update primitive layers to use the new API
- Unit tests
=> Add transform and enable options to attribute class

examples/website/geojson/app.js
Date format in firefox is not very flexible, made the new Date() API returns invalid result. 
- fix  the date format issue
=> fix firefox invalid date

modules/core/src/lib/attribute.js, test/modules/core/lib/attribute-manager.spec.js, test/modules/core/lib/attribute.spec.js
For #3447 
- Only cast external buffer array type if necessary
- Allow `attribute.type` to be overwritten
=> Relax restrictions for external buffers

docs/contributing.md
- compile `for await` in `lifecycle/component-state` requires minimum Node 10.x
Signed-off-by: Shan He <heshan0131@gmail.com>
=> update node requirement to 10.x

docs/api-reference/attribute-manager.md, examples/webpack.config.local.js, modules/core/package.json, modules/core/src/lib/attribute.js, modules/jupyter-widget/package.json, modules/layers/src/arc-layer/arc-layer.js, modules/layers/src/bitmap-layer/bitmap-layer.js, modules/layers/src/column-layer/column-layer.js, modules/layers/src/icon-layer/icon-layer.js, modules/layers/src/line-layer/line-layer.js, modules/layers/src/path-layer/path-layer.js, modules/layers/src/point-cloud-layer/point-cloud-layer.js, modules/layers/src/scatterplot-layer/scatterplot-layer.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer.js, modules/mesh-layers/package.json, modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js, modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js, package.json, test/modules/core/lib/attribute.spec.js, yarn.lock
Follow up of #3468 
- Bump luma.gl dependencies
- Remove `doublePrecision` option, use `type: GL.DOUBLE`
=> Attribute: use `type: GL.DOUBLE` for double precision

dev-docs/RFCs/README.md, dev-docs/RFCs/vNext/component-wrapping-rfc.md
For #2929 
- By popular demand: As part of the push to unify ongoing Jupyter Notebook integration efforts, I was asked to write up a summary of current ideas around a common JS component to handle wrapping (registration and basic plumbing) of components to be exposed in non-JS environments)
- New RFC
=> RFC: Component Wrapping System

modules/core/src/controllers/orbit-controller.js
The change was introduced in https://github.com/uber/deck.gl/commit/0bb6dc992b7dde5b83a692571c15a5bab43b8038 it breaks the `rotationOrbit` transition in the point cloud example.
- Remove orbit controller rotation normalization for now
=> Remove orbit controller rotation normalization

modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer-fragment.glsl.js, modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer-fragment.glsl1.js, modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js
SimpleMeshLayer is completely unimpressed by changes to its opacity value. This change makes the layer transparent when the opacity is <1.0.
Possible problem: The default layer opacity is 0.8 but SimpleMeshLayer was always rendered as if it was 1.0. It might be a good idea to set the default opacity of SimpleMeshLayer to 1.0 so existing implementations don't experience sudden transparency. On the other hand this would introduce inconsistency, so I will leave this topic to the experts.
- Multiplying opacity value with existing alpha channel value in SimpleMeshLayers fragment shaders.
=> Respect layer opacity in SimpleMeshLayer

modules/core/src/controllers/controller.js, modules/core/src/controllers/transition-manager.js, modules/core/src/lib/attribute-manager.js, modules/core/src/lib/attribute-transition-manager.js, modules/core/src/lib/deck.js, modules/core/src/lib/layer-manager.js, modules/core/src/lib/layer.js, modules/core/src/lib/uniform-transition-manager.js, modules/core/src/lib/view-manager.js, modules/core/src/transitions/transition.js, test/modules/core/controllers/test-controller.js, test/modules/core/lib/attribute-transition-manager.spec.js, test/modules/core/lib/transition-manager.spec.js, test/modules/core/transitions/transition.spec.js
- Use deck's timeline in `AttributeTransitionManager` and (viewstate) `TransitionManager`, remove dependence on `AnimationProps`
- Use `Transition` class to manage timeline channels
- Tests
=> Transition system refactor (1/2): use timeline

test/size/import-nothing.js
Bundle size reporting was "broken" (all 1KB) after #3395 
- Export non-trivial component in metrics
=> Produce more meaningful metrics

dev-docs/README.md, dev-docs/code-guidelines.md, dev-docs/deckgl-api-guidelines.md, docs/api-reference/composite-layer.md, docs/api-reference/first-person-view.md, docs/api-reference/layer.md, docs/api-reference/view.md, docs/api-reference/web-mercator-viewport.md, docs/contributing.md
Upgrade Guide link in Dev Docs readme should point to correct url.
- Fix typos and broken links in docs
=> Fix typos and broken links in the docs

examples/layer-browser/src/examples/additional-layers.js
close #3525
For #3525
GPUGridLayer crashes when used with GridLayer as both the layers are given same id from `GRID_LAYER_PROPS` object.
- Made different objects to provide props with different id to each layer
=> Fix GPUGridLayer crash when used with GridLayer

modules/geo-layers/src/h3-layers/h3-hexagon-layer.js, modules/test-utils/src/generate-layer-tests.js, modules/test-utils/src/lifecycle-test.js, test/modules/layers/core-layers.spec.js, test/modules/layers/geojson-layer.spec.js
- Make updateTrigger tests with `generateLayerTests`
- Fix an issue in `testLayers` where non-incremental prop update is not respected
- Remove unsupported `getLineDashArray` from `H3HexagonLayer`'s default props
=> Add update trigger tests to generated tests

modules/core/src/lifecycle/component-state.js, modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer.js, test/modules/json/json-converter.spec.js, test/modules/json/json-layer.spec.js
- Fix: uncaught promise error in `ComponentState` when `layer` is not set
- Fix: MultiIconLayer `getAnchorX` and `getAnchorY` update trigger warnings
- Fix: json module test case deprecated prop warning
- Fix: json module test case duplicate layer id warning
=> Misc test error/warning fixes

website/src/components/demos/layer-demos.js, website/src/utils/layer-params.js
Fix #3541
ColumnLayer's `elevationScale` in the documentation is set to `5000` initially, but the input range have a default max value of `100`, so it does not move beyond 100 once changed from the initial state.
Here, I pass a `max` prop to input field with value equal to `5000` .
=> Fix ColumnLayer elevationScale example

test/apps/viewport-transitions-flyTo/package.json, test/apps/viewport-transitions-flyTo/webpack.config.js
Close #3555
Viewport Transitions FlyTo example webpack is configured incorrectly. Hence, the example is not running.
- Updated dependencies in `package.json`
- Created `webpack.config.js` for Webpack 4
=> Fix/Viewport Transitions FlyTo webpack config

dev-docs/RFCs/v7.x/spring-based-transitions-rfc.md
This is the first pass at the RFC for supporting spring-based transitions in DeckGL attributes.
=> spring-based-transitions draft

modules/aggregation-layers/src/heatmap-layer/heatmap-layer.js, modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.js
For #3480 
Requires: https://github.com/uber/luma.gl/pull/1210
Fix `feature` checking in Heatmap Layer and GPUGridAggregator.
- HeatmapLayer/GPUAggregator: fix WebGL feature checking
=> HeatmapLayer/GPUAggregator: fix WebGL feature checking

examples/experimental/json-browser/app.js, examples/experimental/json-browser/config/templates.js, examples/experimental/json-examples/3d-heatmap-minimap.json
For #3557
- New example that uses declarative view api to set up minimap
@Pessimistress 	
- I get this working to 95% but still an issue where the view stats snaps back... 
- maybe you can help me assess if there is a way to fix this with current API, if this is a bug, or if we'd need to make changes to make this work.
=> json: minimap as pure json example

modules/core/src/lib/attribute-transition-manager.js, modules/core/src/lib/attribute-transition-utils.js, modules/core/src/transitions/gpu-interpolation-transition.js, modules/core/src/transitions/gpu-spring-transition.js, test/apps/attribute-transition/app.js, test/apps/attribute-transition/data-generator.js, test/modules/core/lib/attribute-transition-manager.spec.js
This PR is the first pass at implementing spring transitions for attributes. In the process, I've refactored the `GPUInterpolationTransition` class to simplify it and bring it in line with the new `GPUSpringTransition` class (please see [this comment](https://github.com/uber/deck.gl/pull/3530#issuecomment-530472320) regarding the resulting duplicated code). I've also made some changes to the attribute transition test app to incorporate the new spring transition types.
This PR does not implement spring transitions for uniforms. Also, because the spring transition takes an unscaled step every time the transform is run, it is not currently affected by the application's `Timeline` (we plan to address this in a follow-up). Finally, the `onStart` and `onEnd` events are not yet implemented for …
=> attribute spring transition

modules/core/bundle/index.js
Users of the pre-bundled version of deck.gl, e.g. the jupyter-widget module, cannot register their own loaders to use with the built-in async loading system. This is because loaders.gl has one global registry per `loaders.gl/core` copy, and the copy that is pre-bundled with `@deck.gl/core` is not exposed.
- Expose loaders core utilities from the copy that is bundled with deck.
=> Expose loaders.gl endpoints from the core bundle

docs/layers/icon-layer.md, modules/layers/src/icon-layer/icon-layer-fragment.glsl.js, modules/layers/src/icon-layer/icon-layer.js, modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer-fragment.glsl.js
For https://github.com/uber/deck.gl/issues/3178#issuecomment-524427608
@danmarshall We cannot make the `TextLayer` background default pickable in a minor release, as it would be a breaking change. However, you will be able to achieve the effect using
```js
new TextLayer({
// ...
_subLayerProps: {
characters: {alphaCutoff: 0}
}
});
```
- Add `alphaCutoff` prop to IconLayer
=> Add alphaCutoff prop to IconLayer

docs/api-reference/deck.md, modules/core/src/effects/lighting/lighting-effect.js, modules/core/src/lib/deck-picker.js, modules/core/src/lib/deck-renderer.js, modules/core/src/lib/deck.js, modules/core/src/lib/layer-manager.js, modules/core/src/passes/layers-pass.js, modules/core/src/passes/pick-layers-pass.js, modules/core/src/passes/shadow-pass.js
For #
- Updated docs for `useDevicePixels` prop
- minor clean up of un used `useDevicePixels` prop on `LayerManager`
- Compute pixel ratio for each frame, instead of using cached value.
- useDevicePixels docs, minor cleanup
- Calculate device pixel ratio on every frame.
=> Fix pixel ratio calculation, update docs

modules/aggregation-layers/src/utils/cpu-aggregator.js
pickingInfo.object has a null elevationValue in the current deck.gl
beta.
To reproduce, you can add the following `onHover` parameter in
`deck.gl/examples/playground/src/deck-with-maps.js` and look at the
console output:
```
return (
<DeckGL
id="json-deck"
{...this.props}
viewState={viewState}
onHover={x => (x.picked ? console.log(x.object) : null)}
onViewStateChange={this._onViewStateChange}
>
```
HexagonLayers were returning `undefined` keys in tooltips in pydeck–this change should fix that.
- Add pickingInfo name to CPU aggregator output
=> Fix bug that makes undefined key appear in aggregate layer pickingInfo

modules/core/package.json, modules/geo-layers/package.json, modules/mesh-layers/package.json, modules/test-utils/package.json, package.json, test/modules/core/lib/deck.spec.js, yarn.lock
For #3591 
@tsherif @1chandu The singled out test in deck.spec.js is broken in headless GL (browser test passes). The device rect calculation is correct. Picked color is always `[0, 0, 0, 0]`,
=> Bump dependency versions

modules/core/src/controllers/transition-manager.js, modules/core/src/lib/attribute-transition-manager.js, modules/core/src/lib/attribute-transition-utils.js, modules/core/src/lib/uniform-transition-manager.js, modules/core/src/transitions/cpu-interpolation-transition.js, modules/core/src/transitions/cpu-spring-transition.js, modules/core/src/transitions/gpu-interpolation-transition.js, modules/core/src/transitions/gpu-spring-transition.js, modules/core/src/transitions/transition.js, test/modules/core/transitions/transition.spec.js
For #3574 
Broken due to default callbacks removed from `normalizeTransitionSettings` in #3621 
- Generalize `Transition` class, remove `duration` and `easing` references
- Store transition settings in dedicated object in `Transition` instance
- Add `end` method to `Transition`
- Use `Transition` class to handle callbacks in `GPUSpringTransition`
- Align code style in `GPUSpringTransition` and `GPUInterpolationTransition`
=> Fix GPUSpringTransition

bindings/python/pydeck/examples/02 - Scatterplots.ipynb, bindings/python/pydeck/examples/03 - Using pydeck to manipulate data.ipynb
=> Add additional notebook examples for pydeck

docs/api-reference/layer.md
Adding spring transition info to transition docs. I get the feeling that at some point maybe we should offer some explanation on the differences between `interpolation` and `spring` types?
Addresses a blocker in [this list of spring-transition follow-ups](https://github.com/uber/deck.gl/issues/3574).
=> Update transition docs with spring info

modules/core/src/transitions/gpu-spring-transition.js, test/apps/attribute-transition/app.js
This PR adds an `isTransitioning` check to spring-transitions and implements the `onStart`, `onInterrupt`, and `onEnd` events using the `isTransitioning` check. (This is one of the blockers listed in this issue: https://github.com/uber/deck.gl/issues/3574)
It accomplishes this by having each transitioning value render an `isTransitioning` flag to a 1x1 fragment. The fragments are blended, taking the max value, and if the resulting pixel has a value greater than `0`, at least one of the transitions is still in progress.
I'd like to flag a concern here about scalability. This has not been tried with millions of values, yet, though, so I wonder if the blend step is performant enough to be run on every frame for those types of numbers.
=> Implement isTransitioning check for attribute spring-transitions

examples/layer-browser/src/app.js, examples/layer-browser/src/map.js
This was broken in the last layer browser refactor.
- Restore multi depth pick functionality
=> Restore multi depth pick in layer browser

modules/core/src/lib/layer.js
For https://github.com/uber/nebula.gl/issues/275
`attribute.value` may be internally allocated or externally provided. Prior to 7.2, the class did not track the distinction, so if an external typed array is used and then `attribute.updateBuffer` is called, the external typed array will be mutated. This bug was fixed in 7.2.
In multi-depth picking, we:
- Make a copy of the original picking colors
- Mutate the picking colors (allocated typed array)
- Restore the original picking colors (external buffer)
If later `data` changes and `pickingColors` need update again, this external buffer is discarded, and the allocated buffer with the mutated values is put in use again.
This was not caught in any tests because neither the layer browser or the picking tests change the data after performing …
=> Fix multi-picking bug

modules/core/src/lib/attribute-transition-manager.js
This makes sure we remove existing attribute transitions that now have `null` settings as a result of new transition settings being applied.
=> Remove attribute-transitions that have null settings

modules/core/src/lib/attribute-transition-manager.js, modules/core/src/transitions/gpu-interpolation-transition.js, modules/core/src/transitions/gpu-spring-transition.js
For #3574 
- GPU transition classes: Rename `isTransitioning()` to `inProgress`, remove `getTransitioningAttribute()`
- Do not throw with `duration:0`
- Improve minification
=> Clean up transition classes, avoid crash with `duration:0`

modules/aggregation-layers/src/heatmap-layer/heatmap-layer.js, modules/aggregation-layers/src/heatmap-layer/max-vs.glsl.js
`HeatmapLayer` only uses `Texture` API of `Transform` class and doesn't write to `Buffers`, hence doesn't need `Transform Feedback` which is WebGL2 only. Recent [refactor ](https://github.com/uber/luma.gl/pull/1221)of Transform class , doesn't check for WebGL2 for texture processing. Made following changes to enable `HeatmapLayer` for on `WebGL1`.
- Remove `WebGL2` requirement
- Remove checking for features that are implictly enabled when `FEATURES.TEXTURE_FLOAT` (`OES_texture_float`) is supported.
- Update shaders to use WebGL1 (GLSL 100) syntax.
HeatmapLayer example on Mac + Safari:
=> HeatmpaLayer: update required features for WebGL1 support.

docs/layers/gpu-grid-layer.md, modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-layer.js, modules/aggregation-layers/src/utils/gpu-grid-aggregation/grid-aggregation-utils.js
Fix #3534
GPU Grid Layer currently doesn't handles the case when cell size is zero. Hence, some variables get `Infinity` or `NaN` values.
=> Fix GPUGridLayer unhandled cellsize

modules/core/src/lib/layer.js, test/modules/core/lib/layer.spec.js
Follow up of #3652 
The `instancePickingColor` updater used to check the first element of the picking color array as an indicator whether the array has been populated. In 7.2 we start to over-allocate and reuse typed arrays, so this approach is no longer valid.
- Always set the picking colors array
- Support partial update
=> More picking bug fix

modules/core/src/lib/attribute.js, modules/core/src/lib/deck-picker.js, modules/core/src/lib/layer.js, modules/layers/src/path-layer/path-layer.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer.js, test/modules/core/lib/layer.spec.js
- Use `buffer.subData` in `clearPickingColor` instead of mutating the cached array. This also eliminates the need for `copyPickingColors`.
- Promote `attribute.getVertexOffset` to a public method
- Consolidate special-case handling in `PathLayer` and `SolidPolygonLayer`
=> Improve multi-picking performance

docs/layers/s2-layer.md, scripts/bundle.config.js
The s2-geometry lib contains a `require` so it's not usable via a script tag.
This change adds dependency to a specific service, which is not ideal. On the up side, it does not affect anyone who's not using S2Layer with the pre-bundled version.
- Support https://bundle.run with bundle config.
- Update example for using S2Layer from pre-built bundles.
=> Fix S2Layer bundle dependency

modules/aggregation-layers/bundle.js, modules/core/package.json, modules/geo-layers/package.json, modules/layers/package.json, modules/main/bundle.js, yarn.lock
- Merge `experimental` exports from core and aggregation-layers
- Bump loaders.gl to fix `Buffer is undefined` error, see https://github.com/uber-web/loaders.gl/pull/422
=> Fix bugs in pre-bundled version

examples/experimental/sun/src/app.js, examples/website/arc/app.js, examples/website/geojson/app.js, examples/website/heatmap/app.js, examples/website/highway/app.js, examples/website/icon/app.js, examples/website/icon/icon-cluster-layer.js, examples/website/line/app.js, examples/website/map-tile/app.js, examples/website/mesh/app.js, examples/website/plot/app.js, examples/website/plot/plot-layer/axes-layer.js, examples/website/plot/plot-layer/plot-layer.js, examples/website/plot/plot-layer/surface-layer.js, examples/website/point-cloud/app.js, examples/website/scatterplot/app.js, examples/website/screen-grid/app.js, examples/website/tagmap/app.js, examples/website/tagmap/tagmap-layer/README.md, examples/website/tagmap/tagmap-layer/tagmap-layer.js, examples/website/text-layer/app.js, website/src/components/demos/layer-demo-base.js, website/src/s2-geometry.js, website/src/static/index.html, website/webpack.config.js
**FOR DISCUSSION**
Requires publishing #3672 and #3674.
Pros:
- Website bundle 5.6M -> 3.2M
- We do not have to republish the website if a bug is fixed in the libraries.
- This helps verify the validity of the pre-bundled version.
Cons:
- Complicate the website setup and potentially harder to debug.
- Production build of the website includes deck, luma, mapboxgl, h3-js, and highlight.js from CDN.
- Avoid using `import DeckGL from 'deck.gl'` in examples.
=> Split website bundle

docs/developer-guide/custom-layers/writing-shaders.md
Simple one line change to the docs.
=> Fix typo in shader documentation

modules/core/src/lib/composite-layer.js, test/modules/core/lib/composite-layer.spec.js
For #3671
- Wrap overriding accessors
- Tests
=> Wrap accessors passed in subLayerProps

bindings/python/pydeck/docs/layer.md
=> Update pydeck layer docs

modules/core/src/lib/attribute.js, modules/layers/src/arc-layer/arc-layer.js, modules/layers/src/bitmap-layer/bitmap-layer.js, modules/layers/src/column-layer/column-layer.js, modules/layers/src/icon-layer/icon-layer.js, modules/layers/src/line-layer/line-layer.js, modules/layers/src/path-layer/path-layer.js, modules/layers/src/point-cloud-layer/point-cloud-layer.js, modules/layers/src/scatterplot-layer/scatterplot-layer.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer.js, modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js, modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js, test/modules/core/lib/attribute.spec.js
Fixes Tile3DLayer rendering in Safari.
When using `COORDINATE_SYSTEM.METER_OFFSETS`, the positions attributes are assigned `type: GL.FLOAT`, so no 64xyLow attributes are generated. This seems to be fine in most of the cases, but some layers in Safari have the `positions64xyLow` attribute compiled to location 0, which cannot be disabled.
The fix is to always mark the positions attributes as `type: GL.DOUBLE`, but change their default allocation type to `GL.FLOAT` when high precision is not required. This way we always define the 64xyLow attributes, and there is no perf hit when auto-packing meter offset positions.
As a side effect, this change will also allow external `Float64Array` supplied to positions attributes in the meter offset coordinate system.
- Add optional `fp64` flag to …
=> Always generate 64xyLow attributes for positions

package.json
This was broken when lerna stopped bumping root package version.
=> Fix inlined version in published package

docs/layers/heatmap-layer.md, docs/whats-new.md, examples/website/heatmap/app.js, modules/aggregation-layers/src/heatmap-layer/heatmap-layer.js, modules/aggregation-layers/src/heatmap-layer/triangle-layer-fragment.glsl.js, modules/aggregation-layers/src/heatmap-layer/triangle-layer-vertex.glsl.js, modules/aggregation-layers/src/heatmap-layer/triangle-layer.js, website/src/components/demos/heatmap-demo.js
For #3591 & #3554 
- Add `weightDomain` prop to specify custom domain range, this is a required as workaround due to ANGLE issues (#3554)
- Docs:
- Remove `Experimental`
- Remove restriction of `WebGL2`
- Document new prop.
- Update whats-new
-
=> HeatmapLayer: Add 'colorDomain' prop

docs/developer-guide/custom-layers/writing-shaders.md, modules/core/src/shaderlib/index.js, modules/core/src/shaderlib/misc/geometry.js, modules/core/src/shaderlib/picking/picking.js, modules/geo-layers/src/great-circle-layer/great-circle-vertex.glsl.js, modules/layers/src/arc-layer/arc-layer-vertex.glsl.js, modules/layers/src/bitmap-layer/bitmap-layer-vertex.js, modules/layers/src/column-layer/column-layer-vertex.glsl.js, modules/layers/src/icon-layer/icon-layer-vertex.glsl.js, modules/layers/src/line-layer/line-layer-vertex.glsl.js, modules/layers/src/path-layer/path-layer-vertex.glsl.js, modules/layers/src/point-cloud-layer/point-cloud-layer-vertex.glsl.js, modules/layers/src/scatterplot-layer/scatterplot-layer-vertex.glsl.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer-vertex-main.glsl.js, modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer-vertex.glsl.js, modules/mesh-layers/src/scenegraph-layer/scenegraph-layer-vertex.glsl.js, modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer-vertex.glsl.js, modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer-vertex.glsl1.js
For #3719
This change removes picking module-specific calls from individual shaders. This is in preparation of adding more sophisticated picking logic.
- Add `pickingColor` to `geometry` struct
- Remove `picking_setPickingColor` calls from layer vertex shaders.
=> Consolidate picking injection

docs/api-reference/deck.md, examples/layer-browser/src/app.js, modules/core/package.json, modules/core/src/lib/deck-picker.js, modules/core/src/lib/deck.js, modules/core/src/lib/picking/pick-info.js, modules/core/src/lib/picking/query-object.js, modules/core/src/passes/pick-layers-pass.js, modules/core/src/shaderlib/picking/picking.js, modules/mesh-layers/package.json, package.json, yarn.lock
For #3719
Requires https://github.com/uber/luma.gl/pull/1268
This PR demonstrates that by adding a new render pass (a variation of the picking pass) we can retrieve the accurate world position of the picked fragment.
The additional pass is performed after the regular picking pass, when the picking info is processed. It draws the picked layer into the picked pixel (a 1x1 framebuffer), using color to encode the world z. After decoding the Z value of the picked pixel, we can unproject the cursor position accurately into the 3D space.
- The new pass is opt-in so that it doesn't affect performance of existing use cases.
- The new pass is cheaper than the picking pass because it
+ disables blending
+ only renders one layer
+ only renders one pixel (regardless of `pickingRadius`)
+ decoding z is …
=> Picking 3D point

modules/aggregation-layers/src/utils/scale-utils.js, test/modules/aggregation-layers/utils/scale-utils.spec.js
For #3630
Add `domain` function to existing `getQuantileScale` and `getOrdinalScale`
- Add domain method in `scale-utils.js`
- Write test for these changes
=> Add domain method to scales

modules/core/src/lib/deck-picker.js, modules/core/src/lib/deck.js, modules/core/src/lib/picking/pick-info.js, test/modules/core/lib/deck-picker.spec.js
- Private methods naming convention
- Avoid unnecessarily deconstructing and reconstructing objects
=> Clean up picking code

modules/core/src/lib/deck-picker.js, modules/core/src/lib/deck-renderer.js, modules/core/src/lib/deck.js, modules/core/src/passes/layers-pass.js, modules/core/src/passes/pick-layers-pass.js, modules/test-utils/src/lifecycle-test.js
- Private method naming convention
- Avoid unnecessary breaking/reconstructing parameter objects
=> Clean up render passes

modules/aggregation-layers/src/utils/gpu-grid-aggregation/aggregate-all-vs-64.glsl.js
For #
Applying work around for an ANGLE bug similar to HeatmapLayer
More details: #3732 
ANGLE bug: https://bugs.chromium.org/p/angleproject/issues/detail?id=3941&can=8&q=&colspec=ID%20Type%20Status%20Priority%20Feature%20Owner%20Summary
- GPUGridAggregator: enforce point size to workaround ANGLE bug
=> GPUGridAggregator: enforce point size to workaround ANGLE bug

docs/api-reference/deck.md, examples/layer-browser/src/map.js, modules/core/src/effects/lighting/lighting-effect.js, modules/core/src/lib/deck-picker.js, modules/core/src/lib/deck-renderer.js, modules/core/src/passes/layers-pass.js, modules/core/src/passes/pick-layers-pass.js, modules/core/src/passes/shadow-pass.js
Currently, the `pickable` prop is tied to the following features:
- Callbacks such as `onHover` and `onClick`
- Auto highlighting
- Queries such as `pickObjects`
This makes it difficult for applications that need different behaviors in auto-picking on hover (e.g. tooltips, auto-highlight) vs. multi-depth picking on click (e.g. map editing).
This PR introduces an additional `renderPass` field to the `layerFilter` parameters so that applications can control whether a layer is rendered based on which render pass it's in.
Related: https://github.com/uber/streetscape.gl/pull/396
- Add picking mode to `pass` string
- Add `pass` to `layerFilter` parameters
=> Add `pass` parameter to layerFilter

examples/layer-browser/src/app.js, modules/core/src/effects/lighting/camera-light.js, modules/core/src/effects/lighting/lighting-effect.js, modules/core/src/effects/lighting/point-light.js, modules/core/src/effects/post-process-effect.js, modules/core/src/lib/deck-renderer.js, modules/core/src/lib/effect.js, modules/core/src/passes/draw-layers-pass.js, modules/core/src/passes/layers-pass.js, test/modules/core/effects/lighting-effect.spec.js, test/modules/core/effects/post-process-effect.spec.js, test/modules/core/lib/effect-manager.spec.js, test/modules/core/passes/pick-layers-pass.spec.js
- Rename: `effect.prepare` -> `effect.preRender`, no longer returns object
- Rename: `effect.render` -> `effect.postRender`, returns the last output buffer
- Rename: `effect.getParameters` -> `effect.getModuleParameters`
- Remove `DeckRenderer`'s dependency on `PostProcessEffect`, allow custom effects to have `postRender` lifecycle
- Remove `effectProps` from layer pass, use `moduleParameters`
=> Effects system clean up

modules/core/src/lib/deck-picker.js
- When the camera is not pointing to the ground, common space z must compensate for the offset.
=> Fix 3d picking projection with camera offset

.travis.yml, bindings/python/pydeck/setup.py
Python build is breaking after a Puppeteer update that makes it incompatible with its VM's version of Node. This PR uses a more recent version of node.
-
=> Update Python travis build

dev-docs/RFCs/README.md, dev-docs/roadmaps/gpu-table-roadmap.md
For #3758
- First cut of GPUTable roadmap
- Will be rebased on top of #3818 before landing, should only contain gpu-table-roadmap.md
=> dev-docs: Add `GPUTable` roadmap

modules/core/src/lib/attribute.js, test/modules/core/lib/attribute.spec.js
For https://github.com/uber/deck.gl/issues/3838
Was calling `buffer.subData` with `Float64Array`.
=> Fix attribute allocation bug when using partial update with double precision

modules/core/src/lib/attribute/data-column.js, test/modules/core/lib/attribute/attribute.spec.js
For #3852 
Fixes render test failure.
`Attribute._areValuesEqual` only compares `size` elements, thus failing to detect change when comparing `[1]` with `Float32Array([1, 1, 2, ...])`.
- When checking for constant update, first check if the existing value is a constant
=> Fix attribute constant comparison

docs/layers/trips-layer.md, examples/layer-browser/src/examples/additional-layers.js, modules/geo-layers/src/trips-layer/trips-layer.js, test/modules/geo-layers/trips-layer.spec.js, test/render/test-cases.js
For https://github.com/uber/deck.gl/issues/3869
- Remove support for the legacy use case (`[x, y, timestamp]` format)
- Remove arbitrary zShift applied in the vertex shader
- Docs
- Remove tests for the legacy use case
=> v8.0 TripsLayer API change

docs/upgrade-guide.md, modules/core/src/lib/deck.js, test/modules/core/lib/deck.spec.js
For https://github.com/uber/deck.gl/issues/3869 https://github.com/uber/deck.gl/issues/3867
This is a known issue from v6+. Making the breaking change in v8.
- State change in one view should not be applied to other views
- Tests
=> Fix view state handling

modules/layers/src/path-layer/path-layer.js, modules/layers/src/path-layer/path-tesselator.js, test/modules/layers/path-tesselator.spec.js
For #3758 
This change simplifies the layout of the position attributes, saves a little bit of memory, and prepares `PathTesselator` for accepting external buffers.
In this new format, loops are padded with 2 additional vertices, and paths without loops no longer require tesselation. We may expose it later as an option for use cases where performance is more important than visual quality. @twojtasz 
- Use a single positions buffer in `PathLayer`
- Unit tests
=> Simplify PathLayer tesselation

modules/core/src/lib/attribute/attribute-manager.js, modules/core/src/lib/attribute/attribute-transition-manager.js, modules/core/src/lib/attribute/attribute-transition-utils.js, modules/core/src/lib/attribute/attribute.js, modules/core/src/lib/layer.js, modules/core/src/transitions/gpu-interpolation-transition.js, modules/core/src/transitions/gpu-spring-transition.js, modules/core/src/utils/array-utils.js, modules/core/src/utils/tesselator.js, modules/geo-layers/src/trips-layer/trips-layer.js, modules/layers/src/path-layer/path-layer.js, modules/layers/src/solid-polygon-layer/polygon-tesselator.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer.js, test/modules/core/lib/attribute/attribute.spec.js, test/modules/core/utils/array-utils.spec.js, test/modules/layers/core-layers.spec.js, test/modules/layers/polygon-tesselation.spec.js
For #3758
Variable-width attributes (e.g. those of the `PathLayer` or the `PolygonLayer`) contain a `bufferLayout` member that stores the vertex count of each object as `[chunk0Length, chunk1Length, ...]`.
This PR replaces the member with `vertexStarts` which stores the staring indices of each object as `[chunk0Start, chunk1Start, ...]`. This allows us to access arbitrary positions in the data without having to loop from the start.
This is in preparation for RFC #3884 -- if an application wants to supply a flat positions buffer for paths/polygons, they need to also supply a `vertexStarts` array, making the previously private API public.
I'm not happy with the name `vertexStarts`. Any suggestions?
- `Attribute` class
- `Tesselator` classes
- Attribute transition utils
- Unit tests
Verified …
=> Change bufferLayout to startIndices

modules/core/src/lib/attribute/attribute.js, modules/geo-layers/src/trips-layer/trips-layer.js, test/modules/core/lib/attribute/attribute.spec.js
For #3758 
- Attribute auto updater allows assigning each vertex in a tesselated object different values.
- Simplify `TripsLayer`
- Tests
=> Support variable-width values in auto update

modules/core/src/lib/attribute/attribute-transition-utils.js, modules/core/src/lib/attribute/attribute.js, modules/core/src/lib/attribute/data-column.js, modules/core/src/utils/array-utils.js, modules/layers/src/path-layer/path-layer.js, modules/layers/src/path-layer/path-tesselator.js, test/modules/core/lib/attribute/attribute.spec.js, test/modules/layers/path-tesselator.spec.js
For #3758 
This change moves the handling of attribute offset from typed array generation to the buffer management. Layers and application no longer have to consider the buffer layout when dealing with attributes.
- `DataColumn` can upload value to WebGL buffer at an offset
- Remove `Attribute.elementOffset`
- `PathTesselator` no longer adds padding to the positions array
=> Handle offset in DataColumn

dev-docs/RFCs/README.md, dev-docs/RFCs/v7.x/layer-culling-rfc.md
For #148
- Frustum culling is required for performant 3D tiles rendering
=> RFC: Layer Culling

website-gatsby/gatsby-config.js, website-gatsby/ocular-config.js, website-gatsby/package.json, website-gatsby/src/components/info-panel.jsx, website-gatsby/src/constants/defaults.js, website-gatsby/src/utils/data-utils.js, website-gatsby/src/utils/format-utils.js, website-gatsby/src/utils/worker-utils.js, website-gatsby/static/workers/flight-path-data-decoder.js, website-gatsby/static/workers/util.js, website-gatsby/templates/examples/example-line-layer.jsx, website-gatsby/templates/index.jsx, website-gatsby/templates/style.scss
For #3775, subtask of #3754 
I've ported the LineDemo example from the current website into the ocular gatsby system.  I'm looking for feedback on the port of this single example before I move the rest over in one or more future PRs.
To port the new example, I did the following:
- Reworked the LineDemo component to work without redux
- Moved the use of InfoPanel into the LineDemo component as a direct dependency
- Ported over a minimal set of code for the loading data on web workers
- Added a gatsby SCSS plugin to the website and ported over some minimal styling
=> Port line layer example and web worker data loader to ocular gatsby website  

docs/layers/path-layer.md, docs/layers/solid-polygon-layer.md, modules/core/src/utils/tesselator.js, modules/layers/src/path-layer/path-layer.js, modules/layers/src/path-layer/path-tesselator.js, modules/layers/src/polygon-layer/polygon-layer.js, modules/layers/src/solid-polygon-layer/polygon-tesselator.js, modules/layers/src/solid-polygon-layer/polygon.js, modules/layers/src/solid-polygon-layer/solid-polygon-layer.js, test/modules/layers/path-tesselator.spec.js, test/modules/layers/polygon-tesselation.spec.js
For #3758 
In preparation to (efficiently) accept external position buffers.
See updated documentation in this PR.
- Add option to skip normalization in `Tesselator`
- Add experimental prop `_pathType` to `PathLayer`
- Add experimental prop `_normalize` to `SolidPolygonLayer`
- Docs
- Unit tests
=> Add option to skip normalization in tesselators

modules/core/src/lib/attribute/attribute-manager.js, modules/core/src/lib/attribute/attribute.js, modules/core/src/lib/layer.js, modules/core/src/utils/iterable-utils.js, test/modules/core/lib/attribute/attribute-manager.spec.js, test/modules/core/lib/attribute/attribute.spec.js, test/modules/core/utils/iterable-utils.spec.js, test/render/test-cases.js
For #3758, implements the RFC in #3884 
- Drops support for external attributes in top-level props
- Add `attribute.setBinaryValue`, support auto-packed attributes
- Unit tests
- `PathLayer`
- `SolidPolygonLayer`
=> Support binary logical attributes

test/data/grid-aggregation-data.js, test/modules/aggregation-layers/utils/gpu-grid-aggregator.spec.js
Otherwise we can't skip them when debugging with `test.only`.
=> Move substantial data operation inside unit tests

docs/layers/polygon-layer.md, docs/layers/solid-polygon-layer.md, modules/geo-layers/src/h3-layers/h3-cluster-layer.js, modules/geo-layers/src/h3-layers/h3-hexagon-layer.js, modules/geo-layers/src/s2-layer/s2-layer.js, modules/geo-layers/src/s2-layer/s2-utils.js, modules/layers/src/polygon-layer/polygon-layer.js
Follow up of #3905 
- Add `_normalize` prop to `PolygonLayer`
- Skip normalization in `H3HexagonLayer` and `S2Layer`
- Docs
=> Add option to skip normalization in PolygonLayer

dev-docs/RFCs/README.md, dev-docs/RFCs/v7.x/binary-data-rfc.md, dev-docs/RFCs/v8.0/binary-support-improvements-rfc.md
For #3758 
This is a proposal for practical API changes we can make by v8.0, before full data frame support. The goal of this design is to
- provide a more intuitive way for users to work with binary data
- be compatible with the planned data frame support work in upcoming releases
- avoid drastic changes to the core infrastructure
=> RFC for v8.0 binary support API

modules/core/bundle/lumagl.js
- Remove classes that are not needed by custom layers
- Remove utility functions dropped in luma.gl v8
- Remove shader modules that are re-exported by deck
=> Simplify bundle luma exports

docs/upgrade-guide.md, examples/layer-browser/src/app.js, modules/core/src/lib/init.js, modules/layers/src/bitmap-layer/bitmap-layer.js, modules/layers/src/icon-layer/icon-layer-vertex.glsl.js, modules/layers/src/icon-layer/icon-manager.js, modules/layers/src/text-layer/font-atlas-manager.js, modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer-vertex.glsl.js, modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js, modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js
For #3869 
- Switch `HTMLImageLoader` to `ImageLoader` (supports loading to `ImageBitmap` when `Image` is not available)
- Flip y in texture packing: `BitmapLayer`, `IconLayer`, `TextLayer`
=> Remove texture flip

bindings/python/pydeck/pydeck/io/html.py, bindings/python/pydeck/pydeck/io/templates/imports.j2, bindings/python/pydeck/pydeck/io/templates/index.j2, modules/jupyter-widget/package.json, modules/jupyter-widget/src/create-deck.js, modules/jupyter-widget/src/deck-bundle.js, modules/jupyter-widget/src/index.js, modules/jupyter-widget/src/plugin.js, modules/jupyter-widget/src/standalone-html-index.js, modules/jupyter-widget/src/version.js, modules/jupyter-widget/webpack.config.js, test/modules/jupyter-widget/index.spec.js, test/render/jupyter-widget-test.html
For #3640 
This PR and its parent #3638 collectively simplify the way pydeck is built. In particular, this PR does the following:
- Simplifies dependency management for pydeck's standalone HTML renderer (which allows users to generator visualizations without having installed Jupyter).
- Switches pydeck to use the deck.gl standalone bundle in modules/core/bundle.
- Modifies webpack to use the appropriate aliases for the standalone bundle when composing the supporting bundles for Notebook, Lab, and the standalone HTML renderer.
- Skips failing node tests temporarily (browser tests are passing)
=> Refactor pydeck standalone HTML generator

examples/experimental/bezier/src/bezier-curve-layer/bezier-curve-layer.js, examples/website/plot/plot-layer/surface-layer.js, modules/core/src/lib/layer-manager.js, modules/core/src/lib/layer.js, test/apps/carto-wip/time-sliced-scatterplot-layer/time-sliced-scatterplot-layer.js
For #3869 
- Avoid referencing `layer.internalState` from `LayerManager`
- Remove unused `model.userData.layer`
- Remove unused `layer.state.layer`
- Deprecate `layer.state.attributeManager`
=> Clean up layer internal state

modules/core/src/lib/layer.js, modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer.js
- Do not copy `pickingColorCache` to new typed array in the one-instance-per-object use case
=> Reuse instancePickingColors value

examples/layer-browser/src/examples/core-layers.js, examples/layer-browser/src/utils/flatten-vertices.js, modules/aggregation-layers/bundle.js, modules/aggregation-layers/src/aggregation-layer.js, modules/aggregation-layers/src/heatmap-layer/heatmap-layer.js, modules/aggregation-layers/src/index.js, modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.js, modules/core/src/index.js, modules/core/src/utils/flatten.js, modules/extensions/src/fp64/project64.js, modules/extensions/src/path-style/path-style.js, modules/jupyter-widget/src/deck-bundle.js, modules/layers/src/path-layer/path-tesselator.js, modules/layers/src/solid-polygon-layer/polygon-tesselator.js, modules/main/bundle.js, modules/main/src/index.js, modules/react/src/deckgl.js, modules/test-utils/src/generate-layer-tests.js, test/modules/core/utils/flatten.spec.js, test/modules/geo-layers/h3-layers.spec.js, test/modules/imports-spec.js
For #3869 
- Remove `experimental` object from core and aggregation-layers, use underscore names for experimental exports
- Remove unused `flattenVertices` util
cc @heshan0131
=> Remove `experimental` export, use underscores

modules/core/src/lib/attribute/attribute.js, modules/core/src/lib/attribute/data-column.js, test/bench/index.js, test/bench/layer.bench.js
A fix we made in `attribute._normalizeValue` from 7.3 to 8.0 is showing up in profiling. This PR restores the old implementation for size<=4 use cases for performance.
Before:
├─ initialize layers: 34.3 iterations/s ±20.04%
├─ update layers: 13.5 iterations/s ±6.94%
After:
├─ initialize layers: 37.5 iterations/s ±20.41%
├─ update layers: 39.4 iterations/s ±6.43%
- Improve `attribute._normalizeValue` perf
- Bench tests
=> Attribute update perf

modules/layers/src/icon-layer/icon-layer.js
In IE11, the icon layer was incorrectly rendered. (#2486)
This is because the IE11 webgl engine was interpreting the position list as 2d elements to match the `attribute vec2 positions;` declared in the [shader](https://github.com/uber/deck.gl/blob/master/modules/layers/src/icon-layer/icon-layer-vertex.glsl.js#L24). Other browsers correctly skipped the `z` coordinate.
* Specify icon-layer positions as 2d points
* Specify to the `Geometry()` that the positions have a size of 2 to override the [default](https://github.com/uber/luma.gl/blob/master/modules/core/src/geometry/geometry.js#L90-L92) luma.gl behaviour of assuming a size of 3.
=> Icon layer: Use 2D positions to match vertex shader

modules/core/src/lifecycle/component-state.js, modules/core/src/lifecycle/component.js, modules/core/src/lifecycle/constants.js, modules/core/src/lifecycle/create-props.js, modules/core/src/lifecycle/props.js, modules/layers/src/icon-layer/icon-layer.js, test/bench/create-props.bench.js, test/bench/index.js
Before
├─ createProps#empty: 575K iterations/s ±1.46%
├─ createProps#realWorld: 417K iterations/s ±6.83%
After
├─ createProps#empty: 6.01M iterations/s ±1.98%
├─ createProps#realWorld: 1.94M iterations/s ±2.27%
- Use `Symbol` instead of `Object.defineProperties` for props' non-enumerable fields
- Add deprecation warning/fallback to setters on the props prototype, instead of checking with for loop
- Bench tests
=> Improve createProps perf

modules/geo-layers/src/trips-layer/trips-layer.js
For https://github.com/uber/deck.gl/issues/3976
`TripsLayer` was not setting the `bufferLayout` on `instanceTimestamps` which breaks partial update.
(Patching 7.3-release; this method has been removed on master)
- Fix `instanceTimestamps` attribute update
=> Fix trips layer timestamps attribute partial update

examples/layer-browser/package.json, examples/layer-browser/src/app.js, examples/layer-browser/src/map.js, modules/core/src/lib/deck.js, modules/react/src/deckgl.js, modules/react/src/utils/position-children-under-views.js
Related issue: #3389
In v7, the `eventManager` only listens to mouse events on the `<canvas>`, not the children of `<DeckGL>`. After this PR, all events inside the deckgl-wrapper are captured.
- Use the optional `props.parent` as `eventManager`'s root element. `parent`, if supplied, is already used as the container for auto-created canvas.
- Remove the old CSS hack `pointerEvents: none;` for React children
- Fix a bug introduced in #3870 - mutating `deck.viewState` may break `viewManager`'s detection of viewport change.
- Fix using react-map-gl `NavigationControl` with auto-controller (missing `viewId` when calling `onViewStateChange`).
=> React: eventManager listens to all children
