docs/api-reference/mapbox/mapbox-layer.md

For #3450
- Make code sample functional

Update code sample in MapboxLayer docs

---

modules/layers/src/icon-layer/icon-layer.js

IconLayer: check texture width and height before drawing

---

.travis.yml
bindings/python/.gitignore
bindings/python/pydeck/requirejs_dependencies.json
bindings/python/pydeck/requirements-dev.txt
bindings/python/pydeck/requirements.txt
bindings/python/pydeck/setup.py

For #2929
- Correct a small RequireJS typo that breaks rendering
- Add additional requirements for `python setup.py install` and development.

Add additional setup.py requirements

---

modules/mesh-layers/src/scenegraph-layer/scenegraph-layer-fragment.glsl.js
modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js

- enable opacity in scene graph layer

fix opacity issue in scene graph layer

---

dev-docs/RFCs/vNext/component-wrapping-rfc.md

#3065 ## Background
Added something to Ib's RFC

update the component-wrapping-rfc.md

---

modules/core/package.json
modules/mesh-layers/package.json
package.json
test/modules/core/lib/picking.spec.js
yarn.lock

- update unit test
- bump luma.gl version

Bump luma.gl version to 7.3.0-alpha.5

---

bindings/python/pydeck/examples/01 - Introduction.ipynb
bindings/python/pydeck/pydeck/widget/widget.py
modules/jupyter-widget/src/index.js
modules/jupyter-widget/src/utils.js
modules/jupyter-widget/src/widget.js

For #2929 
`Deck.update()` which refreshes the data in a Jupyter widget broke in a refactor–this PR corrects that.

Re-introduce support for live updates and introduce 2-way API communication

---

examples/webpack.config.local.js
modules/core/src/lib/attribute-transition-manager.js
modules/core/src/lib/attribute-transition-utils.js
test/modules/core/lib/attribute-transition-manager.spec.js
test/modules/core/lib/attribute-transition-utils.spec.js

This is a WIP: Programs need to be fetched from a program manager cache.

Transition system refactor (2/2): create one transform per attribute

---

bindings/python/pydeck/dependency_managers/__init__.py
bindings/python/pydeck/requirejs_dependencies.json

For #2929 
Reverts pydeck changes made directly to master

Revert pydeck path changes

---

bindings/python/pydeck/README.md

For #2929
Adds an interactive documentation link

Add mybinder URL to pydeck README

---

modules/core/src/lib/attribute-transition-manager.js
modules/core/src/lib/attribute-transition-utils.js
modules/core/src/lib/attribute.js
modules/core/src/lib/base-attribute.js
test/apps/attribute-transition/app.js
test/apps/attribute-transition/data-generator.js

- Handle 64bit attribute
- Fix issue in transitioning normalized buffers

Fix double precision attribute transitions

---

modules/geo-layers/package.json
modules/geo-layers/src/index.js
modules/geo-layers/src/tile-3d-layer/get-frame-state.js
modules/geo-layers/src/tile-3d-layer/tile-3d-layer.js
modules/main/src/index.js
yarn.lock

Add Tile3DLayer to geo-layers module

---

examples/gallery/src/arc-layer.html
examples/gallery/src/geojson-layer.html
examples/gallery/src/great-circle-layer.html
examples/gallery/src/highway.html
examples/gallery/src/icon-layer.html
examples/gallery/src/line-layer.html
examples/gallery/src/text-layer.html
website/src/components/demos/layer-demo-base.js

- Documentation embedded demos
- Scripting examples

Use built-in tooltip API in examples

---

bindings/python/pydeck/dependency_managers/__init__.py
bindings/python/pydeck/requirejs_dependencies.json

For issue #2929
Stacked diff associated with #3548
Some of the JS file asset paths are incorrect in the requirejs configs, which keeps data from rendering

[#3548 - Part 2] Change JS bundle filepath names

---

bindings/python/pydeck/examples/04 - PointCloudLayer.ipynb
bindings/python/pydeck/pydeck/bindings/deck.py
bindings/python/pydeck/pydeck/io/html.py
bindings/python/pydeck/setup.py
bindings/python/pydeck/tests/browser/test_html_renderer.py

For #2929
Stacked diff associated with #3548
- Additional support for standalone HTML rendering within a Jupyter notebook: Specify the HTML file's path relative to the running Jupyter notebook
- Indicate in setup.py that the README is in markdown.

[#3548 - Part 4] Update notebook documentation to include additional pydeck features

---

dev-docs/RFCs/vNext/tile-3d-layer.md

Add Tile3DLayer doc

---

modules/core/src/lib/layer.js

Fix shadow module toggle bug

---

bindings/python/pydeck/requirements.txt
bindings/python/pydeck/setup.py

For #2929 
Seeing errors around the `ipykernel>=5.1.2` requirement and providing a substitute installation.

Provide additional support for Python 2.7 installations

---

modules/geo-layers/src/tile-3d-layer/tile-3d-layer.js

- return all layers as sublayer

fix vricon tile stop rendering issue

---

package.json
yarn.lock

ocular-dev-tools: 0.0.29 (modernize es6 dists)

---

.travis.yml
bindings/python/pydeck/requirements-dev.txt
bindings/python/pydeck/tests/browser/test_examples.py
bindings/python/pydeck/tests/browser/test_html_renderer.py

CI is failing on the Python build for valid PRs because of some Pyppeteer-related issue. Cutting pyppeteer for the moment.
- Remove pyppeteer from the dev dependencies
- Skip tests using pyppeteer on CI

Revert Python pyppeteer installation

---

docs/layers/tile-3d-layer.md

Fix Tile3DLayer doc links

---

modules/main/bundle.js

This needs to be cherry-picked to 7.2-release

Add extensions to master bundle

---

examples/layer-browser/package.json
examples/website/mesh/package.json
examples/website/point-cloud/package.json
modules/core/package.json
modules/layers/package.json
website/package.json
yarn.lock

Bump loaders.gl to latest latest 1.2 prod

Bump loaders.gl to latest latest 1.2 prod

---

modules/core/bundle/index.js
modules/core/bundle/lumagl.js

Shaves ~56K in minimized bundle
- Cherry-pick luma exports

Bundle optimization

---

examples/website/3d-tiles/app.js
website/src/components/demos/tiles-3d-demo.js

- add contributions in info panel

Add Cesium Ion attributions for 3D tile example

---

docs/developer-guide/custom-layers/subclassed-layers.md

Fix outdated custom layer example

---

examples/website/3d-tiles/README.md
examples/website/3d-tiles/package.json

- update readme and deck.gl versions

Update readme and deck.gl dependencies in 3d tiles example

---

docs/layers/tile-3d-layer.md
examples/layer-browser/package.json
examples/playground/package.json
examples/website/3d-tiles/package.json
examples/website/mesh/package.json
examples/website/point-cloud/package.json
modules/core/package.json
modules/geo-layers/package.json
modules/geo-layers/src/tile-3d-layer/tile-3d-layer.js
modules/layers/package.json
package.json
website/package.json
yarn.lock

- bump loaders.gl everywhere
- introduce Josh's [changes](https://github.com/uber-web/loaders.gl/pull/400) in loaders.gl 
- add `getColor` to props

Adopt most recent change from loaders.gl and bump loaders.gl

---

examples/playground/package.json
website/package.json
website/scripts/build.sh

- Build and copy playground and gallery examples when run `yarn build` in `website` directory

Update website build script

---

CHANGELOG.md

add missing change logs

---

modules/jupyter-widget/src/utils.js
modules/jupyter-widget/src/widget-tooltip.js

For #2929
- Change default tooltip styling for pydeck

Update pydeck tooltip style and modularize the Jupyter widget tooltip

---

docs/api-reference/json/json-converter.md
examples/playground/json-examples/3d-heatmap.json
modules/json/src/json-configuration.js
modules/json/src/json-converter.js
test/modules/json/data/deck-props.json
test/modules/json/json-configuration-for-deck.js
test/modules/json/json-converter.spec.js

- to support passing DracoLoader and DracoWorkerLoader from json files in playground.
- @deck.gl/json

Support constants and non instantiate prop in json module

---

bindings/python/pydeck/pydeck/bindings/deck.py

[Jupyter Widget] Allow easier configuration of height and width in a pydeck visualization

---

modules/geo-layers/src/tile-3d-layer/tile-3d-layer.js
modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js

- change API name to _composeModelMatrix

Change API name to _composeModelMatrix for API audit

---

docs/layers/tile-3d-layer.md
modules/geo-layers/src/tile-3d-layer/tile-3d-layer.js
test/modules/geo-layers/tile-3d-layer/tile-3d-layer.spec.js

Tileset3DLayer API audit

---

modules/core/src/lib/attribute-transition-manager.js
modules/core/src/lib/attribute-transition-utils.js
modules/core/src/lib/uniform-transition-manager.js
modules/core/src/transitions/cpu-interpolation-transition.js
modules/core/src/transitions/cpu-spring-transition.js
modules/core/src/transitions/transition.js
test/modules/core/lib/attribute-transition-manager.spec.js
test/modules/core/lib/uniform-transition-manager.spec.js
test/modules/core/transitions/transition.spec.js

For #3574 
- Add default spring settings
- Add `CPUInterpolationTransition` and `GPUInterpolationTransition` class
- Unit tests

Support spring transition in UniformTransitionManager

---

docs/layers/arc-layer.md
docs/layers/bitmap-layer.md
docs/layers/column-layer.md
docs/layers/contour-layer.md
docs/layers/cpu-grid-layer.md
docs/layers/geojson-layer.md
docs/layers/gpu-grid-layer.md
docs/layers/grid-cell-layer.md
docs/layers/grid-layer.md
docs/layers/h3-hexagon-layer.md
docs/layers/heatmap-layer.md
docs/layers/hexagon-layer.md
docs/layers/icon-layer.md
docs/layers/line-layer.md
docs/layers/path-layer.md
docs/layers/point-cloud-layer.md
docs/layers/polygon-layer.md
docs/layers/scatterplot-layer.md
docs/layers/scenegraph-layer.md
docs/layers/screen-grid-layer.md
docs/layers/simple-mesh-layer.md
docs/layers/solid-polygon-layer.md
docs/layers/text-layer.md
docs/layers/trips-layer.md

Follow up of #3443 
- Update layer docs
- What's new

Add transition badges to newly enabled props in layer docs

---

bindings/python/pydeck/README.md

Update pydeck README

---

bindings/python/pydeck/requirements-dev.txt

Adding Python `requests` library to support a notebook example
For #
-

Add requests library to support new pydeck example

---

bindings/python/pydeck/pydeck/bindings/deck.py
bindings/python/pydeck/pydeck/io/html.py
bindings/python/pydeck/pydeck/io/templates/js.j2
bindings/python/pydeck/pydeck/widget/widget.py
modules/jupyter-widget/src/utils.js
modules/jupyter-widget/src/widget.js

For #2929
- Provides support for users to hide pydeck tooltip while still allowing
data selection

Allow pydeck users to hide tooltip

---

bindings/python/pydeck/docs/deck.md

Update pydeck docs: deck.md

---

examples/website/3d-tiles/app.js

- use UberVisTeam Token
- 3d-tiles example

Update token and id for Melbourne 3d tiles

---

bindings/python/pydeck/README.md

Update pydeck README.md to include docs link

---

bindings/python/pydeck/README.md

Update pydeck README.md with binder logo

---

bindings/python/pydeck/docs/README.md
bindings/python/pydeck/docs/deck.md

Update pydeck documentation landing page

---

bindings/python/pydeck/docs/view_state.md
bindings/python/pydeck/pydeck/bindings/view_state.py
bindings/python/pydeck/tests/test_data_utils.py

Update pydeck docs: view_state.md

---

bindings/python/pydeck/setup.py

Update pydeck setup.py to enable a production build

---

docs/upgrade-guide.md
docs/whats-new.md

7.3 What's New

---

docs/layers/tile-3d-layer.md
examples/layer-browser/package.json
examples/website/3d-tiles/app.js
examples/website/3d-tiles/package.json
examples/website/mesh/package.json
examples/website/point-cloud/package.json
modules/core/package.json
modules/geo-layers/package.json
modules/geo-layers/src/tile-3d-layer/tile-3d-layer.js
modules/layers/package.json
yarn.lock

Pass DracoLoader to Tile3DLayer from app

---

website/scripts/build.sh

For #
If `examples/gallery or playground` are cleaned , website build fails, update the build script to install dependencies for these folders.
-

Website: update build script to install dependencies

---

modules/jupyter-widget/src/widget.js

- Fix issue where container height is not getting properly set, hiding
the widget

Fix pydeck widget rendering issue

---

bindings/python/pydeck/requirejs_dependencies.json
modules/jupyter-widget/src/utils.js
modules/jupyter-widget/src/widget.js
modules/jupyter-widget/webpack.config.js

- Update S2 library to correspond with core deck.gl's S2 library

Update S2 library within pydeck

---

bindings/python/pydeck/dependency_managers/__init__.py
bindings/python/pydeck/pydeck/_version.py
bindings/python/pydeck/pydeck/bindings/deck.py
bindings/python/pydeck/pydeck/io/html.py

Hardcode iframe height in pydeck

---

examples/website/screen-grid/app.js
website/scripts/build.sh
website/src/static/index-dist.html
website/src/static/index.html

- Use local bundle for `yarn start`

Fix website local testing

---

website/src/components/demos/heatmap-demo.js

HeatmapLayer example: reduce the radius range

---

website/package.json
website/src/components/demos/layer-demo-base.js
website/src/components/input.js
website/src/stylesheets/_gallery.scss
website/src/utils/format-utils.js
website/src/utils/layer-params.js

For #3591 
- Fix bug where Chrome color picker loses focus
- Enable controls for accessor props
- Fix unintended vertical scrollbar
- Fix async prop url link

Tweak embedded demo options panel styling

---

website/src/stylesheets/_gallery.scss

Make gallery options panel wider

---

bindings/python/pydeck/pydeck/bindings/deck.py

This is an unused, early feature of pydeck
It's confusing and should be cut
-

Remove addition operator overload from pydeck

---

bindings/python/pydeck/pydeck/bindings/deck.py
bindings/python/pydeck/pydeck/io/html.py
bindings/python/pydeck/pydeck/io/templates/js.j2
bindings/python/pydeck/pydeck/widget/widget.py
modules/jupyter-widget/src/utils.js
modules/jupyter-widget/src/widget-tooltip.js
modules/jupyter-widget/src/widget.js

Allow pydeck user to modify tooltip text

---

bindings/python/pydeck/README.md

Fix typo, change text for clarify
-

Update pydeck README.md

---

.readthedocs.yml

Add .readthedocs.yml for readthedocs.org hosting

---

bindings/python/pydeck/README.md

Update pydeck README.md with to_html params

---

modules/core/src/lib/tooltip.js
modules/jupyter-widget/src/widget-tooltip.js

Ignore keys with undefined values in the jupyter-widget custom tooltip

---

bindings/python/pydeck/README.md

Update pydeck README.md with readthedocs link

---

bindings/python/pydeck/README.md

Correct pydeck README typo

---

website/package.json
website/src/components/demos/heatmap-demo.js

For #
Custom color domain is needed due to an ANGLE [issue](https://bugs.chromium.org/p/angleproject/issues/detail?id=3941) for Windows and iOS platforms.
- HeatmapLayer Demo: Conditionally add colorDomain controls

HeatmapLayer Demo: Conditionally add colorDomain controls

---

modules/core/src/lib/base-attribute.js

delete deprecated buffer props

---

examples/website/heatmap/app.js
examples/website/heatmap/package.json
modules/aggregation-layers/src/heatmap-layer/heatmap-layer.js

- Clamp `colorDomain` when float target is not supported.

Fix heatmap example on iOS

---

bindings/python/pydeck/docs/conf.py
bindings/python/pydeck/pydeck/_version.py

Release of pydeck to coincide with deck.gl 7.3
For #3640
-

Bump pydeck to 0.1.dev5

---

website/src/utils/layer-params.js

For https://github.com/uber/deck.gl/issues/3031

Fix embedded demo crash

---

modules/geo-layers/src/tile-layer/tile-layer.js
modules/geo-layers/src/tile-layer/utils/tile-cache.js
modules/geo-layers/src/tile-layer/utils/tile.js
test/modules/geo-layers/tile-layer/tile-cache.spec.js
test/modules/geo-layers/tile-layer/tile-layer.spec.js

See discussion in https://github.com/uber/deck.gl/pull/3704
- Avoid excessive re-render during continuous viewport updates

TileLayer cache rendered sub layers

---

modules/aggregation-layers/src/heatmap-layer/max-vs.glsl.js

possible fix for #3554 
More details: https://bugs.chromium.org/p/angleproject/issues/detail?id=3941
-

HeatmapLyaer: set point size to address ANGLE bug

---

examples/website/heatmap/app.js
website/package.json
website/src/components/demos/heatmap-demo.js

For #
Added additional controls/code to set `colorDomain` to workaround ANGLE issue. Given this issue is resolved in #3732 , remove these new controls/code.
-

Website: HetamapLayer demo update

---

modules/core/src/lib/deck-picker.js
modules/core/src/lib/layer.js
modules/core/src/lib/picking/pick-info.js
modules/core/src/passes/draw-layers-pass.js
modules/core/src/passes/layers-pass.js
modules/core/src/passes/pick-layers-pass.js
modules/core/src/passes/shadow-pass.js

- Avoid rerender when `autoHighlight` is disabled
- Avoid updating picking module parameters unless layer props change

Improve auto-highlight related perf

---

modules/aggregation-layers/src/screen-grid-layer/screen-grid-cell-layer.js
modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer.js
test/modules/aggregation-layers/index.js
test/modules/aggregation-layers/screengrid-cell-layer.spec.js
test/modules/layers/core-layers.spec.js

Fixes #3526 
- Split ScreenGridLayer into, 
1. ScreenGirdLayer (Composite) that handles aggregation
2. ScreenGridCellLayer (Layer) that handles rendering grid cells.
- ScreenGridLayer: Split into Composite and SubLayer

ScreenGridLayer: Split into Composite and SubLayer

---

bindings/python/pydeck/examples/04 - Plotting massive data sets.ipynb

Add new lidar point cloud example

---

.travis.yml

Python Travis CI tests are failing with no code changes
([example](https://travis-ci.com/uber/deck.gl/jobs/244336702)). It
appears to be related to some external dependencies no longer used in
the build.
-

Simplify Python travis build

---

modules/geo-layers/src/tile-layer/tile-layer.js
test/modules/geo-layers/tile-layer/tile-layer.spec.js

For https://github.com/uber/deck.gl/issues/3776

Invalidate cache when updateTriggers changed

---

README.md

[enhancement/grammar/typo fixing] - deck.gl/readme.md - improving documentation

---

examples/website/mesh/app.js

Fix meshlayer exmaple

---

bindings/python/pydeck/docsview.rst

Remove orphaned documentation page
-

Remove unused documentation page from pydeck

---

website/contents/pages.js
website/src/static/markdown/examples.md

 Fix the url to tile 3d layer example

---

modules/aggregation-layers/src/heatmap-layer/heatmap-layer.js

For #3812 
Fix sublayer id. Will port to `7.3-release` branch.
- HeatmapLayer: fix sublayer id

HeatmapLayer: fix sublayer id

---

docs/README.md

Maybe include `update-release-branch` script?

Update deck.gl version in readme

---

docs/api-reference/json/overview.md
docs/whats-new.md
website/contents/pages.js
website/package.json
website/src/static/markdown/examples.md

For https://github.com/uber/deck.gl/issues/3771

Fix playground links

---

dev-docs/RFCs/v8.0/grid-aggregation-attributemanager.md

For #3810 
Adding RFC to integrate Aggregation Layers with `AttributeManager` and `Layer` lifecycle methods.
-

RFC: Integrate Aggregation Layers with Attribute Manager

---

modules/geo-layers/src/tile-layer/tile-layer.js
test/modules/geo-layers/tile-layer/tile-layer.spec.js

https://github.com/uber/deck.gl/pull/3788 followup

TileLayer: only invalidate tile.layer when updateTriggerChanged

---

bindings/python/pydeck/pydeck/bindings/deck.py
bindings/python/pydeck/pydeck/bindings/view_state.py
bindings/python/pydeck/pydeck/widget/widget.py
modules/jupyter-widget/src/utils.js
modules/jupyter-widget/src/widget.js

For #3640
- Add warning banner to pydeck
- Wrap console.warn to catch displayed warnings

Optionally surface pydeck warnings in widget UI

---

examples/website/icon/package.json
modules/layers/src/icon-layer/icon-manager.js
test/modules/layers/icon-manager.spec.js

For https://github.com/uber/deck.gl/issues/3834

Fix IcanLayer autopacking bug

---

modules/core/src/controllers/controller.js
test/modules/core/controllers/custom-controller.spec.js
test/modules/core/controllers/index.js

For https://github.com/uber/deck.gl/issues/3822
- Make sure custom events are always registered

Fix: custom controller events

---

modules/core/package.json
modules/geo-layers/package.json
modules/layers/package.json
yarn.lock

Bump loaders.gl dependencies

---

docs/upgrade-guide.md
modules/core/src/lib/layer.js

For #3869
- Remove deprecated methods in v7

Layer class deprecations

---

docs/upgrade-guide.md
examples/gallery/src/mapbox-layer.html
modules/geo-layers/src/h3-layers/h3-hexagon-layer.js
modules/layers/src/arc-layer/arc-layer.js
modules/layers/src/line-layer/line-layer.js
test/apps/attribute-worker/test-cases.js

For #3869
- ArcLayer
- LineLayer
- H3HexagonLayer
- Examples

Remove deprecated layer props

---

modules/aggregation-layers/src/aggregation-layer.js
modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer.js
modules/core/src/lib/composite-layer.js
test/modules/aggregation-layers/aggregation-layer.spec.js
test/modules/aggregation-layers/index.js

For #3777 
Minor fixes for crashes discovered in unit tests.
Add unit tests for new `AggregationLayer`.
- AggregationLayer : minor fixes and unit tests.

AggregationLayer : minor fixes and unit tests.

---

docs/api-reference/standalone/deckgl.md
docs/get-started/using-standalone.md
docs/upgrade-guide.md
examples/gallery/src/arc-layer.html
examples/gallery/src/bitmap-layer.html
examples/gallery/src/boiler-plate.html
examples/gallery/src/column-layer.html
examples/gallery/src/contour-layer.html
examples/gallery/src/geojson-layer.html
examples/gallery/src/great-circle-layer.html
examples/gallery/src/hexagon-layer.html
examples/gallery/src/highway.html
examples/gallery/src/icon-layer.html
examples/gallery/src/line-layer.html
examples/gallery/src/mapbox-layer.html
examples/gallery/src/point-cloud-layer.html
examples/gallery/src/scatterplot-layer.html
examples/gallery/src/screengrid-layer.html
examples/gallery/src/text-layer.html
examples/gallery/src/viewport-transition.html
examples/get-started/pure-js/mapbox/index.html
examples/get-started/scripting/basic/index.html
examples/get-started/scripting/mapbox/index.html
modules/core/bundle/deckgl.js
modules/core/src/lib/view-manager.js
test/apps/standalone/index.js
test/render/jupyter-widget.js

For #3869 
- Remove the special handling of `viewState` and `controller` in the standalone bundle
- Docs
- Examples

[v8.0] Scripting API update

---

dev-docs/RFCs/README.md
dev-docs/RFCs/v8.0/projection-system-expansion-rfc.md
dev-docs/RFCs/vNext/projection-system-expansion-rfc.md

For https://github.com/uber/deck.gl/issues/3831

[RFC] Projection system changes

---

website-gatsby/gatsby-ssr.js
website-gatsby/ocular-config.js

For #3754 
Basic fixes for getting the ocular-gatsby website to compile and build correctly.

Fix settings to get ocular-gatsby site to build successfully.

---

modules/core/src/utils/tesselator.js
modules/layers/src/path-layer/path-tesselator.js
modules/layers/src/solid-polygon-layer/polygon-tesselator.js

For #3758 
Calculate each attribute separately, in preparation for accepting external buffers
- `PathTesselator`
- `PolygonTesselator`

Light tesselator refactor

---

modules/geo-layers/package.json
test/render/test-cases.js
yarn.lock

For #3893 
- Use `h3.getRes0Indexes()` per @nrabinowitz 's suggestion

Bump h3-js

---

docs/upgrade-guide.md
modules/core/src/controllers/controller.js
modules/core/src/lib/layer.js
modules/core/src/lib/picking/pick-info.js
modules/core/src/lib/view-manager.js
modules/core/src/views/perspective-view.js
modules/json/src/index.js

For #3869 
Mostly unused and undocumented methods.
See inline comments.

Various core deprecations

---

test/data/grid-aggregation-data.js
test/modules/aggregation-layers/utils/grid-aggregation-utils.spec.js

For #
Fix gpu aggregation tests
-

Fix gpu aggregation tests

---

examples/layer-browser/src/app.js
modules/core/src/lib/layer.js
modules/core/src/passes/layers-pass.js

Fix polygon offset

---

docs/api-reference/attribute-manager.md
modules/core/src/lib/attribute/attribute-manager.js

- Avoid unnecessary construction/destruction of small objects

Improve AttributeManager logging perf

---

dev-docs/RFCs/v7.x/SSAO-effect-rfc.md

First step for the SSAO effect development
- RFC doc

SSAO effect RFC

---

modules/aggregation-layers/src/index.js
modules/aggregation-layers/src/utils/bin-sorter.js
modules/aggregation-layers/src/utils/cpu-aggregator.js
modules/aggregation-layers/src/utils/scale-utils.js
test/modules/aggregation-layers/index.js
test/modules/aggregation-layers/utils/bin-sorter.spec.js
test/modules/aggregation-layers/utils/scale-utils.spec.js

- Calculate domain based on style type
- Add test to bin-sorter

Supporting quantile and other scale type in aggregation layer

---

modules/core/src/lib/layer.js

For bundle size optimization
- Use iteration to check change flag updates

Clean up change flags handling in Layer class

---

docs/layers/tile-3d-layer.md
docs/upgrade-guide.md
examples/website/3d-tiles/app.js
modules/geo-layers/src/tile-3d-layer/tile-3d-layer.js

- v8.0 API audit
- `onTileLoadFail` -> `onTileError`

Tile3DLayer: v8.0 audit

---

docs/layers/contour-layer.md
modules/aggregation-layers/src/contour-layer/contour-layer.js
modules/aggregation-layers/src/contour-layer/contour-utils.js
test/modules/aggregation-layers/contour-layer/contour-layer.spec.js

For #
ContourLayer: optimize sublayer prop setup, fix docs.

ContourLayer: optimize sublayer prop setup

---

test/modules/aggregation-layers/grid-aggregation-layer.spec.js

For #
- CellSize was too small taking too long to finish the test under headless mode.
- Increase the cell size and also enable more test cases.
- AggregationTests: update the test to reduce total run time

AggregationTests: update the test to reduce total run time

---

modules/aggregation-layers/src/cpu-grid-layer/cpu-grid-layer.js
modules/aggregation-layers/src/hexagon-layer/hexagon-layer.js
modules/aggregation-layers/src/utils/cpu-aggregator.js
test/modules/aggregation-layers/cpu-grid-layer/cpu-grid-layer.spec.js
test/modules/aggregation-layers/hexagon-layer.spec.js

For #
`filterData` is not a public API, rename it to`_filterData`.
-

Prop rename: filterData to _filterData

---

modules/layers/src/solid-polygon-layer/solid-polygon-layer-vertex-side.glsl.js

Seems to fix it for now. Would still like to dig in and find the root cause.
Temporary fix for #3886

Voodoo fix for polygon rendering on Linux/Intel

---

.travis.yml
bindings/python/pydeck/setup.py

For #
Porting required changes from #3817 CC: @ajduberstein 
-

Fix CI Build

---

docs/layers/arc-layer.md
docs/layers/column-layer.md
docs/layers/geojson-layer.md
docs/layers/icon-layer.md
docs/layers/line-layer.md
docs/layers/point-cloud-layer.md
docs/layers/polygon-layer.md
docs/layers/scatterplot-layer.md
docs/layers/scenegraph-layer.md
docs/layers/simple-mesh-layer.md
docs/layers/solid-polygon-layer.md
docs/layers/text-layer.md
examples/experimental/bezier/src/bezier-curve-layer/README.md

For #
[Doc]: update color prop description in all layers
Ref: #3358
-

 [Doc]: update color prop description in all layers

---

docs/layers/tile-layer.md
docs/upgrade-guide.md
modules/geo-layers/src/tile-layer/tile-layer.js

v8.0 API audit
- TileLayer: onViewportLoaded -> onViewportLoad

TileLayer: change onViewportLoaded to onViewportLoad

---

docs/api-reference/json/conversion-reference.md

For #3640
Documentation for new syntactic sugar
-

@deck.gl/json: Document new syntactic sugar

---

docs/api-reference/extensions/data-filter-extension.md

For #
Update data filter extension doc with aggregation layers limitations.
-

Doc: update data filter extension doc

---

docs/api-reference/layer.md
docs/developer-guide/performance.md
docs/layers/icon-layer.md
docs/layers/path-layer.md
docs/layers/solid-polygon-layer.md

For #3758 
- Docs and developer guide

Update documentation about using binary data

---

docs/whats-new.md

v8.0 what's new

---

bindings/python/pydeck/pydeck/widget/_frontend.py
modules/jupyter-widget/package.json
modules/jupyter-widget/src/create-deck.js
modules/jupyter-widget/src/index.js
modules/jupyter-widget/src/standalone-html-index.js
modules/jupyter-widget/webpack.config.js
test/render/jupyter-widget-test.html
yarn.lock

pydeck: Make a single bundle for use in standalone and Jupyter rendering

---

modules/geo-layers/src/s2-layer/s2-utils.js
test/modules/geo-layers/s2-layer.spec.js

For #4019 
- Make sure resolution is always an integer
- Unit tests

Fix s2 layer polygon generation

---

examples/playground/json-examples/3d-heatmap-minimap.json
examples/playground/json-examples/3d-heatmap.json
examples/playground/json-examples/line.json
examples/playground/json-examples/scatterplot.json
examples/playground/json-examples/screen-grid.json
examples/playground/json-examples/tagmap.json

Fix playground examples

---

modules/aggregation-layers/package.json
modules/core/package.json
modules/geo-layers/package.json
modules/jupyter-widget/package.json
modules/mesh-layers/package.json
modules/test-utils/package.json
package.json
test/modules/core/shaderlib/project/project-glsl-test-utils.js
yarn.lock

Bump math.gl and probe.gl dependencies

---

modules/aggregation-layers/src/cpu-grid-layer/grid-aggregator.js
modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-layer.js
modules/aggregation-layers/src/grid-aggregation-layer.js
test/modules/aggregation-layers/grid-aggregation-layer.spec.js
test/modules/aggregation-layers/grid-aggregator.spec.js
test/modules/aggregation-layers/utils/gpu-grid-aggregator.spec.js

For #3983
- [Fix] CPUAggregation: filter out points ouside of viewport bounds.

[Fix]: CPU Aggregation: filter out points outside of viewport.

---

docs/layers/contour-layer.md
docs/layers/screen-grid-layer.md
examples/website/screen-grid/app.js
modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.js
test/modules/aggregation-layers/gpu-grid-layer/gpu-grid-layer.spec.js

For #3983 
Fix invalid blend mode warnings.
ContourLayer: add missing prop documentation.
- Fix WebGL BlendEquation warnings

Fix WebGL BlendEquation warnings

---

scripts/bundle.config.js

Fix bundle transpilation

---

docs/README.md
docs/api-reference/attribute-manager.md
docs/api-reference/json/json-converter.md
docs/developer-guide/custom-layers/picking.md
docs/layers/tile-3d-layer.md

Fix broken links in docs

---

modules/aggregation-layers/src/aggregation-layer.js
modules/aggregation-layers/src/aggregation-layer.md
modules/aggregation-layers/src/contour-layer/contour-layer.js
modules/aggregation-layers/src/cpu-grid-layer/grid-aggregator.js
modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-layer.js
modules/aggregation-layers/src/grid-aggregation-layer.js
modules/aggregation-layers/src/grid-aggregation-layer.md
modules/aggregation-layers/src/heatmap-layer/heatmap-layer.js
modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer.js
modules/aggregation-layers/src/utils/gpu-grid-aggregation/aggregate-to-grid-vs.glsl.js
modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator-constants.js
modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.js
modules/aggregation-layers/src/utils/grid-aggregation-utils.js
modules/aggregation-layers/src/utils/prop-utils.js
test/browser.js
test/data/grid-aggregation-data.js
test/modules/aggregation-layers/aggregation-layer.spec.js
test/modules/aggregation-layers/cpu-grid-layer/cpu-grid-layer.spec.js
test/modules/aggregation-layers/grid-aggregation-layer.spec.js
test/modules/aggregation-layers/grid-layer.spec.js
test/modules/aggregation-layers/hexagon-layer.spec.js
test/modules/aggregation-layers/screen-grid-layer.spec.js
test/modules/aggregation-layers/utils/gpu-grid-aggregator.spec.js

For #3844
Different approach than : #3850
- Add support for `dimensions`
- Add support for detecting when positions changed or any attribute is changed.
- Add support for detecting when extension props changed.
- Update documents, and unit tests.
- AggregationLayer: add support for aggregation change detection.

AggregationLayer : Improve aggregation state management

---

modules/core/src/utils/math-utils.js
test/modules/core/lib/transition-manager.spec.js
test/modules/core/utils/math-utils.spec.js
test/modules/core/viewports/viewport.spec.js
test/modules/core/viewports/web-mercator-viewport.spec.js

Broken due to #3841 
- `fov` no longer depends on `height`
- `viewMatrix` now scales x and y as well as z
- Mercator common space y is flipped
Tested with /test/apps/frustum-culling

[WIP] Fix frustum plane calculation

---

examples/playground/json-examples/3d-tiles-royal.json
examples/playground/json-examples/3d-tiles-st-helens.json
examples/playground/src/configuration.js

Fix playground 3d tiles demos

---

.eslintrc.js
modules/aggregation-layers/package.json
modules/core/package.json
modules/core/src/lib/deck.js
modules/jupyter-widget/package.json
modules/mesh-layers/package.json
modules/test-utils/package.json
modules/test-utils/src/lifecycle-test.js
package.json
website/.eslintrc.js
yarn.lock

For #4072 
- Bump luma.gl dependencies to 8.0.1
- Try fix inline versioning

Bump dependencies

---

modules/aggregation-layers/package.json
modules/core/package.json
modules/geo-layers/package.json
yarn.lock

Fix flyToInterpolator crash when transitioning to the same viewport center

---

modules/core/src/lib/deck.js

`deck.setProps` runs ~30% faster, saves ~6ms/60 frames.
- Merge initialization checks
- Avoid creating new objects

Improve deck.setProps perf

---

bindings/python/pydeck/PUBLISH.md

pydeck: Correct PUBLISH.md typo

---

scripts/bundle.config.js

Exclude all Node polyfills
Saves ~5k off minified bundle

Update bundle config

---

modules/jupyter-widget/src/create-deck.js
modules/jupyter-widget/src/plugin.js
modules/jupyter-widget/src/version.js

Support Jupyter Lab and decrease bundle size.
For #3640 
-

@deck.gl/jupyter-widget: Read version and module name from bundle for JupyterLab

---

modules/react/src/utils/evaluate-children.js

to children with deckGLViewProps flag

update evaluate-children to pass deck gl view ports

---

test/apps/mapbox-tile/app.js
test/apps/mapbox-tile/index.html
test/apps/mapbox-tile/package.json
test/apps/mapbox-tile/utils/decode.js
test/apps/mapbox-tile/webpack.config.js

Update the dev configs and upgrade to deck v8

Fix mapbox tile test app

---

.readthedocs.yml
bindings/pydeck/LICENSE.txt
bindings/pydeck/docs/conf.py
bindings/pydeck/docs/layer.rst
bindings/pydeck/pydeck/bindings/deck.py
bindings/pydeck/pydeck/bindings/json_tools.py
bindings/pydeck/pydeck/bindings/layer.py
bindings/pydeck/pydeck/data_utils/color_scales.py
bindings/pydeck/pydeck/data_utils/type_checking.py
bindings/pydeck/pydeck/data_utils/viewport_helpers.py
scripts/bindings-precommit-hook.sh

For #3640
- Update docs with new syntax

pydeck: Update documentation for 0.2.0

---

website/package.json
website/scripts/build.sh
website/src/static/index-prod.html
website/src/static/index-staging.html

In `\website` directory, run `yarn build-staging`.

Add build-staging script to website

---

bindings/pydeck/README.md
modules/jupyter-widget/webpack.config.js

pydeck: Reduce JupyterLab bundle size

---

docs/api-reference/extensions/path-style-extension.md
docs/layers/h3-cluster-layer.md
docs/layers/h3-hexagon-layer.md

Minor documentation fixes

---

docs/developer-guide/performance.md
examples/experimental/interleaved-buffer/README.md
examples/experimental/interleaved-buffer/app.js
examples/experimental/interleaved-buffer/data.js
examples/experimental/interleaved-buffer/package.json
examples/experimental/interleaved-buffer/webpack.config.js

- Add an example to `experimental`

Add interleaved buffer example

---

modules/layers/package.json
modules/layers/src/icon-layer/icon-manager.js
package.json
yarn.lock

For #4132
- replace `loadImage` with `load` and `ImageLoader`

IconLayer: use load instead of loadImage to load icons

---

modules/core/package.json
yarn.lock

Bump mjolnir.js dependency

---

yarn.lock

- run `yarn upgrade`
- update `yarn.lock`

Bump yarn.lock

---

dev-docs/RFCs/v8.0/cpu-aggregation-refactor.md

For #3583 
RFC for CPU Aggregation refactor to integrate with `AttributeManager` and support data filtering.
- RFC: CPU Aggregation Refactor

RFC: CPU Aggregation Refactor

---

modules/layers/src/path-layer/path-layer-fragment.glsl.js
modules/layers/src/path-layer/path-layer-vertex.glsl.js
modules/layers/src/path-layer/path-layer.js

- Improve readability of the shader
- Correctness
SVG:
Before:
After:

Path layer vertex shader improvements

---

modules/aggregation-layers/package.json
modules/core/package.json
modules/jupyter-widget/package.json
modules/mesh-layers/package.json
modules/test-utils/package.json
package.json
yarn.lock

Bump luma dependency

---

modules/core/src/lib/attribute/attribute.js
test/modules/core/lib/attribute/attribute.spec.js

For #4181 
- Re-allocate buffer considering `byteOffset`
- Unit tests

Fix buffer size check in Attribute.updateBuffer

---

bindings/pydeck/examples/README.md
bindings/pydeck/examples/arc_layer.py
bindings/pydeck/examples/bitmap_layer.py
bindings/pydeck/examples/column_layer.py

For #4103 
- Add ArcLayer example
- Add BitmapLayer example

pydeck: ArcLayer, BitmapLayer, ColumnLayer examples

---

bindings/pydeck/pydeck/_version.py
bindings/pydeck/setup.py

For #4202 
!-- For other PRs without open issue -->
Dependency/setup changes to allow publishing to conda-forge
- Remove deprecated pytest-runner in order to allow publishing to conda-forge
- Exclude tests from build (still included in source distribution specified in MANIFEST.in)
- Bump version for release

pydeck: Update to 0.2.1

---

bindings/pydeck/CHANGELOG.md

For #4103 
Give pydeck its own changelog going forward
-

pydeck: Add CHANGELOG.MD

---

bindings/pydeck/examples/contour_layer.py
bindings/pydeck/examples/geojson_layer.py
bindings/pydeck/examples/heatmap_layer.py

For #4103
Three more entries for pydeck demos
Cattle vs poultry locations in New Mexico:
Cattle vs poultry locations in New Mexico:
Vancouver property prices
- New example files

pydeck: Add examples for ContourLayer, GeoJsonLayer, and HeatmapLayer

---

bindings/pydeck/PUBLISH.md
bindings/pydeck/README.md
bindings/pydeck/docs/index.rst

For #4103 
- Changed binder branch to use pydeck 0.2.1 and moved examples to the root of the Docker container

pydeck: Update mybinder URLs

---

bindings/pydeck/README.md

pydeck: Update README.md with conda usage

---

bindings/pydeck/examples/icon_layer.py
bindings/pydeck/examples/line_layer.py
bindings/pydeck/examples/path_layer.py

pydeck: Add IconLayer, LineLayer, and PathLayer examples

---

examples/layer-browser/package.json
examples/playground/package.json
modules/aggregation-layers/package.json
modules/core/package.json
modules/jupyter-widget/package.json
modules/mesh-layers/package.json
modules/test-utils/package.json
modules/test-utils/src/lifecycle-test.js
package.json
website-gatsby/package.json
yarn.lock

Also remove the VAO edge case handling from the layer lifecycle tests as they're no longer needed.

Bump luma to 8.1.0-alpha.2

---

modules/mapbox/src/deck-utils.js

- Repeat map at low zoom levels

[mapbox] support repeating at low zoom levels

---

modules/google-maps/src/google-maps-overlay.js
modules/google-maps/src/utils.js
test/modules/google-maps/mock-maps-api.js

Fixes issues from https://github.com/uber/deck.gl/pull/3643
For #4144 #3576
- Supports zoom 0-3

[google-maps] support lower zoom levels

---

examples/get-started/pure-js/google-maps/app.js
modules/google-maps/src/utils.js

For #4186 #4218
- Handle width = 0 case

Handle edge case in google-maps view state calculation

---

bindings/pydeck/examples/point_cloud_layer.py
bindings/pydeck/examples/polygon_layer.py

pydeck: Add PointCloudLayer and PolygonLayer examples

---

examples/experimental/terrain/package.json
examples/experimental/terrain/src/app.js
examples/experimental/terrain/src/locations.js
examples/experimental/terrain/src/surface.js
examples/experimental/terrain/src/terrain-layer/terrain-layer.js

Continuation of #4236 
- Add UI Controls for jumping to interesting locations, showing the terrain mesh wireframe, and picking different surface textures.
- Update Martini

Add additional controls to TerrainLayer example UI

---

bindings/pydeck/.gitignore
bindings/pydeck/bump_version.py
bindings/pydeck/pydeck/frontend_semver.py
bindings/pydeck/pydeck/io/html.py
bindings/pydeck/pydeck/widget/_frontend.py
bindings/pydeck/requirements-dev.txt
bindings/pydeck/setup.py

pydeck: Enforce pydeck notebook deck.gl semver on sdist

---

modules/google-maps/src/utils.js

For https://github.com/uber/deck.gl/issues/4218
- Safeguard against scale=0

[google-maps] fix occasional crash during resize

---

bindings/pydeck/.gitignore
bindings/pydeck/Makefile
bindings/pydeck/examples/_update_docs.py

Allow for quick visual review of pydeck examples and also support images for pydeck gallery pages
- Update Makefile command
- Add screenshot utility

pydeck: Add utility to convert pydeck examples to screenshots

---

docs/api-reference/composite-layer.md
docs/api-reference/layer.md
modules/core/src/lib/composite-layer.js
modules/core/src/lib/layer.js
modules/core/src/lifecycle/component-state.js
modules/geo-layers/src/tile-layer/tile-layer.js
modules/layers/src/icon-layer/icon-layer.js
modules/layers/src/icon-layer/icon-manager.js
modules/test-utils/src/snapshot-test-runner.js
test/modules/core/lib/composite-layer.spec.js
test/modules/core/lib/layer.spec.js
test/render/test-cases/icon-layer.js

For #4091 
- `Layer.isLoaded`
- `CompositeLayer.isLoaded`
- Rename `IconManager.loaded` to `IconManager.isLoaded`
- Tests

Add layer.isLoaded

---

docs/api-reference/viewport.md
docs/api-reference/web-mercator-viewport.md

For https://github.com/uber/deck.gl/issues/4280

Update outdated viewport docs

---

website/src/components/input.js
website/src/utils/format-utils.js

For https://github.com/uber/deck.gl/issues/4279

[website] Handle color type: null

---

docs/layers/README.md
docs/layers/terrain-layer.md
docs/table-of-contents.json
examples/experimental/terrain/package.json
examples/experimental/terrain/src/app.js
modules/core/package.json
modules/geo-layers/package.json
modules/geo-layers/src/terrain-layer/terrain-layer.js
modules/jupyter-widget/package.json
modules/layers/package.json
modules/main/src/index.js
test/modules/geo-layers/index.js
test/modules/geo-layers/terrain-layer.spec.js
website/contents/pages.js
website/package.json
website/src/components/demos/layer-demos.js
yarn.lock

For #4236 
- Adding TerrainLayer to @deck.gl/geo-layers
- Updating loaders.gl
- TerrainLayer Documentation
- TODO before land: clean up experimental examples (add advance example to somewhere else).

TerrainLayer integration

---

modules/arcgis/src/arcgis-deck-external-renderer.js
modules/arcgis/src/arcgis-deck-layer-view-2d.js
modules/arcgis/src/commons.js
modules/core/bundle/lumagl.js

Update arcgis module to use luma.gl instead of raw gl calls as much as possible.

Use luma.gl in arcgis module

---

bindings/pydeck/Makefile
bindings/pydeck/bump_version.py

For #4103
- Add Make command for test.pypi publication
- Remove unused arguments in bump_version.py

pydeck: Add additional publishing scripts

---

bindings/pydeck/requirements-dev.txt
bindings/pydeck/setup.py
bindings/pydeck/tests/dev-containers/build-and-screenshot.sh
bindings/pydeck/tests/dev-containers/jupyterlab/Dockerfile
bindings/pydeck/tests/dev-containers/jupyternb/Dockerfile

For #4103 
Continue to modify new pydeck release tools for use in the 0.3.0 release
-

pydeck: Update release requirements for 0.3.0

---

docs/layers/tile-layer.md
modules/geo-layers/src/tile-layer/tile-layer.js
modules/geo-layers/src/tile-layer/tileset-2d.js
modules/geo-layers/src/tile-layer/utils.js
test/modules/geo-layers/tile-layer/utils.spec.js

For https://github.com/uber/deck.gl/issues/4331
- Add `tileSize` prop to TileLayer
- Unit tests
- Docs

TileLayer: expose tileSize prop

---

examples/README.md
examples/layer-browser/README.md

Update outdated READMEs in the examples directory

---

docs/layers/README.md
docs/layers/mvt-tile-layer.md
docs/table-of-contents.json
website/contents/pages.js
website/src/components/demos/layer-demos.js

Needed after #3935
Once MVT Tile Layer is merged, we need to have docs so that users know how to use the layer properly.
- Add MVT Tile Layer docs

Add MVTTileLayer docs

---

modules/geo-layers/src/terrain-layer/terrain-layer.js

- Handle cached data (non-promise)
- Propagate parent layer props: `pickable`, `opacity`, `modelMatrix` etc.

Terrain layer bug fixes

---

modules/jupyter-widget/src/create-deck.js
modules/jupyter-widget/src/script-utils.js

Fix bug where custom module classes are only installed in the first cell after page reload. 
For #
-

pydeck: fix repeated script loading

---

docs/layers/bitmap-layer.md
docs/layers/terrain-layer.md
examples/website/terrain/app.js
modules/geo-layers/src/mvt-layer/mvt-layer.js
modules/geo-layers/src/terrain-layer/terrain-layer.js
modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js
test/modules/geo-layers/terrain-layer.spec.js
test/render/test-cases/mvt-layer.js
website/src/components/demos/terrain-demo.js

For #4317 #4346
- Rename `terrainImage` to `elevationData`
- Rename `surfaceImage` to `texture`
- Docs

Terrain layer API audit

---

docs/layers/tile-3d-layer.md
docs/upgrade-guide.md
examples/layer-browser/package.json
examples/playground/package.json
examples/website/3d-tiles/app.js
examples/website/3d-tiles/package.json
examples/website/3d-tiles/webpack.config.js
examples/website/mesh/package.json
examples/website/point-cloud/package.json
examples/website/scenegraph-layer/package.json
modules/core/package.json
modules/geo-layers/package.json
modules/geo-layers/src/tile-3d-layer/tile-3d-layer.js
modules/jupyter-widget/package.json
modules/jupyter-widget/src/create-deck.js
modules/layers/package.json
package.json
website-gatsby/package.json
website/package.json
website/src/components/demos/tiles-3d-demo.js
yarn.lock

- loaders.gl v2.1 refactors change the tile loaders api
- Tile3DLayer API change
This PR depends on loaders.gl v2.1

geo-layers: refactor tile-3d-layer

---

docs/README.md
docs/api-reference/attribute-manager.md
docs/api-reference/deck.md
docs/api-reference/layer.md
docs/developer-guide/custom-layers/layer-extensions.md
docs/developer-guide/custom-layers/picking.md
docs/developer-guide/custom-layers/primitive-layers.md
docs/developer-guide/custom-layers/writing-shaders.md
docs/developer-guide/tips-and-tricks.md
docs/effects/lighting-effect.md
docs/effects/post-process-effect.md
docs/layers/scenegraph-layer.md
docs/layers/simple-mesh-layer.md
docs/upgrade-guide.md

Fix broken luma.gl doc links

---

docs/layers/tile-3d-layer.md
website/package.json

tile-3d-layer: fix doc

---

docs/api-reference/arcgis/deck-renderer.md
docs/api-reference/arcgis/overview.md
docs/upgrade-guide.md
docs/whats-new.md

8.1 what's new and upgrade guide

---

modules/layers/src/icon-layer/icon-layer.js
modules/layers/src/icon-layer/icon-manager.js

For #4316
- pass layer's `loadOptions` to `IconManager`

layers: pass loadOptoins to IconManager from IconLayer

---

modules/layers/src/geojson-layer/geojson-layer.js
test/modules/layers/geojson-layer.spec.js

For https://github.com/uber/deck.gl/pull/4365
- Forward `highlightedObjectIndex`

Fix GeoJsonLayer's handling of highlightedObjectIndex

---

docs/api-reference/deck.md

For # NA
- this section is out of date with the current metrics
-

Update _onMetrics callback documentation

---

docs/api-reference/layer.md

For https://github.com/uber/deck.gl/issues/4414

Fix sample code in layer.md

---

modules/jupyter-widget/src/create-deck.js

For https://github.com/uber-web/loaders.gl/issues/710
- Remove 3D tile loader from @deck.gl/jupyter-widget

@deck.gl/jupyter-widget: Remove Tiles3DLoader

---

bindings/pydeck/.gitignore
bindings/pydeck/examples/custom_layer.py
bindings/pydeck/pydeck/frontend_semver.py

pydeck: Update custom layer example

---

bindings/pydeck/.gitignore

For #4103
- Add to python gitignore

pydeck: Update .gitignore

---

bindings/pydeck/docs/Makefile
bindings/pydeck/docs/conf.py
bindings/pydeck/docs/scripts/embed_examples.py

For #4103
- Push makefile hook into conf script
- Change .rst templating tool to error on machines that don't have a Mapbox token

pydeck: Change Sphinx documentation conf.py

---

.readthedocs.yml

pydeck: Update readthedocs.yml

---

bindings/pydeck/PUBLISH.md
bindings/pydeck/docs/installation.rst

pydeck: Fix some spelling in docs

---

docs/api-reference/web-mercator-viewport.md

- document `fitBounds` on `WebMercatorViewport`
it is not currently documented but given as an example here https://github.com/uber/deck.gl/blob/master/docs/developer-guide/views.md#viewport 
- `docs/api-reference/web-mercator-viewport.md`

doc: document WebMercatorViewport.fitBounds

---

bindings/pydeck/examples/01 - Introduction.ipynb
bindings/pydeck/examples/02 - Scatterplots.ipynb
bindings/pydeck/examples/03 - Using pydeck to manipulate data.ipynb

pydeck: Update example notebooks for 0.3.0

---

docs/layers/tile-layer.md

Fixes typo in docs
- Removed a duplicated word in the docs

fix double word

---

bindings/pydeck/docs/CHANGELOG.rst
bindings/pydeck/pydeck/frontend_semver.py

pydeck: Lock pydeck to deck.gl semver ~8.1.*

---

examples/get-started/pure-js/harp.gl/README.md
examples/get-started/pure-js/harp.gl/app.js
examples/get-started/pure-js/harp.gl/decoder.js
examples/get-started/pure-js/harp.gl/index.html
examples/get-started/pure-js/harp.gl/package.json
examples/get-started/pure-js/harp.gl/webpack.config.js
examples/get-started/scripting/harp.gl/index.html

- get-started example for harp.gl

Add harp.gl example

---

docs/api-reference/layer.md
modules/aggregation-layers/package.json
modules/core/package.json
modules/core/src/lib/layer.js
modules/core/src/lib/picking/pick-info.js
modules/extensions/package.json
modules/jupyter-widget/package.json
modules/mesh-layers/package.json
modules/test-utils/package.json
package.json
test/modules/core/lib/picking.spec.js
yarn.lock

For https://github.com/visgl/deck.gl/issues/3803
- Bump luma.gl (fixed picking uniform normalization)
- Support per-object highlightcolor
- Docs

Support per-object highlightColor

---

.travis.yml

pydeck: Update Travis CI build command

---

website/src/static/markdown/showcase.md

Shorter description to avoid text clipping

Update website showcase page

---

docs/api-reference/mapbox/mapbox-layer.md
docs/api-reference/mapbox/overview.md

- Consistent capitalization of `Mapbox` in prose
- Update Mapbox, deck.gl version numbers
- Add React example of injecting deck.gl layers into Mapbox, including responses from https://github.com/visgl/deck.gl/issues/4521

Update MapboxLayer docs

---

docs/api-reference/viewport.md

- Add example for `getFrustumPlanes()`

Update viewport doc

---

modules/aggregation-layers/src/utils/bin-sorter.js
test/modules/aggregation-layers/utils/bin-sorter.spec.js

- this improvement will account for all type of values including 'string'

[bin-sortor] correctly sort all values

---

bindings/pydeck/.flake8
bindings/pydeck/Makefile
bindings/pydeck/examples/great_circle_layer.py
bindings/pydeck/examples/h3_cluster_layer.py
bindings/pydeck/pydeck.json
bindings/pydeck/tests/bindings/data_utils/test_binary_transfer.py
bindings/pydeck/tests/bindings/pydeck_examples/hexagon_layer_function.py
bindings/pydeck/tests/bindings/pydeck_examples/multilayers.py
bindings/pydeck/tests/bindings/test_deck.py
bindings/pydeck/tests/bindings/test_layer.py
bindings/pydeck/tests/browser/screenshot_utils.py
bindings/pydeck/tests/browser/test_html_renderer.py
bindings/pydeck/tests/test_settings.py

Move flake8 linter configuration into a config file
Updates flake8
-

pydeck: Update flake8 config

---

package.json

- Update project description
- Fix invalid JSON
- Remove `dependencies` (`esri-loader` is specified as a dependency in the arcgis module)

Root package.json clean up

---

bindings/pydeck/pydeck/widget/widget.py
modules/jupyter-widget/src/playground/playground.js

pydeck + @deck.gl/jupyter-widget: Support bidirectional communication with new transport abstraction

---

test/modules/jupyter-widget/binary-transport.spec.js
test/modules/jupyter-widget/create-deck.spec.js
test/modules/jupyter-widget/index.spec.js
test/modules/jupyter-widget/widget-tooltip.spec.js

- Prefer ES6 `import` to `require`

Standardize jupyter-widget tests

---

modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer-fragment.glsl.js

For #4647
- fix TextLayer support for opacity

Fix TextLayer support for opacity

---

docs/api-reference/globe-view.md
docs/api-reference/globe-viewport.md
docs/table-of-contents.json
modules/core/src/controllers/globe-controller.js
modules/core/src/controllers/map-controller.js
modules/core/src/index.js
modules/core/src/lib/constants.js
modules/core/src/viewports/globe-viewport.js
modules/core/src/viewports/viewport.js
modules/core/src/views/globe-view.js
modules/main/src/index.js
test/modules/core/controllers/controllers.spec.js
test/modules/core/lib/transition-manager.spec.js
test/modules/core/viewports/globe-viewport.spec.js
test/modules/core/viewports/index.js
test/modules/core/views/view.spec.js
website/contents/pages.js

For #4638
- Add experimental classes `GlobeView`, `GlobeViewport` and `GlobeController`
- docs
- unit tests

Globe Projection (PR 1)

---

modules/aggregation-layers/package.json
modules/core/package.json
modules/extensions/package.json
modules/geo-layers/package.json
modules/geo-layers/src/tile-3d-layer/tile-3d-layer.js
modules/jupyter-widget/package.json
modules/layers/package.json
modules/layers/src/icon-layer/icon-manager.js
modules/mesh-layers/package.json
modules/test-utils/package.json
package.json
test/apps/glsl-debugger/package.json
website-gatsby/package.json
yarn.lock

- Bump math.gl and loaders.gl to the latest production
- Bump luma.gl to 8.2 beta
- Fix IconManager support for ImageBitmap

Bump math.gl and loaders.gl

---

modules/core/package.json
modules/geo-layers/package.json
modules/jupyter-widget/package.json
modules/layers/package.json
package.json
yarn.lock

Bump loaders.gl to 2.2.2

---

bindings/pydeck/examples/03 - Using pydeck to manipulate data.ipynb
bindings/pydeck/tests/notebooks/test_nbconvert.py

Skips test that relies on the live Singapore taxi data API
- Deactivate test
- Add comment in example notebook warning against issues with the data

pydeck: Update tests for interaction handling notebook

---

bindings/pydeck/README.md

pydeck: Add downloads badge to README

---

modules/core/src/controllers/controller.js
modules/core/src/controllers/map-controller.js
modules/core/src/controllers/orbit-controller.js
modules/core/src/lib/view-manager.js
modules/core/src/views/first-person-view.js
modules/core/src/views/globe-view.js
modules/core/src/views/orbit-view.js
modules/core/src/views/orthographic-view.js
modules/core/src/views/view.js
test/modules/core/controllers/test-controller.js
test/modules/core/views/view.spec.js

Follow up of https://github.com/visgl/deck.gl/pull/4639#discussion_r434899510
- Remove `ViewState.ViewportType`, add `ViewState.makeViewport`
- Make sure the same props are used to resolve viewport and controller props
- Tests

Improve the consistency of controller behavior

---

docs/api-reference/globe-view.md
examples/experimental/interleaved-buffer/README.md
examples/get-started/pure-js/arcgis/README.md
examples/get-started/pure-js/basic/README.md
examples/get-started/pure-js/globe/README.md
examples/get-started/pure-js/globe/app.js
examples/get-started/pure-js/globe/package.json
examples/get-started/pure-js/globe/webpack.config.js
examples/get-started/pure-js/google-maps/README.md
examples/get-started/pure-js/harp.gl/README.md
examples/get-started/pure-js/mapbox/README.md
examples/get-started/react/basic/README.md
examples/get-started/react/mapbox-browserify/README.md
examples/get-started/react/mapbox/README.md
examples/get-started/scripting/globe/index.html

For #4717 
- Add get-started examples
- Add remarks to GlobeView doc

Add globe examples to get-started

---

docs/layers/tile-layer.md
docs/upgrade-guide.md
docs/whats-new.md

v8.2 what's new

---

modules/geo-layers/src/tile-layer/tile-layer.js
modules/geo-layers/src/tile-layer/tileset-2d.js
test/modules/geo-layers/tile-layer/tile-2d-header.spec.js

- When maxRequests <= 0, set `throttleRequests` to `false`
- Docs to be updated in #4705

Remove throttleRequests TileLayer prop

---

modules/core/src/controllers/transition-manager.js
modules/core/src/transitions/linear-interpolator.js
test/modules/core/transitions/linear-interpolator.spec.js

- Bring in https://github.com/visgl/react-map-gl/pull/1080
- Fix crash in keyboard navigation/double click zoom if `initialViewState` does not spefify `pitch` or `bearing`

Fix transition bugs

---

scripts/update-release-branch.sh
website/gatsby-config.js
website/package.json
website/scripts/build.sh

For #4717
- Fix update release branch script for new website setup
- Add Google Analytics tracking
- Fix worker transpilation

Fix website build issues

---

docs/api-reference/extensions/brushing-extension.md
docs/api-reference/extensions/data-filter-extension.md
docs/api-reference/extensions/fill-style-extension.md
docs/table-of-contents.json

Missed these when migrating to Gatsby.

Add missing doc pages

---

modules/mapbox/src/deck-utils.js
test/modules/mapbox/mapbox-layer.spec.js

Fix MapboxLayer error after Deck is finalized

---

website/src/examples/point-cloud-layer.js
website/src/examples/scatterplot-layer.js
website/src/examples/screen-grid-layer.js

For https://github.com/visgl/deck.gl/issues/4780

Fix source code links in some website examples

---

modules/layers/src/arc-layer/arc-layer-vertex.glsl.js

see #4772
Should fix this example when using an up to date version of deck.gl

ArcLayer: Make source and target available for injection

---

package.json
yarn.lock

For https://github.com/visgl/deck.gl/issues/4789
- Bump `@babel/*`

bump babel dependencies

---

modules/core/src/lib/attribute/data-column.js
modules/core/src/lib/deck-picker.js
modules/core/src/lib/deck.js
modules/core/src/utils/typed-array-manager.js

For #
- Add experimental/unsafe options to control memory usage (array pool size, CPU buffer copies, FBO creation)
-

core: Add experimental optimization options

---

bindings/pydeck/requirements/requirements-rtd.txt

Support the Geopandas example in the documentation
- Add pandas and geopandas to the documentation requirements

pydeck: Update readthedocs.io documentation requirements

---

examples/website/icon/README.md

Fix 404 for docs link of IconLayer

---

bindings/pydeck/examples/globe_view.py

Add missing data source comment.
- Add comment
- Remove unused keyword `get_line_color`
- Add water geojson

pydeck: Add comment to GlobeView example

---

bindings/pydeck/examples/03 - Event handlers and data selection in pydeck.ipynb
bindings/pydeck/pydeck/bindings/deck.py
bindings/pydeck/pydeck/io/templates/index.j2
bindings/pydeck/pydeck/widget/debounce.py
bindings/pydeck/pydeck/widget/widget.py
bindings/pydeck/setup.py
modules/jupyter-widget/src/lib/jupyter-transport-view.js
modules/jupyter-widget/src/playground/create-deck.js
modules/jupyter-widget/src/playground/playground.js
modules/jupyter-widget/src/playground/utils/css-utils.js

For #3864 etc
Exploring an approach for adding generic event handling to pydeck.
-

jupyter-widget:  sketch for generic event handling

---

modules/core/bundle/deckgl.js

For #4809
- Support changing mapStyle in standalone bundle

Support changing mapStyle in standalone bundle

---

bindings/pydeck/docs/conf.py
bindings/pydeck/docs/scripts/const.py
bindings/pydeck/docs/scripts/embed_examples.py
bindings/pydeck/docs/scripts/generate_grid_html.py
bindings/pydeck/docs/scripts/templates.py
bindings/pydeck/docs/scripts/update_images_rst.py
bindings/pydeck/docs/scripts/utils.py
bindings/pydeck/examples/globe_view.py
bindings/pydeck/pydeck/bindings/deck.py
bindings/pydeck/pydeck/widget/debounce.py
bindings/pydeck/pydeck/widget/widget.py

pydeck: Apply formatter

---

bindings/pydeck/setup.py

This change properly excludes the tests folder, and as such it will not be installed in the users Python environment.
Fixes: #4907

Fix exclusion of tests folder

---

modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer.js
modules/layers/src/text-layer/text-layer.js
test/modules/layers/text-layer/text-layer.spec.js

For #4910 
- Fix `sdf` prop propagation
- Set `MultiIconLayer`'s `alphaCutoff` to 0
- Unit test

Fix TextLayer sdf mode

---

docs/api-reference/geo-layers/tile-layer.md
modules/geo-layers/src/tile-layer/tile-layer.js
modules/geo-layers/src/tile-layer/tileset-2d.js
test/modules/geo-layers/tile-layer/tileset-2d.spec.js

For [#4935](https://github.com/visgl/deck.gl/issues/4935)

Add onTileUnload callback for TileLayer

---

modules/aggregation-layers/package.json
modules/carto/package.json
modules/core/package.json
modules/geo-layers/package.json
modules/jupyter-widget/package.json
modules/layers/package.json
package.json
yarn.lock

- loaders -> 2.3.0-beta
- math -> 3.3.0-beta

Bump loaders.gl and math.gl dependencies

---

test/modules/geo-layers/tile-layer/tileset-2d.spec.js

- Fix unhandled promise rejection in Tileset2D test

Fix test error

---

examples/get-started/pure-js/arcgis/app.js
examples/get-started/pure-js/arcgis/package.json

For #4985
- Add missing `@deck.gl/arcgis` dependency
- Lock arcgis version to 4.15

Fix arcgis example

---

examples/get-started/pure-js/arcgis/app.js
modules/arcgis/src/deck-props.js

For #4985
See also #4992
- Use `for .. of Accessor.keys()` instead of `for .. in Accessor.properties` in `deck-props.js`.

[arcgis] Fix rendering in the latest esri release

---

modules/core/src/lib/init.js

For #2169
- Change default `imagebitmap.premultiplyAlpha` to `none`

Change ImageLoader default option

---

modules/core/src/lib/deck-picker.js
modules/core/src/lib/picking/pick-info.js
test/modules/core/lib/deck-picker.spec.js

For #4808
- Do not create picking FBO if no layers are pickable

Picking optimization

---

docs/developer-guide/tips-and-tricks.md
docs/upgrade-guide.md
docs/whats-new.md

8.3 What's New

---

docs/README.md
docs/developer-guide/interactivity.md
docs/table-of-contents.json

For https://github.com/visgl/deck.gl/issues/5008
- Fix example in tooltip guide
- Add missing pages to TOC

Fix doc issues

---

examples/website/3d-heatmap/README.md
examples/website/3d-tiles/README.md
examples/website/3d-tiles/index.html
examples/website/arc/README.md
examples/website/carto-sql/README.md
examples/website/data-filter/README.md
examples/website/geojson/README.md
examples/website/heatmap/README.md
examples/website/highway/README.md
examples/website/icon/README.md
examples/website/image-tile/README.md
examples/website/line/README.md
examples/website/map-tile/README.md
examples/website/mesh/README.md
examples/website/plot/README.md
examples/website/point-cloud/README.md
examples/website/point-cloud/index.html
examples/website/scatterplot/README.md
examples/website/scenegraph/README.md
examples/website/screen-grid/README.md
examples/website/tagmap/README.md
examples/website/terrain/README.md
examples/website/trips/README.md
website/src/examples/text-layer.js

For #4998
- Update example readmes to correct broken documentation links & add proper attribution

Examples readme pass

---

examples/website/election/README.md
examples/website/election/app.js
examples/website/election/index.html
examples/website/election/map-style.js
examples/website/election/package.json
examples/website/election/webpack.config.js

Add Google Maps example

---

examples/website/election/README.md
examples/website/election/app.js
examples/website/election/index.html
examples/website/election/map-style.js
examples/website/election/package.json
examples/website/election/webpack.config.js
examples/website/i3s/README.md
examples/website/i3s/app.js
examples/website/i3s/index.html
examples/website/i3s/package.json
examples/website/i3s/webpack.config.js

Add ArcGIS/I3s and Google Maps examples (#5017) (#5018)

---

examples/playground/json-examples/carto-bq-tiler.json
examples/playground/json-examples/carto-sql.json
examples/playground/json-examples/index.js
examples/playground/src/configuration.js

CARTO layers don't work in the playground, this PR tries to fix that.

Playground compatible with CARTO layers

---

docs/api-reference/layers/bitmap-layer.md
modules/layers/src/bitmap-layer/bitmap-layer.js

For #4966
- Add `textureParameters` prop to `BitmapLayer`

Add textureParameters prop to BitmapLayer

---

docs/api-reference/mesh-layers/scenegraph-layer.md
website/src/doc-demos/mesh-layers.js

For #4574
Adding embedded animated ScenegraphLayer to docs.
-

[ScenegrapchLayer] Add embedded demo

---

modules/layers/src/geojson-layer/geojson-layer.js
modules/layers/src/polygon-layer/polygon-layer.js

Polygon layer fill should not update when line color update triggers change
Signed-off-by: Shan He <heshan0131@gmail.com>

Fix a bug polygon fill layer updates when line color changes

---

docs/api-reference/geo-layers/mvt-layer.md
docs/api-reference/geo-layers/tile-layer.md
modules/core/src/lib/deck-picker.js
modules/geo-layers/src/mvt-layer/mvt-layer.js
modules/geo-layers/src/tile-layer/tile-layer.js

Related with https://github.com/visgl/deck.gl/issues/4952
I still need to add the tests, but I’d really appreciate some feedback from your side.
We do a double transformation of coordinates when this feature is enabled: one for rendering and we add another one to compare against the frustum panels. We’ll need some guidance to improve that.
Any feedback is more than welcome!

onViewportFeatures function callback in MVTLayer

---

docs/api-reference/layers/icon-layer.md
modules/layers/src/icon-layer/icon-layer.js
modules/layers/src/icon-layer/icon-manager.js
test/modules/layers/icon-manager.spec.js

For #4152
- Add `onIconError` callback to `IconLayer`
- Unit test

Add onIconError to IconLayer

---

docs/api-reference/aggregation-layers/cpu-grid-layer.md
docs/api-reference/aggregation-layers/gpu-grid-layer.md
docs/api-reference/aggregation-layers/grid-layer.md
docs/api-reference/aggregation-layers/heatmap-layer.md
docs/api-reference/aggregation-layers/hexagon-layer.md

- Fix broken image link
- Remove unnecessary requirement of "6 colors"
- Explain how mapping works

Update docs for colorRange

---

modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer.js
test/modules/layers/text-layer/text-layer.spec.js

Change default alphaCutoff to non-zero

---

modules/core/src/lib/attribute/data-column.js
modules/core/src/lib/layer.js
modules/core/src/utils/typed-array-manager.js
test/modules/core/lib/attribute/attribute.spec.js
test/modules/core/lib/layer.spec.js
test/modules/core/utils/typed-array-manager.spec.js

Cherry-pick overallocation fixes for 8.3.7

---

docs/README.md
docs/developer-guide/interactivity.md
docs/developer-guide/using-layers.md
docs/developer-guide/viewports.md
docs/get-started/getting-started.md
docs/get-started/using-standalone.md
docs/get-started/using-with-map.md
docs/get-started/using-with-react.md

Addressing comments from #4634

Update interaction docs

---

docs/api-reference/core/controller.md
modules/core/src/controllers/controller.js
modules/core/src/controllers/globe-controller.js
modules/core/src/controllers/map-controller.js
modules/core/src/controllers/orthographic-controller.js

- Add `dragMode` to controller options

Expose option to flip pan/rotate in controllers

---

docs/api-reference/core/controller.md
modules/core/src/controllers/controller.js
modules/core/src/controllers/first-person-controller.js
modules/core/src/controllers/map-controller.js
modules/core/src/controllers/orbit-controller.js

For https://github.com/visgl/deck.gl/issues/5089
- Allow options passed to `controller.keyboard` (see documentation)
- Docs

Expose hard-coded keyboard control parameters

---

modules/layers/src/text-layer/text-layer.js
modules/layers/src/text-layer/utils.js
test/modules/layers/text-layer/text-layer.spec.js
test/modules/layers/text-layer/utils.spec.js

For #5164
- TextLayer support Unicode characters
- Add code to missing character warning
- Test

Fix TextLayer handling of unicode characters

---

bindings/pydeck/docs/installation.rst

For #5109
- Make it clearer that the installation instructions were not written with Windows in mind.

pydeck: Update installation instructions

---

docs/api-reference/core/layer.md
docs/api-reference/geo-layers/mvt-layer.md
docs/api-reference/geo-layers/terrain-layer.md
docs/api-reference/geo-layers/tile-3d-layer.md
docs/api-reference/layers/bitmap-layer.md
docs/api-reference/layers/icon-layer.md
docs/api-reference/mesh-layers/scenegraph-layer.md

For https://github.com/visgl/loaders.gl/issues/981
- Document `loadOptions` prop

Document loadOptions prop

---

docs/api-reference/layers/bitmap-layer.md
docs/api-reference/layers/icon-layer.md
docs/api-reference/mesh-layers/simple-mesh-layer.md
docs/developer-guide/custom-layers/prop-types.md
modules/core/src/lifecycle/prop-types.js
modules/core/src/utils/texture.js
modules/layers/src/bitmap-layer/bitmap-layer.js
modules/layers/src/icon-layer/icon-layer.js
modules/layers/src/icon-layer/icon-manager.js
modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js
test/modules/core/lifecycle/component-state.spec.js
test/render/test-cases/icon-layer.js

- Consolidate image->texture conversion in various layers, providing consistent behavior
- Unit tests

Add image prop type

---

docs/api-reference/geo-layers/h3-cluster-layer.md
docs/api-reference/geo-layers/h3-hexagon-layer.md
docs/api-reference/layers/icon-layer.md
docs/api-reference/test-utils/snapshot-test-runner.md
docs/api-reference/test-utils/test-layer.md
docs/developer-guide/coordinate-systems.md
docs/developer-guide/testing.md
docs/get-started/getting-started.md
docs/whats-new.md

Update outdated links in docs

---

modules/core/src/lib/deck.js

Pass onError prop to AnimationLoop

---

modules/layers/src/text-layer/text-layer.js

Fix TextLayer transition forwarding

---

modules/core/src/lib/attribute/attribute-transition-manager.js
modules/core/src/lib/attribute/attribute.js
modules/core/src/lib/layer.js

- Remove unused `uniforms` from Layer.defaultProps
- Add explicit declaration for `transition`

Remove unused layer prop

---

website/src/doc-demos/codepen-automation.js
website/src/doc-demos/codepen.js
website/src/doc-demos/layer-demo.js
website/src/doc-demos/layers.js

Follow up of https://github.com/visgl/deck.gl/pull/5205#issuecomment-738200562
[Staging](https://pessimistress.github.io/deck.gl/docs/api-reference/aggregation-layers/heatmap-layer)
- Populate Codepen source with unused props

Add unused props to codepen source

---

docs/api-reference/mesh-layers/simple-mesh-layer.md
modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js
website/package.json
website/src/doc-demos/mesh-layers.js

- Fix sample code
- Clarify `mesh` prop usage
- Add embedded demo

Improve SimpleMeshLayer documentation

---

docs/api-reference/layers/text-layer.md

For #5281
- Document correct default values

Fix default values in TextLayer documentation

---

modules/geo-layers/src/h3-layers/h3-cluster-layer.js
modules/geo-layers/src/h3-layers/h3-hexagon-layer.js

For https://github.com/visgl/deck.gl/issues/5286
- Forward `transitions` prop to sub layers

Fix h3 layers transitions

---

modules/carto/src/index.js
test/modules/carto/api/maps-api-client.spec.js
test/modules/carto/config.spec.js
test/modules/carto/index.js

The goal of this pr is to improve the test coverage of the CARTO module, especially `src/api/maps-api-client`.
- Unit tests

CARTO: Improve /api test coverage

---

docs/api-reference/core/layer.md
docs/api-reference/geo-layers/great-circle-layer.md
docs/api-reference/geo-layers/terrain-layer.md
docs/api-reference/geo-layers/tile-3d-layer.md
docs/api-reference/geo-layers/trips-layer.md

For #5294
- Document correct peer dependencies for geo-layers module

Fix geo-layers module peer dependencies in documentation

---

modules/core/src/lib/deck-picker.js
modules/core/src/lib/layer.js
modules/layers/src/path-layer/path-layer.js
modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
test/modules/core/lib/layer.spec.js
test/modules/core/lib/pick-layers.spec.js
yarn.lock

For #5295
- Fix clearPickingColor in PathLayer and SolidPolygonLayer when used as sub layers of a GeoJsonLayer
- Test

Fix multi-depth picking for GeoJsonLayer

---

docs/api-reference/core/layer.md
docs/developer-guide/loading-data.md
docs/table-of-contents.json

For #5263
- Add "loading data" developer guide

Add loaders documentation

---

examples/get-started/pure-js/carto/app.js
modules/carto/src/api/maps-api-client.js
modules/carto/src/config.js
modules/carto/src/layers/carto-bqtiler-layer.js
modules/carto/src/layers/carto-layer.js
modules/carto/src/layers/carto-sql-layer.js
test/modules/carto/api/maps-api-client.spec.js
test/modules/carto/carto-bqtiler-layer.spec.js
test/modules/carto/carto-sql-layer.spec.js
test/modules/carto/mock-fetch.js

Include support for the new endpoints of Maps API v2.

CARTO module: Integrate Maps API v2 endpoints

---

modules/geo-layers/src/tile-3d-layer/tile-3d-layer.js

Tile3DLayer: more reliable isLoaded test

---

examples/gallery/src/tile-3d-layer.html

For https://github.com/visgl/deck.gl/issues/5358

Fix Tile3DLayer example in gallery

---

modules/core/src/controllers/controller.js
modules/core/src/controllers/transition-manager.js
test/modules/core/controllers/controllers.spec.js
test/modules/core/controllers/test-controller.js
test/modules/core/lib/transition-manager.spec.js

Same as #5349, accidentally closed

Controller inertia (2/3): maintain correct interaction state in controller

---

docs/api-reference/core/controller.md
modules/core/src/controllers/controller.js
test/modules/core/controllers/controllers.spec.js
test/modules/core/controllers/test-controller.js

For #5089 
- Add smooth scroll zooming
- Add `inertia` option to controller
- Test

Controller inertia (3/3): add inertia option to controllers

---

modules/aggregation-layers/package.json
modules/core/package.json
modules/extensions/package.json
modules/jupyter-widget/package.json
modules/mesh-layers/package.json
modules/test-utils/package.json
package.json
yarn.lock

For https://github.com/visgl/deck.gl/issues/5373

Bump luma.gl to 8.4.0-beta

---

docs/api-reference/core/deck.md
modules/core/src/lib/deck.js

For #5089
- Expose EventManager recognizer options

Expose EventManager recognizer options

---

docs/api-reference/core/deck.md
modules/core/src/lib/deck.js
modules/core/src/lib/view-manager.js

For #5089
- Add `onInteractionStateChange` callback to Deck

Add onInteractionStateChange callback

---

docs/api-reference/geo-layers/mvt-layer.md
docs/upgrade-guide.md
docs/whats-new.md

For #5373 
@ajduberstein Anything significant from the pydeck side?

8.4 what's new and upgrade guide

---

docs/api-reference/core/first-person-view.md
docs/api-reference/core/globe-view.md
docs/api-reference/core/map-view.md
docs/api-reference/core/orbit-view.md
docs/api-reference/core/orthographic-view.md
examples/website/point-cloud/app.js
examples/website/point-cloud/package.json
website/package.json
website/src/doc-demos/aggregation-layers.js
website/src/doc-demos/codepen-automation.js
website/src/doc-demos/demo-base.js
website/src/doc-demos/geo-layers.js
website/src/doc-demos/layers.js
website/src/doc-demos/mesh-layers.js
website/src/doc-demos/views.js

For #5373 
- Add embedded demos to *View doc pages

Add embedded demo to View documentation pages

---

docs/README.md

- Update badge in docs' home page to 8.4

Update badge in docs' home page to 8.4

---

bindings/pydeck/pydeck/settings.py

For #5063
Trying to improve the custom library writing process in order to move 3rd party collaborations (e.g. carto+pydeck) into their own modules.

pydeck: Update custom library registration

---

.github/workflows/website.yml
examples/website/360-video/app.js
examples/website/image-tile/app.js
website/package.json
website/scripts/build.sh
website/scripts/validate-token.js

- Add workflow
- Fix various server-side rendering errors and script failures
Tested in 8.4-release branch: https://github.com/visgl/deck.gl/actions/runs/529467853

Automated website publish workflow

---

modules/core/src/lib/view-manager.js
test/modules/core/controllers/test-controller.js
test/modules/core/lib/view-manager.spec.js

For #5430
- Force numeric dimensions in `controller.makeViewport`
- Unit tests

Fix controller.makeViewport when using percentage dimensions

---

modules/aggregation-layers/package.json
modules/core/package.json
modules/extensions/package.json
modules/jupyter-widget/package.json
modules/mesh-layers/package.json
package.json
yarn.lock

To include https://github.com/visgl/luma.gl/pull/1449

Bump luma.gl dependencies

---

dev-docs/RFCs/proposals/instance-culling-rfc.md
dev-docs/RFCs/proposals/scengraph-layer-lod-rfc.md

- Per discussion in the deck.gl forum around the instance x vertex perf issue for ScenegraphLayer
- New RFC

docs(RFC): Instance Culling RFC

---

modules/aggregation-layers/src/utils/grid-aggregation-utils.js
modules/core/src/controllers/controller.js
modules/core/src/controllers/map-controller.js
modules/core/src/controllers/view-state.js
modules/core/src/lib/attribute/attribute.js
modules/core/src/lib/deck-picker.js
modules/core/src/lib/deck.js
modules/core/src/lib/layer.js
modules/core/src/lib/view-manager.js
modules/core/src/shaderlib/project/viewport-uniforms.js
modules/core/src/utils/tesselator.js
modules/layers/src/column-layer/column-geometry.js
modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js
test/modules/core/controllers/view-states.spec.js

- remove assertions that are not caused by user error - internal calls should always perform safety check instead of throwing
- Add actionable comment/messages to the remaining assertions

Clean up assertions in core and layer modules

---

dev-docs/roadmaps/tile-layer-roadmap.md

This is a starting point for a roadmap for `TileLayer`, to get agreement / share awareness on technical directions.
I suspect we may be doing significant amount of engineering work on this layer (or a fork of it) during the 8.x release cycle, and there are several big PRs open on it, so a little bit of direction will surely not hurt.
For #
-

TileLayer Roadmap

---

modules/core/src/lib/layer-manager.js

For https://github.com/visgl/deck.gl/issues/5398
`layerManager.setProps` immediately performs recursive updates (initialization, update and finalization) if `props.layers` is set. This behavior is inconsistent with other `setProps` methods in `DeckRenderer`, `DeckPicker`, `ViewManager`, and `EffectManager`. Anywhere else `setProps` is a cheap call and no change is actually applied until the next render frame. This behavior has two problems:
- It increases the surface area that triggers WebGL operations, making it harder to block errors when the WebGLContext is lost.
- It is possible, in e.g. React, that `setProps` is called multiple times in between two render frames.
- Do not perform layer updates during `setProps`
This PR is not intended to cause any visible behavioral change.

LayerManager: avoid layer update during setProps

---

modules/react/src/deckgl.js
modules/react/src/utils/position-children-under-views.js
modules/react/src/utils/use-isomorphic-layout-effect.js
test/modules/react/deckgl.spec.js

This PR brings the `DeckGL` component to compliance with the latest React release. It also addresses some long-standing issues in the React module, including #4358, #4513, #4550.
- Migrate DeckGL to a functional component
- Unit tests

Migrate DeckGL to functional component

---

examples/get-started/react/arcgis/README.md
examples/get-started/react/arcgis/app.js
examples/get-started/react/arcgis/index.html
examples/get-started/react/arcgis/package.json
examples/get-started/react/arcgis/webpack.config.js
examples/get-started/react/mapbox/app.js
examples/get-started/react/mapbox/package.json

- Add react-arcgis example
- Add `<NavigationControl>` to react-map-gl example

Update React examples

---

modules/react/src/deckgl.js

For https://github.com/visgl/deck.gl/issues/4550#issuecomment-782781318
- In React strict mode, each render is executed twice, yet `useEffect`/`useLayoutEffect` are executed only once.
- We call `deck.setProps` in every render. When a transition is triggered, a deferred `onViewStateChange` call is scheduled. In `useLayoutEffect` we execute the deferred `onViewStateChange` call to avoid setting state inside a render cycle.
- Due to deck's own prop comparison logic, `onViewStateChange` is only invoked the first of the two renders, while React only execute `useLayoutEffect` in the second of the two renders.
- Track requested state changes across multiple renders

[react] Fix flickering in React.StrictMode

---

docs/api-reference/layers/grid-cell-layer.md

For https://github.com/visgl/deck.gl/issues/5523

Correct getPosition description in GridCellLayer doc

---

examples/layer-browser/package.json
examples/playground/package.json
examples/website/3d-tiles/package.json
examples/website/globe/package.json
examples/website/i3s/package.json
examples/website/mesh/package.json
examples/website/point-cloud/package.json
examples/website/radio/package.json
examples/website/safegraph/package.json
examples/website/scenegraph/package.json
modules/carto/package.json
modules/core/package.json
modules/geo-layers/package.json
modules/jupyter-widget/package.json
modules/layers/package.json
modules/mesh-layers/package.json
package.json
test/apps/arcgis-i3s/package.json
website/package.json
website/src/doc-demos/mesh-layers.js
website/yarn.lock
yarn.lock

Updated `@loaders.gl` version to `3.0.0-alpha`

Change loaders version to ^3.0.0-alpha

---

.nycrc
docs/developer-guide/building-apps.md
docs/upgrade-guide.md
modules/aggregation-layers/package.json
modules/arcgis/package.json
modules/carto/package.json
modules/core/package.json
modules/extensions/package.json
modules/geo-layers/package.json
modules/google-maps/package.json
modules/json/package.json
modules/layers/package.json
modules/main/package.json
modules/mapbox/package.json
modules/mesh-layers/package.json
modules/react/package.json
modules/test-utils/package.json
package.json
scripts/bundle.config.js
test/bench/node.js
test/node.js
yarn.lock

- Upgrade ocular-dev-tools
- Upgrade puppeteer
- Drop ES6 dist entry point

Change build targets

---

bindings/pydeck/examples/binary_transport.py

Binary transport example occasionally crashes because no target is specified in the viewport
-

pydeck: Update binary transport example

---

modules/mapbox/src/deck-utils.js

https://github.com/visgl/deck.gl/issues/5564

[mapbox] unset touchAction when using external gl context

---

docs/api-reference/carto/carto-bqtiler-layer.md
docs/api-reference/carto/overview.md
docs/api-reference/geo-layers/mvt-layer.md

docs: update default carto mapsUrl & fix mvtlayer methods section

---

package.json
tsconfig.json
yarn.lock

For #5589
- Adds a tsconfig and installs typescript
- To see errors that need to be fixed, run `npx tsc --noEmit`
- As above

chore: Add .tsconfig

---

.github/workflows/test.yml
modules/core/src/lib/layer-manager.js

For #5600 
- Set onError before setLayers.

[fix] set onError before setLayers

---

modules/core/src/lib/deck.js

Revert "[feat] WebGL context lost handling > pass to listeners of onError"

---

modules/aggregation-layers/src/heatmap-layer/heatmap-layer.js
test/render/test-cases/heatmap-layer.js

For #5248 
- Fix common bounds calculation in offset coordinate modes
- Render test

Fix HeatmapLayer in offset mode

---

bindings/pydeck/pydeck/io/html.py

For #5514 
Add HTML viewer for pydeck in Colab

Add one-way Google Colab support

---

docs/api-reference/google-maps/google-maps-overlay.md

- Update google-maps-overlay.md, fix spelling of style prop

Update google-maps-overlay.md, fix spelling of style prop

---

docs/api-reference/layers/column-layer.md

Fix ColumnLayer angle prop documentation

---

modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer.js

For #5699
- Use CPU aggregation results if GPU aggregation is disabled

Fix ScreenGridLayer picking w/ cpu aggregation

---

docs/api-reference/core/deck.md
docs/upgrade-guide.md
modules/core/src/lib/deck.js
modules/core/src/lib/layer-manager.js
modules/core/src/passes/layers-pass.js
test/modules/core/lib/layer-manager.spec.js

Properly address https://github.com/visgl/deck.gl/pull/5399#discussion_r599123866
- Change onError callback args
- Change onError default

Update onError callback default

---

modules/core/src/lib/deck.js

Clean up Deck's internal method bindings

---

modules/core/src/lib/deck.js

Invoke onError when GL context is lost

---

docs/developer-guide/views.md

Fix broken link in views.md

---

examples/layer-browser/package.json
examples/playground/package.json
examples/website/3d-tiles/package.json
examples/website/globe/package.json
examples/website/i3s/package.json
examples/website/mesh/package.json
examples/website/point-cloud/package.json
examples/website/radio/package.json
examples/website/safegraph/package.json
examples/website/scenegraph/package.json
modules/carto/package.json
modules/core/package.json
modules/geo-layers/package.json
modules/jupyter-widget/package.json
modules/layers/package.json
modules/mesh-layers/package.json
package.json
test/apps/arcgis-i3s/package.json
website/package.json
yarn.lock

Dependency bump to fix https://github.com/visgl/deck.gl/issues/5775

Bump @loaders.gl to 3.0.0-alpha.14

---

examples/layer-browser/package.json
examples/playground/package.json
examples/website/3d-tiles/package.json
examples/website/globe/package.json
examples/website/i3s/package.json
examples/website/mesh/package.json
examples/website/point-cloud/package.json
examples/website/radio/package.json
examples/website/safegraph/package.json
examples/website/scenegraph/package.json
modules/carto/package.json
modules/core/package.json
modules/geo-layers/package.json
modules/jupyter-widget/package.json
modules/layers/package.json
modules/mesh-layers/package.json
package.json
test/apps/arcgis-i3s/package.json
website/package.json
yarn.lock

Bump @loaders.gl to 3.0.0-alpha.16 to pick up earcut migration to math.gl

---

modules/geo-layers/src/tile-3d-layer/tile-3d-layer.js

For #5806 
- use geometry indices

geo: i3s - support indices

---

test/modules/geo-layers/mvt-layer.spec.js
test/modules/geo-layers/terrain-layer.spec.js
test/modules/geo-layers/tile-3d-layer/tile-3d-layer.spec.js
test/node.js

- Make `fetch` available in Node tests

Polyfill fetch for node tests

---

docs/api-reference/geo-layers/mvt-layer.md

Update to documentation as requested in https://github.com/visgl/deck.gl/pull/5800

MVTLayer binary prop documentation update

---

dev-docs/RFCs/proposals/loader-worker-triangulation.md

RFC for implementing triangulation of polygons in loader web worker for MVTLayers

RFC for implementing triangulation of polygons in loader web worker for MVTLayers

---

examples/website/plot/app.js
modules/core/src/controllers/orbit-controller.js
modules/core/src/views/orbit-view.js

Follow up of #5824
- Refactor OrbitController to use consistent logic with MapController
- Fix zoom drifting in OrbitController

Refactor OrbitController

---

modules/aggregation-layers/src/heatmap-layer/heatmap-layer.js

For #5781
- Fix `colorDomain` in `MEAN` mode

Fix heatmap colorDomain

---

modules/core/src/lib/view-manager.js

For #5845
- When a new controller is added, invalidate all controllers below it so that events are registered in the correct order

Fix event order when dynamically add/remove controllers

---

docs/api-reference/layers/geojson-layer.md
modules/layers/src/geojson-layer/geojson-layer.js

For #5819
- Fix inconsistent sub layer id

Fix inconsistent path layer id in GeoJSONLayer

---

.github/workflows/release.yml
scripts/github-release.js

Publish release notes to https://github.com/visgl/deck.gl/releases
- New workflow

Add automated release workflow

---

modules/geo-layers/src/tile-3d-layer/tile-3d-layer.js

New implementation for https://github.com/visgl/deck.gl/pull/5831
- Use `filterSubLayers` method in `Tile3DLayer`

geo: tile-3d viewport filter

---

examples/get-started/pure-js/arcgis/app.js
examples/get-started/pure-js/basic/app.js
examples/get-started/pure-js/carto/app.js
examples/get-started/pure-js/globe/app.js
examples/get-started/pure-js/google-maps/app.js
examples/get-started/pure-js/harp.gl/app.js
examples/get-started/pure-js/mapbox/app.js
examples/get-started/react/arcgis/app.js
examples/get-started/react/basic/app.js
examples/get-started/react/mapbox/app.js
examples/get-started/scripting/arcgis/index.html
examples/get-started/scripting/basic/index.html
examples/get-started/scripting/carto/index.html
examples/get-started/scripting/globe/index.html
examples/get-started/scripting/google-maps/index.html
examples/get-started/scripting/harp.gl/index.html
examples/get-started/scripting/mapbox/index.html
examples/layer-browser/src/examples/core-layers.js

For #5815
Follow up of #5835
- GeoJsonLayer prop in examples

Update deprecated prop names in examples

---

.github/workflows/release.yml

`create` event does not seem to work as expected

Try fix release action trigger

---

docs/api-reference/core/layer.md

Companion for https://github.com/danmarshall/deckgl-typings/pull/198

Fix type documentation for parameters in LayerProps

---

docs/api-reference/carto/carto-layer.md
docs/api-reference/carto/overview.md

- Improve docs for CARTO submodule

Update CARTO docs

---

docs/api-reference/layers/text-layer.md

For #5836
- Add remarks regarding web fonts and unicode support

Update TextLayer documentation

---

examples/get-started/pure-js/leaflet/README.md
examples/get-started/pure-js/leaflet/app.js
examples/get-started/pure-js/leaflet/index.html
examples/get-started/pure-js/leaflet/package.json
examples/get-started/pure-js/leaflet/webpack.config.js
examples/get-started/scripting/leaflet/index.html

Get-started examples using deck.gl-leaflet by @zakjan

Add leaflet examples

---

docs/api-reference/core/deckgl.md
docs/get-started/using-with-map.md

- Refresh the content of https://deck.gl/docs/get-started/using-with-map
- Add support matrix
- Add example for using maplibre-gl

Update docs about base map usage

---

modules/core/src/lib/view-manager.js

For #5903
- Fix check for new controller added scenario

Fix: new controller added check

---

modules/core/src/lib/view-manager.js
test/modules/core/lib/view-manager.spec.js

For #5917 
Fallout of #5908
- Check if `oldController` exists before finalizing
- Tests

Fix ViewManager crash on multi-view

---

docs/get-started/learning-resources.md

+ change `deck.gl's` to `deck.gl`

Add RandomFractals DeckGL Collection to learning-resources

---

modules/core/src/passes/screen-pass.js

For #5797
- Reset viewport in `ScreenPass`

Fix PostProcessEffect in multi-view

---

docs/api-reference/carto/carto-layer.md

For #
- Changed text about how to access CARTO 3

CARTO module docs: update overview for CARTO 3

---

docs/api-reference/carto/carto-bqtiler-layer.md

For #
- Fixed a couple of typos

Fixed a couple of typos

---

docs/api-reference/carto/overview.md

Update docs overview for CARTO 3

CARTO modulue docs: update overview for CARTO 3

---

docs/api-reference/carto/carto-bqtiler-layer.md
docs/api-reference/carto/carto-layer.md
docs/api-reference/carto/overview.md

Improve/fix language issues in carto module documentation

Update CARTO module documentation

---

docs/api-reference/geo-layers/tile-3d-layer.md
docs/developer-guide/views.md
docs/upgrade-guide.md
docs/whats-new.md

v8.5 what's new and upgrade guide

---

examples/website/mesh/package.json
modules/aggregation-layers/package.json
modules/carto/package.json
modules/core/package.json
modules/geo-layers/package.json
modules/layers/package.json
yarn.lock

Bump math.gl to 3.5.1

---

examples/layer-browser/package.json
examples/playground/package.json
examples/website/3d-tiles/package.json
examples/website/globe/package.json
examples/website/i3s/package.json
examples/website/mesh/package.json
examples/website/point-cloud/package.json
examples/website/radio/package.json
examples/website/safegraph/package.json
examples/website/scenegraph/package.json
modules/aggregation-layers/package.json
modules/carto/package.json
modules/core/package.json
modules/extensions/package.json
modules/geo-layers/package.json
modules/jupyter-widget/package.json
modules/layers/package.json
modules/mesh-layers/package.json
modules/test-utils/package.json
package.json
test/apps/arcgis-i3s/package.json
test/apps/glsl-debugger/package.json
website/package.json
yarn.lock

Bump loaders.gl to 3.0.2, luma.gl to 8.5.0

---

modules/geo-layers/src/mvt-layer/mvt-layer.js
modules/layers/src/geojson-layer/geojson-binary.js
modules/layers/src/index.js
test/modules/geo-layers/mvt-layer.spec.js
test/modules/layers/geojson-binary.spec.js

Bug fix for https://github.com/visgl/deck.gl/issues/5958. 
Once a loaders.gl package is published with https://github.com/visgl/loaders.gl/commit/b28556d7d5925a819897a3352b91c3cdae6f5834 included I'll update this PR. 
I've tested locally with the updated tests

Binary MVTLayer returns geometry when picking

---

examples/playground/json-examples/3d-heatmap-minimap.json
examples/playground/json-examples/3d-heatmap.json

For #5948 
`@loaders.gl/csv` breaking change

Fix playground heatmap examples

---

examples/website/map-tile/app.js

Add copyright and license link to TileLayer example

---

docs/whats-new.md
modules/aggregation-layers/package.json
modules/core/package.json
modules/extensions/package.json
modules/geo-layers/package.json
modules/jupyter-widget/package.json
modules/mesh-layers/package.json
package.json
yarn.lock

Bring in the fix for https://github.com/visgl/luma.gl/issues/1481
- Bump  luma.gl to 8.5.4

Bump luma.gl

---

modules/layers/src/geojson-layer/geojson-layer.js

- more accurate check on sub layer ids

GeoJsonLayer auto highlighting improvement

---

CONTRIBUTING.md

Updating CARTO contributors

---

modules/react/src/deckgl.js

For #6052
- Decouple React update and Deck redraw flag

Fix MapboxLayer React integration

---

docs/api-reference/core/composite-layer.md

The `filterSubLayer` method was added in 8.5 to improve TileLayer/Tile3DLayer performance.
- Add missing documentation

Document CompositeLayer's filterSubLayer method

---

test/modules/jupyter-widget/mock-widget-base.js

For #6063
-  Add DummyManager class

Expand DummyWidget class for @deck.gl/jupyter-widget tests

---

docs/api-reference/google-maps/google-maps-overlay.md
docs/api-reference/google-maps/overview.md
docs/whats-new.md

Updates to docs as part of https://github.com/visgl/deck.gl/issues/5980

Document Google Vector Maps overlay

---

modules/geo-layers/src/tile-3d-layer/tile-3d-layer.js

Changes in terms of https://github.com/visgl/deck.gl/pull/4388 for Tile3DLayer

Add zero _offset to Tile3DLayer

---

docs/developer-guide/views.md
docs/upgrade-guide.md
modules/core/src/lib/picking/pick-info.js
modules/core/src/lifecycle/component.js
modules/core/src/passes/layers-pass.js
test/modules/core/passes/layers-pass.spec.js

For #5970
-  Only call`layerFilter` with top-level layers
- Tests

Only call layerFilter with top-level layers

---

docs/api-reference/carto/carto-layer.md
modules/carto/src/api/maps-v3-client.js
modules/carto/src/layers/carto-layer.js
test/modules/carto/api/maps-api-client.spec.js
test/modules/carto/carto-layer.spec.js

Implementation of https://github.com/visgl/deck.gl/issues/6096

Add geoColumn & columns props to CartoLayer

---

bindings/pydeck/setup.py

This makes it easier for automatic license checkers to verify the license of this package.
For #
-

Use official OSI name in the license metadata

---

docs/upgrade-guide.md

https://github.com/visgl/deck.gl/discussions/6176
- improve wording in 8.5 upgrade guide

Improve the wording of billboard mode pixel size fix in the upgrade guide

---

test/modules/geo-layers/mvt-layer.spec.js
test/modules/geo-layers/tile-layer/tile-layer.spec.js

echo.jsontest.com no longer seems to work
- Swap dummy data to our own source

[chore] fix request failures in unit tests

---

docs/api-reference/aggregation-layers/screen-grid-layer.md
docs/api-reference/layers/bitmap-layer.md
docs/api-reference/layers/icon-layer.md
docs/api-reference/mapbox/overview.md
docs/api-reference/mesh-layers/simple-mesh-layer.md
docs/developer-guide/64-bits.md
docs/developer-guide/tips-and-tricks.md
docs/whats-new.md

Misc doc updates

---

docs/developer-guide/performance.md

Quick typo fix!  Thanks a ton for this awesome library :)

docs: fix typo (recalculat -> recalculate)

---

modules/core/src/lib/deck-picker.js
modules/core/src/lib/picking/pick-info.js
modules/core/src/lib/picking/query-object.js
modules/core/src/passes/layers-pass.js
modules/core/src/passes/pick-layers-pass.js
test/modules/core/lib/picking.spec.js

See discussion in #6152
This change also sets up for alternative picking color encoding should we decide to implement further optimizations.
- Consolidate code that determines whether a layer should be drawn
- Encode layer index more efficiently
- Only warn about layer count limit if more than 255 layers are drawn
- Unit tests

Improve picking index encoding

---

docs/api-reference/core/layer.md
docs/api-reference/core/project.md
docs/api-reference/geo-layers/tile-3d-layer.md
docs/api-reference/layers/arc-layer.md
docs/api-reference/layers/column-layer.md
docs/api-reference/layers/geojson-layer.md
docs/api-reference/layers/icon-layer.md
docs/api-reference/layers/line-layer.md
docs/api-reference/layers/path-layer.md
docs/api-reference/layers/point-cloud-layer.md
docs/api-reference/layers/polygon-layer.md
docs/api-reference/layers/scatterplot-layer.md
docs/api-reference/layers/text-layer.md
docs/developer-guide/coordinate-systems.md
docs/upgrade-guide.md

For #6181 
- Documenting changes made in #6117 

Documentation for new size unit system

---

bindings/pydeck/docs/installation.rst

Makes it a bit more clear since pydeck is now on 0.7.
Or perhaps could just remove any mentions of the version at all?
- Update version info in pydeck docs

Update version info in pydeck docs

---

modules/carto/src/api/index.js
modules/carto/src/api/maps-v3-client.js
modules/carto/src/index.js
test/modules/carto/api/maps-api-client.spec.js

For https://github.com/visgl/deck.gl/issues/6354
- Add `getLayerData` function
- Tests for new URL schema parameter

Add getLayerData function to CARTO module

---

modules/carto/package.json
modules/carto/src/api/index.js
modules/carto/src/api/layer-map.js
modules/carto/src/api/maps-v3-client.js
modules/carto/src/api/parseMap.js
modules/carto/src/index.js
test/apps/carto-map/app.js
test/apps/carto-map/index.html
test/apps/carto-map/package.json
yarn.lock

For https://github.com/visgl/deck.gl/issues/6337
- Add `getMap` function for fetching a set of predefined layers from CARTO
- Example app to compare output for a given map id
- Implementation of autoRefresh to periodically update layers when data from datasources changes
Test updates and documentation to follow in separate PR

Add `fetchMap` function to carto module

---

docs/api-reference/arcgis/deck-layer.md
docs/api-reference/arcgis/deck-renderer.md
docs/api-reference/arcgis/load-arcgis-modules.md
docs/api-reference/arcgis/overview.md
examples/get-started/pure-js/arcgis/app.js
examples/get-started/pure-js/arcgis/package.json
examples/get-started/react/arcgis/package.json
modules/arcgis/bundle.js
modules/arcgis/package.json
modules/arcgis/src/deck-props.js
modules/arcgis/src/index.js
modules/arcgis/src/load-modules.js
package.json
yarn.lock

For #6033
- Support using `@deck.gl/arcgis` with `@arcgis/core`
- Update example to use esm

[arcgis] support ES modules

---

docs/developer-guide/custom-layers/writing-shaders.md

This doc with lower case chars was leading to misunderstandings

Hooks names must be uppercase

---

CONTRIBUTING.md

Accidental find, fixed using GitHub web UI

Fix GitHub Profile URL for Víctor Velarde

---

modules/core/src/lib/deck-picker.js
test/modules/core/lib/pick-layers.spec.js

For #6362
Fallout of #6184
- Remove ad-hoc picking color decoding
- Unit test

Fix multi-depth picking with layerFilter

---

modules/carto/src/api/layer-map.js
modules/carto/src/api/parseMap.js
test/modules/carto/data/visState.json

For https://github.com/visgl/deck.gl/issues/6337
- Pass through CARTO layer label

Pass through CARTO label

---

modules/carto/src/api/maps-v3-client.js
test/modules/carto/api/maps-api-client.spec.js

For https://github.com/visgl/deck.gl/issues/6424
- Rename publicToken to token in `fetchMap`
- Test update

Rename publicToken to token

---

package.json

chore: Remove time from lint command

---

examples/layer-browser/package.json
examples/playground/package.json
examples/website/3d-tiles/package.json
examples/website/globe/package.json
examples/website/i3s/package.json
examples/website/mesh/package.json
examples/website/point-cloud/package.json
examples/website/radio/package.json
examples/website/safegraph/package.json
modules/carto/package.json
modules/core/package.json
modules/geo-layers/package.json
modules/jupyter-widget/package.json
modules/layers/package.json
modules/mesh-layers/package.json
package.json
test/apps/arcgis-i3s/package.json
website/package.json
yarn.lock

For #
- Upgrade to loaders.gl 3.1.0-beta.2
- package.json deps

chore: loaders.gl@3.1.0-beta.5

---

examples/webpack.config.local.js

For #5589 
- Handle .ts files in src

Fix local webpack config

---

docs/developer-guide/loading-data.md

Fixed erroneus property in loading-data documentation

---

modules/geo-layers/src/terrain-layer/terrain-layer.js

For https://github.com/visgl/deck.gl/issues/6451
Use more generic viewport handling.
This change unblocks the `TerrainLayer` from being used in `OrthographicView` and `OrbitView`. The layer still does not work in `GlobeView` (would require the `TerrainLoader` transform Mercator coordinates that the tiles are encoded in back to lngLat).
cc @ibgreen @igorDykhta to see if `GlobeView` support is of interest.
- Remove WebMercatorViewport specific code from `getTerrainData`

TerrainLayer handle non-WebMercator viewports

---

examples/layer-browser/package.json
examples/playground/package.json
examples/website/3d-tiles/package.json
examples/website/globe/package.json
examples/website/i3s/package.json
examples/website/mesh/package.json
examples/website/point-cloud/package.json
examples/website/radio/package.json
examples/website/safegraph/package.json
modules/carto/package.json
modules/core/package.json
modules/geo-layers/package.json
modules/jupyter-widget/package.json
modules/layers/package.json
modules/mesh-layers/package.json
package.json
website/package.json

chore: Bump to loaders.gl@3.1.0

---

examples/layer-browser/package.json
examples/playground/package.json
examples/website/3d-tiles/package.json
examples/website/globe/package.json
examples/website/i3s/package.json
examples/website/mesh/package.json
examples/website/point-cloud/package.json
examples/website/radio/package.json
examples/website/safegraph/package.json
modules/carto/package.json
modules/core/package.json
modules/geo-layers/package.json
modules/jupyter-widget/package.json
modules/layers/package.json
modules/mesh-layers/package.json
package.json
website/package.json
yarn.lock

For https://github.com/visgl/deck.gl/issues/6528

Bump loaders.gl to 3.1.5

---

modules/geo-layers/src/tile-layer/utils.js
test/modules/geo-layers/tile-layer/utils.spec.js

For #6546
- Replace multiple occurrences in URL template
- Unit test

Fix TileLayer url template resolution

---

docs/api-reference/google-maps/google-maps-overlay.md
modules/google-maps/src/google-maps-overlay.js
modules/google-maps/src/utils.js
test/modules/google-maps/mock-maps-api.js

For https://github.com/visgl/deck.gl/issues/6578
- Switch to new API & classes
- Update tests
- Update doc links

Update to new Google Maps API

---

modules/core/src/lib/attribute/attribute-manager.js
modules/core/src/lib/attribute/data-column.js
test/modules/core/lib/attribute/attribute.spec.js

For #4161 
- Add `getBounds()` method to `Attribute`
- Unit tests

Add getBounds method to Attribute

---

modules/core/package.json
modules/core/src/effects/mask/mask-effect.js
modules/core/src/lib/attribute/data-column.js
modules/core/src/lib/effect.ts
modules/core/src/lifecycle/component-state.ts
modules/mesh-layers/package.json
modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.ts
test/modules/core/effects/mask-effect.spec.js
test/modules/geo-layers/tile-layer/tileset-2d.spec.js
yarn.lock

For https://github.com/visgl/deck.gl/issues/6552
- Tidy up lint warnings introduced by work on MaskExtension
- Clean up existing lint warnings

chore: lint fixes

---

docs/api-reference/extensions/mask-extension.md

For #6552 
Embedded example: https://codepen.io/vis-gl/pen/ExbKoYg
- Add documentation for MaskExtension

Add MaskExtension documentation

---

docs/api-reference/carto/fetch-map.md
examples/get-started/pure-js/carto/app.js
examples/get-started/scripting/carto/index.html

We need to improve the documentation for the fetchMap function in the CARTO module and update the CARTO map ID used in the get started examples.
- Improve documentation for fetchMap function
- Update cartoMapID in examples

Update fetchMap docs and example

---

modules/core/src/lib/layer.js

For #6660
- Explicitly define `dataComparator` type

Ignore dataComparator change in props diff

---

docs/api-reference/extensions/overview.md
docs/table-of-contents.json

Website update for https://github.com/visgl/deck.gl/issues/6652
- Add missing links to extensions and order alphabetically for consistency

Correct links to all extensions

---

modules/carto/src/layers/carto-layer.js

CartoLayer was not setting the formatTiles prop for CartoTileLayer. So, if the backend returns the formatTiles to geojson it was ignoring it and try to load it as binary tiles

CARTO: Fix formatTiles propagation at CartoLayer

---

test/apps/carto-dynamic-tile/app.js

Add more datasets to demo app for dynamic tiling

CARTO: update test app dynamic tiling

---

website/src/doc-demos/geo-layers.js

QuadkeyLayer needs to be imported

Fix: missing QuadkeyLayer import for website 

---

docs/api-reference/carto/fetch-map.md

We need to update the image in the fetchMap API reference within the CARTO submodule docs to show the end-to-end process.
- Update fetchMap image pointing to the deck.gl-data repo

Update fetchMap image

---

docs/whats-new.md

For #
- Keep the release notes focused on deck.gl.
-

Neutral release notes

---

docs/api-reference/carto/carto-layer.md
docs/whats-new.md

For https://github.com/visgl/deck.gl/issues/6652
- Correct outdated documentation in CARTO module
- Update CARTO docs link in whats-new

CARTO docs update

---

modules/carto/src/api/maps-v3-client.ts
modules/carto/src/api/parseMap.ts

Fixes regression in https://github.com/visgl/deck.gl/pull/6761

Force GeoJSON for geojson/point fetchMap layers

---

modules/layers/src/bitmap-layer/bitmap-layer-vertex.js

For #6798
- BitmapLayer vertex shader emits correct common position in LNGLAT_AUTO_OFFSET mode

Fix BitmapLayer imageCoordinateSystem: LNGLAT

---

modules/core/src/lib/deck-picker.ts
modules/core/src/lib/layer.js
modules/core/src/lib/picking/pick-info.ts
modules/core/src/lib/picking/query-object.ts
modules/core/src/passes/layers-pass.ts
modules/core/src/passes/pick-layers-pass.ts

For #5589 
- `DeckPicker` and utils

Migrate core/picking to TypeScript

---

modules/core/src/lib/attribute/attribute-manager.ts
modules/core/src/lib/composite-layer.ts
modules/core/src/lib/constants.ts
modules/core/src/lib/deck-picker.ts
modules/core/src/lib/layer-manager.ts
modules/core/src/lib/layer-state.ts
modules/core/src/lib/layer.ts
modules/core/src/lib/picking/pick-info.ts
modules/core/src/lifecycle/component-state.ts
modules/core/src/lifecycle/component.ts
modules/core/src/lifecycle/props.ts
modules/core/src/passes/layers-pass.ts
modules/core/src/shaderlib/project/project-functions.ts
modules/core/src/types/layer-props.ts
modules/core/src/utils/count.ts
modules/core/src/utils/flatten.ts
modules/core/src/utils/memoize.ts
modules/core/src/utils/typed-array-manager.ts
test/modules/core/lib/layer.spec.js
test/modules/core/lifecycle/component-state.spec.js
test/modules/core/lifecycle/props.spec.js

For #5589 
- Layer, CompositeLayer, LayerManager

Migrate Layer class to TypeScript

---

modules/carto/package.json
modules/carto/src/api/maps-api-common.ts
modules/carto/src/api/maps-v3-client.ts
modules/carto/src/index.ts
modules/carto/src/layers/carto-layer.ts

[ts] CartoLayer (carto)

---

modules/google-maps/package.json
modules/google-maps/src/google-maps-overlay.ts
modules/google-maps/src/index.ts
modules/google-maps/src/utils.ts
yarn.lock

Change List:
* Convert GoogleMapsOverlay to Typescript

[ts] GoogleMapsOverlay converted to Typescript.

---

modules/carto/src/api/maps-api-common.ts
modules/carto/src/api/maps-v3-client.ts
test/modules/carto/api/maps-api-client.spec.js

For https://github.com/visgl/deck.gl/issues/6832

CARTO: Do not send schema to CARTO API

---

docs/api-reference/core/view.md
modules/core/src/lib/view-manager.ts
modules/core/src/viewports/orthographic-viewport.ts
modules/core/src/viewports/viewport.ts
modules/core/src/views/view.ts
test/modules/core/viewports/web-mercator-viewport.spec.js
test/modules/core/views/view.spec.js

For #6548 
- Add `offset` parameter to View (see documentation)
- Unit tests

Add view parameter to offset center

---

examples/layer-browser/package.json
examples/playground/package.json
examples/website/3d-tiles/package.json
examples/website/globe/package.json
examples/website/i3s/package.json
examples/website/mesh/package.json
examples/website/point-cloud/package.json
examples/website/radio/package.json
examples/website/safegraph/package.json
modules/carto/package.json
modules/core/package.json
modules/geo-layers/package.json
modules/jupyter-widget/package.json
modules/layers/package.json
modules/mesh-layers/package.json
package.json
test/apps/arcgis-i3s/package.json
website/package.json
yarn.lock

For #6871
- bump @loaders.gl version as new alpha has been just released.
- @loaders.gl version

Bump @loaders.gl from 3.2.0-alpha.2 to 3.2.0-alpha.4

---

test/modules/geo-layers/tile-3d-layer/tile-3d-layer.spec.js

fix(geo-layers): unskip fixed test

---

modules/carto/src/api/layer-map.ts
modules/carto/src/api/parseMap.ts

CARTO: Discrepancies between public maps and fetchMaps

---

modules/google-maps/src/utils.ts

For #6901
- More robust way to calculate the pixel offset between map div and container

[google-maps] More robust offset calculation

---

modules/carto/src/index.ts
modules/carto/src/layers/carto-layer.ts
modules/carto/src/layers/h3-tile-layer.js
modules/carto/src/layers/h3-tileset-2d.js
modules/carto/src/layers/quadkey-tile-layer.js

- Implementation of H3TileLayer
- Instantatiate H3TileLayer when 'h3' scheme is detected

CARTO: Support H3TileLayer in CartoLayer

---

modules/carto/src/layers/carto-layer.ts
modules/carto/src/layers/h3-tile-layer.js
modules/carto/src/layers/quadkey-tile-layer.js

- Default aggregationResLevel in CartoLayer

CARTO: Default aggregationResLevel in CartoLayer

---

modules/carto/src/layers/h3-tile-layer.js
modules/carto/src/layers/h3-tileset-2d.js
modules/carto/src/layers/quadkey-tile-layer.js
modules/carto/src/layers/spatial-index-tile-layer.js

- Map spatial index to data index for autoHighlighting

CARTO: Fix autohighlighting in spatial index tile layers

---

docs/get-started/using-with-map.md

Fix typo in mapbox access token

---

modules/carto/src/layers/h3-tile-layer.js

- Read the H3TileLayer id from props

Carto: fix h3 tile layer id

---

modules/core/src/index.ts
modules/core/src/lib/composite-layer.ts
modules/core/src/lib/layer.ts
modules/core/src/lib/picking/pick-info.ts
modules/core/src/viewports/viewport.ts
modules/geo-layers/package.json
modules/geo-layers/src/mvt-layer/coordinate-transform.ts
modules/geo-layers/src/mvt-layer/find-index-binary.ts
modules/geo-layers/src/mvt-layer/mvt-layer.ts
modules/geo-layers/src/tile-layer/tile-layer.ts
modules/geo-layers/src/tile-layer/tileset-2d.ts
modules/geo-layers/src/tile-layer/types.ts
modules/geo-layers/src/tile-layer/utils.ts
modules/layers/src/geojson-layer/geojson-layer.ts
yarn.lock

Change List:
* Convert MVTLayer to Typescript
* TileLayer props alignment after #6848
* TileLayer: cleanup extra asserts

[ts] MVTLayer

---

modules/core/src/lib/deck.ts
modules/mapbox/bundle.ts
modules/mapbox/src/deck-utils.ts
modules/mapbox/src/mapbox-layer.ts
modules/mapbox/src/mapbox-overlay.ts
test/modules/mapbox/mapbox-layer.spec.js
tsconfig.build.json

For #5589 
- Convert the mapbox modue to TypeScript

[ts] mapbox module

---

modules/core/src/lib/deck.ts
modules/core/src/lib/tooltip.ts

[ts] Tooltip

---

modules/aggregation-layers/package.json
modules/aggregation-layers/src/aggregation-layer.ts
modules/aggregation-layers/src/contour-layer/contour-layer.js
modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-layer.js
modules/aggregation-layers/src/grid-aggregation-layer.js
modules/aggregation-layers/src/heatmap-layer/heatmap-layer.js
modules/aggregation-layers/src/hexagon-layer/hexagon-layer.ts
modules/aggregation-layers/src/index.ts
modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer.js
modules/aggregation-layers/src/types.ts
modules/core/src/lib/attribute/attribute-manager.ts
modules/layers/src/index.ts
test/modules/aggregation-layers/aggregation-layer.spec.js
test/modules/aggregation-layers/grid-aggregation-layer.spec.js

For https://github.com/visgl/deck.gl/issues/5589 & https://github.com/visgl/deck.gl/issues/6967
Change List:
* HexagonLayer converted to ts
* AggregationLayer converted to ts

[ts] HexagonLayer & deps

---

modules/layers/src/geojson-layer/geojson-binary.ts
modules/layers/src/geojson-layer/geojson-layer.ts
modules/layers/src/geojson-layer/sub-layer-map.ts
modules/layers/src/utils.ts

For https://github.com/visgl/deck.gl/issues/5589 & https://github.com/visgl/deck.gl/issues/6967
Change List
* migrate remaning 'modules/layers' sources to typescript

[ts] modules/layers leftovers

---

docs/get-started/using-with-typescript.md
docs/table-of-contents.json

For #5589 
- New getting started page

Add typescript documentation

---

modules/core/src/index.ts
modules/core/src/lib/layer-extension.ts
modules/extensions/package.json
modules/extensions/src/clip/clip.ts

For #5589 
- LayerExtension class
- ClipExtension

[ts] LayerExtension

---

test/modules/mapbox/index.js
test/modules/mapbox/mapbox-gl-mock/evented.js
test/modules/mapbox/mapbox-gl-mock/map.js
test/modules/mapbox/mapbox-gl-mock/style.js
test/modules/mapbox/mapbox-gl-mock/transform.js
test/modules/mapbox/mapbox-layer.spec.js
test/modules/mapbox/mapbox-overlay.spec.js
test/modules/mapbox/resolve-layers.spec.js

For #6773
- Tests for the mapbox module

[mapbox] Tests

---

modules/core/src/views/view.ts
modules/mapbox/src/deck-utils.ts
modules/mapbox/src/index.ts
modules/mapbox/src/mapbox-overlay.ts
modules/mapbox/src/resolve-layers.ts
test/modules/mapbox/index.js
test/modules/mapbox/mapbox-gl-mock/evented.js
test/modules/mapbox/mapbox-gl-mock/map.js
test/modules/mapbox/mapbox-gl-mock/style.js
test/modules/mapbox/mapbox-gl-mock/transform.js
test/modules/mapbox/mapbox-layer.spec.js
test/modules/mapbox/mapbox-overlay.spec.js
test/modules/mapbox/resolve-layers.spec.js

For #6773
- Support both overlaid and interleaved modes in `MapboxOverlay`
- `View` class: do not overwrite `padding` in view state unless `padding` is defined on the view
- `MapboxLayer` and `MapboxOverlay` support `padding` of the base map

Add interleaved prop to MapboxOverlay

---

modules/carto/src/layers/carto-layer.ts

- Type aggregation paramters
- Include in `updateState` to make sure map updates when aggregation parameters change

[ts] CartoLayer aggregation parameters

---

modules/core/src/utils/texture.ts
modules/layers/src/bitmap-layer/bitmap-layer.ts
modules/layers/src/icon-layer/icon-layer.ts
modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.ts

For #5589 
- Add missing `textureParameters` prop definition

Add type for textureParameters

---

examples/website/image-tile/app.js
examples/website/map-tile/app.js

Follow up for https://github.com/visgl/deck.gl/issues/6912
- Update `TileLayer` base examples to use new API

Update TileLayer based examples to use new API

---

modules/extensions/src/fill-style/shaders.glsl.ts

For #7069
- Use 64bit precision for pattern origin

Fix FillStyleExtension precision

---

docs/api-reference/carto/carto-layer.md
docs/api-reference/carto/overview.md

For https://github.com/visgl/deck.gl/issues/6967
- Remove mention of CARTO 2

CARTO: Remove CARTO 2 for documentation

---

modules/carto/src/index.ts

- Export `_tileToQuadbin` & `_quadbinToTile`

CARTO: Export quadbin conversion methods

---

modules/carto/src/index.ts

CARTO: Export quadbin util method

---

modules/aggregation-layers/src/cpu-grid-layer/cpu-grid-layer.ts
modules/geo-layers/src/tile-layer/tile-layer.ts

For #5589
- Should only import from published packages

Fix broken imports

---

docs/developer-guide/base-maps/using-with-mapbox.md
docs/table-of-contents.json

- Add missing page to TOC
- Fix broken links
- Explain difference between react-map-gl versions

Clarify Mapbox usage in docs

---

examples/gallery/src/mapbox-layer.html
modules/mapbox/src/deck-utils.ts

For https://github.com/visgl/deck.gl/issues/7121
- Pass the correct deck instance to event listener

Fix error when using MapboxLayer stand alone

---

modules/google-maps/src/utils.ts

Was this a regression during the TS refactor?

Fixing issue where event listeners were not being removed after finalizing DeckGL when used with google maps

---

modules/core/src/controllers/transition-manager.ts
modules/core/src/lib/constants.ts

For #7130
- Do not directly export enums

Fix TRANSITION_EVENTS export

---

docs/api-reference/carto/fetch-map.md
examples/get-started/scripting/carto/index.html

For https://github.com/visgl/deck.gl/issues/7147
- Use basemap in example
- Doc update

CARTO: Fix scripting example

---

modules/core/src/controllers/first-person-controller.ts

- `maxPitch` should be larger than `minPitch`

Fix FirstPersonController default

---

modules/geo-layers/src/index.ts
modules/geo-layers/src/tile-layer/types.ts
modules/layers/src/bitmap-layer/bitmap-layer.ts
modules/layers/src/index.ts

https://github.com/visgl/deck.gl/issues/7176

add BitmapBoundingBox and NonGeoBoundingBox types.

---

.github/workflows/test.yml
bindings/pydeck/.flake8
bindings/pydeck/Makefile
bindings/pydeck/postBuild
bindings/pydeck/setup.py
bindings/pydeck/tests/notebooks/notebook_utils.py

Fix Python CI

---

website/static/events/madrid-summit-2022/index.html

Fix some typos for Madrid Summit on the event landing page

Website: Fix some typos for Madrid Summit

---

website/static/events/madrid-summit-2022/index.html

- Inform the event will be in person and also streamed online.
- Replace Azure Maps talk for a generic one on basemaps

Small updates at madrid event landing page

---

bindings/pydeck-carto/examples/carto_layer_geo_query.py
bindings/pydeck-carto/examples/carto_layer_geo_query_param.py
bindings/pydeck-carto/examples/carto_layer_geo_table.py
bindings/pydeck-carto/examples/carto_layer_geo_tileset.py
bindings/pydeck-carto/examples/carto_layer_h3_query.py
bindings/pydeck-carto/examples/carto_layer_h3_table.py
bindings/pydeck-carto/examples/carto_layer_h3_tileset.py
bindings/pydeck-carto/examples/carto_layer_quadbin_query.py
bindings/pydeck-carto/examples/carto_layer_quadbin_table.py
bindings/pydeck-carto/examples/carto_layer_quadbin_tileset.py
bindings/pydeck-carto/examples/carto_layer_validation.py
bindings/pydeck-carto/pydeck_carto/layer.py
bindings/pydeck-carto/tests/test_layer.py

Added some tests
Simplified how to add styles on the notify_error function
Removed most of the is_valid_carto_layer from the examples

Changes extension on PR (#7255)

---

website/static/events/madrid-summit-2022/index.html

Link to eventbrite page for registration

[Madrid summit] link to eventbrite page

---

.github/ISSUE_TEMPLATE/bug-report.yml

Fix bug-report-link

---

README.md

Link to deck.gl-raster

---

modules/core/src/shaderlib/project/project.glsl.ts

For #7316
This was introduced by #6117 to GPU-based web-mercator projection. `project_size` automatically infers the latitude from the `geometry` struct. For some layers (arc, line, path) `geometry.worldPosition` is set to the start position of the segment, but used when projecting the altitude at both the start and the end.
- Explicitly set reference latitude in `project_position`

Fix altitude projection dependence on geometry.worldPosition

---

docs/api-reference/mapbox/mapbox-overlay.md

- Fix typo and add useful links.

Update MapboxOverlay docs

---

bindings/pydeck/pydeck/bindings/deck.py
bindings/pydeck/pydeck/io/html.py
bindings/pydeck/tests/bindings/test_deck.py
bindings/pydeck/tests/io/test_html.py

Fix pydeck render in Google Colab

---

docs/README.md

- Current docs are 8.8, link to 8.5-8.7 as well

chore(docs) update doc version links

---

modules/carto/src/layers/carto-tile-layer.ts
modules/carto/src/layers/spatial-index-tile-layer.ts
modules/core/src/effects/mask/utils.ts

- Fix TS warnings that don't require code changes

Chore: Fix TS warnings

---

modules/layers/src/geojson-layer/geojson.ts
test/modules/layers/geojson.spec.js

For #7367
- Do not throw if geometry is missing
- Test case

Allow null geometry in GeoJSON

---

modules/extensions/src/fill-style/shaders.glsl.ts

Fix FillStyleExtension scaling

---

modules/carto/src/layers/quadbin-tile-layer.ts
test/modules/carto/layers/quadbin-tile-layer.spec.js

Regression introduced by https://github.com/visgl/deck.gl/pull/7257
- Convert hexidecimal ids when reading JSON data
- Test update

CARTO: Support JSON format in QuadbinLayer

---

modules/carto/src/api/maps-v3-client.ts
test/modules/carto/api/maps-api-client.spec.js

For https://github.com/visgl/deck.gl/issues/7243
- Include aggregation and geoColumn in POST
- Test

CARTO: Include aggregation and geoColumn in POST

---

modules/extensions/src/clip/clip.ts
modules/extensions/src/mask/mask.ts
test/modules/extensions/clip.spec.js
test/modules/extensions/index.js
test/modules/extensions/mask.spec.js

Follow up of #7413
- Explicitly check for prop value `undefined`
- Unit tests

Additional ClipExtension and MaskExtension tests

---

docs/api-reference/geo-layers/tile-layer.md
docs/upgrade-guide.md

For #7461
- Update `zRange` docs
- Add to upgrade guide

Update TileLayer documentation

---

modules/jupyter-widget/package.json
modules/jupyter-widget/src/deck-bundle.js
modules/jupyter-widget/src/index.js
modules/jupyter-widget/src/lib/jupyter-transport-model.js
modules/jupyter-widget/src/lib/jupyter-transport-view.js
modules/jupyter-widget/src/playground/create-deck.js
modules/jupyter-widget/src/playground/playground.js
modules/jupyter-widget/src/playground/utils/google-maps-utils.js
modules/jupyter-widget/src/playground/utils/mapbox-utils.js
test/modules/index.js
test/modules/jupyter-widget/dummy-jupyter-widgets-base.js
test/modules/jupyter-widget/dummy-mapbox-gl.js
test/modules/jupyter-widget/index.js
test/modules/jupyter-widget/mock-widget-base.js
test/render/index.js

Follow up of #7523 
- Remove all `require()` from jupyter-widget source and tests

Restore jupyter-widget tests

---

modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.ts
modules/core/src/effects/lighting/lighting-effect.ts
modules/core/src/index.ts
modules/core/src/lib/layer-manager.ts
modules/core/src/shaderlib/index.ts
modules/jupyter-widget/src/playground/create-deck.js
modules/main/src/index.ts
test/browser.js
test/modules/aggregation-layers/gpu-cpu-aggregator.spec.js
test/modules/core/effects/lighting-effect.spec.ts
test/modules/core/lib/deck-picker.spec.js
test/modules/core/lib/pick-layers.spec.js
test/modules/core/shaderlib/project/project-32-64-glsl.spec.js
test/modules/core/shaderlib/project/project-glsl.spec.js
test/modules/geo-layers/h3-layers.spec.js
test/modules/layers/column-geometry.spec.js
test/render/index.js
test/render/jupyter-widget.js

fix: First clean test run (some disabled tests) (v9)

---

modules/extensions/src/brushing/brushing.ts
modules/extensions/src/clip/clip.ts
modules/extensions/src/mask/mask.ts

For #7496, follow up of #7513
- Remove work arounds in extension classes

Update extension classes to leverage new default props behavior

---

modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.ts

For #7555
- Fix SimpleMeshLayerProps wireframe type

Fix SimpleMeshLayerProps.wireframe and SimpleMeshLayerProps._instanced type

---

examples/website/3d-tiles/app.jsx

Fix 3d-tiles example Ceisium asset server URL

---

dev-docs/RFCs/v8.0/ui-module-rfc.md

Some relevant discussions:  #5354 #6285
On top of the discussion topics raised in this document, I would also like to compile a list of use cases for this feature. What are the controls you currently use or hope to use? In what ways do they need to interact with the `Deck` instance? 
- New dev doc

UI module RFC

---

modules/core/bundle/debug.ts
modules/core/bundle/peer-dependency.ts
modules/core/package.json
modules/core/src/lib/attribute/attribute-manager.ts
modules/core/src/lib/composite-layer.ts
modules/core/src/lib/deck-picker.ts
modules/core/src/lib/layer.ts
modules/core/src/lifecycle/props.ts
modules/core/src/shaderlib/shadow/shadow.ts
modules/core/src/viewports/viewport.ts
modules/geo-layers/src/h3-layers/h3-cluster-layer.ts
modules/geo-layers/src/tile-3d-layer/tile-3d-layer.ts
modules/geo-layers/src/tileset-2d/tile-2d-header.ts
modules/geo-layers/src/tileset-2d/tile-2d-traversal.ts
modules/jupyter-widget/src/playground/create-deck.js
modules/layers/bundle/peer-dependency.ts
modules/layers/src/geojson-layer/geojson.ts
modules/layers/src/icon-layer/icon-manager.ts
modules/layers/src/solid-polygon-layer/polygon.ts
modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer.ts
modules/mapbox/package.json
modules/mapbox/src/resolve-layers.ts

For #
- Previous PR hangs, this removes some package.json changes
-

chore: Reduce eslint warnings

---

test/modules/core/shaderlib/project/project-32-64-glsl.spec.js

For #
- Address a few of the many local test breakages on Apple silicon
-

chore: Disable GPU tests on Apple silicon

---

modules/core/src/index.ts

For #7620
- Export type AccessorContext

Export type AccessorContext from core.

---

examples/website/3d-tiles/app.jsx

chore(examples): 3d-tiles - update Cesium token

---

docs/api-reference/geo-layers/imagery-layer.md
docs/api-reference/geo-layers/tile-layer.md
docs/whats-new.md
modules/geo-layers/package.json
modules/geo-layers/src/imagery-layer/imagery-layer.ts
yarn.lock

- (fix) ImageryLayer does not update on data change
- (fix) ImageryLayer does not update on layers change
- (fix) Broken projection
- (fix) Callbacks should not fire if a request has been overriden

ImageryLayer bug fixes

---

docs/api-reference/extensions/terrain-extension.md
modules/extensions/src/index.ts
modules/extensions/src/terrain/height-map-builder.ts
modules/extensions/src/terrain/terrain-cover.ts
modules/extensions/src/terrain/terrain-effect.ts
modules/extensions/src/terrain/terrain.ts
test/modules/extensions/terrain/terrain-cover.spec.js
test/modules/extensions/terrain/terrain-effect.spec.js
test/modules/extensions/terrain/terrain.spec.js
test/render/test-cases/terrain-layer.js

For #7635 
- Implement decisions of TSC API Audit meeting, Feb 21, 2023
- `TerrainExtension` => `_TerrainExtension` (Rename export/imports in code, docs) 
- `props.terrainFittingMode` => `terrainDrawMode`

chore(extensions): TerrainExtension API Audit

---

examples/website/wms/app.jsx
website/src/examples-sidebar.js

For https://github.com/visgl/deck.gl/issues/7635
https://github.com/visgl/deck.gl/pull/7677 broke the website
- Correct listing in sidebar
- Remove unneeded serviceType prop

docs: Fix WMS website example

---

modules/core/src/lib/attribute/attribute-manager.ts
yarn.lock

For #7683
This is already fixed on master, back porting to 8.8-release
- Fix type import from outdated package

Fix type error

---

modules/geo-layers/src/tile-layer/tile-layer.ts

For #7697
- `TilesetClass` should be optional

Fix TileLayer prop type

---

CONTRIBUTING.md
examples/get-started/react/google-maps/README.md
examples/playground/json-examples/README.md
examples/website/3d-tiles/README.md
examples/website/terrain-extension/README.md
examples/website/terrain/README.md

For #7704 
- CONTRIBUTING.md
- Some READMEs in examples

Update docs to match recent dev environment changes

---

website/docusaurus.config.js
website/src/components/example/styled.js
website/src/components/info-panel/styled.js
website/src/components/input.jsx
website/src/doc-demos/demo-base.js
website/src/doc-demos/layers.js

For #7635 
- Use theme variables in styled components
- Switch map style based on theme

Fix docusaurus website dark mode

---

docs/upgrade-guide.md
docs/whats-new.md

8.9 what's new

---

.github/workflows/release.yml
.github/workflows/website.yml
website/src/components/input.jsx

For #7635 
- Fix bad merge that breaks tooltip styling
- Upgrade workflow node version

Misc fixes for website

---

.ocularrc.js
scripts/postinstall.sh

For #7739
- Output UMD bundles

Fix bundle settings

---

docs/whats-new.md

For https://github.com/visgl/deck.gl/issues/7635. Followup to https://github.com/visgl/deck.gl/pull/7730
- Include condensed version of changes [detailed here](https://github.com/visgl/deck.gl/pull/7376)

Add pydeck changes to whats-new

---

modules/carto/src/api/maps-v3-client.ts
modules/carto/src/layers/spatial-index-tile-layer.ts
modules/core/src/utils/math-utils.ts
modules/extensions/src/mask/mask-effect.ts
modules/mapbox/package.json
website/src/components/example/doc-item-component.jsx
website/src/doc-demos/codepen-automation.js

chore: Fix lint warnings

---

website/docusaurus.config.js

For #7635 
- Add search config (indexed by [Algolia DocSearch](https://docsearch.algolia.com/))

Configure search on website

---

.ocularrc.js
package.json
yarn.lock

For #7745
- Upgrade dev tools
- Add loaders global

Fix pre-built bundle errors

---

examples/website/collision-filter/app.jsx
examples/website/collision-filter/calculateLabels.js

Followup to https://github.com/visgl/deck.gl/pull/7712
- move `calculateLabels` into separate file

CollisionFilter website example: move calculateLabels into separate file

---

modules/mapbox/src/deck-utils.ts

For #7742
- Handle small pitch angle

Fix MapboxLayer crash when pitch=0

---

website/src/components/home/index.jsx

[website] fix get started link

---

.github/ISSUE_TEMPLATE/bug-report.yml

- Minor updates to the bug report template

(chore) update bug report template

---

modules/mapbox/src/mapbox-overlay.ts

For #7785 
- Subscribe to drag events from the map

MapboxOverlay handles drag events when interleaved:false

---

modules/core/src/lib/layer-extension.ts

For #7804
- Fix LayerExtension default type

(fix)TypeScript: LayerExtension default type

---

modules/geo-layers/src/h3-layers/h3-cluster-layer.ts
test/modules/geo-layers/h3-layers.spec.js

For #7618
Bug introduced in https://github.com/visgl/deck.gl/pull/6678/files#diff-1b034b18a480ef8267e2482a5e1e53fed894c800c5664c79a087f8ff8a09a221
- Fix accessor forwarding
- Test

Fix H3ClusterLayer accessors

---

website/src/components/example/make-example.jsx

The integration examples are not rendered correctly.
- Make maps fill container

Fix website example styling

---

modules/geo-layers/src/wms-layer/wms-layer.ts

For #
- layers that implement their own loading need to redefine isLoaded.
- redefine is loaded, track loading.

fix(geo-layers): Implement WMSLayer.isLoaded

---

modules/carto/package.json
modules/carto/src/layers/quadbin-tileset-2d.ts
yarn.lock

Includes fix from https://github.com/CartoDB/quadbin-js/pull/13

CARTO: Bump quadbin library to 0.1.8

---

docs/api-reference/geo-layers/tile-3d-layer.md

Tiles3DLayer is marked as experimental in the doc

Remove experimental from Tiles3DLayer

---

modules/layers/src/solid-polygon-layer/polygon.ts
test/modules/layers/polygon-tesselation.spec.js

For #7882
- Fix coordinate permutation
- Unit test

Fix polygon tesselation on yz plane

---

modules/google-maps/src/google-maps-overlay.ts
test/modules/google-maps/google-maps-overlay.spec.js
test/modules/google-maps/mock-maps-api.js

For https://github.com/visgl/deck.gl/issues/7888
- requestRedraw when removing interleaved overlay
- test

GoogleMapsOverlay: requestRedraw when removing interleaved overlay

---

modules/core/src/transitions/fly-to-interpolator.ts
test/modules/core/transitions/fly-to-interpolator.spec.js

For https://github.com/visgl/deck.gl/issues/7898
- Add `position` to linearly interpolated props in `FlyToInterpolator`
- Tests

Support position in FlyToInterpolator

---

docs/developer-guide/custom-layers/prop-types.md
examples/website/image-tile/app.jsx
website/docusaurus.config.js
website/src/examples/wms-layer.js
website/yarn.lock
yarn.lock

- Update lock files
- Fix module resolution in website config to account for new dependency of `@loaders.gl/i3s`

chore: fix website build

---

modules/core/src/lib/view-manager.ts
modules/core/src/views/view.ts

For https://github.com/visgl/deck.gl/issues/7956
- Use controller.type rather than ControllerType

Use controller.type rather than ControllerType

---

docs/api-reference/core/controller.md

Just a small readme controller fix

---

modules/extensions/src/path-style/shaders.glsl.ts

For #7875
- Improve uv calculation when using offsets

PathStyleExtension: fix dash + offset usage

---

docs/api-reference/carto/carto-layer.md

[website] Fix broken links to CARTO docs

---

docs/api-reference/core/widget.md
modules/core/src/index.ts
modules/core/src/lib/deck.ts
modules/core/src/lib/tooltip.ts
modules/core/src/lib/widget-manager.ts
modules/main/src/index.ts
test/modules/core/lib/index.js
test/modules/core/lib/tooltip.spec.js
test/modules/core/lib/widget-manager.spec.js

For #7946
- Add `WidgetManager`
- Reimplement `Tooltip` as a widget
- Declarative API (`deck.setProps({widgets})`)
- Widgets module

Add WidgetManager

---

.github/workflows/scorecard.yml

Resolves #7998
- Add Scorecard workflow to flag supply-chain security issues
Feel free to reach out if you have any feedbacks on the tool.

[Feat] Flagging supply-chain security issues

---

.eslintrc.js

Get rid of some lint warnings.
- Update eslint settings

Update eslint settings

---

modules/extensions/src/terrain/terrain-pass.ts

For #7942
- Force reset transparent color when drawing to terrain covers

[TerrainExtension] fix cover rendering with clear color

---

docs/api-reference/widgets/overview.md
modules/main/bundle.ts
modules/main/package.json
modules/main/tsconfig.json
modules/widgets/README.md
modules/widgets/bundle.ts
modules/widgets/package.json
modules/widgets/tsconfig.json
tsconfig.build.json

For #7946 
With the exception of tooltip, the plan is to distribute widgets in their own module. 
- adding widgets module
- documentation
@Pessimistress, should I target master or `9.0-dev`?

add(modules) widget module

---

bindings/pydeck/pydeck/io/html.py

Fix lint error in Python CI

---

modules/geo-layers/src/tile-layer/tile-layer.ts

For #8029
Bug introduced by #7985
- Explicitly pass down all updateTriggers

Fix TileLayer updateTriggers propagation

---

package.json

- Prevent outdated files from being published

[chore] clean typescript output before new build

---

modules/core/src/lib/deck-renderer.ts
test/modules/core/lib/deck.spec.ts

For https://github.com/visgl/deck.gl/issues/8059
- Abort render when no views are provided
- Test

DeckRenderer abort rendering when no views

---

examples/website/plot/plot-layer/axes-layer.js

Fix typo introduced by https://github.com/visgl/deck.gl/pull/8043

[website] Fix double comma typo

---

examples/website/carto-sql/app.jsx

For https://github.com/visgl/deck.gl/pull/8103
- Remove unused import

Chore: fix unused var lint error

---

modules/mapbox/src/deck-utils.ts

For #8091
- Include terrain source when drawing each MapboxLayer

[mapbox] fix drawing TerrainExtension in interleaved mode

---

docs/api-reference/carto/fetch-map.md

docs: Fix broken links in fetchmap.md

---

docs/api-reference/carto/fetch-map.md

Followup to https://github.com/visgl/deck.gl/pull/8126 which had invalid links
- Valid links

docs: Valid links in fetchmap.md

---

.ocularrc.js

Fallout from #8045
- Point aliases to correct files

Fix aliases for node tests

---

modules/geo-layers/src/index.ts

Export `TripsLayerProps` from geo-layers `index.ts`

---

modules/core/src/lib/deck-picker.ts
modules/core/src/passes/pick-layers-pass.ts
test/apps/mask/app.jsx
test/modules/core/lib/pick-layers.spec.ts

For https://github.com/visgl/deck.gl/issues/8125
- Include required mask layers when rendering to picking buffer
- Test

Include required mask layers when picking

---

docs/api-reference/core/widget.md
docs/api-reference/layers/arc-layer.md
docs/api-reference/widgets/fullscreen-widget.md

- Add missing anchor tags generated by website build

Chore: Add missing anchor tags

---

modules/widgets/src/stylesheet.css

Fix stylesheet.css

---

modules/geo-layers/src/tile-3d-layer/tile-3d-layer.ts

For #8260
- Add protections to Tile3DLayer.isLoaded

Imorove Tile3DLayer.isLoaded

---

website/src/doc-demos/mesh-layers.js

- Reference compatible loaders version in embedded example

Fix loaders script version in website

---

modules/geo-layers/src/tile-3d-layer/tile-3d-layer.ts.disabled

For #8260, #8279
- Add protections to Tile3DLayer.isLoaded

[v9] Improve Tile3DLayer#isLoaded

---

modules/carto/src/api/maps-api-common.ts
modules/carto/src/api/maps-v3-client.ts

We have added a filter parameter to be able to filter sources using a widget language.
- Added filter parameter to fetchLayerData

CARTO: added filter parameter to fetchLayerData

---

modules/extensions/src/collision-filter/shader-module.ts
modules/extensions/src/data-filter/shader-module.ts

Follow up to https://github.com/visgl/deck.gl/pull/8373/files
- Use `in` rather than `attribute` in shaders

Update extension shaders to GLSL 300 

---

examples/website/plot/plot-layer/axes-fragment.glsl.js
examples/website/plot/plot-layer/fragment.glsl.js
examples/website/plot/plot-layer/grid-vertex.glsl.js
examples/website/plot/plot-layer/label-fragment.glsl.js
examples/website/plot/plot-layer/label-vertex.glsl.js
examples/website/plot/plot-layer/surface-vertex.glsl.js

Fixes `Views/OrbitView` website example. Requires https://github.com/visgl/luma.gl/pull/1911
- Update shaders to glsl300

[v9] Port plot-layer shaders to glsl300

---

docs/api-reference/carto/quadbin-tile-layer.md
docs/whats-new.md

[chore] Update broken links in website

---

examples/website/screen-grid/app.jsx
modules/aggregation-layers/src/screen-grid-layer/screen-grid-cell-layer.ts
modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer.ts

- for https://github.com/visgl/deck.gl/issues/8318
Fixes examples/website/screen-grid, with support only for CPU-side aggregation currently.
Preview:

fix(aggregation-layers): Fix screen-grid-layer with CPU aggregation

---

docs/api-reference/core/project.md
examples/website/globe/animated-arc-layer.js
examples/website/mask-extension/animated-arc-layer.js
test/modules/aggregation-layers/gpu-grid-layer/gpu-grid-cell-layer-vertex.spec.ts
test/modules/layers/path-layer/path-layer-vertex.spec.ts

- Fix GLSL in globe & mask website examples
- Misc other shader fixes

[chore] Fix glsl in website examples

---

modules/carto/src/api/maps-api-common.ts

- carto(v8): fetchLayerData to support columns prop for query sources

carto(v8): fetchLayerData to support columns prop for query sources

---

website/src/examples/screen-grid-layer.js

Followup to https://github.com/visgl/deck.gl/pull/8416
- Default screen grid example to CPU

[website] Default screen grid example to CPU

---

examples/website/i3s/app.jsx
website/src/examples/arcgis.js

Example is not using the ArcGIS basemap (as that integration is broken), however it does showcase the I3S data loading
https://github.com/visgl/deck.gl/assets/453755/00c351a5-2e15-4697-bd67-ff2f47c3a965
- Simplify & fix example page
- Use Maplibre basemap

[website] Fix ArcGIS example

---

examples/website/wms/app.jsx

[website] fix WMSLayer example

---

modules/carto/package.json
yarn.lock

For https://github.com/visgl/deck.gl/pull/8460

Bump quadbin to 0.2.0

---

docs/api-reference/extensions/collision-filter-extension.md

For https://github.com/visgl/deck.gl/issues/8459

doc: Note on transparency in CollisionFilterExtension

---

CONTRIBUTING.md

Performing a fresh setup on a Mac M3 Pro I needed to do this

[docs] Add note on Python in CONTRIBUTING

---

scripts/github-release.js

`github-release` script is broken since ESM module switch: https://github.com/visgl/deck.gl/actions/runs/8017233518/job/21900681839
- Use `import` rather than `require`

chore: Use import in `github-release` script

---

modules/core/src/lib/deck.ts
test/modules/core/lib/deck.spec.ts

For #8463
- Deck checks if finalized before device is ready
- Unit test

Fix Deck error when finialize() is called before initialization

---

modules/core/src/lib/deck.ts
modules/core/src/passes/layers-pass.ts

fix(core): redraw() should clear canvas by default

---

.github/workflows/test.yml

chore(test): report coverage to coveralls

---

modules/widgets/package.json

Closes #8494
- Copy stylesheet.css to dist

fix(widgets): publish stylesheet

---

modules/carto/src/api/common.ts
modules/carto/src/api/fetch-map.ts
modules/carto/src/sources/base-source.ts

For https://github.com/visgl/deck.gl/issues/8578
- Override default clientId when passed in source
- Pass through clientId in tilestats request

CARTO: Respect clientId property

---

examples/get-started/react/google-maps/app.jsx
examples/get-started/react/google-maps/index.html
examples/get-started/react/google-maps/package.json

For the upcoming 1.0 release of [react-google-maps](https://github.com/visgl/react-google-maps/)
@usefulthink
- Update get-started/react/google-maps to use `@vis.gl/react-google-maps`

chore(example): update get-started/react/google-maps

---

modules/core/package.json
modules/core/src/lib/deck.ts
package.json
yarn.lock

- Upgrade probe.gl
- Upgrade ocular-dev-tools
- Add pretty print to `test-node` and `test-browser-headless`

Improve test harness

---

modules/carto/src/layers/vector-tile-layer.ts
modules/geo-layers/src/mvt-layer/mvt-layer.ts
modules/layers/src/geojson-layer/geojson-layer.ts

- GeoJsonLayer types
- MVTLayer types
- VectorTileLayer types

feat(layers): specify feature properties type for GeoJsonLayer

---

website/src/examples/mapbox.mdx

Duplicate of https://github.com/visgl/deck.gl/pull/8626 which didn't merge to master

website: Do not render Mapbox example in SSR

---

modules/core/src/lib/picking/pick-info.ts
modules/core/src/types/layer-props.ts
modules/layers/src/bitmap-layer/bitmap-layer.ts
modules/layers/src/index.ts
modules/layers/src/path-layer/path-layer.ts
modules/layers/src/solid-polygon-layer/solid-polygon-layer.ts
modules/layers/src/text-layer/text-layer.ts

Minor improvements to core types
- Allow `null` or `undefined` be passed to `data` prop
- Optional modifiers for `PickingInfo`
- Add `BitmapLayerPickingInfo` type

Type improvements

---

modules/carto/src/layers/vector-tile-layer.ts
modules/geo-layers/src/index.ts
modules/geo-layers/src/mvt-layer/mvt-layer.ts
modules/geo-layers/src/tile-layer/tile-layer.ts

- Add `TileLayerPickingInfo`
- Add `MVTLayerPickingInfo`

feat(geo-layers): add TileLayerPickingInfo type

---

modules/extensions/src/data-filter/data-filter-extension.ts
test/modules/core/lib/attribute/attribute.spec.ts
test/modules/core/lib/deck-picker.spec.ts
test/modules/core/lib/deck.spec.ts
test/modules/core/passes/pick-layers-pass.spec.ts
test/modules/extensions/brushing.spec.ts
test/modules/extensions/collision-filter/collision-filter.spec.ts
test/modules/extensions/data-filter.spec.ts
test/modules/extensions/fill-style.spec.ts
test/modules/extensions/fp64.spec.ts
test/modules/extensions/index.ts
test/modules/extensions/mask/mask.spec.ts
test/modules/extensions/path.spec.ts
test/modules/geo-layers/h3-layers.spec.ts
test/modules/geo-layers/tileset-2d/tileset-2d.spec.ts
test/modules/google-maps/google-maps-overlay.spec.ts
test/modules/index.ts
test/render/jupyter-widget.js
test/render/test-cases/index.js

- Some extension tests
- Jupyter widget tests
- Some render tests disabled in #8379

chore(test): reenable some tests

---

modules/extensions/src/terrain/terrain-effect.ts

For https://github.com/visgl/deck.gl/issues/8582 & https://github.com/visgl/luma.gl/issues/2036
- Remove terrain module when cleaning up TerrainEffect

Remove terrainModule from ShaderAssembler on cleanup

---

docs/api-reference/widgets/compass-widget.md
docs/api-reference/widgets/zoom-widget.md
docs/table-of-contents.json

add(docs) widgets table of contents

---

README.md
docs/get-started/learning-resources.md

Fix slack workspace link in docs

---

docs/whats-new.md

For #
- It looks weird to me that a specific feature like widgets comes before general release updates.
- Reorder the release notes.

docs: Reorganize whats new

---

modules/arcgis/src/commons.ts
modules/core/src/lib/deck.ts
modules/core/src/passes/pick-layers-pass.ts
modules/core/src/types/layer-props.ts
modules/mapbox/src/deck-utils.ts

- Proper typing for `layer.props.parameters` and `deck.props.parameters`

fix(core): Type props.parameters

---

docs/api-reference/geo-layers/tile-layer.md

chore(docs): Add BitmapLayer import

---

package.json

- tsc does not actually rebuild unless *.tsbuildinfo is cleared.

fix(build): inlined version off by 1

---

examples/get-started/pure-js/google-maps/app.js
examples/get-started/pure-js/google-maps/package.json
examples/website/google-3d/app.js
examples/website/google-3d/package.json
website/package.json
website/yarn.lock

Update google maps examples

---

docs/upgrade-guide.md

With the release of deck.gl v9, the CARTO module has several breaking changes. Just making sure that the Upgrade guide covers them nicely but thoroughly.
- Added missing items to upgrade guide

[Docs] Missing details in CARTO module upgrade guide

---

docs/whats-new.md

chore(docs): Update what's new highlight images

---

modules/core/src/controllers/controller.ts
modules/core/src/index.ts
modules/core/src/lib/deck.ts
modules/core/src/lib/view-manager.ts
modules/core/src/views/first-person-view.ts
modules/core/src/views/globe-view.ts
modules/core/src/views/map-view.ts
modules/core/src/views/orbit-view.ts
modules/core/src/views/orthographic-view.ts
modules/core/src/views/view.ts
test/modules/core/lib/deck.spec.ts

- *ViewProps
- ControllerOptions, viewport change callback parameters

feat(core): export useful types

---

modules/extensions/src/terrain/terrain-cover.ts
modules/extensions/src/terrain/utils.ts

For #8760 
- The picking texture should disable interpolation

fix(extensions): picking over draped terrain

---

docs/api-reference/aggregation-layers/contour-layer.md
docs/api-reference/aggregation-layers/cpu-grid-layer.md
docs/api-reference/aggregation-layers/gpu-grid-layer.md
docs/api-reference/aggregation-layers/grid-layer.md
docs/api-reference/aggregation-layers/heatmap-layer.md
docs/api-reference/aggregation-layers/hexagon-layer.md

More import path fixes after #8785 #8826 
- Correct import paths in example code

fix(docs): aggregation layer imports

---

.github/workflows/test.yml
.github/workflows/website.yml

Remove outdated dependencies; and security best practices.
- Remove headless-gl dependencies from the test workflow
- Use an access token with stricter scope

chore: update CI workflows

---

modules/aggregation-layers/src/heatmap-layer/heatmap-layer.ts
modules/aggregation-layers/src/heatmap-layer/triangle-layer.ts
modules/layers/src/text-layer/text-background-layer/text-background-layer.ts

- HeatmapLayer
- TextBackgroundLayer

Remove WebGL-only triangle-fan topology

---

website/src/pages/index.jsx

add maplibre to list Google Maps, Mapbox, ArcGIS

Add maplibre to landing

---

modules/core/src/lib/init.ts

Ocular uses a typescript plugin now: https://github.com/uber-web/ocular/blob/1f78a1070db452ce8d88fa10e013c1e77513a903/modules/dev-tools/src/ts-plugins/ts-transform-version-inline/index.ts#L20
- comments

chore: update version build comments

---

modules/carto/src/layers/quadbin-heatmap-tile-layer.ts

Follow up to https://github.com/visgl/deck.gl/pull/8782
- Use project.scale in shader rather than project_uScale

CARTO: Update QuadbinHeatmapTileLayer to use project UBO

---

modules/core/src/lib/widget-manager.ts

Closes #8877 
https://github.com/visgl/deck.gl/assets/2461547/e480b6ab-72e5-40b1-a70d-46300906adac
- increase widget container zIndex

fix(widgets): increase z-index to fix mouse events

---

modules/carto/src/basemap.ts
test/modules/carto/api/basemap.spec.ts

- carto: Fix fetchMap visibleLayerGroup filtering to include static layers

fix(carto): Fix fetchMap visibleLayerGroup filtering to include static layers

---

modules/carto/src/api/types.ts
modules/carto/src/sources/raster-source.ts
test/modules/carto/sources/raster-source.spec.ts

- Adding `filters` parameter to `rasterSource` in carto module

Add filters parameter to rasterSource

---

test/apps/framebuffer/app.js

- `test/apps/framebuffer` to v9 API

Fix framebuffer test app

---

docs/api-reference/carto/overview.md

Fixes broken link introduced by https://github.com/visgl/deck.gl/pull/8944

docs: Fix broken link after file rename

---

docs/README.md

fix dead link to pydeck installation in readme

---

examples/website/image-tile/app.tsx

Closes #8964
- Fix image bounds

Fix website image-tile example

---

docs/api-reference/core/deckgl.md
modules/core/src/scripting/deckgl.ts

Closes #8916
- DeckGL scripting interface types

Document additional props of the scripting interface

---

README.md

- Line 83: Updates URL, fixes link to website
- Line 84: Updates URL, fixes link to website

Fixes broken links in main README.md

---

website/package.json

chore(website): revert change to engines

---

modules/core/src/shaderlib/misc/uniform-types.ts
modules/mesh-layers/src/scenegraph-layer/scenegraph-layer-fragment.glsl.ts
modules/mesh-layers/src/scenegraph-layer/scenegraph-layer-uniforms.ts
modules/mesh-layers/src/scenegraph-layer/scenegraph-layer-vertex.glsl.ts
modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.ts
modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer-fragment.glsl.ts
modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer-uniforms.ts
modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer-vertex.glsl.ts
modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.ts

- Port `ScenegraphLayer`
- Port `SimpleMeshLayer`
- Add math.gl types to `UniformType`

mesh-layers UBO

---

docs/api-reference/carto/cluster-tile-layer.md

Fix broken links introduced in https://github.com/visgl/deck.gl/pull/9007

website: Fix broken links

---

modules/carto/src/layers/vector-tile-layer.ts

- carto: fix subLayerProps overriding in VectorTileLayer

carto: fix subLayerProps overriding in VectorTileLayer

---

modules/aggregation-layers/package.json
modules/arcgis/package.json
modules/carto/package.json
modules/extensions/package.json
modules/geo-layers/package.json
modules/google-maps/package.json
modules/json/package.json
modules/layers/package.json
modules/mapbox/package.json
modules/mesh-layers/package.json
modules/react/package.json
modules/test-utils/package.json
modules/widgets/package.json

For 9.1 beta release
- Fix incorrectly locked peer dependency versions

chore: fix peer dependency versions

---

modules/core/package.json
yarn.lock

Closes #9265
- Bump mjolnir.js to include https://github.com/visgl/mjolnir.js/pull/8

Bump mjolnir.js

---

docs/api-reference/core/attribute-manager.md
docs/api-reference/core/controller.md
docs/api-reference/layers/grid-cell-layer.md
docs/developer-guide/custom-layers/composite-layers.md
docs/whats-new.md

- Fixes/removes broken links for removed doc pages
- Misc anchor links

chore: Fix broken links in website

---

modules/carto/src/layers/post-process-utils.ts
modules/carto/src/layers/raster-layer-vertex.glsl.ts
modules/carto/src/layers/raster-layer.ts
modules/carto/src/layers/raster-tile-layer.ts

Applying https://github.com/visgl/deck.gl/pull/9286 to 9.0-release

CARTO: Fix seams between tiles in RasterTileLayer

---

docs/api-reference/mapbox/overview.md

- Syncronization -> Synchronization

docs: update overview.md

---

docs/api-reference/extensions/data-filter-extension.md

Closes https://github.com/visgl/deck.gl/issues/9319
- Document typescript usage of `DataFilterExtension`

website: TypeScript example for DataFilterExtension

---

docs/api-reference/core/deck.md
website/docusaurus.config.js
website/src/pages/playground.jsx

For https://github.com/visgl/deck.gl/issues/9056
- Wrap `App` in `() => <App />` to appease `BrowserOnly`
- Add widget CSS

website: Fix crash when running playground example

---

examples/website/mask-extension/animated-arc-layer.ts

For https://github.com/visgl/deck.gl/issues/9056
- Mask example needing similar UBO port to https://github.com/visgl/deck.gl/pull/9306

website: Update mask example to use UBOs

---

modules/aggregation-layers/src/common/aggregator/gpu-aggregator/webgl-bin-sorter.ts
modules/arcgis/src/commons.ts
modules/extensions/src/data-filter/aggregator.ts
modules/extensions/src/data-filter/shader-module.ts
test/modules/mesh-layers/scenegraph-layer.spec.ts

For https://github.com/visgl/deck.gl/issues/9056
- Use `disableWarnings` in `Model` creation to avoid logging
- Do not pass `categoryBitMask` in `getUniforms` unless explicitly set

chore: Model.disableWarnings across codebase

---

website/src/examples-sidebar.js

Hiding website example until https://github.com/visgl/luma.gl/issues/2304 is fixed

website: Hide FirstPersonView example

---

docs/api-reference/mapbox/overview.md
docs/upgrade-guide.md
docs/whats-new.md
modules/aggregation-layers/package.json
modules/arcgis/package.json
modules/carto/package.json
modules/core/package.json
modules/extensions/package.json
modules/geo-layers/package.json
modules/google-maps/package.json
modules/json/package.json
modules/jupyter-widget/package.json
modules/layers/package.json
modules/main/package.json
modules/mapbox/package.json
modules/mesh-layers/package.json
modules/react/package.json
modules/test-utils/package.json
modules/widgets/package.json
yarn.lock

For #9056 
- Update wording in what's new
- Add breaking changes to upgrade guide
- Mapbox submodule overview address both Mapbox and Maplibre compatibility

docs: v9.1 GlobeView related updates

---

test/apps/carto-map/app.ts

We've added support in CARTO for Aggregated Geometries, so we should add an example to illustrate such
- New Map in `/test/apps/carto-map/` with such example

Add Points Aggregated by Geometry example

---

CHANGELOG.md

changelog: fix link to human readable upgrade guide (#9392)

---

.eslintrc.cjs
modules/arcgis/package.json
modules/carto/package.json
modules/google-maps/package.json
modules/jupyter-widget/package.json
modules/layers/package.json
yarn.lock

For #9416
- Enable lint rule for extraneous dependencies
- Add missing dependencies to package.json

Add missing dependencies

---

examples/website/collision-filter/app.tsx
examples/website/icon/app.tsx

Blame find and replace.
- Fix broken imports in examples

chore: Fix bad import path in examples

---

modules/mapbox/src/mapbox-overlay.ts
modules/mapbox/src/types.ts

Closes #9389
- Avoid surfacing internal types

fix(mapbox): relax MapboxOverlay type

---

modules/widgets/src/index.ts
modules/widgets/src/reset-view-widget.tsx

Closes #
- Needs #9477 to land first
-

feat(widgets): new ResetViewWidget (v9.1)

---

modules/core/src/lib/layer-manager.ts
modules/core/src/shaderlib/index.ts
modules/core/src/shaderlib/project/project.glsl.ts
modules/core/src/shaderlib/project/project.ts

Ib/webgpu plumbing 24 - shaderlib (stacked PR)

---

modules/core/src/lib/deck.ts

webgpu stacked PR deck

---

modules/core/src/lib/attribute/data-column.ts
modules/core/src/lib/attribute/gl-utils.ts
modules/core/src/lib/deck.ts
modules/core/src/lib/layer-manager.ts
modules/core/src/lib/layer.ts
modules/core/src/passes/layers-pass.ts
modules/core/src/shaderlib/index.ts
modules/core/src/shaderlib/project/project.glsl.ts
modules/core/src/shaderlib/project/project.ts

Closes #
- Prep diff for WebGPU support
- Minor changes to unblock WebGPU, should not break WebGL

chore: WebGPU plumbing

---

examples/website/maplibre/app.tsx

Closes #9505
- Disable right-drag for pitch and lock pitch to prevent keyboard input

website: Disable pitching on Maplibre globe

---

examples/get-started/pure-js/widgets/app.js
modules/widgets/src/index.ts
modules/widgets/src/stylesheet.css
modules/widgets/src/timeline-widget.tsx

Closes #
Having at least some kind of minimal timeline widget seems essential to a code widget offering.
This is an extremely minimal PoC, just to get some basic working code in place.
TODO
- Integrate something like TripsLayer into the example
- Improve the styling
- Add tick marks and labels, current time, etc.
- ...
-

feat(widgets): minimal TimelineWidget (PoC)

---

modules/carto/src/layers/vector-tile-layer.ts

Followup to https://github.com/visgl/deck.gl/pull/9449
- `autoLabels` prop optional

CARTO: Make autoLabels prop optional

---

modules/widgets/src/index.ts
modules/widgets/src/info-widget.tsx
modules/widgets/src/lib/components.tsx
modules/widgets/src/view-selector-widget.tsx
test/apps/widgets-example-9.2/app.ts

Closes #
- Widget that lets the user select split screen configuration (none, horizontal, vertical)
-

[feat] ViewSelectorWidget

---

website/static/events/seattle-summit-2025/index.html

Pivoting the topic of my talk to be more about @vis.gl/react-google-maps in general.

Update talk title in seattle summit 2025 agenda
