visgl/deck.gl

- modules/mesh-layers/src/scenegraph-layer/gltf-utils.js
Program uniforms aren't set until the draw.
> Fix ScenegraphLayer asset wait

- examples/playground/package.json
- modules/core/src/lifecycle/constants.js
- website/src/utils/layer-params.js
For #3983 
- Use `Symbol.for` instead of `Symbol` to take advantage of the global registry
- Fix a crash in website embedded demos when try to access original async values
> Secretly expose props symbols

- dev-docs/RFCs/README.md
- dev-docs/RFCs/vNext/mobile-platform-support-rfc.md
For #
- This is intended as a strategic alignment RFC, Align tech leads on a "longer term" strategy for Mobile and Native Mobile Platform support
- If someone picks up this work, it will be advantageous to have an agreed-upon strategy for how what should be done.
- New RFC.
> RFC: Mobile Platform Support

- docs/api-reference/react/deckgl.md
- docs/upgrade-guide.md
- examples/layer-browser/src/map.js
- modules/core/src/controllers/transition-manager.js
- modules/react/src/deckgl.js
- modules/react/src/utils/evaluate-children.js
- modules/react/src/utils/position-children-under-views.js
- package.json
- test/modules/react/utils/evaluate-children.spec.js
- test/modules/react/utils/position-children-under-views.spec.js
For #3983 
- Fix a crash when used with older versions of react-map-gl (missing `transitionInterpolator.getDuration`)
- Behavioral change: (except the base map) all child elements default to render above the canvas. This removes the dependency on `child.props.style.zIndex` to position children.
- Behavioral change: (except the base map) no longer overwrites `child.props` with information from the current viewport (viewState, width, height, etc.). This removes React warning about unsupported div props. Components can still use `ContextProvider` or functional child to listen to viewport change.
- Only create one wrapper for each view. This improves performance when a lot of child elements are used.
- Unit tests
- Docs
> React module fixes

- modules/aggregation-layers/src/grid-aggregation-layer.js
- modules/core/src/effects/lighting/point-light.js
- modules/core/src/lib/layer.js
- modules/core/src/shaderlib/project/project-functions.js
- modules/geo-layers/src/great-circle-layer/great-circle-vertex.glsl.js
- modules/geo-layers/src/tile-layer/tile-layer.js
- modules/layers/src/bitmap-layer/bitmap-layer-vertex.js
- website/contents/pages.js
- website/package.json
For #3983 
- Remove reference to deprecated `COORDINATE_SYSTEM.IDENTITY` (fixes console warning)
- Move picking highlight related code out of `updateState()`. It depends on `this.getModels()` being populated, but we don't have control over whether or when `super.updateState()` is called by the layer. (fixes `BitmapLayer` autohighlight)
- Add `DECKGL_FILTER_COLOR` hook to `BitmapLayer` vertex shader (fixes picking)
- Update `GreatCircleLayer` vertex shader (base layer changed to use vec3 64low attributes)
- Rerender sublayers when `TileLayer`'s props change
> Layer bug fixes

- modules/aggregation-layers/src/contour-layer/contour-layer.js
- modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer.js
- modules/aggregation-layers/src/utils/grid-aggregation-utils.js
- test/browser.js
- test/data/grid-aggregation-data.js
- test/modules/aggregation-layers/aggregation-layer.spec.js
- test/modules/aggregation-layers/gpu-cpu-aggregator.spec.js
- test/modules/aggregation-layers/grid-aggregation-layer.spec.js
- test/modules/aggregation-layers/index.js
- test/modules/aggregation-layers/utils/aggregation-operation-utils.spec.js
- test/modules/aggregation-layers/utils/gpu-grid-aggregator.spec.js
For ##3844
- Fixes
- Fix accessor settings in ScreenGrid and Contour Layers (not applicable for other layers)
- Tests
- Update unit tests for GridAggregationLayer, and enable it for Node.
- Clean up aggregation-data file
- Add new unit tests for CPU and GPU Aggregators (Screen and World space aggregation)
- Add new tests for util methods.
-
> AggregationLayers: Update and improve unit test coverage.

- modules/core/bundle/deckgl.js
- modules/main/bundle.js
- website/package.json
- website/webpack.config.js
For #3983 
- Replace imported es6 code with esm
- Drop unused `@deck.gl/json` from the main bundle (jupyter-widget is building its own bundle), dependency expression-eval is causing issues
- Fix website build warnings
> Fix bundle transpilation

- docs/developer-guide/interactivity.md
> Looks like these methods have been deprecated

- modules/aggregation-layers/src/contour-layer/contour-layer.js
- modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-cell-layer.js
- modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-layer.js
- modules/aggregation-layers/src/heatmap-layer/heatmap-layer.js
- modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer.js
- modules/aggregation-layers/src/utils/grid-aggregation-utils.js
- test/modules/aggregation-layers/gpu-cpu-aggregator.spec.js
- test/modules/aggregation-layers/gpu-grid-layer/gpu-grid-cell-layer.spec.js
- test/modules/aggregation-layers/grid-aggregation-layer.spec.js
For #3983
- Fix aggregation dirty flags, so when data is loaded, aggregation is re-run.
- Use alignment for translation only, use actual bounding box for calculating grid dimensions.
- Fix translation and gridOrigin setttings
- Fix GPUGridLayer's sublayer attribute settings.
- Fix aggregation dirty flags.
- Use alignment for translation only.
- Fix bounding box translation
- Fix GPUGridLayer attribute setting
> AggregationLayer: various fixes

- examples/layer-browser/package.json
- examples/playground/package.json
- examples/website/3d-tiles/package.json
- examples/website/mesh/package.json
- examples/website/point-cloud/package.json
- examples/website/scenegraph-layer/package.json
- modules/core/package.json
- modules/geo-layers/package.json
- modules/geo-layers/src/tile-3d-layer/get-frame-state.js
- modules/jupyter-widget/package.json
- modules/layers/package.json
- test/modules/geo-layers/tile-3d-layer/get-frame-state.spec.js
- yarn.lock
For #3983 
- Bump loaders.gl to 2.0.0-beta.8 (bounding volume fix)
- Fix frustum plane conversion
> fix 3d tiles culling

- modules/react/src/deckgl.js
For #3983 
Fixes a website issue where the map is displayed behind the container div's background
- Set the React wrapper's z-index
> Fix React wrapper z-index

- modules/core/src/lib/init.js
For #4069
@tsherif Same change needs to be made to luma.gl.
- Avoid crash if a `deck` object already exists in the global scope.
> Avoid crash when a `deck` object already exists in the global scope

- modules/core/src/lib/deck.js
- modules/core/src/lib/picking/pick-info.js
For #4055
- Do not call root `onHover` if a layer `onHover` callback returned `true`
> Fix hover event bubbling

- bindings/python/pydeck/PUBLISH.md
- bindings/python/pydeck/setup.py
For #3640 
Documents how to publish pydeck
- Add release checklist for pydeck
> pydeck: Add pydeck release checklist

- modules/core/src/lib/deck-picker.js
- modules/core/src/lib/deck.js
- modules/core/src/lib/picking/pick-info.js
Move calling layer callbacks outside of `DeckPicker`. This makes the handling of hover events consistent with click, drag etc.
> Clean up hover handling

- docs/upgrade-guide.md
- modules/core/src/lib/deck.js
For #4075 
- Log warning if both `initialViewState` and `viewState` are both specified
- Add explanation to the upgrade guide
> Warn if initialViewState and viewState are both present

- modules/jupyter-widget/src/version.js
The `version` variable needs to be defined in a way that it can be used by JupyterLab (which installs from the source code).
For #3640
- Define `version` from the distribution bundle
> @deck.gl/jupyter-widget: Change version variable for JupyterLab installation

- package.json
Found the reason root `version` script is not executed by lerna - root package.json cannot use a name that collides with one of the submodules.
> Fix inline versioning

- bindings/python/pydeck/README.md
- bindings/python/pydeck/pydeck/io/html.py
- modules/jupyter-widget/package.json
For #3640
The standalone HTML renderer needs to download a built version of @deck.gl/jupyter-widget from a CDN to work. Blocking for pydeck 0.2.0.
> pydeck: Add CDN-hosted bundle for standalone HTML rendering

- modules/layers/src/icon-layer/icon-manager.js
- test/render/test-cases.js
For #4039 
- `IconManager`: add a `loaded` field indicating if the icons are fully loaded.
> Fix randomly failed icon layer render test

- modules/react/src/utils/position-children-under-views.js
- test/modules/react/utils/position-children-under-views.spec.js
Fixes the following console warning:
```
react.development.js:188 Warning: Each child in a list should have a unique "key" prop.
Check the render method of `DeckGL`. It was passed a child from App. See https://fb.me/react-warning-keys for more information.
in StaticMap (created by App)
in DeckGL (created by App)
in App
```
- Avoid creating lists
> Fix react key warning

- docs/developer-guide/debugging.md
- modules/core/bundle/debug.js
- Fix mixed usage of `import` and `module.exports` syntax in `bundle/debug.js`
- Add debug bundle documentation
> Fix debug bundle warning

- modules/aggregation-layers/src/utils/gpu-grid-aggregation/aggregate-to-grid-vs.glsl.js
For #4065 
Adding a workaround specific to ANGLE. With this fix, GPU Aggregation works on windows:
-
> GPUGridAggregator: Add WA for ANGLE specific bug.

- modules/core/src/lib/deck.js
For #4116
`canvas` is behind view containers in v8.0.
- Assign cursor style to container element
> fix cursor style in React

- modules/react/src/deckgl.js
For #4115
The default position of the canvas is not aligned top-left if the parent container has `text-align: center`.
- Explicitly set canvas position
> [react] explicitly set deck canvas position

- modules/core/src/utils/tesselator.js
- modules/layers/src/solid-polygon-layer/polygon-tesselator.js
- test/modules/layers/polygon-tesselation.spec.js
For #4114 
- Do not throw if `geometryBuffer.value` is missing
- Deduce `instanceCount` from luma.gl Buffer instance
- Unit tests
> Fix Tesselator handling of luma.gl buffers

- docs/api-reference/layer.md
- modules/core/src/lib/attribute/attribute.js
- modules/core/src/lib/attribute/data-column.js
- modules/core/src/utils/tesselator.js
- modules/layers/src/solid-polygon-layer/polygon-tesselator.js
- test/modules/core/lib/attribute/attribute.spec.js
- test/modules/layers/polygon-tesselation.spec.js
For #4114 
- Do not throw (in most cases) when `value` is missing from external buffer
- Allow external buffer to override the `type` accessor
> Fix support for luma.gl buffers as external attributes

- docs/api-reference/deck.md
- examples/gallery/src/viewport-transition.html
- examples/playground/src/deck-with-maps.js
- examples/website/3d-tiles/app.js
- modules/core/src/lib/deck.js
- modules/core/src/utils/deep-equal.js
We currently have two models of view state management:
- Stateless:
```jsx
<DeckGL controller={true}
viewState={this.state.viewState}
onViewStateChange={({viewState}) => this.setState({viewState})} />
```
- Stateful
```jsx
<DeckGL controller={true}
internalViewState={INITIAL_VIEWSTATE} />
```
Currently, if the user wants to manipulate the view state outside of the controller at any time (e.g. click a button and fly to another city), they have to use the stateless model.
The main concern is that this breaks the reactive paradigm (potentially modifying props outside of the React render cycle). Maybe we don't expose this method on the React component?
Related: [Imperative API RFC](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v7.x/imperative-api-rfc.md)
- Add `deck.setViewState` …
> Support initialViewState updates

- docs/api-reference/deck.md
- modules/core/src/lib/deck-picker.js
- modules/core/src/lib/deck-renderer.js
- modules/core/src/lib/deck.js
- modules/core/src/lib/layer-manager.js
- modules/core/src/lib/layer.js
- modules/core/src/passes/layers-pass.js
- test/modules/core/lib/layer-manager.spec.js
For #4134
- Do not throw during layer lifecycles: initialize, update, finalize, draw
- Switch error logging from `log.warn` to `log.error`
- Add `onError` callback to `Deck` class (see updated documentation)
- Test
> Error handling

- modules/core/src/shaderlib/project/project.glsl.js
- modules/core/src/shaderlib/project/viewport-uniforms.js
- test/apps/mapbox-tile/app.js
- test/apps/mapbox-tile/utils/decode.js
- test/modules/core/shaderlib/project/viewport-uniforms.spec.js
For #4104
This PR fixes the usage of `COORDINATE_SYSTEM.CARTESIAN` with `WebMercatorViewport`. In this case, positions are in common space instead of lng-lat. This is discussed in #3935, where the source data (mapbox vector tiles) is pre-projected to the Web Mercator plane.
More generically, this is needed to support alternative 2D projections such as Stereographic, Albers, etc. For these projections, it is not feasible to do the full projection on the GPU with acceptable performance and precision. We will need to project lng-lat positions to the common space on the CPU, and then use these positions with a geospatial viewport.
- Address more `coordinateSystem`/`projectionMode` combinations in uniform calculation
- Unit tests
> Project module: support pre-projected positions

- modules/geo-layers/src/h3-layers/h3-hexagon-layer.js
- test/modules/geo-layers/h3-layers.spec.js
For https://github.com/keplergl/kepler.gl/issues/887
- Check if `h3Distance` fails
- Tests
> Fix H3HexagonLayer update when viewport jumps

- modules/core/src/shaderlib/project/project.glsl.js
- test/modules/core/shaderlib/project/project-glsl.spec.js
In offset mode `project_common_position_to_clipspace`, the fourth component does not matter as it is dropped by `viewProjectionMatrix`:
https://github.com/uber/deck.gl/blob/848420ca1fc3214d8c81ecffb79354ce01bd064c/modules/core/src/shaderlib/project/viewport-uniforms.js#L129
- Remove unnecessary code from `project_common_position_to_clipspace`
- Tighten test cases
> Remove unnecessary code from project glsl

- modules/core/src/shaderlib/project/project.glsl.js
For #4145 and maybe #4159 
Experiments show:
- `if (true)` passes
- `if (project_uCoordinateSystem == COORDINATE_SYSTEM_LNGLAT)` passes
- `if (project_uProjectionMode == PROJECTION_MODE_WEB_MERCATOR)` passes
- `if (project_uCoordinateSystem == COORDINATE_SYSTEM_LNGLAT && project_uProjectionMode == PROJECTION_MODE_WEB_MERCATOR)` does not pass
Should the bug be reported somewhere?
- Split if statement
> Voodoo fix for Mac+NVIDIA bug

- modules/geo-layers/src/tile-layer/utils/viewport-util.js
- test/modules/geo-layers/tile-layer/viewport-util.spec.js
When the viewport's longitude is close to the 180th meridian, the bounding box will look something like
|  | minX | maxX |
|--|--|--|
| boundingBox | -200 | -150 |
| tileIndex (z=4) | -0.88 | 1.33 |
The old calculation clamps tileX to `[0, scale]` which was incorrect. tileX should loop between `[0, scale]` as the map repeats.
In the above case, the old calculation returns `[0, 0, 4]` and `[1, 0, 4]`. The correct result should be `[0, 0, 4]`, `[1, 0, 4]` and `[15, 0, 4]`.
- Fix bug in `getTileIndices`
- Unit tests
> [TileLayer] fix tile indices generation in edge cases

- docs/api-reference/extensions/data-filter-extension.md
- examples/website/data-filter/app.js
- examples/website/data-filter/range-input.js
- modules/extensions/src/data-filter/data-filter.js
- modules/extensions/src/data-filter/shader-module.js
- test/modules/extensions/data-filter.spec.js
Provide a way to filter UNIX timestamps accurately.
- Add `fp64` option to `DataFilterExtension`
- Docs
- Unit tests
> data-filter: support double precision

- modules/core/src/shaderlib/project/project.glsl.js
This is already fixed in master, patch 7.3
- Apply modelMatrix before mercator projection
> Fix modelMatrix application in the project module

- modules/json/src/helpers/convert-functions.js
- modules/json/src/helpers/instantiate-class.js
- test/modules/json/helpers/convert-functions.spec.js
For  #4177
Boolean props on all layers created via @deck.gl/json appear to have been returning to their default value if specified as `false`.
The bug only affected situations where a prop's default value is `true`, and the user wished to deactivate it, e.g. `stroked` and `filled` exhibit this behavior in the GeoJsonLayer, while `extruded` does not, because of their [defaults](https://github.com/uber/deck.gl/blob/master/docs/layers/geojson-layer.md#filled-boolean-optional).
- Fix bug
- Add test to prevent regression
> @deck.gl/json: Fix bug dropping props with falsy values

- examples/playground/webpack.config.js
`HtmlWebpackPlugin` is unused, and not installed by `packages.json` for this example.
Note that tests were skipped locally when making this PR, because they were failing for me on `master`. (also `yarn bootstrap` was failing)
> Remove HtmlWebpackPlugin from examples/playground

- modules/react/src/utils/position-children-under-views.js
Pull request #4098 partially fixed issue with missing key error. Context
element is used in array children and also misses key. This PR fully fixes
issue #4116.
> [React] fix missing key error

- examples/website/data-filter/app.js
See inline comments for context.
We changed the default `farZMultiplier` from `10` to `1.01` in v8, making the issue more prominent than before.
This change still does not solve the clipping at high zoom levels, but should be sufficient for the purpose of this demo.
> Fix disappearing circles in the data-filter example

- modules/jupyter-widget/package.json
- modules/jupyter-widget/src/binary-transport.js
- modules/jupyter-widget/src/create-deck.js
- modules/jupyter-widget/src/widget.js
- test/modules/jupyter-widget/binary-transport.spec.js
- test/modules/jupyter-widget/index.js
Change `npm run watch` for faster development within JupyterLab, which can call `jlpm run watch` on the package.json here.
Incorporate binary data transfer within the DeckGLWidget widget.
For #4103
> [Binary support, part 2] @deck.gl/jupyter-widget: Process binary data within DeckGLModel

- modules/core/src/lib/attribute/attribute-transition-utils.js
- modules/core/src/lib/attribute/data-column.js
- modules/core/src/transitions/gpu-spring-transition.js
For https://github.com/uber/deck.gl/issues/4223
Stride is calculated incorrectly when setting external interleaved buffers.
This fix needs to be cherry-picked to the 8.0 release branch. I will add a render test in a follow up PR (render test setup has diverged on master).
> Fix transition for 64bit attributes

- docs/layers/base-tile-layer.md
- modules/geo-layers/src/tile-layer/utils/viewport-util.js
- modules/layers/src/base-tile-layer/base-tile-layer.js
- modules/layers/src/base-tile-layer/utils/tile-2d-header.js
- modules/layers/src/base-tile-layer/utils/tile-cache.js
- modules/layers/src/base-tile-layer/utils/tile.js
- modules/layers/src/base-tile-layer/utils/tileset-2d.js
- test/modules/geo-layers/tile-layer/tile-layer.spec.js
- test/modules/layers/base-tile-layer/base-tile-layer.spec.js
- test/modules/layers/base-tile-layer/tile-cache.spec.js
- test/modules/layers/base-tile-layer/tileset-2d.spec.js
- test/modules/layers/index.js
Resolves https://github.com/uber/deck.gl/issues/3511
This PR refactors `BaseTileLayer`/`TileCache` classes to function more similar to `Tile3DLayer`/`Tileset3D`. Traversal now reruns every time any tile finishes loading, instead of waiting for the entire viewport to load. The logic that determines tile visibilities is entirely moved into `TileCache`. It also uses a more sophisticated strategy (configurable by the user) to pick placeholders when a tile is pending.
The new API needs audit.
- Add `strategy` prop to `BaseTileLayer` (see documentation)
- `TileCache` rewrite
- Unit tests
> TileLayer improvements

- docs/layers/text-layer.md
- modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer.js
- modules/layers/src/text-layer/text-layer.js
- modules/layers/src/text-layer/utils.js
- test/modules/layers/text-layer/text-layer.spec.js
- test/modules/layers/text-layer/utils.spec.js
- test/render/test-cases/text-layer.js
For #3758 
cc @ajduberstein @twojtasz 
- Add binary support to TextLayer
- Unit and render tests
> Support binary data in TextLayer

- bindings/pydeck/pydeck/bindings/deck.py
- bindings/pydeck/pydeck/io/html.py
- bindings/pydeck/pydeck/io/templates/index.j2
For #4103 
- Add background color
- Add effects to deck object
> pydeck: Add support for background colors in standalone HTML renderer

- examples/experimental/h3-grid/README.md
- examples/experimental/h3-grid/package.json
- examples/experimental/h3-grid/src/app.js
- examples/experimental/h3-grid/src/h3-grid-layer.js
- examples/experimental/h3-grid/src/h3-utils.js
- examples/experimental/h3-grid/webpack.config.js
- modules/geo-layers/src/h3-layers/h3-hexagon-layer.js
It's not clear what the use case would be outside of demoing h3-js, so I'm adding this layer as an example, not part of the layer catalog.
A `minZoom` is added based on the `resolution` and `maxHexCount` props to avoid loading too many hexagons in one viewport.
> Add example: H3GridLayer

- .eslintrc.js
- modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-cell-layer.js
- modules/core/bundle/lumagl.js
- modules/core/src/effects/post-process-effect.js
- modules/extensions/package.json
- modules/extensions/src/fp64/project64.js
- modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
- modules/mesh-layers/package.json
- modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js
- scripts/bundle.config.js
For #4254
- Bundle config: do not make luma submodules other than `@luma.gl/core` externals
- Audit submodule usage of `@luma.gl/core`, make sure that they match the luma APIs exposed by standalone bundle
- Fix eslint settings
> Fix bundle dependencies

- modules/react/src/deckgl.js
- modules/react/src/utils/extract-styles.js
- test/modules/react/index.js
- test/modules/react/utils/extract-styles.spec.js
In 7.x, apps can set the mix-blend-mode CSS property of the canvas by specifying the `style` prop of the `DeckGL` React component. This is important for compositing deck.gl's canvas with a base map. Due to a bug fix for positioning, the approach was broken in 8.0.
- Memoize element styles
- Whitelist `mixBlendMode` for the canvas
> [react] Fix support for mix-blend-mode style

- modules/core/src/shaderlib/project/project.glsl.js
For #4237 
The only difference is
```glsl
position_world.xyz += position64Low;
```
vs.
```glsl
position_world += project_uModelMatrix * vec4(position64Low, 0.0);
```
Looks like the former triggers some optimization in shader compilation.
Tested on iPhone; will release an alpha for testing on other devices once merged.
> fix 64-bit precision in low-end GPUs

- examples/experimental/terrain/package.json
- examples/experimental/terrain/src/app.js
- examples/experimental/terrain/src/surface.js
- examples/experimental/terrain/src/terrain-layer/terrain-layer.js
Progress on #4236 
New TerrainLayer interface internalizes all data preparation logic so the user doesn't need to write that boilerplate. Also supports being used as a tiled layer (internally rendering a TileLayer of SimpleMeshLayers), or as a single mesh (internally rendering a SimpleMeshLayer).
This layer is suitable for rendering a few use cases:
- Terrain tiles globally from a tile server (similar to TileLayer).
- A static set of tiles from a tile server.
- A custom tile of your own dataset (e.g. non-[Slippy map tiles](https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames)).
Interactions while loading new tiles now feels way smoother since we're now offloading terrain mesh generation to web workers.
New prop interface:
```
const defaultProps = {
...TileLayer.defaultProps,
// Image …
```
> Refactor TerrainLayer for performance and ease of use.

- examples/website/mesh/app.js
- modules/core/src/lib/attribute/attribute.js
When the prop `mesh` is loaded asynchronously, we create a new model, and invalidates all attributes.
The bug is in the Attribute class. If `instanceColors` is a constant, without changing the constant value, the `attribute.neesRedraw` flag is not set during an update, so the attribute is never sent on the new model.
- Mark invalidated attributes as `needsRedraw`
> Fix using `getColor` with constant in SimpleMeshLayer

- modules/core/src/lib/attribute/attribute.js
- test/modules/core/lib/attribute/attribute.spec.js
Through the TypedArrayManager, it is possible that a buffer from the pool can be used that contains invalid values for the type and the update of the attribute may only affect the attribute.size, rather than the buffer.length.
Limit fix limits the validation to Math.min(attribute.size, 4)
> Fix attribute check greater than attribute size

- bindings/pydeck/docs/layer.rst
For #4103 and #4164
Provide greater detail on the JS expression parser, especially where strings that aren't demarcated as constants within the @deck.gl/jupyter-widget JSON configuration
- Add section documenting string constant usage
> pydeck: Update docs with string constant usage

- docs/api-reference/arcgis/arcgis-deck-layer.md
- docs/api-reference/arcgis/load-arcgis-modules.md
- docs/api-reference/arcgis/overview.md
- examples/get-started/pure-js/arcgis/app.js
- modules/arcgis/src/index.js
- website/contents/pages.js
- Change the resolved result of `loadArcGISModules` from array to object (see updated docs)
- Allow empty `modules` argument to `loadArcGISModules`
- Documentation pass
@damix911
> Clean up ArcGIS module API and docs

- modules/geo-layers/src/terrain-layer/terrain-layer.js
- modules/geo-layers/src/tile-layer/tile-2d-header.js
- modules/geo-layers/src/tile-layer/tileset-2d.js
- package.json
- yarn.lock
The TileLayer refactor broke TerrainLayer (`bbox` must be available before calling `getTileData`)
- Call `getTileData` after tile metadata is populated
- Fix id collision in TerrainLayer
- Bump root loaders.gl dependencies
> TerrainLayer fixes

- modules/arcgis/package.json
My previous PR #4252 was missing some build-related info in the `package.json` file for the `@deck.gl/arcgis` module. This is a first attempt at fixing it.
> Fix package.json for modules/arcgis

- docs/layers/terrain-layer.md
- modules/geo-layers/src/terrain-layer/terrain-layer.js
- website/src/components/demos/terrain-demo.js
For #4236 
- Only display a tile if both the mesh and the surface image are loaded
- Fix an update issue in non-tiled scenario when `terrainImage` is changed
- Restore no texture option in the demo
> Improve TerrainLayer loading experience

- bindings/pydeck/tests/dev-containers/README.md
- bindings/pydeck/tests/dev-containers/build-and-screenshot.sh
- bindings/pydeck/tests/dev-containers/docker-compose.yml
- bindings/pydeck/tests/dev-containers/jupyterlab/Dockerfile
- bindings/pydeck/tests/dev-containers/jupyternb/Dockerfile
- bindings/pydeck/tests/dev-containers/snap.py
- bindings/pydeck/tests/dev-containers/test.ipynb
For #4103 
A group of scripts that make local dev testing/release faster. A great deal of my time while publishing is around verifying that pydeck continues to work in its different environments.
- Add docker-compose and Dockerfiles to create/run JupyterLab and Jupyter Notebook
- Add Python script `snap.py` for running test Jupyter notebook in both Jupyter environments
- Add test notebook `test.ipynb`
> pydeck: Add containerized JupyterLab/Jupyter Notebook tools for local development

- bindings/pydeck/examples/gpu_grid_layer.py
- bindings/pydeck/examples/great_circle_layer.py
- bindings/pydeck/examples/grid_layer.py
- bindings/pydeck/examples/h3_cluster_layer.py
- bindings/pydeck/examples/hexagon_layer.py
- bindings/pydeck/examples/s2_layer.py
- bindings/pydeck/examples/scatterplot_layer.py
- bindings/pydeck/examples/screengrid_layer.py
- bindings/pydeck/examples/text_layer.py
- bindings/pydeck/examples/trips_layer.py
Added following examples:
ScatterplotLayer
TextLayer
GPUGridLayer
GreatCircleLayer
HexagonLayer
H3ClusterLayer
GridLayer
S2Layer
ScreenGridLayer
TripsLayer
For #4281
Background
Added new examples into pydeck basing on javascript examples as requested.
There is one additional example (TripsLayer) comparing to pull request #4282 which was canceled. All of the comments provided in PR4282 are fixed in this pull request. Formatting is done with the help of python black library
Change List
Added: screengrid_layer.py, s2_layer.py, grid_layer.py, h3_cluster_layer.py, hexagon_layer.py, great_circle_layer.py, gpu_grid_layer.py, scatterplot_layer.py, text_layer.py, trips_layer.py into \bindings\pydeck\examples\
> pydeck: Add 10 additional examples 

- modules/core/src/lifecycle/component-state.js
- modules/geo-layers/src/mvt-tile-layer/mvt-tile-layer.js
- modules/geo-layers/src/terrain-layer/terrain-layer.js
- modules/test-utils/src/lifecycle-test.js
- package.json
- test/modules/geo-layers/terrain-layer.spec.js
- test/modules/imports-spec.js
- test/node.js
- yarn.lock
test-utils' `testLayer` was relying on errors thrown by `LayerManager` and `DeckRenderer`. As of #4135 we are no longer throwing errors, but calling the `onError` callback. This resulted in several new layer tests not failing despite of lifecycle errors.
- Fix `testLayer` error handling
- Fix `TerrainLayer` tests
- Fix `MVTTileLayer` tests
- Fix an unnecessary crash in `ComponentState` when async prop is rejected
> [test-utils] Fix testLayer

- docs/layers/s2-layer.md
- docs/upgrade-guide.md
- modules/geo-layers/package.json
- modules/geo-layers/src/s2-layer/s2-geometry.js
- modules/geo-layers/src/s2-layer/s2-utils.js
- package.json
- scripts/bundle.config.js
- test/modules/geo-layers/s2-layer.spec.js
deck.gl's pre-bundled version excluded s2-geometry because of its size (the module is not tree shakable). However, because s2-geometry does not offer an umd entry point, it is not easy to supply this dependency in a scripting environment. We recommended `https://bundle.run` in the documentation in the past, but it's not always reliable.
- Cherry pick s2-geometry utilities into the geo-layers module
There is an outstanding discussion with @macrigiuseppe on exposing some of these functionalities.
> Remove s2-geometry dependency

- modules/arcgis/src/arcgis-deck-external-renderer.js
- test/apps/arcgis/README.md
- test/apps/arcgis/app.js
- test/apps/arcgis/index.html
- test/apps/arcgis/package.json
- test/apps/arcgis/webpack.config.js
It seems like a [recent change](https://github.com/uber/deck.gl/pull/4302/commits/02f3ecd8ea0e0075bd70d562641929964f5d5589) _"broke"_ `ArcGISDeckExternalRenderer`, the 3D integration between deck.gl and ArcGIS.
It's tricky to see the breakage because there is still no sample app, nor test, in the codebase. Plus, 3D integration was WIP, and things did not look correct, but at least it was possible to write apps that did not crash.
I am fine with merging this; to see the positive impact of this PR I am working on some pens that I will share once ready. Once things are looking good I will work on adding automated testing and a `pure-js` sample app in the codebase, specific for 3D.
> Fix .gl and .state access

- bindings/pydeck/pydeck/bindings/deck.py
- bindings/pydeck/pydeck/io/html.py
For #4103 
Supports rendering of HTML pages in Collab
The 2-way interactive widget won't work in Collab yet. We seem to be awaiting this issue: https://github.com/googlecolab/colabtools/issues/60
- Add built-in support for rendering .to_html in Google Collab
> pydeck: Support rendering in Google Collab

- modules/layers/src/path-layer/path-tesselator.js
In an application with heavy path layer usage the typed array manager
can get to a point where the number of points exactly fits in the
allocated buffer.  This problem is this does not appear to be accounting
for the shaderAttributes and results the runtime error:
'glDrawElementsInstancedANGLE: attempt to access out of range vertices in attribute'
This extra padding 3 * 3 is based on how the type array manager needs to allocate.
> Workaround for invalid attribute index access

- modules/core/src/shaderlib/project/project-functions.js
- modules/core/src/shaderlib/project/viewport-uniforms.js
- test/modules/core/shaderlib/project/project-functions.spec.js
The CPU `projectPosition` to GPU `project_position` parity was broken when using CARTESIAN coordinate system with Web Mercator projection (#4140).
- `projectPosition` and `getUniformsFromViewport` now share the same logic
- Additional unit tests
> Fix projectPosition in CARTESIAN coordinate system

- examples/website/image-tile/README.md
- examples/website/image-tile/app.js
- examples/website/image-tile/index.html
- examples/website/image-tile/package.json
- examples/website/image-tile/webpack.config.js
Following up on https://github.com/uber/deck.gl/issues/4230#issuecomment-590906607, this is the tiling example.   This is in conjunction with the data being merged on to master here: https://github.com/uber-common/deck.gl-data/pull/15.  We should probably hold off on merging this PR until we can test the raw data on master there locally.
After @Pessimistress merged #4246 I am giving an example here of the non-geospatial use-case, displaying the capability and also matoivating future creation of a new controller that has smoother zoom/pan as per https://github.com/uber/deck.gl/issues/4230#issuecomment-590911073
- Add a non-geospatial tiling example
> Non-Geospatial Tiling Example

- modules/core/src/lib/composite-layer.js
- modules/core/src/lib/layer-manager.js
- modules/core/src/lib/view-manager.js
- modules/core/src/utils/flatten.js
- test/modules/core/utils/flatten.spec.js
Before:
- Array of 10,000 items: 18.3K iterations/s ±4.33%
- Array of 1,000 nested items (max depth = 10): 25.2K iterations/s ±2.64%
After:
- Array of 10,000 items: 23.7K iterations/s ±8.20%
- Array of 1,000 nested items (max depth = 10): 34.9K iterations/s ±4.09%
`Array.flat(Infinity)`:
- Array of 10,000 items: 608 iterations/s ±3.79%
- Array of 1,000 nested items (max depth = 10): 1.22K iterations/s ±1.59%
- Private `flatten` utility API
> Improve flatten perf

- modules/core/src/index.js
- modules/geo-layers/src/tile-layer/tile-layer.js
- test/modules/geo-layers/tile-layer/tile-layer.spec.js
For #4350
- Expose the `flatten` utility from core
- Flatten returned results from `renderSubLayers`
> Fix TileLayer crash when renderSubLayers returns array

- modules/core/src/shaderlib/project/viewport-uniforms.js
- test/modules/core/shaderlib/project/project-functions.spec.js
- test/modules/core/shaderlib/project/viewport-uniforms.spec.js
`geospatialOrigin` is frounded in lnglat space while `shaderCoordinateOrigin` is frounded in common space.
- Match `geospatialOrigin` and `shaderCoordinateOrigin`
- Tests
> Fix jumpy projection using WEB_MERCATOR_AUTO_OFFSET with CARTESIAN coordinates

- docs/layers/mvt-layer.md
- docs/layers/tile-layer.md
- examples/website/map-tile/app.js
- modules/geo-layers/src/mvt-layer/mvt-layer.js
- modules/geo-layers/src/tile-layer/tile-layer.js
- modules/geo-layers/src/tile-layer/utils.js
- modules/test-utils/src/generate-layer-tests.js
- test/modules/geo-layers/mvt-layer.spec.js
- test/modules/geo-layers/tile-layer/tile-layer.spec.js
- test/modules/geo-layers/tile-layer/utils.spec.js
- test/render/test-cases/mvt-layer.js
- website/src/components/demo-launcher.js
- website/src/components/demos/geo-layer-demos.js
- website/src/components/demos/layer-demo-base.js
- website/src/components/demos/layer-demos.js
For #4317 
- Add `data` prop to `TileLayer`, make `getTileData` optional
- Remove `MVTLayer`'s `urlTemplates` prop, use `data` instead
- Validate and deep-compare URL templates
- Docs
- Tests
- Update website demos
> TileLayer and MVTLayer API audit

- docs/layers/terrain-layer.md
- modules/geo-layers/src/terrain-layer/terrain-layer.js
- modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js
- website/src/components/demos/geo-layer-demos.js
- website/src/utils/layer-params.js
For #3591 
- Change the embedded example in TerrainLayer docs to use single mesh (easier for users to click on images and see what they are). We already have a tiled example in the Examples tab.
- Forward the `material` prop to `SimpleMeshLayer`
- `SimpleMeshLayer`: added a hack to allow `mesh` to use world coordinates instead of meter-offsets @xintongxia
> Fix TerrainLayer support for single mesh

- docs/api-reference/arcgis/deck-renderer.md
- docs/api-reference/arcgis/overview.md
This PR does two things:
- _Important_. Fixes two links in `docs/api-reference/arcgis/overview.md`
- _Less important but worth considering_. Adds the word _"experimental"_ in a couple of places wrt the novel `DeckRenderer` class.
> Some minor changes for 8.1 ArcGIS docs

- modules/core/src/passes/layers-pass.js
- modules/geo-layers/src/terrain-layer/terrain-layer.js
- modules/geo-layers/src/tile-layer/tile-layer.js
- test/apps/mapbox-tile/app.js
- test/modules/core/passes/index.js
- test/modules/core/passes/layers-pass.spec.js
- test/modules/core/passes/shadow-pass.spec.js
For #4369
`layerIndex` is used to set the [default polygonOffset](https://github.com/uber/deck.gl/blob/a4767c4cb49dcdc6ad55d334feca8f1555cfe967/modules/core/src/lib/layer.js#L79). It is important for reducing z-fighting between multiple 2D layers.
When using the `TileLayer`, sublayer indices are currently calculated as this:
| tile | layer | layerIndex |
| --- | --- | --- |
| tile0 | subLayer0 | 0 |
| | subLayer1 | 1 |
| | subLayer2 | 2 |
| tile1 | subLayer0 | 3 |
| | subLayer1 | 4 |
| | subLayer2 | 5 |
| tile2 | subLayer0 | 6 |
| | subLayer1 | 7 |
| | subLayer2 | 8 |
In fact, all `subLayer0`s are rendering contents from the same logical map layer.  The artificial offset between them causes unexpected occlusions. After this PR, sublayer indices will look like this:
| tile | layer | …
> Fix polygon offset calculation in TileLayer

- docs/layers/h3-hexagon-layer.md
- examples/layer-browser/src/examples/additional-layers.js
- modules/geo-layers/src/h3-layers/h3-hexagon-layer.js
- test/modules/geo-layers/h3-layers.spec.js
For #4329
- Detects when the input hexagon set has multiple resolutions, setting rendering to "high precision" when true
- Fixes color accessor in H3HexagonLayer example
- Adds tests for high precision rendering
> Add support for multiple H3 resolutions to H3HexagonLayer

- modules/layers/src/point-cloud-layer/point-cloud-layer.js
- test/modules/layers/point-cloud-layer.spec.js
When the prop **sizeUnits** was set to **meters** it would access a field that didn't exist.
This has been corrected and a test added.
> Fix PointCloud sizeUnits as "meters"

- modules/jupyter-widget/src/create-deck.js
- test/modules/jupyter-widget/create-deck.spec.js
For #4103 
- As discussed in #4375 there is an issue when the jupyter widget initializes using a synchronous API but the custom library script loading happens asynchronously. 
- Wait for script loading to complete
> pydeck/jupyter-widget: Call mergeConfiguration again after addCustomLibraries complete

- bindings/pydeck/pydeck/bindings/layer.py
- modules/jupyter-widget/src/binary-transport.js
- modules/jupyter-widget/src/widget.js
- test/modules/jupyter-widget/binary-transport.spec.js
Previously a TypedArray for a binary DataView could be embedded in the JSON passed to @deck.gl/json. It's unclear what changed but in recent code this TypedArray is being converted to a dictionary, which breaks binary transfer.
This PR updates the Python interface for binary transfer (which made this issue easier to test) and assigns the value of data in a TypedArray to an already-instantiated layer, rather than the JSON specification for that layer.
- Update Python interface
- Have `@deck.gl/jupyter-widget/binary-transport` add data to layers via layers.clone instead of setting a layer's data attribute directly.
> @deck.gl/jupyter-widget and pydeck: Fix binary data bug

- bindings/pydeck/README.md
- bindings/pydeck/docs/installation.rst
For #4103 
- Update docs to align JupyterLab's @deck.gl/jupyter-widget installation to pydeck's
Trying to avoid this @deck.gl/jupyter-widget error: `Error: Module @deck.gl/jupyter-widget, semver range 8.1.0-beta.3 is not registered as a widget module`. A combination of synchronizing the dependencies via these instructions as well as `jupyter lab clean` got around this.
> pydeck: Update installation instructions for JupyterLab

- modules/layers/src/geojson-layer/geojson-layer.js
- modules/layers/src/path-layer/path-layer.js
- modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
For https://github.com/uber/deck.gl/pull/4365
The GeoJsonLayer splits paths and polygons in Polygon, MultiLineString and MultiPolygon features into multiple data objects before passing them to the sublayers.
To highlight all paths/polygons in the same source geometry, they must be rendered with the same picking color.
- PathLayer picking color when used as a sublayer
- PolygonLayer picking color when used as a sublayer
- GeoJsonLayer treatment of `highlightedObjectIndex`
> Fix GeoJSON multi-geometry highlighting

- bindings/pydeck/docs/conf.py
- bindings/pydeck/docs/gallery/html/grid.html
- bindings/pydeck/docs/images.rst
- bindings/pydeck/docs/index.rst
- bindings/pydeck/docs/scripts/README.md
- bindings/pydeck/docs/scripts/embed_examples.py
- bindings/pydeck/pyproject.toml
For #4103 
Read the Docs doesn't seem to support isolated html pages that aren't explicitly included somewhere in the toctree or via a link
- More explicit MIT license
- Embed HTML directly rather than use iframes (fixes tooltip cropping issues–div would get cut-off in the iframe)
- Separate out file used to include assets in toctree (images.rst, formerly part of index.rst)
> pydeck: Embed HTML in documentation directly

- .readthedocs.yml
- bindings/pydeck/docs/conf.py
For #4103
Support for ReadTheDocs.io to build documentation from scratch.
This might take a few PRs to get right.
Multi-language docs, stable and development docs, and hosted Elasticsearch are all good reasons to use ReadTheDocs.io. While we're not doing it in the short-term, I'd like to support the option to host docs here.
- Install pydeck from scratch for RTD
- Support RTD running embed_examples.py
> pydeck: Update RTD.io config to install pydeck and generate embedded examples

- modules/layers/src/text-layer/utils.js
For #4434
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCodePoint
- Replace `fromCharCode` with `fromCodePoint`
> TextLayer: support UTF-32 characters when using binary data

- bindings/pydeck/docs/index.rst
The docs homepage has a link to create a bug report issue. This simply prefills `pydeck:` in the title bar as a nudge for a user to include `pydeck` in the title.
Alternatively, you could have a separate `pydeck` badge, and a `Bug Report (pydeck)` issue template that asks for Pydeck-specific info, like Jupyter environment, pydeck version, etc. And then also applies the `pydeck` badge.
> pydeck: Include `pydeck:` in title for bug report link

- bindings/pydeck/pydeck/bindings/deck.py
- bindings/pydeck/tests/bindings/test_deck.py
Address #4493
- Handle empty layers
- Add test case
> pydeck: Allow an empty layer argument in Deck object

- website/contents/pages.js
I was unaware that there's a `deck.gl/json` [conversion reference](https://github.com/visgl/deck.gl/blob/master/docs/api-reference/json/conversion-reference.md) documentation page, because it isn't available on the website.
This adds the conversion reference page and the [`json-configuration`](https://github.com/visgl/deck.gl/blob/master/docs/api-reference/json/json-configuration.md) page to the website. The latter is just a stub, so if you don't want to include it on the website that's fine, but it would be nice for the conversion reference to be on the website.
> Add JSON conversion reference to website

- website-gatsby/src/examples/example-data-filter-demo.jsx
- website/src/components/demos/data-filter-demo.js
`manitude` should be `magnitude`
> Fix typo in data filter example

- modules/core/src/lib/deck-picker.js
> Fix DeckPicker.resize crash when float FBO is not supported

- modules/layers/src/path-layer/path-layer.js
- modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
For #4539
`object` is by default populated as `data[index]` which could be undefined. Use the first data object instead.
- Broken by #4426
> Fix picking info population

- modules/core/src/transitions/transition.js
- test/modules/core/transitions/transition.spec.js
Currently the start time of a transition is recorded when it's triggered, not when it's first rendered. As a result, the CPU time during the start frame eats into the requested duration. This becomes a problem if heavy processing is required to trigger the transition (e.g. attribute transition may need to process the incoming buffer).
- Fix transition start delay
> Fix transition start delay

- bindings/pydeck/pydeck/io/html.py
pydeck throws an error on windows due to different environment encodings.
For #4576
Previously added in #4405
- set `encoding="utf-8"` on javascript read when set offline is set to True.
@ajduberstein
> pydeck: set offline javascript read to use utf-8 encoding

- modules/core/src/lib/deck-picker.js
For https://github.com/visgl/deck.gl/issues/4584
The picking system can handle up to 255 layers.
The above issue is observed when there is a large number of layers (in the reported use case, 4 TileLayers * cached tiles * 4 sublayers per tile). This PR drops non-pickable layers from the list to use indices more efficiently. Although it does not solve all potential issues caused by the tile layer, in normal use cases picking should behave as expected.
This PR is intended to be a quick workaround to patch production.
- Assign layer index more efficiently in the picking pass.
> Workaround for picking index overflow

- modules/core/src/controllers/orbit-controller.js
- modules/core/src/views/orbit-view.js
- test/modules/core/views/view.spec.js
Per documentation, `orbitAxis` should be defined in the `OrbitView` constructor. However, if it's not also specified in `viewState`, `OrbitController`  falls back to the default value. This results in confusing behavior where the controller created by `new OrbitView({orbitAxis: 'Y'})` actually produces viewStates with `orbitAxis: 'Z'`.
- `OrbitController` uses `OrbitView`'s `props.orbitAxis` if specified
- Unit tests
> Fix: OrbitView's orbitAxis prop is not used by OrbitController

- modules/core/src/index.js
- modules/main/src/index.js
This allows people to write their own `TransitionInterpolator`s without copying that code into their own code base. 
This begins to address #4407.   I think, judging by the docs, that this is something that might have been assumed to be happening, but isn't: https://github.com/visgl/deck.gl/blob/master/docs/api-reference/view-state-transitions.md#view-state-transitions: " ...But a user can provide any custom implementation for this object using TrasitionInterpolator base class."
- Export `TransitionInterpolator` from the core.
> Export TransitionInterpolator

- docs/api-reference/viewport.md
- examples/website/map-tile/app.js
- modules/aggregation-layers/package.json
- modules/core/package.json
- modules/core/src/viewports/viewport.js
- modules/core/src/viewports/web-mercator-viewport.js
- modules/geo-layers/package.json
- modules/geo-layers/src/tile-layer/utils.js
- package.json
- yarn.lock
This is in preparation for fixing tile fetching at extreme pitch angles.
We currently calculate visible bounds of a viewport by unprojecting the four screen corners. At pitch ~= 72, the horizon comes into view and the top two corners no longer unproject to reasonable coordinates (points fall behind the camera). This PR switches to use the `getBounds` utility in @math.gl/web-mercator which produces correct results.
- Add `viewport.getBounds()`. Each viewport type may need to implement its own bounding box calculation.
> Add viewport.getBounds

- modules/core/src/utils/typed-array-manager.js
- modules/layers/src/path-layer/path-tesselator.js
- test/modules/core/utils/typed-array-manager.spec.js
For https://github.com/visgl/deck.gl/issues/4604
The padded area in `PathLayer`'s interleaved `positions` attribute is never assigned. The numbers are uploaded to the WebGL buffer as `Infinity`s and are causing problems in `mix()`.
- TypedArrayManager initializes padded area with 0s
- Unit test
> Fix NaN values in recycled typedarray for PathLayer

- modules/geo-layers/src/tile-layer/tile-layer.js
For #4608 
Described in #4608 
- Change the check to wipe the current cached layers when updateTrigger variables are updated.
> Wipe the current cached layers when updateTrigger variables are updated

- examples/website/map-tile/app.js
- modules/geo-layers/src/tile-layer/tile-2d-traversal.js
- modules/geo-layers/src/tile-layer/tileset-2d.js
- modules/geo-layers/src/tile-layer/utils.js
- test/modules/geo-layers/tile-layer/utils.spec.js
- website/src/actions/app-actions.js
- website/src/components/demos/map-tile-demo.js
- website/src/components/info-panel.js
- website/webpack.config.js
For #4482 
- Use frustum culling in OSM tile traversal
- Show tile boundary in website demo
> Use frustum culling in OSM tile traversal

- dev-docs/RFCs/proposals/data-manager-rfc.md
- dev-docs/RFCs/proposals/transport-format-rfc.md
Trying to generalize the need that arose from pydeck's binary support.
> Data Manager RFC

- docs/layers/geojson-layer.md
- docs/layers/scatterplot-layer.md
- modules/layers/src/geojson-layer/geojson-layer.js
- modules/layers/src/scatterplot-layer/scatterplot-layer.js
- test/modules/layers/index.js
- test/modules/layers/scatterplot-layer.spec.js
The objective of this PR is to add points by pixels (in addition to the current meters option) to the ScatterPlot layer.
In the same way as `lineWidthUnits` works for lines, this PR adds `pointRadiusUnits` for points. Also, the same options: `meters` and `pixels`, with `meters` as default one.
**Why?** right now, if you want to have points with the very same size in every zoom: you will see how a new layer is drawn
Using `pointRadiusUnits: "pixels"`:
- Added `pointRadiusUnits` prop to `GeoJsonLayer`
- Added `radiusUnits` prop to `ScatterplotLayer`
- Docs
> Adding points by pixels to ScatterplotLayer 

- docs/layers/tile-layer.md
- examples/website/map-tile/app.js
- modules/geo-layers/src/tile-layer/tileset-2d.js
- modules/geo-layers/src/tile-layer/utils.js
- test/modules/geo-layers/tile-layer/utils.spec.js
mapbox-gl uses `floor`. We changed from `floor` to `ceil` in https://github.com/visgl/deck.gl/pull/4117 to increase the quality of raster tiles. This results in very aggressive fetching behavior.
The change saves about 40% of tile loads in worst-case scenarios.
- Adjust zoom level by tile size
- Docs
@ilan-gold
> TileLayer: adjust zoom by tileSize

- bindings/pydeck/Makefile
- modules/jupyter-widget/package.json
- yarn.lock
> pydeck: Correct JL2 dependency bug

- docs/shader-modules/project.md
- modules/core/src/lib/constants.js
- modules/core/src/shaderlib/project/project-functions.js
- modules/core/src/shaderlib/project/project.glsl.js
- modules/core/src/shaderlib/project/viewport-uniforms.js
- modules/core/src/shaderlib/project32/project32.js
- test/modules/core/shaderlib/project/project-glsl.spec.js
For #4638
- Add `project_get_orientation_matrix` shader function
- Docs
> Globe Projection (PR2)

- modules/core/src/shaderlib/project/project.glsl.js
- modules/layers/src/arc-layer/arc-layer.js
- modules/layers/src/path-layer/path-layer-vertex.glsl.js
- modules/layers/src/path-layer/path-layer.js
- modules/layers/src/scatterplot-layer/scatterplot-layer.js
- test/apps/globe/app.js
- test/apps/globe/index.html
- test/apps/globe/package.json
- test/apps/globe/webpack.config.js
For #4638
This PR adds a test application and demonstrate preliminary support for the `GlobeView` among core layers.
A few layers require more substantial work to be done in follow up PRs, see https://github.com/visgl/deck.gl/issues/4638#issuecomment-637927760
- Add test application
- Support globe projection in PathLayer's vertex shader
- Use consistent mesh orientation (front/back) in core layers
> Globe Projection (PR3)

- docs/api-reference/test-utils/test-layer.md
- modules/test-utils/src/index.js
- modules/test-utils/src/lifecycle-test.js
- test/modules/core/lib/layer.spec.js
For https://github.com/visgl/deck.gl/pull/4365#issuecomment-639642708
Note that the skipped MVTLayer test still does not pass with this PR. It will rely on https://github.com/visgl/deck.gl/pull/4658
- Add `testLayerAsync` to test-utils
- Remove deprecated `testUpdateLayer` and `testDrawLayer` (not documented, not used)
- Docs
> [test-utils] Add testLayerAsync

- modules/core/src/lib/deck.js
- test/render/test-cases/icon-layer.js
Currently, a viewport update is propagated to layers during render. If any new layer is set in `props`, it is initialized with the last viewport.
Technically layers should not be affected by viewport change after initialization. However, many layers do make assumptions during data update based on the type of view being used. This is mostly a problem during the render tests, where views may change between test cases. Using the previous viewport to initialize layers makes the test result dependent on the previous test case and is causing confusing behavior.
The change proposed by this PR does not have any perf impact. When `activateViewport` is called again during render, `viewportChanged` flag is false and therefore does not trigger duplicate layer updates.
- activate the current viewport …
> Always initialize new layers with the current viewport

- test/modules/geo-layers/tile-layer/tile-layer.spec.js
- Use `t.ok(subLayers.length < 2)` for test while layer hasn't yet loaded.
Should I check for `layer.isLoaded` in every test? I currently don't check in these two tests, since I didn't need it for the tests to pass (locally)
https://github.com/visgl/deck.gl/blob/1ca25a6b72cfcc93378e15998422e2edff60e825/test/modules/geo-layers/tile-layer/tile-layer.spec.js#L131-L146
> Fix failing TileLayer tests

- modules/layers/src/icon-layer/icon-manager.js
Handle `imageData` in `ImageBitmap` format
> Fix IconManager for loaders 2.2.0

- modules/core/src/lib/deck.js
For https://github.com/visgl/deck.gl/issues/4695
See inline comments
- Restore calling `onHover` for mouse out event
> Call onHover on all affected layers

- modules/core/src/shaderlib/project/project-functions.js
- modules/core/src/shaderlib/project/project.glsl.js
- modules/core/src/shaderlib/project/viewport-uniforms.js
- modules/geo-layers/src/mvt-layer/mvt-layer.js
- test/modules/core/shaderlib/project/project-functions.spec.js
Might help with https://github.com/visgl/deck.gl/issues/4605
Before:
After:
- Support `coordinateOrigin` in CARTESION + MERCATOR mode
> Fix MVTLayer projection precision

- docs/developer-guide/views.md
- modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer.js
- modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.js
- modules/core/src/lib/layer-manager.js
- modules/core/src/lib/layer.js
- modules/core/src/passes/layers-pass.js
- modules/core/src/viewports/viewport.js
- test/render/test-cases/mvt-layer.js
For #4712
This change allows the following layers to be used in a multi-view application:
- `TileLayer`
- `Tile3DLayer`
- `HeatmapLayer`
- `HexagonLayer`
- `H3HexagonLayer`
- `ScreenGridLayer`
- `layerManager.activateViewport` no longer sets the `viewportChanged` flag for all
- Add `layer.activateViewport` method - this is called when a layer is actually drawn.
- `changeFlags.viewportChanged` is only set if:
+ the layer has `props.visible: true`
+ the layer passes the `layerFilter`
+ the active viewport has changed deeply
- `this.context.viewport` during `layer.updateState` now reflects:
+ the current viewport, if this layer is being initialized
+ the last active viewport, if this layer has been drawn
- Some minor perf improvements on viewport comparison
> Set per-layer viewportChanged flag

- scripts/bundle.config.js
For #4717 
Looks like an unintended change from #4365
@jesusbotella you can build non-minified bundles by running `yarn build-bundle --env.dev` in each module.
> Fix bundle config

- modules/core/src/lib/picking/pick-info.js
- Fix bug where `pickingInfo.coordinate` is off if the viewport is not top-left aligned
> Fix coordinate when picking in multiple views

- bindings/pydeck/examples/pydeck_with_geopandas.py
- bindings/pydeck/pydeck/bindings/deck.py
- bindings/pydeck/pydeck/bindings/layer.py
- bindings/pydeck/pydeck/data_utils/__init__.py
- bindings/pydeck/pydeck/data_utils/type_checking.py
For #4499
Automatically call `__geo_interface__` on objects that implement it. Un-nest properties within the GeoJson.
- Automatically call and un-nest data within a GeoPandas DataFrame if passed to a layer
- Add example
```python
import geopandas as gpd
import pydeck
features = [{
"type": "Feature",
"geometry": {
"type": "Point",
"coordinates": [125.6, 10.1]
},
"properties": {
"name": "Dinagat Islands",
"radius": 1000000,
"color": [255, 160, 14]
}
},{
"type": "Feature",
"geometry": {
"type": "Point",
"coordinates": [0, 0]
},
"properties": {
"name": "Water",
"radius": 3000000,
"color": [155, 134, 152]
}
}]
gdf = gpd.GeoDataFrame.from_features(features)
layer = pydeck.Layer(
'GeoJsonLayer',
-    data=gdf.__geo_interface__,
+    data=gdf,
pickable=True,
)
pydeck.Deck(layers=[layer]).show() …
```
> pydeck: Better support for GeoPandas

- bindings/pydeck/pydeck/__init__.py
- bindings/pydeck/pydeck/bindings/__init__.py
- bindings/pydeck/pydeck/bindings/deck.py
- bindings/pydeck/pydeck/bindings/map_styles.py
- bindings/pydeck/pydeck/io/html.py
- bindings/pydeck/tests/io/test_html.py
Simplifies `Deck.to_html`, which will now return a string or an iframe with a srcdoc depending on which arguments are passed.
The srcdoc is particularly useful because this means that pydeck doesn't have to write a separate document from a Notebook, which makes it easier to get work into nbviewer
- Automatically detect whether or not pydeck is running in a Jupyter environment (with manual override in case this fails)
- Write a srcdoc in an iframe instead of a separate document
- Eliminate temporary files in pydeck
> pydeck: Simplify Deck.to_html()

- modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer-fragment.glsl.js
I had a bug that crashed the Edge Legacy browser. Determined the cause to be usage of the "return" statement in the fragment shader. Re-worked the logic flow with "else" clauses to achieve the same logic without using "return."
> Fix TextLayer fragment shader in Edge Legacy browser

- modules/core/src/passes/layers-pass.js
- test/modules/geo-layers/tile-layer/tile-layer.spec.js
When using `TileLayer` and `MapView({repeat: true})`, layers' `viewportChanged` flag is repeatedly set as we iterate through each copy of the world at low zoom levels. This results in `TileLayer` constantly trying to update and displaying incorrect tiles.
The bug was introduced by #4722. Prior to the PR viewport activation was called once per view. The PR started calling `layer.activateViewport` inside `shouldDrawLayer()`, which is executed once per sub-viewport.
- Resolve layer parameters (`shouldDrawLayer`, `renderIndex` etc.) only once per view
> Fix constant update when using TileLayer with repeated maps

- bindings/pydeck/examples/globe_example.py
- bindings/pydeck/examples/pydeck_with_geopandas.py
- bindings/pydeck/pydeck/bindings/deck.py
- bindings/pydeck/pydeck/bindings/view.py
- bindings/pydeck/pydeck/io/html.py
- bindings/pydeck/tests/io/test_html.py
Support the globe view within pydeck
- Add globe example
- Modify view to allow for height and width arguments
- Apply Black py34 formatter
> pydeck: Support globe view example

- bindings/pydeck/pydeck/bindings/deck.py
- bindings/pydeck/pydeck/io/html.py
- bindings/pydeck/tests/dev-containers/build-and-screenshot.sh
Fix `to_html` typo around iframe width (700px in the source vs '100%' listed in the docs for the default value) and call function that auto-detects a Jupyter environment on the correct line
> pydeck: Fix iframe rendering width default value

- examples/website/image-tile/app.js
This is not an issue when running stand-alone, but crashes the website when navigating between example pages.
- `useEffect` should not return a non-function
> Fix image-tile example crash on unmount

- bindings/pydeck/pydeck/io/html.py
- bindings/pydeck/tests/io/test_html.py
IPython throws a warning when you use don't use its `IFrame` class to write an iframe into a document, but their IFrame class doesn't support srcdoc (class source [here](https://github.com/ipython/ipython/blob/f8c9ea7db42d9830f16318a4ceca0ac1c3688697/IPython/lib/display.py#L245), which we use for writing our documents. 
- Suppress IPython warning for iframe usage
- Allow user to write a file and display it simultaneously
> pydeck: Suppress warning for IFrame usage

- modules/core/src/lib/uniform-transition-manager.js
- test/modules/core/lib/uniform-transition-manager.spec.js
When an async prop is resolved, `diffProps` currently re-triggers any ongoing uniform transition.
- Make sure transition's `fromValue` is always defined
> Fix uniform transition error when using async props

- examples/website/point-cloud/app.js
For https://github.com/visgl/deck.gl/issues/4798
- Use standard loaders.gl mesh header API
> Use standard API in point cloud example

- modules/core/src/lib/attribute/attribute.js
- modules/core/src/lib/layer.js
- test/modules/core/lib/layer.spec.js
After this PR, if a layer is never pickable or uses auto highlight, its picking colors attribute is not populated. This makes it so that:
- A non-pickable layer using large external binary will not throw the 'index out of picking color range' error
- Saves attribute packing time and memory for non-pickable layers
Note that a layer that was once pickable and then turned off will still update its picking colors buffer.
- Disable `instancePickingColors`/`pickingColors` attribute if `pickable` is off and `highlightedObjectIndex` is not specified
> Do not create unnecessary picking colors buffer

- modules/jupyter-widget/src/playground/utils/mapbox-utils.js
Fixes #4820 
I'll spend some time figuring out [how to incorporate attribution](https://docs.mapbox.com/help/how-mapbox-works/attribution/) with the Jupyter widget but for now I'll just remove it.
- Remove code that modifies the mapboxgl attribution footer
> Remove pydeck attribution in Mapbox footer

- bindings/pydeck/examples/07 - Binary Transport.ipynb
- modules/jupyter-widget/src/lib/jupyter-transport-view.js
- modules/jupyter-widget/src/playground/playground.js
- test/modules/jupyter-widget/binary-transport.spec.js
For #4824
A misnamed argument in the Transport Widget (``binary`` instead of ``dataBuffer``) broke binary transport in pydeck, which is still light on tests. I've added a demo notebook to make this easier to test in the future.
- Rename argument to `processDataBuffer ` that is causing an undefined variable error
- Add a Notebook example to make this easier to detect and test
> pydeck: Correct data buffer issue

- modules/core/src/lib/layer.js
- test/modules/core/lib/layer.spec.js
For #4833
- When `updateState` creates a new model, always set the picking module parameters.
> Fix picking module parameters on newly created model

- modules/core/src/lib/deck-picker.js
- modules/core/src/lib/deck.js
- modules/core/src/passes/pick-layers-pass.js
`PickLayerPass.render` is called without the `views` parameter, so `view.clear` is not respected in picking.
- Pass `views` to the picking render pass
> Fix picking with multiple views

- CHANGELOG.md
Fix broken link (old one generated a blank white page)
> Update changelog to correct web link for docs

- modules/json/src/transports/transport.js
- modules/jupyter-widget/src/lib/jupyter-transport.js
- modules/jupyter-widget/src/playground/playground.js
For #3864 etc
- Continue improving Transport abstraction for jupyter widget
- Adds `Transport.getRootDOMElement()` method to ensure playground doesn't directly access the jupyterWidget.
> jupyter-widget: playground no longer directly accesses jupyterWidget

- docs/api-reference/geo-layers/terrain-layer.md
The docs refer to `rScale`/`gScale`/`bScale`, but it's actually Scaler instead of Scale
For #
-
> [rgb]Scale -> [rgb]Scaler in docs

- docs/api-reference/mesh-layers/simple-mesh-layer.md
- modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js
For #4749
- Address concern that enabling vertex colors in SimpleMeshLayer in 8.2 will silently start rendering colors in existing meshes.
- Add a new pro `_useMeshColors` requiring users to explicitly enable mesh colors.
> mesh-layers: Add `_useMeshColors` prop to `SimpleMeshLayer`

- docs/api-reference/core/layer.md
For #4877
- Remove mentionings of `oldContext`
> Remove outdated parameter from layer class documentation

- modules/core/src/controllers/controller.js
- test/modules/core/controllers/test-controller.js
For https://github.com/visgl/deck.gl/issues/4874
- Avoid using deprecated `KeyboardEvent.keycode`, use `code` instead
Tested in Chrome, FF, Safari
> Avoid using deprecated KeyboardEvent.keycode

- docs/api-reference/arcgis/deck-layer.md
- docs/api-reference/arcgis/deck-renderer.md
- modules/arcgis/src/deck-props.js
Tentative fix for #4895 (I am still evaluating other strategies).
- Add a `getCursor` descriptor in `deck-props.js` so that a `deck.getCursor` property is recognized and copied when specified for a `DeckLayer` (2D, `MapView`) or a `DeckRenderer` (3D, `SceneView`).
> Possible solution to the ignored getCursor

- bindings/pydeck/docs/conf.py
- bindings/pydeck/docs/scripts/embed_examples.py
- bindings/pydeck/docs/scripts/snap_thumbnails.py
- bindings/pydeck/docs/scripts/utils.py
- bindings/pydeck/examples/arc_layer.py
- bindings/pydeck/examples/binary_transport.py
- bindings/pydeck/examples/bitmap_layer.py
- bindings/pydeck/examples/column_layer.py
- bindings/pydeck/examples/geopandas_integration.py
- bindings/pydeck/examples/globe_view.py
- bindings/pydeck/examples/great_circle_layer.py
- bindings/pydeck/examples/grid_layer.py
- bindings/pydeck/examples/hexagon_layer.py
- bindings/pydeck/examples/s2_layer.py
- bindings/pydeck/pydeck/bindings/deck.py
- bindings/pydeck/setup.py
- bindings/pydeck/tests/bindings/pydeck_examples/hexagon_layer_function.py
- bindings/pydeck/tests/bindings/pydeck_examples/minimal.py
- bindings/pydeck/tests/bindings/pydeck_examples/stacked.py
- bindings/pydeck/tests/bindings/test_layer.py
For #3640
This is from running `make pre-commit` within the pydeck folder. I think I'd prefer a shorter line length.
-
> pydeck: Additional formatting updates

- modules/core/src/passes/layers-pass.js
- test/modules/core/passes/layers-pass.spec.js
For #4913
The layer index resolver (#4388) allows us to draw sublayers from different tiles at the same z-index (polygonOffset).
A bug was introduced by #4586, when we tried to save layer indices by filtering out composite layers during picking. The implementation of the layer index resolver expects a parent layer to be resolved before its children. Because composite layers are never resolved during picking, it creates a discrepancy between the screen pass and the picking pass. 
- Resolve missing parent layer index
- Unit tests
> Fix layer index resolution in picking

- docs/developer-guide/debugging.md
- docs/faq.md
- examples/webpack.config.local.js
It seems that support for the Seer Chrome extension has been removed, but some misleading references to it lingered in the docs.
-
> Remove docs references to Seer

- docs/api-reference/extensions/data-filter-extension.md
- modules/extensions/src/data-filter/aggregator.js
- modules/extensions/src/data-filter/data-filter.js
- test/apps/data-filter/src/app.js
- test/modules/extensions/data-filter.spec.js
See doc change
- Add `countItems` option and `onFilteredItemsChange` prop to `DataFilterExtension`
- ✔ Chrome (Mac, Win)
- ✔ FF
- ✔ Safari
- ✔ Chrome on Android
- ✔ Safari on iOS
- ❌ Headless-gl
> Add GPU-based counter to DataFilterExtension

- modules/arcgis/src/commons.js
- modules/core/src/lib/deck.js
This fixes an issue that can arise when deck.gl is sharing the WebGL context and the `deck.props._framebuffer` property is set.
deck.gl will try, under certain circumstances, to resize the canvas even when it is intended to be managed externally and this can lead to all sorts of bugs.
For #4948.
- Don't resize the canvas if an external framebuffer was specified
> Avoid canvas resizing when not owned by deck.gl (i.e. when `props._framebuffer` is set)

- docs/api-reference/carto/carto-bqtiler-layer.md
- docs/api-reference/carto/carto-sql-layer.md
- docs/api-reference/carto/overview.md
- docs/table-of-contents.json
- examples/get-started/pure-js/carto/README.md
- examples/get-started/pure-js/carto/app.js
- examples/get-started/pure-js/carto/index.html
- examples/get-started/pure-js/carto/package.json
- examples/get-started/pure-js/carto/webpack.config.js
- examples/get-started/scripting/carto/index.html
- modules/carto/bundle.js
- modules/carto/package.json
- modules/carto/src/api/maps-api-client.js
- modules/carto/src/auth.js
- modules/carto/src/index.js
- modules/carto/src/layers/carto-bqtiler-layer.js
- modules/carto/src/layers/carto-layer.js
- modules/carto/src/layers/carto-sql-layer.js
- modules/main/package.json
- test/modules/carto/auth.spec.js
- test/modules/carto/carto-bqtiler-layer.spec.js
- test/modules/carto/carto-sql-layer.spec.js
- test/modules/carto/index.js
- test/modules/imports-spec.js
- test/modules/index.js
Deck.gl is today the preferred/official library for CARTO to build Location Intelligence apps. We consider that the best option for the future is to be part of Deck.gl family and we've created **@deck.gl/carto** for this 😄 . 
Why a module inside deck.gl repo?  It's a more collaborative approach. The closer to Deck.gl, the better. We want our engineers in this ecosystem rather than working on a wrapper or an external module.
We've included some examples at `examples/carto` but was not clear for us to find the right place. Feel free to suggest another location even if you consider it shouldn't be part of this repo. 
This module provides two layers:
- CartoSQLLayer: is a layer to visualize data hosted in your CARTO account and apply custom SQL.
- CartoBQTilerLayer: is a layer to visualize …
> CARTO module @deck.gl/carto

- docs/api-reference/core/globe-view.md
- modules/core/src/viewports/globe-viewport.js
- modules/geo-layers/src/mvt-layer/mvt-layer.js
- modules/geo-layers/src/tile-layer/tile-2d-traversal.js
- test/modules/core/viewports/globe-viewport.spec.js
Requires bug fixes in `@loaders.gl/mvt` and `@math.gl/polygon`
- Add `GlobeViewport.getBounds`
- Fix tile traversal in non-mercator viewports
- Parse MVT tiles to wgs84 in non-mercator mode
> MVTLayer: support globe view

- modules/layers/src/text-layer/text-layer.js
For https://github.com/visgl/deck.gl/issues/4987
- Forward `getText` trigger to sub layer
> Fix TextLayer getText update trigger

- examples/get-started/pure-js/carto/package.json
It adds the dependencies to @deck.gl/carto at pure-js example.
I've linked against the final module, so right now yarn asks to select the right version but once published it won't appear. 
Related with https://github.com/visgl/deck.gl/issues/4998
> Add dependencies to CARTO pure-js example

- modules/aggregation-layers/src/heatmap-layer/heatmap-layer.js
For #4998 
Sampling float texture in fragment shader worked in iOS 13 but not iOS 14
- Use RGBA texture for color scale
> Fix HeatmapLayer on iOS 14

- docs/api-reference/google-maps/overview.md
- modules/google-maps/src/google-maps-overlay.js
- modules/google-maps/src/utils.js
- test/modules/google-maps/google-maps-overlay.spec.js
Fix usage of `getTooltip` in GoogleMapsOverlay
The overlay sets top/left offsets of the canvas, which should be applied to the tooltip as well.
- Create a container for deck canvas and tooltip
- Unit test
> Fix built-in tooltip in GoogleMapsOverlay

- modules/aggregation-layers/src/heatmap-layer/heatmap-layer.js
- modules/aggregation-layers/src/heatmap-layer/triangle-layer.js
For #5003
- If reaggregation is triggered by zoom change, always debounce
- Disable update if `visible: false`
> Fix heatmap debounce

- modules/layers/src/bitmap-layer/bitmap-layer.js
Haven't touched the video side of the BitmapLayer, but this looks like a typo and might prevent errors in the future
> Fix typo in BitmapLayer

- examples/website/map-tile/app.js
Hide the borders of invisible tiles
> Fix border display in osm tile example

- modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js
After upgrading a project that used animations embedded in a gltf model from deck 7 to 8, a new error appeared in the console and the model with the animation wasn't rendering. Other models without animations still render correctly, and removing the animation prop from the broken model fixed the rendering (although it was static). The issue was isolated to an undefined object that was previously defined.
I think the `animationProps` object in question was deprecated and now we should use `timeline` under `context.deck.animationLoop`, and perhaps @tsherif has some more context around this history.
- Reference `timeline` from `deck.animationLoop` instead of `context.animationProps.time`
> [ScenegraphLayer] Fix context.animationProps undefined

- modules/carto/src/layers/carto-layer.js
According to composite Layers documentation,  
> to make updateTriggers work when accessors need to be recalculated, we need to remap the user's updateTriggers from the parent layer's prop names to the sublayers' prop names.
Currently, CartoLayer is not remapping the user's updateTriggers so layers like these
`
new CartoSQLLayer({
...
getRadius: d => radius,
updateTriggers: {
getRadius: radius
}
})
`
Is not changing the point radius when radius variable changes
> fix: CartoLayer: remap the user's updateTriggers from the parent layer

- modules/layers/src/solid-polygon-layer/solid-polygon-layer-vertex-main.glsl.js
For #5042 
- Use 64-bit positions for normal calculation
> Improve the precision of polygon normal calculation

- docs/api-reference/carto/carto-bqtiler-layer.md
- docs/api-reference/carto/carto-sql-layer.md
- modules/carto/src/layers/carto-bqtiler-layer.js
- modules/carto/src/layers/carto-layer.js
- modules/carto/src/layers/carto-sql-layer.js
This PR covers a need that is present in every CARTO-PS project. You need to know if the request to the tiler service failed and when it finished loading, so you can catch the error or display a loading spinner when necessary.
* Change documentation in carto-bqtiler-layer.md to include the new callbacks
* Change documentation in carto-sql-layer.md to include the new callbacks
* Add callbacks to carto-layer.js
> add onDataLoad and onDataError callbacks to carto-layer.js

- modules/geo-layers/src/tile-layer/tile-2d-header.js
- test/modules/geo-layers/tile-layer/tile-2d-header.spec.js
I tried my hand at fixing #5041 (using Kyle's recommendation) and added a test case.
In #5041 Kyle/Xiaoji noted that the individual tiles were not calling `done` on their `requestToken` if the `AbortSignal` was raised before the actual call to `getTileData`.  This PR should fix this.
- Update `TileHeader2D` to handle quickly-aborted tiles, before calling `getTileData`.
- Add a test that calls `abort` before awaiting the response of `_loadData`.
> Fix Quickly Aborted Tiles

- modules/aggregation-layers/src/utils/gpu-grid-aggregation/transform-mean-vs.glsl.js
For #5051
This bug affects ContourLayer, GridLayer and ScreenGridLayer
Same work around for ANGLE bug in https://github.com/visgl/deck.gl/pull/4113, applied to MEAN aggregation
- Explicitly set `gl_pointSize`
> Fix MEAN aggregation on Windows

- modules/core/src/shaderlib/project/project.glsl.js
For https://github.com/visgl/deck.gl/issues/5048#issuecomment-713839826
The shader compiler in Safari iOS really wants to reorder these two:
```
position_world.xyz -= project_uCoordinateOrigin;
position_world += project_uModelMatrix * vec4(position64Low, 0.0);
```
Safari is the new IE.
- Shift things around
Tested on iPhone.
> Fix project precision on iOS 14

- examples/playground/package.json
- examples/playground/src/deck-with-google-maps.js
GoogleMapsOverlay is not exported at main package anymore
> Fix Google basemap in playground

- modules/arcgis/src/deck-renderer.js
Seems like it should fix the wrong alignment between an ArcGIS basemap with `SceneView` and deck.gl.
@Pessimistress gets full credit for this; I was on the wrong track by trying to match the FOV of a `FirstPersonView`. Thanks!
For #5065
> ArcGIS 3D altitude fix

- modules/core/src/shaderlib/project/project.glsl.js
For #4981
Latitude 90/-90 projects to Infinity/-Infinity in Web Mercator projection. When passed to the project shader module they end up being clipped. This affects paths/polygons with vertices over the poles.
- Clamp latitude to reasonable range
> Shader support for extreme latitude coordinates

- examples/website/safegraph/README.md
- examples/website/safegraph/app.js
- examples/website/scenegraph/app.js
- website/src/doc-demos/layer-demo.js
- website/static/mapstyle/deck-light.json
Follow up of #5079
- Restore Mapbox custom layer example (requires 3D buildings)
- Fix basemap of the ScenegraphLayer example
- Fix basemap of embedded doc demos
- Fix console error in website light style
> Misc fixes of mapstyle in examples

- modules/carto/src/api/maps-api-client.js
- modules/carto/src/config.js
- modules/carto/src/layers/carto-sql-layer.js
- test/modules/carto/config.spec.js
During the beta of Maps API v2 we've changed the URLs and these changes are in production and they're not backward compatible.
> Fix: Maps APIv2 has changed the endpoints

- docs/api-reference/aggregation-layers/heatmap-layer.md
Example did not use 'data' in layer declaration, which could cause confusion for newer users since no heatmap is rendered without the data.
For #
-
> Add 'data' argument in HeatmapLayer documentation

- docs/api-reference/aggregation-layers/contour-layer.md
- docs/api-reference/aggregation-layers/cpu-grid-layer.md
- docs/api-reference/aggregation-layers/gpu-grid-layer.md
- docs/api-reference/aggregation-layers/grid-layer.md
- docs/api-reference/aggregation-layers/hexagon-layer.md
- docs/api-reference/aggregation-layers/screen-grid-layer.md
- modules/aggregation-layers/src/aggregation-layer.js
- modules/aggregation-layers/src/contour-layer/contour-layer.js
- modules/aggregation-layers/src/cpu-grid-layer/cpu-grid-layer.js
- modules/aggregation-layers/src/cpu-grid-layer/grid-aggregator.js
- modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-layer.js
- modules/aggregation-layers/src/hexagon-layer/hexagon-aggregator.js
- modules/aggregation-layers/src/hexagon-layer/hexagon-layer.js
- modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer.js
- modules/aggregation-layers/src/utils/aggregation-operation-utils.js
- modules/aggregation-layers/src/utils/bin-sorter.js
- modules/aggregation-layers/src/utils/cpu-aggregator.js
- test/modules/aggregation-layers/grid-aggregation-layer.spec.js
- test/modules/aggregation-layers/grid-layer.spec.js
- test/modules/aggregation-layers/hexagon-layer.spec.js
- test/modules/aggregation-layers/utils/aggregation-operation-utils.spec.js
- test/render/test-cases/grid-layer.js
For #4449
Because CPUAggregator does not use AttributeManager, the usage of accessors are not conforming with [documentation for standard accessor](https://deck.gl/docs/developer-guide/using-layers#accessors).
- All `get*Weight` props are now conforming (constant, callback, callback using non-iterable data)
- `get*Value` props are called with additional information to support non-iterable data usage.
- Unit tests
> CPU Aggregator accessor conformance

- modules/geo-layers/src/mvt-layer/mvt-layer.js
Restrictive limits for tilejson didn't work when a tilejson object is passed to `data` prop.
> fix: apply restrictive zoom for inline tilejson at MVTLayer

- modules/core/src/lib/attribute/data-column.js
- test/modules/core/lib/attribute/attribute.spec.js
- When using the default attribute packing, `value` is already overallocated, and we should not overallocate again when creating the WebGL buffer.
- When using custom attribute packing (binary attribute, `instancePickingColors`), this will be less efficient if the data size increases frequently over time. It is arguably a small use case comparing to the memory savings.
- Be conservative when allocating WebGL buffer size
> Remove double buffer overallocation

- modules/core/src/lib/layer.js
- modules/core/src/utils/typed-array-manager.js
- test/modules/core/lib/layer.spec.js
- test/modules/core/utils/typed-array-manager.spec.js
For #5076 
- limit the number of encoded indices in picking buffer to 2**24, log a warning.
- a way to set custom over allocation for buffers.
> Fix: Limit for color picking cache size; overAlloc override.

- modules/geo-layers/src/h3-layers/h3-hexagon-layer.js
For #5125
There are two issues:
- `_updateVertices` was mutating the points in `vertices`. Because the first and last points are the same object, it gets manipulated twice, resulting in a wild position.
- `ColumnLayer` unable to render the base disk along the curvature of the globe. This makes it impossible for `H3HexagonLayer` to generate vertices described by meter offsets. Temporary solution is to always use `PolygonLayer` to render the hexagons.
- Avoid mutating vertices
- Always use high precision mode in GlobeView
> Fix H3HexagonLayer in GlobeView

- modules/core/src/lib/attribute/attribute-transition-manager.js
`AttributeTransitionManager` is constructed for every layer, and if run in a WebGL1 context, will warn about attribute transition being disabled on initialization. This has been a source of confusion for many new users. This PR disables the warning unless attribute transition is actually requested.
- Move warning in `AttributeTransitionManager`
> Only warn about WebGL2 support if attribute transition is used

- modules/geo-layers/src/tile-layer/tile-2d-traversal.js
- modules/geo-layers/src/tile-layer/utils.js
- test/modules/geo-layers/tile-layer/utils.spec.js
For #5124
Note that the tile indices generated by this change are no longer culled by the view horizon; at low zoom levels, it will load the back of the earth if the back is not clipped by the far plane.
- Use frustum culling for globe tile traversal
- Test
> Fix GlobeView tile traversal

- docs/upgrade-guide.md
- modules/layers/src/arc-layer/arc-layer-vertex.glsl.js
- modules/layers/src/arc-layer/arc-layer.js
For #4621
Before:
After:
- ArcLayer handling of `wrapLongitude`
cc @heshan0131
> ArcLayer wrapLongitude always draws shortest path

- modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js
For #5185
There are two issues:
- Deprecation warning is shown when `scenegraph` is still loading and the value is `null`
- Loaders.gl warnings about not supported top-level options
- Ignore `scenegraph: null`
- Remove overriding of `getLoadOptions` method (the return value is used by luma's `GLTFInitiator`, not the loader)
> Fix ScenegraphLayer warnings

- docs/developer-guide/custom-layers/prop-types.md
- modules/core/src/lib/layer.js
- modules/core/src/lifecycle/component-state.js
- modules/core/src/lifecycle/prop-types.js
- test/modules/core/lifecycle/component-state.spec.js
- Add `transform` to prop type definition, remove hard-coded dataTransform call in ComponentState
- This technically changes `dataTransform` behavior - it now applies to synchronously supplied data as well
- Unit tests
> Support generic transform in prop types

- modules/layers/src/text-layer/font-atlas-manager.js
- modules/layers/src/text-layer/text-layer.js
FontAtlasManager was not initializing its texture correctly; instead it was relying on the IconLayer to override the texture parameters:
https://github.com/visgl/deck.gl/blob/8.3-release/modules/layers/src/icon-layer/icon-manager.js#L262
This was broken by #5197, resulting in aliased fonts:
After this PR, the TextLayer no longer manages its own texture. It supplies the font atlas canvas directly to its sublayer, which is then converted to a texture via the new prop transform API.
- Remove texture creation from FontAtlasManager
> Simplify FontAtlasManager

- modules/layers/src/point-cloud-layer/point-cloud-layer.js
- modules/layers/src/scatterplot-layer/scatterplot-layer.js
- modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
- modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js
For #5206 
Make `getShaders()` work consistently across all layers
- SolidPolygonLayer
- ScenegraphLayer
> Improve getShaders() support

- modules/layers/src/solid-polygon-layer/solid-polygon-layer-fragment.glsl.js
- modules/layers/src/solid-polygon-layer/solid-polygon-layer-vertex-main.glsl.js
Extruded `SolidPolygonLayer` can produce a lot of overdraw. 
Right now each extruded loop (e.g. a building) is connected to the next one with a rectangular polygon (which is discarded in fs).
For our test map with an extruded single `SolidPolygonLayer` FPS goes up from 12 > 26 FPS with this fix.
- create "degenerate" triangles in `SolidPolygonLayer`'s vertex shader instead of per fragment discard.
> Improve SolidPolygonLayer shaders performance (side polygons)

- docs/api-reference/layers/bitmap-layer.md
- docs/api-reference/layers/icon-layer.md
- docs/api-reference/mesh-layers/simple-mesh-layer.md
- modules/core/src/utils/texture.js
- modules/layers/src/text-layer/font-atlas-manager.js
- test/modules/core/lifecycle/component-state.spec.js
`image` prop type supports an additional format: plain object (see documentation).
- Fixes an issue in TextLayer where the sub layer does not update if the font atlas canvas is reused
- Provides a way to further customize texture generation, e.g. format, mipmaps
- This allows pydeck users to directly pass pixel data without having to encode it into an image. @ajduberstein 
- image prop transform supports plain object as input
- FontAtlasManager texture format
- Docs
> Support plain object as image source

- modules/core/src/lib/composite-layer.js
- modules/core/src/lib/layer.js
- modules/test-utils/src/lifecycle-test.js
- test/modules/core/lib/composite-layer.spec.js
For #5165
Right now, if a composite layer requires an update on viewport change (e.g. `TileLayer`, `HeatmapLayer`), `updateState` and `renderLayers` methods are called from `activateViewport`. However, we do not perform recursive updates during this phase, which means the new sublayers become orphans -- they are never used by the LayerManager.
This bug has been hidden by the fact that none of the official layers change sub layer props based on viewport properties. The TileLayer adds/removes sub layers during a separate update cycle, triggered when a tile is loaded.
- If a composite layer requires an update on viewport change, delay the call to `updateState` and `renderLayers` to the next update cycle
- `testLayer` util handles delayed update
- Unit test
> Fix composite layer update on viewport change

- modules/test-utils/src/generate-layer-tests.js
> [test-utils] Fix generateLayerTests crash when onBeforeUpdate is not supplied

- .github/workflows/test.yml
See the PR in `react-map-gl` for a description of why we should be using `pull_request` instead of `pull_request_target`: https://github.com/visgl/react-map-gl/pull/1251
> Use pull_request instead of pull_request_target in Github Actions workflow

- bindings/pydeck/docs/index.rst
Multiple links in the pydeck landing page are broken. This fixes that.
> pydeck: Fix broken documentation links

- docs/developer-guide/interactivity.md
- docs/upgrade-guide.md
- modules/core/src/lib/deck-picker.js
- modules/core/src/lib/picking/pick-info.js
- test/modules/core/lib/picking.spec.js
For #5177 
When picking with overlapping views, the current behavior is to always use the first viewport in the list.
See inline comment for new behavior.
The result could still be incorrect if the picked layer is rendered into multiple overlapping views. The only way to know which viewport is picked in that scenario is to pick once per view, which has a perf impact. We don't currently have a known use case like that.
This fix covers most use cases (minimap, screen space overlay) that are broken today.
- Be smarter in picking viewport
- Remove legacy `pickingInfo.lngLat`
- Add `pickingInfo.viewport`
- Fix unprojection in `onClick`
> Fix picking coordinate calculation in overlapping views

- docs/upgrade-guide.md
- modules/carto/src/layers/carto-layer.js
- modules/geo-layers/src/mvt-layer/coordinate-transform.js
- modules/geo-layers/src/mvt-layer/mvt-layer.js
- test/modules/geo-layers/mvt-layer.spec.js
`MVTLayer` coordinates transformation to WGS84.
Users usually think that something is wrong when trying to extract `object.coordinates` from `onClick/onHover` events in `MVTLayer`. Returned values are relative (0-1) coordinates in the tile, for better performance.
This PR includes a coordinates transformation to WGS84 latitude/longitude for `MVTLayer`.
- Add coordinates transformation function in `MVTLayer` for `onClick/onHover` events
- Link `MVTLayer` `onClick` method in `carto-layer`
- Unit tests
> MVTLayer coordinates transformation to WGS84

- docs/api-reference/core/linear-interpolator.md
- modules/core/src/controllers/controller.js
- modules/core/src/controllers/map-controller.js
- modules/core/src/transitions/linear-interpolator.js
Longitude/latitude should not be interpolated linearly when zoom is in transition. This fixes #2360 and is required to enable smooth scroll-zooming for #5089.
- Add `around` option to `LinearInterpolator`
- Controller passes `around` position on double tap
> Fix MapView center during linear zoom transition

- modules/jupyter-widget/src/deck-bundle.js
For #5063. Reverts inclusion of @deck.gl/carto in the core pydeck JS bundle.
We need a way of handling 3rd party/vendor-specific modules in pydeck that does not include that vendor's integration by default–much like how `@deck.gl/core` and `@deck.gl/carto` are separate modules there should be a `pydeck` core and `pydeck_carto`.
- Remove Carto module from standalone bundle
> Remove 3rd party modules from @deck.gl/jupyter-widget

- docs/api-reference/core/deck.md
- docs/api-reference/core/first-person-view.md
- docs/api-reference/core/globe-view.md
- docs/api-reference/core/map-view.md
- docs/api-reference/core/orbit-view.md
- docs/api-reference/core/orthographic-view.md
- docs/api-reference/react/deckgl.md
- docs/developer-guide/tips-and-tricks.md
- Update outdated content in the `Deck` class doc (e.g. geospatial-only references), add documentation
for missing props
- Consistent formatting
> Core API docs pass

- docs/api-reference/layers/geojson-layer.md
- docs/api-reference/layers/grid-cell-layer.md
- docs/api-reference/layers/polygon-layer.md
- docs/api-reference/layers/solid-polygon-layer.md
- docs/api-reference/layers/text-layer.md
- docs/api-reference/mapbox/mapbox-layer.md
- Fix links in API reference docs. Several links pointed to the `geo-layers` dir when they should've been pointed to the `layers` dir.
> Fix docs links

- modules/geo-layers/src/tile-layer/tile-layer.js
- test/modules/geo-layers/tile-layer/tile-layer.spec.js
Following up #5297, I think this is a reasonable extension of that work (which totally works exactly as expected).  I can totally close this if this is not something we are interested in @Pessimistress @chrisgervang @kylebarron - sorry for the multiple PR's, the use-cases were slightly different so I didn't notice this one when testing the fix for #5297 
I think `updateTriggers` and `finalizeState` have similar use cases in this case and the docs for deck.gl do state that `finalizeState` is for [releasing resources](https://deck.gl/docs/api-reference/core/layer#finalizestate)
- add a `finalizeState` method to `TileLayer` for aborting ongoing requests
> Abort Ongoing Requests when TileLayer is Destroyed

- docs/api-reference/geo-layers/tile-layer.md
- docs/upgrade-guide.md
- modules/geo-layers/src/tile-layer/tile-layer.js
The callback at TileLayer doesn't return the x,y,z of the tile and it's quite difficult to work only with the tile data. For example, if the user wants to transform to WGS84 we need to also provide the reference tile together with the data.
This is a small breaking change that we need to notify in the release.
- Return an array of tile objects at onViewportLoad instead of the content of the file.
- Updated TileLayer doc. I've included a section for the Tile class.
> Return tile objects at OnViewportLoad instead of data

- docs/api-reference/geo-layers/mvt-layer.md
- docs/api-reference/geo-layers/tile-layer.md
- modules/geo-layers/src/mvt-layer/mvt-layer.js
- test/modules/geo-layers/mvt-layer.spec.js
MVTLayer users receive the tiles content at `onViewportLoad` in local coordinates. This PR add a new getter `dataInWGS84` to return the tiles transformed in WGS84
Usage example:
```javascript
const onViewportLoad = tiles => {
tiles.forEach(tile => {
// data in local coordinates
const dataInLocalCoords = tile.data;
// data in world coordinates (WGS84)
const dataInWGS84 = tile.dataInWGS84;
});
};
new MVTLayer({
id: "..."
data: "..."
onViewportLoad
})
```
> Tiles content in WGS84 for MVTLayer

- docs/api-reference/geo-layers/mvt-layer.md
- modules/geo-layers/src/mvt-layer/mvt-layer.js
`onViewportChange` is only available for MVTLayer and it can be replaced by listening to `onViewStateChange` and `onViewportLoad`.
> Remove onViewportChange callback at MVT layer

- modules/core/src/utils/math-utils.js
- modules/core/src/viewports/viewport.js
- test/modules/core/utils/math-utils.spec.js
While experimenting with additional viewport settings, I noticed that our frustum calculation is based on a bunch of assumptions of how the projection matrix is composed. For example, if `projectionMatrix` is externally supplied without the fov/near/far parameters, it will not work. After this change, `getFrustumPlanes` will support any generalized use case.
I have verified that the output is identical (aside from slight precision differences) in MapView/OrbitView/OrthographicView. This utility is also already covered by test cases.
- New `getFrustumPlanes` algorithm
- Drop unused `viewport` fields: `cameraDirection`, `cameraUp`, `cameraRight`, and `projectionProps`
> Simpler and more robust frustum calculation

- modules/aggregation-layers/src/heatmap-layer/heatmap-layer.js
- modules/aggregation-layers/src/heatmap-layer/triangle-layer.js
This PR fixes a rare racing condition where the viewport during `heatmapLayer.renderLayers` is different from the viewport during `triangleLayer.draw`. It removes an old hack that was intended to avoid texture update when the layer is invisible. As of the current release, `heatmapLayer.updateState` and `heatmapLayer.renderLayers` are no longer triggered on viewport change when the layer is invisible.
- Remove `onRedraw` hack, update weight texture in `updateState`
> Fix HeatmapLayer update racing condition

- docs/api-reference/layers/polygon-layer.md
- docs/api-reference/layers/solid-polygon-layer.md
- docs/upgrade-guide.md
- modules/layers/src/polygon-layer/polygon-layer.js
- modules/layers/src/solid-polygon-layer/polygon.js
- modules/layers/src/solid-polygon-layer/solid-polygon-layer-vertex-side.glsl.js
- modules/layers/src/solid-polygon-layer/solid-polygon-layer.js
- test/bench/tesselation.bench.js
Follow up of #5223 
This PR allows binary users to specify the winding order of their polygon data if they choose to skip normalization.
I also considered using this prop to control the default winding order during normalization but decided against it for now. Benchmark shows that perf difference is ~10% when using one vs another. I've noticed that GeoJSONs converted from Shapefiles using GDAL do not conform to the right-hand rule, so it's hard to determine what's the best order to use simply based on the file format. It might introduce more confusion than benefit if we ask the user to explicitly pick one.
- Add `_windingOrder` prop to `PolygonLayer` and `SolidPolygonLayer`
- A benchmark test for polygon normalization
- Docs
> Add prop to specify winding direction in SolidPolygonLayer

- docs/api-reference/layers/bitmap-layer.md
- docs/whats-new.md
- examples/website/image-tile/app.js
- modules/layers/src/bitmap-layer/bitmap-layer-fragment.js
- modules/layers/src/bitmap-layer/bitmap-layer.js
For #
- Adds texture coordinates to bitmap layer picking info.
- Adjust picking color in bitmap layer fragment shader
- Decode picking color in BitmapLayer.getPickingInfo callback.
- Added notes to bitmap-layer.md and whats-new.md
Added pixel coordinates to image-tile example (gigapixel moon).
Needs docs etc. @kylebarron assuming you will be able to handle any remaining work?
> feature(core): Add pixel picking to BitmapLayer

- docs/api-reference/core/deck.md
- modules/core/src/lib/deck.js
For #4548, make it easier to customize cursor
- Pass `isHovering` to `getCursor`
> Pass isHovering to getCursor

- modules/core/src/lib/layer.js
- test/modules/core/lib/layer-manager.spec.js
This fixes the issue where a failed layer tries to update repeatedly on every render cycle.
- Reset the change flags and temporarily overwritten context when a layer's `updateState`/`draw` errors out
- Unit test
> Make sure layer context is reset even if a layer throws during update

- modules/geo-layers/src/terrain-layer/terrain-layer.js
For #5373 
- `onViewportLoad` is now called with an array of tiles
> Fix TerrainLayer error after onViewportLoad breaking change

- docs/api-reference/carto/carto-bqtiler-layer.md
- docs/api-reference/carto/carto-sql-layer.md
- modules/carto/src/layers/carto-layer.js
By default errors from `_updateData` in CartoLayers were caught and output to the error log, now the errors will be uncaught by default to help with tests and debugging.
> Avoid silencing errors by default in CartoLayer

- modules/core/src/views/orbit-view.js
- modules/core/src/views/orthographic-view.js
`OrbitView` and `OrthographicView` do not conform with documentation ("takes the same parameters as the `View` constructor") because they are selectively passing user props to the `Viewport` constructor. This blocks user from using their own `orthographic` or `projectionMatrix` settings.
- Merge props when constructing `OrbitViewport` and `OrthographicViewport`
> Fix OrbitView and OrthographicView custom prop handling

- docs/api-reference/core/lighting-effect.md
- docs/api-reference/core/post-process-effect.md
Allow the iFrame to stretch outside of the page width of the markdown.
Before:
After:
> Update styling of embedded codepen demos in docs

- modules/geo-layers/src/mvt-layer/mvt-layer.js
- modules/geo-layers/src/terrain-layer/terrain-layer.js
For https://github.com/visgl/deck.gl/issues/5453
When calling `load` with a non-array `loaders` argument it blocks the usage of other registered loaders.
- Make all `loaders` prop defaults arrays.
> Fix MVTLayer loaders prop propagation

- modules/core/src/controllers/controller.js
- modules/core/src/controllers/first-person-controller.js
- test/modules/core/controllers/controllers.spec.js
For #5458
`transitionInterpolator` was removed from `TransitionManager.defaultProps` by #5371 because the default only worked with `MapView`.
- restores default `transitionInterpolator` based on which controller is in use.
> Restore default transitionInterpolator

- modules/geo-layers/src/mvt-layer/mvt-layer.js
Picking info was launching an exception when trying to transform to WGS84.
> MVT: fix picking non-binary

- bindings/pydeck/pydeck/bindings/deck.py
Resolves #5474
api_keys dictionary expects keys of either mapbox, google_map or carto, which are accessed via provider.value.
> BUG FIX: pydeck api_keys 

- examples/layer-browser/package.json
- examples/playground/package.json
- examples/website/3d-tiles/package.json
- examples/website/globe/package.json
- examples/website/i3s/package.json
- examples/website/mesh/package.json
- examples/website/point-cloud/package.json
- examples/website/radio/package.json
- examples/website/safegraph/package.json
- examples/website/scenegraph/package.json
- modules/carto/package.json
- modules/core/package.json
- modules/geo-layers/package.json
- modules/jupyter-widget/package.json
- modules/layers/package.json
- modules/mesh-layers/package.json
- package.json
- yarn.lock
Bump loaders to 2.3.9. @loaders.gl^2.3.9 is required because the mime type was added in 2.3.9.
It fixes some errors with MIME type, for instance with scripting: https://github.com/visgl/deck.gl/pull/5455/files#r575313513
> Bump loaders.gl dependencies

- package.json
- test/render/test-cases/text-layer.js
- yarn.lock
- Bump ocular-dev-tools (nyc@^15 and updated config)
- Lower render test threshold for TextLayer render tests (no visible change, most likely due to font hinting/antialiasing changes in new Chrome)
> Try improve coverage report

- modules/geo-layers/src/mvt-layer/mvt-layer.js
Workaround for unrecognized/empty response from the tile server
- Force using a single loader to parse MVT data
> Force using a single loader for MVT data

- modules/core/src/lib/deck.js
- modules/core/src/lib/tooltip.js
For #5260
Before:
After:
- Clear tooltip if the viewport moves
> Clear tooltip when viewport changes

- modules/geo-layers/src/tile-layer/tile-layer.js
- Remove `Top level loader option 'signal' deprecated` warning
- Make sure that tiles can still be aborted when the user passes `loadOptions.fetch`
> Fix TileLayer fetch options

- modules/core/src/views/orbit-view.js
- modules/core/src/views/orthographic-view.js
For #5522
- `OrbitView`/`OrthographicView` should not pass `longitude`/`latitude` to the base `Viewport` constructor
> Force OrbitView/OrthographicView to create non-geospatial viewports

- modules/jupyter-widget/package.json
- modules/jupyter-widget/webpack.config.js
We do not have to do a full transpile of the source. Jupyter Notebook's browser requirement: https://jupyter-notebook.readthedocs.io/en/stable/notebook.html#browser-compatibility
- Specify babel targets
- Uncomment `inline-webgl-constants` plugin (fixed by #5517)
> Update jupyter-widget bundle config

- examples/webpack.config.local.js
Fallout of the build targets change (missing polyfill dependencies)
> Fix start-local script in examples

- docs/table-of-contents.json
Fix indeterministic failure in populating the TOC with `README.md` pages. cc @ibgreen
> Fix website TOC

- examples/layer-browser/package.json
- examples/playground/package.json
- examples/website/3d-tiles/package.json
- examples/website/globe/package.json
- examples/website/i3s/package.json
- examples/website/mesh/package.json
- examples/website/point-cloud/package.json
- examples/website/radio/package.json
- examples/website/safegraph/package.json
- examples/website/scenegraph/package.json
- modules/carto/package.json
- modules/core/package.json
- modules/geo-layers/package.json
- modules/jupyter-widget/package.json
- modules/layers/package.json
- modules/mesh-layers/package.json
- package.json
- yarn.lock
Bump loaders.gl to 2.3.13 to fix MVT binary with empty tiles: https://github.com/visgl/deck.gl/issues/5534
> Bump loaders.gl to 2.3.13

- modules/core/src/lib/deck.js
For #5398
- _onWebGLContextLost callbacks passed to Luma and registered 
- deck.onError is triggered by _onWebGLContextLost
> [feat] WebGL context lost handling > pass to listeners of onError

- docs/api-reference/aggregation-layers/heatmap-layer.md
Link is currently incorrectly rendered because of a missing closing `)`
> Fix link in heatmap-layer.md

- modules/layers/src/bitmap-layer/bitmap-layer.js
For #5576 
The `BitmapLayer` does not have a `pickingColors`/`instancePickingColors` attribute, which is required by the base `Layer` multi-picking logic.
- Skip drawing in multi-picking after the layer is picked
> Fix BitmapLayer crash during multi-depth picking

- bindings/pydeck/pydeck/io/html.py
- bindings/pydeck/setup.py
> pydeck: Change cell height and enable _repr_html_ in Colab

- docs/api-reference/extensions/path-style-extension.md
- examples/layer-browser/src/examples/core-layers.js
- modules/extensions/src/path-style/path-style.js
- modules/extensions/src/path-style/shaders.glsl.js
For #
- There is a use case to pick dash line either interacts with gap or the solid strokes
- PathStyleExtension: add an option `allowPickGap`, which allows picking on the gap of dash lines
> PathStyleExtension: allow picking gaps between solid lines

- modules/geo-layers/src/terrain-layer/terrain-layer.js
For #5686
- Update props that `TerrainLayer` passes to `TileLayer`. The `TileLayer`'s `defaultProps` are seeded as the `TerrainLayer`'s `defaultProps`, so this updates to include all `TileLayer` props.
> Update TerrainLayer props passed to TileLayer

- modules/geo-layers/src/tile-layer/tile-layer.js
After #5720, tiles do not render after they are loaded until the next viewport change.
This is technically a different bug, but was exposed by the above change. `TileLayer` calling `tileset.setOptions(props)` breaks the binding with the layer callbacks.
- Cherry-pick the props to pass to `Tileset2D` as options
> Fix TileLayer rerender after props change

- modules/layers/src/geojson-layer/geojson-layer-props.js
Supporting PR for implementing triangulation of polygons for MVTLoader in loaders.gl
[RFC](https://github.com/visgl/deck.gl/pull/5685)
- `triangulate` Boolean prop is added to `MVTLayer`
> MVT triangulation

- modules/core/src/lib/layer.js
For #5728
- properly calculate cacheSize in Layer::calculateInstancePickingColors()
> fix for picking buffer generation with custom buffer over alloc

- docs/api-reference/core/layer.md
- modules/core/src/lib/deck-picker.js
- modules/core/src/lib/deck-renderer.js
- modules/core/src/lib/layer-manager.js
- modules/core/src/lib/layer.js
- modules/core/src/lifecycle/component-state.js
- modules/core/src/passes/layers-pass.js
- modules/geo-layers/src/terrain-layer/terrain-layer.js
- modules/geo-layers/src/tile-layer/utils.js
- test/modules/geo-layers/tile-layer/utils.spec.js
Revamps the error handling system
- Simplify the propagation of the `onError` prop across core classes. Consolidate lifecycle error handling to use layer context.
- Add an `onError` callback to base `Layer` props. Related but not limited to use case discussed in #5647 
> Add onError to Layer props

- docs/upgrade-guide.md
- docs/whats-new.md
- modules/geo-layers/src/mvt-layer/mvt-layer.js
In v8.5 we would like to change the default of the `binary` prop in the `MVTLayer` to `true` as this code path is much faster and offers a smoother experience to the user
> Set default of MVTLayer binary to true

- modules/core/src/controllers/controller.js
- modules/core/src/controllers/first-person-controller.js
- modules/core/src/controllers/globe-controller.js
- modules/core/src/controllers/map-controller.js
- modules/core/src/controllers/orbit-controller.js
- modules/core/src/controllers/orthographic-controller.js
- modules/core/src/transitions/linear-interpolator.js
- modules/core/src/viewports/globe-viewport.js
- modules/core/src/viewports/viewport.js
- modules/core/src/viewports/web-mercator-viewport.js
- modules/core/src/views/orthographic-view.js
- Consolidate transition props logic across controller classes
- Add `viewport.panByPosition` interface
- Fix OrhographicController zoom drifting #5779
> Refactor linear transition in controllers

- modules/core/src/lib/composite-layer.js
- modules/core/src/passes/layers-pass.js
- modules/geo-layers/src/tile-layer/tile-layer.js
- test/modules/geo-layers/tile-layer/tile-layer.spec.js
For #5818
This allows a composite layer to control sub layer visibility based on viewport.
In the TileLayer use case, this improves performance by avoiding the generation of new layers when tile visibilities change.
- Add `CompositeLayer.filterSubLayer` method (see inline JSDoc)
- `TileLayer` sub layers visibility handling
> Allow CompositeLayer to filter sub layers during redraw

- modules/geo-layers/src/mvt-layer/mvt-layer.js
- modules/geo-layers/src/terrain-layer/terrain-layer.js
- modules/geo-layers/src/tile-layer/tile-layer.js
Implements https://github.com/visgl/deck.gl/issues/5808
I've tested that the extra header is present in the requests (note that this causes CORS errors in your specific example from terrarium @Pessimistress, but this is a server side problem, the OSM tiles work fine). Additionally, I've verified that when moving the map quickly tile requests do get aborted.
Where possible I rewrote the code to use the Layers `fetch` prop, but decided that it wasn't worth it for the case of loading terrain data as:
- it would be challenging to implement
- the loading of terrain tiles is closely coupled to the layer anyway
- having the `fetch` prop be invoked for two different types of request (imagery & terrain) would be error prone
> Pass through loadOptions and AbortSignal to MVTLayer & TerrainLayer

- bindings/pydeck/pydeck/widget/widget.py
This is just a proposed typo fix
I just renamed a variable from `debouce_seconds` to `debounce_seconds`
> fixed typo in debounce_seconds name

- docs/api-reference/core/layer.md
- modules/core/src/lib/composite-layer.js
- modules/core/src/lib/layer.js
- modules/geo-layers/src/mvt-layer/mvt-layer.js
- modules/geo-layers/src/terrain-layer/terrain-layer.js
- modules/geo-layers/src/tile-layer/tile-layer.js
For #5808
- Call `fetch` with consistent arguments in MVTLayer and TerrainLayer
- Remove TileLayer override of `fetch`, merge with base layer default
- CompositeLayer forwards `fetch` via `getSubLayerProps`
> Consolidate and document fetch prop

- docs/api-reference/core/deck.md
Documentation style has been taken from https://github.com/visgl/deck.gl/blob/master/docs/api-reference/core/deckgl.md#container-domelement--string-optional
Code supports it here: https://github.com/visgl/deck.gl/blob/c5ff0470f6ae18a5d3b838406c7e8647628a58d8/modules/core/src/lib/deck.js#L415-L436
> Fix type documentation for canvas in Deck

- examples/get-started/pure-js/google-maps/app.js
- examples/get-started/scripting/google-maps/index.html
Avoid deprecation warning in Google Maps example by using latest library (3.45) https://developers.google.com/maps/documentation/javascript/versions
> Increase Google maps version from 3.39 to 3.45

- modules/layers/src/geojson-layer/geojson-layer-props.js
- test/modules/geo-layers/mvt-layer.spec.js
Fix for https://github.com/visgl/deck.gl/issues/5851
This change does fix the issue with the radio example, but I hope I haven't missed something about how the data is then uploaded to the GPU or used elsewhere. In other words, I hope that I haven't fixed an apparent off-by-one error and inadvertently created another elsewhere
> Correct data.length for geojson-layer-props polygons

- examples/layer-browser/package.json
- examples/playground/package.json
- examples/website/3d-tiles/package.json
- examples/website/globe/package.json
- examples/website/i3s/package.json
- examples/website/mesh/package.json
- examples/website/point-cloud/package.json
- examples/website/radio/package.json
- examples/website/safegraph/package.json
- examples/website/scenegraph/package.json
- modules/carto/package.json
- modules/core/package.json
- modules/geo-layers/package.json
- modules/jupyter-widget/package.json
- modules/layers/package.json
- modules/mesh-layers/package.json
- package.json
- website/package.json
- yarn.lock
To test latest version of @loaders.gl before new release
- All loaders.gl dependencies were updated to v3.0.0-alpha.21
> Bump @loaders.gl to 3.0.0-alpha.21

- docs/api-reference/layers/geojson-layer.md
- docs/api-reference/layers/text-layer.md
- docs/whats-new.md
- examples/website/tagmap/app.js
- examples/website/tagmap/tagmap-layer/tagmap-layer.js
- modules/layers/src/geojson-layer/sub-layer-map.js
- modules/layers/src/text-layer/text-layer.js
- modules/layers/src/text-layer/utils.js
- test/modules/layers/text-layer/text-layer.spec.js
For #5815 
Make it possible to render text labels in MVTLayer without knowing the characters used.
- TextLayer supports `characterSet: 'auto'`
- GeoJsonLayer exposes `textCharacterSet`
- Tests
- Update TextLayer example to use new feature
- What's new
> TextLayer supports characterSet:auto

- modules/carto/src/layers/carto-layer.js
Since we added support pointType prop to allow changing point rendering in GeoJsonLayer  at #5835, CARTO module was throwing (for table and query maptypes):
```
WebGL: INVALID_VALUE: uniform1fv: invalid srcOffset
```
https://codepen.io/alasarr/pen/MWpxGxY
It happens because CartoLayer tries to merge with sublayer `defaultProps`, however it's not required to do it to inherit sublayer default props.
> Fix: CARTO module WebGL invalid value for table

- modules/geo-layers/package.json
- modules/geo-layers/src/tile-3d-layer/tile-3d-layer.js
- test/modules/geo-layers/tile-3d-layer/tile-3d-layer.spec.js
- yarn.lock
We updated `Tileset3D` options structure. This update is to meet these changes.
- Fix `Tileset3D` options structure;
- Fix coordinates in test. `throttleRequests` is true by default now and `RequestScheduler` cuts tiles outside of the frustum.
This PR is prior to bumping loaders.gl version to latest beta.
> tile-3d: update with new loaders version

- modules/geo-layers/src/mvt-layer/mvt-layer.js
Revert hack from #5507 and use the new feature from https://github.com/visgl/loaders.gl/pull/1584
- Use fallback `mimeType` to ensure that MVTLoader is selected
> MVTLayer use all loaders

- examples/layer-browser/package.json
- examples/playground/package.json
- examples/website/3d-tiles/package.json
- examples/website/globe/package.json
- examples/website/i3s/package.json
- examples/website/mesh/package.json
- examples/website/point-cloud/package.json
- examples/website/radio/package.json
- examples/website/safegraph/package.json
- examples/website/scenegraph/package.json
- modules/carto/package.json
- modules/core/package.json
- modules/geo-layers/package.json
- modules/jupyter-widget/package.json
- modules/layers/package.json
- modules/mesh-layers/package.json
- package.json
- test/apps/arcgis-i3s/package.json
- website/package.json
- yarn.lock
I released 3.0.0-beta.6 with https://github.com/visgl/loaders.gl/pull/1597 .
> Bump loaders to 3.0.0-beta.6

- docs/api-reference/carto/carto-layer.md
- docs/api-reference/carto/overview.md
- docs/upgrade-guide.md
- docs/whats-new.md
- modules/carto/src/api/maps-v3-client.js
Update docs to use CARTO 3 instead of CARTO Cloud Native
> Update docs: Rename to CARTO 3

- docs/api-reference/geo-layers/mvt-layer.md
- docs/api-reference/geo-layers/terrain-layer.md
- docs/developer-guide/loading-data.md
- docs/upgrade-guide.md
- modules/geo-layers/src/mvt-layer/mvt-layer.js
- modules/geo-layers/src/terrain-layer/terrain-layer.js
- test/modules/geo-layers/mvt-layer.spec.js
- test/modules/geo-layers/terrain-layer.spec.js
For #5263
Note that while this is technically a breaking change, the default behavior does not change for most users. The following use cases are affected:
- Using these layers in an environment that does not support WebWorker (e.g. node tests)
- Debugging the loaders by disabling worker
- MVTLayer default `loaders` prop
- TerrainLayer default `loaders` prop
- TerrainLayer removes `workerUrl` prop and merges `loadOptions.terrain` instead
- Tests
> MVTLayer and TerrainLayer switch to use worker-only loaders

- bindings/pydeck/pydeck/widget/widget.py
- modules/jupyter-widget/src/playground/create-deck.js
For https://github.com/visgl/deck.gl/discussions/5132
Add `on_drag_*` event handlers to pydeck
- Update Jupyter widget to support `on_drag_*` handlers
> pydeck: Add on_drag_start, on_drag, and on_drag_end handlers

- docs/upgrade-guide.md
- examples/website/point-cloud/app.js
- modules/core/src/controllers/orbit-controller.js
- modules/core/src/views/orbit-view.js
- test/modules/core/views/view.spec.js
- test/render/test-cases/simple-mesh-layer.js
For #5948 
`orbitAxis` has always been documented as a `OrbitView` prop, but in practice it could be set in the view state as well. This lead to various inconsistency bugs when we handle view state across viewport, controller and transition interpolators. 
This PR drops the default value from `OrbitController` and `OrbitViewport` for clarity. `orbitAxis` is now set once and for all in the `OrbitView` constructor.
- Set `orbitAxis` fall back in `OrbitView` constructor
- Fix point cloud example
> Enforce OrbitView orbitAxis prop

- modules/geo-layers/src/terrain-layer/terrain-layer.js
#5979 bumped our use of loaders.gl to 3.0.2. That release includes support for terrain skirting https://github.com/visgl/loaders.gl/pull/1662, which we can now enable in the TerrainLayer. Users can enable `skirtHeight` through the user of `loadOptions.terrain.skirtHeight`, but setting a default will make it easier to use for users who don't know the loaders.gl API as well. Setting a skirt height of 2 * the max error of the mesh should cover any seams (assuming the source elevation model is continuous).
- Set a default `skirtHeight` when using the TerrainLayer in tiled mode.
> Provide default skirt height for tiled TerrainLayer

- modules/core/src/lib/deck.js
For #5987
- Do not call `onError` if gl context is lost after `Deck.finalize`
> Avoid onError call if context is lost after finalization

- docs/api-reference/core/web-mercator-viewport.md
- examples/webpack.config.local.js
- modules/core/src/viewports/web-mercator-viewport.js
- test/modules/core/viewports/web-mercator-viewport.spec.js
Implementation of https://github.com/visgl/deck.gl/issues/5929
> WebMercatorViewport support external projectionMatrix

- docs/api-reference/geo-layers/mvt-layer.md
- docs/upgrade-guide.md
- modules/geo-layers/src/mvt-layer/mvt-layer.js
Set MVTLayer binary to `false`. Related to https://github.com/visgl/deck.gl/issues/6006
> fix: MVTLayer set binary to false by default

- modules/core/src/lib/deck.js
- modules/react/src/deckgl.js
For #5999
- Deck should not overwrite the id of an externally-provided canvas
- The React wrapper div is now assigned id `${props.id}-wrapper`. If `props.id` is not specified, the id is default to `deckgl-wrapper`, consistent with the previous behavior.
> Allow user to control React wrapper id

- docs/api-reference/layers/text-layer.md
- modules/layers/src/text-layer/text-background-layer/text-background-layer-vertex.glsl.js
- modules/layers/src/text-layer/text-background-layer/text-background-layer.js
- modules/layers/src/text-layer/text-layer.js
For https://github.com/visgl/deck.gl/issues/4579#issuecomment-786731076
This is a nice to have feature with very low impact.
- TextLayer supports both vec2 and vec4 `backgroundPadding`
- Docs
> TextLayer supports backgroundPadding as vec4

- modules/geo-layers/src/mvt-layer/mvt-layer.js
- modules/geo-layers/src/tile-layer/tile-layer.js
Changes on `minZoom` or `maxZoom` props didn't work at MVTLayer. Reported at https://github.com/visgl/deck.gl/issues/6023
> Fix: MVT update min/maXZoom props

- modules/geo-layers/src/mvt-layer/mvt-layer.js
- modules/test-utils/src/index.js
- modules/test-utils/src/lifecycle-test.js
- test/modules/core/lib/picking.spec.js
The MVTLayer has incorrect picking behavior if two features in the source data share the same `id`, but have a different `layerName`
- `MVTLayer.getHighlightedObjectIndex()` checks that the hovered feature has the correct `layerName` as well as the correct `id`. This PR is only for the non-binary codepath.
- Add `MVTLayer` test cases to the `picking.spec.js` tests
- Test picking in `MVTLayer` for two features with matching `id`, but different `layerName`
> Check for correct matching layerName when highlighting in MVTLayer

- modules/aggregation-layers/package.json
- modules/carto/package.json
- modules/core/package.json
- modules/geo-layers/package.json
- modules/geo-layers/src/tile-layer/tile-2d-traversal.js
- modules/layers/package.json
- test/modules/geo-layers/tile-layer/utils.spec.js
- yarn.lock
For #5860 
- Upgrade math.gl to 3.5.4 (bug fixes for bounding volumes)
- Estimate the bounding volume of tiles better
> Improve tile traversal in GlobeView

- modules/geo-layers/src/mvt-layer/find-index-binary.js
- modules/geo-layers/src/mvt-layer/mvt-layer.js
- modules/layers/src/geojson-layer/geojson-binary.js
- modules/layers/src/index.js
- test/apps/mapbox-tile/app.js
- test/apps/mapbox-tile/webpack.config.js
- test/modules/core/lib/picking.spec.js
- test/modules/geo-layers/mvt-layer.spec.js
- test/modules/layers/geojson-binary.spec.js
For #6006
- Fix incorrect usage of feature id (should return global feature id)
- Move `findIndexBinary` from GeoJsonLayer to MVTLayer (logic does not apply to generic GeoJSON)
- Handle default `uniqueIdProperty`
- Handle filter by layer name
- Update MVT test app
- Unit tests
> Fix MVTLayer autoHighlight with binary data

- docs/api-reference/core/orthographic-controller.md
- docs/api-reference/core/orthographic-view.md
- modules/core/src/controllers/orbit-controller.js
- modules/core/src/controllers/orthographic-controller.js
- modules/core/src/views/orthographic-view.js
- test/modules/core/controllers/controllers.spec.js
For the charting use case
- `OrthographicViewport` accepts `zoom` as either a number (uniform zoom) or an array (independent zoom)
- `OrthographicController` new option `zoomAxis`
- Test
> OrthographicView supports independent x/y zoom levels

- modules/google-maps/src/google-maps-overlay.js
Came across a regression with the Google library (which is updating weekly) where the rendering completely broke down. This fix makes sure the GL state is correct so that the rendering in Google Maps works
> Bug fixes in google overlay

- modules/geo-layers/src/tile-3d-layer/tile-3d-layer.js
- modules/geo-layers/src/tile-layer/tile-layer.js
For #6122
There are various issues in TileLayer/Tile3DLayer's override of sublayer `visible` prop:
- `Tile3DLayer` is not forwarding its `visible` prop to cached sub layers correctly
- `TileLayer` does not hide sub layers when toggled off if the `visible` prop is set by `renderSubLayers` explicitly
- Use `filterSubLayer` to hide all tiles if `visible` is false
> Fix TileLayer and Tile3DLayer visiblility

- modules/core/src/lib/attribute/attribute-manager.js
- test/modules/core/lib/attribute/attribute-manager.spec.js
Fixes #6129 (see [discussion](https://github.com/visgl/deck.gl/discussions/6128) as well).
- Make sure default values of added attributes match docs/luma.gl constants
> Fix Default Values in `AttributeManager` `add` method

- modules/carto/src/api/maps-v3-client.js
It returns API error at the exception message. I've also added a bad parameter message when 400 is received
> CARTO: include API error at the exception message

- docs/api-reference/carto/carto-layer.md
Prevent gatsby build from failing (https://github.com/visgl/deck.gl/runs/3454234729). As no other doc mentions the the type of the object in an Array I just removed the annotation as it was causing gatsby to fail.
> Remove <String> from CartoLayer doc

- modules/geo-layers/src/tile-layer/tile-2d-traversal.js
For #6147
- Two additional reference points along the equator for bounding volume calculation the topmost tile.
> [GlobeView] Additional reference points for bounding volume calculation

- docs/api-reference/aggregation-layers/heatmap-layer.md
- modules/aggregation-layers/src/heatmap-layer/heatmap-layer.js
For #6157
- debounceTimeout prop for Heatmap layer to control debounce timeout by adjusting it based on dataset size and radius.
- weightsTextureSize prop for Heatmap to control performance of max-weight calculation, rendering quality, memory usage.
- HeatmapLayer::getShaders methods can be used to override weights transform shaders in extended layers.
- heatmap-related logic from updateState is moved to _updateHeatmapState method to be able to override it in an extended class.
> Heatmap - expose additional properties

- docs/api-reference/core/composite-layer.md
- modules/core/src/lib/composite-layer.js
For #6149
- Drop checking `_subLayerProps` exists or not in `shouldRenderSubLayer`
> Drop sublayers with no data even if the _subLayerProps prop contains

- CHANGELOG.md
I forgot to add the header to the changelog when I released 8.6.0-alpha.2
> Fix changelog 8.6.0-alpha.2

- modules/google-maps/src/google-maps-overlay.js
- modules/google-maps/src/utils.js
- test/modules/google-maps/google-maps-overlay.spec.js
https://github.com/visgl/deck.gl/issues/5980
We were seeing issues with the integration where the Google basemap didn't display due to deck.gl changing WebGL state when the Google library didn't expect it
- Disable rendering using the deck.gl animation loop to ensure we only modify GL state in the Google `onDraw` lifecycle method
- Workaround for incorrect view state (hopefully we can remove this in the future if Google resolve on their end)
- Support rendering to framebuffer when present (supports optimized render path for Google maps)
- No longer need to continuously render (due to framebuffer fix)
- Animated layers and other state changed correctly request rerender via Google maps
> Google overlay state synchronization

- modules/core/src/shaderlib/project/project.glsl.js
- modules/core/src/shaderlib/project/viewport-uniforms.js
For #6154
- More accurate projection of positions that are far away from the viewport center
> Improve shader projection in auto offset mode

- modules/core/src/lib/deck-renderer.js
- modules/mapbox/src/deck-utils.js
Following https://github.com/visgl/deck.gl/pull/6049, remove ad-hoc filtering logic in the mapbox module.
- Support `layerFilter` override in `DeckRenderer.renderLayers`
- Remove ad-hoc filtering logic in the mapbox module
> Use new layerFilter in MapboxLayer

- docs/api-reference/geo-layers/tile-layer.md
- modules/geo-layers/src/tile-layer/tile-2d-traversal.js
- modules/geo-layers/src/tile-layer/utils.js
- test/modules/geo-layers/tile-layer/utils.spec.js
For #6188
- Check tiles against `extent` in geospatial mode
- Clarify behavior in documentation
> TileLayer uses props.extent to cull tiles in geospatial mode

- modules/google-maps/src/utils.js
Fixes #6207, adding missing pickingRadius to click event handler in google maps
> Fix missing picking radius for onClick handlers

- modules/geo-layers/src/tile-layer/tile-layer.js
For #6205 
- Use the latest layer instance
> Fix TileLayer getTileData not using the latest loadOptions

- modules/core/src/lifecycle/component-state.js
- test/modules/core/lib/layer-manager.spec.js
For #6192
- Call `freezeAsyncOldProps` when an async prop is set synchronously
- Add tests to capture the issue
> Fix diffProps when an async prop is set synchronously

- modules/aggregation-layers/src/heatmap-layer/heatmap-layer.js
For #6221
When data changes, we cancel the denounced weight map update and rerender immediately with outdated bounds.
- force update bounds if data is changed
> Fix Heatmap data update

- modules/core/src/lib/attribute/attribute-manager.js
- modules/core/src/lib/attribute/attribute.js
- test/modules/core/lib/attribute/attribute-manager.spec.js
- test/modules/core/lib/attribute/attribute.spec.js
For #6211
- Skip allocation if `attribute.constant` is `true`
- Unit tests
> Fix excessive allocation for constant attributes

- docs/api-reference/geo-layers/tile-layer.md
- modules/geo-layers/src/mvt-layer/mvt-layer.js
- modules/geo-layers/src/tile-layer/tile-2d-header.js
- modules/geo-layers/src/tile-layer/tile-layer.js
- modules/geo-layers/src/tile-layer/tileset-2d.js
- test/modules/core/lib/picking.spec.js
- test/modules/geo-layers/mvt-layer.spec.js
- test/modules/geo-layers/tile-layer/tile-2d-header.spec.js
- test/modules/geo-layers/tile-layer/tile-layer.spec.js
- test/modules/geo-layers/tile-layer/tileset-2d.spec.js
Fixes #6179
- Add a `reload` method for `Tileset2D` to be called on updates by `updateTriggers` instead of creating a new tileset
> TileLayer retains cache on data change

- README.md
- docs/api-reference/geo-layers/h3-hexagon-layer.md
- docs/upgrade-guide.md
- modules/geo-layers/src/h3-layers/h3-hexagon-layer.js
For #6238
- Update highPrecision prop to expect 'auto' | true | false values. Default is now 'auto'. (Breaking change)
- The h3 data is fully analyzed only for highPrecision: auto mode.
> H3HexagonLayer: force low precision; early exit for data analysis loop

- modules/aggregation-layers/src/hexagon-layer/hexagon-layer.js
- modules/layers/src/column-layer/column-layer-vertex.glsl.js
- modules/layers/src/column-layer/column-layer.js
- modules/layers/src/column-layer/grid-cell-layer.js
For #6181 
- Add `radiusUnits` to `ColumnLayer`
- `HexagonLayer` uses common radius with d3-hexbin, removes rerenders on viewport change
> Update HexagonLayer to use the new unit system

- modules/carto/src/api/index.js
- modules/carto/src/api/maps-api-common.js
- modules/carto/src/api/maps-client.js
- modules/carto/src/api/maps-v3-client.js
- modules/carto/src/config.js
- modules/carto/src/index.js
- test/modules/carto/api/maps-api-client.spec.js
For https://github.com/visgl/deck.gl/issues/6230
- Add tests to capture case where CARTO is initialized without `setDefaultCredentials` (repro for bug)
- Modify `getData` to only use default credentials if they have been defined for correct API version
Source of bug was fact that V1 & V2 API uses a format string for the `mapsUrl` so it is by default not null. Sanity checking we have the right API version in the default credentials is good anyway and removes the source of this bug
> CARTO: fix layer credentials overwrite

- CHANGELOG.md
Fix changelog for v8.7.0-alpha.1. By mistake, I set it to `v8.7.0-alpha.0` instead of `v8.7.0-alpha.1`
> Fix changelog for v8.7.0-alpha.1

- modules/carto/src/api/maps-v3-client.js
- modules/carto/src/api/parseMap.js
- modules/carto/src/config.js
- test/apps/carto-map/app.js
- test/modules/carto/api/maps-api-client.spec.js
- test/modules/carto/carto-bqtiler-layer.spec.js
- test/modules/carto/carto-layer.spec.js
- test/modules/carto/carto-sql-layer.spec.js
- test/modules/carto/config.spec.js
- test/modules/carto/mock-fetch.js
For https://github.com/visgl/deck.gl/issues/6375
- Switch to V3 API by default
- Simplify `setDefaultCredentials`
- Update tests
- Update `fetchMap` function to use `cartoMapId` and `credentials` options
> CARTO default to v3 API

- modules/core/src/shaderlib/project/viewport-uniforms.js
For #6350
While it's unclear to me how the math.gl dependency does not get resolved correctly for the reporting users, it may potentially crash in case the user provides a custom `projectionMatrix` that is not a Matrix4 instance:
https://github.com/visgl/deck.gl/blob/efc46e015dbf74520db3011b2c575f5e9aff4521/modules/core/src/viewports/viewport.js#L402-L404
- remove Matrix4 dependency from project module `getUniforms`
> Remove Matrix4 dependency from project module getUniforms

- modules/geo-layers/src/mesh-layer/mesh-layer-vertex.glsl.js
- modules/geo-layers/src/mesh-layer/mesh-layer.js
For #6467
- don't create constant attribute `uvRegions`;
- if `uvRegions` regions attribute is not presented, use UV0s as is.
The  changes were checked as fork in loader.gl repository: https://github.com/visgl/loaders.gl/pull/1935
> fix(geo-layers): _MeshLayer & repeating textures

- modules/core/src/shaderlib/project/viewport-uniforms.js
- test/modules/core/shaderlib/project/viewport-uniforms.spec.js
For #6480
- Avoid mutating `coordinateOrigin` when generating uniforms
- Unit test
> Avoid mutating coordinateOrigin

- modules/carto/src/layers/carto-dynamic-tile-layer.js
- modules/geo-layers/src/index.ts
CARTO module uses getURLFromTemplate and this function can be useful for other modules too. CARTO module has a bug at dynamic tile layer when we try to import  it works in local but not in the bundle because getURLFromTemplate is not exported
> Export getURLFromTemplate at geo-layers

- modules/core/src/passes/layers-pass.js
- test/modules/core/passes/layers-pass.spec.js
For https://github.com/visgl/deck.gl/issues/6552
When passing a `Framebuffer` as a `target` the GLViewport calculated assumed the width and height to be equal to the GL canvas
- When a custom target is passed to the layers pass, use its width&height rather than that of the canvas
- When the `moduleParameters` specify a pixel ratio, respect this when calculating the GL viewport
> Correctly calculate GLViewport with Framebuffer

- modules/carto/src/api/layer-map.js
- test/modules/carto/data/visState.json
Highlighting doesn't work in layers returned by fetchMap Carto module method when these layers are MVT layers. This happens because these layers don't have uniqueIdProperty. To replicate the same behavior as in Builder we are assuming that tilesets returned by the maps API normally have a geoid
- uniqueIdProperty added to MVT layers returned by fetchMap Carto module
> Fix Highlighting in Carto module

- .eslintrc.js
- modules/core/src/effects/mask/mask-effect.js
- modules/core/src/effects/mask/utils.js
- modules/core/src/passes/layers-pass.ts
- modules/core/src/passes/mask-pass.ts
- modules/extensions/src/mask/mask.js
- modules/extensions/src/mask/shader-module.js
- test/apps/mask-orthographic/app.js
- test/apps/mask/app.js
- test/modules/core/effects/mask-effect.spec.js
- test/modules/core/passes/mask-pass.spec.js
- test/modules/extensions/mask.spec.js
- test/render/test-cases/effects.js
For #4161 
Support up to 4 mask layers. `maskId` is now required to enable masking. If `maskId` is not found, it is treated as if `maskEnabled: false`.
@felixpalmer Do we still need `maskEnabled` in this case?
- MaskEffect
- MaskExtension
- Test app
- Unit tests
> Support multiple masks

- modules/mapbox/src/deck-utils.js
- test/modules/mapbox/mapbox-layer.spec.js
For #6584
- MapboxLayer's viewport gets `repeat` dynamically
> MapboxLayer only repeats if the base map renders multiple copies

- modules/core/src/lib/deck-picker.js
- modules/core/src/lib/picking/pick-info.js
- modules/core/src/passes/layers-pass.ts
- modules/core/src/shaderlib/picking/picking.js
For #6587
The interpolation-based `targetZ` approach does not have acceptable precision in OrbitView.
- Encode clipspace z in depth picking instead of commonspace z
> Fix depth picking accuracy

- modules/core/src/views/orthographic-view.js
- test/modules/core/views/view.spec.js
The `target` position is not projected correctly when using independent zooms.
- OrthographicViewport passes custom `distanceScale` to base constructor
- Unit tests
> Fix OrthographicView projection when using independent scales

- modules/aggregation-layers/package.json
- modules/carto/package.json
- modules/core/package.json
- modules/geo-layers/package.json
- modules/layers/package.json
- yarn.lock
Fixes crash in MaskEffect if the mask bounds are beyond the Web Mercator boundaries
- Update dependencies
> Bump math.gl to 3.5.7

- modules/carto/src/api/layer-map.js
- modules/carto/src/api/parseMap.js
- test/modules/carto/api/layer-map.spec.js
H3 hexagon layers are not shown when you load a map using the fechMap Carto module method. It's because we are assuming that the hexagon column is always 'h3'. Instead, we should read this column from the map config. To get this, I've replaced the `LAYER_MAP` constant with a function that receives the layer type and the config as params. This also allows us to read more configuration parameters if would be necessary.
- Replaced the `LAYER_MAP` constant with a function that receives the layer type and the config as params
> CARTO fetchMap: Fix h3 hexagon layers are not shown

- modules/carto/src/layers/carto-dynamic-tile-layer.js
If you try to use an extension with the CartoDynamicTileLayer it doesn't work because the CartoDynamicTileLayer is overwriting the `props.extensions`
- Include  extensions sent in properties in the CartoDynamicTileLayer
> CARTO module: Fix extensions don't work with CartoDynamicTileLayer

- docs/api-reference/core/layer.md
- modules/core/src/lib/layer-props.ts
- modules/core/src/lib/layer.js
For #6630 
The stated behavior is that `highlightedObjectIndex` overrides `autoHighlight`. However, we use `Number.isFinite` to check if `highlightedObjectIndex` is specified, while the default value is `-1`.
https://github.com/visgl/deck.gl/blob/ef64ce181a76c13ba16d3c021f776063a50a47e9/modules/core/src/lib/layer.js#L934-L938
This PR does not change this overriding order, but makes sure that no overrides happen if `highlightedObjectIndex` is unspecified.
- `highlightedObjectIndex` default to `null`
> Change highlightedObjectIndex default to null

- modules/carto/src/layers/carto-dynamic-tile-layer.js
- modules/carto/src/layers/carto-layer.js
- yarn.lock
Simplify how format tiles logic works, we trust now on the parameter returned by the backend instead of apply a complex logic here.
> CARTO: Simplify format tiles logic

- modules/carto/src/api/layer-map.js
- modules/carto/src/api/parseMap.js
- modules/carto/src/layers/carto-dynamic-tile-layer.js
- test/modules/carto/api/parseMap.spec.js
- test/modules/carto/data/visState.json
With this PR the `fetchMap` method support tile layers in geojson and binary format
- The fetchMap will load a CartoDynamicTileLayer if the tile format is not MVT
> CARTO fetchMap: Support tiles in different formats 

- modules/carto/src/api/layer-map.js
- modules/carto/src/api/maps-v3-client.js
- modules/carto/src/layers/carto-dynamic-tile-layer.js
- modules/carto/src/layers/carto-layer.js
- test/modules/carto/carto-layer.spec.js
Some data in the CDN is cached and it has not the `formatTiles` parameter, we're setting the default to MVT to guarantee compatibility with public maps.
It cannot be done by purging CDN because some customer could have it at the local browser cache.
> Default format tiles to MVT to guarantee compatilibity with data cached in CDN

- modules/carto/src/layers/carto-tile-layer.js
This PR set `formatTiles` to `binary` as default for `CartoTileLayer`
> CARTO: set default formatTiles to binary at CartoTileLayer

- modules/geo-layers/src/tile-layer/utils.js
For #6607 
- Use math.gl 3.0 API
> Fix math.gl deprecation warning

- modules/mapbox/src/deck-utils.js
For #6556
When an external Deck instance is used to create a MapboxLayer, it could be one of two cases:
1. Deck driving Mapbox (React use case)
2. Mapbox driving Deck (pure JS, existing deck use case)
The current code always treat the external instance as if it's case 1.
- Deduce use case from deck's initialization props
> [mapbox] Fix event handling when using external deck

- modules/carto/src/api/maps-v3-client.ts
- test/modules/carto/api/maps-api-client.spec.js
CARTO `fetchMap` was not supporting a custom `geoColumn` for datasets.
- Pass through `geoColumn` and `columns` from maps API
- Test
> Add support for geoColumn & columns to fetchMap

- docs/api-reference/core/deck.md
- docs/api-reference/core/layer.md
- docs/api-reference/layers/bitmap-layer.md
- docs/api-reference/layers/icon-layer.md
- docs/api-reference/mesh-layers/scenegraph-layer.md
- docs/api-reference/mesh-layers/simple-mesh-layer.md
- docs/developer-guide/custom-layers/layer-extensions.md
- docs/developer-guide/custom-layers/picking.md
- docs/developer-guide/custom-layers/prop-types.md
- docs/developer-guide/tips-and-tricks.md
Follow up of #6681
Per discussion with @ibgreen, given that luma.gl site is prioritizing v9 preview, deck.gl docs will point luma.gl links to the current release branch on GitHub.
> chore(docs): Update luma.gl docs links

- modules/core/src/lifecycle/constants.ts
This was a typo introduced by https://github.com/visgl/deck.gl/pull/6454
The library itself is not affected, since all references of the symbol are directly imported from this file. However, the production website's "Edit on Codepen" feature crashes due to the symbol id `asyncPropResolved` being hard coded.
- Fix symbol id.
> Fix website "Edit on Codepen" link

- modules/carto/src/api/maps-v3-client.ts
- modules/carto/src/layers/carto-layer.js
- modules/carto/src/layers/carto-tile-layer.js
- test/apps/carto-dynamic-tile/app.js
For https://github.com/visgl/deck.gl/issues/6508
Tiles were being requested in binary format even when `formatTiles: 'mvt'`
- Append formatTiles to TileJSON URL when requested
- Better `shouldUpdateData` check
- Improve test app to allow easy selection of dataset & tile format
> CARTO: Append formatTiles to TileJSON URL when requested

- docs/api-reference/mapbox/mapbox-layer.md
- docs/api-reference/mapbox/mapbox-overlay.md
- examples/get-started/pure-js/mapbox/app.js
- examples/get-started/pure-js/mapbox/index.html
- modules/mapbox/package.json
- modules/mapbox/src/deck-utils.js
- modules/mapbox/src/index.ts
- modules/mapbox/src/mapbox-overlay.js
- modules/mapbox/src/mapbox-overlay.ts
- test/modules/mapbox/mapbox-layer.spec.js
- yarn.lock
This enables deck.gl to be used with react-map-gl v7.0 along with native controls. It also greatly simplifies the pure-js use case, whereas before the users were required to implement camera synchronization manually.
The `MapboxOverlay` implements Mapbox's `IControl` interface. When used, a deck canvas is inserted into Mapbox's controls container, and Mapbox handles all the user interaction. This works almost identically to the `GoogleMapsOverlay` class.
- add MapboxOverlay
- get-started example
- docs
> [mapbox] add MapboxOverlay

- bindings/pydeck/pyproject.toml
The latest version of `setuptools` broke our CI, see: https://github.com/visgl/deck.gl/runs/5687413943?check_suite_focus=true, but it turns out our `pyproject.toml` file is invalid anyways. The `requires` array should be under the `[build-system]` header.
- Update `pyproject.toml` in line with [PEP 621](https://peps.python.org/pep-0621/)
> Fix Python CI

- modules/aggregation-layers/src/cpu-grid-layer/cpu-grid-layer.js
- modules/aggregation-layers/src/hexagon-layer/hexagon-layer.js
For #6813
- Use double precision for positions in `CPUGridLayer` and `HexagonLayer`
> Fix position precision in CPU aggregation layers

- modules/core/src/passes/layers-pass.ts
- test/modules/core/lib/layer.spec.js
For #6830
During uniform transition, we shadow `layer.props` with `internalState.propsInTransition` inside lifecycle calls (`_update` and `_drawLayer`. In `LayersPass`, module parameters are currently pre-calculated outside of these lifecycle methods, so they are not using the "real" props.
- Account for props in transition
- Unit tests
> Fix uniform transition for shader module props

- modules/geo-layers/src/tile-3d-layer/tile-3d-layer.js
In "@loaders.gl/tiles@3.2.0-alpha.2" new method was added for async traversal of the tileset. This method includes debounce logic to mitigate spamming from the view.
- Replace sync `Tileset3D.update` to async `Tileset3D.selectTiles` method in Tile3DLayer.
> feat(geo-layers): Tile3DLayers-async tileset traversal

- examples/get-started/react/google-maps/README.md
- examples/get-started/react/google-maps/app.js
- examples/get-started/react/google-maps/package.json
- examples/get-started/react/google-maps/webpack.config.js
I saw that react and google maps did not have an example so I created one. I used [@googlemaps/react-wrapper](https://www.npmjs.com/package/@googlemaps/react-wrapper) which is made by google maps and therefore should be stable.
- Create the google-maps example for react.
- Update the docs with the new example
- [Base map doc](https://deck.gl/docs/get-started/using-with-map)
- [React doc](https://deck.gl/docs/get-started/using-with-react)
> React Google-maps example

- modules/geo-layers/src/tile-layer/utils.ts
- test/modules/geo-layers/tile-layer/utils.spec.js
For #6816 
`stringHash` can return negative numbers and crash the template selection.
- Force `stringHash` to return non-negative numbers
- Test case
> Fix crash in getURLFromTemplate

- modules/carto/src/layers/carto-layer.ts
- modules/core/src/index.ts
- modules/core/src/lib/composite-layer.ts
- modules/core/src/lib/layer-manager.ts
- modules/core/src/lib/layer-state.ts
- modules/core/src/lib/layer.ts
- modules/core/src/lifecycle/component-state.ts
- modules/core/src/lifecycle/component.ts
- modules/core/src/lifecycle/create-props.ts
- modules/core/src/shaderlib/project/project-functions.ts
- modules/core/src/types/layer-props.ts
- modules/geo-layers/src/mvt-layer/mvt-layer.js
- modules/geo-layers/src/tile-layer/tile-layer.ts
- modules/geo-layers/src/tile-layer/utils.ts
- modules/layers/src/scatterplot-layer/scatterplot-layer.ts
For #5589 
Continue discussion from https://github.com/visgl/deck.gl/pull/6803#discussion_r846417620
In this proposal, we no longer require the generic type `PropsT` to extend `LayerProps`. The type of `layer.props` is instead enforced with `PropsT & Required<LayerProps>`. This removes TypeScript's complaint that `PropsT` may override some of `LayerProps` fields.
See proof-of-concept in [this Playground snippet](https://www.typescriptlang.org/play?#code/C4TwDgpgBAMghiCAnACkg9mAzlAvFAbwCgpSpM4BjAS1AH4AuKAOwFcBbAI2QG4iBfIkQD0AKlFQAQnCzQANgmRRRwopQVYc8REgA8aTFgAqAPkIkyYDNiYHsRqADIoAJQgBHVtSQQAJru1kOywTITIoSnRmLGAkVkpgdCQACgA6dKtDWzgkYGo4OX1rYxMAbQBdAEpzcPDgAAtqLFTM7DwoAHlOACsIBNSZLGoAc2Zkgn4AGih0luLKi1JBRahhiGAOsCpaEGTKpjYuJWJash9gViRmKAamucNUihpQFcFl0EgoI2o5CEDUYrtE5kdjUZgALXQ6HYjBYHG4SD4yzE …
> Base Layer type signature

- modules/carto/src/layers/h3-tile-layer.js
- modules/carto/src/layers/h3-tileset-2d.js
- modules/carto/src/layers/quadkey-tile-layer.js
- Read out maxresolution from tilejson
- Limit data fetching by resolution not zoom level
- Improve `getTileIndices` for H3 when zoomed in
> CARTO: Cartolayer h3 maxresolution tile limit

- modules/mapbox/src/deck-utils.js
- test/modules/mapbox/mapbox-layer.spec.js
For #6894
Normally viewstates are normalized by deck.gl's controller. In the MapboxLayer use case, it is extracted from mapbox's methods. `map.getCenter()` could apparently return longitude that is out of range.
- Normalize longitude into `[-180, 180]`
> [mapbox] restrict longitude returned by map.getCenter()

- modules/core/src/lib/layer-state.ts
- modules/core/src/lib/layer.ts
- modules/core/src/lifecycle/component-state.ts
- modules/core/src/lifecycle/component.ts
My understanding of the Component/ComponentState inheritance hierarchy is that they are intended to extract the props resolution logic out of the Layer class. As we transition to TypeScript, the `Object.seal` call in the Component constructor forces the Component to reference many layer-specific types, which breaks that abstraction. This refactor moves the sealing into the Layer constructor instead.
> Remove layer-specific logic from Component class

- modules/core/src/lib/layer.ts
- modules/layers/src/geojson-layer/geojson-layer.ts
- modules/layers/src/scatterplot-layer/scatterplot-layer.ts
For #5589 
This proposal replaces many `@ts-ignore` usage with the `!` pattern. I think it is a better approach because:
- `@ts-ignore` ignores ALL TS rules, not just 2531. The decorated line practically loses all type checks, which could be valuable in catching other bugs. `!` only tells TS to ignore one variable's possible null state.
- It's just less verbose to write.
I purposefully do not use this pattern in the core module - where things are more subject to unexpected states - I believe that it's better to explicitly document any assumptions there. For the layer implementations, however, the lifecycle methods are only ever invoked by the layer manager, where `state`, `context` and `internalState` are always defined. The risk that anything will break by forcing TypeScript to ignore …
> [ts] Handle nullable layer members in layer code

- modules/geo-layers/src/geo-cell-layer/GeoCellLayer.ts
- modules/geo-layers/src/quadkey-layer/quadkey-layer.ts
- modules/layers/src/polygon-layer/polygon-layer.ts
Change List:
* fix wrong typing introduced in (#6822)  for in Polygon, GeoCell and Quadkey layers.
> [ts] Fix prop types of Polygon, GeoCell and Queadkey layers.

- modules/main/src/index.ts
- tsconfig.build.json
For https://github.com/visgl/deck.gl/issues/5589 & https://github.com/visgl/deck.gl/issues/6967
Change List:
* [ts] main: re-export recently added typings from:
* @deck.gl/core
* @deck.gl/layers
* @deck.gl/geo-layers
* @deck.gl/aggregation-layers
* Add @deck.gl "main" module to tsbuild.
> [ts] main: re-export recently added typings

- modules/core/src/effects/mask/mask-effect.ts
- modules/core/src/passes/layers-pass.ts
I have a map with 600+ `visible: false` tile layers which resulted in almost 20k of sublayers where the visibility is `false`.
The performance is very slow due to some checks in the deck lifecycle.
These changes have shown 20-40% performance improvements for each render frame.
- Prioritise checking visibility flag first
- Do not calculate render index if layer is not drawn
Edit: This is related to discussion #7021
> Improve performance for `visible: false` layers

- docs/api-reference/mapbox/mapbox-layer.md
- docs/api-reference/mapbox/mapbox-overlay.md
- docs/api-reference/mapbox/overview.md
- docs/developer-guide/base-maps/using-with-mapbox.md
For #6773
- Update mapbox module documentation. Most notably I am removing the old nested-dependency React usage pattern for `MapboxLayer`. The old pattern is hard to understand, causes many bugs and should be replaced by `MapboxOverlay` and `interleaved: true`.
- Update base map developer guide
> [mapbox] documentations

- docs/api-reference/core/deck.md
- modules/core/src/lib/deck-picker.ts
- modules/core/src/passes/layers-pass.ts
- modules/core/src/passes/pick-layers-pass.ts
- modules/geo-layers/src/tile-layer/tile-layer.ts
- modules/geo-layers/src/tile-layer/tileset-2d.ts
- modules/geo-layers/src/tile-layer/utils.ts
Proof of concept for discussion #6729
Picking on hover draws 20 tiles before this PR, and only 1 tile after.
- Add `cullRect` to layer filter context
- `TileLayer.filterSubLayer` culls sub layers based on the scissor rectangle
- Test
- Culling for generic layers?
> Cull TileLayer sub layers during picking

- modules/carto/src/layers/quadkey-tileset-2d.ts
- test/modules/carto/layers/quadkey-tileset-2d.spec.js
Followup to https://github.com/visgl/deck.gl/issues/6912
`Tileset2D` now relies on tiles providing their bbox, which was missing from the `QuadkeyTileset2D`
https://github.com/visgl/deck.gl/blob/master/modules/geo-layers/src/tile-layer/tileset-2d.ts#L244-L257
- Provide bbox in metadata
> QuadkeyTileset2D add missing metadata

- modules/geo-layers/src/tile-layer/tileset-2d.ts
For #7050
- Fix `Tileset2D.isTileVisible` culling in non-geo case
> Fix picking in non-geospatial TileLayer

- modules/layers/src/icon-layer/icon-layer.ts
Fix a bug where auto-packed IconLayer mutates the default `iconMapping` object.
- Ignore `iconMapping` value if auto packing
> Avoid mutating iconMapping value in autopacking

- modules/aggregation-layers/src/heatmap-layer/heatmap-layer.ts
For https://github.com/visgl/deck.gl/issues/6994
The render of the weights texture in the `HeatmapLayer` was giving incorrect results as the GL state had the incorrect `clearColor` (set on the shared context by Google Maps).
- When performing the `weightsTransform` explicitly set `clearColor`
> GoogleMapsOverlay: HeatmapLayer weightsTransform uses correct clearColor

- modules/google-maps/src/utils.ts
- test/modules/google-maps/google-maps-overlay.spec.js
For https://github.com/visgl/deck.gl/issues/6993
- Override `useDevicePixels` in `GoogleMapsOverlay` (as is done in `MapboxOverlay`)
- Tests
> GoogleMapsOverlay: Force useDevicePixels to true in interleaved mode

- docs/api-reference/core/deck.md
- modules/core/src/lib/deck.ts
- modules/google-maps/src/google-maps-overlay.ts
- modules/mapbox/src/deck-utils.ts
- modules/react/src/deckgl.ts
For https://github.com/visgl/deck.gl/issues/7080, fixes regression in https://github.com/visgl/deck.gl/pull/7049
- Add public `isLoaded` flag to deck class
- Use `isLoaded` rather than `onLoad` in React Deck component
> Add isInitialized flag to Deck class

- modules/core/src/lib/deck.ts
For #7081
This is a regression due to a change in `redraw` from
```js
const redrawReason = reason || this.needsRedraw({clearRedrawFlags: true});
```
to 
```js
const redrawReason = this.needsRedraw({clearRedrawFlags: true}) || reason;
```
The intention is to always clear the dirty flags when redraw is forced by the user. However, this changed the `reason` received by `_customRender`, which the ArcGIS integration is relying on.
- `redraw` always invoke `_customRender` with user-supplied reason, if any
> Fix arcgis integration

- modules/core/src/lifecycle/component-state.ts
See https://github.com/visgl/deck.gl/issues/6981
- If `props.fetch` is specified as null/undefined, async prop resolves to null
> Resolve async prop to null if fetch is undefined

- modules/carto/src/layers/h3-tile-layer.ts
- modules/carto/src/layers/h3-tileset-2d.ts
- test/apps/carto-dynamic-tile/app.js
- test/modules/carto/layers/h3-tileset-2d.spec.js
- Use `minZoom`&`maxZoom` props in addition to `min/maxresolution` when limiting H3 tile requests
> CARTO: Handle minZoom&maxZoom in H3TileLayer

- modules/layers/src/column-layer/column-layer-vertex.glsl.ts
- modules/layers/src/column-layer/column-layer.ts
For #6966
Before:
After:
- Shrink the fill area of `stroked: true`
> Fix z fighting in ColumnLayer when using 2d stroke

- modules/carto/src/style/color-bins-style.ts
- modules/carto/src/style/color-categories-style.ts
- modules/carto/src/style/color-continuous-style.ts
- modules/carto/src/style/utils.ts
- Improve `carto/style` typings for `color*` functions - improve typings and and use types from `@deck.gl/core`
> [ts] Improve carto/style typings.

- docs/get-started/using-with-react.md
For https://github.com/visgl/deck.gl/issues/7143
Change List
- Replace mapboxApiAccessToken with mapAccessToken in the getting started with react documentation.
> Replace mapboxApiAccessToken with mapAccessToken

- modules/core/src/lib/deck.ts
- modules/core/src/passes/layers-pass.ts
- modules/mapbox/src/deck-utils.ts
- modules/mapbox/src/resolve-layers.ts
- test/modules/mapbox/mapbox-gl-mock/map.js
- test/modules/mapbox/mapbox-gl-mock/style.js
For #7139
A hack was put in https://github.com/visgl/deck.gl/pull/6565 to manually override the starting index of layers. This number is incorrect when composite layers are stacked.
This PR properly resolves layer z when multiple draw passes are used in the same render cycle.
- Add `clearStack` option to `LayersPass.render`
- Remove `_offset` hack from `MapboxLayer`
> Fix MapboxLayer index resolution

- docs/api-reference/mapbox/mapbox-overlay.md
- docs/get-started/using-with-react.md
- docs/table-of-contents.json
Deprecation warning when following docs: 
```
getColor` is deprecated and will be removed in a later version. Use `getFillColor/getLineColor` instead
```
> [mapbox] docs use getFillColor instead of getColor

- docs/api-reference/core/web-mercator-viewport.md
- modules/core/src/viewports/web-mercator-viewport.ts
Without this clarification `fitBounds` doesn't behave correctly because the default value for `width` and `height` is `1`.
> [docs] `fitBounds` requires width and height

- examples/webpack.config.local.js
- Add missing transforms to webpack config (copied from https://github.com/uber-web/ocular/blob/master/modules/dev-tools/src/configuration/get-babel-config.js)
> [chore] fix local debugging config

- docs/api-reference/mapbox/overview.md
- modules/core/src/viewports/web-mercator-viewport.ts
- modules/core/src/views/map-view.ts
- modules/mapbox/src/deck-utils.ts
- test/apps/multi-viewport/package.json
For #7064 
Note that this only matches the camera matrices between deck and the base map, so that positions are projected correctly. Any data with z=0 in deck layers will still be rendered at sea level and not align with the terrain surface.
- Upgrade math.gl dependency to include https://github.com/uber-web/math.gl/pull/295
- Calculate `viewState.position` if terrain is used
> [mapbox] Match base map camera when terrain is used

- docs/api-reference/geo-layers/h3-cluster-layer.md
- docs/api-reference/geo-layers/h3-hexagon-layer.md
- website/src/doc-demos/geo-layers.js
h3-js has published a new major version which contains breaking changes.
@nrabinowitz Unrelated but `4.0.0-rc1` should not be tagged `latest`?
- Documentations of H3 layers
- In-doc examples of H3 layers
> Restrict h3-js version in scripting examples

- modules/mapbox/src/deck-utils.ts
For https://github.com/visgl/deck.gl/discussions/7170
Not super happy about the behaviors relying on `redrawReason` (a similar bug here https://github.com/visgl/deck.gl/pull/7092) but this will revert the breaking change for now.
- Avoid passing redraw reason to the React component
> [mapbox] Fix legacy React usage pattern

- modules/mapbox/src/deck-utils.ts
- test/modules/mapbox/mapbox-layer.spec.js
For #7128
maplibre 2.0 does not expose `map.version`, see issue at https://github.com/maplibre/maplibre-gl-js/issues/1426
I'm proposing to drop compatibility with mapbox-gl v0.50-1.2, which are more than 3 years old (mapbox v1's latest is 1.13 and maplibre v1's latest is 1.15). These versions are currently identified by the absence of `map.version`.
- Always use the most recent near plane value (technically a breaking change, for mapbox-gl <=1.2)
> Fix maplibre-gl interleaving

- modules/core/src/lib/view-manager.ts
- test/modules/core/lib/view-manager.spec.js
For #7156
`Controller.makeViewport` currently assumes that the associated `view` never changes.
- Always use the latest view to calculate view states
> Fix controller bug when view props change

- docs/api-reference/layers/geojson-layer.md
- docs/api-reference/layers/solid-polygon-layer.md
- modules/layers/package.json
- modules/layers/src/geojson-layer/geojson-layer.ts
- modules/layers/src/geojson-layer/sub-layer-map.ts
- modules/layers/src/solid-polygon-layer/polygon-tesselator.ts
- modules/layers/src/solid-polygon-layer/polygon.ts
- modules/layers/src/solid-polygon-layer/solid-polygon-layer.ts
- test/modules/layers/polygon-tesselation.spec.js
This should fix rendering of full 3d data (data that changes only on the z plane). See https://github.com/visgl/deck.gl/issues/7203
As per the suggested solution to the issue https://github.com/mapbox/earcut/issues/21#issuecomment-98119437 this should calculate the plane with the maximum area, then use that plane to tesselate on.
I've also bumped the earcut version to the latest as it was a few behind, and according to the patch notes there have been a lot of performance improvements made.
> [feat] Add a _full3d prop that uses the plane with the maximum area to tesselate

- modules/carto/src/api/maps-v3-client.ts
- test/modules/carto/api/maps-api-client.spec.js
QueryParameters are not reading well in the fetchMap method
Read QueryParameters from the dataset object
> CARTO fetchMap fix: parametrized queries are not working

- modules/carto/bundle.ts
- modules/json/src/helpers/execute-function.js
- modules/json/src/helpers/instantiate-class.js
- modules/json/src/json-converter.js
- modules/jupyter-widget/src/playground/create-deck.js
This PR contains the required changes in the JS modules to support functions from custom libraries.
**@deck.gl/carto**
- Export deck.carto in CartoLayerLibrary (including the functions)
**@deck.gl/json**
- Add warn when converting the functions (like in the classes) instead of an error. This is required to allow loading functions from a custom library
**@deck.gl/jupyter-widget**
- Extract functions from library
- Allow passing a configuration in createDeck
> Support dynamic functions in configuration

- modules/carto/src/api/layer-map.ts
- modules/carto/src/api/parseMap.ts
- carto: fetchMap supports markers with original, not-masked colors
> carto/fetchMap: support custom markers with original colors

- modules/jupyter-widget/src/playground/widget-tooltip.js
- test/modules/jupyter-widget/widget-tooltip.spec.js
Minor fix in widget-tooltip variables replacement: reset the value to avoid replacing non-existing variables in the template.
> Minor fix in widget-tooltip: reset value on every iteration

- modules/carto/src/api/layer-map.ts
- modules/carto/src/api/parseMap.ts
- test/apps/carto-map/app.js
- test/modules/carto/data/visState.json
To match behavior in Kepler, `depthTest: false` needs to be set on point layers
- disable depthTest for point layers
- test updates
> CARTO: fetchMap disable depthTest for point layers

- modules/carto/src/api/maps-v3-client.ts
The maps API no longer guesses the geometry column, so it must be explicitly specified
- Explicitly specify `geoColumn` for GeoJSON fetchMap datasets
> CARTO: Explicitly set geoColumn when requesting geoJSON

- modules/layers/src/text-layer/font-atlas-manager.ts
When you have 2 `TextLayer` instances using the same fontFamily, fontWeight, ... (all the properties used in the `_getKey()` method are the same) and the `charSet` is set to `auto`, you could end up in a situation where the atlas of 1 of the text layers doesn't contain all the characters.
In my application I have the following scenario:
- 2 `TextLayer` instances with the same font settings (hence the `_getKey()` method would return the same String)
- Extra data is added to 1 `TextLayer` where the text contains new characters, not previously present
- Later, the same data is added to the other `TextLayer`. However, the drawn text for this second layer only shows the characters that were already present on the map and not the new characters. This indicates those new characters are not …
> Font Atlas Manager: Always update the atlas with the cached version

- docs/api-reference/core/layer.md
- Correct import typo. We no longer update `luma.gl`. Use `@luma.gl/constants`.
> [docs] luma constants

- modules/carto/src/layers/spatial-index-tile-layer.ts
Edge case where changing the `aggregationResLevel` leads to invalid tiles being requested
- Recreate `Tileset` whenever `aggregationResLevel` is changed
> CARTO: Recreate tileset if aggregationResLevel changes

- modules/carto/src/api/maps-v3-client.ts
- test/modules/carto/api/maps-api-client.spec.js
Checking the existence of the `aggregationResLevel` if we don't have `aggregationExp` is not correct because we add a default `aggregationExp` if it doesn't exist https://github.com/visgl/deck.gl/blob/master/modules/carto/src/api/maps-v3-client.ts#L174
This can cause some maps to fail when loaded via the fetchMap method
- Remove the `aggregationResLevel` existence check if we don't have `aggregationExp`.
> CARTO: remove aggregationExp parameter check

- modules/core/src/viewports/viewport.ts
- modules/react/src/utils/position-children-under-views.ts
For #7382
react-map-gl v7 ignores top-level `padding` prop if `viewState` is passed.
- Store original `padding` value in Viewport class
- Pass down `padding` as part of `viewState` to React children
> [react] Fix padding compatibility with react-map-gl v7

- examples/webpack.config.local.js
- package.json
- yarn.lock
This solves various compilation errors when running the `start-local` command from the examples.
`@babel/preset-typescript` uses a babel transform which does not support some of the latest typescript syntax.
`ts-loader` uses tsc under the hood.
- use `ts-loader` in `webpack.config.local.js`
> [chore] use ts-loader in local app testing

- modules/geo-layers/src/tile-layer/tileset-2d.ts
- test/modules/geo-layers/tile-layer/tileset-2d.spec.js
For #7396
- Tileset2D never prunes selected tiles from cache
- Test
> Fix Tileset2D cache pruning

- examples/website/map-tile/app.js
- modules/geo-layers/src/tile-layer/tile-layer.ts
This fixes the following issue in the [map-tile example](https://deck.gl/examples/tile-layer/):
- tooltip shows nonsense content instead of disappearing when the pointer leaves the map
- `pickInfo.tile` should not be populated if nothing is picked. This might be lightly breaking if an application expects `tile` to be always present (like the example app) but arguably is the correct behavior.
> TileLayer exposes accurate picking info on pointer out

- modules/layers/src/icon-layer/icon-manager.ts
For https://github.com/visgl/deck.gl/discussions/7449
The discrepancy comes from loading images with and without premultiplication.
The default ImageLoader is registered with options: https://github.com/visgl/deck.gl/blob/691e3f5bce548aacbf00a16e65c87fae5501b4f2/modules/core/src/lib/init.ts#L56-L60
This is used for loading the `iconAtlas` prop.
When using auto packing, the `IconManager` calls `load` directly with `ImageLoader`, in which case the default options are not used.
- Use default loader to load individual icons
> Use default loader to load icons

- .eslintrc.js
- modules/aggregation-layers/package.json
- modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-cell-layer.ts
- modules/aggregation-layers/src/heatmap-layer/heatmap-layer-utils.ts
- modules/aggregation-layers/src/utils/cpu-aggregator.ts
- modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.ts
- modules/aggregation-layers/src/utils/resource-utils.ts
- modules/arcgis/package.json
- modules/arcgis/src/commons.ts
- modules/core/src/lib/deck-picker.ts
- modules/core/src/lib/deck.ts
- modules/extensions/package.json
- modules/extensions/src/data-filter/aggregator.ts
- modules/google-maps/package.json
- modules/layers/package.json
- modules/layers/src/bitmap-layer/bitmap-layer.ts
- modules/layers/src/column-layer/column-layer.ts
- modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.ts
- test/modules/core/lib/resource/resource-manager.spec.js
- test/modules/core/lifecycle/component-state.spec.js
- test/modules/core/shaderlib/project/project-32-64-glsl.spec.js
- test/modules/layers/core-layers.spec.js
- tsconfig.json
> chore(tests): lint fixes, test fixes

- examples/webpack.config.local.js
Fixes regression introduced by https://github.com/visgl/deck.gl/pull/7401. When trying to build test apps that include layers from the aggregation-layers an error is thrown due to a `.js` not being processed by the loader. Repro by running `yarn start-local` in `test/apps/carto-map`.
```
ERROR in deck.gl/modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.js 185:25
Module parse failed: Unexpected token (185:25)
File was processed with these loaders:
* ../../../node_modules/source-map-loader/index.js
You may need an additional loader to handle the result of these loaders.
|     } = this.state;
|
>     gridAggregationModel?.delete();
```
- Include `.js` files in `ts-loader` config
> Include js files for ts-loader

- modules/core/src/lib/attribute/attribute.ts
- test/modules/core/lib/attribute/attribute-manager.spec.js
For #7504
Internally generated `startIndices` always have `data.length + 1` elements, with the last one indicating the end of the attribute buffer. This may not be true with user-supplied `startIndices`.
- Add a safety check to `attribute.getVertexOffset`, which is used by `layer.disablePickingColor`
- Unit tests
> Fix disablePickingColor with externally supplied startIndices

- modules/core/src/lib/composite-layer.ts
- modules/core/src/lifecycle/component-state.ts
- modules/core/src/lifecycle/component.ts
- modules/core/src/lifecycle/constants.ts
- modules/core/src/lifecycle/create-props.ts
- modules/core/src/lifecycle/props.ts
- test/bench/create-props.bench.js
- test/modules/core/lib/layer.spec.js
- test/modules/core/lifecycle/props.spec.js
For #7496
Before this change, we parse the static `defaultProps` object once for each layer class, and then merge it recursively with parent class defaults once for each layer class as well. The result is stored in e.g. `ScatterplotLayer["_mergedDefaultProps"]`.
After this change, we parse the static `defaultProps` object once for each layer class and layer extension class, and merge them recursively with parent class defaults for each layer class + extension class list combination. The result is stored in e.g. `ScatterplotLayer["_mergedDefaultProps:DataFilterExtension:FillStyleExtension"]`.
This approach ensures that `ExtensionClass.defaultProps` behave the same as `LayerClass.defaultProps` when used together.
My main concern about merging this is the perf impact. Here are the resulting …
> Handle defaultProps of extensions

- modules/core/src/lib/layer.ts
- test/modules/core/lib/layer.spec.js
For #7560
- Update module settings if `highlightedObjectIndex` is switched from number to null
- Test cases for different highlighting props combinations
> Improve logic to update auto highlight module settings

- docs/developer-guide/custom-layers/prop-types.md
- modules/core/src/lifecycle/prop-types.ts
- modules/core/src/utils/texture.ts
- modules/extensions/src/fill-style/fill-style.ts
- test/modules/extensions/fill-style.spec.js
Follow up of #7496
- Remove ad-hoc prop handling in FillStyleExtension, use core async resolution system
- `image` prop type accepts a new option to override default texture parameters
- Tests
- Docs
> FillStyleExtension leverages new default props behavior

- modules/carto/src/api/layer-map.ts
When aggregating via `count`, we there is no need to calculate domain of input data.
- support for aggregation type `count` in `fetchMap`
> Carto: support for attributes aggregated by count

- modules/core/src/index.ts
- modules/core/src/lib/constants.ts
- modules/core/src/lib/deck-picker.ts
- modules/core/src/lib/layer-extension.ts
- modules/core/src/lib/layer.ts
- modules/core/src/passes/draw-layers-pass.ts
- modules/core/src/passes/layers-pass.ts
- modules/core/src/passes/pick-layers-pass.ts
- modules/core/src/types/layer-props.ts
- modules/extensions/src/mask/mask-effect.ts
- modules/extensions/src/mask/mask-pass.ts
- test/modules/core/lib/deck-picker.spec.js
- test/modules/extensions/mask/mask-effect.spec.js
For #7195
This PR contains changes to the core module in preparation to support terrain. There should be no breaking change.
- Add `OPERATION.TERRAIN` enum
- `Layer`: `operation` prop supports any combination of operations, e.g. `draw+terrain`
- `DeckPicker`: invoke `effect.preRender()` in the picking pass as well as the screen render pass
- `LayerExtension`: add `getNeedsRedraw` lifecycle method
- Light refactor in `LayersPass` and `PickLayersPass` for easier subclassing
> TerrainExtension (1/3)

- modules/layers/src/arc-layer/arc-layer-vertex.glsl.ts
- modules/layers/src/icon-layer/icon-layer-vertex.glsl.ts
- modules/layers/src/line-layer/line-layer-vertex.glsl.ts
- modules/layers/src/path-layer/path-layer-vertex.glsl.ts
- modules/layers/src/point-cloud-layer/point-cloud-layer-vertex.glsl.ts
- modules/layers/src/scatterplot-layer/scatterplot-layer-vertex.glsl.ts
- modules/layers/src/text-layer/text-background-layer/text-background-layer-vertex.glsl.ts
- modules/mesh-layers/src/scenegraph-layer/scenegraph-layer-vertex.glsl.ts
- modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer-vertex.glsl.ts
For #7195
`TerrainExtension` rewrites gl_Position in the `DECKGL_FILTER_GL_POSITION` hook based on the common position. This breaks layers like `IconLayer`, `TextLayer`, `ScatterplotLayer`, `PathLayer` in billboard mode, where multiple vertices are offset from the same clipspace anchor.
`DECKGL_FILTER_GL_POSITION` is currently called after the last assignment of `gl_Position`.
This PR moves it to before any clipspace offset is applied, i.e. where `gl_Position` corresponds to `geometry.position`.
- Invoke `DECKGL_FILTER_GL_POSITION` hook before screen space offset is applied
> DECKGL_FILTER_GL_POSITION hook consistency

- modules/core/src/lib/layer-state.ts
- modules/core/src/lib/layer.ts
- modules/core/src/lifecycle/component-state.ts
- modules/test-utils/src/lifecycle-test.js
- test/modules/core/lib/composite-layer.spec.js
- test/modules/core/lifecycle/component-state.spec.js
For https://github.com/visgl/deck.gl/pull/7605#discussion_r1091946791
`layer.getCurrentLayer()` should return `null` if the layer has been removed.
- `ComponentState` clears component reference when finalized
- test-utils `testInitializeLayer` adds option to defer finalization
- Unit tests
> ComponentState should dereference component on finalize

- modules/core/src/lib/deck-picker.ts
- modules/core/src/lib/deck-renderer.js
- modules/core/src/lib/deck.ts
- modules/core/src/lib/effect-manager.ts
- modules/core/src/lib/effect.ts
- modules/core/src/lib/layer-extension.ts
- modules/core/src/lib/layer-state.ts
- modules/core/src/lib/layer.ts
- modules/core/src/passes/layers-pass.ts
- test/modules/core/lib/layer-extension.spec.js
For #7374
See relevant discussions in https://github.com/visgl/deck.gl/pull/7375
- `EffectManager.addDefaultEffect` supports sorting of effects
- Add `LayerExtension.getNeedsPickingBuffer` to enable picking buffer on a layer
- Add `preRenderStats` to `LayersPassRenderOptions` to pass information from `Effect.preRender` to downstream pipelines.
> Preparation for CollideExtension

- modules/core/src/passes/layers-pass.ts
- modules/core/src/viewports/viewport.ts
- modules/geo-layers/src/tileset-2d/tileset-2d.ts
- modules/geo-layers/src/tileset-2d/utils.ts
- test/modules/geo-layers/tileset-2d/tileset-2d.spec.js
For #7614
When using `MapView` with `repeat: true`, and the scissor rect crosses the 180 meridian, the world space culling bounds may not be described by a single rectangle.
- `getCullBounds` handles sub viewports
- Unit tests
> Fix tile culling in repeating WebMercatorViewport

- modules/layers/src/icon-layer/icon-manager.ts
- modules/layers/src/text-layer/font-atlas-manager.ts
For https://github.com/visgl/deck.gl/discussions/7623
According to https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext#browser_compatibility this flag is not implemented in Safari but it doesn't seem to break when I tested locally.
- IconManager
- FontAtlasManager
> Add willReadFrequently flag to 2d context creation

- modules/carto/src/api/maps-v3-client.ts
- test/modules/carto/api/maps-api-client.spec.js
POST requests create issues with the API, increase the size limit for GET request to allow larger queries
> CARTO: Increase GET limit to 8192

- docs/api-reference/core/deckgl.md
- examples/gallery/src/arc-layer.html
- examples/gallery/src/bitmap-layer.html
- examples/gallery/src/boiler-plate.html
- examples/gallery/src/column-layer.html
- examples/gallery/src/contour-layer.html
- examples/gallery/src/geojson-layer.html
- examples/gallery/src/great-circle-layer.html
- examples/gallery/src/hexagon-layer.html
- examples/gallery/src/highway.html
- examples/gallery/src/icon-layer.html
- examples/gallery/src/line-layer.html
- examples/gallery/src/scatterplot-layer.html
- examples/gallery/src/screengrid-layer.html
- examples/gallery/src/text-layer.html
- examples/gallery/src/tile-3d-layer.html
- examples/gallery/src/viewport-transition.html
- examples/get-started/scripting/carto/index.html
- examples/get-started/scripting/mapbox/index.html
- modules/core/bundle/deckgl.js
For #7635 
It's possible to use maplibre with the current bundle, but the user is required to pass `map: maplibregl` to the `DeckGL` constructor. This PR make it possible to use maplibre without this manual step.
- Auto detect `maplibregl` global object
- Move scripting examples to use maplibre-gl
> Better support for maplibre in scripting interface

- modules/core/bundle/index.ts
- modules/core/src/scripting/deckgl.ts
- modules/core/src/scripting/loadersgl.ts
- modules/core/src/scripting/lumagl.ts
`yarn test dist` is failing on master as a fallout of the test harness upgrade.
The issue is that a significant chunk of code in `modules/core/bundle` is also a dependency of `jupyter-widget`. The test harness can only correctly resolve import paths for code in `modules/*/src`.
Before all these changes to the test harness, the jupyter-widget tests were wrapped in a try/catch and silently ignored if imports failed. I do not believe it was the right solution as it also ignored any non-import-related issues. And we can no longer do that anyways because `require` is not allowed in the current ESM-only setup.
- Move `DeckGL` scripting interface into `core/src`
- JS -> TS
> Move core bundle source into src directory

- docs/api-reference/layers/icon-layer.md
- modules/layers/src/icon-layer/icon-manager.ts
- test/modules/layers/icon-manager.spec.js
This issue has been raised in the Slack channel:
When using the `IconLayer` with auto packing, the application may not know the dimensions of an icon before loading it. Providing the wrong width/height will cause the rendered icon to be stretched.
After this PR, the `IconManager` preserves the aspect ratio of the incoming icon image while resizing.
This is technically a breaking change with no way of reverting to the old behavior. I would argue that it is the expected behavior, though.
Other caveats:
- The packing algorithm is still run before any icon is loaded using the user-provided width/height, so there may end up being some empty pixels in the texture when all is loaded. However, this way we only have to resize the texture once.
- If an icon image's aspect ratio is different from …
> IconManager preserve aspect ratio when auto packing

- modules/geo-layers/src/tile-3d-layer/tile-3d-layer.ts
- modules/geo-layers/src/tile-layer/tile-layer.ts
If the TileLayer is rendered as a sub layer of another layer (e.g. TerrainLayer), `pickingInfo.sourceLayer` points to the TileLayer itself, creating an infinite loop in `updateAutoHighlight`. The same goes for `Tile3DLayer`.
`updateAutoHighlight` should not depend on a pick info field that it doesn't manage.
- Create a separate field `sourceTile` in `pickingInfo` for tile highlighting.
> Fix autoHighlight crash when TileLayer is used as a sub layer

- modules/core/src/lib/deck-renderer.ts
- modules/core/src/lib/deck.ts
- modules/core/src/passes/layers-pass.ts
- modules/core/src/passes/pick-layers-pass.ts
- modules/extensions/src/collide/collide-effect.ts
- modules/extensions/src/mask/mask-effect.ts
- modules/extensions/src/terrain/terrain-effect.ts
- test/modules/extensions/terrain/terrain-effect.spec.js
- DeckRenderer to TypeScript
- Remove `pass.startsWith('picking')` hack, include a `isPicking` flag in render context
> DeckRenderer to TypeScript

- docs/api-reference/aggregation-layers/heatmap-layer.md
This fixes the formatting of a link.
The URL included parenthesis that were confusing the markdown parser, so I've encoded these characters.
This affected both the [rendering of the file on GitHub](https://github.com/jamesscottbrown/deck.gl/blob/master/docs/api-reference/aggregation-layers/heatmap-layer.md) and on the [generated docs site](https://deck.gl/docs/api-reference/aggregation-layers/heatmap-layer).
> docs: fix formatting of link

- docs/api-reference/extensions/collision-filter-extension.md
- docs/api-reference/extensions/overview.md
- docs/api-reference/extensions/terrain-extension.md
For #7635 
https://codepen.io/vis-gl/pen/oNPXXzm
@felixpalmer There is a bug here - the collide map is not rerendered after the icon layer is loaded, you'll need to move around to get it to update.
https://codepen.io/vis-gl/pen/VwGLLeR
- CollideExtension doc
- TerrainExtension doc
> Add embedded demo to new extension docs

- modules/extensions/src/mask/mask-effect.ts
For https://github.com/visgl/deck.gl/issues/7635, specifically required for animating mask in https://github.com/visgl/deck.gl/pull/7681
Logic is similar to that used in `TerrainEffect`: https://github.com/visgl/deck.gl/blob/master/modules/extensions/src/terrain/height-map-builder.ts#L59-L65
- Check for new Layer instance and transitions when checking for `maskChanged`
> Update mask when layer instance changes

- docs/developer-guide/views.md
This might seem obvious, but an explicit statement might have helped me to avoid a bug I've just spent a while debugging.
(I was using a deck.gl MapboxOverlay, and updating the viewport with`deckOverlay.setProps({viewState })` - this worked, but interacting with the map would snap back to the previous viewport. The fix was to update the viewport on the mapbox map instead).
> docs: add warning about updating viewport

- docs/api-reference/layers/text-layer.md
- docs/upgrade-guide.md
- examples/layer-browser/src/examples/core-layers.js
- modules/layers/src/text-layer/text-layer.ts
This PR addresses 2 semi-related issues:
- It's unclear what the value of the `maxWidth` prop refers to. It is not CSS pixels, and it is not a multiplier.
- When using `TextLayer` with background and the `CollisionFilterExtension`, overriding `sizeScale` in `collisionTestProps` results in unexpected behavior in the `TextBackgroundLayer`.
Explanation:
In the context of the `TextLayer`, there are two size systems:
- User-specified text size, via `getSize` and `sizeScale`. The layer roughly matches the output of the layer to CSS pixels, e.g. `getSize: 12, sizeScale: 2` in layer props is roughly equivalent to `font-size: 24px` in CSS. Let's call this **pixel size**.
- Internally, character positions in a text blob are calculated using the sizes of `iconMapping`, which depends on how large …
> TextLayer scaling consistency

- docs/developer-guide/coordinate-systems.md
I *think* this is a typo in the docs.
I think a multiplication sign would mean that the map is scaled such that whatever circle of latitude is being viewed corresponds to 512 common units, which seems reasonable.
A multiplication sign would also be consistent with how OSM map tlles work - the OSM wiki states [1]:
> The horizontal distance represented by each square tile, measured along the parallel at a given latitude, is given by:
> $S_{tile} = C ∙ cos(latitude) / 2^{zoomlevel}$
I initially noticed this because points on a scatteplot layer were about bigger than expected, and the error seemed to be roughly a factor of $1/cos^2(\phi)$,
[1]: https://wiki.openstreetmap.org/wiki/Zoom_levels
> docs: correct division sign to multiplication

- modules/core/src/shaderlib/picking/picking.ts
- modules/layers/src/bitmap-layer/bitmap-layer-fragment.ts
For #7698
- Do not override the default picking color when picking z
> Fix BitmapLayer pick 3d

- modules/core/src/lib/deck.ts
- modules/core/src/lib/effect-manager.ts
- modules/core/src/lib/view-manager.ts
- modules/core/src/lifecycle/prop-types.ts
- modules/core/src/utils/deep-equal.ts
- modules/extensions/src/collision-filter/collision-filter-effect.ts
- test/modules/core/utils/deep-equal.spec.js
Follow up of  #7506
The JSDoc states that `depth: ...Use 0 (default) for shallow comparison, -1 for infinite depth` while 0 is really used for comparing child fields one level down.
Across the code base, I can find usages of both semantics (sometimes 1 for child element comparison, sometimes 0).
- Match `deepEqual` behavior with JSDoc
> deepEqual consistency

- modules/geo-layers/package.json
- modules/geo-layers/src/wms-layer/utils.ts
- modules/geo-layers/src/wms-layer/wms-layer.ts
- package.json
- test/modules/geo-layers/wms-layer.spec.js
Saves ~78k in bundle size
- Move proj4 to dev dependencies (for testing)
- Alternative projection util
- Tests
> Replace proj4 with lightweight alternative

- docs/upgrade-guide.md
For https://github.com/visgl/deck.gl/pull/7728
> Upgrade guide note on GoogleMapsOverlays rightclick

- modules/core/src/effects/post-process-effect.ts
- modules/core/src/passes/screen-pass.ts
For #7748
The bug was introduced in #7515 - as part of the effort to avoid destroying/recreating models, `PostProcessEffect.setProps` was added to update existing module settings, but the settings are not propagated to the model.
- `ScreenPass` moves `moduleSettings` from constructor to `render` parameter
- `PostProcessEffect` calls new `ScreenPass` API
> Fix PostProcessEffect prop update

- modules/layers/src/text-layer/text-layer.ts
`TextLayer.fontSettings` propType doesn't include a compare depth leading to unnecessary state updates
> TextLayer.fontSettings propType compare depth 1

- website/src/doc-demos/codepen-automation.js
- Change Codepen dependency to maplibre-gl
> Use maplibre in Codepen examples

- modules/core/src/lib/attribute/data-column.ts
- test/modules/core/lib/attribute/attribute.spec.js
I was experiencing a bug that traced back to the attribute auto updater using data left over in reallocated buffers. This happens when an attribute's size is larger than 1 and the accessor returns `undefined`:
In the auto updater, the relevant block is https://github.com/visgl/deck.gl/blob/8.9-release/modules/core/src/lib/attribute/attribute.ts#L404-L410. When `objectValue` is undefined, calling `attribute._normalizeValue` ends up in https://github.com/visgl/deck.gl/blob/8.9-release/modules/core/src/lib/attribute/data-column.ts#L511-L514 -- which only puts `defaultValue[0]` into `out`. Thus when the auto updater calls [`fillArrray`](https://github.com/visgl/deck.gl/blob/master/modules/core/src/lib/attribute/attribute.ts#L405), it will only copy over a single value per vertex (`out` is …
> Fix bug when using default value in attributes with size greater than 1

- modules/extensions/src/collision-filter/shader-module.ts
For https://github.com/visgl/deck.gl/issues/7776
Using `vec4(0.)` to discard a vertex seems to have precision issues, safer to have a point that is clearly outside (e.g. where `w !== 0`.
- Discard vertex by placing outside clip space
> CollisionFilterExtension: Discard outside clip space

- modules/google-maps/src/utils.ts
- modules/mapbox/src/mapbox-overlay.ts
- test/modules/google-maps/google-maps-overlay.spec.js
This is branched off from #7668 to fix the existing bugs, but without the controversial changes to the API (which remain in #7668).
I've originally reported a bug on Slack: https://deckgl.slack.com/archives/C34AC5MSQ/p1676629109034669
The picking functions were used by the mapbox event handlers before deck was fully initialized.
This should hopefully land in v8.x before any breaking changes (in deck.gl v9.0).
- Avoid picking in GoogleMapsOverlay before deck is initialized
- Avoid picking in MapboxOverlay before deck is initialized
---
**None of this was tested**
I'm not sure how to run automated tests for the deck.gl codebase. `yarn bootstrap` fails with gyp not able to find `python` (which should be `python3` on this macOS machine). `yarn test` failed during linter step in untouched …
> Fix bug with picking in overlay mouse handlers before deck is initialized

- modules/carto/src/layers/schema/carto-spatial-tile-loader.ts
- modules/carto/src/layers/schema/carto-spatial-tile.ts
- modules/carto/src/layers/schema/carto-tile.ts
- modules/carto/src/layers/schema/carto-vector-tile-loader.ts
- modules/carto/src/layers/schema/fast-pbf.ts
- modules/carto/src/layers/schema/tile-loader-utils.ts
- modules/carto/src/layers/spatial-index-tile-layer.ts
The parsing of protobuffers is slower than it needs to be, due to the implementation iterating over large arrays of fixed size data, when it can just map the whole array into memory in some cases.
- Implement direct memory copy versions of `readPackedDouble` and `readPackedFixed64`
- Return the correct data structure from `TileReader` to avoid second pass to `unpackProperties`
- Speed up picking with spatial index layers by exploiting the tile/data heirarchy
> CARTO: data loading performance improvements

- modules/core/src/lib/layer-extension.ts
- modules/core/src/lib/layer.ts
- modules/core/src/lifecycle/component.ts
- modules/core/src/lifecycle/create-props.ts
- test/modules/carto/layers/carto-tile-layer.spec.js
- test/modules/core/lib/picking.spec.js
- test/modules/geo-layers/mvt-layer.spec.js
For #7811
Introduced by #7513 after we start merging default props from extensions.
- Use `Class.extensionName` as component name if exists
> Fix component name warning for layer extensions

- modules/carto/src/api/layer-map.ts
- modules/carto/src/api/maps-v3-client.ts
- modules/carto/src/layers/h3-tile-layer.ts
- modules/carto/src/layers/quadbin-tile-layer.ts
- modules/carto/src/layers/quadbin-utils.ts
- modules/carto/src/layers/schema/carto-spatial-tile.ts
- modules/carto/src/layers/schema/carto-tile.ts
- modules/carto/src/layers/schema/fast-pbf.ts
- modules/carto/src/layers/spatial-index-tile-layer.ts
- modules/carto/src/utils.ts
- test/modules/carto/index.js
- test/modules/carto/layers/quadbin-layer.spec.js
- test/modules/carto/utils.spec.js
For https://github.com/visgl/deck.gl/issues/7828
Changes in preparation for adding the 'raster' map type in order to reduce size of final PR. These changes do not change the function/API
- Type improvements
- New quadbin util method & tests
- Generalize fast-pbf function to allow use with all data types
- Cleaner way to force mime-type
- createBinaryProxy utility method
> CARTO: preparation for raster changes

- modules/carto/src/api/maps-v3-client.ts
- test/modules/carto/api/maps-api-client.spec.js
- test/modules/carto/mock-fetch.js
Followup to https://github.com/visgl/deck.gl/pull/7643
- Support switching to POST with long queries against the stats API
- Test for stats request flow
> CARTO: support long queres for stats requests via POST

- modules/core/src/lib/deck.ts
- modules/core/src/lib/view-manager.ts
- modules/core/src/views/view.ts
- test/modules/core/lib/view-manager.spec.js
- test/modules/core/shaderlib/project/project-functions.spec.js
- test/modules/react/deckgl.spec.js
- test/node.ts
For #7852
- Allow Deck class set `width` and `height` to 0
- Ignore viewport of size 0 (will skip `updateState` & `draw` of corresponding layers)
- Tests
> Handle hidden canvas

- modules/core/src/lifecycle/prop-types.ts
- modules/core/src/utils/texture.ts
- modules/extensions/src/fill-style/fill-style-extension.ts
- test/modules/extensions/fill-style.spec.js
For #7854
When `FillStyleExtension` is used with a composite layer, the `fillPatternAtlas` prop is loaded by the top-level layer (`GeoJsonLayer` in this case) and passed down to sublayers (`SolidPolygonLayer`). However, when a sublayer is finalized due to data change, it is able to delete the external texture, despite that the texture is still in use. This PR ensures that textures can only be released by the layer that created them.
- Use layer id to track texture ownership
- Test
> fix(core): premature release of texture prop

- test/render/test-cases/index.js
Fix CI failure on master
As far as I can tell, this test is broken in the Chrome v113 headless mode only. The browser test passes without any issues. The `instancePositions` data at each step read correctly, but the rendering outputs do not match the buffer.
Downgrading puppeteer also makes the issue go away.
- Temporarily disable the attribute transition render tests.
> Disable transition render tests

- docs/api-reference/geo-layers/tile-layer.md
Document that getTileMetadata is not optional and what to return from it.
> Update documentation for TileLayer

- modules/carto/src/layers/h3-tileset-2d.ts
- test/modules/carto/layers/h3-tileset-2d.spec.js
It is possible that the `H3TileLayer` is initialized (in particular when used with React) before the `WebMeractorViewport` is passed in. The missing latitude in the default viewport provided by `LayerManager`then causes a crash
- Handle non-geospatial viewport in `H3Tileset2D`
- Test
> CARTO: Handle DEFAULT-INITIAL-VIEWPORT in H3Tileset2D

- modules/react/src/utils/evaluate-children.ts
React deprecated `defaultProps` on functional components: https://github.com/facebook/react/pull/16210
react-map-gl change scheduled for v7.1: https://github.com/visgl/react-map-gl/pull/2173
This PR will detect a map component correctly when `defaultProps` is missing.
When used with `react-map-gl@>=7.0`, `props.mapStyle` is always specified by the user as the default `mapStyle` renders a blank map.
When used with `react-map-gl@<7.0`, `props.mapStyle` falls back to `defaultProps.mapStyle`.
- Do not rely on `defaultProps` when detecting React map component
> [react] detect map component without defaultProps

- modules/core/src/lib/tooltip.ts
- test/modules/core/lib/tooltip.spec.js
The tooltip element is shown below the picked object and this is not optimal when your object is in the bottom right of the map. This is not the best in terms of UX and the tooltip can overflow. Since deck doesn't handle tooltip position based on the dimensions of the tooltip element we need a way to pass in our own `style.transform` to setTooltip.
This PR has a minor improvement that uses user-provided `style.transform` without overwriting it at the end of setTooltip function. A similar change has been made to the overwrite of `style.display` because it's also hardcoded. See discussion in #7024 for more context.
- ENH: Extend el.style.transform in setTooltip
- TST: Add test to show getTooltip using user provided 'style.transform'
> Extend tooltip style.transform instead of overwriting it

- modules/core/src/controllers/controller.ts
For #7933
In this use case, when `dragRotate` and `dragPan` are both disabled programmatically, the `panend` event handler is deregistered, leaving the `isDragging` state to `true`.
This change does not introduce new performance overhead because `Deck`'s `onDrag*` events are still listening to `pan*` events, and the recognizer is never turned off.
- Correct `isDragging` controller state when `dragRotate` and `dragPan` are both off.
> Reset isDragging state if panning is disabled dynamically

- modules/carto/src/layers/carto-layer.ts
- test/modules/carto/carto-layer.spec.js
`loadOptions` passed to `CartoLayer` were getting [overwritten](https://github.com/visgl/deck.gl/blob/master/modules/carto/src/layers/carto-layer.ts#L329)
- Merge `loadOptions` with access token
- Test
> CARTO: merge loadOptions passed in prop

- modules/core/src/lib/deck.ts
- modules/core/src/lib/layer.ts
- tsconfig.json
- tsconfig.module.json
For #7945
- `layer.raiseError` wraps the incoming error instead of trying to amend it. `Error.cause` is universally supported as of 2022, see [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error#browser_compatibility)
- Log `error.cause` in Deck's default `onError` callback
> Avoid rewriting error.message

- modules/geo-layers/src/tile-layer/tile-layer.ts
For #7968
After #7513, we merge the props definition of extension classes into the props prototype, and use the async prop handling from `ComponentState`. `TileLayer` uses `{...props}` to pass props to `renderSubLayers`, which does not enumerate async props. In this case, the sublayers never receive the resolved values of `fillPatternAtlas` and `fillPatternMapping`, both added by the `FillStyleExtension`.
- Call `getSubLayerProps` in `TileLayer.renderLayers`
> Fix TileLayer passing async props to sub layers

- modules/aggregation-layers/package.json
- modules/arcgis/package.json
- modules/carto/package.json
- modules/core/package.json
- modules/extensions/package.json
- modules/geo-layers/package.json
- modules/google-maps/package.json
- modules/json/package.json
- modules/layers/package.json
- modules/main/package.json
- modules/mapbox/package.json
- modules/mesh-layers/package.json
- modules/react/package.json
- modules/test-utils/package.json
- yarn.lock
For #7936 
`@babel/runtime` is introduced to both the ES5 and ESM entry points by our current babel setting (`@babel/transform-runtime`). It should be listed as a dependency.
We may be able to eliminate the dependency in v9 with something similar to https://github.com/uber-web/probe.gl/pull/237
- Add @babel/runtime to dependencies
> Add @babel/runtime to dependencies

- docs/api-reference/json/conversion-reference.md
- docs/api-reference/json/json-configuration.md
- modules/json/src/helpers/instantiate-class.js
- modules/json/src/json-configuration.js
Read `React` from configuration as the `JsonConfiguration` merge function only allows to [add known attributes to the class](https://github.com/visgl/deck.gl/blob/master/modules/json/src/json-configuration.js#L40). 
Right now, React is always undefined when you try to render `reactComponents` and you will get this error `Cannot read properties of undefined (reading 'createElement')`
```
function instantiateReactComponent(Component, props, configuration) {
const {React} = configuration;
const {children = []} = props;
delete props.children;
if (configuration.preProcessClassProps) {
props = configuration.preProcessClassProps(Component, props, configuration);
}
props = convertFunctions(props, configuration);
return React.createElement(Component, props, children);
}
```
> Update json-configuration.js to read React from configuration root

- modules/geo-layers/src/mvt-layer/mvt-layer.ts
For #8005
- update type `MVTLayer`: optional `highlightedFeatureId` prop allows `number`, as well as `string` and `null`
> MVTLayerProps: allow `higlightedFeatureId` to be number

- package.json
- test/modules/layers/icon-manager.spec.js
- test/node.ts
- test/utils/mock-canvas-api.js
- yarn.lock
Remove `canvas` npm package from node test dependencies. This module is causing unnecessary trouble when installing on Apple Silicon chips.
- Remove `canvas` npm package from devDependency
> Remove canvas as devDependency

- docs/get-started/using-standalone.md
We noticed this example doesn't work without the CSS, and uses an older version of mapbox, so this PR is fixing it.
> Update standalone document

- .github/workflows/test.yml
- package.json
Allow CI to function on master while 9.0 work is in progress
> Temporarily disable node test and coverage report

- modules/layers/src/scatterplot-layer/scatterplot-layer-fragment.glsl.ts
This is a variant of #8046 targeted 8.9-release.
Fix for:
- #7613
- #6783
Scatterplot layer does not load on the Exynos based Samsung S22/S22+/S22 Ultra devices which include new Xclipse 920 graphics IP. The change in fragment shader helps to avoid the issue on these devices.
Tested on Exynos based Samsung Galaxy S22.
- Rendering workaround for Xclipse 920 in Scatterplot layer fragment shader
> Fix Scatterplot layer rendering on Xclipse 920 graphics

- modules/react/src/deckgl.ts
- modules/react/src/utils/extract-jsx-layers.ts
For #8108
- add typings for React DeckGL render callback
> Add typings for React render callback children

- modules/core/src/viewports/web-mercator-viewport.ts
- modules/mapbox/src/deck-utils.ts
For #8060
The current projection matrix parameters in WebMercatorViewport are designed to match an early release of Mapbox. Between mapbox-gl, maplibre-gl, and their different major versions, the calculation has diverged significantly. This hack extracts near and far plane positions from a private property on the mapbox-gl map.
For the long term, I will open feature requests for the base maps to expose their projection matrix.
- WebMercatorViewport accepts external nearZ/farZ positions
- MapboxLayer uses base map nearZ/farZ if available
> [mapbox] Fix interleaving when base map has terrain

- examples/website/carto-sql/app.jsx
- examples/website/plot/plot-layer/axes-layer.js
- website/src/examples/carto.js
The CARTO [example](https://deck.gl/examples/carto) is using the old (v2) API, this PR updates it to the new API.
- Update to v3 source
- Use colorBins & tidy
- Remove Weeks UI
> CARTO: Update website SQL example to use v3 API

- modules/carto/src/layers/schema/carto-tile.ts
The current API doesn't support passing NULL values in properties. It is possible to make the change in backend such that in the case of a NULL value the `value` property in the `KeyValueObject` is omitted, thus indicating a NULL. To support this the client must stop providing the empty string as a default value
- Use `null` as default for `KeyValueObject.value`
> CARTO: Use null as default value for KeyValueObject

- package.json
The carto module uses the `__VERSION__` injected by the build process to construct the URL needed for worker loaders. This parameter is injected during the build, however the publish process only bumps the npm version after the build completes. The `core` module also uses `__VERSION__` and is rebuilt using the `version` script after the bump to pick up the correct version
- Rebuild the carto module in the `version` script
> Add carto module to `version` build script

- test/modules/core/lib/deck.spec.ts
Test case introduced by #8065 written in v9 API cannot be directly cherry-picked into v8 branches
- Revert to using `gl`
> Fix node test on v8

- modules/core/src/controllers/controller.ts
For https://github.com/visgl/deck.gl/discussions/8101
- Only block wheel scroll if event is inside of an interactive view
> Fix issue where deck.gl blocks wheel scroll over non-interactive area

- babel.config.js
- package.json
- yarn.lock
For #7946 #8182
- Fix babel config syntax
- Bump ocular-dev-tools to include https://github.com/uber-web/ocular/pull/435 for publishing the widgets module
> [chore] Fix widget module publishing

- package.json
- if the developer has installed volta locally, it will ensure that the versions of yarn and node that are specified in the package.json volta section are used. Otherwise this section is ignored.
- this can save time when returning to a repo after some hiatus, as it is very clear what node and yarn versions are expected to work.
- volta sections have been added to most frameworks including deck.gl master.
- Add volta section to package.json
> chore: Add volta section to package.json on 8.10-release branch.

- modules/carto/src/layers/h3-tile-layer.ts
- modules/carto/src/layers/quadbin-tile-layer.ts
- modules/carto/src/layers/raster-tile-layer.ts
- modules/carto/src/layers/spatial-index-tile-layer.ts
For https://github.com/visgl/deck.gl/issues/8148
- Remove `aggregationResLevel` prop
- Tidy types in Spatial Index layers
> CARTO: Remove aggregationResLevel prop

- examples/website/ghcn/app.tsx
- examples/website/ghcn/index.html
- modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.ts
For https://github.com/visgl/deck.gl/issues/8193
- Convert example to Typescript
- Use `MeshAttributes` for `borderMesh`
- Fix `wireframe` rendering in `SimpleMeshLayer`
> [website] Fix ghcn website example

- modules/core/src/scripting/deckgl.ts
For #8226
Deck may not have any valid viewport if canvas size is 0.
- Sanity check before using viewport
> Fix scripting interface error when canvas is invisible

- modules/google-maps/src/google-maps-overlay.ts
Followup to https://github.com/visgl/deck.gl/pull/7919
- Also use `getCanvas()` in `GoogleMapsOverlay`
- Defensive checks for when canvas isn't available
> Use getCanvas() in GoogleMapsOverlay

- modules/core/src/lib/deck-picker.ts
- test/modules/core/lib/pick-layers.spec.js
For #8197
`pickObjects` currently uses `pickInfo.object` to dedup results. When using binary data, `pickInfo.object` is always `null`. This PR falls back to use `pickInfo.index` in this case.
This is the same as #8216 without the breaking change. Targeting v8.x.
- Return correct results when calling `pickObjects` with binary data
- Unit test
> Fix pickObjects when using binary data

- modules/core/src/lib/attribute/data-column.ts
- modules/core/src/lib/attribute/gl-utils.ts
For https://github.com/visgl/deck.gl/issues/8219
`ColumnLayer` was not rendering correctly, a regression first introduced in https://github.com/visgl/deck.gl/pull/8153 by adding a [layoutChanged()](https://github.com/visgl/deck.gl/pull/8153/files#diff-6865938bd9e33227cb4501cefc20abe93abb4098905de00a0653cd1a80750544R641)
check to the core `Layer` class. In the case of the `ColumnLayer` this was evaluating to `true` becuase the underlying comparison in [bufferLayoutEqual()](https://github.com/visgl/deck.gl/pull/8153/files#diff-11742470930e1b6ff2ef1c13c6102c1a9d18f0cbd76ef0bdb1655b68573b8b55R69) was detecting a change in the `instancePickingColors`, specifically the `stride` prop missing in the old accessor and set to `4` in the new accessor.
`Data-Column` uses the `getStride()` function to …
> Use getStride() in bufferLayoutEqual() comparison

- modules/carto/src/sources/boundary-query-source.ts
QueryParameters should be optional for boundaries as in any querysource
> QueryParameters should be optional for boundaries

- modules/carto/src/api/fetch-map.ts
The fetchMap function in the CARTO submodule retrieves the Builder map configuration, including source query parameters but we need to add them also to the requests for attribute statistics.
- Add query parameters to stats requests in fetchMap
> CARTO: Add queryParameters to stats requests in fetchMap

- test/modules/core/lib/deck.spec.ts
`yarn test` fails when run locally due to `htmlCanvas` not being defined
- [Use canvas rather than htmlCanvas in deck.spec](https://github.com/visgl/deck.gl/commit/973de77c1873546c08135ca2f76a0cc22846cad6)
> Use canvas rather than htmlCanvas in deck.spec

- modules/carto/src/layers/utils.ts
- modules/carto/src/layers/vector-tile-layer.ts
Followup to https://github.com/visgl/deck.gl/pull/8269
- Handle empty 204 responses
- Log instead of throw on duplicate geoid
> CARTO: Boundaries handle empty 204 responses

- modules/aggregation-layers/package.json
- modules/arcgis/package.json
- modules/carto/package.json
- modules/extensions/package.json
- modules/geo-layers/package.json
- modules/google-maps/package.json
- modules/json/package.json
- modules/layers/package.json
- modules/mapbox/package.json
- modules/mesh-layers/package.json
- modules/react/package.json
- modules/test-utils/package.json
- modules/widgets/package.json
Installing the v9 alpha package currently gives warnings of the form:
```
warning " > @deck.gl/aggregation-layers@9.0.0-alpha.3" has incorrect peer dependency "@deck.gl/core@^8.0.0".
```
- Bump all v8 peerDependencies to v9
> [chore] Bump peerDependencies to 9.0.0

- examples/website/plot/plot-layer/axes-layer.ts
- examples/website/plot/plot-layer/plot-layer.ts
- examples/website/plot/plot-layer/surface-layer.ts
- examples/website/plot/tsconfig.json
Cleanup from #8289. Originally builds were failing without a `tsconfig.json`, but that's no longer happening — possibly something else got fixed during the PR review process. With `tsconfig.json` removed, the `// @ts-ignore` lines are no longer necessary, so we can define `this.state` in the same way as other examples.
> [website] Clean up TS types in 'plot' example

- .github/workflows/release.yml
- .github/workflows/scorecard.yml
- .github/workflows/test.yml
- .github/workflows/website.yml
Updating CI to Node.js v18 LTS and current versions of GitHub Actions. Fixes a few errors in the CI logs. Security support for Node.js v16 ended in September. Some older GitHub Actions were still relying on Node.js v12.
https://endoflife.date/nodejs
We could also configure Dependabot or Renovate Bot to do this automatically, if that's of interest.
> chore(ci): Update CI dependencies

- examples/website/360-video/app.jsx
- modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.ts
- fixes https://github.com/visgl/deck.gl/issues/8315
- requires https://github.com/visgl/luma.gl/pull/1853
- related to https://github.com/visgl/luma.gl/pull/1810
- related to https://github.com/visgl/luma.gl/issues/1850
~~My guess is that my changes to manually bind picking uniforms in `simple-mesh-layer.ts` do not really belong in this file, but I've left that part in place for now since it did resolve the errors. Currently the mesh renders entirely in the picking color `#00ffff`, but if I comment that line of the shader out we do see the 360º video as expected, so I think all that's left is the fixes to picking discussed in #1850.~~
~~Since there are a few related PRs and discussions in flight, I'm just opening this PR for visibility.~~
Fixes broken link to 360º video. Earlier commits …
> [website] Update FirstPersonView example for v9

- modules/carto/src/api/layer-map.ts
- test/apps/carto-map/app.ts
- test/modules/carto/api/layer-map.spec.ts
Quantile stats for numeric attributes in static spatial index tilesets  are enclosed in extra `global` object
- support extra `global` container for quantile stats in carto fetchMap API
> Carto: fix support for quantile color scale in static tilesets in fetchMap

- docs/api-reference/core/fly-to-interpolator.md
The "source" link for `fly-to-interpolator` seems to be outdated/broken/not working anymore, updated with new link.
For #8319
- Fix "source" link for `fly-to-interpolator` docs
> docs: fix source link for `fly-to-interpolator` (close #8319)

- modules/carto/src/sources/base-source.ts
- modules/carto/src/sources/types.ts
For #8304
- Document properties new Carto Source constructors
> carto: add typedocs to source types

- modules/aggregation-layers/src/heatmap-layer/heatmap-layer.ts
- modules/core/src/lib/attribute/attribute-transition-utils.ts
- modules/core/src/lib/attribute/attribute.ts
- modules/core/src/lib/attribute/data-column.ts
- modules/core/src/lib/attribute/gl-utils.ts
- modules/core/src/lib/layer.ts
- modules/core/src/transitions/gpu-interpolation-transition.ts
- modules/core/src/transitions/gpu-spring-transition.ts
- modules/core/src/utils/tesselator.ts
- test/modules/core/lib/attribute/attribute.spec.ts
Applies changes required for removing BufferWithAccessor from luma.gl v9.
- https://github.com/visgl/luma.gl/pull/1864.
We'll have to do something about sync `getData`, but I'm leaving that for another PR.
> Remove use of deprecated BufferWithAccessor

- modules/core/src/lib/deck.ts
- modules/core/src/passes/layers-pass.ts
- modules/google-maps/src/google-maps-overlay.ts
> [v9] Fix GoogleMapsOverlay by not clearing canvas

- examples/experimental/tfjs/src/layers/tensor-2d-layer.ts
- modules/aggregation-layers/src/heatmap-layer/max-fs.glsl.ts
- modules/aggregation-layers/src/heatmap-layer/max-vs.glsl.ts
- modules/aggregation-layers/src/heatmap-layer/triangle-layer-fragment.glsl.ts
- modules/aggregation-layers/src/heatmap-layer/triangle-layer-vertex.glsl.ts
- modules/aggregation-layers/src/heatmap-layer/weights-fs.glsl.ts
- modules/aggregation-layers/src/heatmap-layer/weights-vs.glsl.ts
- modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer-fragment.glsl.ts
- modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer-vertex.glsl.ts
- modules/aggregation-layers/src/utils/gpu-grid-aggregation/aggregate-to-grid-fs.glsl.ts
- modules/aggregation-layers/src/utils/gpu-grid-aggregation/aggregate-to-grid-vs.glsl.ts
- modules/aggregation-layers/src/utils/gpu-grid-aggregation/transform-mean-vs.glsl.ts
- modules/arcgis/src/commons.ts
- modules/core/src/effects/post-process-effect.ts
- modules/core/src/shaderlib/shadow/shadow.ts
- modules/core/src/transitions/gpu-interpolation-transition.ts
- modules/core/src/transitions/gpu-spring-transition.ts
- modules/extensions/src/brushing/shader-module.ts
- modules/extensions/src/clip/clip-extension.ts
- modules/extensions/src/collision-filter/shader-module.ts
- modules/extensions/src/data-filter/aggregator.ts
- modules/extensions/src/data-filter/shader-module.ts
- modules/extensions/src/mask/shader-module.ts
- modules/extensions/src/terrain/shader-module.ts
- modules/layers/src/icon-layer/icon-layer.ts
- modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer-fragment.glsl.ts
- modules/layers/src/text-layer/text-background-layer/text-background-layer-fragment.glsl.ts
- modules/layers/src/text-layer/text-background-layer/text-background-layer-vertex.glsl.ts
- modules/mesh-layers/src/scenegraph-layer/scenegraph-layer-fragment.glsl.ts
Opening this PR as a draft for now. Unlike the previous few PRs, ~~tests are failing here and~~ I haven't worked out how to test most of these changes, as they depend on things like aggregation layers that aren't working in v9 yet.
> Update remaining shaders to GLSL 300

- test/modules/carto/api/maps-api-client.spec.js
- test/modules/carto/carto-layer.spec.js
- fix cartoLayer tests broken in #8412
> carto/v8: fix CartoLayer tests

- modules/core/src/lib/attribute/attribute-transition-utils.ts
- test/modules/core/lib/attribute/attribute-transition-manager.spec.ts
Instead of getBufferData we can use WebGLBuffer#readSyncWebGL2, which has the advantage of greater type safety. I'm surprised by the changes in the unit test — see comment there — but this strictly improves visual results on `test/apps/attribute-transition` so I think it's an improvement directionally.
Related:
- https://github.com/visgl/deck.gl/pull/8379
- https://github.com/visgl/deck.gl/pull/8392
Dependencies:
- https://github.com/visgl/luma.gl/pull/1919
~_Marked as draft until Luma update in https://github.com/visgl/deck.gl/pull/8405._~
> chore(core): Remove getBufferData helper

- modules/carto/src/layers/spatial-index-tile-layer.ts
- modules/geo-layers/src/mvt-layer/find-index-binary.ts
- modules/geo-layers/src/mvt-layer/mvt-layer.ts
- modules/geo-layers/src/tile-layer/tile-layer.ts
- modules/geo-layers/src/tileset-2d/tile-2d-header.ts
- modules/geo-layers/src/tileset-2d/tile-2d-traversal.ts
- modules/geo-layers/src/tileset-2d/tileset-2d.ts
- modules/geo-layers/src/tileset-2d/utils.ts
As I was working on #8290 I noticed internal state (such as `state.tileset`) wasn't typed, which led to some difficultly when working on the layer. This PR adds types to for internal state to `TileLayer` and layers that extend it, namely `MVTLayer`, `SpatialIndexTileLayer`. Along the way I visited `Tileset2D` to ensure it was consistent with the layer's types.
I'll port changes to v9 as well, some of these layers are disabled so v8 is better for testing.
- Types internal state for `TileLayer`, `MVTLayer`, and `SpatialIndexTileLayer`
- Initializes optional state to `null` if the layer resets it to `null`
- Changes tile types from `undefined` to `null` where necessary
> v8 audit tile layer types

- modules/core/src/passes/pick-layers-pass.ts
Currently the picking buffer is not cleared correctly before each picking pass. In this block...
https://github.com/visgl/deck.gl/blob/eb44d5e53bc45cf97871c9f37aaed65a650a5e97/modules/core/src/passes/pick-layers-pass.ts#L80-L111
... we pass the clearColor into `withGLParameters`, but `layers-pass.ts` overrides it below:
https://github.com/visgl/deck.gl/blob/eb44d5e53bc45cf97871c9f37aaed65a650a5e97/modules/core/src/passes/layers-pass.ts#L63-L71
This PR provides one possible solution to the bug. But I am wondering if either the type definitions, or the current usage pattern of `withGLParameters`, should be changed in v9 to avoid similar issues. Perhaps `clearColor` should not be accepted as a parameter to `withGLParameters`? Or we start to remove uses of `withGLParameters` as we are working …
> fix(core): Ensure picking buffer is cleared before each pass

- examples/website/google-3d-tiles/app.jsx
- modules/extensions/src/terrain/terrain-effect.ts
For #7892
- Update terrain extension example with tooltip
- Detect picking render passes in terrain extension
- Fix terrain cover invalidation
To test, start `google-3d-tiles` example locally:
Just the updated example: Tooltips don't work.
Updated example and fixes: Tooltips work.
> TerrainExtension: Support picking on draped layers

- .eslintignore
- .gitignore
- .prettierignore
- docs/api-reference/mapbox/mapbox-overlay.md
- docs/get-started/using-with-typescript.md
- examples/experimental/tfjs/src/demo-histogram.ts
- examples/experimental/tfjs/src/demo-spectrogram.ts
- examples/experimental/tfjs/src/layers/histogram-layer.ts
- examples/experimental/tfjs/src/layers/spectrogram-layer.ts
- examples/experimental/tfjs/src/layers/tensor-2d-layer.ts
- examples/website/carto-sql/app.tsx
- package.json
In v9.0 (and implemented in #8460), TypeScript type definitions are included in the default entrypoints for all deck.gl modules. This PR cleans up remaining references to the legacy /typed entrypoints, and updates the documentation.
> chore(types): Remove remaining references to /typed entrypoints

- CHANGELOG.md
After discussing with @Pessimistress, we've decided not to release version 8.10 for production since it was mainly for testing widgets. Instead, we've included 8.10 changes in the v9 release, focusing on features ready for production.
I've reviewed the [8.10 alpha changelog](https://github.com/visgl/deck.gl/blob/8.10-release/CHANGELOG.md) and the [8.9 changelog](https://github.com/visgl/deck.gl/blob/8.9-release/CHANGELOG.md) to determine which updates should be documented in the v9 changelog. Our goal is to ensure clarity and accuracy in our release notes, avoiding duplication of changes already released in 8.9.
Once I've finalized the v9 changelog, I'll update the [GitHub release notes](https://github.com/visgl/deck.gl/releases/tag/v9.0.0-alpha.1) accordingly.
Let me know if there are …
> Add widgets to v9 changelog

- scripts/write-heading-ids.ts
- website/babel.config.js
- website/package.json
- website/yarn.lock
Currently these changes allow the website to be ran locally using `yarn start`, but `yarn build-staging` fails.
In order to publish the website, instances to `import GL from '@luma.gl/constants';` will need to be removed (to be done in followup PR)
- Fix `write-headings-id` script
- Remove `inline-webgl-constants` script
> Fix website to work with ESM

- examples/website/election/app.js
- examples/website/line/app.jsx
- examples/website/plot/plot-layer/surface-layer.ts
- examples/website/plot/plot-layer/utils.js
Folllowup to https://github.com/visgl/deck.gl/pull/8509, allows website to build now that we no longer use `inline-webgl-constants`
- Remove `GL from '@luma.gl/constants'` imports
- Replace constants
> [website] Remove luma.gl/core GL import from website

- modules/mapbox/src/mapbox-overlay.ts
For #8528
- Reset container text alignment
> fix(mapbox): overlay position affected by text alignment

- modules/extensions/src/data-filter/data-filter-extension.ts
Follow up to https://github.com/visgl/deck.gl/pull/7915
Omitting `categorySize` from constructor led to the shader to crash due to `DATACATEGORY_CHANNELS` not being defined
- Explicitly define options for `DataFilterExtension` constructor
> Provide defaultOptions for DataFilterExtension

- modules/aggregation-layers/src/hexagon-layer/hexagon-layer.ts
- modules/geo-layers/src/trips-layer/trips-layer.ts
Closes #8507
While working on this, I briefly searched for similar errors by looking for `ExtraPropsT & Required<` and noticed `HexagonLayer` had the same issue.
- Forward `DataT` from `TripsLayer` instance to `_TripsLayerProps` instance
- Forward `DataT` from `HexagonLayer` instance to `_HexagonLayerProps` instance
> Respect `DataT` on `TripsLayer` props

- docs/developer-guide/base-maps/using-with-mapbox.md
For https://github.com/visgl/deck.gl/issues/8538
- Fix broken link to react-map-gl's docs regarding usage with a mapbox-gl fork
> doc: using-with-mapbox: fix broken link

- .ocularrc.js
- modules/core/src/scripting/lumagl.ts
- modules/layers/src/column-layer/column-geometry.ts
For #7457 
Shaves ~110k off core dist.min.js
- Cherry pick luma global exports in core bundle
- Remove unnecessary import from ColumnGeometry
> Cherry pick luma global exports in core bundle

- modules/aggregation-layers/src/contour-layer/contour-layer.ts
- modules/aggregation-layers/src/cpu-grid-layer/cpu-grid-layer.ts
- modules/aggregation-layers/src/gpu-grid-layer/gpu-grid-layer.ts
- modules/aggregation-layers/src/heatmap-layer/heatmap-layer.ts
- modules/aggregation-layers/src/hexagon-layer/hexagon-layer.ts
- modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer.ts
- modules/carto/src/layers/raster-layer.ts
- modules/core/src/lib/attribute/data-column.ts
- modules/core/src/lib/attribute/gl-utils.ts
- modules/core/src/lib/layer.ts
- modules/core/src/transitions/gpu-spring-transition.ts
- modules/extensions/src/data-filter/data-filter-extension.ts
- modules/geo-layers/src/mesh-layer/mesh-layer.ts
- modules/layers/src/arc-layer/arc-layer.ts
- modules/layers/src/bitmap-layer/bitmap-layer.ts
- modules/layers/src/column-layer/column-layer.ts
- modules/layers/src/icon-layer/icon-layer.ts
- modules/layers/src/line-layer/line-layer.ts
- modules/layers/src/path-layer/path-layer.ts
- modules/layers/src/point-cloud-layer/point-cloud-layer.ts
- modules/layers/src/scatterplot-layer/scatterplot-layer.ts
- modules/layers/src/solid-polygon-layer/solid-polygon-layer.ts
- modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer.ts
- modules/layers/src/text-layer/text-background-layer/text-background-layer.ts
- modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.ts
- modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.ts
- test/modules/core/lib/attribute/attribute-manager.spec.ts
- test/modules/core/lib/attribute/attribute.spec.ts
For #7457 
- DataColumn class handles the new type
- Layer attribute definitions
- Tests
> Change Attribute.type to VertexType from WebGL constants

- modules/aggregation-layers/package.json
- modules/arcgis/package.json
- modules/carto/package.json
- modules/core/package.json
- modules/core/src/lib/attribute/data-column.ts
- modules/extensions/package.json
- modules/geo-layers/package.json
- modules/google-maps/package.json
- modules/json/package.json
- modules/jupyter-widget/package.json
- modules/layers/package.json
- modules/main/package.json
- modules/mapbox/package.json
- modules/mesh-layers/package.json
- modules/react/package.json
- modules/test-utils/package.json
- modules/widgets/package.json
For #7457 
- Remove duplicates between dependencies and peerDependencies
- peerDependencies should not lock version
- Remove unused dependencies
> Audit module dependencies

- test/browser.ts
- test/modules/aggregation-layers/index.ts
- test/modules/carto/index.ts
- test/modules/carto/layers/raster-tile-layer.spec.ts
- test/modules/core/lib/index.ts
- test/modules/geo-layers/index.ts
- test/modules/google-maps/google-maps-overlay.spec.ts
- test/modules/index.ts
- test/modules/json/json-render.spec.ts
Running `yarn test browser` in stable Chrome, on macOS:
- before: 1748 tests, 3 failures
- after: 1939 tests, 2 failures
Related:
- https://github.com/visgl/deck.gl/issues/8592
> chore(tests): Restore more in-browser tests

- modules/core/src/passes/layers-pass.ts
https://github.com/visgl/deck.gl/pull/8543 breaks `MaskPass` due to incorrect operator precedence causing `clearColor` to always be `[0, 0, 0, 0]` 
- Correct operator precedence for clearColor in LayersPass
> Correct operator precedence for clearColor in LayersPass

- .eslintignore
For #8595
I've been building pydeck locally which seems to have caused `yarn test` to throw the error described in #8595. To resolve I've just added the `bindings/` dir to .eslintignore
- added `bindings/` to .eslintignore
> ignore bindings directory when running linter

- package.json
- yarn.lock
Fixes `yarn test browser-headless` and `yarn test cover` on my machine, excluding render tests.
> chore(deps): Upgrade to puppeteer v22.4.0

- website/src/examples/mapbox.js
Follow up on #8600 
@felixpalmer noticed a crash with the Mapbox example in the website that hadn't occurred in the standalone version. The issue was introduced in #8557 when it was ported to react. The root cause should be resolved by importing the `App` component in the website instead of `renderToDOM`.
- import mapbox as react component
> chore(website) import mapbox as react component

- modules/core/package.json
- package.json
- yarn.lock
- Upgrade probe.gl to skip faulty release 4.0.8
> chore: bump probe.gl

- modules/core/src/scripting/deckgl.ts
- modules/core/src/scripting/map-wrapper.ts
- modules/mapbox/src/mapbox-overlay.ts
- package.json
- test/modules/react/utils/evaluate-children.spec.ts
- yarn.lock
Previously the scripting bundle imports the mapbox wrapper from react-map-gl v5. That version is no longer being maintained. This PR ports the wrapper class to TS and removes the dev dependency.
Saves ~30k off the core bundle.
- Adds `MapWrapper` class for scripting bundle
- Remove dev dependency on `react-map-gl` v5
> Remove dev dependency on react-map-gl v5

- website/src/examples/mapbox.mdx
Staging build fails when trying to build Mapbox example. Follow same pattern as with `carto.mdx` as mark as `ClientOnly`
> website: Do not render Mapbox example in SSR

- docs/api-reference/geo-layers/tile-layer.md
- modules/geo-layers/src/tile-layer/tile-layer.ts
- modules/geo-layers/src/tileset-2d/tileset-2d.ts
- modules/test-utils/src/generate-layer-tests.ts
- test/modules/geo-layers/tile-layer/tile-layer.spec.ts
- test/modules/geo-layers/tileset-2d/index.ts
- test/modules/geo-layers/tileset-2d/tileset-2d.spec.ts
Adds a 'debounceTime' prop to TileLayer and Tileset2D. Queues tile requests until no new tiles have been requested for at least `debounceTime` milliseconds. Assuming this API and feature sound OK, I'll include docs and tests as well.
Related:
- https://github.com/visgl/loaders.gl/pull/2892
> feat(geo-layers): Add .debounceTime option to Tileset2D, TileLayer

- modules/layers/src/point-cloud-layer/point-cloud-layer.ts
For https://github.com/visgl/deck.gl/issues/8582, fixes regression from https://github.com/visgl/deck.gl/pull/8572/
It may be worth considering updating the format emitted from loaders.gl @ibgreen to avoid passing GL constants
- PointCloudLayer colors attribute type use 'unorm8'
> PointCloudLayer colors attribute type use 'unorm8'

- examples/experimental/bezier/src/bezier-curve-layer/bezier-curve-layer.js
- examples/experimental/interleaved-buffer/app.js
- examples/website/plot/plot-layer/surface-layer.ts
Follow up to https://github.com/visgl/deck.gl/pull/8572 & fix for https://github.com/visgl/deck.gl/issues/8582 (fixes plot website example)
- Use string constants for buffer types
> examples: Use string constants for buffer types

- modules/carto/src/api/request-with-parameters.ts
> feat(carto): Sort params in request cache key.

- modules/core/src/controllers/first-person-controller.ts
For https://github.com/visgl/deck.gl/issues/8149
- Scrolling moves camera in direction given by pointer, with constant z
> FirstPersonController scroll to move in 2D

- modules/react/package.json
- yarn.lock
Non-TypeScript users should not be forced to install types
- Revert overly strict peer dependency versions from #8451
- Move `@types/react` and `@types/react-dom` to devDependencies
> fix(react): move types to devDependencies

- modules/carto/src/api/request-with-parameters.ts
In requestWithParameters, cache pending requests, not just completed requests. Tested against `examples/website/carto-sql`, reduces total number of API requests from 6 → 2.
> feat(carto): Cache pending requests.

- modules/core/src/passes/layers-pass.ts
For #8582 fixes the minimap example
- Clear viewport
> fix(core): support view.clear

- docs/api-reference/geo-layers/tile-layer.md
- docs/developer-guide/animations-and-transitions.md
- docs/developer-guide/building-apps.md
- docs/developer-guide/tips-and-tricks.md
- docs/developer-guide/view-state-transitions.md
- docs/get-started/using-with-react.md
There are various minor typos in documentation pages that I noted during reading. I see the guidance to create issues first, but these are truly trivial, and probably not worth an issue (per page). If the workflow requires them, let me know and I'll work through filing issues.
- fix documentation typos / spellos - no code changes
> docs: trivial typo fixes

- modules/core/src/lifecycle/prop-types.ts
- modules/extensions/src/fill-style/fill-style-extension.ts
- test/render/test-cases/index.js
- test/render/test-cases/polygon-layer.js
[Default texture parameters](https://github.com/visgl/deck.gl/blob/1c4f9a99596b3f913426f7d5df3d7e831b4e99c0/modules/core/src/utils/texture.ts#L3) sets `mipmapFilter: 'linear'` and it cannot be unset by merging with another `SampleProps`
Alternatively we could remove it from the defaults but that will be a bigger breaking change.
- Work around and comment
- Restore render tests
> Fix FillStyleExtension artifact

- modules/layers/src/solid-polygon-layer/solid-polygon-layer-vertex-main.glsl.ts
- modules/layers/src/solid-polygon-layer/solid-polygon-layer-vertex-side.glsl.ts
- modules/layers/src/solid-polygon-layer/solid-polygon-layer-vertex-top.glsl.ts
- test/render/test-cases/polygon-layer.js
Broken by refactor in #8153 - `project_normal` must be called after `geometry.position` is populated
- Call `project_normal` after project position
- Restore render test
> Fix SolidPolygonLayer lighting

- test/render/test-cases/views.js
Loaders v4 no longer includes status code in error message. See https://github.com/visgl/loaders.gl/pull/2921
- Restore render tests
> Restore MVTLayer render test

- modules/carto/src/index.ts
- modules/carto/src/sources/index.ts
I think access to these generic source option types (SourceOptions, QuerySourceOptions, ...) would be helpful. We can certainly work around not having them, but they do make things a bit easier to type.
> feat(carto): Export types for generic source options

- modules/extensions/src/fill-style/fill-style-extension.ts
Luma is mirroring the WebGPU spec, in which all samplers have `mipmapFilter`, but we can restrict the range of mipmaps used with `lodMinClamp` / `lodMaxClamp`. 
Related:
- https://github.com/visgl/deck.gl/pull/8668
> fix(extensions): Use lodMaxClamp to disable mips

- docs/upgrade-guide.md
- modules/core/src/effects/lighting/lighting-effect.ts
- modules/core/src/effects/post-process-effect.ts
- modules/core/src/index.ts
- modules/core/src/lib/deck-picker.ts
- modules/core/src/lib/deck-renderer.ts
- modules/core/src/lib/deck.ts
- modules/core/src/lib/effect-manager.ts
- modules/core/src/lib/effect.ts
- modules/extensions/src/collision-filter/collision-filter-effect.ts
- modules/extensions/src/mask/mask-effect.ts
- modules/extensions/src/terrain/terrain-effect.ts
- test/modules/core/effects/lighting-effect.spec.ts
- test/modules/core/effects/post-process-effect.spec.ts
- test/modules/core/lib/effect-manager.spec.ts
- test/modules/core/lib/index.ts
- test/modules/extensions/collision-filter/collision-filter-effect.spec.ts
- test/modules/extensions/collision-filter/index.ts
- test/modules/extensions/index.ts
- test/modules/extensions/mask/index.ts
- test/modules/extensions/mask/mask-effect.spec.ts
- test/modules/extensions/terrain/index.ts
- test/modules/extensions/terrain/terrain-effect.spec.ts
For #8680
- Add `setup` lifecycle method for creating GPU resources
- Update all Effect implementations
- Unit tests
> Update Effect interface

- modules/core/src/effects/lighting/lighting-effect.ts
- modules/core/src/index.ts
- modules/core/src/lib/deck.ts
- modules/core/src/lib/layer-manager.ts
- modules/core/src/lib/layer.ts
- modules/core/src/passes/shadow-pass.ts
- modules/core/src/shaderlib/index.ts
- modules/core/src/shaderlib/shadow/shadow.ts
- modules/extensions/src/collision-filter/collision-filter-effect.ts
- modules/extensions/src/terrain/terrain-effect.ts
- modules/extensions/src/terrain/utils.ts
- modules/main/src/index.ts
- modules/test-utils/src/snapshot-test-runner.ts
- test/modules/core/effects/lighting-effect.spec.ts
- test/modules/extensions/terrain/index.ts
- test/modules/extensions/terrain/terrain-cover.spec.ts
- test/modules/extensions/terrain/terrain-effect.spec.ts
- test/modules/extensions/utils.ts
- test/render/test-cases/effects.js
- test/render/test-cases/index.js
- test/render/test-cases/terrain-layer.js
For #8680
- Replace `ShaderAssembler.addDefaultModule` with a method on Deck class
- Fix shadow module minor issues
- Render tests
> Register default shader module with Deck

- .github/workflows/scorecard.yml
Fix Scorecard breaking due to not being able to sign the results. Scorecard uses Sigstore tool to sign its results and Sigstore has done an update (https://blog.sigstore.dev/tuf-root-update/). This update is not compatible with older Scorecard versions (for example, v.2.1.2 used here), but Scorecard v2.3.1 is compatible with Sigstore changes.
- Update scorecard from v2.1.2 to v2.3.1
> Bug fix: Update scorecard to v2.3.1

- modules/core/src/scripting/map-wrapper.ts
- Explicitly pass `container` to Map constructor
> fix(core): base map creation error in DeckGL scripting interface

- modules/aggregation-layers/src/aggregation-layer.ts
- modules/core/src/index.ts
- modules/main/src/index.ts
The public API of the aggregation-layers module depends on a type that isn't exported from the core module. I've made the quick fix here to export that type, resolving the error:
```
node_modules/@deck.gl/aggregation-layers/dist/aggregation-layer.d.ts:16:29:
16 │ ...ring]: import("modules/core/src/lib/attribute/attribute").default;
╵                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This PR changes the the compiled types in `aggregation-layer.d.ts`:
```diff
-    getAttributes(): {
-        [id: string]: import("modules/core/src/lib/attribute/attribute").default;
-    };
+    getAttributes(): {
+        [id: string]: Attribute;
+    };
```
But this looks like the type of issue that could also possibly be fixed by a TS update or some of the types error detection that …
> fix(aggregation-layers): Fix missing types export

- modules/carto/src/api/request-with-parameters.ts
- modules/carto/src/sources/base-source.ts
- test/modules/carto/api/request-with-parameters.spec.ts
- test/modules/carto/index.ts
- test/modules/carto/mock-fetch.ts
Related:
- #8648
Adds unit tests for `requestWithParameters`.
`requestWithParameters()` does not include the given `accessToken` in the request, but appends it to the response body. This behaves confusingly with the cache — a second caller may get the first caller's access token — and only one caller to `requestWithParameters()` currently provides that parameter, so I've removed the access token parameter and applied it in the calling function instead.
***
OUTDATED: ~~While requestWithParameters() caches unique requests, it should apply accessToken and errorContext separately for each invocation, regardless of whether separate requests were made.~~
> fix(carto): Clean up and add unit tests for requestWithParameters cache

- modules/core/src/scripting/lumagl.ts
https://github.com/visgl/deck.gl/pull/8574 in v9 limited luma.gl exports only to a few selected classes. There is a removed TODO "Cherry-pick luma core exports that are relevant to deck". Following this reasoning, can we export BufferTransform as well? It's used in GPUInterpolationTransition.
My need for it is driven by a custom layer in a pure-JS environment, where deck.gl is imported with a script tag. As parts of luma.gl are still exported, it seems this case is still supported. Otherwise it would be necessary to import a full luma.gl bundle with a matching version.
- Export BufferTransform from luma.gl
> Export BufferTransform from luma.gl

- examples/gallery/src/boiler-plate-arcgis.html
- examples/get-started/pure-js/arcgis/app.js
- modules/arcgis/package.json
- modules/arcgis/src/commons.ts
- modules/arcgis/src/deck-layer-view-2d.ts
- modules/arcgis/src/deck-renderer.ts
- yarn.lock
For #8710
- Remove dependency on `@luma.gl/webgl`, use Deck's `onDeviceInitiated`
- Handle async resource creation
- Remove `withParametersWebGL`, use v9 string parameters
> fix(arcgis): remove dependency on @luma.gl/webgl

- website/package.json
- website/yarn.lock
Overly aggressive dependency trimming in #8646
- Restore dependency `react-virtualized-auto-sizer` (required by playground)
> chore: fix website build

- modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.ts
For #8751 
- Remove ad-hoc handling of attributes/parameters/module settings; populate `this.state.models` to use the base layer's default behavior
Tested: website scenegraph example (instanced); documentation embedded example (animated); Google 3D tiles example (non-instanced)
> fix(mesh-layers): ScenegraphLayer picking

- bindings/pydeck/requirements/requirements-dev.txt
Partial fix for #8469. Runtime errors remain, but pinning to jupyterlab <4 is required to build in any case.
> fix(pydeck): Pin 'jupyterlab' dependency to v3.x

- modules/arcgis/src/commons.ts
- modules/core/src/index.ts
- modules/core/src/lib/deck.ts
- modules/core/src/lib/effect.ts
- modules/core/src/lib/layer-manager.ts
- modules/core/src/lib/tooltip.ts
- modules/core/src/lib/view-manager.ts
- modules/core/src/lib/widget-manager.ts
- modules/google-maps/src/google-maps-overlay.ts
- modules/mapbox/src/deck-utils.ts
- modules/react/src/deckgl.ts
- modules/react/src/utils/position-children-under-views.ts
- modules/test-utils/src/test-runner.ts
- modules/widgets/src/compass-widget.tsx
- modules/widgets/src/fullscreen-widget.tsx
- modules/widgets/src/zoom-widget.tsx
- Deck class generic parameter `ViewsT` should default to `null` (matches default `props.views`)
- Tightening the type for `viewState`/`initialViewState`: only use id-to-state map if `ViewsT` is an array
Before, very confusing hints:
After:
With a single non-map view:
With multiple views:
> Improve view types

- modules/react/src/deckgl.ts
`FunctionComponent.defaultProps` has been deprecated by React. `DeckGL.defaultProps` was removed in #8763 without providing fallbacks causing the canvas to be 0x0.
- Use React's recommended approach to supply default width and height
> fix(react) component default size

- .github/pull_request_template.md
The PR template tells users to use "For #" but that won't work with GitHub linked issues:
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
- Change PR template from "For #" to "Closes #"
- Restructure PR template for readability
> Update PR template for linked-issues

- modules/core/src/lib/deck.ts
Closes #8768
- Do not remove canvas if using user-supplied `gl`
> fix(core): Deck.finalize removes externally created canvas

- bindings/pydeck/pydeck/io/html.py
Appears to have been a typo in https://github.com/visgl/deck.gl/pull/8034. Boolean values of 'tooltip' should be converted to JavaScript booleans, all other values should be returned as-is. With this change, pydeck is now working locally when using 'to_html'. With 'show' I'm still seeing errors running locally related to bindings, but this is enough to make more progress on Deck v9 support.
> fix(pydeck): Fix pydeck tooltip serialization

- docs/upgrade-guide.md
Closes #8793 
- docs/update-guide.md
+ in `@deck.gl/mapbox` section
* DeckOverlay should be replaced to MapboxOverlay
> chore(docs): should use MapboxOverlay instead of DeckOverlay

- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/website.yml
- test/modules/geo-layers/mvt-layer.spec.js
- test/modules/geo-layers/tile-3d-layer/tile-3d-layer.spec.js
Intended to isolate cause of failing tests in https://github.com/visgl/deck.gl/pull/8786 on the v8.9 release branch. This PR updates the CI to supported node.js versions, and disables a couple of tests that currently pass in the browser but fail in node.js.
> chore(ci): Update node.js in CI for v8.9 release branch

- bindings/pydeck-carto/pydeck_carto/layer.py
- bindings/pydeck/pydeck/frontend_semver.py
- bindings/pydeck/pydeck/io/html.py
- bindings/pydeck/requirements/requirements-dev.txt
- modules/carto/bundle.ts
Patch for the `8.9-release` branch, restoring a missing global for the pydeck-carto integration. I've included some known fixes added since the last release as well.
Related:
- https://github.com/visgl/deck.gl/pull/7546 (global export lost here)
- #8756
- #8780
> fix(pydeck-carto): Fix missing global for pydeck-carto in 8.9 release

- bindings/pydeck-carto/Makefile
- bindings/pydeck-carto/examples/scripts/carto_layer_geo_query.py
- bindings/pydeck-carto/examples/scripts/carto_layer_geo_query_param.py
- bindings/pydeck-carto/examples/scripts/carto_layer_geo_table.py
- bindings/pydeck-carto/examples/scripts/carto_layer_geo_tileset.py
- bindings/pydeck-carto/examples/scripts/carto_layer_h3_query.py
- bindings/pydeck-carto/examples/scripts/carto_layer_h3_table.py
- bindings/pydeck-carto/examples/scripts/carto_layer_h3_tileset.py
- bindings/pydeck-carto/examples/scripts/carto_layer_quadbin_query.py
- bindings/pydeck-carto/examples/scripts/carto_layer_quadbin_table.py
- bindings/pydeck-carto/examples/scripts/carto_layer_quadbin_tileset.py
- bindings/pydeck-carto/examples/scripts/carto_styles_color_bins.py
- bindings/pydeck-carto/examples/scripts/carto_styles_color_categories.py
- bindings/pydeck-carto/examples/scripts/carto_styles_color_continuous.py
- bindings/pydeck-carto/examples/scripts/hello_world.py
- bindings/pydeck-carto/pydeck_carto/sources.py
- bindings/pydeck-carto/tests/test_sources.py
PR targets branch of https://github.com/visgl/deck.gl/pull/8577.
Changes:
- add `make test-scripts` macro for quickly testing pydeck-carto examples
- update example scripts to output HTML in the scripts directory, for testing with `npx serve`
- update H3, quadbin, and styling examples for deck v9
- miscellaneous fixes for CARTO sources in pydeck-carto
> feat(pydeck-carto): Update H3, Quadbin, and styling examples for deck.gl v9

- modules/main/package.json
For #8802
- Add missing sub module (arcgis)
- Add missing peer dependencies for sub modules
> fix(main): Add missing peerDependencies

- modules/extensions/src/data-filter/data-filter-extension.ts
- modules/extensions/src/data-filter/shader-module.ts
Closes #8774
- When `filterSoftRange` is truncated by `filterRange` fallback to use hard edge
> fix(extensions): DataFilterExtension handling of filterSoftRange

- modules/geo-layers/src/tile-layer/tile-layer.ts
Closes #8787
`CompositeLayer` by default auto highlights all sub layers, assuming they all share the same data. This is true for most layers except overridden in `GeoJsonLayer` (which selectively passes highlight down depending on the feature), and in tiled layers. The basic `TileLayer` does not have any knowledge of how `renderSubLayers` uses the data, therefore there isn't a default behavior that will work for every use case. However, it is safer (and more correct?) to only highlight the sub layer that is being picked, than to assume that all sublayers should be highlighted at the same picked index.
For discussion: this is technically a breaking change (bug originally introduced in a 8.8 patch #7650), is it ok to include it as a patch?
- Add picked sub layer to `TileLayerPickingInfo`
- …
> fix(geo-layers): TileLayer default autoHighlight

- modules/core/src/transitions/gpu-interpolation-transition.ts
Closes #7780
Transition was previously calculated as (equivalent to)
```
result = mix(from, to, t);
result64Low = mix(from64Low, to64Low, t);
```
Which is mathematically incorrect.
- Support double attributes in GPUInterpolationTransition
> Support fp64 in GPUInterpolationTransition

- modules/aggregation-layers/package.json
- modules/arcgis/package.json
- modules/carto/package.json
- modules/core/package.json
- modules/extensions/package.json
- modules/geo-layers/package.json
- modules/google-maps/package.json
- modules/json/package.json
- modules/jupyter-widget/package.json
- modules/layers/package.json
- modules/main/package.json
- modules/mapbox/package.json
- modules/mesh-layers/package.json
- modules/react/package.json
- modules/test-utils/package.json
Targets the `8.9-release` branch.
Previously (in #8813) the 'tag' entry was missing from modules that didn't already have a 'publishConfig' entry — 'main' and 'jupyter-widget' — which was my mistake.
Additionally, I've learned that npm enforces a rule `"Tag name must not be a valid SemVer range: v8"` when running `npm dist-tag add` but not when running `npm run publish`. So we need some sort of prefix or suffix rather than just "v8". I've opted for "v8-lts" here, matching the convention of the Angular project.
> fix(repo): Rename 'v8' release tags to 'v8-latest'

- modules/layers/src/column-layer/column-layer-fragment.glsl.ts
- modules/layers/src/solid-polygon-layer/solid-polygon-layer-fragment.glsl.ts
Closes #8411
Tested on BrowserStack, waiting for user confirmation
- Explicitly assign `geometry.uv` in the fragment shader
> fix(layers): work around Samsung shader compilation failure

- modules/core/src/passes/layers-pass.ts
Closes #8602
v8 -> v9 the undefined behavior changed to always clear
- Explicitly set `clearStencil` in LayersPass
> fix(core): explicitly set clearStencil in LayersPass

- modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator-constants.ts
- modules/aggregation-layers/src/utils/resource-utils.ts
- modules/core/src/passes/shadow-pass.ts
- modules/core/src/transitions/gpu-spring-transition.ts
- modules/extensions/src/collision-filter/collision-filter-effect.ts
- modules/extensions/src/data-filter/aggregator.ts
- modules/layers/src/icon-layer/icon-manager.ts
- test/apps/wboit/wboit-layer/wboit-layer.js
- Prep for 9.1 upgrade
- remove internal texture params
> chore: Remove internal texture parameters (v9.1)

- bindings/pydeck/pydeck/bindings/deck.py
- bindings/pydeck/tests/notebooks/test_nbconvert.py
Jupyter bindings are not currently working in pydeck, and won't make it into the pydeck v0.9 release. To make this less disorienting for users, I've made two changes here:
1. `.show()` should call `.to_html()` automatically, as it would in Colab or other environments
2. `.update()` should show a warning
This can certainly be revisited in upcoming releases, as we consider what to do about two-way bindings.
> chore(pydeck): Disable broken Jupyter bindings in v0.9

- docs/api-reference/widgets/zoom-widget.md
- modules/widgets/package.json
Closes #8862
- Adds export of widget stylesheet in `package.json`
- Removes non-existent container prop from zoom-widget documentation (unrelated, can split into individual PR if preferred)
I've tested the `import` case with the `test/apps/widget` example, I have _not_ tested the `style` case, mainly because I'm not 100% sure on the best way to do so, happy to take guidance on testing that without having to publish.
> fix(widgets): export @deck.gl/widgets/stylesheet.css

- modules/layers/src/arc-layer/arc-layer-vertex.glsl.ts
- modules/layers/src/arc-layer/arc-layer.ts
Taking advantage of our move to es300.
- Removes `positions` attribute, use `gl_VertexID` instead
- No longer rebuilds model on `numSegments` change
> feat(layers): Simplify ArcLayer

- docs/api-reference/core/attribute-manager.md
- docs/upgrade-guide.md
- modules/core/src/lib/attribute/attribute-manager.ts
- modules/core/src/lib/attribute/attribute.ts
- modules/core/src/lib/attribute/data-column.ts
- modules/core/src/lib/layer.ts
- modules/extensions/src/brushing/brushing-extension.ts
- modules/extensions/src/brushing/shader-module.ts
- modules/extensions/src/collision-filter/collision-filter-extension.ts
- modules/extensions/src/collision-filter/shader-module.ts
- modules/extensions/src/data-filter/data-filter-extension.ts
- modules/extensions/src/data-filter/shader-module.ts
- modules/extensions/src/fill-style/fill-style-extension.ts
- modules/extensions/src/fill-style/shader-module.ts
- modules/layers/src/solid-polygon-layer/solid-polygon-layer-vertex-main.glsl.ts
- modules/layers/src/solid-polygon-layer/solid-polygon-layer-vertex-side.glsl.ts
- modules/layers/src/solid-polygon-layer/solid-polygon-layer-vertex-top.glsl.ts
- modules/layers/src/solid-polygon-layer/solid-polygon-layer.ts
- test/modules/core/lib/attribute/attribute-manager.spec.ts
- test/modules/core/lib/attribute/attribute.spec.ts
Closes #8849
This proposed fix adds a `stepMode` attribute setting. If set to `dynamic`, it will be resolved to one of `vertex` and `instance` based on whether the target model is instanced. With this change I'm able to remove much redundancy from layers/extensions where the same buffer is shared between instanced and non-instanced models.
- Remove `divisor` from attribute and shader attribute settings. While this is a breaking change,
+ Setting it does nothing as of v9.0
+ Moving forward, we won't be able to make it work exactly like v8, due to luma API changes
+ Most custom layers use `AttributeManager.add` and `AttributeManager.addInstanced` instead of explicitly setting `divisor`, so the impact will be low
- Add `stepMode` to attribute settings
- SolidPolygonLayer
- BrushingExtension …
> feat(core): Explicitly set stepMode in Attribute layout

- bindings/pydeck/docs/contributing.rst
- bindings/pydeck/pydeck/io/html.py
Currently when using Pydeck in Google Colab, the `iframe_height` argument sets the minimum height, the iframe renders at that height, and then it incrementally becomes taller until reaching the maximum cell height allowed by colab, 1000px:
[colab_height_bug.webm](https://github.com/visgl/deck.gl/assets/1848368/cc1223e9-40c6-4998-a2e9-ac3eb7b6b9fe)
I believe this is the fix, but haven't found a way to test local builds against Google Colab environments yet. I'll look a bit more into that, and perhaps test on an alpha release if that's not possible. Perhaps there's also some CSS padding or margin contributing to the problem.
- Set both minHeight and maxHeight in Google Colab cell size
> fix(pydeck): Fix cell height in Google Colab

- modules/carto/src/api/request-with-parameters.ts
- modules/carto/src/utils.ts
- test/modules/carto/utils.spec.ts
Loading the latest version of pydeck-carto in a Python notebook environment, a function imported from `@loaders.gl/core` is not available, and throws an error when calling requestWithParameters:
There's some nuance in how the Python packages load dependencies from CDNs, which could benefit from a closer look, but in the meantime ... the function is very short, and maybe importing it from `@loaders.gl/core` is unnecessary. To resolve the bug, I've copied `isObject` and `isPureObject` into the CARTO module, both are one-liners.
Publishing a patch release of `@deck.gl/carto` will be enough to fix the bug — pydeck-carto does not require an update.
- https://github.com/visgl/deck.gl/pull/8865
- Copies `isObject` and `isPureObject` from `@loaders.gl/core`
- Updates unit tests
> fix(pydeck-carto): Use local isPureObject

- modules/google-maps/src/google-maps-overlay.ts
Closes #8891
Seems like with raster basemaps, initial render happens when canvas is not yet attached to any parent.
This patch ensures that we use _declared_ canvas parent, even before canvas is attached to DOM.
- GoogleMapsOverlay fix initial layer position on raster basemaps
> GoogleMapsOverlay: fix initial layer position on raster basemaps

- modules/carto/package.json
- yarn.lock
Updates the `cartocolor` dependency (color palettes) to v5.0.0.
Changes in `cartocolor`:
- Update license to [Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/)
- Add ESM and CJS builds
> chore(carto): Update cartocolor to v5

- docs/api-reference/carto/overview.md
- docs/api-reference/carto/quadbin-heatmap-tile-layer.md
- docs/table-of-contents.json
- modules/carto/src/layers/heatmap.ts
- modules/carto/src/layers/quadbin-heatmap-tile-layer.ts
Documentation update for https://github.com/visgl/deck.gl/pull/8703
> CARTO: QuadbinHeatmapTileLayer docs

- modules/carto/package.json
- test/apps/carto-dynamic-tile/package.json
- yarn.lock
Pulls in a fix for the cartocolor module, and adds the missing `maplibre-gl` dependency in the carto-dynamic-tile test app. Confirmed rendering as expected:
> fix(deps): Update deps for deck.gl/carto and test app

- modules/carto/src/api/carto-api-error.ts
- modules/carto/src/api/request-with-parameters.ts
- test/modules/carto/api/request-with-parameters.spec.ts
In case of errors, Carto APIs return information that is useful for applications and now we almost completly hide it in new sources. This PR exposes whole response in `CartoAPIError.responseJson` property.
(note, we do expose `response` object, but we can't get full json content as it was already consumed in `requestWithParameters`)
- feat(carto): requestWithParameters to store received json response in CartoAPIError
> feat(carto): requestWithParameters to store received json response in CartoAPIError

- modules/carto/src/layers/quadbin-heatmap-tile-layer.ts
QuadbinHeatmapLayer does not yet handle props inherited from its parent types. This PR updates `renderLayers` to handle QuadbinHeatmapLayer's own props explicitly, then pass anything left over into the PostProcessQuadbinTileLayer props.
> fix(carto): Support QuadbinHeatmapTileLayer onViewportLoad callback

- modules/carto/src/api/common.ts
- modules/carto/src/api/request-with-parameters.ts
- test/modules/carto/api/query.spec.ts
- test/modules/carto/api/request-with-parameters.spec.ts
- test/modules/carto/sources/boundary-query-source.spec.ts
- test/modules/carto/sources/boundary-table-source.spec.ts
- test/modules/carto/sources/h3-query-source.spec.ts
- test/modules/carto/sources/h3-table-source.spec.ts
- test/modules/carto/sources/h3-tileset-source.spec.ts
- test/modules/carto/sources/quadbin-query-source.spec.ts
- test/modules/carto/sources/quadbin-table-source.spec.ts
- test/modules/carto/sources/quadbin-tileset-source.spec.ts
- test/modules/carto/sources/raster-source.spec.ts
- test/modules/carto/sources/vector-query-source.spec.ts
- test/modules/carto/sources/vector-table-source.spec.ts
- test/modules/carto/sources/vector-tileset-source.spec.ts
Changes:
- If `requestWithParameters` base URL conflicts with given parameters, override base URL
- Use URLSearchParams API to merge non-conflicting parameters cleanly
- Move `DEFAULT_PARAMETERS` and `DEFAULT_HEADERS` to local constants in `request-with-parameters.ts`. When adding new `DEFAULT_PARAMETERS` we need to be careful of the precedence (user params > default params > base url params) and that information is clearer in context.
- Update unit tests, since `URLSearchParams#toString` handles whitespace and trailing slashes differently than the previous URL building logic.
> fix(carto): Resolve conflicts between base URL and parameters

- modules/carto/src/layers/vector-tile-layer.ts
- modules/geo-layers/src/mvt-layer/mvt-layer.ts
- test/modules/carto/layers/vector-tile-layer.spec.ts
Changes:
- feat(geo-layers): Expose protected method, _isWGS84
- chore(carto): Use _isWGS84 to avoid building picking info twice
Related:
- https://github.com/visgl/deck.gl/pull/8926
> feat(geo-layers): Allow layers extending MVTLayer to override isWGS84

- docs/get-started/using-with-react.md
Quick fix for invalid code in `Using deck.gl with React` - object in an array was suffixed with a semicolon, which is invalid syntax.
- `docs/get-stated/using-with-react.md` - small syntax fix in code example
> fix(docs): fix invalid code syntax in Using deck.gl with React

- modules/aggregation-layers/src/aggregation-layer-v9/aggregation-layer.ts
- modules/aggregation-layers/src/aggregation-layer-v9/aggregator.ts
- modules/core/src/lib/composite-layer.ts
- modules/core/src/lib/layer.ts
- modules/core/src/passes/layers-pass.ts
For #7457
The goals of this refactor:
- Unified Aggregator interface for both GPU aggregation and CPU aggregation
- Simplified Aggregator and AggregationLayer classes that no longer concern:
+ Different props.data formats (iterable, non-iterable, binary...)
+ Projection systems
+ Specific prop names and update triggers
- Fully typed and extensively documented
Planned PRs:
- Aggregator and AggregationLayer 
- GPUAggregator
- CPUAggregator
- ScreenGridLayer
- GridLayer
- HexagonLayer
- ContourLayer
- Remove legacy code
- New `Aggregator` interface
- New `AggregationLayer` abstract class
- Add `isDrawable` to `Layer` class to decouple `isComposite` from drawing behavior. `AggregationLayer` is a composite layer (renders sublayers) but also participate in the draw cycle.
> GPU Aggregation (1/8): Aggregator and AggregationLayer

- modules/carto/src/layers/heatmap-tile-layer.ts
Follow up to #8703 
`t.data` can return a Promise if the content isn't yet loaded, leading to a crash
- Use tile.content rather than tile.data to avoid Promise
> fix(carto): Use tile.content in HeatmapTileLayer

- modules/carto/package.json
- modules/carto/src/api/parse-map.ts
No particular urgency here, but seemed good to update the blending code for WebGPU and this was the last reference to `@luma.gl/constants` in the package. 
~~Tests pass but I want to check the rendering results locally and haven't done that yet; marking as draft in the meantime.~~ Checked against #8957.
> chore(carto): Remove dependency on @luma.gl/constants

- modules/extensions/src/data-filter/data-filter-extension.ts
Closes #8937
The category filter uniform is only set once on prop change. `IconLayer` and `ScenegraphLayer` have conditional draw calls where `uniforms` are not applied until the texture loads.
- `DataFilterExtension` should set the necessary uniforms in every draw call
> fix(extensions): DataFilterExtension not setting category uniforms

- modules/core/src/lib/layer.ts
Closes #8936
- Avoid clearing picking module's `highlightedObjectColor` on `highlightColor` change
> Fix highlightedObjectIndex

- docs/api-reference/test-utils/overview.md
- modules/test-utils/src/utils/setup-gl.ts
- test/node.ts
Closes #8912
- Allow layer tests to run without WebGLDevice
> fix(test-utils): run layer tests in Node

- modules/layers/src/geojson-layer/geojson-layer.ts
- modules/layers/src/polygon-layer/polygon-layer.ts
Simply corrects an incorrect type description for GeoJSONlayer and PolygonLayer typings.
- modules/layers/src/geojson-layer/geojson-layer.ts
- - ln. 125
- modules/layers/src/geojson-layer/polygon-layer.ts
- - ln. 170
> Fixes line width default type description for geo and polygon layers

- modules/carto/src/layers/schema/carto-tile.ts
Bug where 64bit positions were converted to 32bit
- Do not reduce position precision to 32bit
> CARTO: do not reduce position precision to 32bit

- docs/api-reference/carto/data-sources.md
In https://github.com/visgl/deck.gl/pull/8971 we removed a `matchingColumn` prop from the CARTO module, specifically for the `boundaryQuerySource` and `boundaryTableSource`. 
We need to reflect this in the API reference documentation
- Remove `matchingColumn` from the CARTO sources API reference
- Add a small comment to guide developers when using Boundary sources
> docs(CARTO): remove matching column prop from API reference

- modules/extensions/src/data-filter/data-filter-extension.ts
- modules/extensions/src/data-filter/shader-module.ts
- modules/test-utils/src/index.ts
- modules/test-utils/src/utils/layer.ts
- test/modules/extensions/data-filter.spec.ts
- test/modules/layers/geojson-layer.spec.ts
- test/modules/layers/scatterplot-layer.spec.ts
For https://github.com/visgl/deck.gl/issues/8997 tested with `examples/website/data-filter` & `test/apps/data-filter`
- Add uniformBlock definition
- Rename variables in shader
- Change module names to avoid dash
- Generate `unifromTypes` dynamically using `unifromTypesFromOptions()`
- Test updates
> DataFilterExtension UBOs

- docs/api-reference/widgets/compass-widget.md
- docs/api-reference/widgets/zoom-widget.md
- modules/widgets/src/compass-widget.tsx
- modules/widgets/src/zoom-widget.tsx
- test/apps/widgets/app.js
- test/apps/widgets/package.json
Follow up on https://github.com/visgl/deck.gl/pull/8903#discussion_r1606873870
The intended design of the `viewId` prop is:
- If a `viewId` prop is defined by a user, the widget is placed in that view (i.e. a mini-map) and changes that view.
- Otherwise, the widget is considered "multi-view"; it is placed in the root widget container and should change all views.
This PR implements this second bullet. Currently, a widget with an undefined `viewId` behaves in an unintuitive way: it affects the last viewport that changed.
- Zoom and Compass widgets affect all views if not attached to specific view
- docs
> feat(widgets) affect all views if not attached to specific view

- modules/aggregation-layers/src/heatmap-layer/heatmap-layer.ts
Closes #8960
`weights.buffer` is `null` if weight is a constant.
Note that HeatmapLayer is not working on master due to UBO work (#8997).
This patch has been tested on the `9.0-release` branch.
- HeatmapLayer handles constant attribute when updating weight map.
> fix(geo-layers): HeatmapLayer crash with constant weight

- modules/mapbox/src/mapbox-overlay.ts
Closes # none
when use mapbox function   `map.addControl(deckOverlay);`
versions:    
"mapbox-gl": "^3.5.1",
"@deck.gl/mapbox": "^9.0.21",
Parameters of type 'MapboxOverlay' cannot be assigned to parameters of type 'IControl'.
Among these types, the types returned by "getDefultPosition()" are incompatible.
Type 'string' cannot be assigned to type 'ControlPosition'.
- mapbox-overlay.ts
> fix: mapboxOverlay's getDefaultPosition return type error

- modules/main/package.json
Publish is [failing](https://github.com/visgl/deck.gl/actions/runs/9927550385/job/27422646792), possibly due to how `$_` behaves when its invoked by a script. Its possible that `$_` overrides the script.
- build script
> fix(main) copy css explicitly

- docs/api-reference/widgets/compass-widget.md
- docs/api-reference/widgets/fullscreen-widget.md
- docs/api-reference/widgets/zoom-widget.md
- modules/widgets/src/compass-widget.tsx
- modules/widgets/src/fullscreen-widget.tsx
- modules/widgets/src/zoom-widget.tsx
> fix(widgets) widget id was required, should be optional

- modules/aggregation-layers/src/heatmap-layer/heatmap-layer.ts
Fixes regression introduced by https://github.com/visgl/deck.gl/pull/8782
- Add `project32` module to heatmap shaders
- Update project shaderInputs when updating weightmap
> HeatmapLayer fix to work with project UBO

- modules/carto/src/layers/heatmap-tile-layer.ts
- modules/carto/src/layers/raster-layer-vertex.glsl.ts
- modules/carto/src/layers/raster-layer.ts
- Update Raster shader to use `ColumnLayer` UBOs
- Pass density in `RTTSolidPolygonLayer` via UBO
> carto module UBO

- modules/core/src/effects/post-process-effect.ts
- modules/core/src/passes/screen-pass-uniforms.ts
- modules/core/src/passes/screen-pass.ts
- modules/core/src/transitions/gpu-interpolation-transition.ts
- modules/core/src/transitions/gpu-spring-transition.ts
- Add UBOs for `ScreenPass` & tidy types
- Add UBOs for GPU transitions
> core module UBO

- modules/carto/src/layers/vector-tile-layer.ts
Related to https://github.com/visgl/deck.gl/issues/9059. Rather than fix the accuracy issue, we simply do not clip point layers, as it shouldn't be necessary anyway.
- Only clip polygon/line layers in `VectorTileLayer`
> CARTO: Only clip polygon/line layers

- modules/carto/src/layers/raster-layer.ts
- modules/carto/src/layers/raster-tile-layer.ts
- modules/carto/src/layers/spatial-index-tile-layer.ts
- modules/carto/src/utils.ts
- test/apps/carto-dynamic-tile/app.tsx
- test/apps/carto-dynamic-tile/datasets.ts
Closes https://github.com/visgl/deck.gl/issues/9045
Because of the low-level data format used, picking was not working
https://github.com/user-attachments/assets/a5d8d0f0-e6d4-40ec-9bca-565aca7aa329
- No longer extends `SpatialIndexTileLayer` as no functionality used
- Custom `_updateAutoHighlight` that works directly with index
- Generate correct object in `getPickingInfo`
- Improve `createBinaryProxy` so that `Object.keys(object.properties)` et al work
> CARTO: Implement picking & autohighlight in RasterLayer

- modules/core/src/index.ts
- modules/core/src/lib/layer.ts
- modules/core/src/shaderlib/index.ts
- modules/core/src/shaderlib/misc/uniform-types.ts
- modules/core/src/shaderlib/shadow/shadow.ts
- modules/extensions/src/clip/clip-extension.ts
- modules/extensions/src/collision-filter/shader-module.ts
- modules/extensions/src/mask/shader-module.ts
- test/modules/core/shaderlib/shadow/shadow.spec.ts
- Add UBOs for `shadow` module
- Remove residual `UniformTypes` instances
> shadow module UBO

- modules/aggregation-layers/src/heatmap-layer/heatmap-layer-uniforms.ts
- modules/aggregation-layers/src/heatmap-layer/heatmap-layer-utils.ts
- modules/aggregation-layers/src/heatmap-layer/heatmap-layer.ts
- modules/aggregation-layers/src/heatmap-layer/max-vs.glsl.ts
- modules/aggregation-layers/src/heatmap-layer/triangle-layer-fragment.glsl.ts
- modules/aggregation-layers/src/heatmap-layer/triangle-layer-uniforms.ts
- modules/aggregation-layers/src/heatmap-layer/triangle-layer-vertex.glsl.ts
- modules/aggregation-layers/src/heatmap-layer/triangle-layer.ts
- modules/aggregation-layers/src/heatmap-layer/weights-vs.glsl.ts
- Port `HeatmapLayer` and supporting layers to UBO
> HeatmapLayer UBO

- package.json
8.9 branch is missing `yarn publish-prod` commands making it impossible to publish new packages via CI
- Copy across changes from https://github.com/visgl/deck.gl/pull/8828
- Copy .github workflows from master branch
- Add volta definition to package.json
- Fix type
> CI release on 8.9-release branch

- modules/carto/src/layers/heatmap-tile-layer.ts
- modules/carto/src/layers/heatmap.ts
- modules/core/src/passes/screen-pass.ts
Followup to https://github.com/visgl/deck.gl/pull/8703
Previous version only supported 6 colors in color map via explicit unifroms. With this change a `colorTexture` is used instead, like in the `HeatmapLayer` to provide an unlimited number of colors
- Generate `colorTexture` from passed `colorRange` in Layer
- Replace `colorRange` with `colorTexture` in shader module
> CARTO: HeatmapTileLayer full colorRange

- modules/carto/src/layers/cluster-tile-layer.ts
- modules/carto/src/layers/cluster-utils.ts
`TileLayer` keeps the `tile` instances even when reloading all the tiles. Thus the tile aggregation needs to check if the properties change and re-aggregate the data if they have
- Re-aggregate on change of properties
- Pass through `needsUpdate` to force re-render
> CARTO: Re-aggregate properties on change

- modules/carto/src/layers/cluster-tile-layer.ts
- modules/carto/src/layers/cluster-utils.ts
- modules/carto/src/style/color-bins-style.ts
- modules/carto/src/style/color-categories-style.ts
- modules/carto/src/style/color-continuous-style.ts
- modules/carto/src/style/utils.ts
Followup to https://github.com/visgl/deck.gl/pull/8957
- Move `stats` from feature to `data.attributes`
- Update color helpers to pass through `objectInfo`
> CARTO: Move cluster stats into data.points.attributes

- modules/mapbox/src/resolve-layers.ts
Closes #9086
Tested with [get-started/pure-js/mapbox](https://github.com/visgl/deck.gl/tree/master/examples/get-started/pure-js/mapbox)
- Handle new return type of `map.getLayer()`
> fix(mapbox): interleaved mode in Mapbox@3.6.0

- docs/developer-guide/custom-layers/subclassed-layers.md
Closes #9106
There is an [example](https://deck.gl/docs/developer-guide/custom-layers/subclassed-layers#overriding-attribute-calculation) in the documentation for Subclassed Layers which implements a multi coloured path layer, it is broken with version 9 of deck.gl.
The changes I have made fix the code in my case.
- fix the broken example in the documentation
> Docs: Fix Subclassed Layers example

- docs/developer-guide/base-maps/using-with-google-maps.md
The useMemo for the GoogleMapsOverlay creation was missing an empty dependency array so it was being re-created on every render and thus failing to render anything.
- Adds a missing empty dependency array in some Google Maps example code
> fix DeckGLOverlay example for Google Maps

- modules/aggregation-layers/src/common/aggregator/gpu-aggregator/webgl-aggregation-transform.ts
- test/modules/aggregation-layers/common/webgl-aggregator.spec.ts
For https://github.com/visgl/deck.gl/pull/8887#discussion_r1738284310
Tested on M2. Thanks @felixpalmer for the insight.
- Avoid interpolating NaNs
> Fix GPUAggregator on M chips

- examples/layer-browser/src/examples/aggregation-layers.js
https://github.com/visgl/deck.gl/pull/9100 removed `CPUGridLayer`/`GPUGridLayer`
- Fix layer browser to work with only `GridLayer`
> Fix layer browser

- docs/api-reference/aggregation-layers/screen-grid-layer.md
- modules/aggregation-layers/src/common/utils/bounds-utils.ts
- modules/aggregation-layers/src/contour-layer/contour-layer.ts
- modules/aggregation-layers/src/grid-layer/grid-layer.ts
- modules/aggregation-layers/src/hexagon-layer/hexagon-layer.ts
- modules/aggregation-layers/src/screen-grid-layer/screen-grid-cell-layer.ts
- modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer-fragment.glsl.ts
- modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer-vertex.glsl.ts
- modules/aggregation-layers/src/screen-grid-layer/screen-grid-layer.ts
- test/apps/aggregator/app.ts
- test/apps/aggregator/histogram-layer.ts
- test/apps/aggregator/index.html
- test/apps/aggregator/package.json
- test/modules/aggregation-layers/screengrid-cell-layer.spec.ts
- Extract common `getBinIdRange` util
- Align ScreenGridLayer's `colorRange` behavior with the other layers
- Add a test app (used for validating example code in docs)
> GPU Aggregation: miscellaneous clean up

- docs/api-reference/geo-layers/tile-layer.md
- modules/geo-layers/src/tileset-2d/tileset-2d.ts
Closes [#9155](https://github.com/visgl/deck.gl/issues/9155)
It is sometimes desirable to disable the cache of TileLayer.
- 0 values are now possible for maxCacheSize and maxCacheByteSize by using nullish coalescing and non-strict comparison with null.
> Allow 0s for maxCacheSize and maxCacheByteSize

- bindings/pydeck-carto/pydeck_carto/sources.py
Correction to documentation, where 'aggregation_exp' was incorrectly marked as optional.
> docs(pydeck-carto): Indicate that aggregation_exp is required

- modules/carto/src/layers/cluster-tile-layer.ts
- modules/carto/src/layers/cluster-utils.ts
ClusterTileLayer was relying on `Tile` instances to be new or cleared or reset when new tile is loaded and used `tile.userData` as cache. It appears, that reloading tile doesn't instantiate new tile ... or retains `userData` and thus new tile would reuse aggregations from old version of self.
Fix creates separate cache in layer state to keep aggregations keyed by tile content. 
- carto: Fix caching in cluster tile layer
> carto: Fix caching in ClusterTileLayer

- modules/aggregation-layers/src/common/aggregator/gpu-aggregator/aggregation-transform-uniforms.ts
- modules/aggregation-layers/src/common/aggregator/gpu-aggregator/webgl-aggregation-transform.ts
Avoid sending NaN as uniform as it is believed to cause issues in some browsers.
Int value `-1` (all ones) is NaN when interpreted as float32: https://en.wikipedia.org/wiki/Single-precision_floating-point_format#Exponent_encoding
According [intBitsToFloat](https://registry.khronos.org/OpenGL-Refpages/gl4/html/intBitsToFloat.xhtml) this solution may subject to GPU-specific behavior:
> If the encoding of a NaN is passed in x, it will not signal and the resulting value will be undefined.
- Avoid sending NaN as uniform.
> Remove NaN uniform

- docs/api-reference/core/controller.md
- docs/api-reference/core/deck.md
- docs/upgrade-guide.md
- examples/vite.config.local.mjs
- modules/core/package.json
- modules/core/src/controllers/controller.ts
- modules/core/src/lib/constants.ts
- modules/core/src/lib/deck.ts
- modules/core/src/lib/widget-manager.ts
- package.json
- scripts/postinstall.sh
- test/modules/core/controllers/controllers.spec.ts
- test/modules/core/controllers/test-controller.ts
- test/modules/core/lib/widget-manager.spec.ts
- yarn.lock
- Upgrade mjolnir.js to v3, remove postinstall hack script that fixes hammer.js
- Update Deck class to use v3 API - mjolnir's EventManager no longer comes with preset recognizers, they need to be explicitly defined
- `tripan` event is changed to `multipan` and requires two fingers instead of three
- Docs & upgrade guide
> Upgrade mjolnir.js to v3

- tsconfig.json
See #9183
Input:
```ts
export default class Deck {
static defaultProps = defaultProps;
static VERSION = VERSION; 
}
```
Output targeting ES2022:
```js
export default class Deck {
static { this.defaultProps = defaultProps; }
static { this.VERSION = VERSION; }
}
```
Output targeting ES2020:
```js
class Deck {
}
Deck.defaultProps = defaultProps;
Deck.VERSION = VERSION;
export default Deck;
```
> Move publish target to es2020

- modules/carto/src/api/layer-map.ts
- modules/carto/src/api/parse-map.ts
- modules/carto/src/api/types.ts
- test/modules/carto/api/parse-map.spec.ts
Followup to https://github.com/visgl/deck.gl/pull/8703 to add support in `fetchMap`
- Support `colorRange`, `radiusPixels` and `getWeight` in `parseMap`
- Update tests
> CARTO: parseMap support for HeatmapTileLayer

- modules/core/src/index.ts
- modules/core/src/shaderlib/index.ts
- test/modules/aggregation-layers/hexbin.spec.ts
- test/modules/core/shaderlib/project/project-32-64-glsl.spec.ts
- test/modules/core/shaderlib/project/project-functions.spec.ts
- test/modules/core/shaderlib/project/project-glsl-test-utils.ts
- test/modules/core/shaderlib/project/project-glsl.spec.ts
Remove remaining instances of `setUniforms` in tests
- Port `hexbin` & `project` spec tests, adding UBOs to replace individual uniforms
- Export `ProjectProps` type
- Add typing
- Rename & tidy to match new conventions
> Convert tests to use UBOs

- docs/developer-guide/custom-layers/layer-extensions.md
- docs/developer-guide/custom-layers/layer-lifecycle.md
- docs/table-of-contents.json
- Update custom layer & layer extension guides
- Add missing link to TOC
> docs: Update to use UBOs rather than setUniforms

- modules/carto/src/layers/raster-layer.ts
Fix performance regression in Carto's RasterLayer caused by unnecessary buffer updates.
RasterLayer wraps `data` passed to ColumnLayer in temporary object and by default this was detected as data change in all ColumnLayers on each layer update (like opacity).
- carto: RasterLayer doesn't update buffers on each render
> carto: RasterLayer fix perf issue caused by spurious data changes

- modules/core/src/lifecycle/create-props.ts
Closes #9206
Change List
- create-props.ts Changed `createPropsPrototypeAndTypes` to bail out if the parent class of the passed component class is the global function prototype so that it doesn't get polluted.
There may well be a better and cleaner way to do this, but this fixes the bug I'm experiencing.
Note that I was not able to get tests to run locally or on my fork via Github Actions, but the errors appear unrelated to my changes and seem to be occurring on some workflow runs on the main repo.
P.S. deck.gl is an absolutely amazing piece of software!
> Avoid adding props to global function prototype. Doing so breaks the react-three-fiber reconciler

- modules/carto/src/layers/raster-layer-vertex.glsl.ts
- test/apps/carto-dynamic-tile/app.tsx
The cells were being positioned incorrectly, see comparison with tile bounds:
- Fix off by one error introduced by axis inversion
- Fix import in test app
> CARTO: Fix off-by-one raster vertex shader error

- docs/developer-guide/views.md
Fix for a syntax error in the `layerFilter` function in the [Views Developer Guide](https://deck.gl/docs/developer-guide/views).
> website: Fix Syntax Error in layerFilter 

- modules/core/src/lib/layer.ts
- modules/layers/src/geojson-layer/geojson-binary.ts
- modules/layers/src/geojson-layer/geojson-layer-props.ts
- test/bench/layer.bench.js
- test/modules/layers/data/fixtures.ts
The `instancePickingColors` attribute has some hard-coded assumptions about size, such as...
https://github.com/visgl/deck.gl/blob/27d2010790691dae7589f537ff1cfd39c1b1d0b6/modules/core/src/lib/layer.ts#L879-L882
... but MVTLayer currently initializes the buffer with 3, not 4, components. This leads to a bug in `pickMultipleObjects` where `disablePickingIndex` fails to disable the previously selected object index (or goes out of bounds) and the operation just returns `depth` duplicate references to the top hit.
While we could try to handle multiple attribute sizes, I think it's probably preferable to just have one way to represent things. Here I've switched MVTLayer to 4-component picking colors, following [WebGL's 4-byte alignment best …
> fix(layers): Fix MVTLayer + pickMultipleObjects

- examples/website/scenegraph/app.tsx
Currently the scenegraph example makes infinite continuous requests for `all.json` locally for me. On the production website I'm not seeing anything because the OpenSky API returns 429s, but it might be that my IP address has just been rate limited.
I think the current behavior leads to continuous requests, because `data` is assigned in the loop callback, but `data` is also a dependency of the effect so these changes trigger more requests. I've refactored a bit and this fixes the issue locally, but I'm still blocked by the OpenSky API and can't test with real data.
Aside - Given that it only updates every 60s, maybe it'd be simpler (for purposes of showing a scenegraph example) to make a single request and skip the refresh cycle?
> fix(website): Fix infinite loop in scenegraph example

- docs/api-reference/mapbox/overview.md
Just spent some time figuring out why this didn't work.
As you can see [here](https://github.com/mapbox/mapbox-gl-js/blob/d7652ba8eda70a97809840364beed81bad07930d/src/ui/map.js#L242), the correct property name is `useWebGL2`.
> The correct property name is useWebGL2

- modules/carto/src/index.ts
To avoid a breaking change with v9.1, we'll re-export a few more imports from `@carto/api-client` in the `@deck.gl/carto` package:
- query
- QueryParameters
- CartoAPIError
> fix(carto): Add missing re-exports from API client in v9.1

- modules/carto/package.json
- modules/carto/src/api/fetch-map.ts
- yarn.lock
A followup to #9230, this PR does some internal refactoring of `fetchMap()` to reduce the (repeated) use of optional parameters with defaults imported from `SOURCE_DEFAULTS`, and tries to decouple the file somewhat from the baseSource() implementation. User-facing API is unchanged.
It probably also makes sense to move this function into `@carto/api-client` at some point, but I don't think we're ready to tackle that for v9.1.
> refactor(carto): Refactor fetchMap() for deck.gl v9.1

- modules/mapbox/src/deck-utils.ts
- modules/mapbox/src/mapbox-layer.ts
- modules/mapbox/src/mapbox-overlay.ts
- modules/mapbox/src/resolve-layers.ts
- modules/mapbox/src/types.ts
Closes #9211
Dependency `@types/mapbox-gl` was removed in v9.0 (unintentionally?) by #8204
It wouldn't be compatible with maplibre-gl anyways...
- Remove type dependency on mapbox-gl
> fix(mapbox) Remove type dependency on mapbox-gl

- modules/carto/src/layers/post-process-utils.ts
- modules/carto/src/layers/raster-layer-vertex.glsl.ts
- modules/carto/src/layers/raster-layer.ts
- modules/carto/src/layers/raster-tile-layer.ts
When using a `TileLayer` to render tiles, thin seams can appear between the tiles due to antialiasing at the edge of each tile. To work around this, use the same RTT workflow as used in the `HeatmapTileLayer`, which will render all the tiles into a non-AA texture. This is not a great solution for general layers as it will introduce jagged edges, but in the case of the RasterTileLayer the data is so blocky that it isn't obvious
- Add RTT modifiers to `RasterTileLayer` & `RasterLayer`
- Reorganize order of calculations in shader to remove inter-cell precision artifacts
- Add `'no-overlap'` as we have in other layers
- Improve `RTTModifier` type
> CARTO: Fix seams between tiles in RasterTileLayer

- modules/core/src/lib/deck.ts
Canvas resize events are being responded to by two independent code paths:
- `CanvasContext` with `autoResize: true` sets up resize observer which calls `resize` without the correct `useDevicePixels` setting
- `AnimationLoop` with `autoResizeDrawingBuffer: true` checks canvas size before each render frame with the correct `useDevicePixels` setting
If the user sets `useDevicePixels` to a value that is not `window.devicePixelRatio` the canvas ends up getting resized twice to different dimensions.
- Disable `autoResize` when creating the context
> fix(core): conflicting resize logic when using non-default useDevicePixels

- docs/api-reference/core/widget.md
- docs/api-reference/widgets/overview.md
- modules/main/src/index.ts
- modules/widgets/src/compass-widget.tsx
- modules/widgets/src/fullscreen-widget.tsx
- modules/widgets/src/index.ts
- modules/widgets/src/zoom-widget.tsx
For https://github.com/visgl/deck.gl/pull/9304#discussion_r1890355828
Change prop types to `type`. Interfaces are meant for defining a class interface (with methods to implement) and `type` for defining an object's structure.
- exported widget prop types (as `type`)
- docs
> chore(widgets) props should be types rather than interfaces

- examples/get-started/pure-js/maplibre-globe/README.md
- examples/get-started/pure-js/maplibre-globe/app.js
- examples/get-started/pure-js/maplibre-globe/index.html
- examples/get-started/pure-js/maplibre-globe/package.json
- modules/core/src/viewports/globe-viewport.ts
- modules/core/src/views/globe-view.ts
- modules/core/src/views/map-view.ts
- modules/mapbox/src/deck-utils.ts
- modules/mapbox/src/mapbox-layer.ts
- modules/mapbox/src/mapbox-overlay.ts
- modules/mapbox/src/types.ts
- test/modules/mapbox/fixtures.ts
- test/modules/mapbox/mapbox-layer.spec.ts
- test/modules/mapbox/mapbox-overlay.spec.ts
For #9199
Note: requires #9295 
Tested for overlaid and interleaved modes
- `MapboxOverlay` switches views based on map projection mode
> feat(mapbox): support Maplibre globe projection

- .github/workflows/release.yml
GitHub action’s ubuntu-latest image has switched to 24, which by default blocks puppeteer / chrome test mode from running. Easiest solution for now is to pin CI to ubuntu-22.04
> chore: pin ubuntu CI version to fix release workflow

- bindings/pydeck/docs/CHANGELOG.rst
- bindings/pydeck/docs/index.rst
- bindings/pydeck/docs/layer.rst
- bindings/pydeck/docs/widget.rst
- bindings/pydeck/examples/01 - Introduction.ipynb
- bindings/pydeck/pydeck/bindings/widget.py
- bindings/pydeck/pydeck/frontend_semver.py
- bindings/pydeck/pydeck/io/html.py
- bindings/pydeck/pydeck/io/templates/index.j2
For #9056 
Tested widgets in pydeck with the latest beta, its functional! 
Pointing to the CDN to deck 9.1 will 404 until a production release is made, so let's hold off on the pydeck release until then.
- update pydeck to use deck 9.1
- docs
> chore(pydeck) update pydeck to use deck 9.1 and update documentation

- docs/whats-new.md
https://github.com/visgl/deck.gl/blob/9.1-release/docs/whats-new.md#deckgl-v91
Some links lacked the .md file extension.
> fix broken link in 9.1 release notes

- docs/api-reference/react/overview.md
- docs/api-reference/react/use-widget.md
- docs/whats-new.md
For https://github.com/visgl/deck.gl/issues/9056
Fixes website build by removing not yet published links
> website: remove links to custom-widgets

- .github/dependabot.yml
Configures Dependabot to update github-actions dependencies in groups, rather than opening a PR for each dependency. I've set it to do separate PRs for major versions, and a weekly batch PR for non-major versions, but this isn't a strongly-held preference.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates
Minor formatting changes by Prettier.
> chore(ci): Add dependabot groups for github-actions updates

- .github/ISSUE_TEMPLATE/bug-report.yml
Replaces a CartoLayer reference in the issue template. As of deckgl 9.1, it has been replaced by various more specialized layer types.
> chore: Replace CartoLayer reference in issue template

- modules/core/src/lib/deck-picker.ts
Closes https://github.com/visgl/deck.gl/issues/9410
As the `isPicking` flag was not being passed the `CollisionFilterEffect` destroyed the FBO for the non-pickable layers, leading to the layers to then disappear in the render pass
https://github.com/user-attachments/assets/41527ef6-ecee-4105-854e-9a8745bc3ea7
- Explicitly pass `isPicking = true` when invoking `Effect.preRender` from the deck picker
> CollisionFilterEffect: Explicitly pass isPicking to preRender

- bindings/pydeck/docs/contributing.rst
For #9370 and #9064
As discussed during the [OpenViz meeting on 2025-01-30](https://docs.google.com/presentation/d/1hs4GgKPo7J4P54cuxToqZ7HrYxk8vrHsE9u42ENMIfc/edit#slide=id.g32b27f74c35_1_10), content could be added to clarify how to do local development between both python and Javascript.
- Update `pydeck` contribution docs to provide guidance on local development for `@deck.gl/jupyter-widget` module.  This uses the `PYDECK_DEV_PORT` environment variable for which logic was added in PR #4632
> Add instructions for local development of @deck.gl/jupyter-widget

- bindings/pydeck/pydeck/bindings/deck.py
- bindings/pydeck/pydeck/bindings/json_tools.py
- bindings/pydeck/pydeck/io/html.py
- bindings/pydeck/pydeck/io/templates/index.j2
- bindings/pydeck/pydeck/io/templates/style.j2
- modules/jupyter-widget/src/playground/create-deck.js
For #9370
This is a smaller-scoped fix to propagate Javascript errors so that they are immediately visible in a python notebook.
The intent is to make it easier to iterate on errors or collect information for bugs.
This is a short term fix for issue #9370 until the refactor suggested in #9064 is completed. 
- Add new `onError` handler to determine whether to show a `deck.gl` error in the HTML output or via the browser console
- Optionally hook the [Deck.onError](https://deck.gl/docs/api-reference/core/deck#onerror) handler and the `createDeck` exception handler catch block to call the new `onError` handler.
- Add `show_error` boolean flag to instruct `pydeck.Deck` to display the error immediately instead of logging it to the developer console
NOTE: This does *not* raise a python exception …
> feat: Add show_error flag to display error in cell output

- docs/get-started/learning-resources.md
Minor edit to fix a broken link on the Learning Resources page of the deck.gl docs.
> docs: fix broken link in "Learning Resources"

- docs/api-reference/core/post-process-effect.md
- docs/developer-guide/using-effects.md
luma 9.1 changed the export path for PP effects: https://github.com/visgl/luma.gl/pull/2336
- Update docs to use `@luma.gl/effects`
> docs: postprocess imports from luma.gl/effects

- modules/carto/src/layers/heatmap-tile-layer.ts
9.1 broke palette updating, as the API changed. Fixing in line with [HeatmapLayer](https://github.com/visgl/deck.gl/blob/master/modules/aggregation-layers/src/heatmap-layer/heatmap-layer.ts#L561)
- Use `setTexture2DData`
> CARTO: HeatmapTileLayer fix palette updating

- modules/widgets/src/zoom-widget.tsx
Closes #
- FlyToInterpolator doesn't support orthographic viewports
- This is a quick fix to unbreak
- The ideal solution would presumably be to fix FlyToInterpolator to support more viewports
- Avoid adding FlyToInterpolator if `latitude` is not present in view state.
> fix(widgets): ZoomWidget: Prevent crash when used with OrthographicView

- docs/api-reference/mapbox/mapbox-overlay.md
- modules/mapbox/src/mapbox-layer.ts
- modules/mapbox/src/resolve-layers.ts
In Mapbox v3 `slot` replaces `beforeId`:
https://docs.mapbox.com/mapbox-gl-js/guides/migrate/#layer-slots
- Allow layers in `MapboxOverlay` to supply an optional `slot` prop
> feat(mapbox): support Mapbox v3 Standard style slot

- modules/layers/src/scatterplot-layer/scatterplot-layer-fragment.glsl.ts
- modules/layers/src/scatterplot-layer/scatterplot-layer-uniforms.ts
This PR addresses an issue with the scatterplot layer on certain Snapdragon GPUs. Specifically, when the `filled` property was defined as a boolean, the fragment shader misbehaved and discarded fragments regardless of whether `filled` was true or false. Converting the `filled` uniform to a float and modifying the conditional checks resolves this issue by avoiding a known GPU driver bug.
| As Is(Website Example) | To Be |
|--------|--------|
| ![Screenshot_20250310_220515_Firefox](https://github.com/user-attachments/assets/72ef00ef-f0a7-404f-aaed-7e4e27074ab7) | ![Screenshot_20250310_221321_Firefox](https://github.com/user-attachments/assets/0f6d8309-051e-4c22-b390-a6b1735d2952) |
- **Uniform Update:**  
- Changed the type of `filled` in `scatterplot-layer-uniforms.ts` from `bool` to …
> fix(scatterplot-layer): use numeric uniform for "filled" to avoid GPU driver bug

- modules/carto/src/layers/raster-layer-vertex.glsl.ts
Order of instructions in shader (combined with if branch statement) causes precision issues at high zooms
Before:
https://github.com/user-attachments/assets/badffa95-f0d4-41ef-bc54-80cc88e6fc97
After:
https://github.com/user-attachments/assets/105b6d20-61ff-4ce1-8373-4c7ade57be0b
- Subtract large values from each other before applying small offset to preserve precision
> CARTO: RasterLayer improve shader precision at high zooms

- modules/core/src/lib/attribute/data-column.ts
- modules/core/src/lib/attribute/gl-utils.ts
Closes #
- Colors should be normalized in the shader. It would be good to align WebGL but there are a lot of moving pieces and this unblocks WebGPU.
- Use `unorm8` attributes for colors in WebGPU
> chore: WebGPU plumbing

- modules/core/src/lib/attribute/attribute.ts
Closes #
- WebGPU doesn't support constant attributes. 
- Simply treating constant values as `() => value` will cause buffers to be generated and unblocks us until we can implement more advanced shader generation to handle constants.
-
> fix(chore): Disable constant attributes under WebGPU

- tsconfig.json
As of 9.1.6, `docusaurus` is throwing an error related to the WebGPU shaders recently introduced in 9.1. This attempts to fix the issue by appending a js extension to our compiled JS files, we did with glsl shaders.
```
ERROR in ./node_modules/@deck.gl/core/dist/shaderlib/project/project.js 7:0-45
Module not found: Error: Can't resolve './project.wgsl' in '/Users/chris.gervang/code/hubble.gl/website/node_modules/@deck.gl/core/dist/shaderlib/project'
Did you mean 'project.wgsl.js'?
BREAKING CHANGE: The request './project.wgsl' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in …
```
> fix(core) Append `.js` to WebGPU shaders for script builds

- package.json
- website/package.json
Once Yarn v2+ has been installed locally in a development environment, it comes with Corepack as the [preferred way to install package managers](https://yarnpkg.com/corepack). However, Volta (if installed) silently and globally disables Corepack...
- https://github.com/nodejs/corepack/issues/507#issuecomment-2625366567
- https://github.com/volta-cli/volta/issues/987
... which has caused some confusing bugs when the wrong version of Yarn is used, installing a different dependency chain locally vs. CI, and then we get different behaviors in each. To avoid that, I have to disable Volta when working in projects that use Corepack, and to re-enable Volta when working in deck.gl or luma.gl.
Would others be OK with including the `package.json#packageManager` field here, and (if so) in other …
> chore(yarn): Add package.json#packageManager field

- modules/core/src/passes/layers-pass.ts
Closes https://github.com/visgl/deck.gl/issues/9536
Caused by https://github.com/visgl/deck.gl/pull/9483/files#diff-e6bb172fd86c7d509a8ed078b42f5f10eb56d84a5873e7407178bc03beab5923R477-R481
As per comment, luma should backfill these for WebGPU
I've tested by rebuilding the website locally and the Maplibre globe example now works as expected
- Revert to only passing 4 values for glViewport
> Revert #9483 using 6 coordinates in glViewport

- examples/get-started/pure-js/widgets/app.ts
- modules/widgets/src/info-widget.tsx
Closes #
- Three use cases for the `_InfoWidget`
- Hover to show info tooltip
- Click to show an anchored info box
- Static info (app could add multiple anchored info boxes) 
The static use case requires some row lookup which I didn't handle in this PR.
- New mode prop
- Align the callback with getTooltip (we'll probably settle on a different name)
> [feat] Add hover support to InfoWidget

- examples/get-started/pure-js/widgets/app.ts
- modules/widgets/src/components.tsx
- modules/widgets/src/fullscreen-widget.tsx
- modules/widgets/src/index.ts
- modules/widgets/src/splitter-widget.tsx
Closes #
- I was thinking to myself, wouldn't it be nice to have a widget that lets users resize views?
- New experimental SplitterWidget
- Cleanup of widget code
- Possibility to auto detect split from views?
- Possibility to include the view updates in the widget so the app doesn't have to.
- core: To make this work well in declarative setups, we might want to consider adding`DeckProps.initialViews`.
- core: Might be nice to have a `units: 'percent'` or `units: 'ratio'` type prop on views, so percentage views can be specified numerically without the need to generate strings such as "50%".
-
> [feat]: SplitterWidget

- modules/carto/src/layers/raster-tile-layer.ts
RasterTileLayer requires specific properties (metadata) passed to loader.
Passing custom `loadOptions` as props, overrides `loadOptions.cartoRasterTile.metadata` and layer loader always fail to parse tile.
- Carto: RasterTileLayer fix support  for external loadOptions
> fix(carto): RasterTileLayer fix to support external loadOptions

- modules/carto/src/layers/heatmap-tile-layer.ts
On first load, the max density is incorrect
- Use the loaded, but invisible tiles to get a value for `maxDensity` before the layer is made visible and rendered
> CARTO: Fallback to hidden tiles for maxDensity

- modules/carto/src/layers/cluster-tile-layer.ts
- modules/carto/src/layers/h3-tile-layer.ts
- modules/carto/src/layers/quadbin-tile-layer.ts
- modules/carto/src/layers/raster-tile-layer.ts
- modules/carto/src/layers/utils.ts
- modules/carto/src/layers/vector-tile-layer.ts
- modules/carto/test/layers/utils.spec.ts
In a number of places the `loadOptions` prop was mutated, which could lead to bugs when multiple `Layer` instances shared a `loadOptions` object
- Replace `injectAccessToken` with more generic `mergeLoadOptions`
- Update Layers to use new helper
- Tests
> CARTO: Do not mutate passed in loadOptions objects

- docs/api-reference/core/view.md
- docs/whats-new.md
- modules/core/src/views/view.ts
- test/modules/core/views/view.spec.ts
Closes #
- Address comment in the filter views PR: https://github.com/visgl/deck.gl/pull/9572#discussion_r2037935307
- View class
- View tests
- View docs
- What's new
> feat(core): Add View.clone() method

- modules/widgets/src/geolocate-widget.tsx
- test/apps/widgets-example-9.2/app.ts
Closes #
- The fact that we hadn't yet implemented geocoding in the GeolocateWidget was resulting in some confusion around the name.
- Implement support for 3 geocoding services (all require apiKeys). coordinate support remains but now only as a fallback option until a proper geocoder and key are configured.
> feat(widget): Add geocoder support to GeolocateWidget

- modules/mapbox/src/deck-utils.ts
- test/modules/mapbox/mapbox-overlay.spec.ts
Hey all, this is my first PR! I tried my best to follow the existing style/conventions, and I also added a regression test for this fix (could probably use some guidance on this; I'm not super sure this is the best approach).
Overall a pretty simple fix. The gist is that in `MapboxOverlay` we should also use the provided `layerFilter` prop (if it exists) when rendering the "mapbox layers", because in the interleaved case, these layers will also include user-provided layers.
Closes #9300 
- Makes sure `layerFilter` is called when rendering `MapboxOverlay` in interleaved mode
> fix: filter layers in mapbox overlay, interleaved mode

- modules/layers/src/text-layer/text-layer.ts
Closes #
- The TextLayer warning generates noise on our logs. 
- Since it is a "log.warn()" it generates a full stack trace.
- Proposal: keep it but as a debug message.
- This was a v8.9 change message, so seems reasonable to make the change in 9.2
- `log.warn(...)()` => `log.once(1, ...)()`
> chore(layers): Change warning to debug message

- docs/api-reference/widgets/gimbal-widget.md
- docs/api-reference/widgets/overview.md
- modules/widgets/src/gimbal-widget.tsx
- modules/widgets/src/index.ts
- test/apps/widgets-infovis/app.ts
- test/apps/widgets-infovis/index.html
- test/apps/widgets-infovis/package.json
Closes #
- Starting to focus on non-geospatial widgets which is my primary motivation for 9.2.
- I am trying to different approach to handling view updates in widgets.
- The approach currently in use in other widgets is based on scraping the viewports and trying to extract some view state information from them to then be used to update view states.
- Working with directly with view states seems more natural / less hacky.
- The documentation references the widget example to illustrate the widgets. However, this won't work at the moment for non-geospatial widgets.
- There is currently a test app that could be move to examples
- Alternatively we could make the existing example more complex with a switcher between geospatial and non-geospatial.
- Another possible option is to have two …
> feat(widgets): New GimbalWidget

- modules/carto/src/api/fetch-map.ts
- modules/carto/src/constants.ts
In v9.1, `@deck.gl/carto` fetchMap() fails to load layers depending on a default value of the `aggregationExp` property, required for H3 and Quadbin table or query sources. The issue does not occur on `master` branch, or in the v9.2 alpha, but I'm currently seeing another issue (link: TBD) in the v9.2 alpha and would like to backport the fix for v9.1 in the meantime.
- carto: fetchMap() should apply default aggregationExp
* **PR #9668** 👈
This tree was auto-generated by [Charcoal](https://github.com/danerwilliams/charcoal)
> fix(carto): Assign default aggregationExp in fetchMap()

- modules/carto/src/layers/h3-tileset-2d.ts
- test/modules/carto/layers/h3-tileset-2d.spec.ts
The child cells of a H3 tile do not exactly fit into the bounds of the tile.
This leads to picking being broken on the edges of H3 tiles as the picking system culls a tile before it can be rendering for picking
- Pad H3 tiles by appropriate amount
- Test update
> fix(CARTO): H3 tile bounding box includes edge children

- examples/website/point-cloud/app.tsx
- examples/website/scatterplot/app.tsx
- examples/website/scatterplot/index.html
- examples/website/scatterplot/package.json
- modules/core/src/lib/deck.ts
- modules/layers/src/line-layer/line-layer.ts
- modules/layers/src/scatterplot-layer/scatterplot-layer.ts
- test/apps/webgpu-line/app.tsx
- test/apps/webgpu-scatterplot/app.tsx
- test/apps/webgpu - yarn start-local
- Partial start on a WebGPU scatterplot layer
- Shader modules, especially project, need to be implemented, some minimal stubs have been added to ScatterplotLayer to enable rendering
- Add examples/website/webgpu
- Add webgpuAdapter
- Add WGSL source for scatterplot layer
- Disable hooks for WGSL
- Minor fixes
- Keep following shader module dependencies and port code / resolve issues.
> feat(layers): Port ScatterplotLayer to WebGPU / WGSL

- examples/website/point-cloud/package.json
- website/src/examples/point-cloud-layer.js
- website/src/examples/scatterplot-layer.js
Closes #
@Kaapp showed the path with the Pointcloud example!
(Note: The map is there but hidden - We need to adopt premultiplied alpha to enable WebGPU canvas transparency)
-
> website: Add WebGPU scatterplot example

- modules/core/src/lib/deck-picker.ts
Closes #
Add new `pick...Async()` methods to the deck picker.
- in WebGPU, all readback is asynchronous.
- this means that we won't be ble to support the current sync picking methods in the Deck API.
- To avoid breaking existing apps, we keep the old sync picking functions and simply mark them as `@deprecated` in TSDoc
This PR doesn't actually implement async picking. It just introduces the async picking API and path. This allows the rest of deck code base to start preparing, and will make future picking diffs cleaner.
- Add new `pick...Async()` methods to the deck picker.
> feat(core): Add async DeckPicker methods

- examples/website/heatmap/app.tsx
- modules/aggregation-layers/src/heatmap-layer/heatmap-layer.ts
- test/modules/aggregation-layers/heatmap-layer/heatmap-layer.spec.ts
- test/modules/aggregation-layers/index.ts
Fix needed for https://github.com/geoarrow/deck.gl-layers/pull/133
The `HeatmapLayer` does not currently work when data is passed in binary format (as needed by lonboard) as the buffer layout on the weights transform is not correct
Example to repro, included in this PR: https://github.com/visgl/deck.gl/commit/887aefe1e9d7d9e0f84d1a12dd71ffcd4928f8a2
- Fix bug (by recreating `weightsTransform` whenever the `data` prop is changed
- Remove use of `setTexture2DData(...)` as luma no longer allows this
- Reinstate heatmap tests
- Add new test to verify binary data buffer layouts are now correct
> fix: HeatmapLayer working with binary data

- website/static/events/seattle-summit-2025/index.html
Swapped session times and details for Chris Kapp and Chris Gervang/Adam Krebs, updated speaker images, titles, and company logos. Added a break & networking divider at 14:00 and adjusted subsequent session times to reflect the new schedule.
> Update Seattle Summit 2025 agenda and speaker details

- modules/core/src/lib/widget-manager.ts
- modules/core/src/lib/widget.ts
From v9.1 to v9.2, `Widget` changed from a TypeScript interface to an abstract class. A breaking change is introduced that if a widget implementation returns a HTML element from `onAdd`, it is now ignored. The `ContextMenuWidget` on master is broken because of this. I also think it's unnecessary to break existing custom widgets from 9.1.
This PR reverts the breaking change by only calling the new `onCreateRootElement` method if `onAdd` does not return anything (as in most classes in the widgets module). A quick audit shows no existing `onAdd` methods expect `rootElement` to exist. Tested the change with `test/apps/widgets-9.2`.
- Change `onCreateRootElement` from public API to protected utility
- If Widget subclass returns an element from `onAdd`, use the element as `widget.rootElement` …
> Avoid 9.2 breaking change in Widget base class
